Opentrons/opentrons

- protocol-designer/src/components/KnowledgeBaseLink/index.js
- protocol-designer/src/components/StepEditForm/FormAlerts.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/warnings.js
Closes #1882
See changelog
-warning/error 'title' always goes to 'title' of Alert
-instead of 'message' string in form warnings/alerts, there's an optional 'body' which is a React.Node (this matches how TimelineAlerts handles)
-add link to knowledgebase for BELOW_MIN_DISPOSAL_VOLUME warning
-create KnowledgeBaseLink component as a place to organize links to support docs
- do a transfer from 1 well to 2 wells or some other mismatched combo. You should see the error as specified in #1882.
- in a Distribute, set Disposal Volume to something lower than 20% of pipette max vol. You should see a link in the Alert body. Clicking the link should open the 'distribute' page of our knowledgebase in a new tab/window
Does this seem like a half-decent way to organize knowledgebase links for PD for now?
> feat(protocol-designer): make form warnings & errors match TimelineAlerts

- components/src/deck/Deck.css
- components/src/interaction-enhancers/clickOutside.js
- components/src/interaction-enhancers/index.js
- protocol-designer/src/components/LabwareDropdown.js
- protocol-designer/src/components/labware/DisabledSelectSlotOverlay.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/components/labware/NameThisLabwareOverlay.js
- protocol-designer/src/components/labware/labware.css
- protocol-designer/src/containers/ConnectedDeckSetup.js
- protocol-designer/src/containers/Deck.css
- protocol-designer/src/containers/LabwareContainer.js
- protocol-designer/src/labware-ingred/__tests__/containers.test.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/load-file/reducers.js
where you're currently given the option to copy labware, allow users to move labware with expected
swapping behavior. Alter deck component to assume less about bounding element
Closes #1908
> feat(protocol-designer): implement move labware in place of copy

- app/src/pages/Calibrate/Labware.js
- protocol-designer/src/components/KnowledgeBaseLink/index.js
While reviewing the lovely deckmap style refactor branch, I noticed the ReviewDeck modal did not render when modules flag was enabled but no modules were required by the protocol. This is tiny temporary fix. In the future we will combine the ReviewDeck and ReviewModules modals.
Also, with the merge of the new lint rules, KnowlegeBaseLink needed `rel="noopener noreferrer"` this PR adds that so that future builds wont fail.
- fix(app): Check if modulesRequired when displaying review modals
**Run app normally** 
`make dev` 
**Run app with modules enabled**
`OT_APP_MODULES=1 make dev` (with no modules required by protocol)
**Mock session modules** 
uncomment lines 345-351 in `app/src/robot/api-client/client.js` 
**Mock modules API response** 
comment out line 77 and uncomment lines 79-110 in …
> fix(app): Check if modulesRequired when displaying review modals

- protocol-designer/src/components/IngredientsList.css
- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/StepDescription.css
- protocol-designer/src/components/lists/PDListItem.js
- protocol-designer/src/components/lists/PDTitledList.js
- protocol-designer/src/components/lists/index.js
- protocol-designer/src/components/lists/styles.css
- protocol-designer/src/components/steplist/AspirateDispenseHeader.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/components/steplist/SubstepRow.js
I talked with Katie, Morgan, & Pantea and derived:
1. `TitledList` is working pretty good, Run App just doesn't use a lot of its options. It doesn't seem like it needs any refactor - simply don't use some props, and it will behave very vanilla. However, within PD the same styles are always applied to it (outer drop shadow, different margin), so this PR wraps it in some common-across-PD styles in `PDTitledList`.
2. `ListItem` isn't working really for anybody. It doesn't seem to actually be a reusable component. There's a single place in Run App that it's used without additional styles. Everywhere else, it's pretty much overridden. In PD, ListItem-like things (ie any `<li>`s inside `TitledList`s) seem like they are always tabular data, and it seems OK to make the PD version `flex` by …
> refactor(protocol-designer): factor out PDTitledList and PDListItem

- api/opentrons/tools/gantry_test.py
- api/opentrons/tools/overnight_test.py
- api/opentrons/tools/z_stage_test.py
<!--
Set the speed to 8mm/sec while testing for skipped steps during QC. This change in speed is to avoid a resonance on the Z axes, which occurs at 10mm/sec
> perf(api): Slow axis-testing speed to 8mm/sec during QC

- components/src/interaction-enhancers/IntervalWrapper.js
- components/src/interaction-enhancers/IntervalWrapper.md
- components/src/interaction-enhancers/index.js
This PR adds `IntervalWrapper` to interaction enhancers. A follow up PR will be a refactor to replace all `RefreshCards` in the app with `Cards` wrapped in `IntervalWrappers`.
- feat(comp): Add IntervalWrapper to interaction enhancers
Standard review.
> feat(comp): Add IntervalWrapper to interaction enhancers

- protocol-designer/package.json
- protocol-designer/src/components/StepEditForm/MixForm.js
- protocol-designer/src/components/StepEditForm/TransferLikeForm.js
- protocol-designer/src/localization/en/index.js
- protocol-designer/src/localization/en/tooltip.json
- protocol-designer/src/localization/index.js
- yarn.lock
*Overview*
Add the i18next library (https://www.i18next.com/overview/api) to help organize our copy. 
Start off by moving tooltip copy into translations json file.
>  feat(protocol-designer): add i18next and start with tooltips

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/tools/gantry_test.py
- api/tests/opentrons/drivers/test_driver.py
Fix a bug involving pushing/popping gantry speeds, causing one the the QC scripts to move very slowly after 1 cycle. This PR avoids the issue in the QC script by explicitly setting the speed there. But then also we address the underlying problem in the driver, which simply involved replacing any calls to `self.push_speed()` to be instead `self.push_axis_max_speed()`
The bug happens in the following scenario:
```python
try:
driver.push_speed()  # save the current combined speed (400 mm/sec)
driver.set_speed(10)  # set to a slower speed
driver.move({'X': 430})  # hits the switch, forcing a home
except SmoothieError:
driver.pop_speed()  # ERROR OCCURS HERE, b/c previously "pushed" speed was overwritten
```
Here is the sequence of the events in the driver that cause this:
1. The X axis hits …
>  fix(api): maintain speed state after collision recovery

- api/opentrons/config/containers/default-containers.json
- api/opentrons/data_storage/database_migration.py
Closes #1931 and #1849 . 
-  Adds the origin offset to all of the coordinates in the container
- Changes origin location to correct corner and then re-calculates all well locations based off of new origin + L/W of the container [NOTE: This does not work for containers larger than a robot slot size]
Was tested on young-🌔 but please review on your own robot if possible.
> fix (api): Fix the database migration script geometry logic

- api/opentrons/config/containers/default-containers.json
- api/opentrons/containers/placeable.py
- api/opentrons/data_storage/database.py
- api/opentrons/drivers/temp_deck/driver.py
- api/opentrons/modules/__init__.py
- api/tests/opentrons/labware/test_modules.py
This PR adds the TempDeck api object which is implemented similar to the MagDeck api object. Closes #1648 
A TempDeck will be loaded with ```modules.load('tempdeck', <slot number>)``` 
Available TempDeck methods are:
1. ```connect()```
2. ```set_temperature(celsius)```
3. ```disengage()```
4. ```disconnect()```
And properties are:
1. ```device_info```: returns a dict of ```{ 'serial': '', 'model':'', 'version':'' }```
2. ```temperature```: gives current TempDeck temperature
3. ```target```: gives target temperature if set or None
4. ```status```: returns a string- ```heating```, ```cooling```, ```disengaged``` or ```holding at target```
- Added ```TempDeck``` modules class
- Added a driver method to determine status based on current and target temperatures
- Fixed a problem with the …
> feat(api): Add tempdeck api object

- components/src/alerts/alerts.css
- components/src/forms/forms.css
- components/src/styles/colors.css
Closes #1936
- rename --c-bg-warning to --c-warning-light to match zeplin
- rename --c-warningdark to --c-warning-dark for consistency
- restyle caption and error caption of InputField
:baby_chick:
> feat(components): restyle field caption

- protocol-designer/src/components/steplist/TimelineAlerts.js
Closes #1975
Was: `For the first step in a protocol the "change tip" setting must be set to always or once.`
Now: `The first time a pipette is used in a protocol the "change tip" setting must be set to always or once.`
:bulb:
> feat(protocol-designer): update copy for 'no tip on pipette' error

- components/src/forms/InputField.js
- protocol-designer/src/components/IngredientPropertiesForm.js
Closes #1835
- for ingredient selection modal, the volume field contains caption "max {volume}", unless it's showing an error
:alembic:
> feat(protocol-designer): add max volume to ingred selection modal volume field

- protocol-designer/README.md
- protocol-designer/package.json
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/webpack.config.js
- yarn.lock
No ticket for this! For PD closed beta, we'll ask users to send us their files with their feedback. It's hard to trace down bugs if we don't know the version. Having PD's version saved in the file will also help with backwards compatibility issues (even if that's just saying, "this old file is no longer supported"). 
Since PD is kinda stuck with the monorepo version until we figure something else out, it can't really follow semver itself without some monorepo versioning changes. So for now, this PR just uses https://github.com/tvdstaaij/node-git-describe defaults, with commit distance and hash from the last git tag (if different from the tag). It's running `git describe --dirty`.
I figured we could keep the `-dirty` suffix because it might disambiguate cases where a developer saves a file …
> feat(protocol-designer): save version in PD file with git-describe

- api/opentrons/protocols/__init__.py
Closes #1997 -- oops...
- adds "touch-tip" command support for JSON protocols
Code review
I tested on Sunset, if you feel like it you can test too. Requires `make push`
Latest PD artifact https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/edge/index.html should work fine with this for a test protocol. Or I'll Slack you a .json protocol with some "touch-tip" commands for testing this if you want.
> fix(api): support touch-tip for JSON protocols

- api/opentrons/config/modules/95-opentrons-modules.rules
- api/opentrons/modules/__init__.py
This PR changes the way a module node is created in /dev
All modules will be symlinked to `/dev/modules/` with a naming standard of `/ttyN_tempdeck`, `/ttyN_magdeck`, etc where N will be the number corresponding to the original port name assigned by the os. So, a magdeck at path `/dev/ttyACM1` will have a symlink at `/dev/modules/tty1_magdeck`
- Changed udev rules file in `/config/modules`
- Made appropriate changes to modules api objects to switch to above change
> fix(config): change udev rule to include multiple modules

- protocol-designer/src/components/StepEditForm/TransferLikeForm.js
- protocol-designer/src/form-types.js
- protocol-designer/src/steplist/fieldLevel/types.js
- protocol-designer/src/steplist/formProcessing.js
Closes #1689
Command creators & tests already are set up for this! Just needed to hook up the form.
- Add "drop tip" to "Dispense" section of transfer-like forms
Check that this is working in transfer/distribute/consolidate -- inspect the JSON for drop-tip commands after dispense commands.
> feat(protocol-designer): add 'drop tip' to 'dispense' section of form

- protocol-designer/src/components/StepEditForm/MixForm.js
- protocol-designer/src/components/StepEditForm/TransferLikeForm.js
- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/constants.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formProcessing.js
Closes #1933 and addresses part of #1934 
- rename change tip options
- fix bug with forms defaulting to blank change tip option
- make sure change tip options match #1933 
- for all step types, Change Tip should default to "Always" (the first option), and never default to being blank (as was previous behavior for everything but maybe Distribute)
> feat(protocol-designer): rename change tip options

- protocol-designer/src/components/IngredientPropertiesForm.css
- protocol-designer/src/components/IngredientPropertiesForm.js
- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/WellToolTip.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/__tests__/selectors.test.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/top-selectors/well-contents/__tests__/wellContentsAllLabware.test.js
- protocol-designer/src/utils/index.js
- protocol-designer/src/utils/test/sortWells.test.js
- protocol-designer/src/well-selection/selectors.js
##overview
Closes #1294 -- fixes IngredientItem (items in Ingredient List) text, for "serialized" ingredients. Was "Sample 1", "Sample 2" and now uses the ingredient name instead of "Sample"
Also remove old scars code for `serializeName` which went away a month or 2 ago
- factor utils into a dir with index.js
- write tests for sortWells util
- use sortWells where missing
- remove vestigal serializedName code
> fix(protocol-designer): fix serialized name in ingred list

- app-shell/lib/config.js
- app/src/analytics/index.js
- app/src/config/index.js
- app/src/index.js
- app/src/support.js
This PR updates the intercom configuration to attach a unique user ID (generated on first open of the app) that is stored on the filesystem to persist between app openings and re-installs. This _should_ allow users to keep their conversations going.
It also lays a little bit of groundwork for users to be able to input their name and email for support purposes.
Closes #1999
- feat(app): Add persistent unique user ID to intercom data 
I separated support from analytics to make sure we don't leak data between the too and keep our modules (the code kind) more focused.
- Remember to set `OT_APP_MIXPANEL_ID`
- Remember to set `OT_APP_INTERCOM_ID`
- Ask me for a testing environment ID to avoid confusing our support folks
> feat(app): Add persistent unique user ID to intercom data

- app-shell/dev-app-update.yml
- app-shell/lib/config.js
- app-shell/lib/update.js
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/AppSettings/index.js
- app/src/components/controls/LabeledButton.js
- app/src/components/controls/LabeledControl.js
- app/src/components/controls/LabeledSelect.js
- app/src/components/controls/LabeledToggle.js
- app/src/components/controls/index.js
- app/src/components/controls/styles.css
- app/src/config/index.js
This PR also serving as the feature request ticket.
The support team is having trouble keeping track of which users are on beta and how best to support users who are encountering bugs that are present in "stable" but may have been fixed in "beta". This PR adds an option to the app's advanced settings to allow a user to switch between update channels on the fly using the app's existing self-update mechanisms so the support team doesn't need to wrangle a bunch of links all the time
- feat(app): Add update channel selector to advanced settings 
1. Open the app
2. Go to App Settings
3. Change the release channel and notice how the update button state changes
4. Download a prod build from Slack and ensure the updates (and downgrades) actually work
- On mac, it probably won't work because the …
> feat(app): Add update channel selector to advanced settings

- api/opentrons/modules/__init__.py
This is just a follow-up addition to the module.load changes from the set of changes to the Module API objects and their interface to the robot.  The proper instance of placeable was only being attached to the module object instance when the robot was simulating.
In a quick test run on @sanni-t 's robot, this was clearly contributing to the improper pipette positioning that we've been encountering on protocols that include modules.  This doesn't necessarily solve the whole problem, but I figured, as we're still troubleshooting, we might as well eliminate any weird behavior that was just associated with this omission.
>  feat(api): bind labware instance to module on load when not simulating

- Dockerfile
Add openjdk8 to the Dockerfile so that we or hacker users can write and run jvm-based software on the robot.
- Add openjdk8 to Dockerfile
Tested on :moon: :moon:
> feat(compute): Add openjdk8 to container

- api/opentrons/config/__init__.py
- api/opentrons/data_storage/labware_definitions.py
- api/opentrons/instruments/instrument.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/server/main.py
Sometimes the thumb drive where OT2 stores config data is mounted read-only (cause not yet known). When this happens, the server sometimes tries to write data or make directories on the thumb drive, and raises an unhandled exception that causes the server to fail to start. This PR adds exception handling around those write points to allow the server to boot and read previously written configs even if the mount is read-only.
Closes #1903
- handle read-only thumb drive mount on OT2
Needs to be tested on a robot.
> feat(api): Handle read-only thumb drive mount on OT2

- api/opentrons/server/main.py
- api/tests/opentrons/server/test_logs_endpoints.py
The logs endpoint did not take into account creating empty log files if they did not exist. This created weird behavior on front-end side where a user would be prompted to save a file, but nothing actually saved. Closes #2040 .
- Add empty files if either api or serial log(s) do not exist.
@btmorr did I do this in the right place?
> refactor(api): Generate empty log files if not found

- Makefile
- app-shell/.babelrc
- app-shell/Makefile
- app-shell/package.json
- app-shell/src/__mocks__/config.js
- app-shell/src/__tests__/discovery.test.js
- app-shell/src/config.js
- app-shell/src/discovery.js
- app-shell/src/main.js
- app-shell/src/robot-logs.js
- app/Makefile
- app/src/discovery/__tests__/actions.test.js
- app/src/discovery/index.js
- app/src/discovery/types.js
- app/src/index.js
- app/src/reducer.js
- app/src/robot/api-client/client.js
- app/src/robot/test/api-client-discovery.test.js
- app/src/robot/types.js
- app/src/types.js
- discovery-client/.babelrc
- discovery-client/Makefile
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/index.js
- package.json
- scripts/travis-install.sh
- yarn.lock
This PR is part 1 of a 2 part change:
- #2036: Incorporate discovery-client into app-shell behind flag (this one)
- #2045: Move discovery / optionally enable discovery-client (2 of 2)
This PR pulls the `DiscoveryClient` into the app-shell enough to dispatch redux actions when the client finds / updates robots. It **does not** do anything with those actions nor drive any UI from them just yet.
Work is for #990 and #1964
- refactor(app): Incorporate discovery-client into app-shell behind flag
If you're gonna run this from your dev environment (rather than a Slack build), make sure your environment is good:
0. `yarn` (or `make install` if you're feeling it)
1. `make -C discovery-client` to build the non-babel DiscoveryClient for the app-shell
Then, do a normal `make -C app dev` to make sure …
> refactor(app): Incorporate discovery-client into app-shell behind flag (1 of 2)

- app/src/analytics/__tests__/make-event.test.js
- app/src/analytics/make-event.js
- app/src/components/ConnectPanel/index.js
- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/config/index.js
- app/src/discovery/__tests__/actions.test.js
- app/src/discovery/__tests__/reducer.test.js
- app/src/discovery/__tests__/selectors.test.js
- app/src/discovery/index.js
- app/src/health-check/__tests__/health-check.test.js
- app/src/health-check/index.js
- app/src/http-api-client/__mocks__/health.js
- app/src/index.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/api-client/discovery.js
- app/src/robot/reducer/connection.js
- app/src/robot/selectors.js
- app/src/robot/test/api-client-discovery.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/connection-reducer.test.js
- app/src/robot/test/selectors.test.js
This PR is part 2 of a 2 part change:
- #2036: Incorporate discovery-client into app-shell behind flag (1 of 2)
- #2045: Move discovery / optionally enable discovery-client (this one)
It continues the work in 2036 by moving the app's discovery state out of the giant `robot` state subtree and into its own top-level `discovery` subtree. It also wires up the app to the new `DiscoveryClient` + `app-shell/discovery` module.
With this PR, the discovery refactor reaches feature parity with the existing system except for IPv6 wired robots. Remaining planned work:
- Support "legacy" (IPv6) wired robots (hit parity)
- Wire-up robot list persistence across boots
- Add UI for unhealthy but known robots
- Tweak UI for single robot item that is connected over ethernet but is also reachable on WiFi
- …
> refactor(app): Move discovery / optionally enable discovery-client (2 of 2)

- CONTRIBUTING.md
- Makefile
The install target in the root makefile installs pipenv, and was
therefore not using pipenv. Instead, it calls python directly, which is
mostly fine unless you have a default-set-up Mac, which has python
invoking the system's python2. Now, you can override the INSTALL_PYTHON
env var (for instance, by invoking make like `INSTALL_PYTHON=python3
make install`) to select the correct python.
- Add method to override python used to install pipenv in `make install`
> build(make): Add method to override python on which to install pipenv

- app-shell/README.md
@Laura-Danielle alerted me to the fact that I'd let the `app-shell`'s configuration documentation get out of date. This PR updates `app-shell/README.md` with all config options that were not yet documented.
- docs(app-shell): Add missing configuration descriptions to README 
Please check for correctness of descriptions + typos and spelling please! I threw everyone on this review just to make sure you're all aware that this is where documentation for these options live. I'll merge once I have two or three 👍's.
> docs(app-shell): Add missing configuration descriptions to README

- .gitignore
- api/MANIFEST.in
- api/Makefile
- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/instruments/pipette_config.py
- api/opentrons/robot/robot.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/server/endpoints/control.py
- api/setup.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/server/test_control_endpoints.py
- shared-data/robot-data/pipette-config.json
This PR is also acting as a ticket. Pipette configuration data is duplicated in several places in both data and code, and the config loading system is unnecessarily complex. 
This PR will consolidate pipette configuration to only use the version from shared-data, and update multi-channel pick up currents based on test data from @Carlos-fernandez. 
- Bundle pipette-config.json from shared-data into the api wheel
- Use bundled pipette-config.json for pipette configs (no other copies of data)
- Update multi-channel pick up current values based on test data
Tested on 🌔 🌔 --loads correctly with different pipettes (p300_multi_v1 and p300_single_v1).  @Carlos-fernandez please verify the new current values.
> feat(api): Consolidate pipette configuration

- app-shell/Makefile
- app-shell/__mocks__/electron-store.js
- app-shell/src/__tests__/discovery.test.js
- app-shell/src/config.js
- app-shell/src/discovery.js
- app/scripts/advertise-local-api.js
- app/src/config/index.js
- app/src/discovery/__tests__/reducer.test.js
- app/src/discovery/index.js
- app/src/index.js
- app/src/robot/selectors.js
- app/src/shell/index.js
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/index.js
This PR adds robot persistence to file to the app and wires up the necessary state. It also includes some tweaks to various values and configurations based on how discovery behaves in the real world.
- feat(app): Persist known robots to file-system when using new discovery
Try this out on your machine!
0. `make -C discovery-client` (Re-build discovery client)
1. `make -C app dev OT_APP_DISCOVERY__ENABLED=1`
Known issues:
- RPC client and health-check module **do not** handle USB disconnections gracefully when RPC is connected
- This may be a blocker for actual release of new discovery
- For now though its enough for me to keep it behind the feature flag
> feat(app): Persist known robots to file-system when using new discovery

- app/src/components/App.js
- app/src/components/AppSettings/AppUpdateModal.js
- app/src/components/CalibrateDeck/NoPipetteModal.js
- app/src/components/ChangePipette/ExitAlertModal.js
- app/src/components/ClearDeckAlertModal/index.js
- app/src/components/ConfirmTipProbeModal/index.js
- app/src/components/LostConnectionAlert/index.js
- app/src/components/RobotSettings/ConnectAlertModal.js
- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/components/analytics-settings/AnalyticsSettingsModal.js
- app/src/components/modals/ErrorModal.js
- app/src/components/portal/index.js
This PR wraps all `AlertModal`s in a `Portal` to ensure modals are appended to the DOM within the PageWrapper of App.js. This fixes the weird scroll behavior seen in the Wifi Connect modals and should avoid any weirdness when implementing ResetRobotModal. I also too the liberty of adding the alertOverlay boolean to all instances of alertModals in the app.
- refactor(app): Render AlertModals via portal
Please check that all AlertModals render correctly. This PR did not affect Wizards/ModalPages.
> refactor(app): Render AlertModals via portal

- app/src/support.js
This PR functions as a fix for an intercom throttling problem. Calling `intercom('update')` on every route change results in us far surpassing our 20 calls per 30 minutes rule.
This PR addresses the first checkbox of #2019. On robot connect, send the robot name to intercom. This is code correct but will not function properly until the fix above clears out our throttling.
- fix(app): Remove intercom update on route change
- feat(app): Add robot name to intercom on connect
Standard review. 🎙
> feat(app): Add robot name to intercom on connect

- update-server/otupdate/bootstrap.py
- update-server/otupdate/endpoints.py
- update-server/tests/test_bootstrap_fns.py
- update-server/tests/test_server_boot.py
At least on a mac, on zsh, (this issue may be different depending on system and shell because of the
use of shell=True when invoking the server to selftest) the update server self test picks up the
code in the source directory rather than the module to self test. This breaks the unit tests. By
explicitly setting the cwd of the subshell used for the server under test to the root of the venv,
it all works. 
Specifically, this fixes an issue where the unit test checking the ability of the selftest to actually discover problems failed because it was implicitly running the main module.
- Add plumbing to retrieve the venv root from otupdate.bootstrap.create_virtual_environment and pass it down all the way to otupdate.bootstrap._start_server
- Change otupdate.bootstrap._start_server to set the …
> fix(update-server): Set the cwd to the venv during an otupdate selftest

- api/opentrons/server/rpc.py
- api/tests/opentrons/server/test_server.py
- app/src/components/LostConnectionAlert/index.js
- app/src/health-check/__tests__/health-check.test.js
- app/src/health-check/index.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/connection.js
- app/src/robot/selectors.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/connection-reducer.test.js
- app/src/rpc/client.js
- app/src/rpc/message-types.js
This PR adds opt-in ping/pong monitoring to the RPC websocket. It also improves/adds WebSocket closure handling to surface socket closure to the UI more reliably.
Closes #2052
- feat(app,api): Add opt-in ping/pong monitoring to RPC websocket 
Checking on the currently connected robot via polling `GET /health` has proven unreliable (socket can fail even when the health endpoint is fine) and is kind of a mess in terms of app state. Also, now that the app can combine multiple IP addresses into one robot (if `$OT_APP_DISCOVERY__ENABLED` is set), **the existing health-check implementation doesn't know what to do if the currently connected IP goes down but the robot is still accessible via another IP**. For the purposes of switching to new discovery by default, this is blocking.
Rather than …
> feat(app,api): Add opt-in ping/pong monitoring to RPC websocket

- app-shell/src/discovery.js
- discovery-client/.npmignore
- discovery-client/Makefile
- discovery-client/README.md
- discovery-client/bin/discovery-ssh
- discovery-client/package.json
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/cli.js
- discovery-client/src/index.js
- discovery-client/src/poller.js
- discovery-client/src/service.js
- discovery-client/src/types.js
- flow-typed/npm/escape-string-regexp_v1.x.x.js
- flow-typed/npm/mdns-js_v1.0.x.js
- flow-typed/npm/to-regex_v3.0.x.js
In support of the switch to IPv4, this PR adds a couple commands to the `discovery-client` CLI:
- `discovery find [name] [options]` - Find the IP address of a single robot, optionally by name
- `discovery-ssh [name] [options]` - Bash script to call `discovery find` and then SSH into the found robot
- feat(discovery-client): Add CLI commands to find and SSH into a robot
- `discovery find [name] [options]`
- `discovery-ssh [name] [options]`
- How should we deploy this? I'm thinking `npm` might actually be a good idea
- Tool is necessary for factory
- Could be very useful for support + customers
- Should we also update the Makefiles?
- If so, what do we want the task + args to look like
- Also, which Makefile would it live in? I'm thinking top-level
This must be run in an environment with …
> feat(discovery-client): Add CLI commands to find and SSH into a robot

- components/src/deck/Labware.js
- components/src/deck/Tip.js
- components/src/deck/Well.css
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/top-selectors/tip-contents/index.js
Tip tracking made visual!
Closes #1094
Tip tracking right now works only for whole steps, substeps don't show an additional level of detail. If we do want substep-grain tip tracking viz, I want to refactor the well substeps first and maybe the timeline shape itself, because there is a lot of complexity that I don't want to duplicate/expand.
- show tips on deck
:beetle: It looks like there are some bugs with tip use (eg 'once' seems to work like 'always' in some cases). I don't believe they are tip tracking viz bugs, I think what you see is what the robot will do. So, fixing what the robot will do with "once" vs "always" will be another PR. But at least we can see what's happening!
> feat(protocol-designer): display tip use across step timeline

- api/opentrons/data_storage/database.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/server/endpoints/__init__.py
- api/opentrons/server/endpoints/settings.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_settings_endpoints.py
Add endpoints at GET /settings/reset/options and POST /settings/reset to, respectively, query what reset options are available and reset any subset of those options to their factory configurations. This allows us to reset only the parts of the configuration that a user might want, and avoid resetting those configurations that are required for operation and difficult to change.
Closes #1885  
GET /settings/reset/options
```
200 OK
[
{
"id": "deckCalibration",
"name": "Deck Calibration",
"description": "Reset calibration of pipette to deck"
},
{
"id": "tipProbe",
"name": "Tip Probe Calibration",
"description": "Erase tip probe data"
},
{
"id": "labwareCalibration",
"name": "Labware Calibration",
"description": "Erase custom labware calibration"
},
{
"id": "bootScripts",
"name": "Boot …
```
> feat(api): Robot Reset

- api-server-lib/ot2serverlib/endpoints.py
Right now we restart our system by killing pid 1. When this happens, changes that the resin
supervisor and container make to the environment (like environment variables specified in the
Dockerfile) are not persisted across the restart. By using the Resin supervisor's /restart endpoint
(https://docs.resin.io/reference/supervisor/supervisor-api/#post-v1-restart) we can avoid this.
Closes #2092 
- Changing a machine's name in the resin UI does not take effect until the machine's container is restarted (e.g. with the restart button in the Resin UI). Now, hitting the server /restart endpoint causes the change to take effect.
> feat(api): Use the resin supervisor restart endpoint to restart

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
This logging fills up the screen when running factory tests, which can be confusing for testers. And
it is not that useful of a log because this error is expected when no pipette is attached
> refactor(api): Remove log.exception() in _parse_instrument_data()

- Dockerfile
- api/opentrons/resources/ot-environ.sh
- compute/container_setup.sh
- compute/find_ot_resources.py
- update-server/otupdate/control.py
- update-server/otupdate/install.py
- update-server/tests/test_update_api.py
This fixes issues with updating to a 3.2 api on a 3.3 system, and also issues
with running 3.2 on a 3.3 system.
API server wheels from before 3.3.0 do not have resource subdirectories and should not be
provisioned. The update server now inspects the version (from the filename) of the api wheel it is
installing and will not provision wheels whose version is prior to 3.3.0.
In addition, once the 3.2 api is uploaded, it will not have established the
proper setup scripts. This commit changes the container to properly fall back on
the scripts established in /usr/local/lib.
Also, the /restart changes that we thought we made were in the server lib which is not in fact used at all. They need to be in the update server's /restart.
Tested upgrade from 3.0.0 docker file and downgrade to 3.2 api (see …
> fix(update-server): Fix issues with 3.2 api on 3.3 system

- Dockerfile
- api/opentrons/server/endpoints/__init__.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_health_endpoints.py
- update-server/otupdate/__init__.py
- update-server/otupdate/endpoints.py
This commit adds an environment variable in the 3.3.0 dockerfile that is parsed from the api's package.json at build time. This is sent in the /health endpoints of both the api server and
update server:
```
GET /health
200 OK
{
"name": "opentrons-moon-moon",
"api_version": "3.3.0-beta.1",
"fw_version": "edge-6168d32",
"logs": [
"/logs/serial.log",
"/logs/api.log"
],
"system_version": "3.3.0-beta.1"
}
```
```
GET /server/update/health
200 OK
{
"name": "opentrons-moon-moon",
"updateServerVersion": "3.3.0-beta.1",
"apiServerVersion": "3.3.0-beta.1",
"smoothieVersion": "edge-6168d32",
"systemVersion": "3.3.0-beta.1"
}
```
The environment variable `OT_SYSTEM_VERSION` is set up by adding to `/etc/profile` rather than either an `ENV` directive or addition to `to-environ.sh` because
- Variables …
> feat(compute,api,update): Add system version to health, allow resin pull

- api-server-lib/ot2serverlib/endpoints.py
When /server/restart is provided by api-server-lib, there's a bug that was fixed in the
update-server version of /server/restart: a new thread has no asyncio event loop running and a new
one must be created.
The issue can be seen when the robot fails to restart when /server/update is hit with current edge running on system 3.0:
From Resin logs, immediately after hitting restart
```
main  Exception in thread Thread-1:
main  Traceback (most recent call last):
main    File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
main      self.run()
main    File "/usr/local/lib/python3.6/threading.py", line 864, in run
main      self._target(*self._args, **self._kwargs)
main    File "/data/packages/usr/local/lib/python3.6/site-packages/ot2serverlib/endpoints.py", line 134, in …
```
> fix(api-server-lib): Fix /server/restart failing in api-server-lib

- app/src/rpc/client.js
Bug ticket + fix.
Long running HTTP requests (like POST /robot/home) lock up the webserver, preventing it from responding to the app's RPC pings. If the threshold is low enough, the app will close down the websocket before the API unlocks. #2083 introduced a threshold that was lower than the time it takes the robot to finish homing.
This PR works around that issue by increasing the missed-ping threshold until the system can be rearchitected.
- fix(app): Increase RPC ping threshhold to workaround API lock during POST /robot/home
Make sure clicking "Home" in the robot settings page doesn't cause the RPC connection to close
> fix(app): Increase RPC ping threshhold to work around API lock

- app-shell/src/config.js
- app/src/components/DeckMap/ConnectedSlotItem.js
- app/src/components/InstrumentSettings/AttachedModulesCard.js
- app/src/components/ReviewDeckModal/LabwareComponent.js
- app/src/components/RunPanel/index.js
- app/src/config/index.js
- app/src/pages/Calibrate/Labware.js
This PR removes the modules feature flag to enable modules by default
- feat(app): Enable modules by default 
Make sure modules work without having to set a feature flag
> feat(app): Enable modules by default

- protocol-designer/src/components/steplist/TimelineAlerts.js
- protocol-designer/src/step-generation/errorCreators.js
if timeline alert doesn't have a verbose title and message, default to just the title
> fix(protocol-designer): ensure that timeline alert message defaults

- api/opentrons/tools/factory_test.py
App data directory changed to a location with spaces in its name. This PR fixes one of the QC scripts to accept file paths with spaces.
> fix(api): QC script accepts paths with spaces by adding double-quotes

- Dockerfile
- Makefile
When this was only a Dockerfile variable, it was only available in the environ of the original pid 1
of the system (and children). This means it works fine in the API server, but logging in remotely -
even with a login shell - won't have it set. Now it will.
Without this commit, RUNNING_ON_PI is only available in /proc/1/environ (and only if it hasn't previously been "restarted" by killing pid 1):
```
296f25b:~# env | grep RUNNING_ON_PI
296f25b:~# bash -lc "env | grep RUNNING_ON_PI"
[ bash ] Environment already configured
[ bash ] Environment already configured
296f25b:~# cat /proc/1/environ | grep RUNNING_ON_PI
RUNNING_ON_PI=1
```
After, it is available in any login shell:
```
bash-4.3# bash -l
[ bash ] Configuring environment
[ bash ] Environment configuration done
[ bash ] Environment …
```
> fix(compute): Make RUNNING_ON_PI available in env again

- api/opentrons/server/endpoints/settings.py
- api/tests/opentrons/server/test_settings_endpoints.py
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/AppSettings/AppInfoCard.js
- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/ResetRobotModal.js
- app/src/components/controls/LabeledCheckbox.js
- app/src/components/controls/index.js
- app/src/components/controls/styles.css
- app/src/http-api-client/actions.js
- app/src/http-api-client/index.js
- app/src/http-api-client/reducer.js
- app/src/http-api-client/reset.js
- app/src/http-api-client/server.js
- app/src/pages/Robots/RobotSettings.js
- components/src/styles/typography.css
This PR adds reset robot button to advanced settings and reset robot with options modal(s)
Closes #2030
- feat(app): Add reset robot UI with options
Please make sure it works on actual robots.
> feat(app): Add reset robot UI with options

- app/src/components/calibrate-pipettes/Pipettes.js
- app/src/pages/Calibrate/Pipettes.js
When calibrating, the link to change pipette if incorrect pipette attached directed the user to
/robots and now it to leads to /robots/{robot-name}/instruments
> fix(app): route users to the correct place to change pipettes

- protocol-designer/src/components/StepEditForm/FormSection.css
- protocol-designer/src/components/StepEditForm/FormSection.js
Closes #1769
- fix gear size expanding with browser zoom in Step Forms
Zooming (eg `Ctrl +`) shouldn't make the gear resize weirdly anymore
> fix(protocol-designer): fix gear size expanding with browser zoom

- api/opentrons/drivers/temp_deck/driver.py
- api/opentrons/modules/tempdeck.py
This PR fixes the issue of multiple port access by tempdeck driver due to _poll_temperature() threads not terminating properly.
Also makes sure to deactivate the tempdeck before disconnecting (needed in case a user doesn't add deactivate() at the end of their protocol or if a run is canceled before deactivating the module)
- Changed _poll_temperature() thread so that it terminates immediately upon disconnect
- All status and temperature properties of the tempdeck api object now depend on the _poll_temperature() thread to receive temperature updates from the module. If the thread is not active, then the driver's update_temperature() method will need to be called exclusively to get the latest tempdeck status
> fix(api): fix _poll_temperature() thread, deactivate before disconnect

- app/src/components/AppSettings/AppInfoCard.js
Somewhere between the last release and 3.3.0 the the title 'Information' was removed from the app info card in the more section of the app.
-fix(app): Add missing title to app info card
Open app, click more tab, confirm Information title renders in top app info card.
> fix(app): Add missing title to app info card

- protocol-designer/src/steplist/generateSubsteps.js
Fixes #2151
In all steps that have it (transfer/distribute/consolidate), the "Pre-wet tip" option should no longer create its own extra substep row.
> fix(protocol-designer): hide pre-wet tip asp/disp from substeps

- api/opentrons/modules/magdeck.py
This PR changes the magdeck engage height from `plate_height -1` to `plate_height-0.4` after measuring for tolerance required
> feat(api): change magdeck engage height

- api/opentrons/data_storage/database.py
SQLite occasionally creates a journal file to ensure atomicity of transactions
(https://www.sqlite.org/tempfiles.html#rollback_journals). This is located at the path of the file
with -journal appended, e.g. opentrons.db-journal. This wouldn't normally be a problem except that
in addition to using the journal for transactions, SQLite uses it as a way to recover from a
catastrophic data loss like a loss of power, or, say, someone deleting the database backing store
out from under it. So to ensure that we remove the database, we also have to make sure that if a
journal exists we remove it as well.
> fix(api): Delete the labware database journal on reset

- components/src/tooltips/HoverTooltip.js
- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/localization/en/button.json
- protocol-designer/src/localization/en/tooltip.json
Tooltips! For step creation button (aka "Add Step" button)
Closes #1979
* pare down StepCreationButton to simpler functional component
* add 'positionFixed' & 'modifiers' props to HoverTooltip
- :computer_mouse:
> feat(protocol-designer): add tooltips for step creation button

- components/src/__tests__/__snapshots__/lists.test.js.snap
- components/src/lists/TitledList.js
- components/src/lists/lists.css
Before, hovering over TitledList carat only showed a "hover state" (background color darkens) when the TitledList was NOT selected. This PR shows the carat "hover state" on both unselected and selected TitledLists.
And when I say TitledLists, I'm talking about how they're used by PD with all the fancy props, not the minimalistic use of TitledList in Run App (which should not be affected)
Closes #1977
- show 'hover state' background color shift when user hovers over carat of a selected TitledList
^ uses black at 5% opacity instead of opaque 5% gray
- Nothing weird in Run App's TitledLists
- :carrot: :mouse:
> feat(protocol-designer): restyle selected TitledList carat hover

- components/src/forms/InputField.js
- components/src/forms/forms.css
- protocol-designer/src/components/StepEditForm/FlowRateField/FlowRateField.js
- protocol-designer/src/components/StepEditForm/FlowRateField/index.js
- protocol-designer/src/steplist/actions/handleFormChange.js
1. Clear flow rate when pipette is changed
2. On a form with no pipette selected (new form), flow rate field is disabled.
Yet another part of #1323  :)
- refactor handleFormChange to support multiple transformations
- add `disabled` prop to `InputField` component
- disable flow rate field when no pipette is selected
- changing pipette should reset flow rate to "Default" (falsey). Should work in all Steps (except Pause)
- on a form with no pipette selected (new form), flow rate field is always disabled. Disabled: label & input field text is grayed out, and clicking does nothing. When you select a pipette, it becomes enabled
> feat(protocol-designer): flow rate field more dependent on pipette

- shared-data/definitions/tube-rack-15_50ml.json
Fixed labware def in shared-data for `tube-rack-15_50ml` -- before, wells were all messed up and overlapping!
- Fix def! Used `default-containers.json` for x/y/diameter, but kept the updated depth (but rounded to 2 decimal places)
- `make -c shared-data/ build` then you can view the updated definition in PD on the deck. Note that all defs have a hard-coded offset `svgOffset` in `Plate` component, so it will be off, but if you zero out `svgOffset`, then the labware will be centered :sob:
> fix(shared-data): fix tube-rack-15_50ml labware def

- .travis.yml
- Makefile
- appveyor.yml
This PR runs `pipenv` and `yarn` in parallel on CI to speed up the builds during the `make install` stage. It also gives users the option to run `make install` in parallel on their own machines.
- ci: Parallelize `make install` in CI 
`make` has an option `-j, --jobs` that lets you specify how many jobs can run in parallel. By default, `--jobs` is set to `1`. However, by passing `-j 2` (or, just `-j` to let your computer figure out how many jobs to run based on number of cores your CPU has), you can tell `make` to run more jobs.
By splitting `make install` into `install-py` and `install-js` and adding them as task dependencies of `install` (rather than part of the task body), `make` will run them in parallel when you tell it `-j 2`.
Compared to the build immediately before this one (so …
> ci: Parallelize `make install` in CI

- app/src/support.js
Our support module was caching the intercom handler too early (before the window had a chance to load, which is when the Intercom snippet actually assigns to `window.Intercom`), resulting in all our intercom calls nooping. This change removes the caching so window.Intercom is always
called correctly ([as suggested by @IanLondon](https://github.com/Opentrons/opentrons/pull/2140#pullrequestreview-150317031))
- fix(app): Grab intercom handler from window on every call
When you connect to a robot, you should see the "Robot Name" field of your intercom user update to that name. Hit me up over Slack for the correct intercom ID to use.
```shell
make -C app dev OT_APP_INTERCOM_ID=xyz123
```
> fix(app): Grab intercom handler from window on every call

- app/src/components/RobotSettings/ResetRobotModal.js
- app/src/support.js
This PR closes #2019 by adding attached pipettes info to intercom data when a the api returns `'api:PIPETTES_SUCCESS'`
- feat(app): Add attached pipette info to intercom support
Unfortunately, the imported intercom handler always returned as a `noop` for `Intercom('update')` calls. So we had to do it the old fashioned way with `window.Intercom(...)`
Intercom does not accept arrays or objects for values in custom data fields. So rather than just have a single data attribute `Pipettes: {...}` with all of the apps info about the pipettes, it needed to be split up into `Left Pipette: model string` etc.
TODO: (in the future)
Add pipette serial numbers to intercom once they are exposed by the api
We have a test intercom app for these PRs so we can avoid confusing support with our nonsense …
> feat(app): Add attached pipette info to intercom support

- api/docs/source/atomic commands.rst
- api/docs/source/index.rst
- api/docs/source/modules.rst
Behavior for the magnetic module has changed such that the module no longer auto-calibrates. Also, the links on the homepage for OT 2 documentation was non-functional.
- Fix spacing of docs
- Add in new magnetic module logic information
- Fix link spacing and formatting.
> (Docs): Fix links formatting

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/server/main.py
- api/opentrons/system/__init__.py
- api/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_wifi_endpoints.py
- api/tests/opentrons/system/test_nmcli.py
In preparation for adding more methods of wifi connectivity, take the subprocess invocations of
nmcli that are currently inline in the /wifi endpoints and move them into their own module
(api/system/nmcli - api/system is itself new and can be used for more python modules whose main
purpose is just to mess around with the system).
Check for regressions, basically. The only thing that might cause a problem is that the old wifi endpoints used this shortcut command in nmcli that's only available for wifi (`nmcli device wlan0 connect $SSID password $PASSWORD`), while this uses the more general form of first creating a connection with `nmcli connection add` and then bringing it up with `nmcli connection up`. Going forward, this will allow us to do more complex configuration for wifi links and …
> refactor(api): Move nmcli interaction into its own module

- api/opentrons/system/nmcli.py
Make sure we use the permanent hardware address for the mac address when we connect to wireless networks.
> feat(api): Ensure the wifi mac address stays fixed

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_wifi_endpoints.py
Fix the hidden flag in the nmcli module and expose it to the REST interface.
Closes #2137 
If anybody wants a router to test with I have an el clasico WRT54G that can be set up to do so.
> feat(api): Add hidden ssid wifi support

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_wifi_endpoints.py
Adds additional network information to the `GET /wifi/status` endpoint. In particular, this now returns
- The IP address of the interface, with its subnet in CIDR format
- The IP address of the interface's gateway
- The MAC address of the interface
If any of these fields aren't found (e.g. if the interface is disconnected, or has a setup where there's no gateway somehow) they'll be null.
For instance, a robot connected to a wifi network might look like:
`GET /wifi/status`
```
200 OK
{
"status": "full",
"ipAddress": "192.168.1.137/24",
"macAddress": "3A:1A:4A:5E:D4:66",
"gatewayAddress": "192.168.1.1"
}
```
while a robot that is not connected might return
```
200 OK
{
"status": "none",
"ipAddress": null,
"macAddress": "3A:1A:4A:5E:D4:66",
"gatewayAddress": null
}
```
Frontend people, …
> Api add network info endpoint

- api/opentrons/api/session.py
- api/opentrons/modules/magdeck.py
This PR switches out the magdeck calibration process and instead has the module `engage()` to:
- a default height for the labware, if it exists. e.g. `engage()`
- or a user-defined offset (+/- mm) to the default height. e.g. `engage(offset=2)`
- or a user-defined custom height, measured as mm from magdeck home position. e.g. `engage(height=10)`
The `calibrate()` method still exists in the api for now, in case it's needed in future. Is this advisable?
> feat(api): add custom height and offset params to magdeck engage

- Makefile
Previously, because the robot finding mechanism was not actually in a target, if no robot was found
in push-api then the makefile would proceed to build the wheel and only fail when it tried to
connect to :31950 (note the lack of actual IP address there). By instead invoking the discovery
client directly in a target and using a file intermediate we can fail fast if no robot is found.
Check it on windows just to be sure.
> chore(build): Make push-api fail if no usb host was found

- api/opentrons/config/containers/default-containers.json
Closes #2184. 
- Adds container definitions for the following:
`opentrons-aluminum-block-2ml-eppendorf`
`opentrons-aluminum-block-2ml-screwcap`
`opentrons-aluminum-block-96-PCR-plate`
`opentrons-aluminum-block-PCR-strips`
Pls test on your robot (pre- and post calibration behaviors) with this protocol:
```
from opentrons import labware, instruments, robot
pcr_plate = labware.load('opentrons-aluminum-block-96-PCR-plate', '1')
pcr_tube = labware.load('opentrons-aluminum-block-PCR-strips', '2')
tubes_eppendorf = labware.load('opentrons-aluminum-block-2ml-eppendorf', '3')
tubes_screwcap = labware.load('opentrons-aluminum-block-2ml-screwcap', '4')
tiprack = labware.load('tiprack-10ul', '6')
pipette = instruments.P10_Single(mount='right', tip_racks=[tiprack])
pipette.pick_up_tip() …
```
> feat(api): Add container definitions for opentrons alumnium block set

- api/opentrons/protocols/__init__.py
- api/tests/opentrons/protocols/test_load_json_protocol.py
- protocol-designer/src/components/StepEditForm/TipPositionInput/TipPositionModal.js
- protocol-designer/src/constants.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/dispense.js
- protocol-designer/src/step-generation/distribute.js
- protocol-designer/src/step-generation/mix.js
- protocol-designer/src/step-generation/transfer.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/actions/handleFormChange.js
- protocol-designer/src/steplist/formLevel/generateNewForm.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- shared-data/protocol-json-schema/protocol-schema.json
Closes #2157
- JSON protocols store default mm from bottom, for aspirate and for dispense, in "default-values" key
- Aspirate and dispense commands have optional parameter to offset mm from bottom, which when specified is used instead of the "default-values" offset
- API defaults for mm from bottom on aspirate/dispense are never used (unless the JSON doesn't include the new "default-values")
- PD: split out generic "offset from bottom" into 2: one for aspirate and one for dispense. I copied over the defaults that the API is using now: 1mm and 0.5mm for asp/disp respectively.
- Hook up tip positioning fields from form to step generation fns so they're saved into the commands list and thus the JSON file
- API's JSON executor, and JSON schema, updated to support explicit mm from bottom …
> feat(protocol-designer): support mm from bottom offset in JSON protocols

- discovery-client/src/__tests__/client.test.js
- discovery-client/src/__tests__/poller.test.js
- discovery-client/src/index.js
- discovery-client/src/poller.js
- discovery-client/src/service.js
- discovery-client/src/types.js
Feature ticket + PR.
Per connectivity discussions, this is a plumbing PR that adds an additional check to the discovery poller: `GET /server/update/health`. This will (eventually) help the app determine if a robot's update server is still up even if the primary API is not responding
- feat(discovery-client): Add GET /server/health check to poller 
Sorry for the large diff; it's mostly unit test changes though. Source changes themselves are small. Easiest way to test this is with the CLI:
```shell
make -C discovery-client
npx discovery browse
```
You will now see that discovered robots have an additional `serverOk` flag:
```
Browsing for services
service added or updated: { name: 'opentrons-dev',
ip: 'localhost',
port: 31950,
ok: true,
serverOk: false }
```
> feat(discovery-client): Add /server/update/health check to poller

- protocol-designer/src/components/FileSidebar/ConnectedFileSidebar.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/index.js
- protocol-designer/src/localization/en/alert.json
If a user attempts to import an existing file or create a new one, their current protocol will be
nuked upon completing that action. We now give people a confirmation step.
> feat(protocol-designer): warn changes will be lost on import/create

- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/http-api-client/__tests__/settings.test.js
- app/src/http-api-client/actions.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/settings.js
Small refactor PR in the same vein as #2215 to make future API work around connectivity state easier with regards to #2100.
- refactor(app): Consolidate /settings calls into common API state
Ensure robot advanced settings still report correctly and can still be changed correctly.
> refactor(app): Consolidate /settings calls into common API state

- components/src/deck/ContainerNameOverlay.js
- protocol-library-kludge/src/URLDeck.css
- protocol-library-kludge/src/URLDeck.js
Support modules and nicknames for labware in OT2 deckmap kludge for Protocol Library!
* support modules & nicknames
* url-encoded JSON in `data` param
- You'd have to test this locally. URLs will look like http://localhost:8080/?data=%7B%22labware%22:%7B%224%22:%7B%22name%22:%22nickname%22,%22labwareType%22:%2296-flat%22%7D%7D,%22modules%22:%7B%224%22:%22tempdeck%22%7D%7D The joy of passing JSON via URL params into iframes :grimacing:
> feat(protocol-library-kludge): support modules and nicknames

- api/docs/source/pipettes.rst
- api/opentrons/__init__.py
- api/tests/opentrons/labware/test_pipette_constructors.py
Bug report + fix. This PR fixes up a couple problems with #2084:
- The change in parameter order of the pipette factories was a **breaking change**
- New parameters were moved to the end of the constructors where all new parameters should be added to avoid breakage
- The new volume parameters weren't actually passed to the pipette config
- Fixed
This PR also:
- Adds tests to sanity check the behavior of the factories and ensure this sort of break isn't introduced again
- Adds `min_volume` and `max_volume` to the documentation
- fix(api): Fix pipette volume params and revert change in param order 
Please make sure the pipette constructors still work! Unit tests pretty much cover everything so this shouldn't be too risky.
> fix(api): Fix pipette volume params and revert change in param order

- api/opentrons/server/main.py
Previously, the API server would always bind to a hostname and port even if a socket was specified -
aiohttp does not consider these mutually exclusive, and the arguments in argparse default to
localhost:8080. This can cause conflicts when the API server tries to start on a robot, in an
unpredictable way. We now consider listening to a socket and listening on a hostname mutually
exclusive.
Closes #2256
> fix(api): Do not bind the api server to localhost if socket specd

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/server/main.py
- api/opentrons/system/nmcli.py
- api/opentrons/util/environment.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_wifi_endpoints.py
Some EAP secured networks (in fact most kinds) either require or allow the use of key files for various tasks, such as client identity authentication through private keys or server identity authentication through x.509 certificates. In some cases, these keys can be large; so, rather than just adding them into the `/wifi/configure` request, here are some new endpoints to manage wifi keys.
They will be stored on disk in the new subdirectory `/data/user_storage/opentrons_data/network_keys`, available in `opentrons.util.environment.settings` as `WIFI_KEYS_DIR`. To allow upload of identically named keys, the key files will be stored in directories named by a hash of the key file itself. Identically-hashed keys are not allowed.
The shape of the endpoints is:
``` GET /wifi/keys
200 OK
{ keys: [ …
```
> Network connectivity: Add key management for EAP secured networks

- .gitignore
- api/Makefile
- api/Pipfile
- api/Pipfile.lock
- api/mypy.ini
Add mypy to the API's lint target, while preventing it from failing the target.
This will have big error messages about failing type checks but (since many of them exist already in the codebase) it will not actually fail the lint target and therefore the build. The goal, going forward, is to fix any type checks in files that you actively touch.
Once all the existing typecheck failures are fixed, we can consider turning on more features like explicitly requiring typechecks.
> build(api): Add mypy and run it (without failing if it fails) in lint

- app/src/http-api-client/__tests__/motors.test.js
- app/src/http-api-client/__tests__/pipettes.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/motors.js
- app/src/http-api-client/pipettes.js
- app/src/http-api-client/settings.js
- app/src/support.js
Small refactor PR in to make future API work around connectivity state easier with regards to #2100. 
Since pipettes is a one off case with refresh it does not implement `buildRequestMaker`.
This pr touches motors as well since they depend on pipettes. Theres a TODO about storing motors in state that might require further discussion.
- refactor(app): Consolidate /pipettes calls into common API
tests pass and everything looks cool on VS but please test all pipette related pages on an actual robot with pipettes to ensure everything still works!
> refactor(app): Consolidate /pipettes calls into common API

- app/src/components/FileInfo/InformationCard.js
- app/src/components/FileInfo/LabwareTable.js
- app/src/components/FileInfo/ProtocolLabwareCard.js
- app/src/components/FileInfo/ProtocolModulesCard.js
- app/src/components/FileInfo/ProtocolPipettesCard.js
- app/src/components/FileInfo/index.js
- app/src/components/FileInfo/styles.css
- app/src/components/UploadError/index.js
- app/src/components/UploadError/styles.css
- app/src/components/UploadPanel/Upload.js
- app/src/components/UploadPanel/index.js
- app/src/components/layout/styles.css
- app/src/pages/Upload/FileInfo.js
- app/src/pages/Upload/index.js
- app/src/protocol/__tests__/selectors.test.js
- app/src/protocol/index.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/session-reducer.test.js
Closes #2129
This PR adds selectors for JSON protocol metadata and wires them up into the File Info page. It also tweaks the error message to show up on the file info page (because protocol metadata would be useful to debug a JSON protocol that was valid JSON but failed during simulation).
- feat(app): Populate FileInfo page with JSON protocol metadata 
Please test this out with:
> feat(app): Populate FileInfo page with JSON protocol metadata

- discovery-client/src/__tests__/client.test.js
- discovery-client/src/index.js
#2206 introduced a regression into the discovery client where as soon as a robot had a known health state, it would be latched, so any change in its `/health` responses would not be propagated
- fix(discovery-client): Fix health state latching regression 
Can test via the CLI or via the app
- Run `make -C discovery-client` first to rebuild from src
- If testing via VS and the CLI: `npx discovery -n opentrons-dev -c localhost`
- If testing via real robot and CLI: `npx discovery -n robot-name-here`
- If testing via app: keep an eye out for your robot
1. Start discovery via app (or CLI)
2. Turn robot off
3. Turn robot back on
> fix(discovery-client): Fix health state latching regression

- CHANGELOG.md
- api/opentrons/CHANGELOG.md
- api/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Beta release `3.4.0-beta.0`
- [Since last beta](https://github.com/Opentrons/opentrons/compare/v3.3.1-beta.0...e178f9e)
- [Since last stable](https://github.com/Opentrons/opentrons/compare/v3.3.0...e178f9e)
Tested on Sunset with fresh labware database, fresh deck calibration, and fresh tip lengths and no tip probe
- No regressions since last beta, but definitions still need work before next stable release
- Sane enough to release to a beta
- No regressions since last beta, but definitions still need work before next stable release
- Sane enough to release to a beta
- Looked good
- Looked good
> chore(release): 3.4.0-beta.0

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/server/main.py
- api/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_wifi_endpoints.py
- update-server/otupdate/install.py
This PR allows the system to connect to wireless networks that are secured
with WPA2-enterprise using
EAP-TLS
PEAP/EAP-MSCHAPv2 (eduroam)
TTLS/EAP-MSCHAPv2
TTLS/EAP-TLS
TTLS/MD5
These should be a good selection of the more popular EAP configurations.
There is also a framework for easily adding more configurations for EAP, by
adding elements to opentrons.system.nmcli._EAP_OUTER_TYPES,
opentrons.system.nmcli._EAP_PHASE2_TYPES, and opentrons.system.nmcli.EAP_TYPES.
Because eap configuration can become complex, the available configuration
options are exposed through a new endpoint, GET /wifi/eapoptions. The return
value describes the required structure for input to POST /wifi/configure.
The new endpoint has a lot of docs about it so check out the function `eap_options` in the wifi endpoints …
> feat(api): Add ability to connect to WPA2-Enterprise networks

- app/src/components/ConnectPanel/RobotLink.js
- app/src/components/ConnectPanel/RobotList.js
- app/src/components/ConnectPanel/connect-panel.css
- app/src/components/ConnectPanel/index.js
- components/src/nav/SidePanel.css
closes #2046
Turns out the calc function for the height of the scrollable area in the sidebar was about 2rem too high, causing the scrollable area to flow off the page.
- fix(app): Fix robot list scroll clipping
The sidebar is in the component library, so this change may (but shouldn't) affect the protocol designer. I did a quick check locally but please confirm.
> fix(app): Fix robot list scroll clipping

- protocol-designer/src/components/StepEditForm/TipPositionInput/index.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/steplist/actions/handleFormChange.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/types.js
- protocol-designer/src/top-selectors/well-contents/wellContentsAllLabware.js
Fix our recurring deleting labware bug #1406 #1614 ...once and for all?
The problem is the worst when you delete a labware that one or more steps are using, in edge it whitescreens.
At least this will have Flow ensure that accessing labware by id will be safe, and not whitescreen due to` TypeError: ___ is undefined`.
* make labware access by id always maybe typed (?Labware) so flow ensures safe access
- Code review -- still sane?
- Test PD, deleted labware experience isn't fantastic, but at least it no longer whitescreens.
The UI won't whitescreen with this PR, but it'll be a little weird. #2161 will address the UI issues left in place by this PR.
> fix(protocol-designer): fix recurring deleted labware bug

- shared-data/js/helpers/computeWellAccess.js
Fixes #2081
When I wrote this, I thought `shared-data/` labware definitions worked like `default-containers.json` definitions -- that rectangular well x/y point was located in the center. However, in `shared-data/` right now, all well x/y points are located at the bottom left bounding box around the well.
In `shared-data/`, this will soon be changed to well center, so I kept the logic and just commented it out until `shared-data/` x/y matches what this code was written for, x/y in well center.
- fix bug in findWellAt fn
- Can select well 9 of trough
- Other labware selection still works (the only other rectangular-well labware is Trash Box, so that's worth testing, works for me)
> fix(protocol-designer): fix bug with well access for rect wells

- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/transfer.js
Fixes bug #2287 where Transfer with change tip: "only the first aspirate" (aka, "once") would change tips too eagerly (for cases where the transfer volume <= pipette max vol, it would change them every time and look the same as if "always" had been selected)
The diff is really 1 line, but I also expanded the tests to catch a wider range of behaviors with tip use.
- fix changeTip="once" behavior for transfer
Transfer tip use works as expected (hover over the saved Transfer step and look at what tips in the tiprack are highlighted)
Does not affect other step types, it's just Transfer.
> Pd fix transfer tip use

- components/src/forms/InputField.js
- components/src/forms/forms.css
- protocol-designer/src/components/StepEditForm/WellOrderInput/WellOrderInput.css
Closes #2196
InputField wasn't tall enough, and WellOrderInput needed a little vertical padding so that the rows in the form still line up.
* consistent vertical padding for InputField and WellOrderInput
- Looks OK
- You're OK with the 1px padding mis-alignment in Firefox on input field (@mcous fixed it, I'm breaking it again, b/c I spent too much time messing trying to reset it with no progress and PD doesn't support FF anyway)
- Run App should not be affected. I'm pretty sure the only thing that could be affected is the wifi password field, I don't see any other uses of InputField in run app -- and that wifi password field looks unchanged to me. Please double-check @Kadee80 @mcous
> fix(protocol-designer): correct alignment of form fields

- api/opentrons/commands/commands.py
- api/opentrons/protocols/__init__.py
- api/opentrons/robot/robot.py
Closes #1694 - `robot.pause` supports optional message param. Also fixes unticketed issue where robot.comment causes commands list in Run App to indent.
JSON example (nothing is indented in JSON b/c only low-level methods used):
.py example (.py uses indentation b/c it uses distribute, etc high-level methods):
* support optional robot.pause message
* fix indentation issue with robot.comment in Run App command log
Not sure who to include in a PR like this so I just tagged a handful of ppl...
> feat(api): support optional pause message

- app/src/components/RunLog/CommandList.js
This PR is also serving as an issue.
**Issue:** Run screen `SpinnerModals` (after confirm cancel run or reset run) overlays did not cover the fill height of the page/screen since those modals were children of `CommandList`
**Fix:** Wrap run log modals in portal.
- fix(app): Wrap run screen modals in portal
Run a protocol - VS is fine, but the modals are very short lived
Cancel or Reset the run
> fix(app): Wrap run screen modals in portal

- app/src/components/JogControls/index.js
This PR closes #2300. Clicking on a jog increment radio button caused an onFocus event which allowed an unused combination of our arrow keys + shift to change the jump size. The solution was to setState and then immediately `.blur()` the clicked element.
- fix(app): Prevent wrong keypress combo from changing jog jump size
Try it out on VS or a Robot. Open up deck calibration or labware calibration (some screen with jog buttons)
Click on a radio button to choose a jog increment (focus the form element)
> fix(app): Prevent wrong keypress combo from changing jog jump size

- api/opentrons/api/session.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/data/no_clear_tips.py
- api/tests/opentrons/robot/test_robot.py
When `Robot.reset` is called, any instruments with tips attached should have the tips removed before clearing the singleton state (including both the instruments dict and pose tracker). Closes #2322.
- fix: clear tip lengths if present before clearing instruments
> fix(api): When reseting the robot singleton, clear added tips

- components/src/structure/structure.css
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/containers/TitleBar.css
Titlebars now stay in view despite scrolling, which allows users to always see possible navigation
options.
Closes #2195
> feat(components): make titlebar stick to top on scroll

- CHANGELOG.md
- app-shell/.gitignore
- app-shell/build/release-notes.md
- app-shell/electron-builder.json
- app-shell/src/update.js
- app/package.json
- app/src/components/AppSettings/AppInfoCard.js
- app/src/components/AppSettings/AppUpdateModal.js
- app/src/components/AppSettings/ReleaseNotes.js
- app/src/components/AppSettings/index.js
- app/src/components/AppSettings/styles.css
- app/src/components/modals/BottomButtonBar.js
- app/src/components/modals/ErrorModal.js
- app/src/components/modals/index.js
- app/src/components/modals/styles.css
- app/src/pages/More/AppSettings.js
- app/src/shell/__tests__/update.test.js
- app/src/shell/index.js
- app/src/shell/update.js
- components/src/modals/AlertModal.js
- components/src/modals/modals.css
- yarn.lock
This PR addresses the app update portion of #2028 
- feat(app): Add release notes to app update modal 
App update is hard to test. Hit me up if you'd like a modified build of the app that has an incorrect version so that it thinks it's out of data.
@umbhau and @pantslakz (and anyone else) let me know what you think of these release notes! I'm thinking we keep the release notes as a summary from the last major release, and we add to it prior to beta releases.
@IanLondon and @b-cooper I added max-height rules to some children of the AlertModal. I didn't see it change anything in PD (because the top level modal doesn't have a height or max-height by default) but please double check for me.
> feat(app): Add release notes to app update modal

- app-shell/src/ui.js
- app/src/components/AppSettings/ReleaseNotes.js
- app/src/components/Resources/ResourceCard.js
The app was opening external links in the app rather than in the browser as expected
- fix(app): Open external links in user's browser instead of app window
> fix(app): Open external links in user's browser instead of app window

- api/opentrons/server/endpoints/settings.py
- api/tests/opentrons/server/test_settings_endpoints.py
Remove deck calibration from factory reset options, as deck calibration reset should not be done
outside of the context of recalibration. Closes #2331 
Ensure that factory reset options still appear as expected
> feat(api): Remove deck calibration from reset options

- CONTRIBUTING.md
Setting core.autocrlf to something that inserts carriage returns on windows means that API pushes to
robots from windows will have carriage returns in the scripts in api/opentrons/resources, which
prevents the robot from booting.
Closes #2305
> docs(contributing): Ask Windows users to set core.autocrlf=input

- api/opentrons/config/containers/default-containers.json
Update labware definitions for 15ml, 50ml, and 15/50ml tuberacks to match actual well heights. Closes #2290 
Combined drawing for modular tube rack with tubes:
Please test thoroughly on a robot
- Move to .top() and .bottom() of every well in
If you wish to use a protocol to do this:
```
from opentrons import robot, instruments, labware
tr = labware.load('opentrons-tiprack-300ul', '1')
tuberack_15_50 = labware.load('opentrons-tuberack-15_50ml', '2')
tuberack_15 = labware.load('opentrons-tuberack-15ml', '5')
tuberack_50 = labware.load('opentrons-tuberack-50ml', '8')
pipette = instruments.P300_Single(mount='right', tip_racks=[tr])
pipette.pick_up_tip()
pipette.move_to((robot.deck, (380.87, 9.0, 0.0)), strategy='arc')
robot.pause()
pipette.move_to((robot.deck, (12.13, 258.0, 0.0)), …
```
> fix(api): Update definitions for tuberacks

- .gitattributes
With our current .gitattributes settings, the hex file with CRLF endings keeps popping up as "modified" whenever I check out a branch.
This should remove the text=auto from applying to the hex files.
Works on Windows?
> chore(chore): add exception in gitattributes for our hex files

- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/step-generation/blowout.js
- protocol-designer/src/step-generation/test-with-flow/blowout.test.js
- protocol-designer/src/steplist/actions/handleFormChange.js
Addresses #2161 but I can't find a clean way to totally close it - added a comment to `handleFormChange` and commented on that ticket with more info.
This PR makes it so labware dropdown shows up as blank instead of just showing the first thing in the list, when the previously selected labware was deleted.
This PR also fixes a bug, for which this PR serves as the ticket:
WHITESCREEN BUG:
* Create a Distribute step that blows out to a `trash-box` labware on the deck
* Delete that trash-box
* Whitescreen!
* fix unticketed bug: setting blowout to a trash-box in a step and deleting the trash box caused whitescreen
*make labware dropdown blank when nonexistent labware selected
* No whitescreen on deleting labware, even in blowout
* Even if it's not all the way to where we wanna be, is the …
> fix(protocol-designer): fix whitescreen on deleting blowout labware

- CHANGELOG.md
- api/opentrons/CHANGELOG.md
- api/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Release PR for 3.4.0
- Changelog document: https://github.com/Opentrons/opentrons/blob/986ee48d6f108104dd105ba5c61b092e23b13e41/CHANGELOG.md
- Release notes document: https://github.com/Opentrons/opentrons/blob/986ee48d6f108104dd105ba5c61b092e23b13e41/app-shell/build/release-notes.md
- Since 3.3.0: https://github.com/Opentrons/opentrons/compare/v3.3.0...986ee48d6f108104dd105ba5c61b092e23b13e41
- Since 3.4.0-beta.0: https://github.com/Opentrons/opentrons/compare/v3.4.0-beta.0...986ee48d6f108104dd105ba5c61b092e23b13e41
Standard release review. @umbhau could use your 👍 on the release notes
> chore(release): 3.4.0

- protocol-designer/src/components/modals/NewFileModal/index.js
Fix a small bug where the tiprack diagram in the new file modal would duplicate the diagram of the
selected right pipette tiprack instead of showing both selections.
> fix(protocol-designer): fix tiprack diagram only displaying right

- api/opentrons/config/modules/95-opentrons-modules.rules
- api/opentrons/drivers/mag_deck/driver.py
- api/opentrons/modules/__init__.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/main.py
- api/tests/opentrons/labware/test_modules.py
- api/tests/opentrons/server/test_update_endpoints.py
This PR adds the firmware update endpoint for modules. 
The update process:
- The update methods use module serial number from POST request to find the module to be updated. 
- Once the matching module is found, it initiates firmware upload by first switching to dfu mode on the atmega32u4 and then selecting the bootloader port opened by dfu mode. The process of searching for this port is different depending on if the module has an older bootloader on it (all iGEM tempdecks have older bootloader)
- The `update_firmware` api method uses this port to upload firmware using avrdude command and returns a success or fail message to the endpoint
- Added firmware update api methods and update server functions
- Added a udev rule for new bootloader
- Added tests for modules and update_server …
> feat(api): add module firmware update endpoint

- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/webpack.config.js
It's annoying to have to look up a commit hash from the git-describe version that we have saved in right now, so this PR introduces an additional field in PD protocols (still conforms with the protocol schema, it's an additional field)
Serves as its own ticket.
Check out the Travis build, save a file, open it in a text editor, and confirm that the `"_internalAppBuildDate"` is the time that the build was made, not the time you opened PD.
> feat(protocol-designer): add "app build date" field to PD saved files

- api/Makefile
- api/opentrons/main.py
- api/opentrons/resources/scripts/start.sh
- api/opentrons/server/__init__.py
- api/opentrons/server/http.py
- api/opentrons/server/main.py
- api/opentrons/server/rpc.py
- api/opentrons/system/resin.py
- api/opentrons/system/udev.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_control_endpoints.py
- api/tests/opentrons/server/test_health_endpoints.py
- api/tests/opentrons/server/test_logs_endpoints.py
- api/tests/opentrons/server/test_settings_endpoints.py
- api/tests/opentrons/server/test_update_endpoints.py
- api/tests/opentrons/server/test_wifi_endpoints.py
This PR separates out the previously entangled server and system functions so that `opentrons.main` handles system configuration while `server.main` only configures and runs the server
- Entrypoint of the system is changed to `opentrons.main`
- Server is restructured to hold the REST (`http.py`) and rpc(`rpc.py`) sides as siblings, so either can be run without the other
- udev and resin configuration moved to `/system`
- Check if the system and server functions have been sufficiently disentangled
> refactor(api): invert control of system and server

- api/opentrons/hardware_control/__init__.py
- api/opentrons/hardware_control/controller.py
- api/opentrons/hardware_control/simulator.py
- api/opentrons/util/environment.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/test_instantiation.py
Add a new submodule called `hardware_control` that will, going forward, be the unit that controls all of the hardware in the robot (the implementation of #2232 ).
The `hardware_control` module is a HAL that presents an API at the lowest semantic level possible while still considering the OT2 as a "robot" rather than as a collection of disparate hardware. For instance, it considers the robot's motion systems as a coherent whole, but uses the absolute deck coordinate frame and does not know about labware. It presents an API on the level of `move` (specifying the gantry axes and each pipette axis), `aspirate` and `dispense`, and `pick_up_tip` and `drop_tip` (over wherever the pipette happens to be, not moving to specific locations) but does not have the higher-level commands such as …
> API: add hardware control

- .travis.yml
- Makefile
- package.json
- yarn.lock
A while back our Python code coverage stopped getting uploaded. I had figured this was a problem with the codecov configuration, but it turns out it was just that a `make clean` was wiping out the API's coverage report before codecov could find and upload it.
This PR calls the coverage task directly after `make test` to avoid any unintended report deletion and also switches from codecov's bash reporter to one from `npm` to avoid coverage (or build) breakages due to unexpected changes in Codecov's unversioned (for us) curl'd bash uploader
- ci(codecov): Fix uploading of python coverage
Please check the coverage report for this branch - https://codecov.io/gh/Opentrons/opentrons/branch/build_fix-coverage
> ci(codecov): Fix uploading of python coverage

- app-shell/src/api-update.js
- app-shell/src/main.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/server.js
- app/src/shell/__tests__/api-update.test.js
- app/src/shell/api-update.js
- app/src/shell/index.js
The PR does work to address #2354 by putting information about the API update bundled with the app (most importantly: version) into the app state.
- refactor(app): Add actual state for API update file 
- The nav link notification dot for "Robots" is now broken
- This should be fixed naturally or almost naturally by work for #2344
- Would also like to confirm what our expected behavior actually is wrt this dot
> refactor(app): Add actual state for API update file

- api/opentrons/labware/__init__.py
Add a skeleton for the new Labware class. Closes #2261
- Add Labware class
I am open to suggestion on how this class should be structured (there isn't much in this PR aside from return types on some important methods), so if you want to weigh in please either comment or send me a message.
> feat(api): Add skeleton of new Labware class

- .gitignore
- api/opentrons/server/endpoints/serverlib_fallback.py
- api/opentrons/server/http.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/containers/test_containers.py
- api/tests/opentrons/containers/test_old_container_loading.py
- api/tests/opentrons/containers/test_placeable_unittest.py
- api/tests/opentrons/helpers/test_helpers.py
- api/tests/opentrons/labware/test_pipette_unittest.py
- api/tests/opentrons/server/test_update_endpoints.py
- api/tests/opentrons/util/test_vector.py
Change api update ignore route to be accessible to client. Other changes are renames for deprecation warnings (get API warnings in test down to 0). Closes #2367 
- Change API update ignore route to "/update/ignore"
- Rename functions in test to clear deprecation warnings
Talked with @mcous about the route change. Ping @Kadee80
> fix(api): Change api update ignore route to be accessible to client

- app-shell/package.json
- app/package.json
- app/src/components/ConnectPanel/RobotItem.js
- app/src/components/ConnectPanel/RobotList.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateModal.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- app/src/pages/Robots/RobotSettings.js
This PR addresses #2354 by checking if the available robot update is an `upgrade` `downgrade` or reinstall. UI changes include:
- only show a `NotificationIcon` in the `RobotListItem` if the available install is an upgrade
- Robot Settings page `InformationCard` button text is [upgrade] [reinstall] or [downgrade]
- More informative text about the type of install in the UpdateModal
- feat(app): Add upgrade and downgrade logic to robot updates
To test on VS, run `make -C api wheel`
change the version of 
`api/dist/opentrons-3.4.0-py2.py3-none-any.whl` 
to 
`api/dist/opentrons-3.3.0-py2.py3-none-any.whl`
change the version of 
`api/dist/opentrons-3.4.0-py2.py3-none-any.whl` 
to 
`api/dist/opentrons-3.5.0-py2.py3-none-any.whl`
> feat(app): Add upgrade and downgrade logic to robot updates

- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateAppMessage.js
- app/src/components/RobotSettings/UpdateModal.js
This PR closes #2354 by prompting user to update thier app in the update robot modal if there is an app update available.
- feat(app): Prompt user to update app in robot update modal
change app and app-shell package.json version to 3.3.0
change app and app-shell package.json version to 3.5.0
> feat(app): Prompt user to update app in robot update modal

- api/opentrons/protocol_api/__init__.py
The protocol API will be the hidden implementation of the way protocols interact with the OT2 system.
It will not be interacted with directly by users; rather, they will use the backwards-compatibility shim specified in #2246 . However, splitting out the implementation in this way allows us to change the layer of separation between the protocol and the robot, and additionally restructure code to allow users to run simulations by running protocols.
This is already (somewhat, they're both stubs after all) integrated with the labware API.
Closes #2233
> feat(api): Add new protocol API stubs

- protocol-designer/src/utils/index.js
- shared-data/js/helpers/index.js
- shared-data/js/index.js
- shared-data/js/labwareTools/__tests__/createLabware.test.js
- shared-data/js/labwareTools/__tests__/example.json
- shared-data/js/labwareTools/__tests__/example2.json
- shared-data/js/labwareTools/assignId.js
- shared-data/js/labwareTools/index.js
- shared-data/js/schema.js
- shared-data/labware-json-schema/labware-schema.json
- shared-data/package.json
- yarn.lock
Closes #2175. This is the base work for creating a tool which will correctly format a labware definition for you so that we will _never_ have to handcraft a definition again 🔮. 
- Add updated JSON Schema for labware definitions 
- Add generator function to make JSON defs for regularly shaped containers (i.e. symmetric grid)
- Add in `round-to` package which is a simple way to round decimals -- may want to use this for all js projects moving forward?
- Put in ability to use function in a browser
- Remove `schema.js` and update any other files associated with old shared-data schema
- Add in labware defs with the new generator function (need to solidify new JSON schema before this can be done)
Let me know if further comments are needed in either test or the function itself. Also if there is …
> feat(shared-data): Add generator function to create regular labware defs

- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/top-selectors/substep-highlight.js
A step toward #2286
This should fix the substep highlighting bug that came along with changing substep shape (?)
and hopefully makes `substep-highlight.js` both more readable and somewhat more performant (it's still recalculating too often, but now it's doing less calculating each time)
* fix substep highlight-wells-on-hover in substep-highlight selector
* make substep/step highlighting only calculate for the currently highlighted step
* substep highlighting works for single and multi?
* step highlighting still ok?
* also works for edge cases (mix, pause, as well as all transferlikes)
> fix(protocol-designer): fix substep highlighting

- labware-designer/Makefile
- labware-designer/index.html
- labware-designer/package.json
- labware-designer/src/index.hbs
- labware-designer/src/index.js
- labware-designer/webpack.config.js
- package.json
- yarn.lock
@Laura-Danielle wrote some useful functions for creating labware, and we want to make it easier to call those functions. Eventually we want to set up a simple form, but for now we're happy with just letting people call those functions from the browser JS console.
Perhaps in the near future we will add a form to this and deploy it as a static site for internal use by support team & protocol team.
To get this running and try it out, do:
```
yarn
make -C labware-designer dev
```
Open your browser to localhost with whatever port it tells you to
Then in your browser JS console, you can use the global `sharedData` variable to use any of the functions or constants exported from `shared-data/` -- eg you can try out `sharedData.getWellTotalVolume('96-flat', 'A1')`
You can also build it with `make …
> feat(labware-designer): set up labware-designer skeleton for use in browser console

- api/opentrons/resources/jupyter/jupyter_notebook_config.py
The jupyter notebook package has a bug in 5.7.0 where specifying the notebook
application’s listening ip as ’*’ causes it to fail to boot:
https://github.com/jupyter/notebook/issues/3946
The workaround listed there is to bind the server to 0.0.0.0 instead, so we do
that here.
Closes #2394
Run on a robot and check that jupyter comes up. Already done on wolf-wolf-wolf-moon (which has notebook 5.6.0, so checking back compat) and divine-night which has 5.7.0.
> fix(api): Bind jupyter notebook to 0.0.0.0

- api/opentrons/hardware_control/__init__.py
- api/opentrons/hardware_control/controller.py
- api/opentrons/hardware_control/simulator.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
Closes #2236
This PR adds the `cache_instrument_models` method which would be used to keep track of attached pipettes. 
When in simulate mode, this method relies on the simulator knowing about the instruments attached to the robot (or mocked). The simulator needs this info while simulating a protocol in the Run app to check if correct pipettes are attached
> feat(api): add instrument cache to hardware control

- app/src/components/ConnectPanel/RobotItem.js
- app/src/components/ConnectPanel/RobotList.js
- app/src/components/ConnectPanel/RobotListItem.js
- app/src/pages/SidePanel.js
This PR closes #2362 by only showing the `Pipettes and Modules` link for selected robots in the `RobotList`.
*note: The ticket says only show sublink for connectable robots. A follow up PR will put this logic in once we have the concept of advertising but not connectable in DC.*
- feat(app): Only display instrument settings for selected robot
Standard review. I pulled out `RobotListItem` into its own file for clarity's sake.
Sorry for the style diffs, I installed Prettier atom plugin and it added the spaces to import { ... }
> feat(app): Only display instrument settings for selected robot

- components/interfaces/DeckSlot.js
- components/src/deck/LabwareContainer.js
- protocol-designer/src/components/LabwareSelectionModal/index.js
- protocol-designer/src/components/labware/ClickableText.js
- protocol-designer/src/components/labware/DisabledSelectSlotOverlay.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/components/labware/NameThisLabwareOverlay.js
- protocol-designer/src/containers/LabwareContainer.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
Refactor to clean up PD some labware components in preparation for #2335
Rename things for clarity, pass less props around, do business logic in container instead of component, etc
* Simplify & clean up LabwareOnDeck, labware overlays, and related components & types
Everything should act & appear the same.
Explicit list of things this PR touches and shouldn't change:
* Add labware, delete labware, and edit liquids still works the same
* Move labware still works the same, and causes the same changes in labware overlays
* "Copy" is still just as TODO as it was (ie,it's  not implemented and warns you that it's not implemented if you try it)
* When "Starting Deck State" is selected, the slots/labware show the editable overlays on hover, when anything else is selected (steps, or "Final Deck …
> refactor(protocol-designer): refactor PD labware components for readability

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/FileSidebar/ConnectedFileSidebar.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-data/selectors/fileFields.js
- protocol-designer/src/file-data/types.js
- protocol-designer/src/file-types.js
Closes #2189
"Created" and "last modified" fields were never implemented in PD load/save functionality, on edge it looked like:
```js
created: Date.now(),
'last-modified': null,
```
Now it should work as listed below in "review requests"
Closes #2189 
* implement 'created' and 'last-modified' file metadata fields for real
* typing workarounds for my bad flow typing decisions in making `FormConnector<FormFields>` :/
Test by examining the saved JSON in text editor.
> feat(protocol-designer): implement "metadata.created" in JSON file

- app-shell/src/__tests__/discovery.test.js
- app-shell/src/discovery.js
- app/src/discovery/index.js
- discovery-client/Makefile
- discovery-client/package.json
- discovery-client/src/__fixtures__/mdns-browser-service.js
- discovery-client/src/__fixtures__/service.js
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/__tests__/poller.test.js
- discovery-client/src/__tests__/service-list.test.js
- discovery-client/src/__tests__/service.test.js
- discovery-client/src/index.js
- discovery-client/src/poller.js
- discovery-client/src/service-list.js
- discovery-client/src/service.js
- discovery-client/src/types.js
Internal users reported strange discovery-client bugs where the standalone CLI discovery-client was able to find robots but the app was unable. We were able to track this down to a problem with the app's cached discovery lists.
This PR updates the DC to sanitize its input list of known services (where the app's cache is passed in) and do continue to dedupe the list whenever it is updated. As a result, we have an actual guarantee that `client.services` will only ever:
- Have a single entry per IP
- Have a single entry where `ip: null` for a given `name`
- fix(discovery-client): Ensure IPs are actually de-duped 
Make sure the discovery list behaves in both the CLI and the app. Things that have tripped us up in the past:
- Discovery health state latching when it shouldn't
- …
> fix(discovery-client): Ensure IPs are actually de-duped

- labware-designer/README.md
- shared-data/js/labwareTools/assignId.js
- shared-data/js/labwareTools/index.js
- shared-data/labware-json-schema/labware-schema.json
Closes #2382. This PR is meant to add more detail on how to use the generator, and what each term in the schema actually represents.
- Adds descriptive README in `labware-designer` on how to use the generator function in the browser
- Addresses changes previously requested by @mcous 
- Adds descriptors to keys in the labware schema
Let me know if anything looks confusing!
> chore(api): Add README on using generator function

- discovery-client/__mocks__/mdns-js.js
- discovery-client/src/index.js
- discovery-client/src/mdns-browser.js
- flow-typed/npm/mdns-js_v1.0.x.js
We use the [`mdns-js`](https://github.com/mdns-js/node-mdns-js) library as out underlying mDNS client for robot discovery. It turns out, this module asyncronously (i.e. uncatchably) throws instead of emitting an error when it encounters a TLD in an advertisement name it doesn't expect (mdns-js/node-mdns-js#78). `mdns-js` only expects a TLD of `.local`.
From user reports, there are definitely devices out in the wild (not our robots) that advertise with TLDs that are not `.local`, and because of the throw, if one of those devices is on the network, the `discovery` client CLI will die on the uncaught throw.
- fix(discovery-client): Monkeypatch async throw in mdns-js
> fix(discovery-client): Monkeypatch uncatchable throw in mdns-js

- api/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
Expose labware accessor functions in the new labware class. In total there are six accessor functions as follows:
- `wells()`: returns a `List[Well]` in a predictable order (order should match `Placeable.wells`)
- `wells_by_index()`: returns a `Dict[Well]` where the keys are well names (e.g.: "A1", "A2", ...) and the values are Well instances
- `rows()`: returns a `List[List[Well]` where each inner list represents a row of wells
- `rows_by_index()`: returns a `Dict[List[Well]]` with alphabetical keys ("A", "B", ...) and values as in `rows`
- `columns()`: returns a `List[List[Well]` where each inner list represents a column of wells
- `columns_by_index()`: returns a `Dict[List[Well]]` with numeric string keys ("1", "2", ...) and values as in `columns`
Closes #2264. 
- Add functions …
> feat(api): Add accessor functions in new labware class

- protocol-designer/src/analytics/actions.js
- protocol-designer/src/analytics/index.js
- protocol-designer/src/analytics/integrations.js
- protocol-designer/src/analytics/reducers.js
- protocol-designer/src/analytics/selectors.js
- protocol-designer/src/components/SettingsPage/Privacy.js
- protocol-designer/src/components/modals/AnalyticsModal.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/index.js
- protocol-designer/src/persist.js
- protocol-designer/src/types.js
This is prep work for #2333 - we're gonna be needing to sync some hand-picked pieces of redux state with localStorage.
I tried a version of this with https://github.com/rt2zz/redux-persist but for PD, I didn't like how much that library is oriented towards persisting large swaths of state. We just want a few small selected pieces, usually at the deepest level of reducer nesting. No other libraries I saw seemed like a good fit, so I reluctantly rolled my own.
**To make a new reducer be persisted:**
- In that reducer, when you get `REHYDRATE_PERSISTED` action, return the result of the `rehydrate` function
- Add that reducer to the `PERSISTED_PATHS` array in `persist.js`
As a proof of concept, and to avoid having 2 different ways of interacting with localStorage, I refactored `analytics/` …
> feat(protocol-designer): implement selective redux persistence

- app/src/components/controls/styles.css
- app/src/components/portal/index.js
#2067 added a Portal-based modal to the app and moved the initial analytics pop-up to that portal. However, if the portal modal was used during the first render (e.g. for the analytics opt-in modal), the
modal root would not be present in the DOM since the root itself is created by the App component. This would then cause the modal to fail to appear.
This PR refactors the Portal component to be stateful in order to a) cache the root
component instead of getting it from the document on every render and b) retry getting the root
after mounting, when we're sure (read: pretty sure) the root is also actually mounted in the DOM
The proper, long-term solution would be to prerender our markup, so this fix should be considered a stop-gap until we do so.
- fix(app): Allow portal …
> fix(app): Allow portal to re-check for root element

- app/src/components/FileInfo/ProtocolLabwareCard.js
Closes #2407. See ticket for relevant details and acceptance criteria
- fix(app): Use labware.type for labware table, not labware.name
See #2407
> fix(app): Use labware.type for labware table, not labware.name

- components/src/styles/borders.css
@howisthisnamenottakenyet wanted to try out changing the default border width from 2px to 1px. This most visibly changes the nav, and PD's list dividers.
It's a 1-character code difference, so this is mostly a design review. It affects both Protocol Designer and Run App.
Please note if the thinner border looks weird anywhere, or if any 2px borders are showing up where they shouldn't.
**Components:** https://s3-us-west-2.amazonaws.com/opentrons-components/components_change-default-border-width/index.html
**PD:** http://opentrons-protocol-designer.s3-website-us-west-2.amazonaws.com/components_change-default-border-width/
**Run App installer:**
* (Windows) https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.4.0-win-b7654-components_change-default-border-width.exe
* (Mac) …
> feat(components): change default border width to 1px

- app/src/components/ConnectPanel/RobotItem.js
- app/src/components/ConnectPanel/RobotListItem.js
- app/src/components/ConnectPanel/index.js
- app/src/discovery/__tests__/selectors.test.js
- app/src/discovery/index.js
- app/src/discovery/selectors.js
- app/src/discovery/types.js
- app/src/http-api-client/server.js
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/cli.js
- discovery-client/src/index.js
- discovery-client/src/mdns-browser.js
- discovery-client/src/service-list.js
- flow-typed/npm/mdns-js_v1.0.x.js
This PR lays the groundwork for #2345 by splitting up the `discovery` selectors into:
- `getConnectableRobots` - Gets all connectable robots
- `getReachableRobots` - Gets all robots that are reachable but not connectable
- `getUnreachableRobots` - Gets all robots that are not reachable
- refactor(app): Organize robots by connectable, reachable, unreachable
Known issue: this PR will (temporarily) break the robot list ordering
> refactor(app): Organize robots by connectable, reachable, unreachable

- api/opentrons/server/endpoints/wifi.py
- api/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_wifi_endpoints.py
Adds a displayName field to eap options:
`GET /wifi/eap-options`
```
200 OK
{
"options": [
{
"name": "ttls/eap-tls",
"displayName": "EAP-TTLS with TLS",
"options": [
{
"name": "identity",
"displayName": "Username",
"required": true,
"type": "string"
},
{
....
```
Closes #2439
> feat(api): Add a displayName field to EAP types in /wifi/eap-options

- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/LiquidsPage/index.js
- protocol-designer/src/components/LiquidsSidebar/index.js
- protocol-designer/src/components/SettingsPage/SettingsSidebar.js
- protocol-designer/src/containers/ConnectedMainPanel.js
- protocol-designer/src/containers/ConnectedNav.js
- protocol-designer/src/containers/ConnectedSidebar.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/localization/en/nav.json
- protocol-designer/src/navigation/types.js
Closes #2426
* liquids page stub
* liquids sidebar
* use i18n more for nav/titlebar; clean up nav.json
In this sprint we've broken up the changes to creating & editing liquids into several tickets, until they're all done the experience will be incomplete. This just introduces a functional new page with nav tab. 
- Note this user story does not include instructional content in right panel
This PR also re-organizes the internationalization for tabs + title bar, nothing visual should be changed (except that main title is now consistently "Protocol Designer Beta" to match designs.
> feat(protocol-designer): add liquids tab and sidebar

- api/docs/source/labware.rst
Incorrectly formatted whitespace caused a code block in the labware documents to not show up
- docs(api): Fix whitespace in code block for delete_container docs
Ensure that the code block for `delete_container` shows up under the labware page of the docs
> docs(api): Fix whitespace in code block for delete_container docs

- app/src/components/ConnectPanel/RobotListItem.js
- app/src/components/ConnectPanel/UnreachableRobotItem.js
- app/src/components/SessionHeader/index.js
- app/src/discovery/__tests__/selectors.test.js
- app/src/discovery/selectors.js
- app/src/discovery/types.js
- app/src/pages/Robots/InstrumentSettings.js
- app/src/pages/Robots/RobotSettings.js
closes #2357 by creating a `displayName` which strips out 'opentrons-' and preserving `name` as is.
- feat(app): Remove 'opentrons-' prefix in robot displayNames
> TitleBar
in RobotSettings and InstrumentSettings pages displays displayName
> feat(app): Remove 'opentrons-' prefix in robot displayNames

- .travis.yml
- CHANGELOG.md
- api/opentrons/CHANGELOG.md
- api/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- scripts/travis-env.sh
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Beta release mostly for the [robot list milestone](https://github.com/Opentrons/opentrons/milestone/68)
https://github.com/Opentrons/opentrons/compare/edge...d480b068d4faac9c3adb163e5574a92bf7ba44e7
Standard beta release testing. Thanks to some travis changes in this PR, builds on this (and future) `release_*` branches will be fully signed on mac, so can actually function as an RC build.
@umbhau please give the release notes a 👁
> chore(release): 3.5.0-beta.0

- api/docs/source/api.rst
- api/opentrons/legacy_api/instruments/pipette.py
- api/opentrons/legacy_api/robot/robot.py
> fix(api): Fix docs build failure after move to legacy_api

- app/src/components/RobotSettings/ControlsCard.js
- app/src/components/RobotSettings/index.js
closes #2377
- feat(app): Move deck calibration to robot controls
Please check that deck calibration works on a robot.
> feat(app): Move deck calibration to robot controls

- api/src/opentrons/server/endpoints/networking.py
- api/src/opentrons/server/http.py
- api/src/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_networking_endpoints.py
This PR replaces the unused `GET /wifi/status` with `GET /networking/status` which returns:
- Internet connectivity status
- IP/MAC/Gateway addresses, device type, and connection state of all networking interfaces defined in the `nmcli.NETWORK_IFACES` enum (`eth0` and `wlan0`)
- feat(api): Add /networking/status endpoint to get all interface info
- Also renames `wifi.py` to `networking.py`
This branch has been pushed to 🌆 so you can test via postman: `GET /networking/status`
Otherwise, please check that the code + unit test changes are sane.
> feat(api): Add /networking/status endpoint to get all interface info

- .gitattributes
For a while, even after changing .gitattributes once or twice, I've been having problems with switching branches when .hex files have been updated. I think our .gitattributes was wrong
This causes a problem on my machine where I have to do a crazy dance in git every time I checkout a branch that has a change in a hex file. Git will convert the line endings, then `git checkout -- .` or `git reset HEAD` or `git stash` don't get rid of the changed file, and the presence of the changed file doesn't let me switch branches.
I find the docs for gitattributes pretty hard to understand, but I think to fix this problem, we need to unset both text and diff `-text -diff` and the [special macro `binary`](https://git-scm.com/docs/gitattributes#_using_macro_attributes) does exactly that while also being …
> fix(repo): fix gitattr hex bug

- protocol-designer/src/components/StepEditForm/FlowRateField/FlowRateField.js
- protocol-designer/src/components/StepEditForm/TipPositionInput/TipPositionModal.js
- protocol-designer/src/components/StepEditForm/TipPositionInput/TipPositionZAxisViz.js
- protocol-designer/src/components/steplist/utils.js
Closes #2405 chore
We've been rounding all wrong! `.toFixed` [isn't reliable](https://bugs.chromium.org/p/chromium/issues/detail?id=778669&can=1&q=tofixed&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) for rounding to fixed precision, so this PR replaces it with lodash's `round` which [uses](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L5434) exponent notation to avoid the floating-point conversion issues.
This is more of a housekeeping best practice chore than fixing actual bugs -- I think to get a bug, you'd have to load a JSON protocol that has its step fields (not even commands, but step fields) edited to add more decimals than allowed. This might be a practical case if we ever increase then decrease allowed decimals for …
> feat(protocol-designer): implement rounding properly

- app-shell/package.json
- app-shell/src/api-update.js
- app/src/discovery/__tests__/selectors.test.js
- app/src/discovery/selectors.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/server.js
Turns out `GET /server/update/health` can return the string "not available" (instead of something like `null`) if it can't figure out its own version. The app wasn't properly sanitizing its API responses, so the switchover to prefering `/server/update/health` to `/health` (implemented in #2462) introduced `throw` path via the `semver` module.
- fix(app): Check semver validity of API returned version strings 
I will configure 🌆's update server to respond incorrectly, so please check that the app no longer whitescreens.
Followup: would love to talk error boundaries with all of @Opentrons/js
> fix(app): Check semver validity of API returned version strings

- api/src/opentrons/system/nmcli.py
- api/tests/opentrons/system/test_nmcli.py
Closes #2489. See ticket for bug details and what this fix does.
- fix(api): Filter out missing SSIDs from network list
> fix(api): Filter out missing SSIDs from network list

- CHANGELOG.md
- api/Pipfile.lock
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Release 3.5.0-beta.1
https://github.com/Opentrons/opentrons/compare/v3.5.0-beta.0...8d6e3e4342ed3db6c4ffe265a524501626349ba0
Standard beta release review. RC builds:
- [Windows 3.5.0-beta.1 RC](https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.5.0-beta.1-win-b8134-release_3.5.0-beta.1.exe)
- [macOS 3.5.0-beta.1 RC](https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.5.0-beta.1-mac-b12094-release_3.5.0-beta.1.zip)
- [Linux 3.5.0-beta.1 RC](https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.5.0-beta.1-linux-b12094-release_3.5.0-beta.1.AppImage)
> chore(release): 3.5.0-beta.1

- Makefile
- api/Makefile
- update-server/Makefile
Pipenv sync was added here: https://github.com/pypa/pipenv/issues/1463 and had a
subsequent bug in it where it would sometimes update pipfile.lock, but that’s
fixed now.
There’s now a solid three part workflow to pipenv, as there should be:
- If you want to change the dependencies of a project, you use pipenv
install/uninstall or edit Pipfile
- When you want to crystallize those dependencies and check in, you use pipenv
lock to generate the lockfile
- When you want to install the dependencies, as in when you checkout from scm,
you use pipenv sync
Please checkout and run `make install` (top level `make install`) and then `make -C api test`.
> chore(api): Update pipenv and use pipenv sync

- shared-data/js/labwareTools/__tests__/createLabware.test.js
- shared-data/js/labwareTools/index.js
It was brought to my attention by @sfoster1 that the `cornerOffsetFromSlot` key was missing from both generated labware defs. This PR is meant to add a check on the labware schema to make sure that no required keys are forgotten.
- Raise error if generator function does not create a valid schema definition.
> feat(api): Add error checking on generated labware def

- components/src/modals/AlertModal.js
- components/src/modals/AlertModal.md
This PR addresses #2507 by adding an optional `iconName` prop to override the alert icon in AlertModal headings
-refactor(components): Add `AlertModal` heading icon override
> refactor(components): Add AlertModal heading icon override

- app/src/components/RobotSettings/ConnectionCard.js
- app/src/components/RobotSettings/SelectNetwork.js
- app/src/components/RobotSettings/connection.js
- app/src/http-api-client/networking.js
- components/src/interaction-enhancers/IntervalWrapper.js
Closes #2383 and closes #2348. See tickets for behavior and acceptance criteria
- refactor(app): Add connnect to unsecured on select to ConnectionCard
1. Launch app with new connection card enabled
```shell
make -C app dev OT_APP_DEV_INTERNAL__MANAGE_ROBOT_CONNECTION__NEW_CARD=1
```
2. Select an open network in the new connection card dropdown
We've got an unsecured WiFi AP set up in the office right now for testing this PR
> refactor(app): Add connnect to unsecured on select to ConnectionCard

- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_offsets.py
Closes #2269 and  closes #2270.
- Add save calibration function for any new deltas from labware calibration
- Add load calibration function to check for any previously saved deltas.
- Changed accessor functions such that they only use 1 instance of a well object _unless_ a new offset is added.
> feat(api): Add ability to save new delta from calibrating labware

- components/src/constants.js
- components/src/tooltips/HoverTooltip.js
- components/src/utils.js
- protocol-designer/src/components/steplist/AspirateDispenseHeader.js
- protocol-designer/src/components/steplist/LabwareTooltipContents.js
- protocol-designer/src/components/steplist/MixHeader.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/components/steplist/StepList.js
- protocol-designer/src/components/steplist/SubstepRow.js
- protocol-designer/src/components/steplist/TooltipPortal.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/utils.js
- protocol-designer/src/step-generation/utils.js
Because of the cramped space on the step list, it is often the case that the labware name is
truncated. For enhanced context, this adds a tooltip that launches on hover of the labware name and
displays the full name and labware type.
Closes #2421
> feat(protocol-designer): add tooltip for labware name/type on steplist

- protocol-designer/src/components/StepEditForm/WellOrderInput/index.js
- protocol-designer/src/localization/en/form.json
Sorry!
* fix forms.json in localization
- All form labels and content should show correct text
> fix(protocol-designer): fix localization refactor mistakes

- api/Makefile
- api/normalized_version.py
Instead of using all phony targets, the makefile now pulls the version out of
package.json so it can find the name of the wheel that will be built and can use
it as a normal Makefile target. Then, we can use that as the prereq for wheel
instead of having wheel contain the commands directly, which means that all the
stuff that now depends on wheel won’t rerun it every single time it’s called.
Let's see what CI does, and please test the following on osx, windows, and linux:
> fix(api): Make the Makefile have more real prerequisites/targets

- .flowconfig
Our Travis builds keep failing due to Flow merge timeout, let's see if this helps.
* attempt to fix timeout in Travis by increasing flow merge timeout from 100s to 300s
Build should pass, but just because it passes doesn't mean 300s is enough since it's variable :/
> fix(repo): increase flow merge timeout

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/config/robot_configs.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/hardware_control/types.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocols/__init__.py
- api/src/opentrons/server/endpoints/control.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/test_instantiation.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_modules.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/server/calibration_integration_test.py
- api/tests/opentrons/server/test_control_endpoints.py
Closes #2235
This PR adds aspirate and dispense functions to `hardware_control`
Changed instruments cache from being a cache of pipette model to being a cache of all pipette config values
Added:
- `aspirate(mount: types.Mount, volume: float = None, rate: float = 1.0)`
- `dispense(mount: types.Mount, volume: float = None, rate: float = 1.0)`
- Method to retrieve pipette properties: `attached_instruments`
- backend methods: `set_active_current()`, `set_pipette_speed()`, `Controller._connect()`
> refactor(api): refactor aspirate/dispense

- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
Closes #2523. See ticket for background.
- feat(app): Show all labware of same type as confirmed
I used this protocol for testing: https://drive.google.com/file/d/19N5Zajll26FT6FIqRx2iv5H7IyWNOxFt/view?usp=sharing
> feat(app): Show all labware of same type as confirmed

- protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.js
- protocol-designer/src/components/LiquidPlacementForm/index.js
- protocol-designer/src/labware-ingred/actions.js
Closes #2430 - now the button does something
* implement "clear wells" button
> feat(protocol-designer): implement "clear wells" button

- app/src/components/RobotSettings/connection.js
- app/src/components/RobotSettings/styles.css
This PR overrides default react-select styles to match design screens.
- refactor(app): Match wifi dropdown styles to design
Standard review. I ran into an unstylable DOM element in `react-select`. See my comment in `styles.css`.
To view the new card:
`make -C app dev OT_APP_DEV_INTERNAL__MANAGE_ROBOT_CONNECTION__NEW_CARD=1`
> refactor(app): Match wifi dropdown styles to design

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/protocols/__init__.py
- api/src/opentrons/server/endpoints/control.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/hardware_control/test_pipette.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/server/test_control_endpoints.py
Add critical point tracking to the hardware control API.
This layer keeps track of whether a pipette or tip is attached in a given mount, and makes the `move_to` method do "the right thing".
The `move_to` moves the critical point of the specified mount to a location. We define the critical point as:
- The mount, or a location convenient to the mount (Right now, the bottom of a P300 single for legacy reasons - open to change here) if there is no pipette attached
- The end of the nozzle of a single pipette or the end of the +Y-most nozzle of a multi pipette if a pipette is attached but has no tip
- The end of the tip of a single pipette or the end of the tip of the +y-most nozzle of a multi pipette if a tip is attached
So doing a `move_to` to the same point for the same mount interspersed …
> feature(api): pipette critical points

- api/src/opentrons/server/endpoints/networking.py
- api/tests/opentrons/server/test_networking_endpoints.py
The API response from `GET /wifi/keys` did not match what was in the documentation nor what was in the spec listed on the PR that added the endpoint (#2254). This PR fixes the endpoint to match the expected output.
Due to the fact that this went out in `v3.4.0`, the client is going to need to work around malformed responses for this endpoint to handle EAP with certificates for older robots gracefully.
- fix(api): Correct GET /wifi/keys response to match documentation
Please check that `GET /wifi/keys` returns a response that looks like `{"keys": [...]}`. This code has been pushed to 🌆
> fix(api): Correct GET /wifi/keys response to match documentation

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/localization/en/button.json
Closes #2534
- Change "Continue to Design" button at the bottom of the file page to "Continue to Liquids"
- Change button destination to liquids tab
> feat(protocol-designer): continue to liquids not design page

- protocol-designer/src/well-selection/reducers.js
> fix(protocol-designer): close liquid placement form when clear wells is clicked

- protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.js
Oops! I wrote `onBlue` instead of `onBlur` so errors were not being shown in LiquidPlacementForm on blur (when user un-focuses the field) but only when they clicked "save".
BUT - I am not sure which is actually the desired behavior for this form: to mask errors until user clicks "save" (existing behavior on edge due to the `onBlue` typo), or to mask errors only until user focuses and un-focuses a field without waiting for them to click "save" (new behavior, this PR)
Since there are only 2 fields in this form, the behavior difference is very subtle.
* fix onBlur typo in LiquidPlacementForm - this makes it so you see errors before clicking "save"
- Is this fix desirable? If not I can tweak this PR so that there are no `onBlur`s which will give us the behavior on `edge`
> fix(protocol-designer): fix LiquidPlacementForm onBlur typo

- protocol-designer/src/step-generation/blowout.js
- protocol-designer/src/step-generation/dispenseUpdateLiquidState.js
- protocol-designer/src/step-generation/dropTip.js
- protocol-designer/src/step-generation/test-with-flow/blowout.test.js
- protocol-designer/src/step-generation/test-with-flow/dispenseUpdateLiquidState.test.js
- protocol-designer/src/step-generation/test-with-flow/dropTip.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
Closes #2498
Prevents adding `__air__` on blowout and drop tip
Before (edge, with example protocol below, final deck state hovering on well F12):
After:
This is all about reusing code that does almost the same thing but not quite. The step-generation function blowout, dropTip, and dispense all update their liquid state via `dispenseUpdateLiquidState`. Both blowout and dropTip effectively want "dispense all the volume within each tip on the pipette" while dispense always uses an explicit volume (it permits over-dispensing but maybe we shouldn't even permit that). Instead of making another `dispenseFullVolumeUpdateLiquidState` fn with similar code, I added new argument `useFullVolume` to `dispenseUpdateLiquidState`, which dropTip and blowout use.
This also fixed an inconsistency in …
> fix(protocol-designer): do not add __air__ on blowout

- api/src/opentrons/config/containers/default-containers.json
This PR is also acting as a bug report. The 1000ul tip rack height is too low (by 16mm), causing a collision when trying to calibrate the tip rack. This PR increases the height of p1000 tip rack to 101mm, and remove unsupported definitions left over from OT1.
- fix(api): increase height of p1000 tip rack definition
- refactor(api): remove unsupported tip rack definitions related to OT1
Protocol:
```
from opentrons import labware, instruments
tr = labware.load('tiprack-1000ul', '1')
plate = labware.load('96-flat', '2')
p = instruments.P1000_Single(mount='right', tip_racks=[tr])
p.pick_up_tip()
p.aspirate(100, plate[0])
p.dispense(plate[1])
p.drop_tip()
```
> fix(api): Fix height of p1000 tip rack definition

- .gitignore
- CHANGELOG.md
- app-shell/.gitignore
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
> chore(release): 3.5.0

- app/src/components/RobotSettings/RobotUpdateModal.js
The robot update modal is supposed to show the release notes of the software version the app is _currently_ at, because that's the wheel file it as. Instead, the app was incorrectly showing the release notes of the latest (or beta, depending on the selected channel) app release, whether or not that update had been applied.
This PR pulls the robot changelog from the correct place.
- fix(app): Show the correct release notes for robot update
> fix(app): Show the correct release notes for robot update

- app/src/components/RobotSettings/SelectNetwork/ConnectForm.js
- app/src/components/RobotSettings/SelectNetwork/ConnectFormField.js
This PR adds validation to Wifi Auth forms. closes #2416 
Tagged as refactor, behind feature flag.
Form is pristine, submit disabled
Required form field `touched` but empty
Min char of 8 for WPA2 passwords
Form validated submit enabled
- refactor(app): Add validation to network auth forms
To enable new connectivity card:
`make -C app dev OT_APP_DEV_INTERNAL__MANAGE_ROBOT_CONNECTION__NEW_CARD=1`
Please double check EAP/PEAP on network in office!
> refactor(app): Add validation to network auth forms

- api/src/opentrons/legacy_api/instruments/pipette.py
- api/tests/opentrons/drivers/test_driver.py
Fix bug where the pipette-specific drop-tip current values form the config are not used while actually dropping-tip.
> fix(api): Fix bug where drop-tip current is not used during drop-tip

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/types.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
Some key changes to instrument handling and homing in hardware_control
These became increasingly necessary as I was doing other things and should be split into their own PR.
There must be a way for callers to specify instruments they expect to be attached when they are simulating. This could previously only be done when initializing a simulator; now, this can be expressed in the call to `hardware_control.API.cache_instruments()` (which also saves a second step of verifying that the result of `cache_instruments()` fits requirements):
```python
>>> api = opentrons.hardware_control.API.build_hardware_simulator()
>>> api.cache_instruments({opentrons.types.Mount.LEFT: 'p10_single'}) # always results in loading a p10 single
>>> api.cache_instruments({opentrons.types.Mount.LEFT: 'p300_single'}) …
```
> API: hardware_control/protocol api integration

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/tools/write_pipette_memory.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/hardware_control/test_pipette.py
- api/tests/opentrons/server/test_control_endpoints.py
Include pipette id in GET /pipettes response. Closes #2148 
- feat(api): Pipette id included in GET /pipettes
Make sure Run App UI doesn't break
> feat(api): Pipette id included in GET /pipettes

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
Closes #2483
- added `blow_out(mount)`, `pick_up_tip(mount, presses, increment)`, drop_tip(mount)`
- changed all `move` methods to accept move speed. This enables us to implement `touch_tip` in protocol_api using only hardware_control `move`s
- added pick_up_tip test
Test the three functions on a robot. 
Example test:
```
>>> import opentrons.hardware_control as hc
>>> import asyncio
>>> import opentrons.types as t
>>> l=asyncio.get_event_loop()
>>> a=hc.API.build_hardware_controller()
>>> l.run_until_complete(a.home())
>>> l.run_until_complete(a.cache_instruments())
>>> l.run_until_complete(a.move_to(t.Mount.LEFT,t.Point(11.6,75,63)))  # rough loc of first tip of P300 tiprack in slot 1
>>> l.run_until_complete(a.pick_up_tip(t.Mount.LEFT))
>>> …
```
> refactor(api): add blow_out, pick_up_tip, drop_tip

- api/src/opentrons/server/endpoints/networking.py
- app/src/components/RobotSettings/SelectNetwork/ConnectForm.js
- app/src/components/RobotSettings/SelectNetwork/ConnectFormField.js
- app/src/components/RobotSettings/SelectNetwork/SelectKey.js
- app/src/components/RobotSettings/SelectNetwork/SelectSsid.js
- app/src/components/RobotSettings/SelectNetwork/index.js
- app/src/components/RobotSettings/SelectNetwork/styles.css
- app/src/components/SelectField/index.js
- app/src/components/SelectField/styles.css
- app/src/http-api-client/networking.js
- components/src/forms/forms.css
This PR closes #2415. See ticket for acceptance criteria. `refactor` because behind feature flag.
- refactor(app): Enable certificate usage with 802.1x
We have an EAP network in the office, which we're working on getting set up with certificate auth. Will ping Slack when it's ready, but until then please check out the code + UI.
Still trying to figure out how caption and padding should interact:
- Current component library form fields have a div for caption that is always rendered, regardless of whether or not there's a caption to render
- That div has a height (via padding), which ends up kind of being an intrinsic padding for all CL form fields, only it cannot be overridden
- Until then, the padding + caption of the `SelectField` component (which is currently app-only) looks different …
> refactor(app): Enable certificate usage with 802.1x

- api/docs/source/new_protocol_api.rst
- api/src/opentrons/__init__.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/deck_calibration/dc_main.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/back_compat.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/test_adapters.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_labware_load.py
This has a lot of backend work to prepare the protocol API for actually interacting with hardware.
We can now load instruments; we can use the backwards-compatibility layer to do it; and we can call move, aspirate, and dispense on them.
In addition, there is now (autogenerated) documentation for the protocol API. It is not included in the doctree but can be accessed at
${docsroot}/new_protocol_api.html once built.
Particular things to check out in this (admittedly probably too large) PR aside from the main event:
- [AddInstrumentCtors](https://github.com/Opentrons/opentrons/blob/4ce1f295948004e1e2cede0ec9addf614cd043a0/api/src/opentrons/protocol_api/back_compat.py#L74-L163) in the back_compat shim. This builds the old pipette constructors (like `instruments.P300_Single` dynamically. …
> API: Add motion to protocol API

- components/src/forms/forms.css
This PR is also a ticket for a refactor. 
An empty div with padding top and a min-height always rendered below all `InputFields` and `DropdownFields`. This was attempting to avoid jumpiness when errors were rendered. Due to border box box-sizing, padding was included in the min-height = jumpiness still existed on error, and the 10px high div wound up being the default vertical spacing for input elements.
- Lower captions are not present in the app currently, and are only present in FlowRate input field. *Not an issue yet with vertical spacing in forms, but captions will affect applied row spacing*
- refactor(components): Update error and caption styles
-  PD forms spacing (form row) was taking this 10px into account. Follow up PR will be needed to fix some form row spacing.
- App forms …
> refactor(components): Update error and caption styles

- app/src/components/TipProbe/RemoveTipPanel.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/test/actions.test.js
This PR closes #2544. Long story short, now whenever you click 'confirm tip removed' at the end of the tip probe sequence, the pipette homes up and out of the way.
- feat(app): Home pipette after tip probe confirmed
Please test on a robot
> feat(app): Home pipette after tip probe confirmed

- api/src/opentrons/server/endpoints/networking.py
- app/src/components/RobotSettings/SelectNetwork/ConnectForm.js
- app/src/components/RobotSettings/SelectNetwork/ConnectModal.js
- app/src/components/RobotSettings/SelectNetwork/SelectKey.js
- app/src/components/RobotSettings/SelectNetwork/SelectSecurity.js
- app/src/components/RobotSettings/SelectNetwork/SelectSsid.js
- app/src/components/RobotSettings/SelectNetwork/index.js
- app/src/components/RobotSettings/SelectNetwork/styles.css
- app/src/components/SelectField/index.js
- app/src/components/SelectField/styles.css
- app/src/http-api-client/networking.js
This PR closes #2553, so please see the ticket for acceptance criteria. Unknown security type will happen in two main instances:
- Robot is out of data (<= 3.3.0) and does not report network security type
- SSID is hidden
- To be fully completed in #2182 
This PR (mainly) adds a new `SelectSecurity` component to display a `SelectField` with either all available security types or just the EAP security types depending on what information is known about a given network and a given robot's supported EAP methods.
- refactor(app): Allow user to specify wifi security type if unknown
- 🌆 is currently loaded with API v3.3.0, so it should:
- Not report any security types for WiFi networks
- Not report any supported EAP types
- Test plan
- To test completely unknown (e.g. a hidden network), you can …
> refactor(app): Allow user to specify wifi security type if unknown

- api/docs/source/new_protocol_api.rst
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/types.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_back_compat.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_geometry.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_offsets.py
The motion commands in the protocol API take a new type, Location, which has a
reference to a labware or well it is related to. This labware or well is used by
a new function, geometry.plan_arc, to break down individual motion commands into
either arc or direct moves depending on if the target is in the same well or
labware as the target of the last move.
In addition, change the Well class position accessors (top(), bottom(),
center()) to return a Location instead of just a Point, and build Wells with
references to their parent Labwares.
This is a prerequisite for #2242 and was blocking the implementation of #2271 so it is split into its own PR.
To test, put onto a robot, put tips on the pipettes, change the pipette models in the script to your pipettes, and run this:
```python
from …
```
> refactor(api): Change motion target locations and add arcs

- protocol-designer/src/components/SettingsPage/SettingsPage.css
- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionInput.js
- protocol-designer/src/components/StepEditForm/WellSelectionInput/index.js
- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/pipettes/reducers.js
- protocol-designer/src/pipettes/selectors.js
- protocol-designer/src/steplist/fieldLevel/errors.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/selectors.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/well-selection/reducers.js
Deprecate old validation logic lingering in stepFormToArgs and protect from invalid arg creation by passing formData through field and form level errors getters.
Remove error block from stepFormToArgs functions. Clean up hydration pathways.
Closes #2485
- split out pipette reducer
- hydrate forms before they hit stepFormToArgs, remove context param
- show warning icon on ConnectedStepItem if that step has a form or field level error
- still block save on field and form level errors, but now only use new validation logic (in `fieldLevel` and `formLevel`)
> refactor(protocol-designer): gate timeline generation with form and field validation

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/protocol_api/test_context.py
There were a couple issues with #2598 that didn't affect functionality and didn't seem worth further delay (since that PR was blocking others). This PR fixes them, specifically
- Re-adding the ability for `aspirate` and `dispense` to take a Well as a location
- Removing `ProtocolContext.move_to` and moving its functionality to `InstrumentContext.move_to`
- Moving the responsibility for retracting a mount when switching between which mount is being moved to `hardware_control`
```python
import asyncio
import opentrons.hardware_control as hc
from opentrons.types import *
a = hc.API.build_hardware_controller()
l = asyncio.get_event_loop()
l.run_until_complete(a.home())
l.run_until_complete(a.move_to(Mount.LEFT, Point(20, 20, 100)))
l.run_until_complete(a.move_to(Mount.RIGHT, Point(40, 20, …
```
> API: consolidate motion functions and fix some small design issues

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/tests/opentrons/hardware_control/test_moves.py
Add out-of-bounds move checks to gantry axes.
This checks for out of bound moves, where the bounds are defined as (0, home_position) in smoothie coordinates, to gantry axis motions. These are checked in smoothie coordinates before the move is sent to the smoothie. If a move is out of bounds, we raise a RuntimeError with a reasonably human readable message.
The positions are checked after all transforms, meaning that different points are reachable depending on
- whether a pipette is attached to a given mount
- what kind of pipette it is
- whether it has tips
For instance, moving to (50, 50, 0) with the right mount when no pipette is attached (or a p300 single without a tip is attached) is out of bounds - that transforms to roughly (50, 50, -25.6) with a proper deck calibration. When a tip …
> API: add out of bounds move checks to hardware_control

- api/src/opentrons/legacy_api/containers/__init__.py
- api/tests/opentrons/database/test_labware_definitions.py
Correct well ordering for custom labware (definitions created using `labware.create`) to iterate over columns instead of rows. Fixes #2631 
- fix(api): correct well ordering for custom labware
Just take a look at the tests and fix. Pretty self-explanatory.
> fix(api): Correct well ordering for custom labware

- api/docs/source/labware.rst
- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
Closes #2583 - adds labware from docs.opentrons.com to PD
* Excluding `point`
* Adding `48-well-plate`!
* add labware from docs.opentrons.com to PD
* fix labware typo in API docs
NOTE: bug #2632 is separate, the 'Tip Racks' won't show up because of it. It's out of scope for this PR (would mess with other PRs in flight).
> feat(protocol-designer): add more labware options to PD

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/types.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/hardware_control/test_pipette.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_offsets.py
This PR causes the protcol_api and hardware_control to use the tip length from tip racks instead of from the pipette config. It also causes Well object to have a boolean flag indicating whether or not there is a tip present, and adds methods on `protocol_api.labware.Labware` and protocol_api.contexts.InstrumentContext` to select the next available tip for `pick_up_tip`, taking into account the number of tips the user is attempting to pick up and the number of channels of the pipette. Closes #2271 
- Use tip length from tip rack throughout `protocol_api`
- Add tip tracking to `protocol_api.labware` classes
- Add tip selection logic to `protocol_api.labware.Labware` and `protocol_api.contexts.InstrumentContext`
- Track tip length in `hardware_control.pipette.Pipette` instead of just a …
> refactor(api): tiplength from tiprack

- protocol-designer/src/components/steplist/StepList.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/index.js
- protocol-designer/src/steplist/actions/thunks.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/test/reducers.test.js
Serves as its own ticket.
This lets us play around with re-ordering steps. The feature will be hard to discover, in part because we don't want people to use it heavily right now. But we can tell select users that this is available to unblock them.
* implement key combo to reorder steps
* unit test for orderedSteps reordering
To try it:
1. Select a step in the step list
2. Use Alt +⬆ to move it UP in the list, use Alt + ⬇ to move it DOWN in the list
3. ??? Profit :man_cook:
> Sneaky key combo for hidden step reordering feature

- app/webpack.config.js
- labware-designer/webpack.config.js
- protocol-designer/webpack.config.js
- protocol-library-kludge/webpack.config.js
- webpack-config/lib/base-config.js
As discussed in RL, this change adds a cache-busting hash to the default webpack bundle filename.
- build(webpack): Add cache-busting to default bundle.js output filename
Ensure dev and prod builds for FE projects affected still work:
> build(webpack): Add cache-busting to default bundle.js output filename

- app-shell/src/discovery.js
- app/src/components/RobotSettings/ConnectBanner.js
- app/src/components/RobotSettings/ReachableRobotBanner.js
- app/src/discovery/__tests__/actions.test.js
- app/src/discovery/__tests__/reducer.test.js
- app/src/discovery/__tests__/selectors.test.js
- app/src/discovery/index.js
- app/src/discovery/selectors.js
- app/src/discovery/types.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/server.js
- app/src/index.js
- app/src/robot/api-client/client.js
This PR:
- Adds restart tracking to the discovery substate based on list updates from health checks and successful HTTP responses to POST /server/restart
- Disconnects RPC automatically if a POST /server/restart request is successfully made
Which allows us to:
- Remove bogus lost connection alerts for purposeful restarts
- Tweak the unreachable robot banner to note that the robot is currently restarting
Closes #2516
- feat(app): Track restart status in discovery state for better alerts
Do various the things that restart the robot with RPC (connection toggle) both connected and disconnected:
1. Deck calibration
2. Factory data reset
> feat(app): Track restart status in discovery state for better alerts

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/StepEditForm/PauseForm.js
- protocol-designer/src/components/forms.css
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
Fix the field spacing regression introduced in #2580
Closes #2597
> fix(protocol-designer): add vertical spacing back to form fields

- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_geometry.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_labware_load.py
Closes #2613. 
- Add ability to load labware def by name
Test on a robot!
- Set feature flag to use `useProtocolApi2`
```
from opentrons import protocol_api
ctx = protocol_api.ProtocolContext()
labware = ctx.load_labware_by_name('generic_96_wellPlate_380_uL', '1')
```
> refactor(api): Add ability to load a labware by definition name

- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionInput.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/load-file/reducers.js
- protocol-designer/src/steplist/actions/actions.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/selectors.js
Improve the user experience when deleting labware that is being used across the protocol. Also
includes some fixes to intermittent bugs associated with the well selection modal given aspiration
and dispense in the same labware.
Closes #2361
> feat(protocol-designer): edit saved step forms when labware is deleted

- protocol-designer/src/pipettes/thunks.js
Because saved step forms may be changed by editing pipettes, close the active unsaved step form to
avoid adverse symptoms after pipette change.
> fix(protocol-designer): close step form when edit pipettes

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Release PR for `3.6.0-beta.0`
https://github.com/Opentrons/opentrons/compare/v3.5.1...edge
Give the changelog and [release notes](https://github.com/Opentrons/opentrons/blob/release_3.6.0-beta.0/app-shell/build/release-notes.md) a gander! This is a relatively low surface-area release
- Linux: https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.6.0-beta.0-linux-b12725-release_3.6.0-beta.0.AppImage
- Mac: https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.6.0-beta.0-mac-b12725-release_3.6.0-beta.0.zip
- Windows: https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.6.0-beta.0-win-b8779-release_3.6.0-beta.0.exe
> chore(release): 3.6.0-beta.0

- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionInput.js
Add the step id to the WellSelectionModal key so that changing the step causes it to rerender.
> fix(protocol-designer): well selection modal refresh on step change

- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionModal.js
Well selection modal well contents are now only correlated with the currently selected step (the one
being edited)
Closes #2558
> feat(protocol-designer): disconnect well selection from hover step state

- protocol-designer/src/components/alerts/TimelineAlerts.js
- protocol-designer/src/dismiss/actions.js
- protocol-designer/src/dismiss/reducers.js
- protocol-designer/src/dismiss/selectors.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/steplist/actions/thunks.js
- protocol-designer/src/steplist/actions/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/selectors.js
- protocol-designer/src/steplist/test/reducers.test.js
Closes #2588
* uses UUID for steps
* update step reducer tests to use string IDs not numbers
- Try deleting, moving, creating, hovering steps -- shouldn't break!
> refactor(protocol-designer): change StepType from number to string

- app-shell/electron-builder.json
This PR is an attempted workaround to fix [flaky AppVeyor builds](https://ci.appveyor.com/project/Opentrons/opentrons/builds/20299796#L4379)
- build(app-shell): Add publisherName to config
🤷‍♂️
> build(app-shell): Add publisherName to electron-builder config

- .travis.yml
Follow-up to #2668: I implemented the JS test stage to run Jest and Flow in parallel as part of the same job, where 1 job === 1 VM (technically container, but whatever).
With that arrangement, it seems flow was hitting merge timeouts more often than not. Rather than increase the flow timeout again (see #2514), I moved `flow check` to its own job (VM).
- It seems to bring down our total run time, because turns out Python tests, JS tests, and Flow check all take about the same amount of time (~6 minutes)
- If flow craps out, we can just restart flow instead of the entire JS suite
Caveats:
- Flow is no longer a gating condition to pushing PD and CL to the `branch-name` folder in S3
- This increases our job usage, which counts against our total
- ci(travis): Move flow typechecking to separate …
> ci(travis): Move flow typechecking to separate job in test stage

- protocol-designer/src/steplist/actions/handleFormChange.js
- protocol-designer/src/steplist/actions/types.js
- protocol-designer/src/steplist/reducers.js
There was some unecessary duplication of concerns between handling unsaved form changes and handling
deletion of labware in all saved forms. This addition creates a function that can be used by both
cases, to unite the logic into one source of truth.
Closes #2657
> refactor(protocol-designer): unite delete labware and handleFormChange logic

- shared-data/robot-data/pipetteModelSpecs.json
This PR shifts the p1000_v1.3 drop-tip and blow-out positions based off QC test results
> fix(api): re-position p1000 droptip/blowout positions

- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/modules/magdeck.py
- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/types.py
- api/tests/opentrons/hardware_control/modules/test_hc_tempdeck.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_geometry.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_offsets.py
- shared-data/definitions2/Opentrons_24_tuberack_1.5_mL_Eppendorf.json
- shared-data/definitions2/Opentrons_6x15_mL_4x50_mL_tuberack.json
- shared-data/definitions2/Opentrons_96_tiprack_300_uL.json
- shared-data/definitions2/biorad_96_wellPlate_pcr_200_uL.json
- shared-data/definitions2/generic_96_wellPlate_380_uL.json
- shared-data/js/__tests__/fixtures/irregularLabwareExample1.json
- shared-data/js/__tests__/fixtures/labwareExample.json
- shared-data/js/__tests__/fixtures/labwareExample2.json
- shared-data/js/labwareTools/__tests__/createIrregularLabware.test.js
- shared-data/js/labwareTools/index.js
- shared-data/labware-json-schema/labware-schema.json
- shared-data/robot-data/moduleSpecs.json
There are now ModuleContexts in protocol_api/contexts.py that expose the module
API. The protocol API also has a new workflow for adding labware to modules:
- create a module with ProtocolContext.load_module()
- call module.load_labware[_by_name]() to load the labware
This avoids the shared=True functionality that was only used for modules but was
designed to be super generic.
Modules also now have their own specs file that defines their geometry,
including the offsets from the deck to their labware and their overall shape.
In addition, fix some minor bugs:
- axis maxima bumped by +0.05mm for all axes to avoid floating point precision
problems when positions are run through deck transform
- hardware_control SynchronousAdapter needs to actually return the results of
coroutines it executes …
> refactor(api): Use modules in protocol api

- api/docs/source/labware.rst
Fix row vs column label typo in labware documentation
> docs(api): Fix incorrect labels for rows and columns in labware docs

- api/docs/source/robot.rst
Fix a previously broken link to the robot config file. This was broken after we moved all live code into src/opentrons.
- Make sure everything looks normal with new link
> docs: Correct the link for changing robot gantry speed

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Update version numbers, changelogs, and release notes for `3.6.0-beta.1`
(https://github.com/Opentrons/opentrons/compare/v3.6.0-beta.0...edge
Standard beta release PR. Very low user-facing surface area in this one so it'd be great if we can do a relatively quick merge + release on this one.
> chore(release): 3.6.0-beta.1

- app/src/components/RobotSettings/SelectNetwork/styles.css
This PR is both an issue and a bug fix. Refactoring `ScrollableAlerModal` to always account for the absolute positioned bottom button bar removed the need for styling case by case. Wifi connect form still implemented that extra padding
- remove  3 rem padding from wifi connect form
Please review all wifi-connect modals to ensure everything renders properly
> refactor(app): Remove padding from wifi connect form

- protocol-designer/src/components/steplist/MultiChannelSubstep.js
Closes #2678
Multichannel substeps are collapsed by default
Note: in the code, we already had `const DEFAULT_COLLAPSED_STATE = true`, but `collapsed` was being used as if it meant the inverse, "expanded".
* make multichannel substeps collapsed by default
Expanding a collapsed step that uses a multi-channel pipette should open with the inner multi-channel-substep rows collapsed.
> feat(protocol-designer): make multichannel substeps collapsed by default

- protocol-designer/src/components/StepEditForm/FormSection.js
- protocol-designer/src/localization/en/tooltip.json
Simple one - just add a tooltip that says "Advanced Settings" to the cog icon.
Closes #2706
Should work for all forms that have the cog icon (transfer/consolidate/distribute)
> feat(protocol-designer): add tooltip to advanced settings icon

- api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py
The tempdeck driver, when it fails, will sleep and try again. When we’re testing
that, we need to wait a bit - since it’s in a thread - before checking the output.
This is super hacky.
> fix(api): Fix the flaky tempdeck test

- components/src/deck/ContainerNameOverlay.js
- components/src/deck/Deck.js
- components/src/deck/LabwareContainer.js
- components/src/deck/LabwareOutline.js
- components/src/deck/constants.js
- protocol-designer/src/components/SingleLabware.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/constants.js
- shared-data/js/constants.js
- shared-data/js/getLabware.js
- shared-data/js/labwareTools/index.js
Closes #2535
As per the slack poll @btmorr conducted two weeks ago, here's my attempt at clearing up "length" vs "width" in different contexts of robot coordinate system (which is used in JS world for JSON labware definition creation) versus SVG coordinate system (used to render deck map + labware).
```js
// constants for dealing with robot coordinate system (eg in labwareTools)
export const SLOT_LENGTH_MM = 127.76 // along X axis in robot coordinate system
export const SLOT_WIDTH_MM = 85.48 // along Y axis in robot coordinate system
// constants for SVG renders of the deck
export const SLOT_RENDER_WIDTH = SLOT_LENGTH_MM // along X axis in SVG coords
export const SLOT_RENDER_HEIGHT = SLOT_WIDTH_MM // along Y axis in SVG coords
```
* use separate constants when dealing with robot …
> refactor(shared-data): rename slot width/height constants

- app/src/components/AppSettings/UpdateApp/RestartAppModal.js
- app/src/components/AppSettings/UpdateApp/UpdateAppMessage.js
- app/src/components/AppSettings/UpdateApp/UpdateAppModal.js
- app/src/components/AppSettings/UpdateApp/index.js
- app/src/components/AppSettings/UpdateApp/styles.css
- app/src/components/RobotSettings/ReachableRobotBanner.js
- app/src/pages/More/AppSettings.js
This PR addresses #2401 by updating the app update modal to follow a similar flow to robot update
This [screen](https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5bcff6296bc6d61900626ef9) in particular.
- refactor(app): Add app update message and release notes toggle behind feature flag
Can be tested on VS
`make -C app dev OT_APP_DEV_INTERNAL__NEW_UPDATE_MODAL=1` to enable new upgrade/downgrade modal feature flag
change `package.json` in `app-shell` to earlier app version so that an app update is available
> refactor(app): Add app update message and release notes toggle

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
This PR updates version numbers and changelogs for the 3.6.0 stable release.
https://github.com/Opentrons/opentrons/compare/v3.6.0-beta.1...edge
I'd like to proactively merge this PR and use the edge build as the RC. If testing the RC build checks out, the merge commit will be tagged and released as 3.6.0. If there are any show-stoppers, we'll move right along to 3.6.1 without releasing 3.6.0
> chore(release): 3.6.0

- protocol-designer/src/components/SettingsPage/SettingsApp.js
- protocol-designer/src/components/SettingsPage/SettingsPage.css
- protocol-designer/src/components/SettingsPage/SettingsSidebar.js
- protocol-designer/src/components/SettingsPage/index.js
- protocol-designer/src/containers/ConnectedMainPanel.js
- protocol-designer/src/containers/ConnectedNav.js
- protocol-designer/src/containers/ConnectedSidebar.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/localization/en/button.json
- protocol-designer/src/localization/en/card.json
- protocol-designer/src/localization/en/nav.json
- protocol-designer/src/navigation/types.js
- protocol-designer/src/tutorial/actions.js
- protocol-designer/src/tutorial/reducers.js
- protocol-designer/src/tutorial/selectors.js
Closes #2652
* add action + reducer + button to clear dismissed hints state
* rename the sidebar itiem from "Privacy" -> "App", and correspondingly rename the `Privacy` components to `SettingsApp`
* Click the Restore button
* Make a new protocol and add a Transfer without adding liquids, you should see a hint
* Click OK to dismiss the hint (you can check "Don't show me again", or not, either way it will get restored when you click the button)
* Clicking the Restore button will un-dismiss the hint (in Redux, and in localStorage)
> feat(protocol-designer): allow user to re-enable dismissed hints

- protocol-designer/src/components/StepEditForm/TipPositionInput/TipPositionModal.js
- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/constants.js
- protocol-designer/src/steplist/actions/actions.js
- protocol-designer/src/steplist/actions/handleFormChange.js
- protocol-designer/src/steplist/actions/thunks.js
- protocol-designer/src/steplist/formLevel/generateNewForm.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/getNextDefaultPipetteId/index.js
- protocol-designer/src/steplist/formLevel/getNextDefaultPipetteId/test/getNextDefaultPipetteId.test.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- protocol-designer/src/steplist/formLevel/warnings.js
Closes #2705. This is a bug fix and a refactor to move towards making `handleChangeForm` the single central place to handle form field value updates to trigger changes in other field values.
* rewrite handleChangeForm to be given a base form (instead of always using unsavedForm)
- Bug is fixed? Creating a new distribute should auto-fill the disposal volume field with 20% of the default pipette that has automatically been selected. Leaving the pristine step and going back to it, you should see the same thing.
- No new bugs? Eg if you look at the POPULATE_FORM action payload which sets the values of `unsavedForm`, you shouldn't see `pipette` field in any pause steps, and you shouldn't see `aspirate_disposalVol_volume` etc in non-distribute steps, and so on.
- Code changes OK?
> fix(protocol-designer): fix missing disposal volume in new distribute forms

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/images/labware/index.js
With #2614 we are planning to remove the `tiprack-1000ul-chem` definition (this is the non-grid, staggered layout tiprack). This PR serves as its own ticket, it removes the 1000-chem tiprack from PD to prepare for the removal of this labware.
As of now, this is the only labware that #2614 will remove which will affect PD. The other labware to be removed aren't in PD.
* remove ability to add `tiprack-1000ul-chem` to the deck or select it for a pipette
Is it OK to remove this now? I haven't heard of anyone ever using this tiprack since I've been working here so IMO it should be safe.
> feat(protocol-designer): remove option of tiprack-1000ul-chem from pd

- protocol-designer/src/components/modals/NewFileModal/NewFileModal.css
- protocol-designer/src/components/modals/NewFileModal/index.js
remove null selection for pipette models from new file modal. Also condense styles to clean up
visual space.
Closes #2721
> feat(protocol-designer): new protocol modal defaults and visual updates

- protocol-designer/src/components/StepEditForm/MixForm.js
- protocol-designer/src/components/StepEditForm/TransferLikeForm.js
- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
Closes #2579
* remove all traces of "delay" advanced setting from forms, type defs, unit test placeholders, etc
Should be straightforward standard review. I'm pretty sure the removal is thorough because searching across PD for `delay` now only shows things related directly to the delay command creator (which the Pause step uses) and nothing else
> feat(protocol-designer): remove delay from advanced settings of all step types

- protocol-designer/src/labware-ingred/reducers/index.js
By default, when a user creates a protocol, one tip rack for each given mount should be placed on
the deck.
Closes #1327
> feat(protocol-designer): place tipracks on protocol creation

- protocol-designer/package.json
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/selectors/fileFields.js
Closes #1623 
* Add moment.js to PD (just for datetime string formatting :cry:)
* Add "Date Created" and "Last Exported" fields
* Replace "unsaved file metadata fields" stuff in Redux with a Formik form
* File Information card only lets you click "Update" button when changes have been made to the form
* Exporting a file will update the "Last exported" datetime immediately
* Is it OK that changing the fields then exporting the file without clicking "Update" will reset the form? Seems like that's necessary if you need to click the button
* Is it OK that unsaved changes in the form are cleared when you leave the page and come back?
> feat(protocol-designer): show file created and modified date

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Updates the changelogs and version numbers for the 3.6.1 release of the app/API. This release updates the aspirate configuration for the P10 single pipette.
https://github.com/Opentrons/opentrons/compare/v3.6.0...edge
Please ensure the changelogs and release notes look good
> chore(release): 3.6.1

- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/steplist/actions/thunks.js
Closes #2767 - when you click a step in the steplist (whether it's already selected or not), or if you create a new step, the main page should scroll to the top, showing the full form.
* Not too too hacky for a temporary fix?
* Works in all useful cases?
* Form-level warnings (eg, recommended disposal vol) scroll into view correctly?
> feat(protocol-designer): scroll to top of page when step created/selected

- protocol-designer/src/step-generation/commandCreators/compound/distribute.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
Closes #2748 - see my comment in that ticket for explanation of problem
- When Volume of a Distribute exceeds the pipette/tip capacity, change tip "once" should use one tip throughout the entire step
> fix(protocol-designer): fix changeTip once bug in distribute step

- protocol-designer/src/step-generation/commandCreators/atomic/aspirate.js
- protocol-designer/src/step-generation/commandCreators/atomic/dispense.js
- protocol-designer/src/step-generation/commandCreators/compound/consolidate.js
- protocol-designer/src/step-generation/commandCreators/compound/distribute.js
- protocol-designer/src/step-generation/commandCreators/compound/mix.js
- protocol-designer/src/step-generation/commandCreators/compound/transfer.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/commandFixtures.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
Closes #2773
* finish implementing flow rate across all step types and "inner mixes"
- Flow rate field should affect main aspirate/dispense JSON commands within Transfer/Distribute/Consolidate/Mix steps
- Flow rate field should affect aspirate/dispense rate within "inner mixes" of transfer/consolidate (distribute mixes are deprecated but should work too)
- Please test by inspecting the JSON commands (should say `"flow-rate": 1` in the atomic commands in the file)
- Please test on a robot (no API update required, 3.6.0 is fine)
> fix(protocol-designer): finish implementing flow rate in PD

- protocol-designer/src/labware-ingred/reducers/index.js
Before, "add liquid" hint was shown when user skipped creating liquids. Now it is shown when user
specifically doesn't have any liquids on the deck in initial deck setup
Closes #2777
* Before, "add liquid" hint was shown when user skipped creating liquids. Now it is shown when user specifically doesn't have any liquids on the deck in initial deck setup
* fix mostly-asymptomatic bug: deleting labware now deletes it from ingredLocations reducer
Modal should show up if user attempts to make a (non-Pause) step and:
Note that if you do this more complex flow that makes you wind up getting no liquids on your deck starting state:
1) create liquids
2) add some to the deck
3) delete all liquids on deck from the labware, or delete the labware itself from the deck 
4) create a step (non-Pause)
...it …
> fix(protocol-designer): fix when add liquid hint is shown

- protocol-designer/src/containers/ConnectedNav.js
In staging, clicking settings then back to main page doesn't take you back to the splash, but takes you to file details. This is a fix!
> fix(protocol-designer): fix regression of #2370

- app/src/components/RobotSettings/UpdateRobot/ReinstallModal.js
- app/src/components/RobotSettings/UpdateRobot/SkipAppUpdateMessage.js
- app/src/components/RobotSettings/UpdateRobot/SyncRobotMessage.js
- app/src/components/RobotSettings/UpdateRobot/SyncRobotModal.js
- app/src/components/RobotSettings/UpdateRobot/UpdateAppModal.js
- app/src/components/RobotSettings/UpdateRobot/UpdateRobotModal.js
- app/src/components/RobotSettings/UpdateRobot/VersionList.js
- app/src/components/RobotSettings/UpdateRobot/index.js
- app/src/components/RobotSettings/UpdateRobot/styles.css
- app/src/pages/Robots/RobotSettings.js
- app/src/pages/Robots/index.js
This PR addresses #2401 by implementing finalized upgrade/downgrade/reinstall screens, actions, and user flow.
- refactor: break up UpdateRobotModal into AppUpdate, RobotSync, and Reinstall modals
- refactor: streamline modal actions
- feature: redirect to menu/app/update on load if an app update is available
`make -C app dev OT_APP_DEV_INTERNAL__NEW_UPDATE_MODAL=1`
- robot = app, app < latest
- robot > app, app < latest
- robot < app, app < latest
- robot < app, app = latest)
- robot > app, app = latest
- robot = app, app = latest
> refactor(app): Simplify upgrade/downgrade modal render logic

- protocol-designer/src/labware-ingred/reducers/index.js
Started this week by finding that with new protocols using one pipette, adding any kind of step except pause causes a whitescreening exception from the step-gen timeline :grimacing:
Used git-bisect to find that this exception is due to a sneaky bug in #2750 which caused fixedTrash to be deleted from Redux labware state when only one pipette was assigned. Without fixedTrash, any step that drops a tip or otherwise interacts with fixedTrash will cause PD to whitescreen (attempts to access labwareById.fixedTrash.A1 in the liquid update fns, fixedTrash is undefined)
Also fixes related bug where no tiprack was being auto-added when you only had one pipette in a new protocol.
> fix(protocol-designer): fix bug where new protocol w 1 pipette deleted fixedTrash

- protocol-designer/src/containers/ConnectedFilePage.js
I forgot a set of parentheses in #2754 
* add parentheses so swap pipette works again
> fix(protocol-designer): fix swap pipettes button dispatch

- api/docs/source/index.rst
- api/src/opentrons/api/session.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/data/Everything_Test_Software.py
- api/tests/opentrons/data/bradford_assay.py
- api/tests/opentrons/data/calibration-validation.py
- api/tests/opentrons/data/dinosaur.py
- api/tests/opentrons/data/multi-only.py
- api/tests/opentrons/data/multi-single.py
- api/tests/opentrons/data/no_clear_tips.py
- api/tests/opentrons/data/pickup-accuracy.py
- api/tests/opentrons/data/smoke.py
- api/tests/opentrons/data/testosaur.py
Add metadata to session for Python protocols. Closes #2616
- Add metadata to session for Python protocols
Test on your robot (upload a protocol without and with a top-level variable named `metadata`, such as the one below).
```
from opentrons import instruments, labware
metadata = {
'this': 'that',
'what?': 'no'
}
tiprack = labware.load('opentrons-tiprack-300ul', '1')
plate = labware.load('96-plate', '2')
pip = instruments.P300_Multi(mount='right', tip_racks=[tiprack])
for well_idx in range(len(plate)):
pip.aspirate(30, plate.wells()[well_idx])
pip.dispense(30, plate.wells()[well_idx])
pip.return_tip()
```
> feat(api): Add metadata to session for Python protocols

- app/src/components/nav-bar/NavButton.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/server.js
closes #2642
- fix(app): Show main nav notification dot for updatable connected robot
- remove broken `getAnyRobotUpdateAvailable` selector and tests
- open app
- connect to a robot with an available update
- navigate to upload or other page with a robot connected
> fix(app): Show main nav notification dot for updatable connected robot

- api/src/opentrons/config/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
opentrons.config._generate_base_config(), in addition to generating and
returning defaults, will _write_ those defaults to the appropriate places unless
the skip_usb flag is set. In get_config_index(), which is mostly intended to
just find the config files, it uses generate_base_config to generate the config
but does not intend to write it. We therefore need to explicitly tell
_generate_base_config to not overwrite anything.
Check that the logic makes sense.
To see if it worked, make an edit (any edit) in settings files on the usb drive, then save and restart the robot. Once it boots, the changes should still be there.
> fix(api): Do not overwrite settings every time we get config files

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
This PR updates the version numbers and changelogs for the 3.6.2 release candidate.
Please note that `3.6.1` was not released
https://github.com/Opentrons/opentrons/compare/v3.6.0...edge
Standard RC review
> chore(release): 3.6.2

- api/docs/source/index.rst
- app/src/components/UploadError/styles.css
- app/src/protocol/__tests__/reducer.test.js
- app/src/protocol/index.js
- app/src/protocol/protocol-data.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
Closes #2617. See ticket for background and acceptance criteria
- feat(app): Display Python protocol metadata in the app 
- Also updated API docs with changes mentioned in #2799 
- Also also snuck in the whitespace fix for protocol upload errors
> feat(app): Display Python protocol metadata in the app

- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_labware.py
Remove unnecessary backcompat measures that have a potentially significant negative impact on api performance and are not need
Remove override for `__getitem__` in new labware class
Remove `cols` alias for `columns`
> refactor(api): Remove unnecessary backcompat measures

- app-shell/src/config.js
- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/OptInPipetteModal/index.js
- app/src/components/RobotSettings/OptInPipetteModal/styles.css
- app/src/config/index.js
This PR closes #2793
- feat(app): Add opt-in modal for new p10s
** quit app, relaunch and view previous robot with opt in modal already seen **
> feat(app): Add opt-in modal for new p10s

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
This PR updates the version numbers and changelogs for the 3.6.3 release candidate.
https://github.com/Opentrons/opentrons/compare/v3.6.2...edge
Standard changelog + release notes review
> chore(release): 3.6.3

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
- shared-data/definitions2/opentrons_1_trash_0.85_L.json
- shared-data/definitions2/opentrons_1_trash_1.1_L.json
- shared-data/labware-json-schema/labware-schema.json
Closes #2241. Finish up the reset of tip management by adding a fixed trash and implementing return tip.  
- Add `has_tip` key on instrument
- Add trash argument to instrument context
- Implement return tip, trash
- Try picking up and dropping tip on robot!
- Code look OK?
> refactor(api): Add fixed trash and return tip

- api/src/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
There was a bug discovered in 3.6.2 and later in which any left hand assignment (or subscript) such as:
```
plate.properties['height'] = height
```
would result in an error such as:
- Check that an ast object is specifically a Name expression
- Add a left hand assignment and make sure it does not work or result in an error
Pls do a before/after test with this protocol
```
from opentrons import labware, instruments, modules
mag_deck = modules.load('magdeck', '1')
output_plate = labware.load('biorad-hardshell-96-PCR', '1', share=True)
output_plate.properties['height'] = 46
for well in output_plate.wells():
well.properties['height'] = 46
```
> fix(api): Fix extract metadata

- CHANGELOG.md
- api/src/opentrons/CHANGELOG.md
- api/src/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/build/release-notes.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- discovery-client/CHANGELOG.md
- discovery-client/package.json
- labware-designer/CHANGELOG.md
- labware-designer/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- protocol-library-kludge/CHANGELOG.md
- protocol-library-kludge/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- update-server/otupdate/CHANGELOG.md
- update-server/otupdate/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
Supercedes https://github.com/Opentrons/opentrons/pull/2840 with correct name
Hotfix 3.6.5.
This contains a fix for a very incorrect aspirate function for the p10 single when the new feature flag was ticked; this was caused by me incorrectly copy pasting the diff of the commit that reverted the change in the config to the code.
Check out the changelogs (including the manually edited one in app-shell/build which I remembered this time)
> Release: 3.6.5

- CONTRIBUTING.md
We have to name release branches to match release_* to get signed builds that can be RCs. Add this
to the releasing section of CONTRIBUTING.md
> docs(release): Add note about release branch names to CONTRIBUTING

- protocol-designer/src/components/Hints/index.js
- protocol-designer/src/components/StepEditForm/ButtonRow.js
- protocol-designer/src/components/StepEditForm/FormSection.js
- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionInput.js
- protocol-designer/src/components/steplist/TerminalItem/TerminalItemLink.js
- protocol-designer/src/components/steplist/TerminalItem/index.js
- protocol-designer/src/containers/ConnectedMoreOptionsModal.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/containers/StepCreationButton.js
- protocol-designer/src/steplist/actions/actions.js
- protocol-designer/src/steplist/actions/thunks.js
Continuing to move the ui state management away from the protocol data that is stored with the
steplist, this branch deprecates the old steplist actions and wires up their uses to the new
ui.steps equivalents
> refactor(protocol-designer): wire up step ui actions and remove old

- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/file-types.js
- protocol-designer/src/form-types.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/pipettes/actions.js
- protocol-designer/src/pipettes/types.js
- protocol-designer/src/step-forms/actions/index.js
- protocol-designer/src/step-forms/index.js
- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-forms/types.js
- protocol-designer/src/steplist/actions/types.js
- protocol-designer/src/steplist/reducers.js
Fixes up previous PR so that pipette info and location is synced correctly, with CRUD-style pipette actions instead.
Also CREATE_CONTAINER has `slot` made optional, if you leave it out the reducer (old: labwareIngred.containers, new: inside initial deck setup step form) will use the next available slot, or ignore the action.
And `orderedSteps` has been copied over into stepForms.orderedSteps, so now all the non-ui reducers in `step-forms/reducers` are redundant and we can start re-routing the selectors
* deprecate editPipettes thunk, make alternative in mergeProps of EditPipettesModal
* createNewProtocol no longer responsible for creating the pipettes - that's handled in ConnectedNewFileModal DTP
> refactor(protocol-designer): sync pipette locations in new initial deck setup step

- shared-data/definitions/opentrons-aluminum-block-PCR-strips-200ul.json
- shared-data/definitions/opentrons-tiprack-300ul.json
- shared-data/js/__tests__/definition-schema.test.js
- shared-data/js/__tests__/definition2-schema.test.js
This does not touch defs in `definitions2/`, only `definitions/`.
This fixes 2 "old" `definitions/` - specifically, during a PD refactor I found that 300uL tipracks weren't rendering correctly, and this is because some new code expects that the `metadata.name` in a given definition is the same string that is used to get that definition via the `getLabware` fn. For `opentrons-tiprack-300ul` and the other one, that expectation did not hold. So let's have the tests ensure consistency!
* add tests to ensure filename matches name or loadName
* fix opentrons-tiprack-300ul and opentrons-aluminum-block-PCR-strips-200ul names
- Won't break anything, right?
> fix(shared-data): add tests to ensure labware filename matches name/loadName

- api/docs/source/index.rst
Super quick link fix for docs.opentrons.com.
- Update a support article link
Go to link?
> fix(docs): Fix broken support article link

- api/docs/source/labware.rst
Update labware docs page to de-emphasize the link to Andy's GH and replace 'containers' with
'labware'
Take a look at the "Labware" docs page and make sure it's clear and correct and that the links work.
> docs(api): Update labware docs page

- protocol-designer/src/components/alerts/ErrorContents.js
- protocol-designer/src/components/steplist/utils.js
- protocol-designer/src/dismiss/selectors.js
- protocol-designer/src/step-generation/commandCreators/compound/transfer.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/steplist/fieldLevel/errors.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
Closes #1603
* break up transfers so no chunk goes under min volume
* change steplist volumes to use 2 significant digits
* form-level warning when specified volume is below pipette min
Should there be timeline-level warnings when you put in a volume that's below the pipette minimum? Eg if you try to transfer/distribute/consolidate/mix 10uL with a P300 etc?
NOTE: this does not fix the existing bug where newly-made forms don't show form-level errors related to auto-filled fields (like `pipette` field). It's happening because the field is seen as pristine but isn't. I'd like to do that in a separate PR - ticket #2883.
* (As long as you touch the Pipette field b/c of the bug) setting the Volume field to a value below the pipette minimum volume gives you a form-level warning.
> feat(protocol-designer): avoid aspirate/dispense below pipette min volume

- protocol-designer/src/step-forms/reducers/index.js
@mcous noticed a bug that caused newly saved step forms to lose some of their metadata on reimport. This fixes that bug.
> fix(protocol-designer): migrate old and new step names and descriptions

- components/src/alerts/alerts.css
This PR is an alternative to now-closed #2889 - which broke Run App!
You get this empty box when an AlertItem has no content.
This is because AlertItem conditionally wraps its children in a div with the `.message` class if `props.children` is truthy. If you pass in a child component that is designed to return null in some cases, like `const Foo = (props) => titleDisplayMap[props.title] || null`, then `props.children` of `AlertItem` will be truthy, and the padding will be applied.
* fix empty box under AlertItem with no body
* is this OK in Run App? The SessionAlert looks OK but I'm not sure how to get to other ones
* PD AlertItems show correctly: both with title only, no content (eg make a Mix with volume larger than pipette max to get "volume greater than pipette volume") and when it …
> fix(components): remove padding from empty AlertItems

- protocol-designer/src/components/StepEditForm/WellSelectionInput/WellSelectionModal.js
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/steplist/DraggableStepItems.js
- protocol-designer/src/components/steplist/StepList.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/containers/HighlightableLabware.js
- protocol-designer/src/dismiss/selectors.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/load-file/migration.js
- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-forms/test/reducers.test.js
- protocol-designer/src/step-forms/utils.js
- protocol-designer/src/steplist/formLevel/getNextDefaultPipetteId/index.js
- protocol-designer/src/steplist/formLevel/getNextDefaultPipetteId/test/getNextDefaultPipetteId.test.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/top-selectors/tip-contents/index.js
- protocol-designer/src/ui/steps/actions.js
- protocol-designer/src/ui/steps/reducers.js
- protocol-designer/src/ui/steps/selectors.js
This diff is a little long because of the find-and-replace, but it should be quicker if you look at one commit at a time. Note: the tiny 2nd commit gets overwritten by the 3rd so you can skip it.
Renaming orderedSteps -> orderedStepIds required a conditional migration, so instead of adding yet another one of these in-reducer migrations I moved these migration fns into a single file, `load-file/migration.js` so they're easier to keep track of. It was making me nervous having them floating around in the LOAD_FILE-handling reducers.
* rename orderedSteps -> orderedStepIds
* centralize file migration into a single function
- old files should load, save, and reload fine with no migration problems
> refactor(protocol-designer): rename orderedStepIds and centralize file migration

- shared-data/definitions2/opentrons_6x15_mL_4x50_mL_tuberack.json
- shared-data/js/__tests__/fixtures/irregularLabwareExample1.json
- shared-data/js/labwareTools/index.js
Closes #2781. During labware testing, it was discovered that row coordinates were reversed from what they should be. So entering well 'A1' would result in the pipette moving to well 'C1' instead.
- Add reversed list of row index to create coordinate
- Fix failing tests
- Re-do 15_50 definition
Here are the parameters for reference:
```
metadata : {"displayName": "Opentrons 15x50mL tuberack", "displayCategory": "tuberack", "displayVolumeUnits": "mL", "displayLengthUnits": "mm", "tags": ["opentrons", "modular", "tuberack", "15", "mL", "50"]},
offset : [{x: 13.875, y: 17.75, z: 123.76}, {x: 71.375, y: 25.25, z: 119.8}],
grid : [{row: 3, column: 2}, {row: 2, column: 2}],
spacing : [{row: 25, column: 25}, {row: 35, column: 35}],
dimensions : {overallLength: 127.75, overallWidth: 85.5, …
```
> fix(shared-data): fix irregular labware generator

- protocol-designer/src/components/labware/LabwareOnDeck.js
drag and drop to move labware was achievable any time the deck map was present, this branch makes it so that a user can only drag and drop to move labware from the manual intervention step
> fix(protocol-designer): restrict move labware to manual intervention

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/robot_configs.py
Currently, we just write config files and trust the OS to flush them.
Unfortunately, for certain workflows the user will immediate powercycle the
robot after changing a setting, and in this case the file has sometimes not been
syncd. Force sync immediately when hanging configs.
> fix(api): Flush and sync config file writes immediately

- app/src/components/DeckMap/LabwareItem.js
- app/src/components/DeckMap/index.js
- app/src/components/FileInfo/ProtocolModulesCard.js
- app/src/components/ModuleItem/ModuleInfo.js
- app/src/components/TempDeckStatusCard/index.js
- app/src/robot/types.js
- components/src/deck/Module.js
- components/src/deck/ModuleNameOverlay.js
- components/src/deck/index.js
- protocol-library-kludge/src/URLDeck.js
- shared-data/js/index.js
- shared-data/js/modules.js
This PR serves as an bug report and a bug fix.
When the `DeckMap` related `Module` component and styles were moved from the app to the component library, we missed the `ModuleNameOverlay`. This resulted in the app rendering the component without its applied styles.
`ModuleNameOverlay` is now part of the Components Library rather than the app and is rendering with styles from Modules.css.
- refactor(components): Move ModuleNameOverlay from app to library
- feature(shared-data): Add getModuleDisplayName method and implement in comp lib modules components
HEIGHT and PADDING_LEFT are hardcoded for now. Should we bother to implement an optional override with props at this time? See my TODO.
Upload a protocol with a module.
calibrate tripracks so that module is not disabled on the deck. 
click …
> refactor(components): Move ModuleNameOverlay from app to library

- api/src/opentrons/api/calibration.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/hardware_control/types.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_geometry.py
- shared-data/definitions2/opentrons_1_trash_0.85_L.json
- shared-data/definitions2/opentrons_1_trash_1.1_L.json
- shared-data/definitions2/usa_scientific_12_trough_22_mL.json
Some labwares, like the fixed trash or troughs, have large wells that are
intended to fit all nozzles of a multichannel pipette. Currently, the system
incorrectly moves the backmost nozzle or tip of a multichannel pipette to
the center of such a well, leaving the front 4 or so channels below the bottom
of the well.
To fix this, we define a new labware quirk, ’centerMultichannelOnWells’, and a
new critical point option, CriticalPoint.XY_CENTER. If CriticalPoint.XY_CENTER
is passed to hardware_control.API.move_to, the system will use the normal z
offset determination but ignore the model offset, thus moving the center of the
pipette even if it’s a multichannel. The protocol context will see the quirks in
the labware and pass the critical point override if necessary.
Some extra complexity is …
> feat(api): api2: Move multichannel center for certain labwares

- protocol-designer/src/step-generation/commandCreators/compound/transfer.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
> Support "change tip per source" / "change tip per dest" in Transfer command creator, write tests
Serves as its own ticket
* implement changeTip options perSource and perDest for transfer command creator
PD should work the same, in the now-outdated Transfer form there's no option for perSource/perDest so this won't be accessible until new flexible steps form
Code + tests review
> feat(protocol-designer): add perSource/perDest changeTip options to transfer.js

- protocol-designer/src/components/StepEditForm/WellOrderInput/WellOrderModal.js
- protocol-designer/src/components/StepEditForm/WellOrderInput/WellOrderViz.js
- protocol-designer/src/components/StepEditForm/WellOrderInput/types.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/test/moveLiquidFormToArgs.test.js
- protocol-designer/src/steplist/utils/index.js
- protocol-designer/src/steplist/utils/orderWells.js
Closes #2906
`moveLiquidFormToArgs`, like the other `___FormToArgs` fns, does a few very limited things:
- Put source/dest wells in order based on well ordering form fields
- Uses checkbox fields to null out dependent fields when unchecked
- Maps form field names to argument names, with no major processing of the values (eg limited to picking the 0th elem of well arrays and casting `?boolean` to boolean)
These are implemented with tests in for the new "moveLiquid" form. There is still upstream processing to do (eg cast strings to numbers with appropriate decimal places, validation) that this does not touch.
- implement moveLiquidFormToArgs + tests (but it's not connected to anything)
- factor out getOrderedWells into stepform utils for easier testing (impossible to mock if inside the same …
> feat(protocol-designer): implement moveLiquidFormToArgs

- api/src/opentrons/legacy_api/instruments/pipette.py
Fix new_tip option in legacy api `transfer` docstring
No code changes.
Look at the new paragraph and make sure it's clear
> docs(api): Fix new_tip option in legacy api `transfer` docstring

- api/src/opentrons/config/robot_configs.py
- api/tests/opentrons/hardware_control/test_robots_config.py
The system was previously expecting acceleration config to be a dict, but on robots that already had saved robotSettings.json it would be a string. Make sure to coerce it into the right type.
> fix(api): Correctly format acceleration from settings as dict

- api/docs/source/writing.rst
Follow up to [this PR](https://github.com/Opentrons/opentrons/pull/2850). Did not realize there were two instances of this link in the documentation.
- Fix broken simulation link
- Check that link works after running `make docs`
> Api docs fix simulation link

- protocol-designer/src/components/StepEditForm/FormAlerts.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
- protocol-designer/src/ui/steps/selectors.js
Miscellaneous cleanup for form-related code, shouldn't affect any functionality 
* remove duplicate form hydration code via `_getHydratedForm` helper
* remove `getFormLevelErrors` selector - it's the same as `getUnsavedFormErrors(state).form`
* rename for clarity: getHydratedUnsavedFormErrors -> getUnsavedFormErrors (since the errors aren't hydrated)
* remove NO_SAVED_FORM_ERROR, it's a leftover and is no longer used anywhere
* consolidate FormError + FormWarning type def (no change from flow perspective)
- code review: any accidental functionality changes? Are renamed names actually clearer?
- quick pass to make sure nothing broke around forms & form warning / errors
> refactor(protocol-designer): cleanup handful of small form-related cruft

- protocol-designer/src/index.js
- protocol-designer/src/test/fixtures/minimalProtocolOldTransfer.json
- protocol-designer/src/test/fixtures/preFlexGrandfatheredProtocol.json
- protocol-designer/src/test/proceduresMatchSnapshots.test.js
Given any JSON protocol saved by PD, the PD app should be able to output the `procedure` section when it saves the file. This is a large-span Redux integration test which I hope will help us maintain backwards compatibility and be explicit about breaking changes (like a snapshot test, we'd have to explicitly update these fixtures).
Much of JSON protocol compatibility is managed by the JSON schema (though this is not yet automated). However, `application-data` is outside of the schema, though this section is essential for PD to re-load and interpret protocols directly, and we have no coverage on it.
I'm hoping that this PR is sufficient to use as one acceptance criteria for backwards compatibility after flex step #2917  -- if these fixtures pass, then we know loading and saving an old …
> test(protocol-designer): add integration test ensuring PD will derive same procedure

- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/commandCreators/compound/distribute.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/index.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.js
- protocol-designer/src/steplist/formLevel/handleFormChange/utils.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/tip-contents/index.js
- protocol-designer/src/ui/steps/selectors.js
Closes #2922
- hook up new step to handleFormChange, so dependent fields should change properly
- refactor how args get used to call command creator fns. Once it's args, `stepType` is replaced with the appropriate `commandCreatorFnName` (eg moveLiquid goes to transfer, consolidate, or distribute; pause goes to delay)
above
- Code review
- Should basically work. Exceptions:
- No substeps will show for the new form yet.
- Known bug: saving a flex step form with a disposal volume will blow up b/c of AssertionError in distribute. I want to do a follow-up when we go into distribute and make sure everything works with the new args + remove old transfer-fallback functionality
- Pause / Mix substeps should work correctly, there is a change I broke them with the commandCreatorFnName refactor
> feat(protocol-designer): hook up flexible step to handleFormChange and gen commands!

- protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.js
- protocol-designer/src/components/StepEditForm/fields/FieldConnector.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/commandCreators/compound/transfer.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/fieldLevel/processing.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.js
- protocol-designer/src/steplist/formLevel/warnings.js
- protocol-designer/src/steplist/index.js
- protocol-designer/src/steplist/utils/index.js
- protocol-designer/src/test/proceduresMatchSnapshots.test.js
Make field masking distinct from casting. Cast fields of hydrated form in general stepFormToArgs, before form is passed down to specificStepTypeFormToArgs fn.
Renamed any instances of field "processing" to "masking" (except `process.js` file name, a general-enough name IMO)
Note: removes use of transferLikeFormToArgs -- old transfer/distribute/consolidate will no longer work. I can put it back in, but it caused a regression in blowout args now that blowout field names have changed. Disabled the snapshot integration test.
Also fixed 1:many and many:1 behavior for `path === 'single'` -- before, it wasn't working because the moveLiquidFormToArgs fn didn't repeat the 1-well array and transfer.js is built only to handle `sourceLen === destLen` case.
Added getErrors and getWarnings cases for …
> feat(protocol-designer): separate field masking from casting

- api/src/opentrons/hardware_control/modules/__init__.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/protocol_api/contexts.py
Adds the minimal stub of Thermocycler to the hardware_control module. Prep work for #2992 
Should be able to:
```
$ make local-shell
(api)bash-3.2$ python
>>> from opentrons.hardware_control import modules
>>> t = modules.thermocycler.Thermocycler(None, True)
```
> refactor(api): Add Thermocycler stub to hardware_control

- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/commandCreators/atomic/delay.js
- protocol-designer/src/step-generation/commandCreators/compound/consolidate.js
- protocol-designer/src/step-generation/commandCreators/compound/distribute.js
- protocol-designer/src/step-generation/commandCreators/compound/mix.js
- protocol-designer/src/step-generation/commandCreators/compound/transfer.js
- protocol-designer/src/step-generation/errorCreators.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/transferLikeFormToArgs.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/ui/steps/types.js
Closes #2921
Also, renamed ConsolidateFormData types to ConsolidateArgs for command creator fns, and `data` to `args` inside the command creator fn defs themselves to match
- code/tests review
Shouldn't change behavior - the UX around what to do when disposal volume + 2*volume exceeds pipette/tip capacity is still TBD and funky, but this PR doesn't actually change any of that
> feat(protocol-designer): disabled distribute's fallback to transfer

- protocol-designer/src/components/steplist/MultiChannelSubstep.js
- protocol-designer/src/components/steplist/SourceDestSubstep.js
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/components/steplist/SubstepRow.js
- protocol-designer/src/containers/ConnectedStepItem.js
With many steps and/or many substeps, PD performance becomes awful. This PR minimizes the re-rendering of StepItem and SourceDestSubstep and related, so that it becomes managable to have a step with 999 substeps, or to have a many steps with several substeps each.
There is still sub-optimal re-rendering when opening/cancelling a step form that shouldn't need to happen, but I can't track that down. I think it's due to the structure of PD's highest-level render components that do the layout, like the whole step list is re-rendered when step form visibility changes?? A problem for another day.
Detailed in PR comments
If you enable "paint flashing" in Chrome's Rendering dev tools you can see when things are re-rendering.
- When moving mouse over substeps, only the de-selected and …
> perf(protocol-designer): optimize substep components to render less often

- api/Makefile
Sphinx doesn't pick up on changes made to docstrings that are captured with
autodoc, so force clear the docs build dirs to  make it see them.
> chore(api): Clean docs before building

- api/src/opentrons/config/__init__.py
- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/protocols/__init__.py
- api/tests/opentrons/config/test_pipette_config.py
These are saved in CONFIG[’pipette_config_overrides_dir], by default
${OT_API_CONFIG_DIR}/pipettes. They are named {pipette_id}.json. They should
contain a structure suitable for updating into a loaded pipette config dict
after the name and model configs are merged.
These overrides are applied whenever pipette configs are loaded, if a pipette id
is known.
Closes #2936
> feat(api): Load and save per-pipette-id config overrides

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/DisposalVolume.js
- protocol-designer/src/components/StepEditForm/fields/Path/index.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.js
- protocol-designer/src/steplist/formLevel/handleFormChange/utils.js
Some fancy things are happening:
* When you go from 'single' to 'multiDispense' path, the disposal volume auto-populates. The value is either the recommended disposal volume (equal to pipette's minVolume), or if that's too big, the largest amount that can fit into the pipette with 2 wells' worth of volume (volume x 2).
* Exception: if the specified volume is exactly half the pipette capacity, that means you get no disposal volume. So the field will not be filled, the checkbox is false.
* If you are already on multiDispense, and you change the volume or the pipette in a way that lowers the disposal volume cap, the disposal volume decrease. The checkbox won't null out. Instead, the disposal volume will be set to zero.
* If 2 wells' worth of volume would exceed pipette/tip capacity, the …
> feat(protocol-designer): improve ux behavior of disposal volume

- api/src/opentrons/drivers/thermocycler/__init__.py
- api/src/opentrons/drivers/thermocycler/driver.py
Closes #2984
This PR adds a thermocycler driver class and enables the driver to connect to/ disconnect from the thermocycler serial port
- add `/driver/thermocycler`
- add `Thermocycler()` class
- add TC `.connect()`, `.disconnect()`, `.is_connected()` & `.port`
Please review that the code makes sense and is well written. 
(The code has been tested on sanni-t bot with a dummy module plugged in. It successfully performed all the mentioned actions)
> feat(api): add thermocycler driver connect/disconnect methods

- Makefile
- api/Makefile
Include API clean and uninstall in top level make uninstall task: in order to ensure that API install handles changes in directory structure correctly. This required removing pipenv uninstall from clean into its own task. Also modified the API all task per request from @mcous. This PR is pulling double-duty as a ticket.
- Add API `clean` and `uninstall` to top level `make uninstall` task
- Revise other make tasks accordingly 
Tested locally on OSX, review if change is desirable
> build(api): Include API clean and uninstall in top level make uninstall task

- api/src/opentrons/__init__.py
- api/src/opentrons/resources/scripts/start.sh
Starting the update server backgrounded and then immediately moving on to
the api server can cause boot failures due to resource contention on the
smoothie’s serial port, since the update server tries to talk to the
smoothie to get its firmware version. To fix this, we need to make the
update server actually close out the smoothie connection so we can hook
in some synch logic, but barring that we
- set a magic env var in the update server so that when it imports the
api wheel, the api wheel knows to not do some long-lasting tasks at
import time, which lessons the time we need to-
- sleep in between the update server and api server starting. Sorry.
> fix(api): Avoid resource contention on smoothie serial during boot

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
This is a first pass at tri-stating the advanced settings. See #3026 for background, but the TL;DR version is we want to be able to store the concept of "a user has set this value to _something_" in addition to the actual setting.
Closes #3026
- Adjusted types as necessary to make `bool`s optional
- Added very simple migration functionality
- Defined two versions of the configuration: unversioned (0) and 1
- Going from 0 to 1 will:
- Convert "old" keys to new keys
- Convert `False` values to `None` (Safer to assume a given "off" value is "unset" than deliberately turned off)
The migration routine I used is the simplest one that I'm familiar with: you put a version in with the data and you compare that version to a list of migrator functions you have. I didn't bother with any of the …
> feat(api): Allow advanced settings to be null (unset)

- components/src/utils.js
Closes #2766 
Now labware like `tube-rack-.75-ml` will display as "tube rack .75ml" not "Tube Rack 75 Ml" (type case is handled by CSS for labware names in all cases I can see). In addition to hyphens, underscores are also converted to spaces to future-proof for `definitions2/` naming style (although maybe that's n/a, since they have an actual `displayName`)
> fix(components): do not convert humanized labware type decimal to space

- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
- shared-data/js/pipettes.js
The change to shape of PipetteNameSpecs caused PD to export invalid protocols that do not run because of `default-values` flow-rate shape change in #2999
On `edge`, protocols will fail to upload in Run App with error `TypeError: unsupported operand type(s) for /: 'dict' and 'float'`. They will also fail JSON schema validation (eg http://jsonschemavalidator.net/)
With this PR, protocols should upload correctly and pass JSON schema validation
Should not affect Run App
> fix(protocol-designer): fix bug where 'default-values' shape did not conform to JSON schema

- protocol-designer/src/components/StepEditForm/fields/WellOrder/WellOrderModal.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/components/StepEditForm/forms/MoveLiquid/SourceDestFields.js
:upside_down_face: 
* remove reference to non-existent `.labware_field class`
Well Order modal should look like the rest of the dropdowns
> fix(protocol-designer): fix well order modal height

- app/src/components/ConfigurePipette/ConfigMessage.js
- app/src/components/ConfigurePipette/index.js
- app/src/components/ConfigurePipette/styles.css
- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/components/InstrumentSettings/InstrumentInfo.js
- app/src/components/InstrumentSettings/styles.css
- app/src/config/index.js
- app/src/pages/Robots/InstrumentSettings.js
This PR closes #2940 by adding a config button that opens a start modal for pipette config. 
Form to be implemented in #2941.
- feat(app): Add pipette config modal behind feature flag
Did some final type checking work today without a robot, so please double check that this works on a robot in the office. Calling this a WIP until I can confirm changes work as expected myself.
Run app without feature flag. Go to instruments settings page.
Run app with pipette config flag
`make -C app dev OT_APP_DEV_INTERNAL__NEW_PIPETTE_CONFIG=1`
- change from feat(app) to refactor since it is behind a feature flag
In next PR:
- Convert alert modal to scrollable alert modal
> feat(app): Add pipette config modal behind feature flag

- app/src/components/AppSettings/AddManualIp/index.js
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/config/index.js
Closes #2740. See ticket for acceptance criteria
- Added non-functional manual IP address entry modal behind development feature flag
```shell
make -C app dev OT_APP_DEV_INTERNAL__MANUAL_IP=1
```
> refactor(app): Add FF'd non-functional manual IP entry modal

- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
Closes #3048
Also move `Number` casting from `mixFormToArgs` to the field casters
Mixing in moveLiquid form should fully work - you need to inspect the JSON to see because mixes are hidden in substeps
Should not break Mix form
> fix(protocol-designer): fix inner mix inside moveLiquid form

- app/src/analytics/README.md
- app/src/analytics/index.js
- app/src/analytics/make-event.js
- app/src/analytics/selectors.js
- app/src/analytics/types.js
- app/src/http-api-client/index.js
- app/src/http-api-client/pipettes.js
- app/src/http-api-client/reducer.js
- app/src/http-api-client/settings.js
- app/src/support.js
This PR adds data about the connected robot to certain analytics events as well as the user's Intercom support profile:
- API version
- Smoothie version
- Left pipette model (already present in Intercom profile)
- Right pipette model (already present in Intercom profile)
- Robot feature flag settings
It submits this data to Intercom any time that data may change, and to MixPanel on:
- Protocol upload request
- Protocol upload success or error
- Run start
- Run finish
Closes #3009, closes #3010
- feat(app): Add robot pipettes, versions, FFs to mixpanel and intercom
Without any environment variables set, you will see debug logs for the Mixpanel event (`debug: Trackable event`) and for the Intercom event (`debug: Intercom update`).
If you test with the production app, you should see these …
> feat(app): Add robot pipettes, versions, FFs to mixpanel and intercom

- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/js/__tests__/pipettes.test.js
- shared-data/js/pipettes.js
#2999 broke the `getPipetteModelSpecs` function that the app relies on to populate various pipette UIs with data. This PR fixes the function and adds some simple snapshot tests as canaries for future regressions.
- fix(shared-data): Fix broken getPipetteModelSpecs pipette data accessor
Make sure the app displays pipettes when a protocol is uploaded
> fix(shared-data): Fix broken getPipetteModelSpecs pipette data accessor

- api/src/opentrons/legacy_api/api.py
It’s nice to try and make the instrument data always consistent, but the point
of having a separate cache method is to run it when you’re _not_ simulating to
preserve data for when you _are_. If you cache when simulating, you overwrite
your stored instruments with nothing and get incorrect model values.
Test: 
- Upload a protocol to a robot with pipettes attached and make sure the models displayed in the protocol config screen match the models in the pipette info page.
> fix(api): Do not cache instruments when simulating

- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/load-file/migration/__tests__/migrationV1.test.js
- protocol-designer/src/load-file/migration/index.js
- protocol-designer/src/load-file/migration/migrationV1.js
Migration version is now persisted on file export
Closes #3047
- you should be able to import an old protocol, have it migrate successfully, and export it.  The migrationVersion key should be set to 1 in the new json file
> fix(protocol-designer): persist migration version to file

- protocol-designer/src/components/labware/BrowseLabwareOverlay.js
- protocol-designer/src/components/labware/ClickableText.js
- protocol-designer/src/components/labware/DisabledSelectSlotOverlay.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/components/labware/NameThisLabwareOverlay.js
- protocol-designer/src/components/labware/OverlayPanel.js
- protocol-designer/src/components/labware/labware.css
- protocol-designer/src/containers/ConnectedDeckSetup.js
- protocol-designer/src/containers/Deck.css
Chrome & Firefox handle some SVG stuff differently, so the Firefox deck overlays were not showing up on hover, and the text was offset at a weird place. This should make deck overlays look pretty much the same in Firefox as they were in Chrome.
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_fix-firefox-deck-overlays/index.html
PD in Chrome should look and act the same as before - please make sure there's no regression with Deck interactivity.
I've tested only on Linux versions of Firefox + Chrome. Please test deck UI:
> fix(protocol-designer): fix svg deck overlay issues for Firefox compat

- protocol-designer/src/index.js
- protocol-designer/src/initialize.js
*Overview* 
We would like to warn users that they are about to lose their protocol if they refresh or close
their browser tab. A regression occured because of updated selector naming conventions, and it
wasn't caught due src/index.js being ignored by flow. This branch moves that initialization logic
into a separate file that is interpretted by flow.
*Changelog*
- update name of selector used to determine if there are unsaved changes ('hasUnsavedChanges' --> 'getHasUnsavedChanges')
- move initialization from `src/index.js` into a new file `src/initialize.js` and add flow annotation
> fix(protocol-designer): warn window.alert on unload

- protocol-designer/src/components/StepEditForm/FormAlerts.js
Closes #3092
* remove old assertion expecting stepId to be number
The bug was: in a never-saved "pristine" form: enter a volume below pipette minimum (eg 1 for a P300), get the "volume below pipette min" form-level warning. Before this PR, clicking the "X" to dismiss that warning did nothing (except do `console.warn` in the console). This PR should make it so the warning is dismissed when you click the X.
> fix(protocol-designer): fix FormAlerts warning dismissal

- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.js
Closes #3082 and closes #3083
Transitioning between any of the 3 paths, and transitioning where the well ratio is N:M (where `N != M` eg 2:4), shouldn't make any weird side-effects like those found in the issues this PR addresses. The non-universal changeTip settings (perSource/perDest) should reset to `always` when made invalid, and the path should reset to `single` when well ratio is N:M.
> fix(protocol-designer): fix flex step path-changing interaction

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/DisposalVolume.js
- protocol-designer/src/components/StepEditForm/utils.js
- protocol-designer/src/form-types.js
- protocol-designer/src/localization/en/tooltip.json
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/warnings.js
Closes #3093, and also fixes the "touch tip" tooltip and the "blowout" tooltip
* `getTooltipForField` returns a div with new `.tooltip` class to style all StepEditForm tooltips
* pass `hoverTooltipHandlers` down correctly, to fix disposal volume + blowout fields
* clear `disposalVolume_volume` when checkbox is unchecked, and re-initialize the volume when the checkbox is checked
- Disposal volume below pipette minimum should generate dismissable disposal volume warning
- When path is not multiDispense, you should never get disposal volume warning
- Disposal volume tooltip should show correctly
- Fixes the "touch tip" tooltip (it did not appear before).
- Fixes blowout tooltip (for special multiDispense-only blowout field in the bottom right)
> PD: fix missing disp vol warning

- .github/semantic.yml
The default configuration of the Semantic Pull Request plugin gives a ✅ if there is _either_ a semantic commit in the PR title or in any of the commits that make up the PR. This is bad for us, because we _always_ squash merge, so only the title matters. We want the semantic PR check to fail if the title is non-semantic, regardless if any of the commits are.
This config change ensures that we only pass if the title is correct
- chore(repo): Configure semantic PR plugin for squash-merging only
Check against documentation:
https://github.com/probot/semantic-pull-requests#configuration
> chore(repo): Configure semantic PR plugin for squash-merging only

- protocol-designer/src/load-file/migration/migrationV1.js
In #3087 `dependentFieldsUpdateMoveLiquid` was updated to have this behavior and @b-cooper suggested to do it in the migV1 fn too, but I forgot! So I'm doing it here
Still a good idea?
> feat(protocol-designer): fallback in migV1 to path=single if path is falsy

- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.js
> fix(protocol-designer): clear inner mix fields when new path does not support them

- components/src/forms/DropdownField.js
- protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.js
- protocol-designer/src/components/StepEditForm/fields/BlowoutLocation.js
- protocol-designer/src/components/StepEditForm/fields/DisposalVolume.js
- protocol-designer/src/components/StepEditForm/fields/Labware.js
- protocol-designer/src/components/StepEditForm/fields/Pipette.js
- protocol-designer/src/components/StepEditForm/utils.js
- protocol-designer/src/labware-ingred/selectors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.js
- protocol-designer/src/types.js
- protocol-designer/src/ui/labware/selectors.js
Closes #3104
* add missing fields to getDefaultsForStepType moveLiquid form
* in dependentFieldsUpdateMoveLiquid, use defaults from getDefaultsForStepType
* clean up dependentFieldsUpdateMoveLiquid
* add tests for new updatePatchBlowoutFields fn
The behavior below should now be enforced - getting to the NO's should be impossible (PD will reset your blowout location to be default trash)
| path |  trash labware | source well | dest well |
|---------------|--------|--------|------|
| single        | yes    | yes    | yes  |
| multiDispense | yes    | yes    | NO  |
| multiAspirate | yes    |  NO | yes  |
> fix(protocol-designer): prevent disallowed path + blowout location combos

- protocol-designer/package.json
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
- protocol-designer/src/load-file/migration/1_1_0.js
- protocol-designer/src/load-file/migration/__tests__/1_1_0.test.js
- protocol-designer/src/load-file/migration/__tests__/index.test.js
- protocol-designer/src/load-file/migration/index.js
- protocol-designer/webpack.config.js
- yarn.lock
Migration version is no longer a key of its own and we derive the necessary file migrations for
given protocol from the major and minor version numbers of the application version. The version is
hard coded in webpack right now, but will be injected into the package.json in further improvements
to the build process.
>  refactor(protocol-designer): sunset migration version, promote applicationVersion

- api/src/opentrons/config/__init__.py
This fixes two bugs:
- Because the wifi keys dir was incorrectly specified as a file in the
configelements, it would not be created on boot if it did not exist
- Because the absolute paths of key material are stored in NetworkManager
connection files, we cannot simply move the wifi keys dir in an update without
rewriting the config files on first boot. That’s a lot of complexity and
avoiding it is worth keeping an annoying path around.
This PR is about both ensuring the config and ensuring the migration of the config. We need to make sure that if the robot was previously connected to a network that required key material, it remains connected after an update and a hard reboot (during a soft reboot, since NetworkManager lives in the base OS, the keys will remain in memory and you won't …
> fix(api): Do not change the wifi keys dir and ensure it is created

- app/src/components/RobotSettings/SelectNetwork/SelectKey.js
- app/src/components/RobotSettings/SelectNetwork/index.js
- app/src/http-api-client/networking.js
This PR addresses a un-ticketed TODO in WPA-EAP where if a user uploads a credential file with the same name (but different contents) as a file already on the robot, the client may use the existing file rather than the new one in the `/wifi/configure` http request.
This fix also demonstrates how we've hit the limits of our robot API state metaphors in the app; we should prioritize pulling in a redux library to lean on instead of rolling our own stuff.
- fix(app): Select correct wifi cred file when duplicate name uploaded
> fix(app): Select correct wifi cred file when duplicate name uploaded

- api/src/opentrons/deck_calibration/__init__.py
- api/src/opentrons/deck_calibration/dc_main.py
- api/tests/opentrons/cli/test_cli.py
V1 of deck calibration was broken (whoops!). Two things wrong:
1. the mount string expected was incorrect (expected 'left'/'right' and was always 'Z'/'A') which resulted in a helper function setting it to _None_ somewhere down the CLI process.
2. The mount offset method only ever passed in a 'right' pipette for a mount
- Added some nice to haves for future of CLI tool in testing
- Fixed incorrect string expectations
- Fixed mount offset calculation func
Please test on your respective robots both moving to points 1,2,3 etc as well as doing the mount offset calculation
> fix(api): deck calibration cli errors in V1

- api/setup.py
The strict constraint on numpy makes it very hard to install on windows, since
this is a version that requires msvc to compile lapack dependencies; it also
conflicts with most jupyter installations which have transitive dependencies
from e.g. astropy that require different versions.
> fix(api): Relax numpy version constraints for wheel

- protocol-designer/src/components/StepEditForm/fields/TipPosition/index.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/components/StepEditForm/forms/MoveLiquid/SourceDestFields.js
- protocol-designer/src/form-types.js
- protocol-designer/src/load-file/migration/1_1_0.js
- protocol-designer/src/load-file/migration/__tests__/1_1_0.test.js
- protocol-designer/src/localization/en/modal.json
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js
Closes #3122 and closes #3123 - both are field name inconsistency issues
I tested a pre-flex do-it-all protocol and make sure the touch tip offset and change tip fields migrate and save correctly. I used http://www.jsondiff.com/ and the grandfathered protocol re-exported thru production PD (because for some reason it's missing commands for steps in the Google Drive version!)
> fix(protocol-designer): fix drop tip offset and change tip field bugs

- app/src/components/ConfigurePipette/ConfigForm.js
- app/src/components/ConfigurePipette/ConfigFormGroup.js
- app/src/components/ConfigurePipette/ConfigMessage.js
- app/src/components/ConfigurePipette/index.js
- app/src/components/ConfigurePipette/styles.css
This PR closes #2941 by rendering a Pipette Config Form using on mock data. I'm cutting this PR off before wiring before it gets too big.
Mock data is copy/pasted from a postman response from #3070 .
- refactor: Render pipette config form fields from data
```
make -C app dev OT_APP_DEV_INTERNAL__NEW_PIPETTE_CONFIG=1
```
This PR does:
This PR _does not_ (will be addressed in new ticket #3091 )
- Render bottom button bar with reset and save buttons
- Implement any api calls
- Add any data to 'settings/pipettes' in api state
- Validate any form fields
Questions:
Standard review. Suggestions appreciated.
> refactor: Render pipette config form fields from data

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/config/robot_configs.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/back_compat.py
- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/server/endpoints/settings.py
- api/src/opentrons/server/http.py
- api/tests/opentrons/config/test_pipette_config.py
- api/tests/opentrons/hardware_control/test_pipette.py
- api/tests/opentrons/hardware_control/test_tip_probe.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/server/test_settings_endpoints.py
- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/robot-data/pipetteModelSpecs.json
- shared-data/robot-data/pipetteNameSpecs.json
- shared-data/robot-data/schemas/pipetteModelSpecsSchema.json
- shared-data/robot-data/schemas/pipetteNameSpecsSchema.json
Accidentally merged this PR during a release. See merged PR and revert here. There is a slight modification to the PATCH endpoint in that it no longer relies on an info field sent by the user.
- Add functions to pipette_config to allow for easier access/shape of data
- Change plunger positions to top level keys instead of nested
- Add three endpoints to get all configs, get a particular config and modify the config
Endpoints are the following:
GET request to ```/settings/pipettes``` returns all pipette configs saved on that robot (will populate for any pipette that has been attached on your robot)
GET request to ```/settings/pipettes/{id}``` returns one pipette config for a known id on the robot (ids can be found from first GET request)
PATCH request to …
> feat(api): add pipette config endpoint

- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/containers/TitleBar.css
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/nav.json
Closes #3127
*Changelog*
- changes the title from "Opentrons Beta" to "Protocol Designer [BETA]"
- gives the Beta tag a separate style
> feat(protocol-designer): update title and add beta tag

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/Path/Path.js
- protocol-designer/src/components/StepEditForm/fields/Path/index.js
- protocol-designer/src/localization/en/form.json
Previously we gave generic reasons to explain why a given Path option had been disabled. As we have
nailed down the interactions of the MoveLiquid form a little more, it became clear that explaining
the reason for disabling was a big UX win. Now when a path option is disabled, the tooltip has a
different visual treatment, as well as a custom explanation of why it has been disabled. Also fixed
a bug preventing the path options from being disabled by incompatible changeTip options.
Closes #3137
The priority order is as follows: 
1. incompatible Well Ratio will always be displayed over other disabling factors
2. excessive transfer volume will be displayed over Change Tip, but not over Well Ratio
3. incompatible Change Tip selection will only be displayed if neither of the above are already …
> feat(protocol-designer): add change tip and reasons for disabled path

- api/src/opentrons/commands/commands.py
- api/src/opentrons/drivers/thermocycler/driver.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
- api/tests/opentrons/protocol_api/test_module_context.py
Adds `set_temperature` command to driver and re-adds it to API (whoops). Closes #2979 
hardware control snippet (in api directory: `make local-shell` and then `python`):
```
import opentrons.hardware_control as hc
import opentrons.hardware_control.adapters as adapt
api = hc.API.build_hardware_simulator(attached_modules=['thermocycler'])
synch = adapt.SynchronousAdapter(api)
synch.discover_modules()
synch.attached_modules
synch.attached_modules['mod0thermocycler'].live_data
synch.attached_modules['mod0thermocycler'].set_temperature(4, None, None)
synch.attached_modules['mod0thermocycler'].live_data
synch.attached_modules['mod0thermocycler'].set_temperature(99, 5, 8) # Note time remaining will be 0
synch.attached_modules['mod0thermocycler'].live_data
```
API snippet (run with simulate …
> feat(api): Add set_temperature command to API and driver

- shared-data/js/constants.js
- shared-data/js/getLabware.js
NOTE: this only updates a helper for rendering that happens to live in shared-data, it shouldn't effect anything outside of PD rendering. 
The y value being generated by the getWellDefsForSVG was only accounting for labware that fit
precisely in a slot. This adds a temporary fix to allow the fix trash to be rendered closer to
correctly which takes into account the difference in overall dimensions between the fixed trash and
all other labware. This also adds a comment documenting the reasoning and explaining the long term
goal for more robust render specific data for given labware.
*Review Requests*
> fix(shared-data): fix y axis svg value for fixed trash

- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/robot-data/pipetteModelSpecs.json
Looks like this was changed in the schema change, and it shouldn't be.
Changes p10 single v1.4 pick up current from 0.4A back to 0.1A
> fix(api): Fix mistakenly-changed pick up current for p10s1.4

- .travis.yml
- api/docs/source/index.rst
- api/docs/source/writing.rst
In addition to fixing a typo and clarifying some wording in the intro para, this
commit changes back to deploying docs on edge. We should, however, be careful
about exactly what we change in docs, to keep them in sync with the currently
deployed version.
> fix(docs): Fix typo and clarify intro in docs, deploy on edge

- app/src/components/ConfigurePipette/ConfigForm.js
- app/src/components/ConfigurePipette/FormButtonBar.js
- app/src/components/ConfigurePipette/index.js
- app/src/components/ConfigurePipette/styles.css
- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/components/InstrumentSettings/InstrumentInfo.js
- app/src/http-api-client/__tests__/settings.test.js
- app/src/http-api-client/pipettes.js
- app/src/http-api-client/settings.js
This PR connects the pipette config form to the `settings/pipettes` endpoint and populates the form with actual pipette config data.
closes #3091
- refactor(app): Connect pipette config form to api endpoint
- refactor(app): Move button bar from ScrollableAlertModal to ConfigForm component (for future reset button work)
Standard review. Can be tested on Sunset.
`make -C app dev OT_APP_DEV_INTERNAL__NEW_PIPETTE_CONFIG=1`
> refactor(app): Connect pipette config form to api endpoint

- api/src/opentrons/simulate.py
For some reason if you don’t explicitly pass a new context to exec() it won’t
let you access things you imported from lower scopes, so any access to e.g.
labware wouldn’t work in a protocol like:
```
from opentrons import labware, instruments
def run_protocol():
l = labware.load('96-flat', 2)
run_protocol()
```
would not be able to find the imported `labware` object.
> fix(api): Clear globals in simulate script

- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMix.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
- protocol-designer/src/steplist/formLevel/handleFormChange/index.js
- protocol-designer/src/steplist/formLevel/handleFormChange/test/mix.test.js
- protocol-designer/src/steplist/formLevel/handleFormChange/utils.js
Adds auto-selection of wells for single-well labware (right now in PD that's just fixed-trash and trash-box) - closes #3146 
Should skip auto-selection if there's a single-well labware that is not multi-channel compatible.
While extending this to Mix form, I realized Mix form was pretty broken. Changing pipette channels did not update well selection, I think we saw some bugs from this earlier but didn't trace them down to Mix form so couldn't replicated. Also tip positioning fields didn't reset when pipette was changed. This PR should make Mix form fields reset correctly.
* add `dependentFieldsUpdateMix`
* new `getDefaultWells` util used to update wells and auto-select well of single-well labware
- Code review
- In both moveLiquid and Mix forms, single-well labware's well should be …
> feat(protocol-designer): auto-select well of single well labware

- app/src/components/ConfigurePipette/ConfigErrorBanner.js
- app/src/components/ConfigurePipette/ConfigForm.js
- app/src/components/ConfigurePipette/ConfigFormGroup.js
- app/src/components/ConfigurePipette/index.js
- app/src/components/ConfigurePipette/styles.css
- app/src/http-api-client/__tests__/settings.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/settings.js
This PR wires up `PATCH` settings/pipettes/{id} to pipette config form.
closes #2943
- refactor(app): Add form submission to pipette config form
`make -C app dev OT_APP_DEV_INTERNAL__NEW_PIPETTE_CONFIG=1`
This PR:
- DOES NOT perform form validation
- DOES render an error from api if you enter a field that is incorrect/out of min/max range (this is precautionary measure, but due to soon to be implemented form validation a user should never see this)
Please test on a robot with valid and invalid fields.
> refactor(app): Add form submission to pipette config form

- protocol-designer/src/networking/opentronsWebApi.js
Add optional emailListName parameter to the call to the confirmEmail endpoint.
Closes #3166
> feat(protocol-designer): add emailListName param to confirmEmail call

- .travis.yml
- protocol-designer/Makefile
For auditability/provenance, we'll add this `.commit` file in PD build directories.
Also, I just made a new bucket `opentrons-protocol-designer-builds` in `us-east-2 (Ohio)`, and Travis will now send PD branch builds there instead of the old one (`opentrons-protocol-designer`).
* `make -C protocol-designer build` updates the .commit file
* travis upload to `opentrons-protocol-designer-builds` bucket
- Code review
- Make sure the S3 bucket for this branch build has a `.commit` file with the correct hash
- Should work OK on Windows so that `make build` isn't broken for Windows developers (however, this will not work _perfectly_ on windows b/c it appears that `>` in Windows will add a Windows line ending to the end of the file :angry: however the build should always happen in Travis on unix …
> ci(protocol-designer): build to NEW BUCKET, add .commit file to PD builds

- protocol-designer/webpack.config.js
- webpack-config/lib/rules.js
As discussed in RL, this PR is an easy win to reduce bundle the PD bundle size by removing almost all of the inlined images from the bundle
Before:
- bundle.b66b2dd51e3c2263caa4.js (4.73 MB, 2.49 MB gzip)
- 1.bundle.ac84872f8541429b5f78.js (21.1 KB, 6.33 KB gzip)
After:
- bundle.6395c9ecd30c90719dea.js (1.91 MB, 458.11 KB gzip)
- 1.bundle.ac84872f8541429b5f78.js (21.1 KB, 6.33 KB gzip)
Make sure all the images still work and load and stuff
We've got some additional low-hanging fruit in terms of bundle size reduction:
- typeform/embed (192 KB, candidate for dynamic import)
- moment (217 KB, prime candidate for replacement)
- opentrons/shared-data (384 KB, candidate for dynamic import)
- See `make -C protocol-designer ANALYZER=1` for more details
> build(protocol-designer): Remove most images from bundle

- protocol-designer/src/components/modals/GateModal/SignUpForm.js
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/networking/opentronsWebApi.js
Switch all staging urls out for production urls
Closes #3180
After this PR is merged all non-production builds of PD will point to: 
- staging typeform
- staging web api
- reflexive `location.href` for redirects
and all deployed production builds will point to:
- production typeform
- production web api
- reflexive `location.href` for redirects
> feat(protocol-designer): point to staging or prod resources accordingly

- api/src/opentrons/legacy_api/instruments/pipette.py
Closes #3105. See ticket for bug description and reasoning.
- fix(api): Manually publish to broker in param-mangling commands
This PR touches the following PAPIv1 methods in `pipette`:
- `aspirate`
- `dispense`
- `mix`
- `touch_tip`
- `air_gap`
For each of those methods, we should be testing:
- Shows correct run log
- Keep an eye out for location, volume, and rate parameters
- Shows up in calibration list
- Especially if location is shifted, e.g. in a dispense with no volume specified
> fix(api): Manually publish to broker in param-mangling commands

- .travis.yml
- app-shell/Makefile
This change allows PD to tag its independent releases without triggering app/API stuff if the tags
are scoped (e.g. git tag -a protocol-designer@1.2.3)
> ci(travis): Match ^v for tag stuff instead of testing presence

- api/src/opentrons/api/calibration.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/conftest.py
When we changed calibration to access well A1 by doing wells()[0], we thought it would work for both old and new labware - and it almost does. Unfortunately, for old labwares that have one well, Placeable tries to be "helpful" by just returning the single well instead of a 1-element list when you call wells().
> fix(api): Access wells in calibration so 1-well containers are ok

- .travis.yml
In order to make viewing branch builds artifacts easier, let's move them to an easier location that is stored in a travis env var.
> ci(protocol-designer): make deploy bucket env var

- protocol-designer/src/configureStore.js
Closes #3172 - what was `fileErrors` is now called `fileUploadMessage` -- I also missed the key `errorMessage` (not `message`) in the action payload.
Also added flow directive to catch basic mistakes like this, and added a couple `any`s to get around actually typing the configureStore stuff (it wasn't typed before, and doesn't seem useful to type "properly" because the definitions would be tautological
- Make a protocol that will break the reducers on import. For example, delete the `ingredients` key (it's at `designer-application.data.ingredients`) from a PD JSON protocol. Import a good protocol, then try to import the bad one. It should show you the JS error that was thrown inside the modal in red, and then upon closing the modal you should be back in your good protocol (trying and …
> fix(protocol-designer): fix mistake with load file error reporting

- protocol-designer/src/error.html
- protocol-designer/webpack.config.js
Closes #3167
Credit to Mike for the redirect to `host` idea + code
* add `error.html` to build
* Code review?
NOTE: After this change is deployed, the staging and prod S3 website settings will have to be modified so that errors go to this new `error.html` (otherwise they'll continue to serve `index.html`)
> feat(protocol-designer): add 404 redirect page

- protocol-designer/src/steplist/formLevel/getDisabledFields/getDisabledFieldsMixForm.js
Closes #3049
Mix fields should be disabled correctly. Specifically, touch tip and tip position fields should be disabled unless both pipette and labware are selected.
> fix(protocol-designer): fix mix form disabled fields

- .flowconfig
- app/src/components/AppSettings/AdvancedSettingsCard.js
- babel.config.js
- package.json
- yarn.lock
As discussed on Slack, this PR adds [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) to our Babel plugin chain. This enables the following syntax:
```js
// before
const foo = bar && bar.baz && bar.baz.qux
// after
const foo = bar?.baz?.qux
```
Flow is able to type this syntax correctly.
- Add optional chaining proposal to babel config
Note: we also discussed adding [@babel/plugin-proposal-do-expressions](https://babeljs.io/docs/en/babel-plugin-proposal-do-expressions), but Flow does not support this plugin at a syntax level, so we can't move forward (facebook/flow#560).
I've made one example change in source to demonstrate the kinds of benefits we could see. A couple things to repeat based on our discussions on Slack and in …
> build(babel): Add optional chaining proposal to babel config

- api/Makefile
- api/src/opentrons/config/modules/95-opentrons-modules.rules
- api/src/opentrons/drivers/thermocycler/driver.py
Addresses #3144
This PR enables the robot to discover a connected thermocycler module
- Added udev rule for the thermocycler boards- These rules make use of the VID and PID of the product to create a symlink to the usb port with the appropriate name. The PID that we use for our modules are sublicensed from Microchip (since we use uC from Microchip). The udev file in this PR includes one rule for the actual board that *will be* the 'Opentrons Thermocycler Module' (PID provided by Microchip for Thermocycler), and a temporary one for the dummy adafruit boards we'll be using for dev
- Added the rules file in Makefile sources so changes made to it are included in the wheel
- Made correction to poll register call (seems like `register()` doesn't use `eventmask` as kwarg)
Please check for any …
> feat(api): add udev rule for thermocycler board

- shared-data/definitions2/generic_96_wellPlate_380_uL.json
@sfoster1 noticed that the diameter of the generic 96 flat was very off. Unfortunately the ANSI standard mechanical drawings do not actually recommend a diameter -- and this seems to be one of the largely varying parameters on well plates.
- Change diameter from 10 -> 6.4 (note this value was pulled from older definition of 96 flat)
- I suppose we should test touch tip on a random 96 flat lying around?
> fix(shared-data): Fix diameter of generic 96 flat

- app/src/components/ConfigurePipette/ConfigForm.js
- app/src/components/ConfigurePipette/index.js
- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/components/InstrumentSettings/InstrumentInfo.js
- app/src/config/index.js
This PR removes feature flag and enables pipette config for up to date robots (robots which return a response from /settings/pipettes)
This PR also renders validates and submits hidden fields when new feature flag `--internalDev.allPipetteConfig` is true.
closes #3112
- feat(app): Enable pipette config modal and form
- feat(app): Render hidden config fields behind new feat flag
*note: I gave a build to support so I will hold off on merging this until they give me feedback on functionality*
`make -C app dev` 
`make -C app dev OT_APP_DEV_INTERNAL__ALL_PIPETTE_CONFIG=1`
> feat(app): Enable pipette config modal and form

- protocol-designer/README.md
- protocol-designer/src/components/ProtocolEditor.js
Closes #3189
* The branch build on PD sandbox should show the GateModal (you may have to clear your cookies to see it)
* `make dev` should not show the GateModal
* `OT_PD_SHOW_GATE=1 make dev` should show the GateModal (as before, you can't get past it unless you serve it on something other than localhost)
> feat(protocol-designer): hide GateModal in dev by default

- app/src/protocol/index.js
- app/src/protocol/protocol-data.js
- app/src/protocol/types.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-data/types.js
- protocol-designer/src/file-types.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/load-file/migration/1_1_0.js
- protocol-designer/src/load-file/migration/index.js
- protocol-designer/src/load-file/types.js
- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-generation/commandCreators/atomic/aspirate.js
- protocol-designer/src/step-generation/commandCreators/atomic/blowout.js
- protocol-designer/src/step-generation/commandCreators/atomic/dispense.js
- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forAspirateDispense.js
- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/index.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/commandFixtures.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
- protocol-designer/src/top-selectors/tip-contents/index.js
- shared-data/js/index.js
- shared-data/protocol-json-schema/jsonProtocolTypeV1.js
Closes #3162 
* update type defs for JSON protocol to match the schema
* move JSON Protocol V1 type defs from PD to shared-data
* use same type defs in Run App
* Code review
> refactor(protocol-designer): fix protocol JSON schema flow type defs

- api/docs/source/modules.rst
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/legacy_api/modules/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/server/endpoints/update.py
- api/tests/opentrons/labware/test_modules.py
- api/tests/opentrons/server/test_control_endpoints.py
- api/tests/opentrons/server/test_update_endpoints.py
Every sequential call to GET /modules was disconnecting and reconnecting all of the modules which
causes interruptions during runs. This introduces a similar caching layer as is implemented in
apiV2. Modules are not disconnected and reconnected if they were there before and are still there.
Closes #3205
- modules are now stored in the robot singleton as a Dict[str, Any], like APIv2 hardware control, as opposed to a list of Module class instances
- we now only connect "new" modules on discover, which should prevent inadvertently decapitating modules during runs by looking for new ones.
> fix(api): cache modules in singleton for apiV1 protocols

- api/README.rst
- api/src/opentrons/deck_calibration/dc_main.py
- api/tests/opentrons/cli/test_cli.py
_sigh_. Closes #3133 and fixes bug introduced in 3.7.0.
After mount calibration, you could not re-verify points as the mount would be set to the left and never to be re-set to the right.
- Add better instructions for CLI within the py file as well as in the README of top level api.
- Add actual tests on the CLI code to catch bugs a little better
Test on robot, how do tests look 😢
> fix(api): cli deck cal pipette control and tests

- api/docs/source/labware.rst
- api/docs/source/new_protocol_api.rst
@pantslakz found some references to api v4 which is properly named api v2.
> fix(docs): Catch some last api v4 references

- api/src/opentrons/drivers/temp_deck/driver.py
Closes #3218
This PR provides a temporary solution to the problem mentioned in #3218 . 
- Force temperature cache update after setting new temperature in `_driver.set_temperature()`
- Fix this cache <-> device status out of sync problem with the solution built for thermocycler
Please test this protocol on a robot and verify that robot pauses during each of the three `wait_for_temp`s. 
Also verify through robot log that the three `prints` responded with a 'target' of the newly set temperature (this is to make sure `wait_for_temp` isn't waiting because of an unstable state of the tempdeck which results in the 'status' changing momentarily) 
```
from opentrons import robot, labware, instruments
from opentrons import modules
def run_custom_protocol():
tiprack = labware.load('tiprack-1000ul', …
```
> fix(api): add target temp verification to set_temperature

- api/src/opentrons/deck_calibration/dc_main.py
Closes #3227. Also adds instructions that you can access from the command line.
- Fix the mount calibration section of deck CLI so that you can jog left pipette and also be able to check validation points again after left pipette.
- Add instructions you can access from the tool itself via `?`
Anything confusing or missing?
> fix(api): Fix the mount calibration pipette control

- api/docs/source/labware.rst
Had a broken support link in the docs. Fixed now.
> fix(docs): Fix broken support link in docs

- components/src/forms/forms.css
- protocol-designer/src/components/StepEditForm/StepEditForm.css
This PR addresses the fact that due to a lack of a specified font size within the form field suffix area, style one offs were arising in both PD and RA. This PR standardizes form font styles and pulls a few as root styles and removes PD one off for unit/suffix styling.
- refactor(components): Standardize form field font styles
Made the decision to make a `:root` style for default and caption fonts rather than using `@apply --font-body-dark` this way if the form font size, color, or weights change, we can change it here in the form stylesheet instead of higher up in atomic font styles. Does this seem sane? Will call this out in a code comment.
> refactor(components): Standardize form field font styles

- components/package.json
The addition of `"sideEffects": false` to `components/package.json` enabled tree-shaking of the components library. This, however, caused CSS specificity problems in PD (and probably
elsewhere). The addition needs to be reverted until we can understand why and fix the underlying cause.
Tree-shaking is beneficial for bundle-size reduction, so our longer-term goal should still be to enable tree-shaking of the components library.
To verify fix, look at the well selection modal in a step edit form in PD sandbox:
<http://sandbox.designer.opentrons.com/components-fix-tree-shaking>
> fix(components): Revert addition of "sideEffects": false

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_geometry.py
Credit to Seth for writing most of this :tophat:
Allows `InstrumentContext.move_to` command to take argument `z_safety`, which allows an API consumer to force the arc height, or to force direct path if `z_safety=0` is specified. 
The default, `z_safety=None`, preserves the current behavior (which is: arc height is determined by to and from labware, arc height is not applied when moving within a Location but is only used when moving from one Location to another)
Motivation: user may want deeper control over pipette movements, especially for **colony picking**
* add `z_margin_override` to `InstrumentContext.move_to` command
> feat(api): add z margin override

- api/src/opentrons/config/__init__.py
- api/src/opentrons/config/robot_configs.py
https://github.com/Opentrons/opentrons/commit/3264cff558fb7f5961f915c5870e0cbe1709c61d
introduced a new format for tip probe config data that overwrote the output of
the CLI deck calibration tip probe.
The tip probe during CLI deck calibration is different from other contexts
because it actually changes the location of the probe center in config. We were
no longer loading that change.
This commit properly migrates the probe_center config field when updating from
3.6.5, and properly loads it on more recent versions.
In addition, when updating from 3.6.5 or prior it will migrate the most recent robot settings backup if it can't find a normal robotSettings.json file. This allows affected users to downgrade (to reestablish the old settings index) then reupgrade.
- Put a robot on 3.6.5 ( …
> fix(api): Correctly migrate probe center settings

- components/src/forms/forms.css
- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/forms/AspDispSection.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/components/StepEditForm/forms/MoveLiquid/SourceDestHeaders.js
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/steplist/formLevel/getDisabledFields/getDisabledFieldsMixForm.js
Closes #3141
- update design of Mix form
- as the "unit" of mix repetitions fields, change "times" to "x"
Pause form is still unaddressed, don't worry about it for this PR, it's next!
> feat(protocol-designer): update mix form design

- shared-data/definitions2/corning_12_wellplate_6.9_ml.json
- shared-data/definitions2/corning_24_wellplate_3.4_ml.json
- shared-data/definitions2/corning_384_wellplate_112_ul.json
- shared-data/definitions2/corning_48_wellplate_1.6_ml.json
- shared-data/definitions2/corning_6_wellplate_16.8_ml.json
- shared-data/definitions2/eppendorf_96_tiprack_1000_ul.json
- shared-data/definitions2/eppendorf_96_tiprack_10_ul.json
'brand' copy needs to be capitalized appropriately for correct renders in Labware Library and other projects. Noted in #3249
* correct capitalization in labware defs
:baby_chick:
> fix(shared-data): fix case of 'brand' text

- components/src/forms/SelectField.css
- components/src/forms/forms.css
- components/src/styles/borders.css
- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/ConditionalOnField.js
- protocol-designer/src/components/StepEditForm/fields/Text.js
- protocol-designer/src/components/StepEditForm/fields/index.js
- protocol-designer/src/components/StepEditForm/forms/Pause.js
- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/labware-ingred/actions/actions.js
- protocol-designer/src/labware-ingred/actions/thunks.js
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/getDisabledFields/index.js
Closes #3142
- new design for pause form
- update substep design to show message even for timed pause
> feat(protocol-designer): update pause form design

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/ChangeTip/ChangeTip.js
- protocol-designer/src/components/StepEditForm/fields/TipPosition/index.js
- protocol-designer/src/components/StepEditForm/fields/WellOrder/index.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/components/StepEditForm/forms/MoveLiquid/SourceDestFields.js
- protocol-designer/src/components/StepEditForm/utils.js
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/localization/en/tooltip.json
Closes #3214: change "Change Tip" tooltip copy (see issue for copy)
Closes #3040: add missing tooltips:
Closes #3041:
Move advanced settings in Transfer form so they go:
ASPIRATE:
- pre wet tip
- mix
- air gap
- touch tip
DISPENSE
- mix
- touch tip
- blowout
> feat(protocol-designer): assorted form tweaks

- api/src/opentrons/simulate.py
Since simulate doesn’t run opentrons.main, it needs to configure the opentrons
domain logger to set whatever log level the user asks for (otherwise it will be
at the default of WARNING)
To test, run a simulation with `--log-level=info` and check that any info messages in the code (you might have to add some) are captured properly.
> fix(api): simulate needs to set loglevel

- api/src/opentrons/api/models.py
- app/src/components/InstrumentSettings/ModulesCardContents.js
Logic was introduced into edge which made the modules (temperature + magnetic) not populate the modules card in the app even though the endpoint was returning correctly formatted data. We will need to do another alpha release once this is merged.
- Remove logic checking for thermocycler flag
- Fix a typo in models.py
Please test this branch on your robot
> fix(app): Fix modules not populating the modules card

- protocol-designer/src/components/StepEditForm/fields/FieldConnector.js
- protocol-designer/src/components/StepEditForm/fields/Volume.js
- protocol-designer/src/components/StepEditForm/utils.js
- protocol-designer/src/localization/en/tooltip.json
Closes #3259
- Should apply only to Transfer form (aka moveLiquid in code)
- Disabled advanced settings should show "Incompatible with current path" tooltip (conveniently the ones that are disabled for reasons do not use `getTooltipForField`), when they are disabled due to the path (and not due to missing labware / pipette selection)
- Blowout advanced setting tooltip should say "Redundant with disposal volume" when & only when it is disabled due to Disposal Volume being checked in a multi dispense
> feat(protocol-designer): show tooltips on disabled fields in Transfer form

- protocol-designer/src/step-forms/selectors/index.js
* `getInitialDeckSetup` was getting rerun because it had state as one of its dependencies
* `getPipetteEntities` was getting rerun every time anything in `state.stepForms` changed,
Those 2 selectors are dependencies of `allSubsteps`, an expensive selector. Now `allSubsteps` should no longer run with changes to unsavedForm -- actions dispatched when opening, editing, and closing a step form would call `allSubsteps`. Now you should see that `allSubsteps` is only called when you save the form, not open/cancel/make transient edits.
* fix selectors used by allSubsteps selector
One noticeable change is that if you have a large protocol with many steps, and type a message in a Pause form for example, there should no longer be significant lag when typing (on `edge`, there can be several of …
> perf(protocol-designer): fix selectors used by allSubsteps selector

- protocol-designer/package.json
- protocol-designer/src/configureStore.js
- protocol-designer/src/step-forms/index.js
- protocol-designer/src/utils/index.js
- yarn.lock
In order to audit the performance and dependency trees of our selectors, let's use reselect-tools to
visualize them.
> chore(protocol-designer): add reselect-tools support

- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/protocol_api/test_module_context.py
Closes #3261 . There was a regression introduced in V2 of the API where a protocol with modules would automatically return an error if those modules were not found. This breaks what the Run App is expecting because this page no longer shows
- Check if a protocol is being simulated and if it is return a simulating module
- Only have a key error if user incorrectly spells a module name
Please run this protocol on a robot without modules attached and check that it correctly shows missing modules. Attach modules and check that the modules do not show as missing in the app.
```
def run(ctx):
tiprack1 = ctx.load_labware_by_name('opentrons_96_tiprack_300_ul', '1')
pip = ctx.load_instrument('p300_single', mount='left', tip_racks=[tiprack1])
td = ctx.load_module('tempdeck', 3)
md = …
```
> fix(api): Remove module load regression in V2

- components/src/buttons/buttons.css
Hover button looks weird over colors backgrounds, because its color is opaque gray. This PR changes it to transparent gray.
Before: 
After:
- All buttons in Run App OK
- All buttons in PD OK
> feat(components): OutlineButton hover color fix

- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/LabwareList/LabwareGallery.js
- labware-library/src/components/LabwareList/styles.css
- labware-library/src/components/LabwareRender/index.js
- labware-library/src/components/LabwareRender/styles.css
- labware-library/src/styles/reset.css
This PR closes #3088 by building out a gallery for the labware card component. Until #3269 is resolved, the gallery displays three images:
- Top-down render of labware from data
- Two placeholder images
Clicking any of the three will display that image in the main gallery view.
- refactor(labware-library): Build out labware gallery functionality
<http://sandbox.labware.opentrons.com/lablib-gallery>
**Please note**
- We don't have any non-render images (#3269)
- Not all labware definitions are correct, so not all renders are correct (#3271)
- Fixed trash renders don't make sense, but fixed trash labware will not be displayed (#3078)
**Acceptance criteria copied from 3088**
- ~Gracefully handle more than three images (display 3, don't break)~ N/A pending #3269
- ~Selected thumbnail should …
> refactor(labware-library): Build out labware gallery functionality

- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/step-forms/selectors/index.js
There are a connected properties in our step item components that are become taxing to calculate as
the length of a protocol grows. By memoizing the result of those calculations for each step item
instance, we can avoid needlessly recalculating the same properties for unrelated step items when
specific changes (e.g. updating the unsaved form) occur.
> perf(protocol-designer): avoid selector recomputation in step forms

- app/src/components/AppSettings/AddManualIp/IpField.js
- app/src/components/AppSettings/AddManualIp/IpItem.js
- app/src/components/AppSettings/AddManualIp/IpList.js
- app/src/components/AppSettings/AddManualIp/ManualIpForm.js
- app/src/components/AppSettings/AddManualIp/styles.css
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/ConnectPanel/index.js
- app/src/discovery/selectors.js
This PR closes #2741 and removes the feature flag for Add Manual IP
- feat(app): Enable adding manual robot IP addresses in app settings
*Note: After some discussion the UI screens differ from the latest Zeplin design*
Comment out line 55 in `app-shell/Makefile`
Open `config.json` in `~/Library/Application\ Support/Opentrons` and make sure discovery.candidates is empty
```
"discovery": {
"candidates": []
}
```
Open `discovery.json` in  `~/Library/Application\ Support/Opentrons` and remove `localhost` / `opentrons-dev` 
make sure virtual smoothie is running `make -C api dev`
`make -C app dev` and navigate to Robots Page
navigate to AppSettings
Click [manage]
___
enter `localhost` and click [+] to add 
___
navigate to robots page
___
Navigate back to App Settings > Add Manual IP modal
___ …
> feat(app): Enable adding manual robot IP addresses in app settings

- app/src/components/CalibrateLabware/instructions-data.js
This PR updates the logic that renders calibration images for tube and vial racks so it renders the same images for labware definition named `tube-rack`, `tuberack` or `vial-rack`.
Closes #3294 
- `tube-rack` is now replaced by `tube` and `vial`
Please test this protocol in the app on V1 to make sure the calibration screen for all three plates shows the image of a tube rack but not a 96 well plate.
```
from opentrons import labware, instruments
tiprack1 = labware.load('tiprack-10ul', '1')
plate1 = labware.load('opentrons-tuberack-2ml-eppendorf', '2')
plate2 = labware.load('opentrons-tuberack-15_50ml', '3')
plate3 = labware.load('small_vial_rack_16x45', '4')
pip = instruments.P10_Single(mount='left', tip_racks=[tiprack1])
pip.transfer(50, plate1.wells(0), plate2.wells(0))
pip.transfer(50, …
```
> fix(app): render correct image for vial and tube racks

- labware-designer/README.md
- labware-library/src/components/LabwareRender/index.js
- shared-data/labware-json-schema/labware-schema.json
Bug report + fix. This PR fixes the new labware library render not taking `cornerOffsetFromSlot` into account. It also makes some changes to the docs and schema descriptions to make the different origins more clear
- fix(labware-library): Take cornerOffsetFromSlot into account with render
None of the renders are really changed, but please check code for correctness
> fix(labware-library): Take cornerOffsetFromSlot into account with render

- app/src/components/InstrumentSettings/AttachedModulesCard.js
- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/components/InstrumentSettings/ModulesCardContents.js
- app/src/components/InstrumentSettings/index.js
- app/src/components/ModuleControls/ModuleData.js
- app/src/components/ModuleControls/TempField.js
- app/src/components/ModuleControls/TemperatureControls.js
- app/src/components/ModuleControls/index.js
- app/src/components/ModuleControls/styles.css
- app/src/components/ModuleItem/NoModulesMessage.js
- app/src/components/ModuleItem/index.js
- app/src/components/ModuleItem/styles.css
- app/src/components/TempDeckStatusCard/index.js
- app/src/config/index.js
- app/src/http-api-client/modules.js
- app/src/pages/Robots/InstrumentSettings.js
This PR implements an initial UI and wires it up to [b-cooper's module POST endpoints](https://github.com/Opentrons/opentrons/pull/3264). This may stay behind a feature flag for a bit but may be immediately useful for internal science work. With the feature flag turned on, you can set a holding temperature for the thermocycler, or deactivate it within the AttachedModulesCard (no protocol necessary).
refactor(app): Implement temperature module controls behind FF
`make -C app dev OT_APP_DEV_INTERNAL__TEMPDECK_CONTROLS=1`
Can be tested on 🌆
> refactor(app): Implement temperature module controls behind FF

- update-server/Makefile
- update-server/buildroot_upload.py
- update-server/otupdate/buildroot/README.md
- update-server/otupdate/buildroot/__init__.py
- update-server/otupdate/buildroot/control.py
- update-server/otupdate/buildroot/ssh_key_management.py
- update-server/tests/buildroot/test_ssh_key_management.py
Add new api
GET /server/ssh_keys -> 200 OK {"public_keys": [{"key_md5": md5 hex digest, "key": key string}]}
POST /server/ssh_keys {"key": key string} -> 201 Created {"message": message, "key_md5": md5 hex digest}
DELETE /server/ssh_keys/:key_md5 -> 200 OK
for managing SSH public keys on buildroot machines. These APIs will only work via linklocal connections as long as the appropriate nginx server is running.
Also, adds a makefile target in update server to update the update server without doing a full update and to put a new key on the robot.
Closes #3320
- Install this server on a buildroot robot. Do it with a normal update so you get the nginx conf changes.
- List, add, and remove some keys and make sure the changes take (i.e. you can or can't ssh into the robot in between changes) …
> feat(update-server): Add SSH public key management for buildroot

- labware-library/src/components/App/Page.js
- labware-library/src/components/App/__tests__/App.test.js
- labware-library/src/components/App/__tests__/Page.test.js
- labware-library/src/components/App/__tests__/__snapshots__/App.test.js.snap
- labware-library/src/components/App/__tests__/__snapshots__/Page.test.js.snap
- labware-library/src/components/App/index.js
- labware-library/src/components/App/styles.css
- labware-library/src/components/LabwareDetails/index.js
- labware-library/src/components/LabwareDetails/styles.css
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/LabwareList/Tags.js
- labware-library/src/components/LabwareList/index.js
- labware-library/src/components/LabwareList/styles.css
- labware-library/src/components/Nav/Breadcrumbs.js
- labware-library/src/components/Nav/index.js
- labware-library/src/components/Nav/styles.css
- labware-library/src/components/Sidebar/styles.css
- labware-library/src/definitions.js
- labware-library/src/index.js
- labware-library/src/prerender.js
- labware-library/src/styles/spacing.css
This PR continues work on #3077
The following parts of the labware detail page were added
- Navigation breadcrumbs
- Gallery
- Tags
- loadName and copy button
- displayName
<http://sandbox.labware.opentrons.com/lablib-detail-page>
@howisthisnamenottakenyet since the screens are only in Sketch, can you please make sure they align with the screens as well as what we discussed in Slack?
Otherwise, please try to test this out on different screen sizes and browsers.
Pathnames:
Screen sizes:
Specific things to keep an eye out for:
- Scroll behavior of different components (e.g. sidebar vs page content)
- Scrollbar positioning (especially with a mouse or non-macOS)
- Element widths and layers
> refactor(labware-library): Add gallery and breadcrumbs to detail page

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/protocol_api/contexts.py
This is something the robot does that apiv2 now does too.
Closes #3346
Testing:
- Use a protocol like 
```
def run(ctx):
ctx.delay(minutes=2)
```
- Check that `opentrons_simulate` does not delay 2 minutes
- Check that protocol upload does not take 2 minutes
- Check that protocol run does take two minutes
> fix(api): Do not sleep in simulated delays

- api/docs/source/complex commands.rst
Some users have noticed inconsistencies in the Complex Liquid Handling commands doc. For example, it seems that some of the printouts were generated from OT-One API. @ethanfjones and I made these edits together
Update tip rack load name from `tiprack-200ul` to `opentrons-tiprack-300ul`
Change code and printouts:
- *Large Volumes*
- transfer volumes in the printout were inconsistent with our current API
- *Multiple Wells*
- old printouts reflects `rows` rather than `cols` as described in the command
- *One To Many*
- change code from `rows('2')` to `cols('2')` 
- update printout to reflect code
- *Few To Many*
- code previously reflected `many to few` (4 sources & 2 dests) rather than `few to many`
- update to OT-2 printout
- *Consolidate*
- change code from `rows('2')` to `cols('2')`  and …
> docs(api): update docs for complex liquid handling commands

- labware-library/src/components/LabwareDetails/Stats.js
- labware-library/src/components/LabwareDetails/index.js
- labware-library/src/components/LabwareDetails/styles.css
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/LabwareList/LoadName.js
- labware-library/src/components/LabwareList/Tags.js
- labware-library/src/components/LabwareList/styles.css
- labware-library/src/components/Sidebar/FilterCategory.js
- labware-library/src/components/Sidebar/FilterManufacturer.js
- labware-library/src/components/Sidebar/__tests__/__snapshots__/FilterCategory.test.js.snap
- labware-library/src/components/ui/LabelText.js
- labware-library/src/components/ui/Table.js
- labware-library/src/components/ui/Value.js
- labware-library/src/components/ui/index.js
- labware-library/src/components/ui/styles.css
- labware-library/src/localization/en.js
- labware-library/src/localization/index.js
This PR continues work on #3077 by adding top level labware stats to the details page
- Centralized some i18n constants
- Centralized some UI components / styles relating to data display
- Added top-level stats to details page
<http://sandbox.labware.opentrons.com/lablib-details-measurements>
This PR was on track to get pretty big thanks to the centralization of common i18n and styles, so I opened it after just the top-level stats rather than continuing with all the other data tables. I'm planning to fast follow, so I may request to punt some feedback to the next PR(s)
Screens for reference
> refactor(labware-library): Add top-level labware stats to details page

- update-server/otupdate/buildroot/ssh_key_management.py
When you migrate a robot from balena to buildroot, it doesn't create an authorized_keys dir - and in general, we should be sensitive of the possibility that file is not present, since it's on the writable filesystem. To deal with this, just make sure the file is present.
Testing:
- Install the update server on a system (either by doing a full update or using the `push-buildroot` makefile target in update-server
- SSH in and delete ~/.ssh/authorized_keys
- Note that you can still push a key with make push-key
> fix(update-server): Create ~/.ssh/authorized_keys if needed

- api/Makefile
- update-server/Makefile
- update-server/otupdate/buildroot/update.py
- update-server/tests/buildroot/test_update.py
- update-server/tests/migration/test_migration_api.py
Fixes a number of stupid mistakes around buildroot:
- Tests not running because there were yield statements in them, which it turns out do not in fact spin the asyncio loop, because why would they
- main update not working and not being caught by said statements because it was missing an argument
- fast-flow not restarting the servers they update or cleaning up after themselves because that's not how bash functions work
To test, update a unit with `make push-buildroot` (making sure to ssh in and manually `systemctl start opentrons-update-server` afterwards), then
- Do another `make push-buildroot` in `update-server` and in `api`, sshing back in afterwards to note that the update server and api are in fact restarted afterwards now
- Do a buildroot update with `buildroot_upload` in update …
> fix(update-server): Fix some issues with br update, test, fast flow

- labware-library/src/components/App/__tests__/App.test.js
- labware-library/src/components/App/__tests__/__snapshots__/App.test.js.snap
- labware-library/src/components/App/index.js
- labware-library/src/components/LabwareDetails/Dimensions.js
- labware-library/src/components/LabwareDetails/WellDimensions.js
- labware-library/src/components/LabwareDetails/index.js
- labware-library/src/components/LabwareDetails/styles.css
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/ui/LabeledValueTable.js
- labware-library/src/components/ui/LowercaseText.js
- labware-library/src/components/ui/index.js
- labware-library/src/components/ui/styles.css
- labware-library/src/definitions.js
- labware-library/src/filters.js
- labware-library/src/localization/en.js
- labware-library/src/styles/spacing.css
- labware-library/src/types.js
This PR adds well information to the labware details page. Closes #3077
- refactor(labware-library): Add well details to labware details page
<http://sandbox.labware.opentrons.com/lablib-finish-detail-page>
- Well bottom/shape icons: #3245 (blocked by #3241)
- Measurement guide: #3353 
@howisthisnamenottakenyet during implementation, I made a few deviations from the screens that were meant to better capture what (I think) the design intent was. Let me know if any of these changes were incorrect:
- Moved "max volume" into well/tube/tip measurements table
- Moved well dimensions table to always be side-by-side with spacing table
- Extended well-group separating line when more than one grid exists across both dimensions and spacing table columns
> refactor(labware-library): Add well details to labware details page

- api/setup.py
In install_requires format, you don't do ==* to unlock a version, you just don't
use a version specifier. ==* causes the install to fail.
This pull requests serves as a bug report and fix.
> fix(api): Correctly specify jsonschema in setup.py install_requires

- app/src/components/AppSettings/AddManualIp/ManualIpForm.js
This PR serves as a bug report and fix. While testing for release, @sfoster1 noticed that clicking the [enter] key to submit a manual IP submitted a blank entry.  Turns out clicking enter submitted the form after it was reset. This PR disables submission if `values.ip` is empty and strips out any whitespace or carriage returns that might have been entered just to be extra paranoid.
- fix(app): Disable manual ip double submit on enter keypress
To test in dev mode comment out link 55 in `app-shell/Makefile`
```
make -C app dev
make -C api dev
```
- add 'localhost' to manual IP
- submit form by hitting [enter] key
> fix(app): Disable manual ip double submit on enter keypress

- app/src/components/CalibrateDeck/InUseModal.js
- app/src/components/CalibrateDeck/NoPipetteModal.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/index.js
Bug report + fix for stale error response states in the app during deck calibration. Exiting the wizard during an error condition should now clear all client-side DC state, allowing the user to retry DC instead of forcing them to restart the app.
- fix(app): Clear deck cal request states on wizard exit
Please test on a real robot! WFH so no robot for me to test on
> fix(app): Clear deck cal request states on wizard exit

- labware-library/src/components/Nav/__tests__/__snapshots__/Nav.test.js.snap
- labware-library/src/components/Nav/index.js
- labware-library/src/components/Nav/styles.css
- labware-library/src/components/website-navigation/MainNav.js
- labware-library/src/components/website-navigation/MenuButton.js
- labware-library/src/components/website-navigation/MobileMenu.js
- labware-library/src/components/website-navigation/MobileNav.js
- labware-library/src/components/website-navigation/index.js
- labware-library/src/components/website-navigation/styles.css
- labware-library/src/components/website-navigation/types.js
- labware-library/src/styles.global.css
- labware-library/src/styles/spacing.css
This PR refactors a few of the nav components to keep track of mobile nav toggle and adds in hardcoded starter for the mobile menu. 
addresses #3382 
- refactor(labware-library): Add mobile nav toggle
Opened this PR now to make sure this refactor makes sense before going to far. 
Disabled scroll on page for mobile, but can't seem to figure out how to affect content_scroller div on tablet size. Suggestions welcome.
I also added a drop shadow to the bottom of the mobile nav since the white on white didn't seem to have enough contrast with the page content.
http://sandbox.labware.opentrons.com/lablib_mobile-nav/
- populate subnav content/links
- possibly split up mobile and desktop nav components/styles into separate directories?
> refactor(labware-library): Add mobile nav toggle

- labware-library/src/components/App/styles.css
- labware-library/src/components/Nav/__tests__/__snapshots__/Nav.test.js.snap
- labware-library/src/components/Nav/index.js
- labware-library/src/components/Nav/styles.css
- labware-library/src/components/website-navigation/MainNav.js
- labware-library/src/components/website-navigation/MobileContent.js
- labware-library/src/components/website-navigation/MobileList.js
- labware-library/src/components/website-navigation/MobileMenu.js
- labware-library/src/components/website-navigation/MobileNav.js
- labware-library/src/components/website-navigation/NavLink.js
- labware-library/src/components/website-navigation/ProtocolMobileContent.js
- labware-library/src/components/website-navigation/SupportMobileContent.js
- labware-library/src/components/website-navigation/__tests__/__snapshots__/MainNav.test.js.snap
- labware-library/src/components/website-navigation/index.js
- labware-library/src/components/website-navigation/nav-data.js
- labware-library/src/components/website-navigation/styles.css
This PR adds in the mobile submenu content and refactors MobileNav (now stateful). 
addresses #3382
- refactor: Add mobile submenu
- refactor: Move mobile navigation state from Nav to MobileNav
Standard review. 
Please note a follow up PR will address any/all styling/spacing/sizing inconsistencies. I also need to organize the monster stylesheet.
> refactor(labware-library): Add mobile submenus

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
Currently, after every command we send an M400, which delays until the
smoothie's queue is empty. We couple this with retrying unacked commands. The
problem is, this couples command acknowledgement with command execution. The
timeouts need to be short enough to be responsive if a command isn't
acknowledged, but short timeouts cause problems with commands that take a long
time - like long motions at low speeds.
Instead, write the command and retry it if not acknowledged, but do not do an
M400 until the command is acknowledged. Once that's done, you can use a very
long timeout for the M400 without worrying about having to retry.
Closes #3300, closes #2822
Run a bunch of protocols! Especially ones that slow the head speed down. Make sure you don't get timeouts. The protocol from #2822 is a …
> refactor(api): Split smoothie command ack timeout from motion

- api/Makefile
- api/opentrons-api-server.service
- api/src/opentrons/config/__init__.py
- api/src/opentrons/deck_calibration/dc_main.py
- api/src/opentrons/main.py
- api/src/opentrons/server/endpoints/__init__.py
- api/src/opentrons/server/endpoints/logs.py
- api/src/opentrons/server/endpoints/settings.py
- api/src/opentrons/server/http.py
- api/src/opentrons/system/nmcli.py
- api/src/opentrons/util/logging_config.py
- api/tests/opentrons/server/test_health_endpoints.py
- api/tests/opentrons/server/test_settings_endpoints.py
- api/tests/opentrons/system/test_nmcli.py
- update-server/otupdate/buildroot/__main__.py
We detect that we're running on buildroot by the presence of /etc/VERSION.json,
which is also where we take some versioning information. Based on that
information, we have:
- Get the device name from hostnamectl to match up with what the update server
set
- Don't mess around with key paths in nmcli
- Force rescans in nmcli since balena won't be doing it for us
- Get logs from journald rather than static files
POST `/settings/log_level` with a json body of `{"log_level": "debug"/"info"/"warning"/"error"}` will set the robot's log level both for the current boot and subsequent boots (so no restart is required).
- /logs/{api,serial}.log has been changed for buildroot robots to actually accept and valid syslog identifier, so anything that something is logging under. `api.log` and `serial.log` …
> feat(api): Detect and change behavior for buildroot system

- api/tests/opentrons/config/test_pipette_config.py
- shared-data/robot-data/pipetteModelSpecs.json
- shared-data/robot-data/pipetteNameSpecs.json
Add Pipette + single-channel Models in pipetteModelSpecs and pipetteNameSpecs 
closes #3039
Pipette + models connected to a robot should be recognized in the App as v2
Note: As of right now, pipette v2 is defined to have the same min and max volume as its v1 counterpart, even though v2 has a different volume range than that of v1. Should we define min and max volume of each pipette model in pipetteModelSpecs rather than pipetteNameSepcs?
> feat(api): Add pipette v2.0 config

- api/src/opentrons/tools/write_pipette_memory.py
This adds pipette+ serials to write_pipette_memory for the models as described in #3394
> feat(api): Add pipette+ to write_pipette_memory

- protocol-designer/src/steplist/fieldLevel/index.js
Some string values were being written to the the offsetFromBottomMm key of certain commands, this
patch casts those values in the field level so that stepFromToArgs only receives numbers for tip
position fields
This ticket serves as the issue and fix for a bug that was initially reported by @opatel0
> fix(protocol-designer): cast offsetFromBottomMm values to number

- labware-library/src/components/website-navigation/Logo.js
- labware-library/src/components/website-navigation/NavLink.js
- labware-library/src/components/website-navigation/NavMenu.js
- labware-library/src/components/website-navigation/ProtocolMenu.js
- labware-library/src/components/website-navigation/SubdomainNav.js
- labware-library/src/components/website-navigation/__tests__/__snapshots__/Logo.test.js.snap
- labware-library/src/components/website-navigation/__tests__/__snapshots__/SubdomainNav.test.js.snap
- labware-library/src/components/website-navigation/nav-data.js
- labware-library/src/components/website-navigation/styles.css
This adds mobile nav < 768px dropdown height and changes the `SubdomainNav` to use `Link` for the 'Labware Library' instead of an anchor tag with `target="_blank"`. When the time comes, we will probably have to refactor `NavLink` as well, but that day is not today.
addresses #3382 
- refactor(labware-library): Add navbar style fixes
- refactor(labware-library): Update `SubdomainNav` to use `Link` when link is within the project
This PR is pre handoff to design review, but these 2 little issues needed to be addressed before that.
Please point out any other glaring issues if you see them. 
http://sandbox.labware.opentrons.com/lablib_navbar-style-tweaks/
> refactor(labware-library): Add navbar style fixes

- update-server/opentrons-update-server.service
- update-server/otupdate/buildroot/__main__.py
- update-server/otupdate/buildroot/name_management.py
- update-server/tests/buildroot/test_update.py
- %-encoding is ok in uri paths but not internet hostnames, so just drop the %s
- use sd_notify (https://www.freedesktop.org/software/systemd/man/sd_notify.html)
to let things depend on opentrons-update-server and know that the hostname
will be set when they start
Testing
- Put this on a buildroot robot. You can use `push-buildroot`, but you'll also have to manually copy the service file to `/etc/systemd/system`
- Either restart the robot to check at boot, or do `systemctl daemon-reload` to pick up the changed service file
- Restart `opentrons-update-server` and then check in the logs, noting that you don't see a line like `systemd[1]: Started Opentrons update server.` until after a line like `opentrons-update[315]: Notifying systemd` (and the logging from `otupdate.buildroot.__main__` …
> feat(update-server): buildroot: use sd-notify and better hostname

- CONTRIBUTING.md
While getting Mel set up to update the docs templates of API, we experienced a Mojave specific issue using pyenv to install Python 3.6.4. This PR updates the docs with a link to documentation from pyenv's wiki that helped us solve the issue.
- docs(api): Update contributing guide
- I'm particularly terrible at spelling and grammar. Is this worded correctly? In the right spot?
> docs(api): Update contributing guide

- api/src/opentrons/legacy_api/robot/mover.py
This keeps the utility of dumping the pose tree for motion, but at debug level
> refactor(api): change logs in mover to be less verbose

- api/src/opentrons/config/advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
Remove unused splitLabwareDef feature flag (this was the feature flag for the first attempt at replacing the geometry system, which was superseded by APIv2 work)
- Remove `splitLabwareDef` feature flag from API server
- Add protection so that if a feature flag is removed, the GET endpoint will not raise an exception on the existence of old keys
Sanity ✔️
> refactor(api): Remove unused splitLabwareDef feature flag

- labware-library/src/components/website-navigation/SupportMobileContent.js
- labware-library/src/components/website-navigation/styles.css
- labware-library/src/styles.global.css
This syncs styles with the main website navbar and implements design feedback. Implementing Akko Pro elegantly in the monorepo and adding GTM will be covered in new separate tickets. #3430 #3431 
closes #3382 
- refactor(labware-library): Match navbar styles with design
http://sandbox.labware.opentrons.com/lablib_navbar-design-review/
> refactor(labware-library): Match navbar styles with design

- app/src/components/InstrumentSettings/InstrumentInfo.js
Closes #3340. Due to the format of the pipette+ model names, images were not automatically being displayed on the instruments card.
- Change REGEX to determine which images propogate in Run App on `attached instruments card`
@mcous I see that you made a note that volumes and channels should come from API, should that be the correct implementation here or is changing the expression sufficient?
> fix(app): Allow valid pipette+ model names for display images

- api/src/opentrons/legacy_api/api.py
- api/tests/opentrons/labware/test_pipette_constructors.py
Closes #3434. Adds backwards compatibility for old pipette constructors when new pipette models are attached to the robot.
**Note** The P50 constructor will _not_ be supported moving forward with new pipette models as the volume range is too different.
- Check that the volume string matches when a pipette+ is found but old constructor is used
- Load in pipette+ configs, but old min/max volumes of pipette model
- Add test to check that this works
You can test using Alise's Robot with the script below. Unfortunately we do not have any pipette+'s in house except the `P1000_Single` but you can see that the robot thinks the correct pipette is attached and you can run the protocol as expected.
```
from opentrons import labware, instruments, robot
tiprack1 = labware.load('tiprack-1000ul', '1') …
```
> feat(api): Add backwards compatibility to old pipette constructors

- app/src/components/ChangePipette/Instructions.js
- app/src/components/ChangePipette/PipetteSelection.js
- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/types.js
- app/src/config/index.js
This PR serves as both a ticket and a refactor to add in a feature flag that hides pipette+ display names.
- Add in a feature flag that will automatically filter out pipette+ display names in attach pipette unless set to true
Anything look amiss 🕵️‍♀️ ?
Run on your laptop. Without feature flag see that the list only includes old pipette names, with feature flag enabled see that all pipette names show up.
Use the feature flag: `OT_APP_DEV_INTERNAL__ENABLE_PIPETTE_PLUS=1`
> refactor(app): Add a feature flag to hide pipette+ options

- app/src/components/FileInfo/ProtocolPipettesCard.js
- app/src/components/calibrate-pipettes/Pipettes.js
This PR served as both a Bug Report and a Bug Fix. Support had reported wrong/no pipette attached messages in File Info and Calibrate Pipettes pages even after the user had gone to instrument settings and attached the correct/missing pipettes. The app was comparing models vs name. This PR gets both actual and session pipette names from shared data to avoid pipette version mismatch.
- fix(app): Verify attached/protocol pipettes
Can be tested on sanniti-bot with `api/tests/opentrons/data/bradford_assay.py`. 
- detach one of the pipettes before loading protocol
- upload protocol and observe missing/wrong pipette message in File Info and Calibrate Pipettes pages
- attach the pipette
> fix(app): Verify attached/protocol pipettes

- api/src/opentrons/server/endpoints/logs.py
- api/src/opentrons/server/http.py
- api/tests/opentrons/server/test_settings_endpoints.py
Move POST /settings/log_level to POST /settings/log_level/local to make it more
clear it's for local log level only
Add POST /settings/log_level/upstream, which changes the log level filter for
messages going upstream to log aggregation. It takes the same request format as
POST /settings/log_level/local, but you can set the level to 'null' to disable
upstream log aggregation.
Closes #3422
Requires https://github.com/Opentrons/buildroot/pull/22
> feat(api): buildroot: allow separate setting of upstream log level

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/main.py
- api/src/opentrons/system/nmcli.py
The smoothie update detection machinery assumes that when the server starts, if
the smoothie does not respond it must be in programming mode. However, this can
also be true if the api server is booting for the first time and expects a
smoothie version that isn't present, like the recent change. In that case, the
update will fail because the smoothie is never set to programming mode. This
commit adds a couple retries for smoothei update, and forces programming mode
for attempts past the first.
In addition, failed firmware updates currently could in theory make the api
server stop because of an uncaught exception. Instead, force the smoothie to be virtual.
- Use this to update some robots still on edge-616 smoothie firmware and make sure it works
- See if you can force the smoothie into …
> fix(api): Handle smoothie update better

- api/src/opentrons/api/models.py
- api/src/opentrons/api/session.py
- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/util/calibration_functions.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/labware/test_pipette_constructors.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/server/test_calibration_endpoints.py
- api/tests/opentrons/server/test_control_endpoints.py
- api/tests/opentrons/server/test_settings_endpoints.py
When we introduced our pipetteModelSpecs/pipetteNameSpecs split for our pipette
data, we settled on
pipette 'name' being the _kind_ of pipette - 'p300_single', 'p10_multi', etc
pipette 'model' being the specific model version of pipette -
'p300_single_v1.5', 'p+20_single_v2.0', etc
However, we didn't fully realize this throughout our stack. The name attribute
of both the robot singleton pipette objects and the hardware control pipette
objects (and everything that depended on them) still used 'name' to mean
'model'. This causes confusion for devs and also bugs like
https://github.com/Opentrons/opentrons/pull/3458
This PR fixes that by
- Making the 'name' attributes on both the old and new pipettes return the name
- Making new 'model' attributes on old and new pipettes that return the model …
> refactor(api): Normalize our use of name and model internally

- .eslintrc.js
- package.json
- yarn.lock
- add lint rules for React hooks
Run `yarn`, try to write some disallowed hook stuff and see the linting give you clear errors :sunglasses: 
Is the order of new plugin/rules in `.eslintrc.js` ok?
> style(js): use recommended "rules of hooks" lint rules

- update-server/tests/buildroot/test_update.py
This test sometimes fails because we don't catch the writing stage.
Fundamentally, we're checking that we progress ok to the done stage, so let's
not fail the test if the asynchronous execution means we miss "writing".
> refactor(update-server): Allow vairable test execution times

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
This is necessary for implementing the json protocol v3 format, which contains
labware definitions inline in the protocol.
Rather than go through labware.load, clients can now call
robot.add_container_by_definition with a definition dict and a string slot name
to load the container.
> feat(api): Allow loading labware v2 definitions directly into apiv1

- app/src/components/ChangePipette/index.js
- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/components/InstrumentSettings/InstrumentInfo.js
This PR serves as a bug report and fix. A recent API update returns both a `name` and `model` for attached pipettes. The `AttatchedInstrumentsCard` and `InstrumentInfo` were using `name` for `robot.name` which caused a conflict resulting in broken routes for change pipette and pipette settings.
This PR changes `name` (robot) prop to `robotName` which fixes the pipette modal routes.
This PR also found another bug with confirming detached pipettes. That should be fixed now as well.
- fix(app): Re-enable change pipette and pipette settings (robotName prop)
- fix(app): Swap out pipette name in change pipette routes with React Hook.
Please test on a robot with edge installed and one with an older version of the API!
Files that are not affected by this PR but should be double checked if …
> fix(app): Re-enable change pipette and pipette settings

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_transfers.py
This commit adds `Labware.previous_tip` and `Labware.return_tips`, which are the
inverse of `Labware.next_tip` and `Labware.use_tips` respectively. These
functions allow returning tips to the tip tracker and making them available
again for further use.
ProtocolContext.return_tip and ProtocolContext.drop_tip (if the target location
is a tiprack) will try and return the tip to the tip tracker when called;
however, because this logic is somewhat complex and race conditions are easy to
find, it doesn't raise an error if the tip can't be returned.
> feat(api): apiv2: allow returning tips to the tip tracker

- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/protocol_api/test_context.py
This PR serves as a ticket and a bug fix. During testing of a separate behavior it was found that the default transfer drop tip behavior in V2 is to return to tip rack.
- ~Remove `trash` kwarg check and add in `return_tip` kwarg~
- Default to dropping tip in trash instead of in tip rack.
Test on Robit using this script
```
def run(ctx):
tiprack = ctx.load_labware_by_name('opentrons_96_tiprack_300_ul', '1')
plate = ctx.load_labware_by_name('generic_96_wellplate_380_ul', '2')
pip = ctx.load_instrument('p300_multi', mount='right', tip_racks=[tiprack])
pip.transfer(10, plate.wells('A1'), plate.wells('A2'))
pip.transfer(10, plate.wells('A1'), plate.wells('A2'), return_tip=True)
```
> fix(api): Fix default transfer tip behavior

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/config/test_pipette_config.py
- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/robot-data/pipetteModelSpecs.json
Closes #3345. This feature allows a user to specify whether v1.5 multi-channels can double drop tip or not.
- Add double drop tip quirk to pipette config
- Check for it in V1 and V2
- Modify save settings format slightly for @Kadee80 such that to modify a setting you should type:
```
quirkName: {value: true/false}
```
You can test at your convenience in V1 or V2 on bitter-wood using the following scripts:
V1
```
from opentrons import labware, instruments, robot
tiprack = labware.load('opentrons-tiprack-300ul', '1')
plate = labware.load('96-flat', '2')
pip = instruments.P300_Multi(mount='right', tip_racks=[tiprack])
pip.transfer(10, plate.wells('A1'), plate.wells('A2'))
pip.drop_tip()
pip.return_tip()
```
V2
```
def run(ctx):
tiprack = …
```
> feat(api): Enable Double Drop Quirk

- api/src/opentrons/protocols/__init__.py
- api/src/opentrons/protocols/execute_v1.py
- api/src/opentrons/protocols/execute_v3.py
- api/tests/opentrons/protocols/test_execute_v1.py
- api/tests/opentrons/protocols/test_execute_v3.py
Closes #3449
NOTE: this also validates v1 JSON protocols and returns an error if they fail to validate. That's a new behavior for APIv1.
- Test v3 protocol on robot running on APIv1 -- try this protocol for example 
[full-forSethBot.json.zip](https://github.com/Opentrons/opentrons/files/3208408/full-forSethBot.json.zip)
on the robot called... ":office::heavy_check_mark::coffee:"
- Make sure v1 JSON protocols still work on APIv1
> feat(api): support running v3 protocols in APIv1

- api/src/opentrons/config/robot_configs.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/config/test_robots_config.py
- api/tests/opentrons/drivers/test_driver.py
In order for users to be able to migrate back and forth between 3.9.0 and some earlier SW version, we need to create a separate key for the new steps per mm shape (which is a dictionary where previously it was a string).
- Create new key in robot_config.py called `gantry_steps_per_mm` this is the value the software will use moving forward in order to fallback to a default of the proper shape
- Return `steps_per_mm` to its old string shape which included the GCODE baked into the command.
On a robot that hasn't previously been upgraded to 3.9.0:
1. upgrade to 3.9.0
2. downgrade to some other SW version (ensure that this step does not fail)
3. upgrade to 3.9.0 again
> fix(api): Add separate key for new steps per mm shape

- labware-library/src/index.hbs
- labware-library/webpack.config.js
Following up on #3440, this PR ensures the GTM ID is pulled in at build time, not run time
- chore(labware-library): Fix GTM config from env var
> chore(labware-library): Fix GTM config from env var

- api/src/opentrons/deck_calibration/endpoints.py
This PR is both a bug report and a fix.
When the robot moves to the "attachTip" point in apiv1 deck cal, it moves to
z=150. This is normally fine. However, a gen2 pipette tops out at z=172, which
means that if a tip is longer than 22mm in config, when the robot moves to
attachTip at the end of deck calibration (with a tip attached) it will move high
enough to trigger the home switch.
The fix is to take the length of a tip into account when moving to the attachTip position when a tip is already attached, effectively using the nozzle critical point.
Tested by successfully running deck calibration using a gen2 p20 single (the original bug report was from @ChrisYarka ).
> fix(api): Account for tip length in deck cal move-to-front

- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/icons/icon-data.js
- labware-library/src/components/App/Page.js
- labware-library/src/components/App/__tests__/Page.test.js
- labware-library/src/components/App/__tests__/__snapshots__/App.test.js.snap
- labware-library/src/components/App/index.js
- labware-library/src/components/LabwareDetails/InsertDetails.js
- labware-library/src/components/LabwareDetails/LabwareDetailsBox.js
- labware-library/src/components/LabwareDetails/WellDimensions.js
- labware-library/src/components/LabwareDetails/WellSpacing.js
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/LabwareList/styles.css
- labware-library/src/components/labware-ui/WellProperties.js
- labware-library/src/components/labware-ui/styles.css
- labware-library/src/definitions.js
- labware-library/src/localization/en.js
- labware-library/src/types.js
- shared-data/definitions2/opentrons_24_tuberack_generic_2ml_screwcap.json
- shared-data/js/types.js
- shared-data/labware-json-schema/labwareSchemaV2.json
~**Blocked by #3490** - this PR to be rebased once 3490 is merged~ rebase completed
This PR adds well bottom shape and well group display name to the high-level well/tube details box in both the Labware Card and Labware Details Page. Closes #3245
- Add well bottom shape and display name to labware library UI
<http://sandbox.labware.opentrons.com/lablib_high-level-well-ui>
> refactor(labware-library): Add well bottom shape and display name to UI

- labware-library/src/components/LabwareDetails/Dimensions.js
- labware-library/src/components/LabwareDetails/InsertDetails.js
- labware-library/src/components/LabwareDetails/LabwareDetailsBox.js
- labware-library/src/components/LabwareDetails/WellDimensions.js
- labware-library/src/components/LabwareDetails/WellSpacing.js
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/Sidebar/FilterCategory.js
- labware-library/src/components/labware-ui/WellCount.js
- labware-library/src/components/labware-ui/WellProperties.js
- labware-library/src/components/labware-ui/index.js
- labware-library/src/components/labware-ui/labels.js
- labware-library/src/localization/en.js
- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/step-generation/test-with-flow/__snapshots__/fixtureGeneration.test.js.snap
- shared-data/definitions2/opentrons_24_aluminumblock_generic_2ml_screwcap.json
- shared-data/definitions2/opentrons_40_aluminumblock_eppendorf_24x2ml_safelock_snapcap_generic_16x0.2ml_pcr_strip.json
- shared-data/definitions2/opentrons_96_aluminumblock_biorad_wellplate_200ul.json
- shared-data/definitions2/opentrons_96_aluminumblock_generic_pcr_strip_200ul.json
- shared-data/definitions2/usascientific_12_reservoir_22ml.json
- shared-data/fixtures/fixture12Trough.json
- shared-data/js/types.js
- shared-data/labware-json-schema/labwareSchemaV2.json
~**Blocked by #3497**. PR will be rebased once 3497 is merged~ Unblocked
This PR renames "troughs" to "reservoirs" and adds the "aluminumBlock" display category. Closes #3446 and closes #3481.
- Rename troughs to reservoirs
- Add aluminum block category
<http://sandbox.labware.opentrons.com/lablib_al-blocks-and-reservoirs/>
> refactor(labware-library): Rename troughs to reservoirs and add al. block cat.

- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/icons/icon-data.js
- labware-library/src/components/LabwareList/LabwareCard.js
- labware-library/src/components/LabwareList/index.js
- labware-library/src/components/Nav/styles.css
- labware-library/src/components/Sidebar/FilterManufacturer.js
- labware-library/src/components/labware-ui/ManufacturerStats.js
- labware-library/src/components/labware-ui/styles.css
- labware-library/src/components/ui/ExternalLink.js
- labware-library/src/components/ui/index.js
- labware-library/src/components/ui/styles.css
- labware-library/src/definitions.js
- labware-library/src/filters.js
- labware-library/src/localization/en.js
- labware-library/src/types.js
This PR adds brand links and SKUs for labware and inserts to the card and details page. It also adds insert brands to the manufacturer filters. Closes #3477
- Add labware/tube brand info to UI and filters
<http://sandbox.labware.opentrons.com/lablib_add-brand-info>
Acceptance criteria from ticket:
This PR doesn't add any new responsive behavior, so please also make sure everything displays / expands in a sane manner
> refactor(labware-library): Add labware/tube brand info to UI and filters

- update-server/otupdate/balena/__main__.py
The buildroot migration process is no longer gated behind a feature flag.
> feat(update-server): Default buildroot migration to available

- protocol-designer/src/labware-defs/selectors.js
PD is still held together with funky shims while we move to v2 labware defs. Right now there is a default `type: fixed-trash` labware on the deck, and it whitescreens PD because `fixed-trash` mapping is not included in the shim. This fixes the whitescreening by mapping `fixed-trash` to the new 1.1L trash defn.
> fix(protocol-designer): add "fixed-trash" labware type to v1->v2 shim

- components/src/deck/LabwareRender.md
Super minor cleanup, @b-cooper pointed out that I left the `LabwareRender` component library examples broken after changing the type of the props from Set<string> to WellGroup.
:eyes:
> docs(components): fix LabwareRender.md

- shared-data/labware/definitions/2/generic_96_wellplate_1.5ml_deep/1.json
- shared-data/labware/definitions/2/opentrons_96_tiprack_1000ul/1.json
- shared-data/labware/definitions/2/opentrons_96_tiprack_10ul/1.json
- shared-data/labware/definitions/2/tipone_96_tiprack_200ul/1.json
The offsets for the following tipracks were not quite right: opentrons 10ul, 1000ul tiprack and tipone 200ul tiprack
- Update offests for above defs
- Modify name of deep well plate to be generic as usa scientific does not carry circular deep well plates
Test on robot if you want
> fix(shared_data): Change deep well name, modify tipracks

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_offsets.py
Part of #3471. Because custom labware cannot be assigned an otId, we cannot use it in the API. This removes the last references in the API to `otId`.
* remove all references to `otId` from API
* Please sanity check!
* This affects APIv1 calibration. When this commit is released, users' calibration offsets that used `{otId}.json` will not be deleted but they will no longer be accessed. Those users will have to re-calibrate. I believe that only v2 labware will be affected. Are external users working with labware loaded via `load_new_labware_def` from APIv1?
> feat(api): do not use labware otId

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/main.py
When the api server boots, if it can't communicate with the smoothie (in this
case because there was a non-backwards-compatible smoothie firmware update,
which is a perfectly reasonable thing to have) it programs the attached
smoothie. This works fine on apiv1. Unfortunately, in apiv2, when the server
first fails to communicate with the smoothie it ends up with a simulating
backend, which doesn't actually do the update.
To fix this, factor the initial smoothie firmware update down to its own
function that just uses the driver directly; this is correct for both api
versions and avoids the rest of the stack purposefully. This is normally a
layering violation but here is best thought of as startup bootstrapping code
that only runs once.
Closes #3501
To test, use the attached smoothie hex and …
> fix(api): Fix first-boot smoothie updates for apiv2

- api/Makefile
I don't know why using shx suddenly broke on my computer, but it definitely did.
Using npx shx works though.
Test if this works on your machine.
> fix(api): Use npx shx instead of shx directly

- api/src/opentrons/api/calibration.py
- api/src/opentrons/api/routers.py
- api/src/opentrons/api/session.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/server/__init__.py
- api/src/opentrons/server/endpoints/control.py
- api/tests/opentrons/api/test_session.py
Force synchronization and serialization of motion commands.
These changes operate at two levels. The first, lower, level is synchronization around `_send_command` in the smoothie driver. This is necessary to prevent smoothie driver calls from different threads racing to read the single serial buffer; if this happens, the error recovery mechanisms then race and break various things inside the pyserial `Serial` object. By wrapping `_send_command` in a lock, we avoid this problem.
Unfortunately, while this lock prevents corruption of internal data structures, it still allows strange robot behavior if a client is commanding two higher-level moves at a time. Consider a client that starts a tip probe via rpc, then starts a home. With only the smoothie lock, the many smoothie commands that make …
> fix(api): Synchronize access to the smoothie and rpc

- protocol-designer/src/top-selectors/tip-contents/index.js
Just a little cleanup towards #3334
* avoid indirect dependency between PD and `Labware` component to better decouple PD from v1 defs
- just changing flow types, so shouldn't change anything in PD
> refactor(protocol-designer): remove PD dependency on old Labware component

- shared-data/js/modules.js
This PR serves as a ticket and fix. Somehow the path to the modules definition in shared-data was incorrect. Instead of pointing to the definition itself, the path was pointing to the schema.
This caused the app to white screen on edge whenever someone clicked on the `pipettes and modules` page.
- Edit the path to point to modules definitions
Try on edge, then on this branch to see the difference. 🌆 2.0 has modules connected.
> fix(shared_data): Fix module path in shared data

- .flowconfig
according to 'flow ls', flow was not ignoring what it was supposed to! I don't think it ever was :/
See https://flow.org/en/docs/config/ignore/
Maybe flow will be faster for you now? This shaved 10sec off of `time yarn run flow check` for me though I only compared N=1 with N=1 so who knows
> chore(flow): fix .flowconfig ignore rules

- .flowconfig
Last `.flowconfig` PR was passing itself, but doesn't get along with the latest `edge`. This fixes the failing `edge` build by treating shared-data definitions as untyped, not ignored.
It also marginally speeds up flow by not type checking any `node_modules`, while not ignoring them completely (so we don't need stubs for everything)
> fix(flow): declare node_modules and shared-data defs as untyped

- labware-library/src/components/ui/LabeledValueTable.js
- labware-library/src/components/ui/TableTitle.js
- labware-library/src/components/ui/styles.css
This PR implements a UI change request:
- refactor(labware-library): Update TableTitle expandable styles
http://sandbox.labware.opentrons.com/lablib_table-title-stylefix
> refactor(labware-library): Update TableTitle expandable styles

- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/UploadRobotUpdate.js
- app/src/components/RobotSettings/styles.css
- app/src/config/index.js
addresses #3560 by adding new advanced setting to allow users to select a local file behind a feature flag
Note: Browse button in advanced settings opens browse file window but selecting a file does not do anything yet.
- refactor(app): Add upload robot update to advanced settings behind ff
Standard code review
`make -C app dev` 
`make -C app dev OT_APP_DEV_INTERNAL__ENABLE_BUILD_ROOT=1`
> refactor(app): Add upload robot update to advanced settings behind ff

- api/tests/opentrons/containers/test_containers.py
- api/tests/opentrons/containers/test_grid.py
- api/tests/opentrons/containers/test_placeable_unittest.py
- api/tests/opentrons/helpers/test_helpers.py
- api/tests/opentrons/integration/test_protocol.py
- api/tests/opentrons/labware/test_pipette_unittest.py
- api/tests/opentrons/util/test_vector.py
This has been a todo for a while; we use pytest and pytest has only limited
integration with unittest. Removing these allows for future use of pytest
features that do not work with unittest, like more complex fixturing.
The files that have `unittest` in the name unfortunately still do because often there's duplicates!
> chore(api): Remove all tests that use the unittest library module

- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.js
Changing the pipette field now resets flow rate and tip offset fields.
This also affects pipette swapping in the Edit Pipettes modal. Before
this fix, it wouldn't actually clear out the fields the warning modal says it would.
> fix(protocol-designer): fix bug with pipette field change

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
- protocol-designer/src/labware-defs/utils.js
Closes #3525 
Here's an example of a 24-well plate with the last well deleted so you can tell which version PD is using -- put it in the correct place in `shared-data` and `make -C protocol-designer dev`, you should see the missing well when you add that labware via the Add Labware modal.
[corning_24_wellplate_3.4ml_flat___V2_EXAMPLE.zip](https://github.com/Opentrons/opentrons/files/3298451/corning_24_wellplate_3.4ml_flat___V2_EXAMPLE.zip)
* Right now the TRASH category is empty, but soon we'll have a definition for that (I think?) otherwise we can filter out any empty categories in a separate tiny ticket
* Also we've talked about pulling out these "getLabware" functions that use `require.context` and putting them into `shared-data` with global jest mocks (like we do for deck defs). Can …
> feat(protocol-designer): select only latest labware

- protocol-designer/src/components/DeckSetup/LabwareOverlays/LabwareName.js
- protocol-designer/src/components/EditableTextField.js
- protocol-designer/src/components/IngredientsList/LabwareDetailsCard/index.js
- protocol-designer/src/labware-ingred/__tests__/containers.test.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/__tests__/utils.test.js
- protocol-designer/src/labware-ingred/actions/actions.js
- protocol-designer/src/labware-ingred/actions/thunks.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/labware-ingred/utils.js
- protocol-designer/src/ui/labware/selectors.js
"Disambiguation numbers" are the UI elements that distinguish labware with the same names eg "Some Trough" vs "Some Trough (1)".
Right now on `edge` disambiguation numbers are not working right at all, this fixes that which closes #2424
This `getNextNickname` fn was a good place to use TDD so I have tests that should cover all the cases. If any cases are missing please comment.
See #2424 for details but basically test combinations of: 
- create several new labware with default and custom names
- delete then create
- duplicate labware
- rename already-named labware via the "Name & Liquids" menu.
> fix(protocol-designer): redo disambiguation nums for labware

- labware-library/src/components/labware-ui/Gallery.js
- labware-library/src/components/labware-ui/styles.css
#3590 made a change to `<RobotWorkSpace>` to remove its intrinsic `width: 100%; height: 100%` in favor of passing in a className at use time.
I missed updating the `RobotWorkSpace` usage in LL. This PR fixes that oversight to get the labware renders working again.
- Fix RWS usage in labware-library by re-adding width and height
<http://sandbox.labware.opentrons.com/refactor_fix-ll-rws>
Please check that labware renders actually show up now
> refactor(labware-library): Fix RWS usage by re-adding width and height

- shared-data/pipette/definitions/pipetteModelSpecs.json
The model offsets for gen2 pipettes were incorrect, in some cases incorrect
enough to cause head crashes during tasks like deck calibration. After
consultation with hardware, these are the correct values.
To test,
1. do a deck calibration with a gen1 pipette (or know that this has already happened)
2. start a deck calibration with a gen2 pipette
3. note that the pipettes, and especially the p20, don't smash the tips attached to them
> fix(api): Fix gen2 model offsets

- components/src/deck/RobotCoordsForeignDiv.js
- components/src/lists/ListItem.md
Resolve issue with transform="none":
- Chrome was logging `Error: <foreignObject> attribute transform: Expected transform function, "none".`
- Firefox was logging `Unexpected value none parsing transform attribute.`
Also while I'm at it, fixes component library error about `StaticRouter` requiring `context`
PD should work the same
> fix(components): fix console error with invalid transform

- __mocks__/electron.js
- app-shell/src/__tests__/discovery.test.js
- app-shell/src/discovery.js
- app-shell/src/main.js
Several Windows users (e.g. see #3482) have reported "phantom" processes sticking around after the app is quit. The processes seem to stack, and in some cases cause connectivity issues.
Upon further inspection, the app's main process was not properly cleaning up:
- Its reference to the main application window
- The discovery client
This PR fixes those oversights and closes #3482. Due to the nature of the bug, it's possible (or even likely) that these phantom processes are present on macOS and Linux and just haven't been observed.
-  Clean up main window and stop discovery client on app quit
1. Install sandbox app build from this branch on a Windows machine
- https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.9.0-win-b10888-app-shell_exit-cleanup.exe
2. Open app
3. Observe app and …
> fix(app-shell): Clean up main window and DC on app quit

- CONTRIBUTING.md
- api/buildroot.mk
- api/release-notes.md
When we ship buildroot, we will decouple the release of app and robot software -
though we will continue to release them at the same time, they are no longer
bundled. We need to add the release notes, which the app provided for both
projects, to the api separately, so they can be delivered separately. In this
case, they will be plopped in the buildroot binaries dir for buildroot to put in
s3 and include in zip files.
Closes #3626
> chore(api): Add api-specific user facing release notes

- app-shell/src/buildroot.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateBuildroot/index.js
- app/src/components/RobotSettings/UpdateBuildroot/styles.css
- app/src/pages/Robots/RobotSettings.js
- app/src/shell/__tests__/buildroot.test.js
- app/src/shell/buildroot.js
- app/src/shell/index.js
Addresses #3561 by showing System Update (buildroot migration) modal when buildroot files are present and version is greater than robotApiVersion.
- refactor: Change robot update button text based on FF enabled and buildrootUpdateAvailable
- refactor: Auto pop up modal when FF enabled and buildrootUpdateAvailable and not set to ignored
- refactor: Add `setBuidrootUpdateIgnored` action to buildroot 
- clicking not now in new `BuildrootUpdate` modal sets update to seen in buildroot state
This issue has a lot of acceptance criteria that is dependant on future work, such as showing a buildroot update release notes (which we will not have until [seths PR](https://github.com/Opentrons/opentrons/pull/3628) lands, and detecting if a robot is already migrated off Balena and on buildroot (todo, …
> refactor(app): View buildroot update notification

- protocol-designer/src/components/modals/FileUploadMessageModal/FileUploadMessageModal.js
- protocol-designer/src/components/modals/FileUploadMessageModal/index.js
- protocol-designer/src/components/modals/FileUploadMessageModal/modalContents.css
- protocol-designer/src/components/modals/FileUploadMessageModal/modalContents.js
- protocol-designer/src/components/modals/FileUploadMessageModal/types.js
- protocol-designer/src/components/modals/modal.css
- protocol-designer/src/configureStore.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/load-file/migration/index.js
- protocol-designer/src/load-file/reducers.js
- protocol-designer/src/load-file/types.js
Closes #3611
- Try uploading an old protocol file (eg from current designer.opentrons.com), you should get the modal specified in 3611 (see the latest design that Pantea posted in that issue thread)
- Make sure it works on small laptop screens (it will scroll in y)
- The `UNDO_LOAD_FILE` action isn't the nicest, because the way files are loaded in PD doesn't support "cancelling" a load after you loaded it. Since we don't have good stories around that, I'm happy with this temporary lightweight `UNDO_LOAD_FILE` thing until we do a more comprehensive approach (later we will also want to finally remove the old `window.confirm`s and may consider some stories around persisting an unsaved file in browser storage and/or remote storage)
> feat(protocol-designer): warn on migrating to 3.0.0

- api/src/opentrons/server/__init__.py
This serves as a ticket report and fix. @ChrisYarka reported a bug when cancelling a protocol which resulted in this error propagating: 
According to the [python docs](https://bugs.python.org/issue31803), `time.clock()` has been deprecated since 3.3. The C equivalent of `time.clock` says that [issues may occur ](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.bpxbd00/clock.htm)if the system is ever reset.
`time.perf_counter()` is an alternative, and was decided on based on [this](https://www.webucator.com/blog/2015/08/python-clocks-explained/) break down of python clocks.
- change time.clock() to time.perf_counter()
Test that you can cancel and reset a protocol without the error above.
> fix(api): Remove usage of time.clock()

- app-shell/src/buildroot.js
#3629 broke the app's main process because `getConfig('devInternal')` might be `undefined`. This PR adds the missing `?` to protect us from that case
- refactor(app-shell): Add missing existence check to FF object
App boots normally and the main process works (e.g. app config can be modified, React + redux devtools are installed, etc.)
> refactor(app-shell): Add missing existence check to FF object

- api/Makefile
make install-key in api will try and install an ssh public key.
It needs the host option
With no key options, it will try and load ~/.ssh/robot_key.pub
With br_ssh_key set, it will try and load $(br_ssh_key).pub
With br_ssh_pubkey set, it will try and load that file directly
This can be used to remote into robots with your own key, or robots that don't
have a key installed.
> chore(api): Make a makefile target for installing an ssh key on br

- api/docs/source/atomic commands.rst
You need to specify z_offset as a kwarg since it isn't the first positional
> chore(docs): Fix touch tip atomic command example

- api/setup.py
Because it uses request.post() instead of explicit multipart, the as-implemented
update server is limited to accepting 1MiB or smaller wheels. We're running up
against that, in large part because of some large labware definitions.
This PR inserts logic into our custom build command in setuptools to re-encode
all the json files in shared data with no newlines or spaces between delimiters.
This makes them basically impossible to read as a human, but does save a couple
KiB uncompressed per files (they're big), which translates into about 20kiB
savings in the compressed file.
- make a wheel on edge, save it somewhere, make a wheel in this pr.
- check that this wheel is smaller than that wheel, and that they contain all the same files
> chore(api): Minify json files in shared data when we build wheel

- api/src/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
Infer API version from protocol on upload. Closes #3537
- Add functions to session module to infer protocol version on upload, based on rules in issue #3537
Double-check that tests cover all relevant metadata packets and possible ways of writing imports
> refactor(api): Infer API version from protocol on upload

- components/src/__tests__/__snapshots__/modals.test.js.snap
- components/src/modals/AlertModal.js
- components/src/modals/AlertModal.md
- components/src/modals/ContinueModal.js
- components/src/modals/Modal.js
- components/src/modals/Modal.md
Add a prop to allow overriding default external scroll restriction on modal components in CL. This
should clear up the scrolling problems in CL as it is the only place that more than one modal
component is rendered simultaneously and out of view.
> fix(components): add remove scroll override prop to Modal

- api/src/opentrons/api/session.py
- api/src/opentrons/deck_calibration/__init__.py
- api/src/opentrons/deck_calibration/dc_main.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/hardware_control/socket_server.py
- api/src/opentrons/main.py
- api/src/opentrons/server/endpoints/__init__.py
- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/cli/test_cli.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/hardware_control/test_socket_server.py
- api/tests/opentrons/hardware_control/test_tip_probe.py
- api/tests/opentrons/server/calibration_integration_test.py
- api/tests/opentrons/server/test_calibration_endpoints.py
- api/tests/opentrons/server/test_settings_endpoints.py
This is in preparation for making a hardware control socket client that can look
the same as an in-memory hardware controller object.
If the hardware controller has synchronous methods that have to be exposed over
jsonrpc, clients can't exactly duplicate the API because those methods have to
be asynchronous to run the jsonrpc client.
Making all the properties and methods asynchronous complicates things somewhat
but allows for the possibility of drop-in replacement socket clients; and for
consumers that need synchronous access, the SynchronousAdapter still provides
functionality.
This is a large set of changes that probably shouldn't be merged without lots of time to test.
Run it on a robot, run some basic protocol actions.
> refactor(api): Make the hardware control API fully async

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
Closes #3664
See ticket for info & criteria
- Should cover both APIv1 and APIv2
> feat(api): default to labware version 1, not latest

- protocol-designer/src/components/DeckSetup/LabwareOverlays/LabwareName.js
- protocol-designer/src/containers/ConnectedTitleBar.js
Mike fixed the behavior where capitalizing `µL` looks like "ML" in most places (because capital mu is M). But we missed one place (at least :upside_down_face: ) -- the labware nicknames, which often contain "µL", especially in protocols that migrated from labware v1.
All places that labware name/nickname is capitalized should have `µL` transform to `UL` and not to `ML`:
- Title bar of Add Liquids modal
- On the deck
- Title bar of View Details modal
> fix(protocol-designer): fix labware nickname µL capitalization

- protocol-designer/src/components/DeckSetup/LabwareOverlays/BrowseLabware.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/EditLabware.js
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/steplist/actions/thunks.js
- protocol-designer/src/ui/steps/actions.js
Fix regression of scroll to top of step form on step select and extend similar functionality to the
BrowseLabware modal on drillDown. Fix intermittent reorder steps crash that occurs after moving a
labware at least once.
Closes #3679
> fix(protocol-designer): mend and extend scroll to top, fix reorder crash

- app/src/components/InstrumentSettings/InstrumentInfo.js
- app/src/components/InstrumentSettings/styles.css
- components/src/structure/LabeledValue.js
Correctly format display name for old pipettes and gen2 pipettes.
Closes #3594
> feat(app): display pipettes gen2 in pipettes card

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/deck_calibration/endpoints.py
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/tools/write_pipette_memory.py
- api/tests/opentrons/labware/test_pipette_constructors.py
- shared-data/pipette/definitions/pipetteModelSpecs.json
- shared-data/pipette/definitions/pipetteNameSpecs.json
- shared-data/pipette/schemas/pipetteModelSpecsSchema.json
Closes #3631 and closes #3484. This PR changes pipette model names such that they do not rely on a hw model version (i.e. GEN2 vs GEN1) to load the correct configs.
- Modify pipette Gen2 model names to volume_type_v2.0
- Modify display names for Gen2 pipettes to volume type GEN2
- Add a backCompat key on Gen2 pipettes to find name key of the older generation config to use
Make sure nothing snuck in from other PR. Check that code looks good and schema changes make sense.
> refactor(api): Rename model keys to be agnostic to hw model version

- api/src/opentrons/legacy_api/api.py
- api/tests/opentrons/config/test_pipette_config.py
- api/tests/opentrons/labware/test_pipette_constructors.py
- shared-data/pipette/definitions/pipetteModelSpecs.json
- shared-data/pipette/definitions/pipetteNameSpecs.json
Closes #3573. With this PR, you will now be able to use a multichannel gen2 pipette with correctly flashed model/id info.
- Add constructors for multichannel pipettes
- Add configs for gen2 multichannels
Anything missing and/or erroneously added?
> feat(api): Add Gen2 multichannel pipette api support

- shared-data/pipette/definitions/pipetteModelSpecs.json
Adds support for v1.5 rev of p50 single. Settings are identical to v1.4 except
for a new aspirate function (and removal of the "legacy" function).
Closes #3680
> feat(api): Add P50Sv1.5

- api/src/opentrons/protocol_api/back_compat.py
This is a regression report and a fix.
#3637 made a lot of hardware control API elements async, including `fw_version`. Unfortunately, the update server imports the wheel and tries to check `fw_version` and send it back on requests to `/server/update/health`, and those requests then 500 because coroutines are not json serializable.
Luckily, the update server is doing this through `opentrons.robot`, which is a `BCRobot`, and already has an override for `fw_version`; so we can just change that to be synchronous. Also luckily the app now prefers `/health` (from the api server) for information like the smoothie version.
> fix(api): Make BCRobot fw_version sync again

- api/src/opentrons/server/endpoints/settings.py
Since we're letting users load v2 labware in v1, we always need to delete v2
labware calibration in factory reset. However, we only delete the database if
apiv1 is selected.
Closes #3700
> feat(api): Always remove v2 calibration

- api/src/opentrons/hardware_control/modules/thermocycler.py
There was a remnant safety to prevent opening the lid of the thermocycler from the python api when
it has set target temperature for the block. Let's remove this for now given that some of this is to
be handled in firmware and we need to limit opening more responsibly.  More immediately, this is to
unblock science testing.
> fix(api): unrestrict thermocycler lid at api level for testing

- labware-library/src/components/Sidebar/LabwareGuide.js
- labware-library/src/components/Sidebar/__tests__/__snapshots__/LabwareGuide.test.js.snap
- labware-library/src/components/Sidebar/styles.css
- labware-library/src/localization/en.js
This PR serving as a ticket and implementation. The "Labware Guide" links in the top-left of the labware library were placeholders. This PR adds the actual Intercom links.
- refactor(labware-library): Add actual links to labware guide
<http://sandbox.labware.opentrons.com/ll_guide-links>
Please note that the Intercom articles themselves are not live yet!
> refactor(labware-library): Add actual links to labware guide

- app/src/components/CalibrateLabware/instructions-data.js
THis PR serves as a bug report and fix. @howisthisnamenottakenyet noticed yesterday that the calibration instructions diagrams were defaulting to the well diagrams/text. This was due to the fact that we used to key reservoirs as troughs. This PR adds in reservoir to the diagram and instruction data.
- fix(app): Add reservoir calibration instruction support
Upload a protocol that contains a reservoir labware. Confirm that the instruction text/diagrams are for a reservoir type labware.
> fix(app): Add reservoir calibration instruction support

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/containers/test_containers.py
This serves as a bug report and fix for incorrect behaviors of labware v2 reservoirs and rectangular well labwares on apiv1.
Reservoirs (previously troughs) need special handling on apiv1 to interact
properly with multichannels. We keep the well size as 0 and manipulate the
center directly to land both single pipettes and the backmost nozzle of
multichannel pipettes at the back of the well, to minimize the surface area of
the hack and make both pipettes work.
Additionally, we need to _not_ do this for wells which are rectangular but are
not part of reservoirs.
To test, interact with a reservoir (such as `usascientific_12_reservoir_22ml`) and rectangular well plate (such as 'usascientific_96_wellplate_2.4ml_deep'`) and see that the pipette goes in the right place.
Note that as with labware …
> fix(api): Correct labwarev2 reservoirs on apiv1

- app-shell/electron-builder.json
Window's code-signing has been broken today due to an unresponsive timestamp server. According to electron-userland/electron-builder#3965, the old default server may heve been deprecated by Verisign. This PR switches our timestamp server to electron-builder's latest default (which we will pick up when we eventually update it).
The new server is Digicert's, who also happens to be the issuer of our Windows code-signing cert. This doesn't make any technical difference whatsoever, but is emotionally calming for me.
- build(app-shell): Use Digicert's timestamp server for code-signing
> build(app-shell): Use Digicert's timestamp server for code-signing

- shared-data/labware/definitions/2/opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical/1.json
- shared-data/labware/definitions/2/opentrons_15_tuberack_falcon_15ml_conical/1.json
- shared-data/labware/definitions/2/opentrons_6_tuberack_falcon_50ml_conical/1.json
This updates the z-definitions for the following, based on [modified drawings](https://drive.google.com/drive/u/1/folders/16hWi78UoWiwCxQLq0gnYWOAtg0R5PEj4) provided by HW
* opentrons_6_tuberack_falcon_50ml_conical
* opentrons_15_tuberack_falcon_15ml_conical
* opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical
To test in APIv2, upload this:
```
def run(ctx):
TEST_INDEX = 0
labware_list = ['opentrons_6_tuberack_falcon_50ml_conical',
'opentrons_15_tuberack_falcon_15ml_conical',
'opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical']
wells_list = [[0, 1, 4, 5], [0, 2, 12, 14], [0, 2, 8, 9]]
plate = ctx.load_labware_by_name(labware_list[TEST_INDEX], 1)
tiprack = ctx.load_labware_by_name('opentrons_96_tiprack_300ul', 11)
pipette = ctx.load_instrument('p300_single', 'right', tip_racks=[tiprack]) …
```
> fix(shared-data): patch v2 opentrons 15 and 50 mL tube racks

- api/src/opentrons/__init__.py
- api/src/opentrons/data_storage/database_migration.py
When the robot boots, it checks to see if the labware database is the right
version, creating it if necessary. If the version detected is incorrect, the
software ensures that it is up to date, then adds all containers from
default-containers.json. If this process gets interrupted (it takes a while, and
the robot can look like it is failing to boot, leading customers to interrupt
it) then the version is still set to be up to date, but the database will be
missing containers. This leads to customers unexpectedly failing to load
labware.
This change splits the detection of required database changes:
- migrations, which change the structure of the database, are gated behind the
user version. If the user version is out of date, the structure is changed.
- independent of the above, at boot (and …
> fix(api): always ensure labware db is up to date

- app/src/components/CalibrateLabware/InfoBox.js
- app/src/components/CalibrateLabware/styles.css
- app/src/components/CalibratePanel/LabwareList.js
- app/src/components/CalibratePanel/LabwareListItem.js
- app/src/components/CalibratePanel/styles.css
- components/src/lists/lists.css
- components/src/tooltips/Tooltip.js
This PR is a fix for unticketted UI bugs involving long labware names messing with the app's calibration UIs. Bugs reported by @howisthisnamenottakenyet 
- Show tooltips on disabled labware in the calibration list
- Wrap long labware names in the calibration info box rather than truncate them
- The truncation CSS was why long labware names would stretch the screen width out
- I couldn't get truncation to work after an hour of work
- Elected to allow the names to wrap, especially considering this UI will be replaced in the near(ish) future
To test, load a protocol with long labware names (or connect to robot with name already loaded)
> fix(app): Stop long labware names overflowing calibration screens

- protocol-designer/webpack.config.js
Bump to 3.0.1 from unreleased 3.0.0
relevant changes from 3.0.0 tag
* chore(protocol-designer): bump to 3.0.1
* feat(protocol-designer): update migration modal copy (#3709)
* fix(protocol-designer): update various styles to match designs (#3714)
* refactor(labware): Redo OT tiprack defs based on CAD data (#3699)
* fix(shared-data): patch v2 opentrons 15 and 50 mL tube racks (#3712)
* fix(labware): Fix generator well y calculation, update docs/schema (#3697)
* fix(api): change resume() back to sync fn (#3702)
* chore(js): update jest to v24; drop --runInBand (#3672)
* fix(protocol-designer): mend and extend scroll to top, fix reorder crash (#3681)
* fix(protocol-designer): inner mix in move liquid predictable tip height (#3418)
> chore(protocol-designer): bump to 3.0.1

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
When changing the smoothie driver in 628c6c47c79a656f9babd552784a96d99deb4852 to
be more robust and have better locking, the changes to the main comms sequence
around write_with_retries and handle_return started trying to handle and recover
from _all_ smoothie alarms, including the one generated by a call to
robot.halt() toggling the estop gpios. This interferes with (read: breaks
catastrophically) protocol cancel, which relies on this sequence:
```
run() rpc call         smoothie      stop rpc call
|                       |                |
smoothie cmd start -> executing          |
|                       | (estop) <-   halt
smoothie cmd raises <- ALARM             |
|                       |                |
exc raised, call done   |                |
(cancel)                | …
```
> fix(api): do not handle smoothie alarms from halt()

- app/src/components/RunLog/SessionAlert.js
- app/src/robot/reducer/session.js
In conjunction with #3721, this PR adds a very minimal amount of app-side logic to avoid swallowing protocol run errors that are _not_ the result of protocol cancellation.
Due to technical limitations with RPC, the run error alert does not display the error that API raises. But the fact that any sort of error banner is displayed is a significant improvement from ending the run without any success or failure indication.
**Note**: the app will still swallow some run errors after this PR. Specifically, it will swallow any error status that is emitted after a "stopped" (cancelled) status is emitted. This seems safe to me until the underlying API issue (#2994) is fixed
Fixes #1828
- fix(app): Do now swallow protocol run errors
- An error can be induced by telling the robot to go somewhere it …
> fix(app): Do not swallow protocol run errors

- api/src/opentrons/api/session.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/server/rpc.py
- api/tests/opentrons/hardware_control/test_socket_server.py
In apiv2, actions are more strongly serialized than in apiv1 because all the smoothie communication actually blocks the asyncio loop! We need to halt from outside the loop, and we also need to not talk to the smoothie and cause races from another thread.
To do this,
- Make `halt` actually ONLY toggle the smoothie e-stop gpios, not recover
- Make `stop` do the recovery
- Make session `stop` call `halt` then `stop` separately, giving time for ongoing smoothie commands to fail
And in the longer term, make a way to cancel protocols other than using a backdoor to get the smoothie to send an error.
Since this hits both apiv1 and v2, test cancelling a protocol on both apiv1 and apiv2.
> fix(api): apiv2: fix protocol cancel

- api/src/opentrons/tools/factory_test.py
- api/src/opentrons/tools/gantry_test.py
- api/src/opentrons/tools/overnight_test.py
- api/src/opentrons/tools/z_stage_test.py
- The data loss factory test gets spoofed by sending two crnls to smoothie,
which races with the smoothie's response and injects newlines into the data it
returns, breaking the test. Don't do this anymore.
- Hide logging that confuses the line involving hard limits
Testing:
- Run the tests on some robots, buildroot and balena, with default deck calibrations (i.e. `rm /data/deck_calibration*` first)
> chore(api): update factory tests logging and smoothie handling

- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateBuildroot/DownloadUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/InstallModal.js
- app/src/components/RobotSettings/UpdateBuildroot/ReinstallModal.js
- app/src/components/RobotSettings/UpdateBuildroot/ReleaseNotesModal.js
- app/src/components/RobotSettings/UpdateBuildroot/SkipAppUpdateMessage.js
- app/src/components/RobotSettings/UpdateBuildroot/SyncRobotMessage.js
- app/src/components/RobotSettings/UpdateBuildroot/SyncRobotModal.js
- app/src/components/RobotSettings/UpdateBuildroot/SystemUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/UpdateAppMessage.js
- app/src/components/RobotSettings/UpdateBuildroot/UpdateAppModal.js
- app/src/components/RobotSettings/UpdateBuildroot/UpdateRobotModal.js
- app/src/components/RobotSettings/UpdateBuildroot/VersionList.js
- app/src/components/RobotSettings/UpdateBuildroot/ViewUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/index.js
- app/src/components/RobotSettings/UpdateBuildroot/styles.css
- app/src/components/RobotSettings/UpdateBuildroot/types.js
- app/src/discovery/selectors.js
- app/src/discovery/types.js
- app/src/pages/Robots/RobotSettings.js
- app/src/shell/__tests__/api-update.test.js
- app/src/shell/__tests__/buildroot.test.js
- app/src/shell/api-update.js
- app/src/shell/buildroot.js
- discovery-client/src/types.js
This PR 
- pops up sync robot modal when FF enabled and appVersion !== robotApiVersion
- clicking view robot update when robot is on balena then shows migration warning modal
- if buildroot files are not present, show placeholder download in progress/error modal
- gets new release notes from buildroot state
closes #3562 
closes #3561 
TODO in follow up PR:
- Format download progress/error screens and messages
Flow implemented based on discussion with @sfoster1 and @mcous 
- refactor(app): Show robot system update modal
- refactor(app): Add getBuildrootStaus selector
- refactor(app): Get BUILDROOT_RELEASE_NOTES from buildroot files
**Old flow**
`make -C app dev`
**Enable FF and point to manifest with release notes for testing**
```
make -C app dev OT_APP_DEV_INTERNAL__ENABLE_BUILD_ROOT=1 …
```
> refactor(app): Show robot system update modal

- api/src/opentrons/legacy_api/api.py
- api/tests/opentrons/labware/test_pipette_constructors.py
- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/js/pipettes.js
- shared-data/pipette/definitions/pipetteModelSpecs.json
- shared-data/pipette/definitions/pipetteNameSpecs.json
- shared-data/pipette/schemas/pipetteNameSpecsSchema.json
For a number of FE use cases, it is helpful to be able to distinguish "categories" of pipette names.
This adds a 'displayCategory' key and value to the pipetteNameSpecs and schema.
> feat(shared-data): add displayCategory to pipetteNameSpecs and schema

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
We didn't have InstrumentContext.speed implemented at all, and the rest of the
apiv2 stack was treating flow rates as if they were linear speeds. This
implements speed, and treats flowrates correctly.
Closes #3737
Closes #3270
Test:
Run the below protocols (apiv1 and apiv2). They have a fast blowout and a slow blowout. The blowouts should be the same speed in each api version, and in particular the slow blowout should have a `G0F31` command sent to the smoothie before the move (if you're using a p300 single; other pipettes will have different numbers for this one since it passes through `ul_per_mm`)
apiv2:
```python
def run(ctx):
tr = ctx.load_labware_by_name('opentrons_96_tiprack_300ul', 2)
trough = ctx.load_labware_by_name('usascientific_12_reservoir_22ml', 1)
pip = …
```
> fix(api): apiv2: Correctly handle flow rates and plunger speeds

- api/src/opentrons/drivers/mag_deck/driver.py
- api/src/opentrons/drivers/serial_communication.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/drivers/temp_deck/driver.py
- api/src/opentrons/drivers/thermocycler/driver.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/modules/__init__.py
- api/src/opentrons/legacy_api/modules/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py
- api/tests/opentrons/drivers/test_driver.py
Our serial logs track all data to and from the smoothie and the modules on an
equal footing. Since the smoothie and the modules all use gcode, when a robot is
connected to a smoothie and several modules it can be quite difficult to figure
out which serial traffic is for which source.
Instead, add a tag to serial logging that will differentiate between traffic to
the smoothie and to modules.
In addition, remove some very chatty error logs.
Just run with some modules attached and make sure nothing crashes
> chore(api): Add tags to differentiate serial log sources

- update-server/buildroot_upload.py
- update-server/otupdate/balena/endpoints.py
- update-server/otupdate/buildroot/control.py
- update-server/otupdate/buildroot/update_session.py
- update-server/otupdate/migration/endpoints.py
- update-server/tests/balena/test_server_boot.py
- update-server/tests/migration/conftest.py
- update-server/tests/migration/test_migration_api.py
- buildroot-migration should have always been in the capabilities subdict of the
health response
- given that it's now the same file as the update, make the migration system
accept ot2-system.zip
> refactor(update-server): fix capabilities and migration filename

- app/src/components/RobotSettings/UpdateBuildroot/DownloadUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/styles.css
This PR closes #3740 by adding download error/progress screens 
(Copy + Design pass needed)
- refactor(app): Add download progress bar and error content
Would appreciate feedback on titles/copy!
Enable FF 
```
make -C app dev OT_APP_DEV_INTERNAL__ENABLE_BUILD_ROOT=1 OT_APP_BUILDROOT__MANIFEST_URL="https://ot-test-bucket.s3.amazonaws.com/releases.json"
```
**Update File download error** (default since 3.10.0 is not in releases.json yet). 
*Be sure to delete __ot-buildroot_ folder!*
**Balena**
**Buildroot**
**Update File download progress**
*Fake app version 3.9.0 *  (3.10.0 is not in releases.json yet)
**Balena**
**Buildroot**
`downloadProgress: null` && `downloadError: null` (really slow internet but no error)
**Balena**
**Buildroot**
> refactor(app): Add download progress bar and error content

- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/protocol_api/test_context.py
This PR serves as an issue and a fix. When no blow_out location is passed, the pipette always blows out at the top of previous well, even if the previous location is `well.bottom()`. This is because `cache_location.labware`, rather than `cache_location`, is saved as the previous location. This PR updates the logic so that pipette would not longer deploys `move_to` if no location is passed, and blows out at the current position. Logic is copied from `aspirate` and `dispense`.
* uses the same logic as `aspirate` and `dispense` to determine the blow_out location 
* update test script accordingly
Test on robot. I will be testing this with the Science Team
> fix(api): fix blow out logic

- api/src/opentrons/legacy_api/api.py
This PR serves as an issue and a fix. When API v1 loading of pipettes was refactored, one piece of logic was missed. If a pipette gen2 was _referenced_ in a protocol, but no pipette was attached at all, then there would be a indexing error on the filtering of pipettes. That is due to the fact that pipette names for gen2 now have no indicator in the model names. i.e. `p20_single_gen2` expected substring would never have matched `p20_single_v2.0`.
- Change filter to check if the first half of the model key is found in the expected substring.
Test on a robot. On edge, call a pipette gen2 in a protocol without attaching any pipette. Notice that you get a list index error. Do the same on this PR and see that you do not get this error anymore.
> fix(api): Allow gen2 reference in protocol without pipette attached

- api/src/opentrons/tools/factory_test.py
This PR serves as a bug report and fix. While running the factory tests on new buildroot robots, we noticed that one of the functions used to call smoothie halt had a name change.
While fixing this, we ran into another problem with the command used to open a socket and find the IP address of the robot. I'm not sure why this was working before as when I tried to use the old command it returned an empty string.
- Fix smoothie halt function name
- Fix IP look up
Test on both balena and buildroot robots to make sure the script does not error.
> fix(factory_scripts): Remove old func name and refactor IP look-up

- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/server/test_control_endpoints.py
This PR closes #3722. Smoothie settings for pipettes such as home position and steps per mm should always be set back to default once it is detected that a non-gen2 pipette (or no pipette) is attached.
This behavior was only prevalent in API V1.
- Do not check if a pipette is present to set smoothie settings to default, just always do it.
On edge you should notice that the smoothie settings described above never get set back to default in V1. This PR fixes that.
> fix(api): Remove model name check for non-gen2 pipettes

- api/src/opentrons/legacy_api/robot/robot.py
This sets the log of `load_container` methods at a debug level
> refactor(api): change log level for load container methods

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
The driver was having issues fully reading the pipette model from the new GEN2 pipette PCBs EEPROM. To mitigate this, we have modified the delay after changing motor currents to 0.1 seconds and we have also disengaged the Z and A axes.
Test with pipette gen1 and pipette gen2s.
> fix(api): Modify delay and motors which are disengaged

- api/src/opentrons/protocol_api/contexts.py
In APIV2, we hadn’t yet changed pick_up_tip and drop_tip to call
commands.publish instead of using a decorator, and thus the decorators wouldn’t
pick up arguments that were deduced after the call, like picking up tips from
the tip racks
specified when creating an instrument, or dropping tips in the trash.
Closes #3364
Use a protocol like this:
```python
from opentrons.protocol_api import contexts
def run(ctx: contexts.ProtocolContext):
tr = ctx.load_labware_by_name('opentrons_96_tiprack_300ul', 1)
pip = ctx.load_instrument('p300_single', 'left', tip_racks=[tr])
pip.drop_tip()
```
and check that the runapp properly displays the location from which the tip is picked up and the location into which the tip is dropped.
> fix(api): apiv2: Display locs for drop/pickup from implicit locs

- api/src/opentrons/protocol_api/contexts.py
Happened to test Seth's tiprack PR with a gen2 pipette and noticed that it picked up tip 3x instead of once. This was happening because the protocol context `pick_up_tip` always defaulted to 3 presses and thus the hardware controller would never check the pipette config to use the correct number of presses.
- Set default presses to `None`
Test with a gen2 pipette in api v2 and see that it picks up the tip once.
> fix(api): Use pip config presses by default

- api/src/opentrons/hardware_control/__init__.py
- api/tests/opentrons/hardware_control/test_moves.py
APIv2 has this thing where if it detects it needs to home it will raise a
MustHomeError, which means most of the time it just doesn't move, which is
annoying and confusing for users. This homes instead of raising a MustHomeError.
This could be annoying for users too if it homes and then tries to do something
at the home position, but that's usually because of another error.
> refactor(api): apiv2: just home instead of raising an error

- labware-library/src/components/labware-ui/labware-images.js
- shared-data/labware/definitions/2/opentrons_96_filtertiprack_1000ul/1.json
- shared-data/labware/definitions/2/opentrons_96_filtertiprack_10ul/1.json
- shared-data/labware/definitions/2/opentrons_96_filtertiprack_200ul/1.json
Closes #3762.  This PR adds the definitions for `10`, `200` and `1000 uL` filter tip racks.
Technical drawings can be found [here](https://drive.google.com/drive/u/1/folders/1EJGJAV8y1d6G_v9vTakb09CecYWmMULM).
Tip rack images are the same as the non filter tip racks.
**Display Names**: 
- Opentrons 96 Filter Tip Rack 10 µL
- Opentrons 96 Filter Tip Rack 200 µL
- Opentrons 96 Filter Tip Rack 1000 µL
**API Names**: 
- opentrons_96_filtertiprack_10ul
- opentrons_96_filtertiprack_200ul
- opentrons_96_filtertiprack_100ul
> feat(shared-data): labwareV2: add filter tip racks

- api/src/opentrons/legacy_api/containers/__init__.py
Please review this PR ASAP so that we can do a release. On numerous robots in Shenzhen, when V2 labware was utilized and calibrated successive amounts of time the offset would start becoming so large that crashing would occur in the labware.
Switch back to V1 labware definitions has been a temporary workaround in the SZ office.
| On Edge  |   On this PR |
|----------|-------------|
| Calibrate up to 5x  | Calibrate up to 5x  |
See that over time on edge the calibration offset becomes so big that there is crashing and/or it misses the labware in some way.
Use this protocol:
```
from opentrons import labware, instruments
plate = labware.load('usascientific_12_reservoir_22ml', 1)
tiprack = labware.load('opentrons_96_tiprack_300ul', 2)
pip = instruments.P300_Single_GEN2(mount='right', …
```
> fix(api): Take difference of offsets found from calibration for v2 labware

- api/src/opentrons/hardware_control/simulator.py
Also while testing seth's tiprack PR I found another bug in v2 haha... Due to the nickname not being a subset of the model name in gen2 anymore, the simulator for api v2 no longer recognized `p300_single_gen2` as a valid name to load a pipette into a protocol context.
Check that you can load pipettes with the following string values:
`p300_single`
`p300_single_v1.4`
`p300_single_gen2`
`p300_single_v2.0`
> fix(api): Allow apiv2 to find pipettes by name versus model

- api/src/opentrons/data_storage/database_migration.py
This is a bug report and a fix.
If the labware database has been partially migrated - one or both of the schema
changes creating tables have occurred, but the sqlite user version has not yet
been set - then the next time the robot boots, it will try to recreate the
tables and die from an unhandled exception. This commit handles these exceptions
and moves to the next migration.
To test, run this python snippet on a robot running apiv1 then restart the api server. If you do this without the fix, the api server will crash on boot; with the fix, you'll get some messages in stdout but everything will be fine.
```python
import sqlite3
conn = sqlite3.connect('/data/opentrons.db')
conn.execute('PRAGMA user_version=0')
```
> fix(api): apiv1: handle partial db schema changes

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/config/robot_configs.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/config/test_robots_config.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/robot/test_robot.py
- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/pipette/definitions/pipetteNameSpecs.json
- shared-data/pipette/schemas/pipetteNameSpecsSchema.json
Closes #3694. Turns out multi-channel gen2's have a different homing position requirement because they are longer :o. This forced our hands to refactor how smoothie run-time configs are handled.
- Add smoothie run time configs into pipette name specs as it is a per pipette type value
- Add a few more tests for smoothie runtime configs
- Add default smoothie configs into robot_settings
Test on a robot, see that the configs are correctly set from a gen1 pipette to a gen2 pipette.
> refactor(api): Remove smoothie run time values from source code

- protocol-designer/package.json
- protocol-designer/webpack.config.js
- yarn.lock
Typeform is broken in PD, blocking any users that don't have the cookie already from using PD!
To reproduce (edge or production PD 3.0.1)
- Open an incognito tab and fill out the typeform
- When you click the "Submit" button, it shows a spinner then disappears. You never get an email and it doesn't direct you to the "check your inbox" page.
This also bumps PD version to 3.0.2 to reflect the hotfix (3.0.2 = 3.0.1 + the typeform version update and the OT_PD_VERSION bump, and no additional changes from `edge`)
> fix(protocol-designer): update typeform version

- api/src/opentrons/legacy_api/containers/placeable.py
- api/src/opentrons/legacy_api/instruments/pipette.py
A P50 pipette with a 300 uL tip attached would attempt to incorrectly aspirate 300 uL as its maximum volume during transfer/consolidate/distribute. This is because during `_create_transfer_plan`, the pipette's max volume is set to be the next tip's maximum volume. It should actually be the lesser of the tip's and pipette's max volumes. Rather than using `get_next_tip` to get the volume of the tip, it nows calls the very first tip of the pipette's available tip racks. 
closes #3789
- set max volume in _create_transfer_plan to be the lesser of the pipette's max volume and the volume of the very first tip of that pipette, if a tip rack is present
To test, simulate the protocol below and it should no longer fail:
```
from opentrons import instruments, labware
tipracks = …
```
> fix(api): apiv1: fix transfer volume

- .travis.yml
- app-shell/Makefile
Our Windows build configuration was not set up to properly ignore tags that don't match `^v.+`, which resulted in bogus Windows publish(es) for other tags (like PD and LL releases).
I couldn't exactly figure out AppVeyor's filtering logic for builds / deploys, so this PR modifies the Makefile in `app-shell` to ensure the release manifest files are not set to publish unless the tag matches `^v.+`
- build(app-shell): Only publish app release if tag matches ^v.+
You can try this out locally by setting the env vars that CI sets. Note that none of this will actually push anything to s3:
```shell
make -C app-shell dist-osx \
OT_APP_DEPLOY_BUCKET=opentrons-app \
OT_APP_DEPLOY_FOLDER=builds \
OT_BUILD=42 \
OT_BRANCH=foobar \
OT_TAG=v3.10.2
```
To test tagged or non-tagged builds, edit or omit …
> build(app-shell): Only publish app release if tag matches ^v.+

- app/src/components/RobotSettings/UpdateBuildroot/DownloadUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/InstallModal.js
- app/src/components/RobotSettings/UpdateBuildroot/InstallModalContents.js
- app/src/components/RobotSettings/UpdateBuildroot/MigrationWarningModal.js
- app/src/components/RobotSettings/UpdateBuildroot/ViewUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/progress.js
- app/src/components/RobotSettings/UpdateBuildroot/styles.css
This PR takes @mcous lovely session/state work and displays install modals accordingly for:
- Server Update (balena only)
- Restart
- System Update
- Restart (again)
- Update Error (might need some copy suggestions after UI final pass)
- Update Complete
closes #3565 closes #3567 closes #3568
- refactor(app): Add install modals for buildroot updates
Note: I am planning a follow up cleanup PR for CSS and possible logic simplification, but for now this PR is big enough. I think we should do a follow up UI pass since some screens have been improvised.
Please test the entire flow for both Balena and Buildroot robots/raspis
```
make -C app dev OT_APP_DEV_INTERNAL__ENABLE_BUILD_ROOT=1
```
**Balena**
- sending file to robot (bouncing spinner)
- applying update to robot (progress bar) …
> refactor(app): Add install modals for buildroot updates

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- app/src/components/CalibratePanel/styles.css
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
Separate calibration will now be required for instances of the same labware that exist in a given
protocol with a different direct parent type (e.g. slot, Thermocycler Module, Magnetic Module...)
Closes #3775
> feat(app, api): Key calibration by parent-type/labware-type combo

- api/src/opentrons/api/session.py
Raise an error if we're on apiv2 and the user tries to upload a protocol
targeting APIv1.
Closes #3750
> refactor(api): apiv2: raise error on api version mismatch

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/protocol_api/contexts.py
Provide a protection for calles to thermocycler.open() and .close() that prevents the possibility of
the lid colliding with the gantry. Before either command is sent to the module, the gantry will move
to a "safe" spot at the highest z above the fixed trash.
> feat(api): move gantry to safe spot while TC lid moves

- app-shell/src/__tests__/discovery.test.js
- app-shell/src/discovery.js
- app/src/components/RobotSettings/UpdateBuildroot/InstallModalContents.js
- app/src/discovery/__tests__/actions.test.js
- app/src/discovery/__tests__/epics.test.js
- app/src/discovery/actions.js
- app/src/discovery/epics.js
- app/src/discovery/index.js
- app/src/discovery/types.js
- app/src/epic.js
- app/src/index.js
- app/src/shell/buildroot/update-epics.js
Ticket + PR. When a robot migrates from Balena to buildroot, its advertised name changes from `opentrons-some-name` to `some-name`. The discovery client keys robots by name, so when a robot migrates we're left with two robots in discovery state.
This PR ensures the old robot is removed post-migration.
- refactor(app): Remove migrated balena robots from discovery
This PR also does some much needed cleanup in the app's `discovery` redux module:
- Action creators split out into `app/src/discovery/actions`
- Side-effects moved from thunks + custom middleware to epics
Testing:
> refactor(app): Remove migrated balena robots from discovery

- shared-data/js/labwareTools/index.js
1. Factor out fns `createRegularLoadName` and `createDefaultDisplayName` for use in Labware Creator
2. For the purpose of displaying a labware as you fill out the fields of Labware Creator, it's useful to get a definition back in cases where the definition isn't totally valid (some fields missing, well height exceeds labware zDimension, etc). So I added a `strict` parameter to the labware creation and validation fns that only throws when `strict` is true, so that I can get the imperfect "work in progess" labware definition for rendering in LC.
This should not change the behavior of `createRegularLabware` fn, just a refactor
> refactor(shared-data): labwareTools refactor for Labware Creator

- api/src/opentrons/system/nmcli.py
On buildroot, nmcli networking connectivity always returns unknown, probably
because of a file caching issue on a read-only rootfs. Changing the call to
nmcli networking connectivity check avoids the cache.
Closes #3768
Put this on both a balena and buildroot robot on a couple different kinds of connection (USB, wifi, etc) and check that it does the right thing still.
> fix(api): force nmcli to actively check for connectivity

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
hardware_control.API.blow_out leaves the plunger at the blowout position, since
it is possibly immersed in liquid. hardware_control.API.aspirate moves the
plunger directly to the target aspirate position. When you combine these, then
if you do a blow out then an aspirate, aspirate will move the plunger - while
immersed in the target well - from blowout directly to the target, which
overaspirates for the period when the plunger is moving from blowout to bottom.
The fix for this is complicated by the architecture of the hardware controller
very much wanting to only move the plunger, and nothing else, during aspirate,
dispense, and blowout, and have no knowledge of labware on the deck. That means
it's not safe to move the plunger from blowout to bottom in aspirate or blowout,
since in both …
> fix(api): apiv2: fix overaspiration after blowout

- api/Makefile
It takes a bit of time whenever you're making local-shell, and non-dev repo
users have problems with it sometimes.
> chore(api): move twine check to test target

- api/docs/source/new_protocol_api.rst
- api/src/opentrons/protocol_api/back_compat.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute_v1.py
- api/src/opentrons/protocol_api/execute_v3.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/data/testosaur_v2.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_back_compat.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_execute_v1.py
- api/tests/opentrons/protocol_api/test_execute_v3.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocol_api/test_labware_load.py
- api/tests/opentrons/protocol_api/test_module_context.py
- api/tests/opentrons/protocol_api/test_transfers.py
This PR encapsulates a number of small changes to the names of apiv2 functions and objects as described in the linked ticket. There's no real functionality or behavior differences, just a bunch of namechanges.
Most of the simple name changes have the old versions stick around with warning level logs about using them; the flow rate, speed, and clearance don't because the structure of them changed. This makes this a breaking change for APIv2, but APIv2 is also not publicly released.
- s/load_labware_by_name/load_labware/
- s/(wells,columns,rows)_by_index/(\1)_by_name/
- make flow rate, speed, and well bottom clearance accessed by attribute instead of as weird fake dicts that you have to assign over rather than modifying keys
Make sure it all makes sense, run or simulate some protocols. …
> refactor(api): apiv2 name changes

- components/src/forms/DropdownField.js
- components/src/forms/RadioGroup.js
These changes come from the Labware Creator branch.
We can't use Formik + RadioGroup correctly without passing in the `name` and `onBlur`
* pass thru name & onBlur
* make some inexact types exact
- 🐨 ?
> refactor(components): pass thru props for RadioGroup

- app/src/components/RobotSettings/InformationCard.js
- app/src/components/layout/index.js
- app/src/http-api-client/server.js
- components/src/buttons/Button.js
- components/src/hooks/__tests__/useInterval.test.js
- components/src/hooks/index.js
- components/src/hooks/useInterval.js
The new BR update flow is designed to update exactly one robot at a time because it drastically simplifies the state needed. This PR ensures the UI will not allow a user to try to kick off multiple BR updates to different robots
- refactor(app): Ensure BR update is disabled if a diff robot is updating
> refactor(app): Ensure BR update is disabled if a diff robot is updating

- api/src/opentrons/legacy_api/instruments/pipette.py
Transfers with blowout and mix after set were mixing before the blowout and once again after. We
should only be mixing before the blowout.
Close #2607
- this should be tested on robot
> fix(api): duplicate mix with blowout during transfer

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_transfers.py
This PR adds support for filter tips in apiv2 by introducing `_working_volume` as a pipette state property. The default working volume is always the max volume of the pipette. The new behavior is that when a pipette picks up a tip, the working volume gets updated to the lesser of the tip volume and the pipette max volume. Pipette `available_volume` will then be calculated using `working_volume` instead of `max_volume` to prevent over-aspiration. 
To retrieve the `totalLiquidVolume` from a well, `_max_volume` is added as a labware variable.
Closes #3674. See #3692 for the version for apiv1.
- add working volume as a pipette state variable
- add function to set working volume during tip pick up
- use working volume to determine pipette available volume instead of pipette max volume
- add …
> feat(api): apiv2: prevent over-aspiration with filter tips

- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/controls/LabeledToggle.js
- app/src/config/index.js
- app/src/config/types.js
Make it easier to test and configure unreleased code by exposing toggles for dev feature flags when devTools are enabled.
Now, when devTools are enabled in the Advanced Settings, devInternal settings are exposed as toggles at the bottom of the Advanced Settings section.
> refactor(app): toggle dev feature flags from settings

- CONTRIBUTING.md
- Makefile
- lerna.json
- package.json
- yarn.lock
This PR upgrades Lerna to the latest stable version to the old pre-release version we were on. This is mainly to have access to the `lerna version` command, that allows the bump process to be separated from the publish process.
This PR **does not** mess with our versioning scheme (change one thing at a time). It does, however, include some features (recognizing version tags on merged branches) that would enable #3847 if we chose to implement that RFC.
- chore: Upgrade lerna for "version" command
**`make bump` usage has changed!**
- Before: `make bump opts="--cd-version=preminor --preid=beta"
- After: `make bump version="preminor --preid=beta"
Also, for now Lerna config is locked to only allowing bumps on branches named `release_*`, so if you find yourself on this branch wanting to test a …
> chore: Upgrade lerna for "version" command

- api/src/opentrons/api/session.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/integration/test_server.py
This ticket alleviates #2047. Due to fundamental architectural problems with the RPC API's session state, it does not fix the issue completely. It should, however, make the run log less wrong than it was before
- fix(api): Do not publish commands for RPC pause/resume in APIv1
> fix(api): Do not publish commands for RPC pause/resume in APIv1

- app/src/components/CalibrateLabware/InfoBox.js
- app/src/components/ModuleControls/index.js
- app/src/components/ModuleLiveStatusCards/index.js
- app/src/components/PrepareModules/index.js
- app/src/components/PrepareModules/styles.css
- app/src/pages/Calibrate/Labware.js
- app/src/robot-api/resources/modules.js
- app/src/robot-api/resources/types.js
- app/src/robot-api/types.js
Provide a mechanism to open the lid of the Thermocycler Module during pre-run calibration, so that the contained labware can be calibrated.
Closes #3066
- with a closed thermocycler on deck, upload a thermocycler protocol to the robot and proceed to labware calibration
- after you've confirmed the module is connected, you should be prompted to open the lid before proceeding
- try again with the lid already open, you shouldn't see the blocking modal at all.
The firmware/hardware combination will not report 'closed' because of latch complications, until new units are in, the behavior of the "Open Lid" button will be either behave as if it's in progress. In order to allow testing, we keep the button enabled for now, despite the loading state. There is a TODO
> feat(app): prompt to open TC lid before labware calibration

- .gitattributes
The tool we use to check that our long description doesn't break on pypi doesn't
handle crlf, so at least in some cases (presumably depending on git settings) on
windows the check would always fail.
> chore(api): force pypi readme eols to lf

- .travis.yml
- api/Makefile
In #3846, latex warnings were causing CI to fail. As a workaround, the warnings were sent to /dev/null/ instead of the commandline. This PR is a refactor to that workaround so that local pdf builds can still print out warnings/not require a pdf build whereas a pdf build is required on CI.
- Require a pdf build if running on CI
- Add a local build option to allow for warnings
> refactor(docs): Allow warnings locally but suppress on CI

- api/docs/source/v2/new_modules.rst
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_module_context.py
- shared-data/deck/definitions/1/ot2_short_trash.json
- shared-data/deck/definitions/1/ot2_standard.json
- shared-data/deck/schemas/1.json
This adds `compatibleModules` to the slots within the deck schema and definitions within shared-data. The addition will allow us to be programmatic about slot/module compatibility as the robot server grows and changes.
The behavior of `protocol.load_module` in PAPIv2 is now slightly augmented.  It will behave the same as it has in the past for TD and MD (e.g. `protocol.load_module('Magnetic Module', 4)`).
Though the Thermocycler Module should now be loaded using `protocol.load_module('Thermocycler Module')` or `protocol.load_module('thermocycler')` with *no specified slot location*. Because the Thermocycler Module has a single compatible slot in the OT2 standard deck definition ('Slot 7'), this will load it into it's position unambiguously.
Similarly, you can load the TC explicitly using …
> refactor(api): add compatible modules to slot definitions and load by default slot

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/server/endpoints/logs.py
- api/src/opentrons/server/endpoints/settings.py
- api/src/opentrons/system/log_control.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
We already have the /settings/log_level/upstream, but it's a lot easier to add a
simple advanced setting that disables the aggregation, which the app can trigger
a modal on.
Also refactors syslog control out of the endpoint implementation.
Closes #3866
> feat(api): Add a log aggregation optout

- protocol-designer/package.json
- yarn.lock
they don't publish a changelog, so we don't know what's different :p
should still send email. There is no existing bug with the previous version but I'm gonna start bumping it before every PD release whenever I remember to 😠
> feat(protocol-designer): bump typeform/embed to v0.12.1

- shared-data/js/labwareTools/__tests__/__snapshots__/createIrregularLabware.test.js.snap
- shared-data/js/labwareTools/__tests__/__snapshots__/createLabware.test.js.snap
- shared-data/js/labwareTools/__tests__/createIrregularLabware.test.js
- shared-data/js/labwareTools/__tests__/createLabware.test.js
- shared-data/js/labwareTools/index.js
I messed up #3804, if strict was false it would "default" to true because of the `||`, oops!
Code review, see unit tests.
> fix(shared-data): fix "strict" arg for labware creation

- app-shell/src/buildroot/index.js
- app/src/analytics/selectors.js
- app/src/components/ConnectPanel/RobotItem.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateBuildroot/InstallModalContents.js
- app/src/components/RobotSettings/UpdateBuildroot/MigrationWarningModal.js
- app/src/components/RobotSettings/UpdateBuildroot/VersionInfoModal.js
- app/src/components/RobotSettings/UpdateBuildroot/ViewUpdateModal.js
- app/src/components/RobotSettings/UpdateBuildroot/index.js
- app/src/components/nav-bar/NavButton.js
- app/src/pages/Robots/RobotSettings.js
- app/src/shell/buildroot/__tests__/selectors.test.js
- app/src/shell/buildroot/actions.js
- app/src/shell/buildroot/reducer.js
- app/src/shell/buildroot/selectors.js
- app/src/shell/buildroot/types.js
While developing the BR update front-end, we leaned on the assumption that the current app version is always going to represent the latest available BR update. Due to how real world software delivery works, this assumption **doesn't hold up** for about 30 min after the latest app version is deployed and before the BR update is built and deployed
This sort of problem can (and should) be solved by separating out our artifact generation and artifact deployment stages, but in the mean time, we need to make sure the app gracefully handles the current version not being present in the BR releases.json manifest.
This PR implements that change by having the update check routine inform the UI that it has found a version entry in the releases manifest _before_ it starts downloading the files. …
> refactor(app): drive BR update logic from releases.json manifest

- app/src/shell/buildroot/update-epics.js
This PR serves as a bug ticket and fix. 
**Issue:** 
When a robot is connected via RPC, RPC unexpected robot disconnect modal would show during buildroot update restarts
Fix:
This PR disconnects any RPC session before starting any type of buildroot update.
- refactor(app): Disconnect RPC session on update start
Connect to a robot (RPC), then perform an update.
> refactor(app): Disconnect RPC session on update start
