- .gitignore
- opentrons_sdk/labware/containers.py
This PR removes a reliance on the current working directory & path hopping to find static files which made the package break when running in a frozen state (executable).
> 20160908 122400 pyinstaller

- .gitignore
- opentrons_sdk/drivers/motor.py
- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/labware/test_instruments.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR (by Katie and I):
* Adds a delay method on pipette that just waits
* Adds a set_speed method and a speed method that set and get the plunger speed (defaults to 300))
* Adds a pause and resume method - pause just halts the run method, queue resumes it
* Adds small unit tests for all of these methods
These were all tested on a robot in real life by us (in addition to unit tested).
Edit - I changed pause to jump to the beginning of the queue and edited the speed command in the driver so that it could change A, B, or XYZ speed (but not singular X/Y/Z speeds - this is not a 1.2 feature and I don't see support for it in the Smoothie docs)
> 52 special gcodes

- opentrons_sdk/containers/__init__.py
- opentrons_sdk/containers/placeable.py
- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/integration/test_protocol.py
- tests/opentrons_sdk/labware/test_instruments.py
This PR adds optional user-defined names to containers and instruments, which can be queried by name through `robot`
> optional user-friendly name for containers/instruments

- opentrons_sdk/labware/instruments.py
- sample_protocol.py
- tests/opentrons_sdk/labware/test_instruments.py
This PR adds:
Transfer - just an aspirate then a dispense (defaults to max vol, like aspirate and dispense)
Distribute - an aspirate (with an extra pull_volume), then a series of dispense to an array of wells, who each get (volume / length of wells)ul.
Consolidate - opposite of distribute, but with no extra_pull.
Mix - by default just dispenses and then aspirates current_volume 3 times. can be given a different number of repetitions.
These all have unit tests and have been tested on the robot.
> Transfer consolidate distribute

- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/labware/test_instruments.py
This PR:
1. Changes `Pipette.mix()` to just call `.aspirate()` and `.dispense()` instead of queueing it's own Commands
2. `.aspirate()` and `.dispense()` can take just a Placeable as argument, and volume will default to the full tip volume
3. `.dispense()` will accept a volume larger than it's current volume, converting internally to it's current volume so as not to move outside the plunger's limit
> 20161007 201600 fix mix and print command queing

- opentrons_sdk/drivers/motor.py
- opentrons_sdk/helpers/helpers.py
- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/command.py
- opentrons_sdk/robot/robot.py
- opentrons_sdk/util/vector.py
- tests/opentrons_sdk/drivers/test_motor.py
- tests/opentrons_sdk/helpers/test_helpers.py
- tests/opentrons_sdk/labware/test_instruments.py
- tests/opentrons_sdk/protocol/test_robot.py
- tests/opentrons_sdk/util/test_vector.py
This PR:
1. breaks down `motor.move_head()` commands into smaller steps so they can be paused
2. enqueues `motor.move_head()` commands, which can be paused, resumed, and stopped
3. refactored `robot.pause()`, `robot.resume()`, and `robot.clear()` handle the `motor`'s queue
4. removed "relative" movements from robot and instrument
> 82 m break down movements into discrete intervals and pause resume the queue test for precision

- opentrons_sdk/labware/instruments.py
- tests/opentrons_sdk/labware/test_instruments.py
This small PR addresses a feature request from the science team to be able to give a volume to the Mix command. A test was added for this (and for the previously untested repetitions arg).
> update mix to take optional volume, fix old test and add args test

- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/labware/test_instruments.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR:
1. Adds speed properties to `aspirate` and `dispense`, set with for example `p200.set_speed("aspirate", 300)`
2. Makes the `robot.home()` command queueable so it can be called within a protocol. Calling `robot.home(now=True)` will bypass the command queue
> 119 m allow aspirate dispense to set speed

- opentrons_sdk/drivers/motor.py
- opentrons_sdk/drivers/virtual_smoothie.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/drivers/test_motor.py
- tests/opentrons_sdk/drivers/test_virtual_smoothie.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR adds some more gcode functionality to the motor driver:
1. Power on/off the motors so they don't over-heat
2. Get the current state of the homing switches (this is added to robot as well)
3. Set the state of the Smoothieboard's 6 Mosfets (for example controlling the magbead module)
> 20161013 161000 expand gcode support

- opentrons_sdk/drivers/motor.py
- opentrons_sdk/drivers/virtual_smoothie.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/drivers/test_motor.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR adds `robot.diagnostics()`, which returns a dict containing version data, and robot state data. The versions include firmware, config, and OT models. The robot state contains the endstop switches, and a boolean for whether an axis has been homed or not (all reset to `False` after a connection is reset)
> 77 s diagnostics

- opentrons_sdk/labware/instruments.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/labware/test_instruments.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR:
1. Associates a placeable to the instrument inside the instrument
2. Refactors `Pipette.go_to()` and `Pipette.move_to()`
3. Adds `Pipette.move_to_bottom()`, `Pipette.move_to_top()`, `Pipette.go_to_bottom()`, and `Pipette.go_to_bottom()`,
> 129-s-move-instrument-placeable-assignment-from-robot-to-instrument

- opentrons_sdk/containers/placeable.py
- tests/opentrons_sdk/containers/test_grid.py
In this PR:
* Infer rows / columns from well indexes in a container
* Introduced WellSeries class to hold a series of wells
* Made WellSeries class a Placeable delegating all calls to a single well within it defined by offset. This way we won't require changes to Pipettes behavior for multi-channel, we will always navigate to the first well within a row, or use the offset.
> Grid containers, support for multi-cannel pipettes

- opentrons_sdk/containers/placeable.py
- opentrons_sdk/robot/robot.py
- opentrons_sdk/util/trace.py
- tests/opentrons_sdk/performance/test_performance.py
- tests/opentrons_sdk/util/test_trace.py
In this PR:
* Added `utils.trace.traceable` decorator with optional `name` argument. On each call of the function decorated with it, it will notify listeners of `util.trace.EventBroker`
* Decorated `robot.move_to` with `@traceable`
* Added `traceable` to performance test
* `util/test_trace.py` shows the example of decorating functions registering listeners in `EventBroker`
> Stream robot updates in API

- opentrons_sdk/drivers/motor.py
- opentrons_sdk/drivers/virtual_smoothie.py
- opentrons_sdk/helpers/helpers.py
- opentrons_sdk/instruments/pipette.py
- opentrons_sdk/robot/robot.py
- tests/opentrons_sdk/drivers/test_motor.py
- tests/opentrons_sdk/drivers/test_virtual_smoothie.py
- tests/opentrons_sdk/helpers/test_helpers.py
- tests/opentrons_sdk/labware/test_magbead.py
- tests/opentrons_sdk/labware/test_pipette.py
- tests/opentrons_sdk/performance/test_performance.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR:
1. Fixes a bug in `helpers.break_down_travel `
2. Add more configuration options to the VirtualSmoothie, including disabling limit switches
3. Adds the `now=False` default argument to all `go_to` and `move_to` methods, so that when they're included within a queued Command, you must call `move_to(location, now=True)` so those movements aren't also queued
```python
p200.move_to(plate[0])                # will be queued
p200.move_to(plate[0], now=True)      # will NOT be queued
```
> 20161018 142300 fix break down movement

- docs/setting_up_environment.md
Using git:// doesn't seem to work; https works fine.
> Use HTTPS to clone opentrons_sdk from pip

- opentrons_sdk/containers/placeable.py
- tests/opentrons_sdk/containers/test_placeable.py
In this PR:
In order to make aspirate and dispense relative to top/bottom look nicer we've added `top()` and `bottom()` to placeable that returns (Placeable, Vector) which will make aspirate/dispense look like: `p200.dispense(100, well.top(5))` which would mean dispense 5mm above the top of a well.
> adds top() and bottom() to placeable

- opentrons_sdk/instruments/pipette.py
- opentrons_sdk/robot/robot.py
- opentrons_sdk/util/log.py
- tests/opentrons_sdk/labware/test_pipette.py
- tests/opentrons_sdk/protocol/test_robot.py
This PR:
1. has the Pipette adding warnings to the Robot during a protocol run
2. the Robot also adds warnings during protocol run
3. slightly modifies transfer, consolidate, and distribute so the arguments are similar to other methods
4. instantiates plunger positions to `None`, and allows simulating a protocol without calibrating the pipette plungers
> 158 s add pipette warnings to robot warnings

- opentrons/drivers/motor.py
- opentrons/robot/robot.py
- tests/opentrons/drivers/test_motor.py
- tests/opentrons/protocol/test_robot.py
This PR:
1. Add driver method for checking smoothieboard version compatibility (for firmware, config file, and `ot_version`), which is checked automatically on `.connect()`
2. `axis_homed` flag moved from driver to Robot
3. version compatibility returned along with version number in `Robot.versions()`
> 179 s report firmware version mismatch on connect

- opentrons/drivers/motor.py
- tests/opentrons/drivers/test_motor.py
- tests/opentrons/labware/test_magbead.py
- tests/opentrons/labware/test_pipette.py
- tests/opentrons/performance/test_performance.py
This is a small PR, allowing `driver.connect()` to raise a `RuntimeError` if the connected robot's versions are incompatible with the current version of the API
> RuntimeError raised if versions incompatible

- opentrons/instruments/instrument.py
- tests/opentrons/labware/test_crud_calibrations.py
This PR adds a `Instrument.delete_calibration_data()` method, which is most helpful while testing, or on the off chance a user wants to re-calibrate everything
> added Instrument.delete_calibration_data() method for testing

- opentrons/drivers/motor.py
- opentrons/robot/robot.py
- tests/opentrons/drivers/test_motor.py
This PR updates the robot dimensions for each version to closely reflect physical dimensions. This allows:
1. movements made before any calibration has been saved to be more accurate (like move to slot)
2. `limit_switches: True` simulations to more accurately report a limit switch hit
> More accurate robot dimensions

- opentrons/containers/placeable.py
- opentrons/drivers/motor.py
- tests/opentrons/drivers/test_motor.py
- tests/opentrons/labware/test_crud_calibrations.py
Small PR, where `Placeable.max_dimensions()` returns `Vector(0, 0, 0)` if it has no children
> Move to slot using max dimensions

- docs/source/index.rst
- opentrons/instruments/instrument.py
- opentrons/instruments/magbead.py
- opentrons/instruments/pipette.py
- opentrons/robot/command.py
- opentrons/robot/robot.py
- tests/opentrons/json_importer/test_json_importer.py
- tests/opentrons/labware/test_pipette.py
- tests/opentrons/protocol/test_command.py
This PR
1. Adds a `Command.setup()` method, to be run before every `Command.do()` to update the caller's state (for example, `Pipette.current_volume`)
> commands-have-setup-and-do-methods

- setup.py
This PR fixes a bug - we left in legacy containers as data in the pip module, instead of switching it over to default_containers.
> change from legacy to default containers

- opentrons/containers/persisted_containers.py
- opentrons/util/environment.py
- opentrons/util/log.py
- setup.py
- tests/opentrons/containers/data/.containers-4.json
- tests/opentrons/containers/data/.secret/containers-3.json
- tests/opentrons/containers/data/containers-1.json
- tests/opentrons/containers/data/containers-2.json
- tests/opentrons/containers/test_persisted_containers.py
- tests/opentrons/util/test_environment.py
- tests/opentrons/util/test_singleton.py
- tests/opentrons/util/test_trace.py
This PR:
* Adds `opentrons.environment` and `get_path()` to track app specific dirs and files, creating respective dirs if necessary
* Changes `persisted_containers` to load default containers and look for custom containers in CONTAINER_DIR ($APP_DATA_DIR/containers) skipping dirs and files that start with `.`
* Adds tests and container files to test custom container functionality
> Use $APP_DATA_DIR/containers to look for custom containers

- .travis.yml
- docs/hello_world.md
- docs/source/api.rst
- docs/source/index.rst
- docs/source/tips_and_tricks.rst
- opentrons/drivers/motor.py
- opentrons/instruments/pipette.py
- opentrons/json_importer/json_importer.py
- opentrons/robot/robot.py
- tests/opentrons/containers/test_grid.py
- tests/opentrons/integration/move_robot.py
- tests/opentrons/labware/test_pipette.py
- tests/opentrons/performance/test_performance.py
This PR:
1. Adds `max_volume` as an initialization value to `Pipette`
2. Removes all mentions of `Pipette.set_max_volume()` from examples, because that method shouldn't be in user protocols, as it's now used primarily as UI route
3. Raises readable exceptions if plunger positions haven't been calibrated yet
> Init pipette with max volume

- opentrons/drivers/motor.py
This PR expands the list of tokens to use for filtering serial devices. This will fix the issue of not seeing `/dev/ttyACM0` on Ubuntu
> Fix serial port listing

- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_pipette.py
This PR adds `Pipette._drop_tip_offset`, which is used as a default Z offset when doing a `drop_tip()`. This is needed to give room for the drop-tip mechanism on pipettes.
> Drop tip uses offset from bottom

- opentrons/containers/__init__.py
- opentrons/robot/robot.py
- tests/opentrons/protocol/test_robot.py
Small PR, making `robot.add_container()` and `containers.load()` have same arg order
> swapped add_container args to match containers.load

- README.rst
- docs/hello_world.md
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/tips_and_tricks.rst
- docs/source/well_access.rst
- opentrons/__init__.py
- opentrons/containers/__init__.py
- opentrons/instruments/instrument.py
- opentrons/json_importer/json_importer.py
- opentrons/robot/robot.py
- tests/opentrons/containers/test_grid.py
- tests/opentrons/drivers/test_motor.py
- tests/opentrons/helpers/test_calibration.py
- tests/opentrons/integration/move_robot.py
- tests/opentrons/integration/test_protocol.py
- tests/opentrons/json_importer/test_import_all_protocols.py
- tests/opentrons/json_importer/test_json_importer.py
- tests/opentrons/labware/test_crud_calibrations.py
- tests/opentrons/labware/test_magbead.py
- tests/opentrons/labware/test_pipette.py
- tests/opentrons/performance/test_performance.py
Instead of
```python
from opentrons.robot import Robot
robot = Robot()
robot.run()
```
you can write
```python
from opentrons import robot
robot.run()
```
Thanks @andySigler @SimplyAhmazing
> Shorten imports

- opentrons/drivers/motor.py
- opentrons/instruments/pipette.py
This PR:
1. Changes `Pipette.dispense()` to default to the bottom of the destination well per user feedback
2. `CNCDriver.wait()` splits delays times by second, so calls to it do not block stop and pause signals
3. Cleans up `CNCDriver` a bit, removing unused code blocks and comments
> Split delay and dispense to bottom

- opentrons/robot/robot.py
- tests/opentrons/protocol/test_robot.py
Small PR, adding `robot.comment()` for adding queued descriptions
Example:
```python
robot.comment("starting protocol")
p200.pick_up_tip().aspirate(plate[0]).dispense(plate[1]).return_tip()
robot.comment("finished protocol")
```
> adds robot.comment for printing custom messages during protocol run

- docs/source/running_app.rst
this updates the docs based on the debugging experience I had with dagney, where we realized that we need sudo privileges to enable port access on linux. this means non admin users have to enable port access on an admin account and thus must modify the command slightly.
> add explanatory note about USER and sudo

- docs/source/well_access.rst
Small PR, fixing comment which specifies what well is being referenced when using `.rows` and `.cols`
> fixes comment in docs for accessing wells using .rows and .cols

- opentrons/containers/__init__.py
- opentrons/containers/persisted_containers.py
- tests/opentrons/containers/test_containers.py
Small PR. Adds a `containers.list()` method, which returns a list of all the loaded container names, in alphabetical order
> add containers.list() to see list of all loaded container files

- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_pipette.py
Small PR, adding optional height argument to `Pipette.touch_tip()`
```python
pipette.touch_tip(plate['A1'])  # normal touch_tip at plate A1
pipette.touch_tip(-3)           # will be 3mm below the top of the previous well
```
> adds optional height argument to touch_tip()

- opentrons/containers/placeable.py
- opentrons/instruments/pipette.py
- tests/opentrons/json_importer/protocol_data/lewistanner_auto_pcr.json
- tests/opentrons/labware/test_pipette.py
This PR adds some requested features to tip tracking:
1. When iterating through tips, the `Pipette` will raise a `RuntimeWarning` if it has run out of tips
2. User can set which tip to start at using `Pipette.start_at_tip(tip)`, where tip is a `Well` inside a tip rack `Container` that's been already attached to the `Pipette` during initialization
3. Adds a method `Pipette.current_tip()` to set and get the current tip on the pipette
```python
pipette = instruments.Pipette(axis='b', tip_racks=[tiprack1, tiprack2])
pipette.start_at_tip(tiprack2['C3'])
pipette.pick_up_tip()  # now has tip tiprack2['C3']
pipette.drop_tip()
while True:
pipette.pick_up_tip()
pipette.drop_tip()
```
> 407 tip tracking prediction

- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_pipette.py
Small PR, creates a pipette command `Pipette.air_gap()`, which takes two optional arguments: `volume` and `height`.
- `Pipette.air_gap()` will automatically move 20mm above the current well, and then aspirate air until the tip is full
- `Pipette.air_gap(10)` will automatically move 20mm above the current well, and then aspirate 10uL of air
- `Pipette.air_gap(10, 7)` will move 7mm above the current well, and then aspirate 10uL of air
> adds Pipette.air_gap(vol, height)

- .travis.yml
- appveyor.yml
- opentrons/__init__.py
- tests/opentrons/util/test_vector.py
Small PR, `opentrons` module raises `RuntimeError` if detected python version is not 3.5
> opentrons module raises exception if python version is not 3.5

- appveyor.yml
- setup.py
Updates the `setup.py` to require `requests>=2.12.4`, to handle the latests release from requests.
> Fix appveyor builds

- opentrons/drivers/motor.py
- tests/opentrons/drivers/test_motor.py
…serial
Small PR address a couple issues in smoothie driver:
1. `set_head_speed` no longer attempts to write to port, was unnecessary and required app to be connected when calling `robot.head_speed()`
2. Serial timeouts occurring during a call to `home()` will raise a RuntimeError explicitly saying the error was most likely caused by a homing switch being disconnected or misaligned
> Driver head speed no connection

- opentrons/containers/__init__.py
- tests/opentrons/containers/test_containers.py
```python
custom_plate = containers.create(
slot='A1',
grid=(8, 4),
spacing=(9, 9),
diameter=4,
depth=8,
name='my-fancy-plate'
)
for well in custom_plate:
print(well)
```
outputs the following
```
<Well A1>
<Well B1>
<Well C1>
<Well D1>
<Well E1>
<Well F1>
<Well G1>
<Well H1>
<Well A2>
<Well B2>
<Well C2>
<Well D2>
<Well E2>
<Well F2>
<Well G2>
<Well H2>
<Well A3>
<Well B3>
<Well C3>
<Well D3>
<Well E3>
<Well F3>
<Well G3>
<Well H3>
<Well A4>
<Well B4>
<Well C4>
<Well D4>
<Well E4>
<Well F4>
<Well G4>
<Well H4>
```
> containers.create() for making custom containers

- opentrons/containers/__init__.py
- opentrons/containers/placeable.py
- opentrons/util/environment.py
- tests/opentrons/containers/test_containers.py
When a custom `Container` is created using `containers.create()`, it is saved as a JSON container within the file specified by environment variable `CONTAINERS_FILE`.
If no `name =` is specified when using `containers.create()`, it will **not be saved** to the file.
> Persist containers create

- opentrons/containers/placeable.py
- tests/opentrons/containers/test_placeable.py
`plate.wells('A1', to='H1')` returns every well in the first rows (8 total)
`plate.wells('A1', to='H1', step=2)` returns every other well in the first rows (4 total)
`plate.wells('H1', to='A1')` returns every well in the first rows, starting at H1
`plate.wells('A1', length=8)` return a total of 8 wells, starting at well A1
`plate.wells('A1', length=8, step=2)` return a total of 8 wells, starting at well A1, and skipping every other well
`plate.wells('H1', length=8, step=-1)` return a total of 8 wells, starting at well H11, and moving backwards from there
> Adds to=, length=, and step= to Placeable.Wells()

- opentrons/instruments/magbead.py
- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_magbead.py
- tests/opentrons/labware/test_pipette.py
`pipette.delay(10)` will delay for 10 seconds
`pipette.delay(10, 2)` will delay for 2 minutes and 10 seconds
`pipette.delay(minutes=10)` will delay for 10  minutes
`pipette.delay(seconds=120)` will delay for 2 minutes (120 seconds)
`pipette.delay(seconds=10, minutes=2)` will delay for 2 minutes and 10 seconds
`pipette.delay(minutes=2, seconds=10)` will delay for 2 minutes and 10 seconds
> Delay takes minutes kwarg

- opentrons/containers/placeable.py
- tests/opentrons/containers/test_placeable.py
Makes `Placeable` class callable by adding `def __call__()`, which then passes all arguments to `Placeable.wells()` and return results. This allows for the following syntax:
```python
plate.rows('2', to='12')
plate.cols('B', length=3, step=2)
```
> Route placeable call args to wells

- opentrons/containers/placeable.py
- tests/opentrons/containers/test_placeable.py
Adds methods to `Placeable` for creating iterables, chain, and cycle iterables, built from the `Placeable`'s children list
```python
plate.wells('A1', 'B2', 'C3').iter()
plate.wells('A1', 'B2', 'C3').cycle()
plate.wells('A1', 'B2', 'C3').chain(trough.wells('A1', 'A2'))
```
previously would have been
```python
iter(plate.wells('A1', 'B2', 'C3'))
itertools.cycle(plate.wells('A1', 'B2', 'C3'))
itertools.chain(plate.wells('A1', 'B2', 'C3'), trough.wells('A1', 'A2'))
```
> Chain and cycle for wellseries

- .travis.yml
- opentrons/__init__.py
This PR:
* Changes the requirement from Python == 3.5 to Python >= 3.6
* Adds tests for Python 3.5 and 3.6 to travis
> Require python 3.5 or above

- opentrons/helpers/helpers.py
- opentrons/instruments/__init__.py
- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_pipette.py
Transfer source and destination lists can be of different lengths, and it will evenly spread the lesser list of wells across the greater list. If the lists aren't evenly divisible, pipette raises an exception.
```python
pipette.transfer(20, plate.wells('A1', 'B1'), plate.wells('C1', 'D1', 'E1', 'F1'))
```
Creates:
- 20uL from 'A1' to 'C1'
- 20uL from 'A1' to 'D1'
- 20uL from 'B1' to 'E1'
- 20uL from 'B1' to 'F1'
> Transfer locations divisible

- opentrons/instruments/pipette.py
- tests/opentrons/labware/test_pipette.py
Small PR adding a kew-word argument `radius=` to touch-tip commands
```python
pipette.touch_tip(radius=0.5)  # percentage of the well's radius to move within
pipette.touch_tip(radius=1.0)  # default is 1.0 (100%)
```
> add kwargs radius= to .touch_tip(); adds test

- opentrons/instruments/pipette.py
- tests/opentrons/json_importer/test_json_importer.py
- tests/opentrons/labware/test_pipette.py
Pipette will use that passed `trash_container`'s first well. So that it will be running `.drop_tip(trash[0])` instead of before it was doing `.drop_tip(trash)`. This is required when using a trash container that has dimensions (like container `"trash-box"`)
> defaults pipette's trash to specify trash[0] when dropping tip

- opentrons/containers/placeable.py
- opentrons/instruments/pipette.py
- opentrons/robot/robot.py
- tests/opentrons/labware/test_pipette.py
Makes the output of `robot.commands()` slightly more readable, no more `"<In Place>"` when it's actually going to a tiprack, etc.
> Pipette commands more readable

- app-src/src/components/Placeable.vue
Removes bug from UI where calibrating placeables with same name doesn't create checkmarks next to the correct container.
> uses container slot to help filter for current container

- api/opentrons/containers/placeable.py
- api/tests/opentrons/containers/test_placeable.py
Small PR, adds `radius=` and `degrees=` optional kwargs to `Placeable.bottom()` and `Placeable.top()`
> Well bottom() and top() with radius/degrees

- api/opentrons/drivers/__init__.py
- api/opentrons/drivers/smoothie_drivers/v2_0_0/driver.py
- api/opentrons/instruments/pipette.py
- api/tests/opentrons/drivers/smoothie_drivers/v2_0_0/test_motor.py
- api/tests/opentrons/labware/test_pipette.py
plus removes some unused methods that can wait for a later PR
> Small patch to smoothie driver after testing

- api/opentrons/drivers/smoothie_drivers/v1_2_0/driver.py
- api/opentrons/drivers/smoothie_drivers/v2_0_0/driver.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/drivers/smoothie_drivers/v1_2_0/test_motor.py
- api/tests/opentrons/drivers/smoothie_drivers/v2_0_0/test_motor.py
If no movement after 1 second, exception is raised. Also adds 10ms delay between coordinate polling, reducing burden on serial port.
Includes a patch for a bug in the old firmware (`v1.0.5`) where if limit switch is hit, robot will not move until it's coordinate system has been reset.
> Refactor wait_for_arrival() to include timeout

- api/opentrons/server/main.py
- app-shell/app/main/main.js
- app-shell/app/main/updater.js
- app-shell/app/main/util.js
Patches two bugs in App:
1. Flask server correctly parses WellSeries containing WellSeries, so as not to duplicate containers in calibration
2. App-shell calls `BrowserWindow.loadURL()` within a `setTimeout()` to hopefully avoid trouble with Chromium not actually sending that request to Flask
> App shell white screen debugging

- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
- api/opentrons/server/main.py
Small PR which adds some safegaurds to avoid ever hitting the Z limit switch. This occurs often when using tall containers and also not calibration to the actual bottom of that container.
- "Aspirate" button in UI will avoid Z switch when moving up
- `robot._create_arc()` will avoid Z switch hit for arc height and for arrival Z position
- `aspirate()` command will only move to `bottom(1)` if the `Well` has height greater than 1
> Avoid Z collisions with limit switch

- app-shell/app/main/main.js
Nodejs running on Windows 10 is not able to resolve `localhost` when not connected to network or in airplane mode.
This PR replaces all mentions of `localhost` inside app-shell with the explicit `127.0.0.1`, which after testing does in fact resolve when in airplane mode.
> replaces localhost with 127.0.0.1

- api/opentrons/instruments/pipette.py
A user discovered a new bug, where given a special combination of coordinates, the AB motors squeal again during `pipette._position_for_aspirate()` where the plunger is set to `bottom` position.
This patch sets the plunger to `bottom` position during `pipette.pick_up_tip()` to avoid this moment all together. However, the long-term solution will be to switch to a newer build of smoothieware EDGE that fixes this bug.
This issue has not been reported by any other user.
> set plunger to 'bottom' during pick-up-tip to avoid firmware bug

- api/opentrons/containers/placeable.py
- api/tests/opentrons/containers/test_placeable.py
Small PR adding `Placeable.wells(x=, y=)` based of feedback. X and Y kwargs are integers
Users were before using `Placeable.cols()[x][y]` to get around this method not existing. This does not read too well, and would also raise error on containers without multiple columns (like "trough-12row")
`Placeable.wells(x=1, y=2)` will return well `B3`
`Placeable.wells(x=1)` will return column `B`
`Placeable.wells(y=2)` will return row `3`
> Placeable.wells(x=, y=)

- app/Makefile
- app/package.json
This is a little PR to fix up CSS linting in `app`. This changes the Makefile linting tasks to look like:
* `make lint` - Lints JavaScript and CSS
* `make lint-js` and `make lint-js-fix` - Lints JS and fixes JS, respectively
* `make lint-css` and `make lint-css-fix` - Lints CSS and fixes CSS, respectively
Also, editor plugins! https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#editor-plugins
> (Chore) Update stylelint and move tasks to Makefile

- app/ui/containers/Root.js
- app/ui/index.js
- app/ui/interface/README.md
- app/ui/interface/index.js
- app/ui/interface/test/actions.test.js
- app/ui/interface/test/reducer.test.js
- app/ui/interface/test/selectors.test.js
- app/ui/robot/README.md
- app/ui/robot/index.js
- app/ui/robot/test/selectors.test.js
- app/ui/util.js
This PR adds an interface state module for tracking purely UI based state. The only piece of state in there right now is the nav panel expanded state, but will probably incorporate other dropdowns, modals, etc.
> Add interface state module and add hooks for nav panel

- .travis.yml
- Makefile
- README.md
- api/.coveragerc
- api/Makefile
- app/Makefile
- app/package.json
Hey guys, another CI-focused chore PR here. This one lets us start collecting coverage information from both the API and the app (also, badges!).
I've switch our coverage provider from Coveralls to Codecov. I've used both in the past, with all my newer projects using Codecov. They're not that different, it's just the Codecov makes multi-language projects super easy, and Coveralls makes it less easy than that. Check out the report for this PR: https://codecov.io/gh/OpenTrons/opentrons/branch/v3-chore-coverage
I've also started a top-level Makefile to start coordinating stuff that until now has only lived in travis.yml. Basically, it has some tasks to call sub-tasks in the Makefiles of `app` and `api`. Right now it's got:
* `make install` - Install all pip and npm dependencies
* `make test` …
> (Chore) App 3.0 - Collect both app and API coverage

- api/opentrons/server/main.py
- api/opentrons/server/robot_container.py
- api/opentrons/server/rpc.py
- api/opentrons/server/tests/conftest.py
- api/opentrons/server/tests/test_integration.py
This PR:
* Fixes sequencing errors and dropped frames.
* Cleans up IP address parse errors in main.py.
* Makes main.py handle `SIGINT` (`^C`) gracefully again.
When making calls that produce notifications, the following could happen:
* A client could receive `CALL_RESULT_MESSAGE` *before* receiving all notifications produced during the call;
* Notifications are arriving too fast can result in server dropping frames, making responses invalid.
In order to fix this the following changes have been made:
* Added a send queue to separate producer and consumer
* In `rpc.py` adding call result to the queue from `exec_loop` after function call returns
* In `rpc.py` call `await client.drain()` to wait for socket buffer to be transmitted, before sending more data …
> Adding proper sequencing and back-pressure + cleanup

- app/rpc/client.js
- app/rpc/test/client.test.js
- app/rpc/websocket-client.js
- app/ui/components/NavPanel.js
- app/ui/containers/Nav.js
- app/ui/containers/Root.js
- app/ui/robot/actions.js
- app/ui/robot/api-client/client.js
- app/ui/robot/reducer.js
- app/ui/robot/test/actions.test.js
- app/ui/robot/test/api-client.test.js
- app/ui/robot/test/reducer.test.js
- Adds disconnect state and actions to store
- Wires up those actions to the UI
- Promisifies existing close method of RcpClient (resolve if actual WebSocket state changes to closed)
- Standard review for correctness
- Make sure it works as expected on your machine
- API doesn't handle reconnects super well at the moment
- Some bugginess with the API is therefor expected
Check List:
- Nothing public
- @OpenTrons/js
> (v3) Feature - disconnect client

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
So, I fell down a pull-request/issue template rabbit hole the other day (mostly thanks to [this repository](https://github.com/stevemao/github-issue-templates)), and I thought there was some opportunity to improve ours! The following PR description is written using this new PR template.
- (Chore) Flesh out PR template to ensure change type and review needs info is present
- (Chore) Add an issue template to help capture relevant info
This PR is basically a proposal, so @OpenTrons/py and @OpenTrons/js please sound off if you think anything is missing, if you think this whole effort is unnecessary, if you have a brilliant idea, etc.
> (Chore) - Flesh out PR template and add issue template

- api/opentrons/server/serialize.py
- api/opentrons/session/session.py
- api/tests/opentrons/server/test_server.py
A small PR to:
* skip object attributes starting with `_` during serialization to reduce chatter and not pull private and internal attributes.
* add `_` to private attributes of `Session` and `SessionManager` to make the API cleaner.
Check List:
> Serialization: filter private attributes of objects serialized

- api/Makefile
- app/ui/robot/api-client/client.js
- app/ui/robot/test/api-client.test.js
#352 changed the shape of the RPC remote object. This PR fixes the client breakage due to that change. While I was here, I also fixed the API `make install` task, because it wasn't quite right.
- (Chore) Update API `make install` to use `pip install -e .`
- (Fix) Update API client to expect `opentrons.api.MainRouter` as the remote object
- (Tests) Update API client tests to for the above fix
I would love to merge this ASAP, so please review in the next 30 minutes. If you're on your phone, this PR is small enough that you should be able to review it from the mobile site without issue.
> (v3 alpha, fix) Update client remote to use MainRouter

- app/ui/components/NavPanel.css
- app/ui/components/NavPanel.js
- app/ui/components/PipetteConfig.css
- app/ui/components/PipetteConfig.js
- app/ui/components/SetupPanel.css
- app/ui/components/SetupPanel.js
- app/ui/components/SideBar.css
- app/ui/components/TipProbe.js
- app/ui/containers/ConnectedSetupPanel.js
This PR implements a ConnectedSetupPanel container and SetupPanel for the calibration nav sidebar.
- (Feature) Calibration Nav Panel
**Note**: If your PR incorporates many changes, or many different types of changes, please consider splitting it up into smaller PRs.
@mcous this PR may just be for QC before moving on. As always, if theres a cleaner way to implement I'm all for suggestions.
> V3a calibration nav panel

- app/rpc/remote-object.js
- app/rpc/test/remote-object.test.js
- app/ui/robot/actions.js
- app/ui/robot/api-client/client.js
- app/ui/robot/reducer.js
- app/ui/robot/test/__mocks__/calibration-manager.js
- app/ui/robot/test/__mocks__/session.js
- app/ui/robot/test/actions.test.js
- app/ui/robot/test/api-client.test.js
- app/ui/robot/test/reducer.test.js
- app/ui/robot/test/selectors.test.js
This PR adds calibration API state tracking to the client and starts work on the selectors that will need to be wired into components and containers. **Targets `app-3-0-alpha`**
- (Feature, Tests) Add instrument and labware state translation to API client
- (Feature, Tests) Add private ID field to RemoteObjects
- (Feature, Tests) Add actions for CalibrationManager calls and responses
- (Feature, Tests) Wire calibration actions and responses to API client
- (Feature, Tests) Track calibration API request state in redux store
@OpenTrons/js please review for correctness
> (v3 alpha, feature) Calibration API client state

- api/tests/opentrons/trackers/test_pose.py
- api/tests/opentrons/trackers/test_pose_tracker.py
- api/tests/opentrons/trackers/test_pose_tracker_integration_tests.py
This is a *small* PR that adds tests around the `Pose` class and `PoseTracker` to verify operation of and avoid regression in `PoseTracker`. It is particularly focused on verification of translations.
- (Tests) Adds tests around `Pose` and `PoseTracker`. Also renamed the old `test_pose_tracker.py` test file to `test_pose_tracker_integration_tests.py` utilizes things like `containers` (or labware), `Pipette`, and `Robot`. 
**Note**: Aside from a rename I did not touch `test_pose_tracker_integration_tests.py`. Therefore, the tests in there are still …
> V3a add pose tracker tests

- app/webpack/rules.js
I broke hot module reloading with CSS back in #338 because I set the [Extract Text Plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) to be always active, even in dev. A closer reading of the plugin's README revealed that it doesn't actually work with HMR... my bad. This PR fixes HMR with CSS by turning off that plugin in dev mode.
- (Chore) Stopped using the Extract Text webpack plugin when NODE_ENV isn't `production`
> (v3) 🚀 Fix CSS HMR in dev

- .travis.yml
travis is case sensitive, so it's not deploying
> Opentrons not OpenTrons repo org name

- api/opentrons/drivers/smoothie_drivers/v3_0_0/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/v3_0_0/serial_communication.py
- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/drivers/test_driver.py
Keep plunger motor current low when not in use, and ramp to high when in use. Dwell after setting power.
When sending commands, driver detects whether the command is a MOVE or HOME action (aspirate/dispense are move actions) on B or C axes (the plunger motors), and if so ramps current to high (500 mA) before sending the command, and then back to low (100 mA) afterward. Also, per @andySigler, after issuing any SET_POWER command, a DWELL command is issued before returning.
> Plunger current high only during move/home

- app/ui/components/App.global.css
- app/ui/components/SetupPanel.css
- app/ui/components/SetupPanel.js
- app/ui/components/TipProbe.css
- app/ui/components/TipProbe.js
- app/ui/containers/ConnectedTipProbe.js
- app/ui/robot/actions.js
- app/ui/robot/reducer/calibration.js
- app/ui/robot/selectors.js
- app/ui/robot/test/actions.test.js
- app/ui/robot/test/calibration-reducer.test.js
- app/ui/robot/test/selectors.test.js
This PR brings the tip probe sequence and views in the app into alignment with the UI/UX screens (which I'm going to call a bug). Mostly, it involves:
* Making sure the correct copy is in place
* Allowing the user to bail out of a tip probe
* Ensuring the view updates properly as the user switches between pipettes
* Minor styling cleanup
- (Fix) Ensure tip probe state is cleared one one instrument if the other instrument is moved
- (Fix) Add missing copy for tip probe instructions
- (Fix) Separate out "has this instrument been probed?" and "what is this instrument doing right now for probing?" in the state
- (Feature) Allow the user to bail out of a tip probe in progress
- (Tests) Update tests for probe state split and tip probe bailout
General app review rules apply
> (v3, bugfix) Align tip probe sequence with screens

- app/ui/containers/ConnectedDeckConfig.js
- app/ui/containers/ConnectedJogModal.js
- app/ui/containers/ConnectedSetupPanel.js
- app/ui/robot/selectors.js
- app/ui/robot/test/selectors.test.js
The pipette used for move to container and jog had been hard-coded. If a given protocol didn't have the pipette that had been hard-coded, things would break pretty drastically. This is a quick and dirty PR to use whichever single-channel pipette is attached for these operations. This PR operates under the assumption that a single-channel pipette will be available.
- (Fix) Use attached single-channel for labware calibration movements instead of hard-coding it
Some of our React/redux containers need some love, because things are getting a little unwieldy. Feel free to point out any confusion, but I would appreciate it if we could punt on it for a future PR in for the sake of getting this bugfix in quickly.
> (v3, bugfix) Use first available 1-channel instrument for move to and jog

- app/ui/components/App.global.css
- app/ui/components/DeckConfig.js
- app/ui/components/JogModal.css
- app/ui/components/JogModal.js
- app/ui/components/SetupPanel.css
- app/ui/components/SetupPanel.js
This PR implements the following updates to better align with designed UI.
- Label jog axes
- Move jog instructions to top
- Jog button hover styles
- Move to next labware button now blue
- Disable run link when not calibrated
- (Chore) Match jog modal to design, css updated
- (Fix) Disable run link until all labware is calibrated
**Note**: If your PR incorporates many changes, or many different types of changes, please consider splitting it up into smaller PRs.
This is generally CSS/organizational chore work. @mcous please double check my disable …
> V3a jog screen alignment

- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- fixes #380
- adds test simulating the behavior
- moves protocol load out of try-finally block
- tear down async test fixture gracefully
- fix existing test in light of new behavior
> Don't emit Session notification even if creation fails

- app/ui/robot/selectors.js
- app/ui/robot/test/selectors.test.js
Our previous run progress implementation was super naive and worked by counting command parents completed. Obviously this gave us super coarse results and wasn't awesome, so this PR switches to a leaves based calculation.
- (Fix) Calculate run progress based on command list leaves
Tiny straightforward PR. Will likely merge as soon as I get any approval unless I hear otherwise
> (v3) Calculate run progress by counting leaves in the command list

- app/ui/components/SetupPanel.js
- app/ui/robot/reducer/calibration.js
- app/ui/robot/selectors.js
- app/ui/robot/test/calibration-reducer.test.js
- app/ui/robot/test/selectors.test.js
During labware confirmation, we had been combining the questions of "has this labware been confirmed?" and "what is the status of the confirmation process on this container?". This PR is a quick and dirty separation of those concerns to aid user testing, in the same vein as what #399 did for intrument probing state.
The end result is that re-doing confirmation on a given container doesn't wipe out the fact that confirmation has occurred at least once (this is important because confirmation of non-tiprack labware is gated by confirmation of tiprack labware).
- (Fix) Split instantaneous labware confirmation status from whether or not the labware has been confirmed at all
As you should note from my `TODO`s, I believe this (and the instrument work in #399) is a sub-optimal …
> (v3) Track labware confirmation separately from instantaneous status

- app/package.json
- app/scripts/advertise-local-api.js
- app/ui/components/ConnectPanel.css
- app/ui/components/RobotItem.js
- app/ui/containers/DiscoveredRobot.js
- app/ui/robot/actions.js
- app/ui/robot/api-client/client.js
- app/ui/robot/api-client/discovery.js
- app/ui/robot/reducer/connection.js
- app/ui/robot/selectors.js
- app/ui/robot/test/actions.test.js
- app/ui/robot/test/api-client-discovery.test.js
- app/ui/robot/test/api-client.test.js
- app/ui/robot/test/connection-reducer.test.js
- app/ui/robot/test/selectors.test.js
This PR adds the entire MDNS service (including both host and name) to the application state rather than just the host. It also adjusts some button copy per UI/UX request.
- (Fix) Adjust connect button copy to say "Connect" and "Disconnect"
- (Feature) Grab whole MDNS service for the state instead of cherrypicking host
Standard review. If you're wondering why I changed every `hostname` to `host`, it's because the MDNS library we're using uses `host`, so I figured alignment there would just make everything a little more straightforward. Plus, it's fewer characters without losing meaning
> (v3) Robot connection tweaks

- app/ui/components/InfoBox.css
- app/ui/components/InfoBox.js
- app/ui/components/SetupPanel.css
- app/ui/components/SetupPanel.js
- app/ui/components/TipProbe.css
- app/ui/components/TipProbe.js
- app/ui/containers/ConnectedSetupPanel.js
Per request from UI/UX, this PR wires the "Run Protocol" button in the calibration setup panel to actually start the protocol run (as opposed to simply navigating the user to the run page where they can subsequently click "Run Job".
I'm not a huge fan of this change, but given that it's for testing I think it's valuable. Also, you may notice that SetupPanel.js is a huge mess. @Kadee80 and I are aware and will be tackling some cleanup work tomorrow.
This PR also adds a little "Hurray, you're ready to run!" message that was in the screens but missing from the app.
- (Feature) Wire "Run Protocol" button in SetupPanel to actually run the protocol
- (Feature) Add ready to run message to the SetupPanel after calibration is complete
Standard review, keeping in mind that we're …
> (v3) Wire run button in setup panel to run protocol

- api/opentrons/commands/commands.py
- api/tests/opentrons/commands/test_description.py
- api/tests/opentrons/labware/test_pipette.py
- Adds `stringify_location` to `commands/commands.py` to turn location
into a string containing an abbreviated list of wells (i.e. 'A1..H12')
and a position on a deck it is located at. Exact wording and mentioning
of labware type is subject to user testing.
- Adds trivial tests and updates existing tests where string representation
of a location is being used.
__NOTE:__ Calls like `container.rows(0, 1, 2)` would produce `WellSeries` of `WellSeries`
this is handled in a suboptimal way (if using lists of lists this could be folding).
This should be re-visited once we phase out `WellSeries`.
Please think of any common cases not addressed by this representation.
Here's an excerpt from Bradford Assay with the change in place:
> Shorten well representation in commands list

- app/ui/components/App.global.css
- app/ui/components/App.js
- app/ui/components/DeckConfig.js
- app/ui/components/Diagram.css
- app/ui/components/Diagram.js
- app/ui/components/NavPanel.css
- app/ui/components/NavPanel.js
- app/ui/components/Page.css
- app/ui/components/SetupPanel.js
- app/ui/components/SideBar.css
- app/ui/components/SideBar.js
- app/ui/components/ToolTip.css
- app/ui/components/ToolTip.js
- app/ui/components/nav/NavBar.js
- app/ui/components/nav/NavButton.js
- app/ui/components/nav/SideBarButton.js
- app/ui/components/nav/nav.css
- app/ui/containers/DiscoveredRobot.js
- app/ui/containers/Nav.js
- app/ui/containers/UploadStatus.js
- app/ui/interface/index.js
- app/ui/interface/test/actions.test.js
- app/ui/interface/test/reducer.test.js
- app/ui/interface/test/selectors.test.js
This PR cleans up the nav sidebar a little to have:
- More specifically scoped React containers
- A more specific file organization
- CSS consolidation and consistence w.r.t. scoped modules and global styles
- (Refactor) Refactored nav sidebar with more container use
- (Refactor) Refactored tooltips to use scoped CSS
- (Tests) Removed an unneeded interface action so updated tests accordingly
Standard review. Please try it out on your machine to make sure everything still works. If you haven't run the app since #414 please remember to run `make install` before running to pick up new dev deps.
> (v3) Cleanup nav sidebar

- api/Makefile
Creates targets in the api Makefile that should make developing with devices easier
1) The development process that these targets are defined around is as follows:
- `$ make active_devices` to find devices that are currently online  
- `export OT_DEVICE_ID=[uuid]` to select the device you want to use (uuid is found in the output from the above commands)
- `make sync_device` to sync your local `api/` to the devices `api/` and restart the application
- `make ssh_device` to enter the running container of the pi to debug or poke around
- `make info_device` to get basic info about the device
**Issues / improvements**
This is a work in progress but should serve as a …
> V3a resin devflow

- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
- app/scripts/advertise-local-api.js
- Removed adding error to log on `_simulate`, allowing
exception to propagate instead
- Fixed test to fail if ANY state change is emitted
- Updated app to advertise local API instance as `http`
> Fix #387 — don't emit state change if SessionManager.create errors out

- app/rpc/client.js
- app/rpc/remote-error.js
- app/ui/components/App.global.css
- app/ui/components/CenteredContent.css
- app/ui/components/CenteredContent.js
- app/ui/components/Upload.css
- app/ui/components/Upload.js
- app/ui/robot/api-client/worker.js
This PR tweaks the errors returned by the RPC client to be more useful, and displays any errors from `session_manager.create` on the upload page.
- (Feature) Added session upload error display to Upload page
- (Chore) Took the opportunity to remove some global CSS per discussions with @Kadee80 
Standard review. Related to #428
> (v3, feature) Display upload error on Upload page

- api/opentrons/api/calibration.py
- api/opentrons/api/models.py
- api/opentrons/robot/robot.py
- api/opentrons/server/main.py
- api/tests/opentrons/api/test_calibration.py
Expose server functions (home and pick_up_tip) for new calibration process, and add debug logging to all routes
- (Chore) Add debug logging to server routes
- (Feature) Add pick_up_tip and home routes to server
- (Docs) Add docstring to calibration manager to point to use site in App
- (Tests) Add contract tests for new server routes
> Added home and pick_up_tip routes to server for new calibration process

- .travis.yml
- app/Makefile
- app/electron-builder.json
- appveyor.yml
Since we don't have any native platform dependencies, we can successfully build both OSX and Linux targets in Travis Linux container.
For releases, we should build and sign on a real OSX machine.
Note the directory change. We are gonna be putting both builds into `osx-linux`. Eventually, I suggest to put all three into something like 'ci-builds'
> Add mac target to travis CI

- api/opentrons/api/calibration.py
- api/opentrons/drivers/smoothie_drivers/v3_0_0/driver_3_0.py
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/mover.py
- api/opentrons/robot/robot.py
- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/robot/test_mover.py
Add a parameter to allow for low power movement in vertical axes, to enable requested workflow changes that prevent damaging pipette during tiprack calibration
- Add parameter to all levels of move commands to enable low power operation of vertical axes
- Fix test mocks to work with new signatures
- Update documentation with new parameters
- Add tests to ensure that low power mode is honored
- Place relevant power configuration parameters into robot_config
- Track last known power settings in driver so they can be restored after commands that request low power
- Remove unused parameter in `_create_arc`
> Add low power setting parameters for movement in Z and A axes

- api/opentrons/cli/main.py
- api/opentrons/config/__init__.py
- api/opentrons/config/config.py
- api/opentrons/drivers/smoothie_drivers/v3_0_0/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/v3_0_0/serial_communication.py
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/util/calibration_functions.py
- api/opentrons/util/environment.py
- api/tests/opentrons/config/test_config.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/drivers/smoothie_drivers/v3_0_0/test_driver_position_cache.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/robot/test_mover.py
- api/tests/opentrons/robot/test_robots_config.py
This PR adds functionality to override default config settings with values stored locally in JSON file located in `APP_DATA_DIR/config.json`. It also adds functionality to save config values that are different from defaults into a local JSON. Default settings are assumed to be minimum sufficient settings to initiate factory calibration safely.
In addition to that I am also:
* further consolidating configurable values making them a part of config and passing instance around instead of accessing values by importing the robot.
* making tip length part of config with the intent that it will be overridden and saved after a tip probe. This might change in the future for scenarios when the same pipette is interacting with multiple tip types during in the same protocol.
@btmorr , i removed line …
> Config management with persistence

- Dockerfile.template
- api/opentrons/drivers/smoothie_drivers/v3_0_0/serial_communication.py
- compute/README.md
1) Functionality that makes the running container connect to the smoothie over serial on the Pi
2) Resin README.md
- (Chore) Adds an envvar to the serial communication file for the smoothie_id and sets the variable in the Dockerfile
- (Docs) Adds README.md in compute to explain how to flash and push to compute devices. 
@astaff @mcous  @btmorr
> Implement Pi connection over serial

- api/opentrons/drivers/smoothie_drivers/v3_0_0/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/v3_0_0/serial_communication.py
Move env var check into driver at callsite, so the env var doesn't get overridden by a constant (functional change is only on the robot, hence no changes in docs or tests.
- (Fix) Move environment variable check from default parameter check to the call-site, so that it does not get overridden with a constant in driver
Check that it runs on the robot as expected
> Fix smoothie id override

- app/electron-builder.json
- app/package.json
- protocol-designer/package.json
Fix build for linux!
installing with `sudo dpkg -i opentrons-v3.0.0-etc-etc.deb` gave error: 'invalid package name (must start with an alphanumeric character)'
Package name was @opentrons/desktop-app, '@' symbol is not allowed by debian package manager.
In this PR:    
* removed '@opentrons/' prefixes in package.json name field
* also removed ""useAppIdAsId": true" for windows build
> fix build for linux

- compute/README.md
Just adds a line to the readme that documents a gotcha which was getting in Mike's way.
Just want the review so everyone sees this issue and it doesn't get in anybody's way in the future.
> Add Resin envvar info to compute readme

- api/opentrons/cli/main.py
A fix enable running using `python -m opentrons.cli.main`
> fix non-absolute import in CLI tool

- api/requirements.txt
Pin pytest version to 3.2.5 to prevent breaks on auto-update
> pin pytest version to 3.2.5

- api/opentrons/instruments/pipette.py
- api/requirements.txt
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/containers/test_default_containers.py
- api/tests/opentrons/integration/test_server.py
- api/tests/opentrons/labware/test_pipette.py
`Pipette` calculates the distance (mm) to move the plunger based on a ul_per_mm value found through volumes tests (`18.51` ul/mm on p300).
Pipette is hardcoded to be a p300 pipette because of this value, which seems ok given all beta testing will be done with p300.
This means that the kwarg `max_volume=` on `Pipette` is now being ignored. This is a breaking change in API, however this kwarg doesn't make sense with electronic pipettes.
Check List:
> Plunger movements based on uL/mm conversion

- README.md
The org. rename to Opentrons (from OpenTrons) and base branch switch to `v3a` threw off our CI and coverage badges in the main README.
- (Chore) Updated CI and coverage badges to Opentrons/opentrons and `v3a`
Note: The README in `api` is still in `.rst` and using badges from a while ago. I elected not to touch it because that documentation in general seems like a different discussion.
> (repo) Fix README CI and coverage badges for new base

- app/ui/components/NavPanel.css
- app/ui/components/NavPanel.js
- app/ui/components/SideBar.js
- app/ui/containers/Nav.js
This PR implements a text warning on the upload panel once an initial session has been created. Text states:
```
WARNING:
Opening a new protocol will close the one you currently have open. This will clear out current calibration data.
```
This is a temporary workaround that can be addressed further in the sidepanel refactor with designs and possible modal.
Check List:
> show re-upload warning on session creation

- api/requirements.txt
Unpinned dependencies continuing to cause failures. Pinning all Python dependencies
- (Bugfix) Pin all dependencies to the version they were yesterday
> Pin all dependencies in requirements.txt

- app/rpc/test/client.test.js
We've been seeing intermittent RPC client failures in the notification test. When looking at the code, there was a race condition where the test notification could be sent before the client had actually resolved and had its notification listener attached. This PR removes that race condition to hopefully remove the test flakiness.
- (Tests) Delay RPC test notification until after the client has definitely resolved
Tiny PR, so a quick 👍 would be appreciated
> (app) Fix flaky RPC client notification test

- app/package.json
- app/scripts/advertise-local-api.js
- app/ui/robot/api-client/discovery.js
- app/ui/robot/test/api-client-discovery.test.js
This PR updated the discovery machinery of the app to also poll for directly connected robots via repeated GET requests to `http://${FIXED_LINK_LOCAL_IPv6}:31950/health`.
Blocked by #480 
- (Feature) Updated discovery.js to poll /health at fixed local IP every sec
- (Chore) Updated MDNS dev script to only advertise if local API is found
Nothing specific, but a Windows test would be helpful!
> (app) Update discovery to poll directly connected robots

- api/opentrons/cli/main.py
- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/cli/test_cli.py
This PR for avoiding collisions caused by using any previously calibrated `tip_length`, `instrument_offset`, and `gantry_calibration`.
We erase the deck-calibration data file at the beginning of deck calibration procedure, using a method `robot_config.clear()` which erases the environments config.json file. We then call `opentrons.reset()` to re-initialize robot with an default config setting.
Check List:
> Erase "config.json" at beginning of deck calibration

- api/opentrons/util/calibration_functions.py
- api/tests/opentrons/util/test_tip_probe.py
[Tested on robot]
This PR addresses Z collisions that happen during tip-probe sequence, where either the tip collides with deck, or the pipette collides with tip-probe. A second parameter is used to ensure there is a clearance between the tip-probes top and the pipette's nozzle, in addition to the clearance between the deck on the attached tip.
The tip-probe test was commented out to avoid including it's refactoring within this PR. The test was overly brittle and reinforced development assumptions, while failing to help identify behavioral failures on the robot. A refactor of tip probe should break up that functionality into components that can be unit tested properly
- (Bugfix) Fix clearance logic to ensure both tip clearance above deck and nozzle clearance above probe box
- …
> Fix tip probe collision

- app/ui/robot/api-client/client.js
- app/ui/robot/test/api-client.test.js
Simple PR to get the app to automagically jump to the run screen if it connects to a running robot. Not in love with the implementation but it's kind of tied to how we deal with the robot API at the moment. Got a TODO in there to keep an eye on it.
- (Feature, Tests) Added push action on connect if session.state is running or paused
Tested on a robot, but would appreciate if you could do the same!
> (app) Go to /run on connect to running bot

- .travis.yml
- Makefile
- app/package-lock.json
- app/package.json
- app/ui/components/connect-panel/RobotItem.js
- app/ui/components/connect-panel/connect-panel.css
- appveyor.yml
- components/.babelrc
- components/.flowconfig
- components/.gitignore
- components/Makefile
- components/README.md
- components/package-lock.json
- components/package.json
- components/src/__tests__/__snapshots__/buttons.test.js.snap
- components/src/__tests__/buttons.test.js
- components/src/buttons.css
- components/src/buttons.js
- components/src/index.js
- protocol-designer/.babelrc
- protocol-designer/package-lock.json
- protocol-designer/package.json
Component Library!!!!11 Yeah this is gonna get weird.
* Added a single component: `PrimaryButton`
* Components library uses `flow` for types instead of PropTypes
* We're gonna be writing simple unit/snapshot tests for our components
* I've included simple ones for PrimaryButton as an example
* Upgraded to React v16 kind of by accident, but nothing broke so¯\_(ツ)_/¯
* This is a reasonable thing to protest so if this makes you uncomfortable let me know and I'll downgrade
Important housekeeping things to note:
* CI/CD is getting unwieldy with regards to multiple projects, how dependencies are installed, and how things are tested
* Manually adding a task to the individual CI configurations seems unscalable
* I think we should start using the top level Makefile as a neutral CI coordinator
* …
> (complib, app) Add components library (with PrimaryButton)

- app/ui/components/Upload.js
- app/ui/components/upload-panel/UploadInput.js
- app/ui/components/upload-panel/UploadWarning.js
- app/ui/components/upload-panel/index.js
- app/ui/interface/index.js
Little PR to fix up some copy around uploading files vs opening protocols (the latter being preferred for UX). Since I was already touching the files, I also added a little fix for the bug that prevented uploading the same file more than once in a row using the click to upload button (was never an issue with the dropzone)
- (Chore) Updated various copy to match the "Open Protocol" language shift
- (Fix) Fixed the bug preventing multiple uploads of same file (#387)
> (app) Change "Upload File" to "Open Protocol"

- Dockerfile
- api/opentrons/cli/main.py
- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/cli/test_cli.py
- compute/scripts/setup.sh
- compute/scripts/start.sh
Add protections and checks related to startup and calibration data
Important change: if you start the robot and "$APP_DATA_DIR/config.json" does not exist, the server **will not start**. It goes into an infinite wait loop so that the developer will be able to ssh in and do factory calibration.
- (feature) Add checks for config file on boot, prompt user to calibrate if not found and then go into wait loop
- (feature) Add confirmation before deleting calibration data, and restart after calibration
- (bugfix) Fix bash string comparison bugs in startup scripts
> Robot config file and id protections

- app/ui/components/connect-panel/RobotItem.js
- components/.flowconfig
- components/.gitignore
- components/Makefile
- components/README.md
- components/package-lock.json
- components/package.json
- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/__tests__/buttons.test.js
- components/src/__tests__/icons.test.js
- components/src/buttons.js
- components/src/icons.js
- components/src/index.js
- components/types/CSSModule.js
This PR copies the baby SVG icon component out of the app and into the components library. At the moment, the icon data are generated by:
1. Exporting the icon symbol as SVG from Sketch
2. Running the SVG through `svgo`
3. Copying the `path` and `viewBox` data from the optimized SVG
Obviously this needs to be automated at some point, but for now it works.
```js
import {Icon, WIFI} from '@opentrons/components'
export function SomeComponent () {
return (
<Icon name={WIFI} className='foobar' />
)
}
```
Still TODO in a followup:
* Replace all icons in app with `Icon` component
* Remove old `Icon.js`, `icons.js`, and `icons.css` in app
- (Feature) Added `Icon` to components library
- (Docs) Improved the components library README instructions
- (Docs) Added `Icon` to README
- …
> (complib, app) Add icons to comp lib (and swap out one USB icon in the app)

- api/opentrons/robot/robot.py
- api/tests/opentrons/protocol/test_robot.py
This is a temporary adjustment to allow a beta machine to run protocol with a container of height 170mm. This issue was the robot was colliding with Z limit switch while running, so this PR simply lowers `robot`'s tip clearance from `42`mm down to `20`mm, and also leaves a TODO emphasizing that this clearance should be determined by the context of that movement, not a context.
Check List:
> lower tip clearance to allow taller containers

- app/ui/components/PipetteConfig.css
- app/ui/components/PipetteConfig.js
- app/ui/components/setup-instruments/InstrumentTabs.js
- app/ui/components/setup-instruments/index.js
- app/ui/containers/ConnectedPipetteConfig.js
- app/ui/pages/SetupInstruments.js
- components/.flowconfig
- components/README.md
- components/package-lock.json
- components/package.json
- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/__tests__/buttons.test.js
- components/src/__tests__/structure.test.js
- components/src/structure/PageTabs.js
- components/src/structure/index.js
- components/src/structure/structure.css
Incremental PR of ongoing calibration screen alignment. I've added a `PageTabs` component ("Structure / Page / Tabs" in Sketch) and wired it to the pipette selection for instrument calibration:
A few things to note:
* Currently hardwired in CSS to two tabs (with `width: 50%;`)
* Pipette calibration is the only place we use this component for now
* Talked this through with UI/UX and everyone thought this was fine
* We're handling `active` manually rather than using `react-router` `NavLinks`
* State tracking with `NavLink` has been super flaky for us
* Happy to revisit if/when we figure out the flakiness
* For now manual tracking is completely reliable
* I started an `app/components/setup-instruments` directory
* For instrument setup specific components, naturally
- …
> (complib, app) Add PageTabs and use it for pip. selection

- compute/scripts/setup.sh
Happens on fresh SD burn. Added quotes in if statement.
Fixed typo.
> Fix setup.sh breaking when `/data/id` is empty

- appveyor.yml
Disable automatic AppVeyor test detection because we don't use it and it _drastically_ increases our build time for no reason.
> (repo) Disable AppVeyor test disc. for faster builds

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
When uploading a protocol in the app, the app first runs the protocol in simulating mode. The `pause` and `resume` functions did not check for simulating status, which means that a `pause` in a protocol followed by any command other than `resume` would cause the script to block forever. This PR modified `pause` and `resume` to pass if simulating.
Updated tests and documentation
- (bugfix) `pause` and `resume` do not block execution when in simulating mode
> Add simulating checks for pause and resume

- api/opentrons/drivers/rpi_drivers/gpio.py
GPIO echo commands fail (do nothing) when not running on a RPi. This is acceptable for use with virtual smoothie. The echo commands also throw various errors when trying to export a pin that has already been exported, such as when the robot is reinitialized without power-cycling the Pi. These commands are idempotent, so the errors can be safely ignored.
- (bugfix) Silence unnecessary sterr messages from gpio commands
> Redirect gpio stderr to null sink

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Per our discussions about moving to GitHub issues as our primary ticketing system, this PR is a refresh of the pull-request and issue templates from #340 (base branch has changed since that PR).
I simplified the stuff that was there in the interest of decreasing duplicate information and also moved all instructions to HTML comments because that made more sense.
- (repo) Add simplified PR/issue templates from develop 
I think the top commented out section is too wordy in both these templates and is information that probably belongs more in a contribution guide. I'm also curious as to what everyone thinks about how the changelog and commit log should / shouldn't be related
> (repo) Add simplified PR/issue templates from develop

- app/ui/components/setup-panel/LabwareList.js
- app/ui/components/setup-panel/LabwareListItem.js
- app/ui/components/setup-panel/ListItem.js
- app/ui/components/setup-panel/index.js
- app/ui/components/setup-panel/link-list.css
- app/ui/components/side-panel/index.js
Currently, we are not highlighting the active step in setup panel. This PR uses `NavLink` and `activeClassName` to do so. Additional fallback `active` prop and styling logic for non `NavLink` ListItems is present but not needed for SetupPanel.
- implement withRouter in NavPanel container
- use router for SetupPanel and children
- active list item style
- still missing logic to highlight non `NavLink` `ListItems`, this will be handled in the `ListItem` and `TitledList` component library PR coming soon.
Check List:
This is a small one, please check to see SetupPanel links in Sidebar highlight active instrument/labware properly.
> Highlight active setup panel list item

- app/.flowconfig
- app/.gitignore
- app/package.json
- app/ui/components/deck/ConnectedLabwareItem.js
- app/ui/index.js
- app/ui/robot/api-client/client.js
- app/ui/robot/api-client/discovery.js
- app/ui/robot/api-client/index.js
- app/ui/robot/api-client/worker.js
- app/ui/robot/test/api-client-discovery.test.js
This is an easy-win PR to launch discovery immediately upon API client startup. It also contains a little bit of chore work to the flow config (I was unable to run `make check` on my machine because flow was digging into files it didn't need to).
- (Feature) Added discovery kickoff to client initialization
- (Fix) Added already scanning guard to prevent discovery spamming
- (Chore) Cleaned up flow, standard, and jest config in app to fix up typechecking 
Nothing special! @btmorr a Windows test would be useful and much appreciated
> (app) Kickoff robot discovery on app launch

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
Use bottom of target location by default in `Pipette.dispense`. Fixes #524 
- (feature) Pipette.dispense defaults to bottom of target location if specific point is not specified
- (docs) Updated docstrings for aspirate and dispense
- (tests) Updated and reordered aspirate and dispense tests for similarity
Tested on the robot. When calling `pipette.dispense(well)` confirmed that the tip is 1mm above the bottom of the well.
When calling `pipette.dispense(well.top())` confirmed that the tip is at the top of the well
> Change default dispense location to bottom

- app/ui/components/deck/ConnectedLabwareItem.js
Use `withRouter` HOC to connect LabwareItem to `location`, instead of grabbing `location` directly from the state.
> Quick app cleanup: Use withRouter to connect LabwareItem to location

- app/package-lock.json
- app/package.json
- app/scripts/advertise-local-api.js
- app/ui/components/connect-panel/index.js
- app/ui/robot/actions.js
- app/ui/robot/api-client/client.js
- app/ui/robot/api-client/discovery.js
- app/ui/robot/reducer/connection.js
- app/ui/robot/selectors.js
- app/ui/robot/test/actions.test.js
- app/ui/robot/test/api-client-discovery.test.js
- app/ui/robot/test/api-client.test.js
- app/ui/robot/test/connection-reducer.test.js
- app/ui/robot/test/selectors.test.js
Another easy win PR for connection handling. This one changes our connection strategy from hostname to IP address. This should drastically improve our Windows connection handling for WiFi robots.
Ticks off a checkbox in #543 
- (Refactor) Organize discovered state by service name rather than hostname
- (Refactor) Connect to service's IP address rather than MDNS hostname
- (Tests) Update state tests for the discovered state refactor
Standard review I think. One thing to note: I changed the local service advertisements from random strings to computer hostname, which means:
* Changing state from keyed by host to keyed by name meant that _everyone's_ local APIs get picked up by the app
* Local API only listens on loopback, but that does mean
* I had to get a little weird to make sure the app …
> (app) Connect to robots via IP rather than hostname

- api/opentrons/api/calibration.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/mover.py
- api/opentrons/robot/robot.py
- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/labware/test_pipette.py
Changes the term 'power' to 'current' in the Smoothie driver and related files. This setting deals with current in mA, so the prior name was confusing. No functional changes
Resolves #565 
- (chore) Change 'power' to 'current' in driver and related files
- Ensure that updated code and documentation are sufficiently clear
> Rename 'power' to 'current' in driver and related settings

- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
- app/ui/robot/api-client/client.js
- app/ui/robot/selectors.js
- app/ui/robot/test/api-client.test.js
- app/ui/robot/test/selectors.test.js
Modify timestamp format in API to milliseconds-since-epoch
Related to #365 
- (chore) Modify session tracker in API to use milliseconds-since-epoch for timestamps
> Change timestamp format in API and App to milliseconds-since-epoch

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- compute/scripts/setup_gpio.py
- compute/scripts/start.sh
Move gpio pin initialization and turn on blue button into compute start script. This should quiet down false error messages, and turn the light on sooner.
- Move gpio initialization into start script
- Move initialization of button light to start script
- Verify on a robot
> Move gpio init and button light init to start script in container

- compute/scripts/start.sh
Fixes incorrect GPIO initialization script path in the compute start script.
- (bugfix) Fix incorrect GPIO initialization script path in compute start script
- Test on the robot and make sure the script is found correctly
> Fix gpio script path in start script

- app/src/robot/actions.js
- app/src/robot/reducer/calibration.js
- app/src/robot/selectors.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
This PR collapses the following `robot.calibration` subtrees
- `moveToFrontRequest` - Status of a `calibration_manager.move_to_front` request
- `tipProbeRequest` - Status of a `calibration_manager.tip_probe` request
- `instrumentByAxis` - Individual calibration "status" of each instrument, like `PROBING`
- This is not the same as the `probedByAxis` subtree, which is a latched boolean flag for if an instrument has been probed
Into the single subtree: `calibrationRequest`. This will simplify logic as we iterate on the tip probe experience.
I also took the opportunity to introduce `flow` to the `calibration` reducer. There's a lot of flow work to be done in our Redux stuff but right off the bat the encouraged me to program more defensively so I'm going to try to stay in the habit of adding …
> refactor(app): Collapse tip-probe tracking state

- app/package.json
- app/src/robot/constants.js
- app/src/robot/reducer/calibration.js
- app/src/robot/reducer/connection.js
- app/src/robot/reducer/index.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
This PR was originally intended to address #592, but as I introduced reselect and flow to the robot selectors, I found out:
- The problem the ticket is trying to solve isn't really a problem
- Or rather, I don't think we'll understand the problems we have until we start to implement #595
- I'm going to hold off on #592 for now, because if I keep swinging blindly this PR is gonna get huge
- Flow is really helpful to have in the reducers and selectors, so I went a little hog-wild 
What I ended up with is a PR that:
- Memoizes all the robot selectors
- The robot module is the only part of the app that does computed state
- Adds flow to all of the robot reducers + selectors
- This helps a non-trivial amount with understanding app state
Fixes #371
- Performance refactor: Memoized robot …
> Memoize robot selectors and introduce flow to robot state

- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/components/StepSubItem.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/containers/StepCreationButton.js
- protocol-designer/src/labware-ingred/__tests__/containers.test.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Most of #583 will be done with this PR (finally! :smiley: ), only last-touch styling will be left
* `StepCreationButton` container only calls `onClickAway` when it's expanded (less Redux logging spam)
* `StepCreationButton` - clicking "+ Add Action" when expanded will collapse it
* `StepList` no longer hard-coded
* `StepItem` no longer shows "labware header" unless both source and dest labwares are assigned
* Moved `labware-ingred/` tests into `labware-ingred/__tests__/` dir
* New Steps are named after their stepType by default, with no other default properties
* Can select a Step by clicking its title
* Can collapse/expand Steps by clicking the carat
1. What should the minimum be for testing this now? I feel conservative about writing new tests for this because I'm not sure how much will …
> PD: Create, select, collapse/expand Steps in Step List

- app/src/components/deck/CalibrateDeck.js
- app/src/components/deck/ConnectedLabwareItem.js
- app/src/components/deck/DeckConfig.js
- app/src/components/deck/LabwareItem.js
- app/src/components/deck/ReviewLabware.js
- app/src/components/deck/ReviewPrompt.js
- app/src/components/setup-panel/InstrumentList.js
- app/src/components/setup-panel/InstrumentListItem.js
- app/src/components/setup-panel/LabwareList.js
- app/src/robot/actions.js
- app/src/robot/reducer/calibration.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/calibration-reducer.test.js
To support [this week's sprint's](https://github.com/Opentrons/opentrons/projects/3) calibration work, we decided to rename the confusingly named flag `labwareReviewed` to `deckPopulated` for clarity. Closes #594; see that issue for reasoning and future plans with this flag.
- Refactor: renamed all instances of `labwareReviewed` to `deckPopulated`
- Refactor: switched default of `deckPopulated` from `false` to `true`
- This is to drive future clear deck before tip probe `ContinueModal`
- Does not change current functionality, as the first click on a Pipette for tip probe sets it to `false` (will change with modal)
> Rename labwareReviewed flag to deckPopulated and default to true

- Dockerfile
- api/Makefile
- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/opentrons/server/endpoints.py
- api/opentrons/server/main.py
- api/opentrons/server/rpc.py
- api/tests/opentrons/server/test_wifi_endpoints.py
- compute/scripts/start.sh
Adds wifi endpoints to list available SSIDs, check connectivity status, and configure credentials.
Related to #526 
Fixes #640 
- (feature) Add endpoints to list available SSIDs, check connectivity status, and configure credentials.
- (refactor) Make server entrypoint more readable
- (docs) Some explanatory material added to method docstrings
- (bugfix) Add missing environment variable to Dockerfile and remove unnecessary shell command
Tested on moon-moon. Feel free to use that or another robot, or test on a laptop. On a laptop, endpoints will return dummy responses that are formatted in a way that is consistent with real responses. If testing on a robot, endpoints will actually execute networking commands--be aware of what you're doing! :)
> Add endpoints for wifi networking

- .travis.yml
- components/Makefile
- components/package.json
- components/styleguide.config.js
- protocol-designer/index.html
Closes #628.
However:
- I'm deploying to S3 for non-failing builds on **all branches**, not just PRs.
- Old branches stay on S3 after the branch is deleted. If that's undesirable to you, please bring it up in the review.
- Fix dumb HTML typo in `protocol-designer/index.html` which was breaking production build page
- Stop running tests for protocol designer twice (`make -C protocol-designer test build` in travis)
- Mess with styleguidist webpack config so that `node_modules/.bin/styleguidist build` works
- `stylelint` ignores `**/dist/**` -- otherwise CSS module classnames violate the `"selector-class-pattern": "^[a-z0-9_]+$"` rule.
Component Library:
https://s3-us-west-2.amazonaws.com/opentrons-components/complib_pd-deploy-pd-and-complib-to-s3/index.html
Protocol Designer WIP: …
> Deploy component library & PD to S3 for design reviews

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints.py
Add version number of API and Smoothie FW to body of response to health endpoint. FW version is memoized when `robot.connect()` is called, so this does not result in repeated additional queries to Smoothie.
Unblocks #528 
- (feature) Add method to driver for retrieving FW version from Smoothie
- (feature) Add body to health endpoint with version of API and FW
Tested on the robot.
> Add metadata to body of health endpoint return

- app/src/components/RunControl.js
- app/src/components/deck/CalibrateDeck.js
- app/src/components/setup-instruments/InstrumentGroup.js
- app/src/components/setup-instruments/InstrumentInfo.js
- app/src/components/setup-instruments/InstrumentTabs.js
- app/src/components/setup-instruments/Instruments.js
- app/src/components/setup-panel/InstrumentList.js
- app/src/components/setup-panel/InstrumentListItem.js
- app/src/components/setup-panel/LabwareList.js
- app/src/components/setup-panel/LabwareListItem.js
- app/src/containers/ConnectedTipProbe.js
- app/src/pages/SetupDeck.js
- app/src/robot/api-client/client.js
- app/src/robot/constants.js
- app/src/robot/index.js
- app/src/robot/reducer/calibration.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
- app/src/robot/types.js
- components/src/structure/PageTabs.js
- components/src/structure/index.js
To help unblock work on #631 and #621, this PR changes the type of `slot` in the app to a string, removes all usage of legacy slot format in the app, and changes remaining instances of `axis` to `mount`.
- Refactor: changed type of `slot` to string
- Refactor: renamed all remaining instrument `axis` selectors, props, etc. to `mount`
- Chore: replaced PropTypes with flow in components that I touched where it was easy
Please make sure this still runs!
> Rename axis to mount and change slot type to string

- api/opentrons/commands/commands.py
- api/opentrons/containers/__init__.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/commands/test_description.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/containers/test_containers.py
- api/tests/opentrons/containers/test_default_containers.py
- api/tests/opentrons/containers/test_grid.py
- api/tests/opentrons/data/bradford_assay.py
- api/tests/opentrons/data/dinosaur.py
- api/tests/opentrons/data/multi-only.py
- api/tests/opentrons/data/multi-single.py
- api/tests/opentrons/data/pickup-accuracy.py
- api/tests/opentrons/data/smoke.py
- api/tests/opentrons/data/testosaur.py
- api/tests/opentrons/helpers/test_helpers.py
- api/tests/opentrons/integration/move_robot.py
- api/tests/opentrons/integration/test_protocol.py
- api/tests/opentrons/labware/test_module_placement.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/labware/test_temp_plate.py
- api/tests/opentrons/protocol/test_robot.py
- api/tests/opentrons/server/test_serialize.py
- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
Fixes #631 
Changes deck-slot naming from the `'A1', 'B2', etc.` scheme to the new `'1', '2', etc.` scheme.
If a container is added using `container.load()` and the slot is referenced using the old scheme, it will be automatically converted to the new numbering, and will throw a deprecation warning.
Most of the work involved in this PR was editing tests so that they no longer check for slots with the old names.
> Issue 554 correct slot names

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
fixes #629 
While homing the `X` axis under some circumstances, the gantry will collide with the `Y` endstop. To avoid this collision, this PR moves the gantry 20 millimeters towards the front of the machine (negative `Y` axis movement) immediately before every `X` home.
This implementation creates the not-so-nice behavior of grinding against the front of machine if the gantry is <20 millimeters away from the front. This has been minimized by setting the current and speed low while performing this `Y` movement.
> Fix 629 y homing switch avoidance

- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/steplist/actions.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Related to #583 -- I meant to do a few unit tests, but wound up flowifying this module. Jest tests in a smaller PR will finally close the issue.
Since we don't have deep flow coverage of Redux stuff yet in our JS project, this smaller-scope fluxification is an example that we *could* build off of, or could totally change.
Things to notice:
* from `redux-actions` it uses the utility functions `createAction` and `handleActions`. I took advantage of `flow-typed` definitions for `redux-actions`
* typed selectors with `reselect`
* It includes a thunk creator (`addStep`) which has different typing concerns than a normal action creator
* add flow types everywhere in `steplist` module of PD
* use new action creator functions instead of manually doing `dispatch({type: 'ADD_STEP', ...stuff})` in …
> Full flow typing for PD 'steplist' module

- protocol-designer/src/steplist/index.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/test/reducers.test.js
closes #583 
* jest tests for reducers
* Also added `index.js` for future `steplist/` imports (TODO later: `import {actions} from '../steplist'` instead of `import {actions} from '../steplist/actions'` in all imports)
We haven't really chatted much about tests. I tried to follow what I saw in the app. How's it look?
> (pd) add Jest tests for steplist reducers

- api/opentrons/api/calibration.py
- api/tests/opentrons/api/test_calibration.py
Expose `return_tip` method in calibration manager. Unblocks #536 
- (feature) Add `return_tip` method to calibration manager
> Add return_tip method to calibration manager

- api/opentrons/server/endpoints.py
- api/tests/opentrons/server/test_wifi_endpoints.py
Return a json packet NOT wrapped in quote marks. Fixes #646 
- (fix) Return json packet not wrapped in quote marks
> Remove `repr` from wifi endpoints

- components/src/__tests__/forms.test.js
- components/src/forms/CheckboxField.js
- components/src/forms/CheckboxField.md
- components/src/forms/RadioGroup.js
- components/src/forms/RadioGroup.md
- components/src/forms/forms.css
Tiny PR that shouldn't change much, but will help out #659 
* `value` prop instead of `checked` / `checkedValue` to match other form fields -- this is initial step to build out form field helpers in react
* updated tests and .md's for CheckboxField & RadioGroup
* fixed CSS CheckboxField problem with shrinking checkbox icon in narrow-width div
> (complib) standardize CheckboxField & RadioGroup

- components/src/__tests__/__snapshots__/lists.test.js.snap
- components/src/index.css
- components/src/lists/ListAlert.js
- components/src/lists/ListAlert.md
- components/src/lists/ListItem.js
- components/src/lists/ListItem.md
- components/src/lists/TitledList.js
- components/src/lists/TitledList.md
- components/src/lists/lists.css
- components/src/structure/navbar.css
- components/src/styles/colors.css
- components/src/styles/cursors.css
- components/styleguide.config.js
This PR closes #654 by adding a `disabled` prop to the `TitledList` component.
While I was touching the TitledList stuff, I touched up the style to get things a little closer to the screens, and I **defaulted the styleguide configuration to sans-serif** :taco:.
Also, I totally named this branch completely wrong. I only noticed right now, though, and I'm too far into writing this pull-request. Anyway, component library review link:
https://s3-us-west-2.amazonaws.com/opentrons-components/app_disable-titled-list/index.html
- Feature: add `disabled` prop to TitledList component
- Chore: adjust `lists.css` so that list styles more closely match our library screens
Standard review. It looked OK to me but @IanLondon could you double check that my futzing around hasn't messed with PD? Happy to …
> Add disabled prop to TitledList and get list styles closer to screens

- Dockerfile
Alpine updated in an upstream un-pinned dependency, which included a new build of `busybox` that did not include `inetd`, which in turn broke both our ssh access over ethernet and the "update" endpoint. 
This PR pins the version of our Resin source container to a specific nightly build with the correct version of `busybox`.
- Pin version of Resin source Docker container to prevent changes in dependencies, specifically in this case fixing the version of Alpine to 3.6 and busybox to 1.26.2 (the build of busybox v1.27.2 that shipped with Alpine v3.6 does not include inetd, which is required for this project)
Tested on moon-moon
> Pin docker source image version

- api/opentrons/instruments/pipette.py
Small PR, changes drop_tip plunger position to `-3.5` millimeters (former it was `-7mm`). That addition 3.5mm were previously traveling was creating an internal collision inside the pipette, and breaking them over time.
This new value `-3.5` millimeters, has been running on life-testing machines for a month.
NOTE: the's hard-coded values will eventually need to be auto configured per pipette model
> reduces droptip distance on plunger by 3.5mm

- api/tests/opentrons/data/calibration-validation.py
- app/src/components/deck/ConfirmCalibrationButtons.js
- app/src/components/deck/ConfirmCalibrationPrompt.js
- app/src/components/deck/ConnectedLabwareItem.js
- app/src/components/deck/NextLabwareLink.js
- app/src/components/deck/ReviewLabware.js
- app/src/components/setup-panel/LabwareList.js
- app/src/containers/ConnectedJogModal.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/calibration.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
First off: I'm sorry. This PR is too big. In hindsight:
- Adding flow typings and the required functionality changes in one PR wasn't necessary
- The functionality changes themselves could've been accomplished in two PRs
- Our request/response actions aren't well suited to flow and will need to be changed
Anyway, this PR closes #621 by using the following procedure to select a "calibrator":
- Tipracks will be calibrated by whichever pipette uses that tiprack
- Non-tipracks will be calibrated by whichever pipette still has a tip on it after tiprack calibration
- Added pipette usage from API session response to tiprack state
- Added tip tracking to pipettes during tiprack calibration
- Refactored containers to use pipette from tiprack state as calibrator if it exists
- Refactored get …
> Calibrate tipracks with inst. that uses them in protocol

- api/opentrons/robot/robot.py
- api/tests/opentrons/labware/test_pipette.py
A bug was found (fixes #660 ) which results in pipettes moving strangely. To recreate, you create a protocol which uses a pipette that has been overwritten by the robot.
```python
p1 = instruments.Pipette(mount='left')
p2= instruments.Pipette(mount='left')
p1.pick_up_tip().aspirate().dispense().return_tip()
```
SOLUTION: Raise a `RuntimeError` if a pipette is attempting to attach to an already occupied mount, resulting in the following:
```python
p1 = instruments.Pipette(mount='left')
p2 = instruments.Pipette(mount='left')
p1.pick_up_tip().aspirate().dispense().return_tip()
```
> Error if pipette mount already occupied

- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
Some documentation still referenced the `axis` parameter in Pipette, which is deprecated. Changes those references to `mount`. Also remove a todo note that is no longer relevant.
- (docs) Replace `axis` with `mount` in Pipette docstrings
> Correct documentation and todo items in pipette and robot

- app/src/components/connect-panel/ScanButton.js
- app/src/components/connect-panel/ScanStatus.js
- app/src/components/connect-panel/connect-panel.css
- app/src/components/connect-panel/index.js
- components/.babelrc
- components/package.json
- components/src/__tests__/__snapshots__/buttons.test.js.snap
- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/__tests__/buttons.test.js
- components/src/buttons/Button.js
- components/src/buttons/FlatButton.md
- components/src/buttons/IconButton.js
- components/src/buttons/IconButton.md
- components/src/buttons/OutlineButton.js
- components/src/buttons/OutlineButton.md
- components/src/buttons/buttons.css
- components/src/buttons/index.js
- components/src/icons/Icon.js
- components/src/icons/index.js
- components/src/structure/SidePanel.css
- components/src/structure/SidePanel.js
- components/styleguide.config.js
(Re)adds `IconButton` component per discussion in #664 and adds `OutlineButton` component as part of #677.
- Added `IconButton` component (`FlatButton` variant) that melds `ButtonProps` and `IconProps`
- Added `OutlineButton` component (`PrimaryButton` variant) as seen in new calibration screens
- Refactored `ScanButton` in the app to use new `IconButton`
- Refactored `buttons.css` to use fancy cssnext nesting (makes it all a bit easier to read)
Standard review!
> Add OutlineButton and IconButton components

- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/labware/test_pipette.py
Previously if the axis parameter was utilized in the pipette constructor, an exception would be thrown.
-Added warning to pipette constructor that the axis parameter is depreciated
-If the axis parameter is used, sets mount to proper value
-Updated tests to check that the warning is being properly executed
-Un-breaks axis exception error. Fixes #571 .
Please double check I am not writing over other's work!
> Adds deprecation warning to axis parameter for pipette constructor

- api/opentrons/server/rpc.py
- api/tests/opentrons/server/test_server.py
When a protocol file contains a syntax error, include the line number of the error in the message returned by the RPC server (to be displayed in the run app). Fixes #669 
- (feature) Add line number to error message from RPC server
Create a protocol with a syntax error, try to run it through the run app, get the error message with a line number that correctly corresponds to the line number from the protocol.
> Add line number to rpc error message

- api/opentrons/cli/linal.py
- api/opentrons/cli/main.py
- api/tests/opentrons/cli/test_linal.py
First pass refactoring the factory calibration CLI app. Removes use of global state and separates out functionality into methods that will be possible to unit test. Changes to functionality of tool should be very minor.
- (refactor) Move current factory calibration functionality from script into class
- (docs) Add documentation to factory calibration app
- (refactor) Add tests to CLI methods
Perform calibration on a robot using the prior version of the CLI, save the data, and then re-do calibration with this CLI. Compare the results.
> Refactor cli app to remove use of global state

- components/src/__tests__/__snapshots__/forms.test.js.snap
- components/src/forms/CheckboxField.js
- components/src/forms/CheckboxField.md
- components/src/forms/DropdownField.js
- components/src/forms/FormGroup.js
- components/src/forms/FormGroup.md
- components/src/forms/InputField.js
- components/src/forms/InputField.md
- components/src/forms/RadioGroup.js
- components/src/forms/forms.css
- components/src/styles/colors.css
closes #712 
* selected state of form fields matches design (light blue, no border)
* uniform `error?: ?string` prop for all form components
* `caption` prop for InputField & DropdownField
* `secondaryCaption` for InputField
* new `--c-light-blue` added to colors.css
* error state examples in styleguidist .md's
https://s3-us-west-2.amazonaws.com/opentrons-components/complib_invalid-form-state/index.html
Type non-positive-numbers into "This is a FormGroup" example's input field to see error
Type too many characters into the "0/12" InputField example
Try popping an `error='nooo'` prop into the different form field examples in styleguide to see error states
And `caption='something'` to InputField / DropdownField (+ `secondaryCaption='99/100'` etc to InputField)
Select fields and see they're …
> (complib) invalid+selected states for form fields

- api/opentrons/api/session.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints.py
- api/opentrons/server/main.py
Adds endpoints for identifying robot (by blinking the button light) and turning the rail lights on and off
- (feature) Add endpoints for identifying robot and turning rail lights on and off
To identify:
```
curl <robot_ip>:31950/identify?seconds=10
```
To turn lights on and off:
```
curl <robot_ip>:31950/lights/on
curl <robot_ip>:31950/lights/off
```
Code on `son-of-moon-moon` has these endpoints available if you want to test
> Add some light control endpoints to server

- app/src/components/deck/ConfirmCalibrationPrompt.js
- app/src/components/deck/ConnectedLabwareItem.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/calibration.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
Upcoming labware calibration work requires some behavioral changes. Rather than try to lump the changes and state cleanup in one, I've split out a bunch of the state cleanup (without behavioral changes) into this PR.
* Collapsed all remaining calibration request substates into the `calibrationRequest` substate
* Split calibration response actions into success and failure types to play correctly with flow
* Removed annoying labware calibration status substate (e.g. `moving-to-slot`, `over-slot`, etc.) in favor of generating the status in a selector based on `calibrationRequest`
* We did this with great success with the tip probe status substate previously
* Also added `labware` level `isMoving` prop to spinner logic!
Standard review.
Please note: this PR breaks labware calibration …
> refactor(app): Rework calibration actions and responses to remove cruft

- api/opentrons/robot/robot.py
In this PR, if moving from one well to another within the same labware, it will only move high enough to avoid collision with that single labware.
If moving from one labware to another, however, it will move up to it's a safe height above all labware.
```python
p300.move_to(plate[0])  # safe height is above ALL labware
p300.move_to(plate[1])  # safe height is above just the plate
p300.move_to(plate[95])  # safe height is above just the plate
p300.move_to(trough[0])  # safe height is above ALL labware
p10.move_to(trough[1])  # different pipette, safe height is above ALL labware
```
`robot._create_arc()` keeps track of the most previously moved-to labware, and if the current container is the same as prior, the arc's `Z` height is determined using that container's calibrated height with the …
> low arc height within same container

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
This PR reduces the amount of time spent homing all axes or an individual axis, which occur both by user-initiation, and also during pipette operations like `probe`, `drop_tip`, and `pick_up_tip`
`drop_tip()` and `pick_up_tip()` use the `fast_home()` method, which moves that axis near it's switch, then homes from there.
`fast_home()` will recover from hitting the home switch to soon, by catching that `SmoothieError` and proceeding with a normal home afterwards.
`robot.home()` was previously homing the `Z` and `A` axis multiple times. This PR removes those redundant homes by only calling `gantry.home()` to home the `XYZA` axes, following by the plunger motors `BC`.
> faster homing

- app/src/components/setup-instruments/InstrumentGroup.js
- app/src/components/setup-instruments/InstrumentTabs.js
- app/src/components/setup-instruments/Instruments.js
- app/src/components/setup-panel/InstrumentList.js
- app/src/components/setup-panel/LabwareList.js
- app/src/components/setup-panel/TipRackList.js
- app/src/robot/README.md
- app/src/robot/constants.js
- app/src/robot/selectors.js
- app/src/robot/types.js
Little PR to clean up `getInstruments`. Previously, it could return an `Instrument` _or_ an object `{mount: Mount}`. This made for some convoluted logic in some components. Now, `getInstruments` always returns an array of `Instrument` objects.
This helps with #677 because the jog confirmation screens need to identify which instrument is being used to confirm the position.
- Added `Instrument` type that represents the instrument object from `getInstruments`
- Refactored `getInstruments` to only return used instruments
- Fixed instrument and labware highlighting in `SetupPanel`
> refactor(app): Simplify getInstruments to only return Array<Instrument>

- protocol-designer/src/components/ProtocolEditor.css
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/containers/ConnectedNav.js
- protocol-designer/src/containers/NavBar.css
- protocol-designer/src/navigation/actions.js
- protocol-designer/src/navigation/index.js
- protocol-designer/src/navigation/reducers.js
- protocol-designer/src/navigation/types.js
- protocol-designer/src/types.js
Boilerplate stuff for page navigation in PD.
* Add new `navigation/` module with Redux stuff for page navigation. My plan is that other navigation-related stuff, like "labware & ingredient setup" mode vs "step editing" mode, and modal states, will go in here too. (Probably header state as well, although that might be its own mini-module, TBD.)
* Use NavIcon instead of Icon in nav panel
* `ConnectedNav`
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_style_nav/index.html#/
* Clicking the 2 NavIcons should visually toggle their "selected" state. The actual "main page" on the right side of the screen doesn't change.
> (pd) Page navigation -- Redux and Container foundation

- app/src/components/connect-panel/RobotItem.js
- app/src/components/connect-panel/connect-panel.css
- app/src/components/nav-bar/NavButton.js
- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/__tests__/icons.test.js
- components/src/icons/Icon.md
- components/src/icons/icon-data.js
This PR closes #770. Matches RobotItem designs. Introduces TOGGLED_ON and TOGGLED_OFF icons to comp lib and implements then in an `IconButton` in robot item. This button does not toggle connectivity yet since we don't have ConnectPage implemented yet. Entire RobotItem dispatched connect or disconnect actions until next PR. 
p.s. I took out the open/close side panel action from the nav bar buttons since i removed the close button in SidePanel in the last PR. SidePanel is officially fixed and open for now. I commented out the logic rather than deleting in incase we have to revert.
- Adds `Toggled_On` and `Toggled_Off` icons to complib
- Adds `IconButton` with toggle icons to `RobotItem`,
- This button is tested with onClick connect disconnect,
but since the entire RobotItem is handling the …
> Update robot list item design

- app/src/components/connect-panel/RobotItem.js
- app/src/components/setup-panel/run-panel.css
- app/src/robot/actions.js
- app/src/robot/api-client/discovery.js
- app/src/robot/reducer/connection.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client-discovery.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
This PR doesn't have a ticket, which is a weird oversight on my part. It is a little PR to improve the usability of the robot list now that it's all pretty and stuff
* Feature: added sorting to the robot list by:
1. Connected vs disconnected
2. Wired vs wireless
3. Alphabetically
* Feature: added wifi icon to the robot in the list if it's not a wired connection
* Feature: added removal detection of wired bot in discovery
* Side note: removal detection while connected is a weird edge case
* Until we can think through error detection and communication, to prevent anything strange, the app will _not_ remove the currently connected robot from the list
> Sort connected/wired robots first and change icon based on wired/wireless

- api/opentrons/data_storage/labware_definitions.py
- api/tests/opentrons/database/test_labware_definitions.py
- api/tests/opentrons/database/test_serializers.py
Add function to list all available labware and add compatibility test for all labware available in new format.
Fixes #766 
- (feature) Add function to list all labware in new system
- (tests) Add compatibility test for all labware in new system
> Add list function and compatibility test for all new labware

- Dockerfile
- compute/conf/nginx.conf
- compute/scripts/start.sh
Add a jupyter notebook server to the robot to make it easier to control for developers who wish to control the robot directly with Python instead of using the run app. (not ticketed--discussed amongst the team at a few points)
- (container) Add jupyter install to Dockerfile, a jupyter notebook server to the start script and register the notebook server port through nginx
> Add jupyter server to robot

- api/opentrons/data_storage/labware_definitions.py
- api/opentrons/data_storage/serializers.py
- api/tests/opentrons/database/test_labware_definitions.py
Adds save functions for user definitions and offset files in new labware definition format. 
Fixes #796 
- (feature) Add save functions for user definitions and offset files in new labware definition format
> Add save functions for user labware definitions and offsets

- .eslintignore
- .eslintrc.js
- .stylelintrc.js
- .travis.yml
- CONTRIBUTING.md
- Makefile
- README.md
- app-shell/Makefile
- app-shell/README.md
- app-shell/package.json
- app-shell/yarn.lock
- app/Makefile
- app/README.md
- app/package.json
- app/src/components/App.css
- app/src/components/App.global.css
- app/src/components/RunControl.css
- app/src/components/RunLog.css
- app/src/components/RunNotifications.css
- app/src/components/ToolTip.css
- app/src/components/Upload.css
- components/Makefile
- components/README.md
- components/package.json
- package.json
- protocol-designer/Makefile
- protocol-designer/package.json
- protocol-designer/src/components/IngredientPropertiesForm.css
- protocol-designer/src/components/IngredientsList.css
- yarn.lock
Our front-end lint configurations (JS, CSS, and flowtype) are all the same, but (excluding flow since #589) each of our projects contain independent (identical) settings files. This is becoming a big enough nuisance that I think we all want this to go away.
As alluded to in #578, linting every front-end project takes pretty much the same time as linting just one, so I replaced all project level `make lint` tasks with repository level tasks. To avoid maintaining multiple identical configs, I've pulled all the lint configs (eslint, stylelint) to the repository level, too.
A caveat: the only way to configure the [standard](https://standardjs.com/) linter is in `package.json`, and the [Atom linter plugin for standard](https://github.com/ricardofbarros/linter-js-standard) gets confused by …
> chore(frontend): Consolidate lint config, tasks, and docs to repo level

- api/opentrons/api/calibration.py
- api/opentrons/robot/mover.py
- api/opentrons/robot/robot.py
- api/opentrons/util/calibration_functions.py
- api/tests/opentrons/protocol/test_robot.py
Fixes #790 
- Robot uses two separate tip-clearances when creating arced movements, one for moving between different labware (20mm), another for moving between wells in the same labware (5mm)
- Robot no longer unnecessarily lowers it's Z height before moving horizontally
> Pipette at safe(r) height when moving between labwares

- app/src/components/CalibrateDeck/LabwareItem.js
- app/src/components/LabwareCalibration/ConfirmModal.js
- app/src/components/LabwareCalibration/ConfirmPositionDiagram.js
- app/src/components/LabwareCalibration/InfoBox.js
- app/src/components/LabwareCalibration/styles.css
- app/src/components/ReviewDeckModal/LabwareComponent.js
- app/src/components/ReviewDeckModal/Prompt.js
- app/src/components/ReviewDeckModal/styles.css
- app/src/components/TipProbe/ContinuePanel.js
- app/src/components/TipProbe/index.js
- app/src/components/setup-panel/DeckCalibrationGroup.js
- app/src/components/setup-panel/InstrumentList.js
- app/src/components/setup-panel/InstrumentListItem.js
- app/src/components/setup-panel/LabwareListItem.js
- app/src/components/setup-panel/RunButton.js
- app/src/components/setup-panel/RunMessage.js
- app/src/components/setup-panel/index.js
- app/src/components/setup-panel/styles.css
- app/src/pages/SetupDeck.js
- app/src/pages/SetupInstruments.js
- components/src/deck/LabwareContainer.css
@pantslakz, @umbhau and I did an in-person review of the calibration flow as implemented, and came away with a set of changes to get the app closer to the designs.
https://docs.google.com/presentation/d/16QWNSxA1xqloF92yMbjGQmF5O_Zs5-6SiLBLQWjc_Dw/edit?usp=sharing
- Refactor: Updated various visual elements and copy based on in-person comparison to UX screens
Still TODO in another PR:
- Swap alignment diagram assets to the new ones
- Deckmap opacity tweaks and MOVE TO overlay
- Return Tip button + setup panel run button removal
Longer term punts:
- Labware details (need to spec out what we want from the API rather than trying to parse labware types on the front-end)
- Tooltips (larger project also involving tutorial mode)
Standard review. @pantslakz here are the links to the app build …
> refactor(app): Implement visual UX feedback for calibration flow

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
> retracts slowly away from Y endstop when homing

- app-shell/lib/main.js
- app/package.json
- app/src/http-api-client/__mocks__/client.js
- app/src/http-api-client/__mocks__/health.js
- app/src/http-api-client/__tests__/client.test.js
- app/src/http-api-client/__tests__/health.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/index.js
- app/src/reducer.js
- app/src/robot/api-client/discovery.js
- app/src/robot/api-client/worker.js
- app/src/robot/index.js
- app/src/robot/reducer/connection.js
- app/src/robot/selectors.js
- app/src/robot/test/api-client-discovery.test.js
- app/src/robot/test/connection-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
- app/src/types.js
- yarn.lock
This PR is part of #807 and #812.
- Added a simple HTTP API client
- Will use this client to retrieve robot settings
- Added a redux module to track responses from the HTTP API
- Currently includes /health, where we get API version information
- Added health data to `getDiscovered` selector 
- Refactors robot discovery to use new HTTP API client for wired robot discovery
This looks big, but the size is mostly from tests, mocks, and flow type additions. I apologize regardless
> feat(app): Add HTTP API client and health state to robots

- Makefile
- app-shell/Makefile
- app/Makefile
- components/Makefile
- protocol-designer/Makefile
Hotfix PR for our build process
- Added call to `flow-typed install` to `make install` so CI `flow` doesn't choke on `jest` for new tests in PD that use jest (#825)
- Reverted removal of  `SHELL=/bin/bash` in Makefiles because apparently `zsh` chokes on the `PATH` setting
Please double check your local build env
> build(make): Add flow-typed install to make install task

- app/Makefile
This is dumb and my fault for not testing #805 more extensively. Turns out I broke `make -C app` on (my) mac, and maybe on *nix in general.
1. `make -C app dev` uses an npm package called [concurrently](https://github.com/kimmobrunfeldt/concurrently) to spawn several tasks concurrently
* webpack dev server
* local mdns reporter
* electron
2. The electron task is a call to `make -C ../app-shell dev`
3. `concurrently` enables color logging by default
- On my machine, this resulted in color codes prepended to the output of `yarn bin`
4. The Makefiles now call `yarn bin` to add to the `PATH`
End result: the extraneous color codes completely borked `PATH` and thereby rendered the `electron` executable in `app-shell/node_modules/.bin` unfindable by Make.
This PR adds the `--no-color` flag (and …
> build(make): Fix concurrently color messing with yarn bin output

- app/src/components/CalibrateDeck/ConnectedLabwareItem.js
- app/src/components/LabwareCalibration/ConfirmModalContents.js
- app/src/components/ReviewDeckModal/index.js
- app/src/components/setup-panel/RunPanel.js
- app/src/robot/selectors.js
Fixes #831
- Fix: made `calibrator` and `calbratorMount` optional and updated containers to adjust accordingly
Try it out with the protocol of 831
> fix(app): Make calibrator optional to support no-pipette protocols

- api/opentrons/commands/commands.py
This PR address a small bug found when `commands/commands.py` attempts to stringify valid arguments to `pipette.transfer()`:
```python
dest_wells = [well.bottom() for well in plate]  # creates a list of tuples
pipette.transfer(100, trough['A1'], dest_wells)  # valid transfer command, but breaks when stringified by commands.py
```
Source/Destination well arguments to pipette commands which were being stringified by `commands/commands.py`, were breaking if a list of tuples was an source or destination for `pipette.transfer()`. This PR uses the `containers.unpack_location()` to automatically convert any list (of either `tuples` or `Placeables`) into a list of `Placeables`.
> stringify list of Placeables

- app/package.json
- app/src/index.js
- yarn.lock
Little chore PR to replace the `redux-logger` middleware with the way more informative [redux devtools extension](https://github.com/zalmoxisus/redux-devtools-extension) in the app. Fixes #625
- Chore: enabled Redux devtools extension in the app ui
This PR removes the `redux-logger` dep so you may want to run `yarn` before testing / after merge. Standard review otherwise.
> chore(app): Enable redux devtools extension

- api/opentrons/api/session.py
- api/opentrons/commands/commands.py
- api/opentrons/containers/__init__.py
- api/opentrons/containers/placeable.py
This PR moves `location_to_list()` to `placeable.py`, and then session manager uses this method to parse command arguments that include lists of locations.
Just like an earlier PR, arguments to `pipette.transfer()` are being parsed by `session.py` and `commands.py`, and given the many different types of arguments accepted by `pipette.transfer()`, so then session and command must be prepared to parse those different types of location arguments.
> Session parses list of placeables

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
This PR raises an exception if when retrieving current position from Smoothieware we don't get all 6 axes. If `driver._parse_axis_values()` gets bad data, we want to raise an exception so `driver.update_position()` can try again.
> Assert that parsed axis values include all 6 axis

- app/src/components/ReviewDeckModal/Prompt.js
- components/src/__tests__/__snapshots__/buttons.test.js.snap
- components/src/__tests__/buttons.test.js
- components/src/buttons/Button.js
- components/src/buttons/FlatButton.js
- components/src/buttons/FlatButton.md
- components/src/buttons/IconButton.js
- components/src/buttons/IconButton.md
- components/src/buttons/OutlineButton.js
- components/src/buttons/OutlineButton.md
- components/src/buttons/PrimaryButton.js
- components/src/buttons/PrimaryButton.md
- components/src/buttons/buttons.css
- components/src/lists/ListItem.js
- components/styleguide.config.js
This PR addresses #807. (new instance of outline button in the designs)
All comp lib buttons can now receive an `inverted` boolean which will change the button style to work on a dark background. You can see this in use in the app on the review deckmap page. 
- adds inverted boolean to button components
- standardizes inverted and default classes for flat and outline buttons
- update styleguide and tests
- TODO: clean up primary button styles, I think they could be cleaner but punting for now.
- add activeClassName prop to ListItem (when url is present)
Standard review. 
https://s3-us-west-2.amazonaws.com/opentrons-components/comp_inverted-buttons/index.html#buttons
> Comp inverted buttons

- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/steplist/actions.js
- protocol-designer/src/steplist/constants.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Closes #759 
* Initial Deck Setup step exists in default state instead of being hard-coded in step list
* Selecting "Deck Setup" steps doesn't dispatch
`POPULATE_FORM` action, and doesn't cause a new blank form to be generated - unlike all other Step types, "Deck Setup" step doesn't open a form upon selection.
* `deckSetupMode` selector indicates if we're in Deck Setup Mode (as opposed to Step Form Edit Mode for Transfer/Mix/etc step types)
* StepItem for "Deck Setup" has no collapse carat
* validatedForms selector supports deck-setup step (kinda, hard-coded data)
And:
* Fix bug with Pause form validation where it would be invalidated when it should have been valid
Using the selector debugger in dev mode, confirm `deckSetupMode` selector is `true` only when a "Deck Setup" step is selected …
> PD: Deck setup step, deck setup mode

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
Use relative gcode command (`G91`) to retract the Y axis while homing, to avoid bug with retrieving current coordinate during Y homing.
> Relative gcodes during y-homing retract

- app/README.md
- app/src/http-api-client/__mocks__/client.js
- app/src/http-api-client/__mocks__/health.js
- app/src/http-api-client/__tests__/health.test.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/types.js
- app/src/http-api-client/wifi.js
- app/src/index.js
- app/src/robot/api-client/discovery.js
- app/src/robot/api-client/worker.js
This PR is part of #698. It adds the ability to retrieve the current WiFi status of a robot (i.e. does the robot have internet access) and the available SSIDs.
- Feature: added wifi module to http-api-client with support for `/wifi/list` and `/wifi/status`
- Feature: added `SKIP_WIRED_POLL` env var to disable polling for wired robot
- Reduces failed `fetchHealth` Redux spam in development (ping @Kadee80)
- `SKIP_WIRED_POLL=1 make -C app dev`
> feat(app): Add /wifi/list and /wifi/status to HTTP API client

- api/opentrons/server/endpoints.py
- api/tests/opentrons/server/test_wifi_endpoints.py
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/wifi.js
This PR is part of #698 and adds additional network information to the /wifi/list response.
- Feature (BREAKING CHANGE): added signal and active flag to /wifi/list reponse
- Previous format: `Array<string>`
- New format: `{list: Array<{ssid: string, signal: ?number, active: boolean}>}`
- Refactor: removed all bespoke response validation from the client
- It's not the client's job to ensure that the response formats are correct
- The extra logic just makes the client harder to read and more brittle
This PR touches both API (@btmorr + @Laura-Danielle) and Run App (@Kadee80 + @IanLondon). I'm also pushing it to `son-of-moon-moon` for testing.
--- 
Update: pushed to `son-of-moon-moon` and appears to be behaving properly
> feat(app,api): Refactor /wifi/list to provide signal and active flag

- components/src/__tests__/__snapshots__/modals.test.js.snap
- components/src/__tests__/modals.test.js
- components/src/modals/AlertModal.js
- components/src/modals/AlertModal.md
- components/src/modals/ContinueModal.js
- components/src/modals/ContinueModal.md
- components/src/modals/Modal.js
- components/src/modals/Overlay.js
- components/src/modals/index.js
- components/src/modals/modals.css
This PR is for #694, #695, #826 (and whatever other tickets require an alert modal of some sort to pop up. It adds an `AlertModal` component and refactors the `ContinueModal` to use `AlertModal` as its base.
- Feature: Added `AlertModal` and use it to drive `ContinueModal`
- Feature: Added `display: pointer` to `Overlay` when `onClick` is present
Components library preview: <https://s3-us-west-2.amazonaws.com/opentrons-components/complib_alert-modal/index.html#alertmodal>
> feat(complib): Add generic AlertModal component

- api/opentrons/instruments/pipette_config.py
This PR increases the `P10_Single` pipette's default Z current while creating a seal with a new tip, to avoid Z motor now having enough force and stalling.
> increases p10 pick_up_tip current to 0.1 amps

- app/src/components/App.js
- app/src/components/RobotSettings/StatusCard.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- app/src/components/connect-panel/RobotItem.js
- app/src/components/connect-panel/RobotList.js
- app/src/components/connect-panel/connect-panel.css
- app/src/components/connect-panel/index.js
- app/src/components/upload-panel/upload-panel.css
- app/src/pages/Robots.js
- app/src/robot/api-client/client.js
- app/src/robot/constants.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/types.js
- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/__tests__/structure.test.js
- components/src/structure/Card.js
- components/src/structure/Card.md
- components/src/structure/LabeledValue.js
- components/src/structure/LabeledValue.md
- components/src/structure/SidePanel.css
- components/src/structure/index.js
- components/src/structure/structure.css
This PR closes #807 by adding a basic robot settings page. Props to @Kadee80 who did most of this work and then got super sick (please feel better soon).
- Feature: Added Card and LabeledValue components to the component library `structure` group
- Feature: Added basic robot settings page to Run App
Standard review!
Build links:
- Windows: https://s3.amazonaws.com/ot-app-builds/ci-builds/opentrons-v3.0.0-win-2018-02-19_20-09-app_robot-settings-page-58ade2b.exe
- Debian: https://s3.amazonaws.com/ot-app-builds/ci-builds/opentrons-v3.0.0-linux-amd64-2018-02-19_20-12-app_robot-settings-page-58ade2b.deb
- Mac: https://s3.amazonaws.com/ot-app-builds/ci-builds/opentrons-v3.0.0-mac-2018-02-19_20-12-app_robot-settings-page-58ade2b.zip
**Note:**
The robot status strings are coming straight from …
>  feat(app): Add basic robot settings page

- Dockerfile
- Makefile
- api/opentrons/server/endpoints.py
- api/tests/opentrons/server/test_wifi_endpoints.py
The `/wifi/configure` endpoint of the API took a JSON request and returned a text response. This PR updates the endpoint to return JSON for consistency and adds the SSID to the response body to help the client accurately process the response.
- Refactored /wifi/configure to return JSON
- Locked pipenv install to 9.0.3 because the 9.1.0 release from a few hours ago seems to break Docker
BREAKING CHANGE: /wifi/configure response is a completely different format now. Ok because there are no clients as of yet
Standard API review. Robot testing ongoing with `wandering-dream`
I am a little worried about this endpoint not working if the user is calling it over WiFi, but given that our primary use-case is calling the endpoint via ethernet (and we're hopefully only allowing /wifi/configure over …
> refactor(api): Refactor /wifi/configure to respond with JSON

- app/src/http-api-client/__tests__/client.test.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/types.js
- app/src/http-api-client/wifi.js
~Blocked by #880. Will rebase branch over / update PR base to `v3a` when 880 is merged. Ready to review, though.~ Rebased and merged
This PR is part of #698 and adds the plumbing necessary for the app to update the WiFi network.
- Feature: added `configureWifi` action creator to call `/wifi/configure`
Standard review. No UI yet so end-to-end robot testing will have to wait until then (unit tests in place, though)
> feat(app): Add configureWifi action creator to call /wifi/configure

- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- app/src/http-api-client/health.js
- app/src/http-api-client/wifi.js
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
- components/src/structure/structure.css
~Blocked by #882. Will rebase the branch and PR when 882 is merged.~ Unblocked
This PR is part of #698 and adds a card that displays the current WiFi network to the robot settings page.
- Added basic ConnectivityCard container component to display current WiFi network
Standard review. Please prioritize reviewing #882 first.
The ConnectiviyCard container uses the `componentDidMount` and `componentDidUpdate` to trigger a call to `/wifi/list` on first render and on updates with a new robot, respectively. We'll probably need a refresh button, too, but for now this works I think.
> feat(app): Add Connectivity card WiFi network to robot settings page

- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
Fixes #881
This PR updates the robot client (RPC, not HTTP) to close any existing connection if it receives a connect command. Previous behavior was to noop upon new connect so this should be a drastic improvement.
- Fix: disconnect old client on new connect command rather than nooping
Works on my machine, so please double check that this works on yours!
> fix(app): Disconnect old rpcClient if it exists on new connect

- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/index.js
This PR closes #812 by adding a basic information card to the robot settings page
- Added basic InformationCard container component to the robot settings page
Similar to #883, the `InformationCard` container has fetch requests attached to `componentDidMount` and `componentDidUpdate`. We probably want a refresh button and/or periodic updates, too, but that's a future us problem.
> feat(app): Add InformationCard with name + server version to robot page

- app/src/components/RobotSettings/ConnectAlertModal.js
- app/src/components/RobotSettings/index.js
- app/src/pages/Robots.js
- app/src/robot/actions.js
- app/src/robot/reducer/connection.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/connection-reducer.test.js
This PR closes #826 by adding an AlertModal to the RobotSettings component that will display if a connect attempt fails.
- Feature: Added ConnectAlertModal to display a message if a robot connection fails
> feat(app): Add ConnectAlertModal for failed robot connection attempts

- components/src/structure/SidePanel.css
This PR closes #886 by preventing `display: flex` from shrinking the side panel.
- Fix: Added `flex-shrink: 0` to the SidePanel CSS rules
Should be a simple review. As an aside, I'm not sure why the Run App uses `display: flex` for the whole page in the first place, so we should investigate that.
> fix(complib): Do not allow flexbox to shrink the side panel

- components/src/deck/Plate.js
Fixes #890. The protocol attached to that ticket blew up the deck map in the app because it uses the `point` container type, which has no `origin-offset` in `default-containers.json`. @IanLondon I'm not sure how "correct" this fix is, but it does stop everything from exploding.
- Fix: added a default `originOffset` of `{x: 0, y: 0}` to the `Plate` component if it can't find one in the labware definition file
@IanLondon could you verify this doesn't cause problems with PD?
> fix(complib): Use default offset of (0,0) if missing from container

- api/opentrons/robot/robot.py
Fixes #818 
Update each mover within  `robot._actuators` within `robot.reset()`, so that if `robot.reset()` is called in a protocol, the machines does not lose position.
> Update robot position after robot.reset()

- api/tests/opentrons/data/Everything_Test_Software.py
This is a 'stress test' of all user facing API changes + any normal python idioms that worked previously. You can run the 'Everything_Test_Software.py' on a robot to test out different behaviors. Not all parts need to be run at once, each section is independent of another.
The following is tested:
-> Different types of pipette constructors
-> Different naming conventions for deck slots
-> Pipette methods: pick_up_tip, return_tip, changing aspirate/dispense speed, transfer, distribute, consolidate methods etc
-> List comprehension inputs for source + destination within high level liquid handling functions
@andySigler @btmorr Let me know if you see other important tests that are missing
> Everything Protocol Test for API

- protocol-designer/src/containers/IngredientsList.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
Still cleaning up ingred selection in PD. Previously, `ingredients` reducer contained `locations`. Since it was all in one reducer, the reducer itself could assign IDs to new ingredients, and differentiate between copying an ingredient with changes, copying an ingredient with no changes, creating a new ingred, or editing an existing ingred -- this is all under the `EDIT_INGREDIENT` action.
This PR factors out `ingredients[ingredGroupId].locations` to its own reducer and adds some tests for it.
* 'ingredients' broken out into 'ingredientLocations'
* No more ID assignment inside 'ingredients' - now 'editIngredients' thunk creates ID of new ingredients
* tests & selectors updated
* Added more type checking to `labware-ingred/` stuff
In PD ingredient selection modal, you should be able to …
> PD: factor out ingred locations

- api/opentrons/server/endpoints.py
- api/tests/opentrons/server/test_health_endpoints.py
- app/src/http-api-client/__tests__/health.test.js
- app/src/http-api-client/health.js
This PR is to support #698 by updating the /health endpoint with the robot name. This will allow the app to display the correct name when updating the WiFi network. Without it, it's very hard for the user to know which robot they're operating on when they're plugged in via ethernet.
- Feature (API): Added robot name to /health endpoint
- Tests (Run App, API): Updated/added tests accordingly
Standard review. Let me know if the health endpoint test is at all worth having
> feat(api): Add robot name to GET /health

- app/src/components/RobotSettings/ConfigureWifiForm.js
- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/inputs.js
- app/src/components/RobotSettings/styles.css
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/wifi.js
- components/src/__tests__/__snapshots__/buttons.test.js.snap
- components/src/__tests__/__snapshots__/forms.test.js.snap
- components/src/__tests__/__snapshots__/modals.test.js.snap
- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/buttons/Button.js
- components/src/forms/DropdownField.js
- components/src/forms/InputField.js
- components/src/forms/forms.css
- components/src/forms/index.js
- protocol-designer/src/components/StepEditForm.js
This PR addresses checkbox 2 of #698 by adding a wifi configuration form to the ConnectivityCard
- Feature: added ConfigureWifiForm to ConnectifyCard to allow setting the WiFi network of a robot
Standard review. A few things to note:
- @IanLondon this PR touches a few of the input components in complib pretty lightly
- I gave PD a once over and everything seemed OK, but can you double check?
- The WiFi form is disabled if the robot is not wired
- **It won't work with `make -C api dev`**
- Still TODO: actually showing this disabled state in the UI with instruction on how to enable it
- Still TODO: indication of "request in progress"
- Soft plan: spinner in the top right corner of the card and disable form
> feat(app): Add wifi configuration to ConnectivityCard

- app/src/components/App.js
- app/src/components/AppSettings/AppInfoCard.js
- app/src/components/AppSettings/index.js
- app/src/components/AppSettings/styles.css
- app/src/components/menu-panel/index.js
- app/src/components/menu-panel/styles.css
- app/src/components/nav-bar/NavButton.js
- app/src/components/side-panel/index.js
- app/src/interface/index.js
- app/src/pages/AppSettings.js
- components/src/icons/icon-data.js
- components/src/lists/ListItem.js
closes #808, addresses #809.
This PR adds 'more' button to the bottom of the `NavBar`, adds a `MenuPanel` to `Sidebar` with its first menu item for App page. App page for now renders a card with a placeholder version from `package.json` and renders disabled update button with the text 'updated'.
- Add more icon to complib
- Make disabled optional param for list-item
- Update navbar to have more tab on bottom
- Add MenuPanel to sidebar
- Add App list item to MenuPanel
- Create AppSettingsPage with AppInfoCard with placeholder version and disabled update button
- Hitting route '/menu' defaults to splash page
- Hitting route '/menu/app' loads AppSettingsPage
Standard review, I tried to follow the same patterns as RobotSettings page.
> Add about page

- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/http-api-client/__tests__/health.test.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/types.js
- app/src/http-api-client/wifi.js
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
- app/src/robot/types.js
This PR addresses a few TODOs from #898 related to selectors. Basically, just jamming the HTTP API request/response state into the `robot` module's selectors was not scalable.
Instead, I've implemented [selectors that take props](https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-component-instances), where `props` is a discovered robot object. I'd recommend reading through the `reselect` docs, but the key details of using props in selectors are:
* Memoization will break if different components share a normal selector, because different components have different props
* If you export a selector factory instead of a selector, memoization is fine again because there are multiple instances of the selector
* However, if you have a selector factory, you now need a …
> refactor(app): Refactor HTTP API selectors for usability

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
When a `pipette.move_to()` is called on the same well as before, it will run a `'direct'` path instead of an `'arc'` path, so that there are no pointless up-and-down motions when performing multiple commands within the same well.
> Api direct movements within well

- app/src/components/AppSettings/AppInfoCard.js
- app/src/components/AppSettings/AppUpdateModal.js
- app/src/components/AppSettings/index.js
- app/src/pages/AppSettings.js
Addresses #810 UI, adds the modal for app update but nothing more for now.
- Add `AppUpdateModal` to `AppSettings` with dummy actions for now
Uncomment lines 5 and 11 in app/src/pages/AppSettings.js to view modal.
> Add tentative update app modal

- components/.babelrc
- components/interfaces/default-containers.json.js
- components/src/deck/Plate.css
- components/src/deck/Plate.js
- components/src/labware-types.js
- components/src/styles/typography.css
Plate labels became way too big with some style breakage a while back. This brings them back (and refactors types a bit)
Tiny wells for 384
* Plate label font size fixed (both normal plates, and 384-format tiny labels)
* Add 'transform-class-properties' to `.babelrc` and refactor `Plate` to use this style instead of binding to `this` in constructor, which flow hates
* New `labware-types.js`, which will be moved into labware-definitions later?
> (complib) update Plate label styles

- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/__tests__/structure.test.js
- components/src/structure/LabeledValue.js
- components/src/structure/RefreshCard.js
- components/src/structure/RefreshCard.md
- components/src/structure/index.js
- components/src/structure/structure.css
Little PR to add a `RefreshCard` component. It's a `Card` with a refresh button in the corner that turns into a spinner when the card is refreshing. Also handles auto-refresh on mount or specific props change.
[Components Library - `RefreshCard`](https://s3-us-west-2.amazonaws.com/opentrons-components/complib_refresh-icon/index.html#refreshcard)
To be used in #698, #810, and anywhere else a `Card` is displaying data that needs to be fetched from somewhere.
- Feature: Added `RefreshCard` to display refreshable data
> feat(components): Add RefreshCard (Card for displaying refreshable data)

- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/WifiConnectForm.js
- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/wifi.js
- app/src/robot/api-client/discovery.js
This PR is (excluding polish) the last front-end PR for #698.
- Feature: added WifiConnectModal that shows up when `/wifi/configure` responds
- Refactor: renamed ConfigureWifiForm to WifiConnectForm for consistency
- Dev: defaulted local dev API to appear as a wired robot
Try it out! Otherwise standard review
> feat(app): Add failure/success modal after wifi connect response

- api/opentrons/server/endpoints.py
- api/tests/opentrons/server/test_wifi_endpoints.py
- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/WifiConnectForm.js
- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/http-api-client/__tests__/client.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/types.js
- app/src/http-api-client/wifi.js
~Currently blocked by #914. Will rebase the branch and the PR when it's merged.~
This PR closes #694 by adding join failure logic to the API and updating the Run App as necessary to handle the failure cases.
- Feature (API): Added error handling and statuses to /wifi/configure
- Refactor (Run App): Cleaned up HTTP response and error handling / types 
@btmorr and @Laura-Danielle please check out the Python side of things. My robot testing is still ongoing to be completed on Monday.
Otherwise, front-end stuff in this PR is fairly light, so standard review.
> feat(app, api): Handle WiFi join failure

- components/src/forms/DropdownField.js
- components/src/forms/RadioGroup.js
- protocol-designer/src/components/FilePage.css
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/FormSection.js
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/StepEditForm.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/containers/ConnectedMainPanel.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/index.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/types.js
- protocol-designer/src/navigation/reducers/index.js
- protocol-designer/src/types.js
- protocol-designer/src/utils.js
Closes #739 
* New 'file-data' atom to handle new form fields in File Page
* Clicking nav icons Page/Gear navigates to file page / design page (via ConnectedMainPanel)
* Changed Component Library input components to use `=> mixed` not `=> void` for onChange onClick etc handlers.
The pipette stuff is not in this PR - I have to factor out `InstrumentInfo` from app, it's identical in PD on the File Page.
NOTE: step forms do NOT disappear when you go back to file page. Later the page navigation action should cause that form to be canceled, since you're exiting that form when you navigate away
I tried to make Flow validate my form stuff as much as possible. The typing for this form gets applied in one place: `Props = {formConnector: FormConnector<FilePageFields>}` in `FilePage.js`
I reused the …
> (pd) File page form

- protocol-designer/src/components/FileSidebar.css
- protocol-designer/src/components/FileSidebar.js
- protocol-designer/src/containers/ConnectedSidebar.js
Closes #903 
FileSidebar component
No `onDownloadClick`: 
With `onDownloadClick`:
Give a truthy onDownloadClick prop to show the download button
* Is it useful to factor out that horizontal divider to component library? Do we use it in Run App?
> (pd) component-only FileSidebar

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
Add a parameter to `Pipette.pick_up_tip` for incremental distance during presses. This will cause the pipette to press by an additional N mm on each press (where N is a float value of the parameter), which will make it possible to experiment on the correct number of presses and press distance without requiring a code push for each iteration, and allow these to be specified in protocols if desired.
- (feature) Add `increment` parameter to `Pipette.pick_up_tip`
> Make pick_up_tip press incrementally further

- .eslintrc.js
- app/src/analytics/index.js
- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/components/TipProbe/UnprobedPanel.js
- app/src/components/setup-panel/InstrumentList.js
- app/src/http-api-client/health.js
- app/src/http-api-client/wifi.js
- app/src/interface/index.js
- app/src/robot/actions.js
- app/src/types.js
- components/src/buttons/Button.js
- components/src/deck/Plate.js
- components/src/modals/AlertModal.js
- components/src/modals/Modal.js
- components/src/modals/Overlay.js
- components/src/structure/PageTabs.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/step-generation/types.js
I was trying to work on health check and ran right into a flow wall. Rather than try to fix everything up in that feature branch, I gave [this article](https://blog.callstack.io/type-checking-react-and-redux-thunk-with-flow-part-2-206ce5f6e705) a read and made some flow tweaks and improvements as its own PR.
- Refactor: improved run app base redux types and enabled flow linting
Make sure linting still passes on your machine. It does on mine
> Improve redux flow types in the app and enable flow linting

- api/opentrons/containers/__init__.py
- api/tests/opentrons/containers/test_containers.py
`containers.create` should always save the definition, because otherwise it is not possible to use the created definition in a protocol, so `save=False` is a non-sense option. Fixes #915 
- (bugfix) Remove `save` parameter from `containers.create`, restoring expected functionality
> Remove save parameter on containers.create

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/ProtocolEditor.css
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/modals/MoreOptionsModal.css
- protocol-designer/src/components/modals/MoreOptionsModal.js
- protocol-designer/src/components/modals/NewFileModal.css
- protocol-designer/src/components/modals/NewFileModal.js
- protocol-designer/src/components/modals/modal.css
- protocol-designer/src/css/globals.css
Closes #904 
* `NewFileModal` - stateful form to populate brand new protocol file
* Fixed weird height issues with PD's high level layout (Navbar + Sidebar + (Header & Panel) -- before it would always scroll the height of the Panel + height of Header, and Navbar / Sidebar didn't ever reach the bottom
* Consolidated PD's modal styles -- `.modal` in `modals.css` gives 80% width
Must be run locally -- get rid of `false` in `ProtocolEditor.js`'s `{false && <NewFileModal onSave={console.log} onCancel={() => console.log('cancel!')}/>}` to see NewFileModal (it doesn't do anything but console.log on save in this PR).
Check out CSS - cleanup suggestions appreciated!
> (pd) NewFileModal comp; modal style cleanup

- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/modals/NewFileModal.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/containers/ConnectedFileSidebar.js
- protocol-designer/src/containers/ConnectedMainPanel.js
- protocol-designer/src/containers/ConnectedNav.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/containers/ConnectedSidebar.js
- protocol-designer/src/containers/ConnectedTitleBar.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/types.js
- protocol-designer/src/navigation/actions.js
- protocol-designer/src/navigation/reducers/index.js
- protocol-designer/src/navigation/selectors.js
- protocol-designer/src/navigation/types.js
Closes #905 
* Placeholder splash page for PD
* On initial PD blank slate state, can click "Create New" in SideBar to open NewFileModal
* Can cancel modal
* Can save modal to state
* With protocol loaded, can click "Create New" in SideBar to open a blank NewFileModal and create a new file alltogether (later ticket: all state should be wiped out on new file / load file)
* `updateFileField` -> `updateFileFields` to take object of keys instead of key, value (since now you can submit the whole form at once)
* Placeholder div and new string enum in `Pages` type for `'file-splash'` page
* ConnectedNav disabled until user creates a protocol (TBD: will it be disabled whenever NewFileModal is open, too?)
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_new-file-modal-submits/index. …
> Pd new file modal -- submits

- Dockerfile
- api/opentrons/config/feature_flags.py
- api/opentrons/containers/placeable.py
- api/opentrons/data_storage/database.py
- api/opentrons/data_storage/labware_definitions.py
- api/opentrons/data_storage/serializers.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/containers/test_containers.py
Add new labware definition behind feature flags. This PR is actually more about the feature flags than about the labware definition code (which is partially working, but can be refined incrementally). See `opentrons.config.feature_flags` for examples. Related to #764, but acting as a ticket for the feature flag model.
- (feature) Add feature flags module
- (feature) Use new labware definitions (unstable--only enable this feature for further developement) 
Tested on `moon-moon` with the feature flag both enabled and disabled, to ensure that new unstable code is not used when disabled.
> Add and use feature flag switch for new labware definitions

- components/src/buttons/buttons.css
- protocol-designer/src/components/FileSidebar.js
- protocol-designer/src/containers/ConnectedFileSidebar.js
- protocol-designer/src/file-data/index.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-data/selectors/fileFields.js
- protocol-designer/src/file-data/selectors/index.js
- protocol-designer/src/file-data/types.js
Closes #854
"Download" button appears, and user can download a JSON file.
Right now it just has blank/placeholder data, and the download button doesn't only show when there is a file to download.
* Added 2 lines to `buttons.css` in Components Library so that `<a>` buttons can render (I need <a> to trigger download)
* Factored out `file-data` selectors into their own dir with an `index.js`
Are changes to `buttons.css` ok?
You should be able to download a JSON file, and if you enter a protocol name / author / description it should show up in the file. The file name should match the name you entered.
Right now, this `createFile` selector is going to run every time any of its inputs change. Ideally this should happen lazily, and only actually run when the user clicks the download button - …
> (pd) download file with metadata; buttons.css resets for <a>

- app/src/http-api-client/__mocks__/health.js
- app/src/http-api-client/__tests__/health-check.test.js
- app/src/http-api-client/health-check.js
- app/src/http-api-client/index.js
- app/src/http-api-client/wifi.js
- app/src/index.js
- app/src/robot/actions.js
- app/src/robot/api-client/worker.js
- app/src/robot/selectors.js
- app/src/robot/types.js
- app/src/types.js
Alrighty. This PR starts work on #695 by building out the necessary logic to poll connected robots `/health` endpoints to make sure they're still up. The next PR(s) will:
* Swap RPC connection drop logic to health check logic
* Wired health check state to connection dropped alert modal
For this one: I've added a `health-check` library to the `http-api-client` module. It consists of:
* Four actions
* Two async ones: `api:START_HEALTH_CHECK` and `api:STOP_HEALTH_CHECK`
* Inform the middleware to start or stop a health check polling interval
* Three sync ones: `api:RESET_HEALTH_CHECK`, `api:SET_HEALTH_CHECK_ID`, and `api:CLEAR_HEALTH_CHECK_ID`
* Reset all health check state for a robot, save the `setInterval` id for a robot, and clear it, respectively
* Middleware
* Calls `setInterval`  + …
> feat(app): Add health check to http api module

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/dc_main.py
- api/opentrons/deck_calibration/endpoints.py
Adds first iteration of endpoints for factory calibration within the UI. Also changes code syntax so that the CLITool still functions as expected.
Begins work on issue #744
- Re-names factory calibration folder to 'deck_calibration'
- Pulls out 'position' and 'jog' functions from dc_main.py and application constants
- Adds 'start' and 'dispatch' endpoints
- 'Dispatch' function currently supports initializing pipette, selecting pipette and jogging current pipette
> Jog and position functionalities broke CLITool

- app/src/components/LostConnectionAlert/ModalCopy.js
- app/src/components/LostConnectionAlert/index.js
- app/src/components/LostConnectionAlert/styles.css
- app/src/components/Page.js
- app/src/http-api-client/__tests__/health-check.test.js
- app/src/http-api-client/health-check.js
- app/src/robot/api-client/client.js
- app/src/robot/selectors.js
This PR adds a very simple AlertModal if and when health check (#940) fails. It does not handle any disabling of links outside the modal, as may be necessary during a "global" (i.e. can appear on any page) alert like this.
Part of #695
* feat(app): Show AlertModal with instructions after health check failure 
Please keep an eye out for any times when clicking "Close" on the modal crashes the UI, or any times the modal doesn't pop up when it should.
Known issue: The alert modal doesn't play super nicely with our modal-like subpages. Will fix this up in a following PR.
Otherwise, @howisthisnamenottakenyet I kinda winged it on [the copy](https://github.com/Opentrons/opentrons/blob/app_disconnect-modal/app/src/components/LostConnectionAlert/ModalCopy.js) based on stuff in the screens. …
> feat(app): Show AlertModal with instructions after health check failure

- Makefile
[`flow-typed` updated its type definitions for redux](https://github.com/flowtype/flow-typed/pull/1731) and now _a bunch_ of our files are showing flow errors. This PR temporarily disables `flow` in CI until we can fix whatever flow is unhappy about and figure out how to avoid this in the future (probably by committing the `flow-typed` defs but maybe something else).
- Disabled `flow` in `make lint-js` CI task
Nothing special here
> ci(js): Temporarily disable flow typechecking in CI

- Makefile
- app/Makefile
- components/Makefile
- package.json
- protocol-designer/Makefile
- yarn.lock
Re-enable flow after #983. This is still looking pretty brittle so we may want to consider avoiding typing redux connected components until we can run this to ground a little farther.
- Upgrade flow to v0.66 (nicer messages)
- Lock flow-typed defs to flow@0.61.0 (gets us the old react-redux types that our code passes with)
- Re-enable flow in CI (reverts #983)
Run `make install` and make sure that `make lint` passes on your machine
> ci(flow): Upgrade flow, lock flow-typed defs to v0.61, re-enable flow

- app/src/components/App.js
- app/src/components/CalibrateDeck/ConnectedLabwareItem.js
- app/src/components/LabwareCalibration/InfoBox.js
- app/src/components/LostConnectionAlert/ModalCopy.js
- app/src/components/SetupPanel/InstrumentListItem.js
- app/src/components/SetupPanel/LabwareListItem.js
- app/src/components/TipProbe/ContinuePanel.js
- app/src/components/Upload.js
- app/src/components/nav-bar/NavButton.js
- app/src/components/setup-instruments/InstrumentTabs.js
- app/src/pages/Calibrate.js
- app/src/pages/SidePanel.js
- app/src/robot/api-client/client.js
This PR refactors the internal URLs used for the calibration page to better reflect the actual nav flow and to prepare for continuing cleanup work in the calibration UI state.
These URLs are not user facing.
- `/setup-intruments` -> `/calibrate/instruments`
- `/setup-deck` -> `/calibrate/labware`
Calibration flow should still work
This PR does not address wonky highlighting in the nav bar and the calibration side panel lists
> refactor(app): Refactor calibrate urls to reflect actual nav flow

- app/scripts/advertise-local-api.js
- app/src/robot/api-client/discovery.js
During the `make -C app dev` task, a little service is launched (`make -C app dev-mdns`) purely to check if you're also running `make -C api dev` and, if you are, advertise your API dev server via MDNS so the app can pick it up.
Changes made to the `dev-mdns` task in #551, while helpful for identification, seems like they were causing MDNS hostname collisions. On my mac, this resulted in a frequent automatic changes to my computer's hostname to try to avoid those collisions. That, in turn, broke the logic the app uses to detect if a given advertisement is coming from `localhost`.
This PR changes the advertised hostname (prepends `Opentrons at`) to avoid collisions and also ensures that advertisements are unpublished on `SIGINT`. This has cleared up the issues on my machine.
- Chore: …
> chore(app): Avoid hostname collisions in dev mdns advertisement

- app/src/components/App.js
- app/src/components/nav-bar/NavButton.js
Bugfix PR to fix a couple routing based regressions in the app
- Fixed crash on protocol upload with no pipettes (broken by #947)
- Fixed default redirect to /robots in prod build (broken by #984)
Please make sure that:
* Clicking on the "Calibrate" nav button takes you where you expect
* If you find bugs here I may ask to punt given the TODO item in this PR about moving that logic from the button to the page
* Uploading a protocol with no pipettes or no labware doesn't blow up the app
@umbhau I added you as a reviewer because you reported one of these bugs. Let me know if this clears things up: https://s3.amazonaws.com/ot-app-builds/ci-builds/opentrons-v3.0.0-mac-2018-03-08_15-54-app_fix-route-bugs-e99cd79.zip
> fix(app): Fix regressions introduced by #947 and #984

- components/src/instrument-diagram/InstrumentGroup.md
- components/src/instrument-diagram/index.js
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/pipetteData.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/fileFields.js
- protocol-designer/src/file-data/selectors/index.js
- protocol-designer/src/file-data/selectors/pipettes.js
- protocol-designer/src/file-data/types.js
Closes #971 and #968 
Refactor cleanup, setting pipettes was too closely tied to file fields.
* Factored out pipette selectors into `pipettes.js` from `fileFields.js`
* Took out pipette field setting from `updateFileFields` action, moved those fields to new `updatePipettes` action.
* User can create new protocol with any combo of pipettes (to leave a mount blank, you still need to explicitly set that pipette to "None" in the New Protocol File modal's pipette dropdown)
* User can see those pipettes in the InstrumentGroup once they click "Save" in New Protocol File modal
> (pd) add all possible pipettes to setup; show pipette InstrumentGroup

- app/src/components/setup-instruments/Instruments.js
- components/src/__tests__/instrument-diagram.test.js
- components/src/instrument-diagram/InstrumentGroup.js
- components/src/instrument-diagram/InstrumentGroup.md
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/containers/ConnectedFilePage.js
Fixes #1000 
Different props, but snapshot is the same
* Check out component library's `InstrumentGroup` example
* Think about whether this might break anything in the app
* If you want, check PD is the same as well
> (complib, app, pd) Update InstrumentGroup to take left/right props

- components/src/deck/Plate.js
- components/src/deck/Well.js
- protocol-designer/src/collision-types.js
- protocol-designer/src/components/IngredientPropertiesForm.js
- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/components/SelectionRect.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/containers/IngredientPropertiesForm.js
- protocol-designer/src/containers/IngredientsList.js
- protocol-designer/src/containers/LabwareContainer.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/__tests__/selectors.test.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/navigation/selectors.js
- protocol-designer/src/utils.js
In preparation for implementing liquid tracking (the RobotState timeline will soon also include `liquid` state that is updated by the command generator reducers just like tip tracking state), this PR refactors the `labware-ingred/` atom's state to maintain ingredient instances (a volume, in a well, in a labware) separately from ingredient groups (name, description, id, etc).
Also, `labware-ingred/` was written before we were using flow so this is part of the ongoing process to standardize and correctly type the state/data getting passed around in `labware-ingred/` -- here, I cleaned up and tested a good chunk of the selectors.
* stuff discussed above
* Slight modifications to Plate and Well prop types in component library
* By virtue of refactoring it, I fixed ingredient deletion (both …
> PD: ingredients have instances with volume, not an overall group volume

- protocol-designer/src/file-data/__tests__/commandsSelectors.test.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/step-generation/test-with-flow/dropTip.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures.js
- protocol-designer/src/step-generation/test-with-flow/replaceTip.test.js
- protocol-designer/src/step-generation/test-with-flow/robotStateSelectors.test.js
- protocol-designer/src/step-generation/types.js
Closes #956 
* Add `liquidState` key to `RobotState` type
* `getLabwareLiquidState` selector reshapes data from the labwareIngreds.ingredLocations reducer to match RobotState.liquidState.labware's shape (access with labwareId.well.ingredGroupId.volume instead of ingredGroupId.labwareId.well.volume)
* Pipette tips also have a place to hold liquid state: pipetteId.tipId.ingredGroupId.volume where tipId is 0-indexed tip number cast to string (for single-channel, just '0'. For 8-channel, '0' is the tip that would go into A1 of a 96-well plate, and '7' would go into well H1. They aren't called 'A' 'B' 'C' because 384 plates skip letters, so I went with zero-indexed numbers to identify the tips of a pipette.
PD should work the same.
If you look at the liquid state selector (Ctrl+F for …
> Pd liquid state in robot state

- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/utils.js
Pre-req for #957 -- `splitLiquid` utility function handles splitting out a given volume of liquid from a source to a dest. Takes equal parts of all ingredients in the source, assuming they're evenly mixed.
Also: `mergeLiquid` does the converse: add 2 liquids together entirely.
* Sanity check: this is how liquid splitting + merging works, right? (Aside from phase separation, which we cannot presently handle in PD liquid tracking)
* Tests cover all useful cases?
Note: `splitLiquid` might return an error object instead of throwing the error later - not sure yet
> (pd) added splitLiquid & mergeLiquid fns with tests

- app/src/components/RobotSettings/CalibrationCard.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- components/src/structure/Card.js
- components/src/structure/Card.md
- components/src/structure/structure.css
- components/src/styles/typography.css
This PR closes #937. Adds a non functioning factory calibration card to RobotSettings to later be wired up. 
- update card component to display optional description
- add factory calibration card to RobotSettings
standard review.
> Add factory calibration card

- CONTRIBUTING.md
- api/Makefile
Little API PR to ensure that Windows machines (and AppVeyor, specifically) can succesfully run `make wheel`
- Update api Makefile to use `shx` for cross-platform POSIX happiness
Please make sure `make wheel` and `make push` continue to work on your machines. I also added a `host` var to `make push`, so you can try it out with different hosts:
```shell
make push host=localhost:31950
```
Something to note: regular `curl` is not yet available in Windows (there is a version available in PowerShell, but it didn't seem to me to act like regular `curl`; ymmv), so I needed to `choco install curl`. You may need to, too. The good news, though, is that [eventually they will be available in cmd.exe in mainline Windows](https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to- …
> chore(api): Update Makefile to be more Windows friendly

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/drivers/test_driver.py
When a limit switch is hit during move, home the axis that caused the alarm to ensure that switches don't stay depressed. Fixes #939 
Also removed a deprecated method on robot that was not backed (this is not a _new_ breaking change, as calling that method would have raised an exception)
- (feature/fix) Add recovery home after a limit switch is hit during move
- tested on 🌔 🌔 
- unit tests are contract tests, not functional
> Recover from depressed limit switch during non-home commands

- app-shell/Makefile
- app-shell/README.md
- app-shell/electron-builder.json
- app-shell/lib/api-update.js
- app-shell/lib/main.js
This PR updates the `app-shell` Makefile and electron-builder config to build the API wheel file and bundle it in the app, respectively. It also adds a little proof-of-concept api updater module to ensure that the update file is accessible.
- Bundle API update wheel in desktop app
1. `make -C app dev`
2. Observe `[shell] api update files: [ 'opentrons-3.0.0-py2.py3-none-any.whl' ]` in the terminal
1. `make -C app-shell`
2. Launch production build
*   macOS: `./dist/mac/Opentrons.app/Contents/MacOS/Opentrons`
*   Linux: `./dist/linux-unpacked/ot-app-desktop`
*   Windows: `./dist/win-unpacked/Opentrons.exe`
3. Observe `api update files: [ 'opentrons-3.0.0-py2.py3-none-any.whl' ]` in the terminal
> feat(app-shell): Bundle API update wheel in desktop app

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/tools/write_pipette_memory.py
- api/tests/opentrons/drivers/test_driver.py
Make pipette read/write methods public on the driver. Also adds docstring to each method, as well as changes the `mount` arg to `"left"` and `"right"` just like how the rest of the API refers to mounts.
Some small changes were also required to `opentrons.tools.write_pipette_memory` to get it working with new methods/args.
> API: public driver methods for writing/reading pipette memory

- app/src/components/Page.css
- app/src/components/RobotSettings/AttachedInstrumentsCard.js
- app/src/components/RobotSettings/InstrumentInfo.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- components/src/structure/structure.css
This PR addresses #862 (UI only). Adds an `AttachedInstrumentCard` and `InstrumentInfo` to the robot setting app. The splitting of these components is necessary to account for some styling one-offs.
Both left and right pipettes detected. Also note the main page area is now scrollable (separate from overflow y scrollable in the sidebar)
Right pipette not detected, mount present in data, not volume or channels. Totally tentative for now.
- Implement styled AttachedInstrumentCard with mock data
- Note this is all highly speculative data that assumes attachedInstruments
always returns at least a left and right object with at least a mount
- Update page.css to allow for scrolling in main page area of app
- Update labeled value styles to use smaller font size for layout purposes,
lots of zany …
> App add attached pipettes card

- components/Makefile
- labware-definitions/Makefile
- protocol-designer/Makefile
We are getting failed builds sporadically in Travis that can always be fixed by just restarting the build.
I think it is this open issue in Jest: "Flaky failure mode" https://github.com/facebook/jest/issues/1874
Since it's a nondeterministic error, it's hard to reproduce. So this PR disables jest's parallelism with the `--runInBand` arg, and we can watch our builds to see if that fixes the error.
These errors look like:
```
make -C components test
make[1]: Entering directory `/home/travis/build/Opentrons/opentrons/components'
cross-env NODE_ENV=test jest \
--coverage=true \
--watch=false \
--updateSnapshot=false
FAIL  src/__tests__/structure.test.js
● Test suite failed to run
/home/travis/build/Opentrons/opentrons/components/src/structure/TitleBar.js:24
}});
^
SyntaxError: Unexpected …
```
> Disable jest parallelism: add --runInBand option to all jest calls

- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/blowout.test.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
- protocol-designer/src/step-generation/test-with-flow/dropTip.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtureGeneration.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures.js
- protocol-designer/src/step-generation/test-with-flow/replaceTip.test.js
- protocol-designer/src/step-generation/test-with-flow/robotStateSelectors.test.js
- protocol-designer/src/step-generation/test-with-flow/touchTip.test.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
Closes #957 
* Single and 8-channel support
* Multiple ingredients supported - assumed to be uniformly mixed
* Well liquid state, and tip liquid state is updated on aspirate
* Track air being aspirated from a source with less volume than the aspirate volume
In writing new liquid state tests I started tripping over all my verbose copy-and-paste fixtures so I cleaned some things up:
* started heavily using `lodash/merge` to make small variations of test fixtures (eg, same as initial state, except tip A1 is `false` under `tipState.tipracks.tiprack1Id`). This fn mutates the obj in its first argument, so I need to be careful to always do give a new obj as its first arg `merge({}, baseFixture, updateObj)`
* had a problem with hard-to-find mutation of `filledTiprackWells` and `emptyTiprackWells` …
> PD: Liquid tracking for aspirate

- .gitignore
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/__init__.py
- api/opentrons/server/endpoints/control.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/endpoints/wifi.py
- api/opentrons/server/main.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/server/test_control_endpoints.py
- api/tests/opentrons/server/test_update_endpoints.py
Add endpoint to get model strings for attached pipettes (fixes #998)
Also reorganize endpoints into sub-modules to make it easier to find functions (no behavioral changes).
- (feature) add endpoint to get model strings for attached pipettes
- (refactor) reorganize endpoint functions into sub-modules
> Add endpoint for reading pipette model info and organize endpoint files

- Dockerfile
Adds `alsa-utils` to the Dockerfile. This gives us control over audio output, as well as a tool for QC'ing machines' speakers.
To test speaker from Resin Terminal or when ssh'ed into machine:
```
$ speaker-test
```
That will play pink-noise from speaker until quit using `Ctrl-C`
> Api: Speaker-test

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/tools/write_pipette_memory.py
Return values for `driver.read_pipette_id` and `driver.read_pipette_model` have changed to a dict. This PR changes `opentrons.tools.write_pipette_memory` to accept these new return values. Also, this PR allows multiple pipettes to be written to without needing to restart the script.
> API: refine write-pipette-memory script for new return values

- Dockerfile
- api/opentrons/tools/test_camera.py
This adds a QC test for the USB-Camera and USB-Flash drive.
Running:
```python
python -m opentrons.tools.test_camera
```
What it does:
1) Uses `ffmpeg` to record 1-seconds of video, saving to mp4 file
2) Mounts an attached USB drive, then copies the mp4 file to it and back
3) Starts a simple server, so that the tester can view the generated mp4
4) Erases the mp4 file at exit
> Api: QC camera and USB flash drive

- compute/README.md
- compute/scripts/start.sh
Add command to run user boot scripts during start. This is most immediately related to networking issues with the Stanford team
- (feature) Run user boot scripts during start
- (docs) Update compute readme
> Add command to run user boot scripts and update compute docs

- app-shell/lib/api-update.js
- app-shell/lib/main.js
- app-shell/package.json
- app-shell/yarn.lock
- app/__mocks__/electron.js
- app/package.json
- app/src/http-api-client/__tests__/client.test.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- app/src/robot/api-client/discovery.js
- yarn.lock
Part of #813 
This PR adds action creators to call `/server/update` and `/server/restart`.
This PR blocks:
- #1055 
- #1056
- #1057 (**Use this PR for e2e testing**)
- #1058 (**Also good for e2e testing**)
- Updated `electron` to latest
- Added method to app-shell's `api-update` method to read `whl` blob
- Created `http-api-client/server` module with action creators for `update` and `restart`
- Modified `http-api-client/client` to handle `multipart/form-data` bodies
This one is kinda hard to test at the moment (because no UI) and there's a lot of follow-up to do. Given timing I may ask to punt on some stuff.
That being said, any sort of sanity checks are good (e.g. "does the app still launch on my machine?"; "does this code look reasonable?"), and from my testing the `/server/update` call …
> Add API client actions for /server/update and /server/restart

- app-shell/lib/api-update.js
- app/__mocks__/electron.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
Part of #813
This PR adds update availability tracking to the robot state and wires the robot info card in the robot page to that state.
Update available is calculated on every successful health check, which means it'll be checked every time the robot page is opened (and the info card is refreshed) and constantly while connected (due to the periodic health check).
~_Base branch of this PR to be swapped to `edge`on when unblocked_~ Unblocked
This PR blocks:
- #1056
- #1057 (**Use this PR for e2e testing**)
- #1058 (**Also good for e2e testing**)
- feat(app): Add update available state and wire to robot info card 
Standard review. You can check view this logic in action by bumping the `version` field in `app-shell/package.json`, connecting to the API dev server, and observing that the …
> feat(app): Add update available state and wire to robot info card

- app-shell/electron-builder.json
I updated the dev version of electron in #1051 but completely forgot to also update the prod version in `app-shell/electron-builder.json`, which resulted in the prod build being completely unable to launch:
This PR fixes that oversight
- fix(app-shell): Fix dev/prod electron version mismatch
Ensure the prod version of the Run App launches on your machine. See `CONTRIBUTING.md` on how to build/launch the prod version or use the build links from Slack
> fix(app-shell): Fix dev/prod electron version mismatch

- protocol-designer/src/step-generation/dispense.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/utils.js
Closes #1054 
Liquid tracking in PD supports `dispense`.
* Slight changes to fixture generator fns to be easier to use and hopefully more expressive (eg, if I don't care about `destPlateType`, I leave it out when making my fixture)
* Unlike aspirate which is all in one function, I wrote a private `_updateLiquidState` in `dispense.js`, which the main `dispense` fn calls. This makes testing a lot easier. I think I'm going to factor tip state, liquid state, and command creation all apart for these commands to make them more testable. I should have thought of that earlier!
* `mergeLiquids` no longer throws warning, just ignores `__air__` key in calculating its volume. Error/warning reporting for things like "you aspirated from a well that is supposed to be empty" or "you dispensed more liquid …
> PD liquid tracking: Dispense

- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/server.js
Part of #813
This PR adds request/response state tracking for the two `/server` endpoints. This state will be used to drive the modal copy, button state, and spinners as (mostly) described by 813.
_Base branch of this PR to be switched to `edge` when unblocked_
This PR blocks:
- #1057 (**Use this PR for e2e testing**)
- #1058 (**Also good for e2e testing**)
- feat(app): Add request/response state for /server/[update,restart] 
This one is another hard one to verify because the UI isn't in place yet. Next PR will add that, so for now a code sanity check would be good. I'm pretty satisfied with the unit tests on this one.
> feat(app): Add request/response state for /server/[update,restart]

- app-shell/lib/api-update.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateModal.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- components/src/buttons/Button.js
- components/src/structure/structure.css
Part of #813 
This PR adds an MVP robot update modal in place. It does not react to state (besides showing when you click the "Update" botton in the `InformationCard`), but it does have buttons wired up for both `/server/update` and `/server/restart` so you can test the client work in #1051 end-to-end.
_Base branch of this PR to be switched to `edge` when unblocked_
This PR blocks:
- #1058
- feat(app): Add MVP robot update modal 
This is a good PR for actually testing the plumbing work for the blocking PRs.
**Question**: is the app supposed to try to only allow updates via ethernet (USB)?
- Ping @umbhau @btmorr @pantslakz @howisthisnamenottakenyet  
This will work with `make -C api ENABLE_VIRTUAL_SMOOTHIE=true`, but after you're done testing you'll need to run `make -C api install` to …
> feat(app): Add MVP robot update modal

- app/src/components/RobotSettings/UpdateModal.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- components/src/modals/AlertModal.js
Last PR of #813 
This PR wires up `/server/:path` request state to the robot update modal to determine what message to display and what the buttons do. Along with #1057, you can use this branch to verify robot update end-to-end.
_Base branch of this PR to be switched to `edge` when unblocked_
- feat(app): Wire request states to robot update modal
This is another good PR for actually testing the plumbing work for the blocking PRs
This test process is very similar to (and adapted from) the test checklist from #1057 
This will work with `make -C api ENABLE_VIRTUAL_SMOOTHIE=true`, but after you're done testing you'll need to run `make -C api install` to undo the effects of the update process.
To see the app send requests, use the "Network" tab of the devtools. To check out the state, use the …
> feat(app): Wire request states to robot update modal

- components/src/__tests__/__snapshots__/lists.test.js.snap
- components/src/__tests__/__snapshots__/nav.test.js.snap
- components/src/__tests__/lists.test.js
- components/src/buttons/Button.js
- components/src/lists/TitledList.js
- components/src/nav/SidePanel.js
- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/steplist/actions.js
- protocol-designer/src/steplist/reducers.js
Closes #961
Closes first part of #1049:
> Whole card is highlighted when hovering over card header
Mousing over a Step on the Step List highlights it, setting the liquid state display. This highlighting/mouseover behavior is new in this PR.
If no Step is highlighted, the selected step (last one that was clicked on, or newly-created one) sets the liquid state display.
The liquid state for the highlighted or selected step is pulled from the robot state timeline, and displayed on the deck.
Currently not supported: wells with multiple ingredients are supposed to turn gray, instead they take on the color of one of their ingredients (arbitrary). Todo in another PR.
* `SidePanel` & `TitledList`: added onMouseEnter & onMouseLeave props
* `HOVER_ON_STEP` action hooked up to `onMouseEnter` + …
> PD Liquid Tracking: Display liquid state timeline

- app/src/components/SetupPanel/InstrumentListItem.js
- app/src/components/SetupPanel/LabwareListItem.js
- app/src/components/SetupPanel/styles.css
#1074 broke the calibration lists because `InstrumentListItem` and `LabwareListItem` were relying on the `ListItem` child wrapper to render properly. This PR keeps `ListItem` generic and adds the wrapping div + styling to InstrumentListItem and LabwareListItem directly
- fix(app): Fix calibration list styling broken by #1074 
Standard review. Sorry for not catching this myself prior to 1074 merge; it was a pretty obvious break.
> fix(app): Fix calibration list styling broken by #1074

- app/src/components/nav-bar/NavButton.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- components/src/__tests__/__snapshots__/nav.test.js.snap
- components/src/nav/NavButton.js
- components/src/nav/navbar.css
This PR closes #806 by adding the notification dot to the Nav Bar
**No update available**
**Update available**
- feat(app): Add selector that returns true if any robot is updatable
- feat(components): Cleanup NavButton and add notification prop
- I switched `NavButton` from `button` to `@opentrons/components::Button`
- In the future we should consolidate styling, too
- feat(app): Display notification in navbar if robot update available 
Standard review! @IanLondon can you triple check my NavButton changes don't mess with PD. Otherwise I think there's continuing work that needs to happen with the app's NavBar architecture, so feel free to point anything out because it may be easy enough to tack on here.
> Add notification to Robots icon if robot update available

- api/Makefile
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/mover.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/control.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_control_endpoints.py
Add HTTP endpoints needed for move, with info for moving a pipette to attach tip position and moving a mount to correct position for swapping pipettes (correct positions determined experimentally). Fixes #1017 and fixes #1009 
- (feature) Add endpoint with info for correct position data
- (feature) Add move endpoint for both pipette and mount targets
- (bugfix) Add port back into api `make push` command
- (feature) Add api `make restart` command
Mount move is still questionable. Both modes need to be tested on a robot.
> Add position info and move endpoints

- app/src/components/ConnectPanel/RobotItem.js
- app/src/components/ConnectPanel/index.js
- components/src/structure/structure.css
Minor robot settings page cleanup
- Fix incorrect button sizing in `Card`s
- Fix robot list highlighting broken by #1074 
- Missing `withRouter`... my bad (again)
Standard review. Ensure the robot list highlights properly when you click robots and that the buttons in `Card`s are uniform (and the refresh buttons are square).
This will mess-up the currently commented out pipette card, but I have fixes for that in an upcoming PR.
> fix(app): Fix wrong Card button sizing and stuck robot list highlight

- protocol-designer/src/components/StepItem.css
- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/components/TransferishSubstep.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Closes #972 
New styles for step item
* Still have placeholder ING1 ING2 ingredients
* Still does not correctly break large volumes into small volumes (these substep rows are a cartoon version of the real command generation, it doesn't show every aspirate/dispense but only some of them, so it needs its own miniature implementation of volume splitting)
* Restyle step item & substep item to match design: transfer & consolidate (not distribute)
* Show source and dest labware names
* Support notes (add from the "more options" modal)
* Clean up selectors a bit
nothing special
> (pd) restyle & show volumes + labware names in step item

- protocol-designer/index.html
- protocol-designer/package.json
- protocol-designer/webpack.config.js
- yarn.lock
The API that backs the google-fonts-webpack-plugin is [down as at the time of writing](https://github.com/majodev/google-webfonts-helper/issues/46) and [breaking our builds](https://travis-ci.org/Opentrons/opentrons/jobs/358204047#L1504). This PR removes the plugin from the PD build pipeline in favor of just using `fonts.google.com` to get our builds back to green.
We can reevaluate how we want to handle webfonts with PD once @IanLondon is back.
- build(pd): Remove google-fonts-webpack-plugin 
Please ensure `make -C protocol-designer dev` and `make -C protocol-designer build` still run on your machine, and that there's no font-based regressions between [edge's build](https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/edge/index.html#/) and [this branch's …
> build(pd): Remove google-fonts-webpack-plugin

- api/opentrons/config/feature_flags.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/main.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/robot/test_robots_config.py
- api/tests/opentrons/server/test_update_endpoints.py
Refactor feature flags to use persistent data instead of environment variables because of unpredictable/undesirable behavior in Resin, and a couple of trivial fixes
- (refactor) Make feature flags use persistent data instead of environment variables
- (chore) Remove some dead code and update comment imports in robot
Tested on 🌔 🌔  and demo'ed to @Kadee80
> Refactor feature flags

- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_calibration_endpoints.py
Adds protections to the deck calibration start endpoint to protect against accidentally starting a new session over top of an existing one, with flag to be able to force override. Fixes #1010 
- (feature) Add protections to deck calibration start endpoint, with force override
- (feature) Add release endpoint for end of calibration
- (chore) Clean up some request handling syntax
Check to make sure routes, verbs, and bodies make sense
> Institute Robot's Rules of Order

- app-shell/Makefile
- app-shell/dev-app-update.yml
- app-shell/electron-builder.json
- app-shell/lib/update.js
- app/__mocks__/electron.js
- app/__tests__/util.js
- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/http-api-client/client.js
- app/src/reducer.js
- app/src/shell/__tests__/shell.test.js
- app/src/shell/index.js
- app/src/types.js
This PR adds app update state tracking to the app-shell and app. It does not cover any UI. Initial state work for #810 and #811.
- feat(app-shell): Tweak artifact name and add update module
- Branch is now always present in the filename for non-tagged builds
- Allows us to differentiate between a regular CI build and a release CI build
- `Opentrons-v3.0.0-beta.2-mac-b1234.zip` vs
- `Opentrons-v3.0.0-beta.2-mac-b1234-edge.zip`
- feat(app): Add shell module to redux with app update state 
Standard review! Added some (temporary) global hooks for testing:
1. `make -C app dev`
2. Open the app devtools
3. Observe state in "Redux > State" tab
4. In the devtools console: `> store.dispatch(checkForShellUpdates())`
5. Close app
6. Modify `app-shell/package.json :: version` to be lower than …
> feat(app, app-shell): App update state tracking

- app/src/components/LabwareCalibration/InfoBox.js
- app/src/components/calibration-info.css
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
This PR closes #1036. After final labware is calibrated,  [calibrate] button changes to [drop tip and proceed to run]. 
- Add return tip actions and response actions
- Implement return tip in infobox
- Tested on son of moon moon
Standard review, test on robot please. @btmorr and I tested together on son-of-moon-moon in person.
> On last calibrated labware, drop tip and proceed to run

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/server/main.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_calibration_endpoints.py
Add "save z" endpoint to factory calibration dispatcher. Fixes #950 
- (feature) Add "save z" command to factory calibration endpoints
- (refactor) Move methods to functions and improve testing style
> Add save_z endpoint and revise endpoint style

- protocol-designer/index.html
I absentmindedly made a change to how `bundle.js` and `bundle.css` were loading in protocol designer's `index.html` from relative paths to absolute paths in #1093. This [broke](https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/edge/index.html) the `s3` deploy of protocol designer.
This PR reverts that change.
- fix(pd): Revert bundle src switch from relative to absolute 
Make sure the s3 deploy of protocol designer works for this branch: https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_fix-s3-deploy/index.html (after CI completes)
> fix(pd): Revert bundle src switch from relative to absolute

- api/opentrons/api/calibration.py
- api/tests/opentrons/api/test_calibration.py
Quick fix to calibrate flow to prevent crash when switching a robot to calibrate to bottom
- (fix) calibrate to bottom move goes to top of well and then user should jog to bottom
> Go to top of well at beginning of calibration motion

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/server/test_calibration_endpoints.py
Add endpoints for attach tip, detach tip, and save xy. Fixes #952 and fixes #1122 
- (feature) Add "save xy" endopint
- (feature) Add "attach tip" and "detach tip" endpoints
- Take a look at packet shape and validation and make sure it makes sense.
- Is attach/detach deck calibration specific activity, or should it be moved to the "control" endpoints like "move_to"? On one hand, the general action should probably be "pick_up_tip" from a tiprack, but on the other there are things like tip probe that also have "attach tip" separate from a tiprack
> Add endpoints for attach/detach tips and save xy

- app/src/http-api-client/__tests__/pipettes.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/pipettes.js
This PR adds app state for API's `GET /pipettes`
- feat(app): Add pipettes module to http-api-client redux module 
This doesn't work on Virtual Smoothie, and the UI is still WIP, so:
1. Launch `make -C app dev`
2. Open Devtools > Console
3. Grab a robot object
1. `> store.getState()`
2. expand object to `robot.connection.discoveredByName`
3. Right click on the robot you're testing with and select "Store as global variable"
4. Note the variable name (e.g. `temp1`)
4. `> store.dispatch(fetchPipettes(temp1))`
5.  Go to "Redux" tab
@btmorr and @Laura-Danielle at the moment we get the unhelpful default aiohttp `500` response on virtual smoothie. I don't know if we want to support this endpoint on virtual smoothie (it makes front-end dev harder if we don't), but perhaps we could look into doing …
> feat(app): Add pipettes module to http-api-client redux module (WIP)

- protocol-designer/src/components/StepCreationButton.css
- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/containers/StepCreationButton.js
Closes #963 (which was mostly closed by #1075) by restyling the "ADD STEP" button to have it appear above the END step, and popover the END step when expanded.
* "Add Step" is less wide, to match design
* "Add Step" lays over END step when expanded
* `onMouseLeave` collapses "Add Step" (click elsewhere behavior is broken, is probably not necessary?)
* Factor out StepCreationButton container to separate component, add css, properly type mapStateToProps + mapDispatchToProps
Nothing special, try it out
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_add-step-popover-style/index.html
> restyle StepCreationButton; break out into component from container

- app-shell/electron-builder.json
- app-shell/package.json
- app/package.json
- app/webpack.config.js
Little chore PR to make sure the app uses a consistent title throughout the browser title and Electron menus.
- chore(app,app-shell): Use consitent app title 
Launch the app, make sure the app title + the name in File, etc. menus is "Opentrons" rather than "OT App", "@opentrons/app-shell", or anything else weird like that
> chore(app,app-shell): Use consitent app title

- app/src/components/RobotSettings/AttachedInstrumentsCard.js
- app/src/components/RobotSettings/InstrumentInfo.js
- app/src/components/RobotSettings/index.js
- app/src/components/RobotSettings/styles.css
- app/src/http-api-client/index.js
- app/src/http-api-client/pipettes.js
This PR contains the UI implementation of #862
- feat(app): Enable pipettes card and drive it with API state 
See #862 for test plan. Stuff to note:
- ~The `/pipettes` API **does not work with virtual smoothie**~
- Fixed by #1134 
- The screens list an example pipette as (e.g.) "*-channel P300"
- At the moment all we get back from the API is a model id, e.g. "p300_multi"
- i.e. we don't get number of channels nor volume
- Rather than parsing it out the model string, I decided just to display it with the `_` replaced with a space, e.g. "p300 multi"
> feat(app): Enable pipettes card and drive it with API state

- api/opentrons/deck_calibration/dc_main.py
- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/test_calibration_endpoints.py
Add endpoint to save calibration data, and add move targets to positions info endpoint. Fixes #951 and fixes #953 
Behavior:
- `move_to`s for the 3 calibration points will move to a point that is 5mm toward the middle of the deck in x and y, and 10mm above the deck in z.
- starting calibration will *NOT* clear out config.json file on disk
- at *END* of calibration, config.json file is overwritten and a backup of the new config is created with a timestamp
- if calibration is ended prematurely, the robot should be restarted, since the in-memory gantry calibration was reset to default. Restart will restore the previous factory calibration.
- (feature) Add HTTP endpoint to save deck calibration data
- (feature) Add info to positions endpoint for calibration point `move_to`s
- (feature) Backup …
> Api save calibration endpoint

- app/src/components/ConnectPanel/connect-panel.css
- app/src/components/ConnectPanel/index.js
This PR closes #1024. Moves refresh button/spinner on connect panel above the robot list. It also adds some spacing between robot items and the slight box shadow to match design screens.
- shrink spinner size
- move spinner/button before robot list
- add spacing between robot items (addresses design comment)
Standard Review.
> Connectivity: Move Refresh and Spinner to Top

- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/constants.js
- protocol-designer/src/containers/LabwareContainer.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/file-data/__tests__/commandsSelectors.test.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/labware-ingred/__tests__/selectors.test.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/dispenseUpdateLiquidState.js
- protocol-designer/src/step-generation/dropTip.js
- protocol-designer/src/steplist/reducers.js
Closes #1083 
Highlighting over a step will show labware & wells involved in that step, and still shows the liquid state at the beginning of that step.
This supports consolidate right now. Once transfer command is built, there is groundwork for that too.
Example: consolidating from deep well to 96 flat:
* Stuff above
* Use constant for fixed trash ID.
Try it out, make sure to include a tip rack and to only use consolidate. Try it with single-channel and 8-channel, make sure it works as you'd expect.
> Pd hover to see labware and wells

- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/styles.css
- app/src/components/RobotSettings/AttachedInstrumentsCard.js
- app/src/components/RobotSettings/InstrumentInfo.js
- app/src/components/RobotSettings/styles.css
- app/src/pages/Robots.js
This PR addresses #860. 
- User initiates a pipette attachment or change via button.
- Alert modal tells them to remove labware and tipracks
- User is able to cancel or ~continue with pipette change~
- change/attach button now link
- route to initial alert modal `/robots/:name/pipettes/:mount`
- back button functional,  continue wit move to front to be addressed in later PR
Standard Review. 
- Go to connectivity panel
- view any robot
- click attach/change button modal with warning message should render, back button should bring user back to robot settings page, continue button disabled.
> Add change/attach pipette warning modal

- protocol-designer/src/components/StepEditForm.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/aspirateUpdateLiquidState.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/dispenseUpdateLiquidState.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/mix.js
- protocol-designer/src/step-generation/robotStateSelectors.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/transfer.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formProcessing.js
- protocol-designer/src/steplist/types.js
Implements the "Transfer" step: now transfer steps update tip/liquid state in RobotState, and generate commands.
Closes #720 
NOTE: "delay", "air gap", and "disposal volume" form fields are not yet supported in either Consolidate or Transfer. For delay, it will be implemented when the Pause Step is implemented. For air gap / disposal vol, we still have yet to determine what exactly their behavior will be in some edge cases.
Also you'll see that Consolidate and Transfer form processing/validation share some code. I'm planning to be more DRY and concise once there are a few more Steps implemented.
* minor types cleanup
* implement transfer form parsing and command generator `transfer.js`
* reusable `mix.js` utility fn for command generators (factored out of `consolidate.js`)
* make some …
> PD: Transfer step

- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/opentrons/server/main.py
- api/opentrons/util/environment.py
- api/opentrons/util/log.py
To help debugging both hardware and software issues, this PR logs all messages written to and read from the serial port to a file.
Also adds an additional `'\r\n'` to the end of each message sent, to ensure that all responses read in end with `'ok\r\nok\r\n'`
> Api: log all serial data written/read over uart to file

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
This PR is meant to change assert statements -> log.warning statements in regards to pipette tips.
- Changes assert 'tip_attached' to log.warning messages
- Removes tests on assert statements
> Changes tip asserts to warning messages

- protocol-designer/src/components/StepItem.css
- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/components/TransferishSubstep.js
- protocol-designer/src/file-data/selectors/pipettes.js
- protocol-designer/src/steplist/formProcessing.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Closes #1095 
"Substeps" are the rows within a StepItem on the StepList. Each substep represents aspirate & dispense commands inside a step (it's not the literal aspirate/dispense commands, but a "cartoon" of them, because including all aspirates/dispenses for mix and blowout etc would make substeps lengthy & hard to read).
This PR introduces "substep groups" for steps using an 8-channel pipette - a "substep group" expands each substep into a group of 8 rows, 1 for each tip. These groups are collapsible.
More fun example with 96 to 384 well matchup:
* generateSubsteps supports multi-channel substep data format for:
* transfer
* consolidate
* minor style updates for StepItem (icon always `->` btw labware, left-align ASPIRATE/DISPENSE)
* Try transfer & consolidate with 8-channel -- do they …
> PD Multi-channel substeps in step list

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
Fixes #1028 where the pipette.delay() command was timing out past 60 second intervals.
- Utilizes robot.pause(), robot.resume() and time.sleep() to perform timed delays
instead of the built in delay function from the driver.
- As a residual effect, adds in 'Pausing robot operation' and 'resuming robot operation' under
published commands for delay.
- Adds a test to ensure that pipette.delay is calling robot pause/resume
Tested on Young 🌔 using the following protocol:
```
from opentrons import containers, instruments
p200rack = containers.load('tiprack-200ul', '4')
source_plate = containers.load('96-PCR-flat', '11')
dest_plates = [
containers.load('96-PCR-flat', '3'),
containers.load('96-PCR-flat', '6'),
containers.load('96-PCR-flat', '9'),
containers.load('96-PCR-flat', '8'), …
```
> Fixes delay timeout error

- protocol-designer/src/components/StepItem.css
- protocol-designer/src/components/StepList.js
- protocol-designer/src/components/TransferishSubstep.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/steplist/actions.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
Closes #1049 
(Screencap note: resize jitter on substeps should be fixed. But it still exists on the Step card, since that's using TitledList's `selected` prop)
This highlights substeps when you hover over them. Should work for both single-channel and multichannel style substeps -- for multi, the whole 8-channel/8-row group is a single "substep" and gets highlighted as one thing.
* action, reducer, selector, and relevant props for hoveredSubstep to work
* Updated types for `ConnectedStepList` -- they were just implicitly typed before, I think this was originally typed when I was newly adapting Flow.
* Try consolidate / transfer with single/multi channel, substeps should highlight when you mouseover them. Whenever substeps are hovered, the big-box-highlight for the step is not shown, but …
> Pd select substep hover

- api/opentrons/__init__.py
- api/opentrons/instruments/pipette_config.py
- api/tests/opentrons/labware/test_pipette.py
This PR adds constructors for all available OT2 pipettes. Values for pick-up-current, and plunger-positions, are not final, but are still up to change from testing.
In addition, **all plunger positions have been shifted upwards 1 mm other that "top"**. This is because the homing switches are being changed to a new supplier, which has a 1mm lower engagement point. By shifting all pipette plunger positions up 1mm, we do not lose enough volume to drop below the pipette's advertised limit (`/tests/opentrons/labware` is ensuring this), and also **does not affect any accuracy findings** from our tests. Fixes #1133 .
> Api: add other pipette models, and shift plunger positions 1mm

- app/src/components/ChangePipette/RequestInProgressModal.js
- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/styles.css
This PR adds (currently hidden) InProgressModal to ChangePipette. 
Addresses #860
- (Feature) add in progress screen as `InProgressModal` to ChangePipettes
- Currently resides in ChangePipette
- Takes title, subtitle, and message a props for reuse later in tip probe
To view `InProgressModal` change line 64 in `app/src/components/ChangePipette/index.js
from: 
```
if (moveToFrontRequest.inProgress) {
```
to:
```
if (!moveToFrontRequest.inProgress) {
```
> Add RequestInProgressModal to ChangePipette

- app/src/http-api-client/__tests__/robot.test.js
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/robot.js
This PR adds redux plumbing to call `GET /robot/positions` and `POST /robot/move`. Part of #860.
- feat(app): Add action creator and reducer for POST /robot/move API
This PR includes debugging code to be removed by the UI wire-up PR. To test this on a robot:
1. Launch the app
2. `> store.getState()`
3. Expand the state object up to and including `state.robot.connection.discoveredByName`
4. Right click on the robot you're testing with and select "Store as Global Variable"
* Will store as `temp1`
Examine the state in the "Redux" tab for `state.api.robot[robotName]`
> feat(app): Add action creator and reducer for POST /robot/move API

- components/src/buttons/buttons.css
- components/src/lists/lists.css
- components/src/styles/borders.css
Currently, TitledList has no border, so when it is `selected` and acquires a 2px border it gets resized.
This PR gives TitledList a transparent 2px border so toggling `selected` doesn't resize its contents.
Also while I was at it, I got took the `2px` for button's border-radius and another `2px` for TitledList's border width and made them both into variables in `borders.css`
.
This should remove the resize-jitter when you mouseover across steps in the StepList in PD, and the only change in Run App should be a tiny bit more spacing around the `TitledList`s in the calibration screen sidepanel. (Also in complib you should see that selecting/deselecting TitledList no longer resizes it.)
> complib: TitledList doesn't resize-jitter when 'selected' is toggled

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/steplist/types.js
Closes #1096 
Shows source/dest wells for single/multi channel transfer/consolidate steps, when you mouseover a substep.
* When a substep is hovered in the Redux state, the `_getSelectedWellsForSubstep` selector-helper fn is used to pull out source/dest wells for each labware for that step.
Play around with it, see if you can break it, some different cases are:
* Source and dest in the same labware vs 2 different labware
* single vs multi channel step
* transfer vs consolidate
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_show-wells-for-substep/index.html#/
> pd: show wells for substep

- app/src/components/ChangePipette/CheckPipettesButton.js
- app/src/components/ChangePipette/ConfirmPipette.js
- app/src/components/ChangePipette/index.js
- app/src/components/RobotSettings/AttachedInstrumentsCard.js
- app/src/components/RobotSettings/InstrumentInfo.js
- app/src/http-api-client/index.js
- app/src/http-api-client/pipettes.js
- app/src/http-api-client/robot.js
This PR connects the UI and state for Attach Pipette flow from Robot settings page. 
- User clicks [attach] and is prompted to clear deck alert
- User clicks [move pipette to front] and in progress screen/message displays
- Once pipette has moved to attach/detach front position, user is prompted to select new pipette to attach
- On selecting a pipette the corresponding attach diagrams/text display
- [Have robot check connection] checks attached vs expected attached pipettes, results in error screen or success 
addresses #860 #862 #863 #864 
- Add `moveToChangePipette` action to `ClearDeckAlertModal
- Add `clearRobotMoveResponse` action  to `IntrumentInfo` button
- Add `confirmPipette` action to `ConfirmPipette`
- TODO in subsequent PRs: 
- Add home action/ to exit buttons
- Refactor …
> Connect robot actions and state to AttachPipette UI

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
This will require a hardware fix, but on Moon-Moon the pipettes are able to be consistently read after fully disengaging the motors. This is a hardware error that should be addressed asap.
> API: disengages all motors when reading from pipette

- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/tests/opentrons/drivers/test_driver.py
Smoothieware has gotten into this weird state where it will repeat the command sent to it, followed by it's own response. None of the GCode commands we use would ever expect to see the sent command within it's own response.
This has been isolated to happen outside OT2 machine and is solved by power cycling or resetting smoothieware, and also does not include the return and newline character `'\r\n'` that would be there if it were an exact copy of the sent bytes.
```
[send] -> G28.2X
[receive] <- G28.2X ok\r\nok\r\n
```
This PR replaces that command in the string with an empty string
```
[send] -> G28.2X
[receive] <- ok\r\nok\r\n
```
> API: removes command echo from beginning of smoothie responses

- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/__tests__/structure.test.js
- components/src/constants.js
- components/src/deck/Plate.js
- components/src/deck/Plate.md
- components/src/deck/Well.js
- components/src/deck/Well.md
- components/src/deck/index.js
- components/src/structure/Pill.css
- components/src/structure/Pill.js
- components/src/structure/Pill.md
- components/src/structure/index.js
- components/src/styles/borders.css
- components/src/styles/colors.css
- protocol-designer/src/components/IngredPill.js
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/components/TransferishSubstep.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/labware-ingred/__tests__/selectors.test.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/top-selectors/well-contents.js
Closes #1050 
This PR makes a lot of changes so that the ingredients in wells, in the world of `Well` and `Plate` style `wellContents`, support multiple ingredients. The way of representing ingredients in `wellContents` style data/props used to be a single ingredient `groupId` -- this was an artifact of the design of the old ingredient/labware selector prototype. Now instead of `groupId`, it's an array: `groupIds`.
Sorry for the ugly diff! This required a significant change in a core part of PD, which is why I've been kicking this "well contents pluralization" can down the road until now when it's needed.
- Refactor to have array of group ids in wells, not single group id
- Refactor to pass in `fillColor`, not `groupId`, to Plate / Well.
- In PD, wells with multiple ingredients become …
> Pd ingred pill labels

- api/opentrons/drivers/smoothie_drivers/serial_communication.py
Quick fix to bug in #1185, where command string being searched for within responses must be encoded to bytes to avoid TypeError
> command converted to bytes

- api/opentrons/tools/factory_test.py
This scripts has somehow started failing when ran against good hardware. This edits the `HALT` line tests by not assuming exactly where in the response the `'ALARM'` key will show up.
This needs to be merged in as quick as possible so QC team can start using
> Api fix factory gpio test

- api/Pipfile.lock
- api/opentrons/data_storage/database.py
- api/opentrons/data_storage/labware_definitions.py
- api/opentrons/data_storage/serializers.py
- api/opentrons/util/calibration_functions.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/database/test_database.py
- api/tests/opentrons/database/test_labware_definitions.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/robot/test_robot.py
Save correct offset data when calibrating labware using new definitions (this functionality is still behind a feature flag, and there may be issues with aspirate and dispense default target locations). Fixes #704, fixes #1142, and relates to #1143 
- (fix) Subtract slot offset from well offset when saving labware offset data
Set the feature flag on a robot, and run protocols to see that calibrations behave as expected (the first pass for each labware will be like calibrating from a completely fresh machine)
> Remove slot offset from labware offset when saving new calibration data

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
After testing on machines in the office, only the plunger motors (`'BC'`) need to be disengaged to ensure an successful pipette EEPROM read.
This is better than disable all 6 axes, because now the gantry will not have the chance of losing any steps.
> Api: disable only plunger when reading eeprom

- Dockerfile
Forces library packages tornado and zmq to be compatible versions (i.e. 4.5.1 and 16.0.2 respectively). See issue https://github.com/jupyter/notebook/issues/3407. Fixes #1066 .
- Forces the versions of jupyter, tornado, pyzmq in the docker file
- Tested in the devbots application, moved one robot over from a separate application that
had a broken jupyter notebook and it was also successful.
> Adds specified versions for jupyter dependencies

- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/test_control_endpoints.py
Add tip length to pipette info endpoint. Fixes #1121 
- (feature) Add tip length to pipette info endpoint
Make sure new data shape makes sense for use in FE of factory calibration flow
> Add tip length to pipette info endpoint

- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
This PR is a client-side workaround for #1021 by guarding against malformed (as far as the app is concerned) RPC session responses.
- fix(app): Guard RPC client against malformed session responses 
Test on robot?
> fix(app): Guard RPC client against malformed session responses

- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/test_control_endpoints.py
Add function to remove instrument from robot state, and use this to clear ephemeral instances in control endpoints. Fixes #1211 
- (feature) Add function to remove instrument from robot state
- (fix) Clear ephemeral instances in control endpoints
> Add function to remove instruments from robot state

- api/opentrons/server/main.py
- api/opentrons/server/rpc.py
`aiohttp` has a default exception response if the `handler` raises:
```html
<html>
<head>
<title>500 Internal Server Error</title>
</head>
<body>
<h1>
500 Internal Server Error
</h1>
Server got itself in trouble
</body>
</html>
```
This is not super helpful, so this PR adds a [middleware](https://aiohttp.readthedocs.io/en/stable/web_advanced.html#middlewares) to log `handler` exceptions...
```
2018-04-18 16:16:39,315 __main__ ERROR [Line 90] Exception in handler for request <Request GET /pipettes >
Traceback (most recent call last):
File "/data/packages/usr/local/lib/python3.6/site-packages/opentrons/server/main.py", line 88, in error_middleware
response = await handler(request)
File "/data/packages/usr/local/lib/python3.6/site-packages/opentrons/server/endpoints/control.py", line 43, in …
```
> feat(api): Log HTTP handler exceptions and respond with traceback in JSON

- api/opentrons/tools/write_pipette_memory.py
To help QC testers know if a pipette has been properly QC'ed in SZ, this update simply prints out the previously written serial number just before writing a new one to the pipette.
> QC: print out the old pipette ID before writing new ID

- api/opentrons/deck_calibration/dc_main.py
- api/opentrons/robot/robot_configs.py
Tiny PR, updates the default probe-center coordinate to the position calculated from the machine's CAD model.
This only affects the first time a machine is tip-probed during factory calibration. After that, this value is never used again.
needs following testing:
> API: default probe coordinate pulled from CAD

- Dockerfile
- api/opentrons/__init__.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/instruments/pipette_config.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/drivers/test_driver.py
- api/tests/opentrons/server/test_calibration_endpoints.py
- api/tests/opentrons/server/test_control_endpoints.py
- labware-definitions/robot-data/pipette-config.json
Fix a typo in the pipette info endpoint, and move pipette model config values to data where it can be imported and used directly in JS apps. Fixes #1222 
- (fix) Fix typo in pipette info endpoint
- (feature) Move pipette config data to json files that can be imported by JS apps
Tested on 🌔 🌔
> Move pipette configs into data and make load function lazy

- Dockerfile
- api/opentrons/data_storage/database.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/main.py
Add debug logging to sql database, and an endpoint to check the server process' environment to make it easier to debug failures that might be due to mis-set environment variables.
- (feature) Add environment endpoint
- (chore) Add debug logging to sql
Tested on :moon: :moon:
> Add debug logging and environment read endpoint

- appveyor.yml
As you may have noticed, our latest Windows release build came in with the filename:
```
Opentrons-v3.0.0-beta.7-win-b3676-%APPVEYOR_REPO_BRANCH%.exe
```
This PR updates the AppVeyor config to use PowerShell to set build info environment variables rather than `cmd.exe` or the AppVeyor `env` block, because they do weird stuff with undefined environment variables (as described below) that PowerShell does not do.
- ci(appveyor): Set build info in PS because CMD is bad at undefined vars 
1. Normally on AppVeyor (as well as Travis), a tag build sets both the tag name and branch name env vars to the tag name
2. Our CI configs take CI specific env vars and rename them to standard ones
* e.g. `OT_BRANCH: '%APPVEYOR_REPO_BRANCH%'`
3. When naming the app asset, we check if the tag env var matches …
> ci(appveyor): Set build info in PS because CMD is bad at undefined vars

- api/opentrons/instruments/pipette_config.py
- labware-definitions/js/index.js
- labware-definitions/js/pipettes.js
- labware-definitions/robot-data/pipette-config.json
Based on discussions with UX as well as app needs for swap pipettes, this PR adjusts the format of `pipette-config.json` and adds a couple JS functions to retrieve known pipette models and pipette configs by model name.
This PR is functioning as a small ticket for Swap Pipettes
- feat(lw-defs): Improve pipette config definitions for dev and UX
- refactor(api): Refactor pipette config JSON retrieval for new format 
Please make sure this didn't break the API @btmorr. @pantslakz can you look at the new `displayName` values in `pipette-config.json` and verify they line up with what we discussed?
Otherwise JS sanity check would be good from @Opentrons/js
> feat/refactor: Update pipette defs based on UX and FE

- app/src/components/ChangePipette/RequestInProgressModal.js
- app/src/components/ChangePipette/styles.css
- app/src/components/LabwareCalibration/ConfirmModal.js
- app/src/components/LabwareCalibration/ConfirmPositionContents.js
- app/src/components/LabwareCalibration/JogControls.js
- app/src/components/LabwareCalibration/styles.css
- app/src/robot/actions.js
- app/src/robot/constants.js
- app/src/robot/reducer/calibration.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/calibration-reducer.test.js
- components/src/forms/forms.css
This PR closes  #1150 and wires up the Select Jog Increment radio groups in jog controls. Its worth noting that right now, jog controls are still using RPC. While testing, I noticed a few issues with in progress spinner modals in the `ChangePipette` and `LabwareCalibration` UIs. Did my best to match design screens again.
- enable increment radio group
- add cursor: pointer to radio/checkbox in comp_lib
- add `setJogDistance` action and `getJogDistance` selector
- fixed a modal in progress screen styles in change pipette and labware calibration modals
- update tests
Standard review. Please click through an entire calibration on an actual robot to test `inProgress` spinners in labware calibration. Most importantly, check setJogDistance and actual jogging action behaving as expected in the …
> Implement jog increment selection

- api/opentrons/instruments/pipette_config.py
There was a bug introduced into beta.8 software on robots that were updated via the app (no docker re-build). The bug resulted in protocols not being able to be uploaded as pipette configs were not loaded properly from constructors and thus returned a 'NoneType' error.
- Changes method that is used in pipette_config.py 'load' function from _load_config_from_file() -> select_config()
> Changes function the pipettte load method uses

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/dc_main.py
This PR adds a step to the factory-calibration CLI tool, in order to save the left-mount to right-mount offset.
Previously this offset was assumed to be identical, but because there is a +/- 5mm tolerance found on machines, this mount-offset is needed to ensure the tip-probe is not missed.
The found offset is saved within `robot_config`, named `mount_offset`, with a default of `(-34, 0, 0)`
The changes in the PR are to the CLI tool only, which is separate from the UI facing deck-calibration methods. The only users of the methods in this PR will be in-house QC testers.
Ran the below script after running the deck-calibration CLI tool, and visually verified they were aligned to the same point on the deck.
```python
from opentrons import robot, instruments
robot.connect()
left = …
```
> Api: left-mount offset during deck calibration

- app/__util__/mock-promise.js
- app/src/components/ChangePipette/index.js
- app/src/http-api-client/__mocks__/client.js
- app/src/http-api-client/__mocks__/health.js
- app/src/http-api-client/__tests__/motors.test.js
- app/src/http-api-client/__tests__/robot.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/motors.js
- app/src/http-api-client/pipettes.js
- app/src/http-api-client/robot.js
This PR addresses the last remaining checkbox in #860 
- test(app): Add tests for POST /robot/move using improved client mock
- feat(app): Add motors module to call POST /motors/disengage
- feat(app): Disengage pipettes during swap after move and before check 
No UI changes in this, just behavioral changes with API interactions.
You can test this out on virtual smoothie or a real robot (I'll be testing on a real one). Keep an eye on the network tab in the devtools to ensure that `POST /motors/disengage` is being sent (and responded to) with the correct axes. It should make the request:
- Immediately following the move to front request (POST /robot/move)
- Immediately preceding any pipette check (GET /pipettes)
> feat(app): Disable plunger during change

- components/src/deck/Plate.js
- components/src/deck/Well.css
- components/src/deck/Well.js
- components/src/deck/Well.md
- components/src/deck/index.js
- protocol-designer/src/components/IngredientSelectionModal.css
- protocol-designer/src/components/IngredientSelectionModal.js
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/components/SingleLabware.css
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/top-selectors/well-contents/index.js
Addresses #1187 - to close it, the "highlighted" state needs to happen when user hovers over wells in either Ingred Selection modal or Well Selection modal. The hover behavior will be follow-up PR.
Wells have an optional fillColor, and they have 4 states:
* Default
* Highlighted (aka "hovered" in designs, but in PD it's "highlighted" b/c sometimes this is when the well itself is hovered, and other times an item on the Step List is hovered / selected and causes this "highlighted" state)
* Selected
* Error
The SVG for circle / rect wells both is in 2 layers: 
TOP:
- border. default = thin black, selected/highlighted: thick blue, or error: thick red
- transparent light gray overlay, which lays over the bottom layer. Overlay is only shown when well is selected
BOTTOM: the fill color of the …
> Complib, PD: styling to match design reqs & cleanup well props

- app/src/analytics/gtm-config.js
- app/src/analytics/index.js
- app/src/analytics/intercom-config.js
- app/src/index.hbs
- app/src/index.js
- app/webpack.config.js
This PR closes #1224 by re-enabling the Intercom snippet, disabling the app v2 GTM config that tried to do intercom stuff, and adding an intercom update call during page change as detailed in their [SPA setup](https://developers.intercom.com/docs/integrate-intercom-in-a-single-page-app).
- feat(app): Add intercom boot and update on page change 
I recommend testing this by talking to yourself in Intercom. Also, please note that you may disable intercom by setting the DISABLE_INTERCOM env var to `1`:
```shell
make dev DISABLE_INTERCOM=1
```
> feat(app): Add intercom boot and update on page change

- api/opentrons/config/feature_flags.py
Change feature flag path override environment variable to disambiguate from labware definition location.
- (fix) Change override environment variable for feature flag file path to OT_FLAG_DIR
Tested on Kaja's robot
> Disambiguate feature flag path environment variable

- components/src/deck/Plate.js
- components/src/deck/Well.css
- components/src/deck/Well.js
- components/src/styles/colors.css
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/top-selectors/well-contents/__tests__/wellContentsAllLabware.test.js
- protocol-designer/src/top-selectors/well-contents/index.js
- protocol-designer/src/top-selectors/well-contents/wellContentsAllLabware.js
- protocol-designer/src/utils.js
- protocol-designer/src/well-selection/actions.js
- protocol-designer/src/well-selection/reducers.js
- protocol-designer/src/well-selection/selectors.js
Closes #1186, and adding hover-to-highlight closes #1187 
New interactivity design for well selection in both **ingredient selector** and **well selector**:
* When not dragging mouse:
* hovering over a well highlights it
* leaving a well un-highlights it
* dragging a selection over several wells highlights it
* holding shift puts you in "eraser" mode, so your selection rectangle then removes wells from your selection. Shift + Click also removes the well you click.
* if you're **not** holding shift and you click and drag, you're in "add to selection" mode. All wells you drag over are added to your selection, and your selection isn't cleared (before, your previous selection was cleared, b/c shift used to be "append mode" -- that's gone, selection always appends now). And click without drag …
> PD: new interaction & design for well selection

- app/src/components/ChangePipette/ConfirmPipette.js
- app/src/components/ChangePipette/Instructions.js
- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/styles.css
- app/src/components/ChangePipette/types.js
This PR is serving as a combo PR and ticket to "finish" up Change Pipettes for real. Aligns the error messages of pipette swap with the screens:
1. Pipette not attached
2. Incorrect pipette attached
3. Pipette not detached
- fix(app): Show more accurate error messages in pipette swap failures
- fix(app): Change back button to read "Exit" when it will exit
Easiest to test on a real robot. If testing on virtual smoothie, switch line 143 in `app/src/components/ChangePipette/index.js` to null to simulate a pipette removal (thanks hot reload).
> fix(app): Show more accurate error messages in pipette swap failures

- app/src/components/setup-instruments/Instruments.js
- app/src/components/setup-instruments/styles.css
- app/src/pages/SetupInstruments.js
- components/src/alerts/AlertItem.js
- components/src/instrument-diagram/InstrumentInfo.js
- components/src/instrument-diagram/instrument.css
This PR addresses #861, with two adjustments to the requirements listed in the ticket:
1. App will direct users to the robot settings page to change pipettes rather than incorporating the change modal in the calibration page
2. Due to various concerns in both the app and the API, the app will _not_ prevent the user from proceeding to tip probe
- The information available to the app to determine an "incorrect" pipette is not completely reliable
- Accordingly, I'm not comfortable blocking tip probe
- See #1260 for some of the story, also RPC is making this worse
- feat(components): Add/fix children/styling for InstrumentInfo and AlertItem
- feat(app): Add alert in tip probe if pipette is incorrect 
Standard code review + robot testing. Virtual smoothie testing works, but is a little …
> feat(app): Wrong pipette alert in tip probe

- app/src/components/CalibrateDeck/LabwareItem.js
- components/src/deck/Plate.js
- components/src/deck/Well.js
#1258 broke the deck map in the app by assuming that every single well in a Plate would have an entry in the `wellContents` prop. The app does not use `wellContents`, so it threw when it got to the deckmap.
Should've caught this in review, so we (myself very much included) should be more diligent about testing these sorts of components changes across our stack. Could also have been caught by some simple snapshot tests in the app, which it may be time to start introducing.
- fix(components): Fix wellContents in Plate becoming mandatory for every Well
Please test in the app and PD
> fix(components): Fix wellContents in Plate becoming mandatory for every Well

- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/robot/api-client/client.js
This PR fixes a couple typos (one in code, one in copy) that didn't break anything but were annoying
- fix(app): Fix typo in return tip handler (code typo)
- fix(app): Fix typo in WiFi confirmation modal (copy typo)
Nothing special
> fix(app): Fix some typos

- protocol-designer/src/components/StepCreationButton.css
World's smallest PR! :earth_africa: 
More padding, even on top & bottom, for Add Step button
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_tweak-add-step-button-spacing/index.html
> tweak StepCreationButton padding

- app/src/components/ChangePipette/styles.css
- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/__tests__/__snapshots__/modals.test.js.snap
- components/src/icons/icon-data.js
- components/src/modals/AlertModal.js
- components/src/modals/AlertModal.md
- components/src/modals/modals.css
This PR addresses #1236. Designs for the alert modals have changed and this is simply some chore work to update comp libs AlertModals before implementing router logic for Deck Calibration screens. 
Updated alert modal can be seen here in the change pipettes clear deck alert modal:
- Alert modal now has a header with gray bg, and warning icon, no border-radius
- Warning icon added to icon-data
Please review app alerts and PD alerts. 
@IanLondon I'm not sure if this affects your PD screens so this PR is mainly to make sure I didn't mess with your screens before moving on. I think the only screen affected is the create new protocol modal.
@mike while previewing run screen alerts I saw a potential second icon (lightbulb) i'm punting on that for now and hardcoding the warning icon for current …
> Update AlertModal style to match designs

- api/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/server/test_calibration_endpoints.py
This PR gives full control of pipette selection to the back end so that the optimal pipette is used for deck calibration.
Fixes #1257
- 'set_current_mount' and 'init pipette' are no longer endpoints, but helper functions
- Starting a calibration session now returns the following packet:
{ 'token': "",
'pipette': { 'mount': "",
'model': ""}}
- When you release a session or start a new session, it now removes previously mounted pipettes.
- More tests I should add?
- Am I handling uncommissioned pipettes in the expected way? @mcous 
- Do names make sense still for the endpoints?
> Removes set mount endpoint and init pipette endpoint adds pipette initialization into start endpoint

- api/opentrons/server/endpoints/control.py
- api/opentrons/server/main.py
This PR adds an endpoint to the server which takes a single frame from images captured with `ffmpeg`, then returns that image as a `jpg` in the HTTP response.
This is most useful of QC testers so the camera can be tested over USB cable.
> API: adds endpoint to take picture from webcam

- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/client.js
- app/src/http-api-client/index.js
- app/src/http-api-client/types.js
This PR lays groundwork for #974, #1008, and #1238 by giving the API client the ability to call and keep track of the `POST /calibration/deck/start` endpoint (which checks that pipettes are present, issues a calibration session token, and returns a pipette to use for calibration).
This is a redux only PR because wiring to UI would've made the diff too large.
- feat(app): Add action + reducer for starting deck calibration 
Code review would be useful. You could wait until it's wired to UI in an upcoming PR to test functionality, or you could test on a real robot / virtual smoothie:
1. Launch the app and open the dev console
2. `> store.getState()`
3. Expand the state object up to and including `state.robot.connection.discoveredByName`
4. Right click on the robot you're testing with and …
> feat(app): Add action + reducer for starting deck calibration

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/blowout.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/dispense.js
- protocol-designer/src/step-generation/errorCreators.js
- protocol-designer/src/step-generation/replaceTip.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/blowout.test.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
- protocol-designer/src/step-generation/test-with-flow/dropTip.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures.js
- protocol-designer/src/step-generation/test-with-flow/replaceTip.test.js
- protocol-designer/src/step-generation/test-with-flow/touchTip.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/touchTip.js
- protocol-designer/src/step-generation/transfer.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
Closes #1276 
For the TL;DR, see the new test in `protocol-designer/src/step-generation/test-with-flow/utils.test.js` (line 64: `'error in a command short-circuits the command creation pipeline'`)
- Changes `step-generation`'s command creators. Instead of throwing an error, they now return an error state if they are called with arguments and/or RobotState that doesn't make sense. The last viable RobotState and commands array is passed down.
- Eg if you run out of tips in PD now, it doesn't white screen. The error is only visible if you look at the console: `Got timeline errors` and inside `timelineErrors` you'll see:
```javascript
{
message : "No more tips for pipette, cannot replace tip",
type: "INSUFFICIENT_TIPS"
}
```
- Since the tests in `step-generation` are typed, flow gets mad when …
> Pd step generation handle errors

- api/opentrons/instruments/pipette.py
- api/opentrons/server/main.py
- api/opentrons/util/calibration_functions.py
- api/tests/opentrons/labware/test_pipette.py
Adjust pipette drop tip position for trash containers by the pipette config y offset. Fixes #1109 
- (fix) Adjust pipette drop tip position for trash containers by the pipette config y offset
Confirmed that the new test corresponds to reality on 🌔 🌔
> Multi-channel drop tips in middle of trash

- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/test_control_endpoints.py
If a pipette is already on a mount, use that pipette instance in control endpoints. Fixes #1302 
- (refactor) If a pipette is already on a mount, use that pipette instance in control endpoints
@mcous Please double-check to ensure that this unblocks deck calibration functions
> Use existing pipette in control functions

- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
- app/src/components/RobotSettings/CalibrationCard.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/index.js
This PR wires `POST /calibration/deck/start` to the Calibrate button in the RobotSettings page. Because that endpoint handles issuing the token and selecting a pipette to use for calibration, merging this PR:
- Addresses checkboxes 1 and 3 of #974
- Closes #1008
- Addresses checkbox 3 of #1235
- Closes #1236
- feat(app): Wire "Calibrate" button to POST /calibration/deck/start
Standard review. Expected behavior:
- On first click of "Calibrate" (i.e. no token issued) with pipette(s) attached
- On second click (i.e. token already issued)
- On first click without pipettes attached 
Please note that "first" and "second" clicks are from the perspective of the API, not the app. In other words, you'll want to relaunch the API to reset the token state.
> feat(app): Wire "Calibrate" button to POST /calibration/deck/start

- api/opentrons/config/feature_flags.py
- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/dc_main.py
- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/cli/test_cli.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_calibration_endpoints.py
There is an updated hardware revision to the deck which adds more visible "crosses" for calibration positions. This PR adds those values to the CLI/endpoints used for factory calibration.
- Add a function to the init file of deck calibration that checks if a feature flag "dots_deck_type()" is set
> Adds ability to set deck type through a feature flag

- app/src/components/CalibrateDeck/InUseModal.js
- app/src/components/CalibrateDeck/index.js
- components/src/forms/forms.css
- components/src/modals/modals.css
Addresses UI checkboxes of #1235. Display In Use Modal if token already issued.
- Display in use modal if robot token already issued
- Disable continue button (no action yet) until all checkboxes are checked
- Cancel button returns to RobotSettings
- Minor form/modal components stylings
Standard review. 
1- Click [calibrate] button in RobotSettings
2- Click [cancel] when prompted with clear deck alert
3- Click [calibrate] button again
4- Confirm Robot In Use modal renders with no boxes checked, continue button disabled
5- Check all 3 boxes, [continue] should enable (continue click action not covered in this PR)
> App: Robot in use modal

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/test_control_endpoints.py
Fixes #1240. Choose point (170.5, 129.0, 5.0) for z "safe" position.
- Adds z position into robot/positions endpoint
- Adds a test that checks this info is returned in robot/positions
- Adds test for deck calibration points 1,2,3 as I did not see where they were being tested
Let me know if you think the position should be some where else. Right now it's on the mid-bottom left side of slot 5.
> Adds specified position for pipette to move to z point

- api/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/server/test_calibration_endpoints.py
There, I fixed it
- (refactor) During deck calibration, if no pipettes are attached, do not create a SessionManager
> No pipette, no session!

- app/src/components/CalibrateDeck/ErrorModal.js
- app/src/components/CalibrateDeck/NoPipetteModal.js
- app/src/components/CalibrateDeck/index.js
This PR closes #974 and sneaks in a little generic error modal to Deck Calibration.
- Add NoPipetteModal to Calibrate Deck
- Add generic error modal as a catchall to Calibrate Deck
Detach pipettes (moon moon is currently with detached pipettes I believe) and click [calibrate] in RobotSettings page. 
*note:* You will probably have to restart the robot to release the previous token.
> Add no pipette attached and generic error modals

- api/opentrons/containers/__init__.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/containers/test_containers.py
- api/tests/opentrons/database/test_labware_definitions.py
Fix orientation of `containers.create` for both old and new labware. Fixes #1354 
- (fix) Reverse orientation of rows and columns in `containers.create`
@Laura-Danielle how will this affect existing protocols?
> Correct orientation of labware from containers.create

- components/src/alerts/alerts.css
- components/src/lists/TitledList.js
- components/src/styles/colors.css
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/StepItem.css
- protocol-designer/src/components/StepItem.js
- protocol-designer/src/components/StepList.js
- protocol-designer/src/containers/Alert.css
- protocol-designer/src/containers/Alerts.js
- protocol-designer/src/containers/ConnectedStepList.js
- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/errorCreators.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/index.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/steplist/utils.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/top-selectors/well-contents/index.js
Closes (almost!) #1086 
- Display errors StepList by showing error icons on the first error-ing step and all following steps
- Display errors in alert banners (they can stack)
- Tip error message matches design doc
- Safer access to prevStepId (stepId - 1 only works when there are no gaps) in SelectablePlate and generateSubsteps
- SelectablePlate falls back to last valid liquid state on the timeline when the timeline reducer bails out after encountering an error
- Clean up types of reducers - removed some `*` and `any` typing hacks
- Added new color for alert border `--c-warning` to `colors.css`
- TitledList's IconProps.className was being overridden by the classname supplied by TitledList, modified TitledList so you can pass a className inside IconProps to the Icon (this was to make the …
> PD: show user "not enough tips" error

- app/src/components/CalibrateDeck/InUseModal.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
This PR closes #1235 by wiring up the Continue button of the InUseModal to `POST /calibration/deck/start {"force": true}`.
- feat(app): Allow user to force take control of robot
Please give this a shot on a virtual bot and a real life bot
> feat(app): Allow user to force take control of robot

- protocol-designer/src/components/StepList.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/delay.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/test-with-flow/delay.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formProcessing.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
Closes #727
Adding a Pause step should create substep (as it did before), and add the `delay` command as specified in [JSON schema 1.0.0](https://github.com/IanLondon/opentrons-json-schema/blob/master/schema.json#L273) (except, the PD json overall doesn't match the schema yet, eg `commands` vs `subprocedure`. This PR is just for the `delay` part)
- delay command and tests
- modify Pause form validation (mostly cleanup)
- remove duplicate `TransferFormData` type definition
- most of the diff is pulling a nested value out of an object and putting it in a const so flow doesn't freak out (`valForm.validatedForm -> validatedForm` diff)
- Make a protocol with Pause, Consolidate, and Transfer steps and save it -- the JSON should look correct
> Pause step generates commands

- api/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/server/test_calibration_endpoints.py
This PR is serving as a bug ticket and its fix. The deck calibration jog endpoint was passing the `axis` parameter directly to the `jog` function. This was fine for `x` and `y`, but for `z` this was a problem because the calibration pipette's carriage z motor is `Z` for the left mount and `A` for the right mount.
The API now passes `session.current_mount` (which is, confusingly enough, either `Z` or `A` instead of `left` or `right`) as the jog axis if `z` comes in from the API client.
Unblocks #1246
- fix(api): Use correct smoothie axis for DC Z jog 
- feat(api): Add parameter verification to `jog` endpoint
- `axis` must be one of `"x"`, `"y"`, or `"z"`
- `direction` must be `-1` or `1`
- `step` must be present (actual verification of number type seemed like too much work for too little …
> fix(api): Use correct smoothie axis for DC Z jog

- api/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/server/test_calibration_endpoints.py
This is a little ticket + PR refactor based on some front-end requirements. Unblocks #1366 
- refactor(api): Make attach/detach DC commands more permissive
- Attach / detach tip will **no longer 400 if tip is already on / off**
- "tip-length" > "tipLength" because snake-case in keys is annoying
Code review + please make sure attach and detach tip commands still work!
> refactor(api): Make attach/detach DC commands more permissive

- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/__tests__/robot.test.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/index.js
This is an app plumbing PR that adds all `POST /calibration/deck` commands to the `calibration` module of the HTTP API client. Accordingly, it lays groundwork for:
- Deck Calibration: Move to Z-Axis Point #976
- Deck Calibration: Save Z Calibration #978
- Deck Calibration: Calibrate XY Point 'A' #979
- Deck Calibration: Calibrate XY Point 'B' #980
- Deck Calibration: Calibrate XY Point 'C' #981
- Deck Calibration: Save Calibration #982
- Deck Calibration: Jog Controls Function #1246
Example usage:
```js
// jog
// note that token is not passed; the thunk pulls it from state instead
const action = deckCalibrationCommand(robot, {
command: 'jog',
axis: 'x',
direction: -1,
step: 0.25
})
dispatch(action)
```
Commands:
```js
type DeckCalRequest =
| {| command: 'attach tip', tipLength: number |} …
```
> feat(app): Add POST /calibration/deck to calibration API module

- components/src/forms/forms.css
Closes #1290 
- When InputField has focus, show dropshadow and white background (previously, focus was indicated by light blue background)
- :ocean:
> complib: restyle InputField focus state

- protocol-designer/src/components/StepItem.css
- protocol-designer/src/components/StepList.js
Closes #1293 
- MORE BOX SHADOW
- "END" step is styled like the rest
- :eye:
> add box shadow & more margin to StepItems

- protocol-designer/src/components/StepEditForm.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/distribute.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/formProcessing.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
Closes #729 and closes #730
Implements Distribute step! User can create distribute steps, they'll update liquid + tip state, and user can save protocol and see that commands have been generated for Distribute.
- `distribute` command and tests
- Some further cleanup to make "TransferLike" (transfer, consolidate, distribute) be treated more uniformly
- Hooked up Distribute form
- Distribute form blows out to trash by default (as opposed to not blowing out. This was not specified in the ticket but I think it makes sense)
- Review tests, they should hopefully be straightforward (just long)
- Try it out in PD! The liquid tracking view as you scrub across the step list should be a good indicator of whether it's working right. Also, download the .json and make sure it generated the commands. …
> Pd distribute command

- app/src/components/CalibrateDeck/InstructionsModal.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
- app/src/components/JogControls/index.js
- app/src/components/LabwareCalibration/ConfirmPositionContents.js
- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/index.js
- app/src/robot/actions.js
- app/src/robot/types.js
This PR wires up the `jog` deck calibration command to @Kadee80's new jog controls component and refactors the labware calibration usage of this component to make sure everything keeps working.
Closes #1246 
- feat(app): Add action and state for setting HTTP jog step size
- feat(app): Wire HTTP jog to CalibrateDeck jog controls
- refactor(app): Cleanup labware cal jog to support changes for deck cal
I've tested this on Sunset. Please at least test that labware calibration jog still works on a robot. For testing deck calibration, getting to a state where you have a valid token and end up on the jog controls is a little tricky and relies on some hot-reload trickery, so it may be easier to wait until more of the API is wired up before actual testing. Otherwise follow the code modification …
> feat(app): Wire jog buttons for Deck Calibration

- protocol-designer/src/containers/ConnectedMoreOptionsModal.js
- protocol-designer/src/containers/ConnectedStepEditForm.js
- protocol-designer/src/steplist/actions.js
- protocol-designer/src/steplist/actions/actions.js
- protocol-designer/src/steplist/actions/handleFormChange.js
- protocol-designer/src/steplist/actions/index.js
- protocol-designer/src/steplist/actions/types.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/well-selection/actions.js
Closes #1298 - this prevents the last white screen error I know of (I'd bet there's a few I don't know of still!) that you could previously cause by selecting wells with a single channel then switching to multi-channel and saving a step.
Also BONUS: changing labware in labware dropdown should clear the well selection for that labware, preventing a similar well-carry-over problem.
#1380 will follow-up this PR (addresses cleaning up pipette data)
* ChangeFormPayload allows multiple form field changes with one action
* changeFormInput action is a thunk, uses access to state to handle form change events differently
* Factored out steplist/actions.js into a directory
- In a Step Form (eg Transfer), select an 8-channel pipette, then select source and/or dest wells. Switching to a single-channel …
> Pd clear well selection after pipette switch

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
This PR includes a check inside both `driver.move()` and `driver.home()` to automatically dwell all axes that are not being moved/homed.
The `driver.dwell_axes()` method will not send a current update if the axis is already at a low current, so this will not create redundant current-setting GCodes.
This has the wonderful side effect of helping to avoiding unnecessary current draw through the motor-driving IC's, which can overheat and enter a thermal-shutdown state if too hot. This is especially true for the Y axis, which if not in a low current when holding, will draw 1.75 amperes, which is very close to the IC's maximum 2.0 amperes, so it can get pretty darn hot.
> API: dwell axis if not included in movement

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
Bug fix. Explicitly return from `driver.update_position` after calling itself recursively, to avoid referencing variable before assignment (variable is `updated_position`)
> explicitly return after recursively calling update_position; adds test

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/tests/opentrons/drivers/test_driver.py
This PR adds some exception handling to when first connecting to the motor-driver.
First, if the serial-port is not accessible, and more descriptive error message is thrown describing how to solve the issue.
Second, the `driver._smoothie_reset()` method is removed from the compute start scripts, and will instead be called automatically if Smoothieware does not respond after first being connected to.
And third, the default serial-port timeouts are adjusted to reflect expected behavior, which is that all commands that do not create movements should response immediately (timeout = 1 second), and moving/homing commands need some time to complete (timeout = 30 second)
> Api updates serial port error handling

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/consolidate.js
- protocol-designer/src/step-generation/distribute.js
- protocol-designer/src/step-generation/errorCreators.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/mix.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/transfer.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
Mix form does stuff now! Closes #723 
- Implemented mix command generator & hooked it up to the Mix step form
- Tried to use some shorthand fns to make the tests a bit more compact -- more readable, or less readable this way?
- Mix form should save commands when you download the JSON
- Substeps for mix aren't implemented yet
> Pd mix command

- api/opentrons/drivers/smoothie_drivers/serial_communication.py
- api/opentrons/tools/factory_test.py
Fixes bug where if a response from the serial port did NOT contain the specified ack characters, then no exception was raised when there should be.
In this PR, if the ACK characters are not in the serial port's response, then a `SerialNoResponse` exception is raised.
If the ACK is an empty byte string (`""`), then an empty response from the serial port will not raise an exception
> API: check for ACK characters in serial response

- protocol-designer/src/components/StepList/StepItem.css
- protocol-designer/src/components/StepList/StepItem.js
- protocol-designer/src/components/StepList/TransferLikeSubstep.js
- protocol-designer/src/components/StepList/index.js
Closes #1331
* move steplist components into their own dir
* body1 font size for step items
* volume left-aligned & normal font color
- Should be a quick one, this is just reorganization and small style changes
> PD: restyle step items & organize steplist comps

- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/calibration.js
Little bugfix PR to ensure the app doesn't end up with a stale deck-calibration token after it calls the `release` endpoint successfully.
- fix(app): Clear DC token upon successful release call 
Standard review. Pretty satisfied with the test coverage on this one. I feel like virtual-smoothie is enough
> fix(app): Clear DC token upon successful release call

- app/src/components/ChangePipette/index.js
- app/src/http-api-client/__tests__/pipettes.test.js
- app/src/http-api-client/pipettes.js
This PR adds app support for the `GET /pipettes` changes made in  #1414
- feat(app): Add `?refresh=true` to `GET /pipettes` calls in ChangePipette 
Put #1414 on a robot, test that app on this branch is able to make it through Change Pipette
> feat(app): Add refresh to GET /pipette calls in ChangePipette

- app/src/components/SetupPanel/InstrumentListItem.js
- app/src/components/SetupPanel/LabwareListItem.js
- app/src/components/SetupPanel/styles.css
This PR closes #1317 by adding an active state to selected labware or instrument item.
- Implement active state style from connection panel in setup panel
Another tiny PR. Just confirm selected labware or pipette matches screenshot for active list item.
> fix(app): Highlight active calibration step in subnav

- .gitignore
Whenever I run virtual smoothie I get a new file `api/tests/opentrons/data/configs/robotSettings.json` that I shouldn't commit. This PR adds `api/tests/opentrons/data/configs/` to `.gitignore`
> add api configs in tests to gitignore

- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/integration/test_server.py
Rpc session was sending entire state of object on every state update, which was overwhelming the webworker and causing it to crash. This modifies the data such that the whole state is sent on first connect, and then on update only the data for the most recent command is sent. Fixes #1021 
This includes a breaking change for the app, as the shape of the data sent back during an rpc session has changed. The shape specified in this change was coordinated with @mcous, who is going to open a PR to fix the break. This will make upcoming releases non-backwards-compatible with prior servers, but they will still be able to update servers as that process does not use rpc.
- (fix) Reduce the size of the data packet sent on state update in the rpc session
Run a long protocol and see the webworker not …
> fix(api): Reduce size of rpc session packet

- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
- app/src/robot/types.js
- app/src/rpc/client.js
- app/src/rpc/remote-object.js
- app/src/rpc/test/client.test.js
- app/src/rpc/test/remote-object.test.js
This PR updates the app to support the minimal session state updates provided by #1426. It also disables remote method deserialization of notification objects (yes , the RPC server sends simple notifications over as crazy RPC objects, too) to further reduce worker / socket load for session update events.
- refactor(app): Support mini session updates in RPC client/robot state 
BREAKING CHANGE: Run timer will not work with robot API software prior to #1426
Will be testing on a robot that has been loaded with #1426. Virtual smoothie testing is also important / valid.
- Protocol runs still work
> refactor(app): Support mini session updates in RPC client/robot state

- api/opentrons/instruments/pipette_config.py
- api/opentrons/server/endpoints/control.py
- shared-data/robot-data/pipette-config.json
Explicitly use 'arc' movement strategy in control move endpoint, and update tip length values to account for overlap between nozzle and tip. Fixes #1402 
- (fix) Explicitly use 'arc' movement strategy in control move endpoint
- (fix) Update tip length values to account for overlap between nozzle and tip
- Do deck calibration flow
- Do labware calibration
> fix(api): Fix movement strategy and values for deck calibration

- app/src/components/nav-bar/NavButton.js
This PR is an easy usability quick win. If a robot is connected and the user returns to robot settings, the connect robot will appear selected, connected, and show the connected robots settings.
closes #1312
- NavButton url mapping takes connectedRobotName if it exists for robot settings page
Followed existing pattern for calibrateUrl in NavButton. 
To test UI:
- Connect to a robot
- Navigate away from robot settings page (upload/calibrate) 
- Navigate back to robot page
- Confirm connected robot is highlighted(blue) and that robot's settings show up in right page panel.
> feat(app): Default robot setting page to connected robot

- app/src/robot/selectors.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/selectors.test.js
This PR changes the order of the internal labware list to sort tip racks according to their associated calibrator pipette. Tipracks calibrated by the multi-channel are placed first in the list. This ensures that by the time the user gets to non-tiprack calibration, they will probably be using a single-channel pipette.
Fixes #1128
- feat(app): Order tipracks calibrated by 8-channel first in list
- Load a protocol with a single and a multi (like `calibration-validation.py`)
> feat(app): Order tipracks calibrated by 8-channel first in list

- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/blowout.js
- protocol-designer/src/step-generation/delay.js
- protocol-designer/src/step-generation/dispense.js
- protocol-designer/src/step-generation/dropTip.js
- protocol-designer/src/step-generation/replaceTip.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/blowout.test.js
- protocol-designer/src/step-generation/test-with-flow/consolidate.test.js
- protocol-designer/src/step-generation/test-with-flow/delay.test.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
- protocol-designer/src/step-generation/test-with-flow/dropTip.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/commandFixtures.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/fixtures.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/index.js
- protocol-designer/src/step-generation/test-with-flow/mix.test.js
- protocol-designer/src/step-generation/test-with-flow/replaceTip.test.js
- protocol-designer/src/step-generation/test-with-flow/touchTip.test.js
- protocol-designer/src/step-generation/test-with-flow/transfer.test.js
- protocol-designer/src/step-generation/touchTip.js
- protocol-designer/src/step-generation/types.js
Closes #1435 
Deletes a :boat:load of lines of code to make `step-generation` tests much more succinct, without adding much complexity.
Also, modified low-level command objects (and their type definitions) to match our JSON schema v1.0.0
- Factor out step-generation fixtures into `fixtures/` dir
- `commandFixtures` makes it easy to change commands in tests in ~one place, so updating the schema doesn't require editing ~2000 lines of code again
- All low-level commands updated to match JSON schema
- Code review highlights: Glance at commandFixtures, and at how all the step-generation tests look now.
- PD should now save protocols fully consistent with JSON schema v1.0.0 https://github.com/IanLondon/opentrons-json-schema/blob/master/schema.json - you can make a protocol and validate it at …
> Pd commands match json schema

- api/opentrons/api/calibration.py
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/labware/test_pipette.py
During labware calibration, the pipette moves to the center of the first well in a labware. For multi-channel pipettes, it specifically places the rear-most tip in the center of that well (the "A1" tip), as this would position the pipette correctly in an 8xN well plate or tiprack. This is a problem with troughs, where the whole multi-channel pipette should be centered in the trough well. As a solution, this PR would make the calibration endpoints check if the word 'trough' is in the name of the labware, and add the multi-channel y-offset value to the position during move, and subtract the y-offset value from the calibration delta when it updates the labware data. The result of this is that both single- and multi-channel pipettes move such that the "A1" tip is near the +Y edge of the …
> fix(api): Move to and use correct calibration point for troughs

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
Attempt to minimize amount of times a number is rounded in intermediate calculations. Fixes #1409 .
- Remove rounding from def _ul_per_mm
- Adds rounding in flow rate calculation speed
> Changes mm movement by only rounding in final location

- api/opentrons/__init__.py
If the database is not present when the robot boots, it tries to create the database from the default-containers.json file. If the split labware def flag is set, it tries to use the "ordering" field which does not exist in default-containers.json. This PR modifies boot behavior so it does not try to migrate the database if the split labware def flag is set.
- (fix) Don't create the sql database if the split labware definition feature flag is set
> Skip database migration if split labware def feature flag is set

- app/__util__/mock-promise.js
- app/src/robot/api-client/client.js
- app/src/robot/test/__mocks__/session.js
- app/src/robot/test/api-client.test.js
The RPC API is unable to handle a `session.stop` call if the protocol run is paused. This PR works around that issue by always calling `session.resume` right before `session.stop`.
Fixes #707
- fix(app): Send session.resume before stop to cancel paused runs
Needs real robot testing! This will be difficult / impossible to test using virtual smoothie.
1. Start protocol run
2. Click "Cancel"
3. Run should cancel and robot should home
4. Robot page should show "Status: Cancelled"
1. Start protocol run
2. Click "Pause" and wait for robot to stop
3. Click "Cancel"
4. Run should cancel and robot should home
5. Robot page should show "Status: Cancelled"
This PR also adds a bunch of tests that were missing but test existing run, pause, resume, and cancel functionality. `'calls session.resume + …
> fix(app): Send session.resume before stop to cancel paused runs

- api/opentrons/instruments/pipette_config.py
- api/tests/opentrons/labware/test_pipette.py
This PR allows pipette configs loaded from JSON to not completely fail if a single value fails to load. For each value expected to find in the loaded JSON, if it is not there, it will be loaded from the `pipette_config` namedtuple.
> API: fallback to pipette_config when json config values fail to load

- app/src/components/ChangePipette/Instructions.js
- app/src/components/ChangePipette/index.js
Title bar and instructions now read mount instead of carriage to keep consistent with API/documentation naming conventions.
closes #1452
- change title bar subtitle and attach pipette instructions to use `mount` instead of `carriage`
Pretty straight forward. You can only see detach pipette title and instructions on VS. I think a code review good enough.
> fix(app): Change carriage to mount in change pipette instructions

- app-shell/lib/api-update.js
- app-shell/lib/config.js
- app-shell/lib/log.js
- app-shell/lib/main.js
- app-shell/lib/ui.js
- app-shell/lib/update.js
- app-shell/package.json
- app/__mocks__/electron.js
- app/src/index.js
- app/src/logger.js
- app/webpack.config.js
- yarn.lock
This PR is also serving as a ticket because I forgot to write the ticket first. My bad.
Lays groundwork for #1329 
- feat(app): Add file/console log module to app's main and renderer 
App only change so no need for robot testing. Please note that this PR _does not_ replace all instances of `console.xyz` in the app. Instead, it adds a single `log.info` to `app/src/index.js` for verification.
Checks:
- New dependencies, so do a `make install`
- Logs from `app-shell` go to log files (`combined.log` and `error.log` at levels `debug` and `error`)
> feat(app): Add file/console log module to app's main and renderer

- shared-data/protocol-json-schema/protocol-schema.json
This isn't 100% done -- there are 3 `TODO`s in the descriptions. But I figure now's as good a time as any to move this schema definition from my personal repo to the monorepo.
- add JSON Schema definition of Opentrons JSON Protocol
- JSON schema OK with you?
- Any thoughts about the TODOs?
It's not intuitive to read JSON Schema definitions if you're new to them - to help understand this, see the example protocol at https://github.com/IanLondon/opentrons-json-schema/blob/master/protocol-example.json for the big picture of how these Protocol JSONs are structured.
> add protocol JSON schema definition 1.0.0

- app/src/components/AppSettings/AnalyticsSettingsCard.js
- app/src/components/AppSettings/index.js
- app/src/components/AppSettings/styles.css
- app/src/components/ConnectPanel/RobotList.js
- app/src/components/ConnectPanel/connect-panel.css
- app/src/components/ToggleButton/index.js
- app/src/components/ToggleButton/styles.css
This PR adds an analytics settings card UI to the app (more) section of the app. Toggle behavior is out of scope and covered in #1330.
- closes #1173
- Create reusable `ToggleButton` component for app, implement in RobotList and AnalyticsSettingsCard
- Implement UI only for analytics settings card
Standard review, nothing in state. Just UI and code review. 
Also, I was eyeballing off a screenshot for this ticket so any spelling/grammar callouts much appreciated!
> feat(app): Add app analytics card UI to app page

- api/opentrons/robot/robot_configs.py
- api/tests/opentrons/robot/test_robots_config.py
This PR fixes a bug in how the save tip-probe data (aka `robot.config.instrument_offset`) was being loaded. The bug was that it wasn't ever being loaded, so the only tip-probe data that was being used was data generated in the same session as the protocol run.
> Api: fix instrument offset load bug

- app-shell/Makefile
- app-shell/README.md
- app-shell/lib/config.js
- app-shell/lib/log.js
- app-shell/lib/main.js
- app-shell/lib/ui.js
- app-shell/package.json
- yarn.lock
This PR implements the electron side of app configuration as described in #1463 in order to support #1329.
- feat(app-shell): Add configuration file with CLI and env overrides
There's +182 of README diff in this one and +50 of package.json + lockfile, so the actual code diff isn't that large.
For testing this, I've been using `ui.width` and `ui.height` because it's readily apparent if they work. But also, the `make dev` task in `app-shell` has been updated to use the CLI args so there's some testing built in.
- e.g. `make dev OT_APP_UI__WIDTH=768`
- Makefile overrides console log level in `make dev` to `debug` (default is `info`)
- e.g. Verify that `make dev OT_APP_LOG__LEVEL__CONSOLE=error` has no effect because of the CLI arg in the Makefile
Also please double check my documentation in …
> feat(app-shell): Add configuration file with CLI and env overrides

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
When a `ParseError` or `SerialNoResponse` error is raised within the driver, this PR increases the number of command retries from 2 to 3, and also adds a small delay (100ms) between each retry.
> API: increase serial retries to 3; add small delay between retries

- api/docs/source/api.rst
- api/opentrons/instruments/pipette.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/labware/test_pipette_unittest.py
Since there was no flag (that I could see) which allowed me to run an import statement and ignore any warnings issued, I used the SKIP flag. This still displays the code-blocks correctly formatted but does not actually run a check on the code. Will re-visit later.
- Changed all code blocks to reflect correct api
- Removed irrelevant functions in robot/pipette
- Made sure no errors and/or warnings returned from the 'make docs' command
Typos?
> Make API tests pass via SKIP flag in Sphinx

- app/src/components/RunLog/styles.css
- components/src/deck/LabwareContainer.css
- components/src/lists/lists.css
- components/src/styles/colors.css
- protocol-designer/src/components/steplist/StepItem.css
Closes #1328 - we're trying to standardize the highlight color across PD + Run App
* Use `--c-highlight` for highlight border of LabwareContainer, TitledList, and StepItem
* Use `--c-highlight` for active text color in RunList
* Delete now-unused `--c-teal` definition
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_components-standardize-highlight-color/index.html
* Look at changes in PD and Run App to components listed above
* `--c-teal` should be removed here, right? Wherever we need it, I think it's really `--c-highlight` (a slightly different shade of teal)
> pd, complib, run app: standardize highlight color

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
This PR adds an explicit call to `disconnect()` before the driver attempts to `connect()` to the port. In the event that the responses from a machine's uart port show an echo, it is occuring immediately after the port has been re-connected to, like after simulating, or swapping between processes and calling robot.connect(). This PR attempts to avoid the source of that error, whether it's source is from Smoothieware or the OS.
In addition, this PR adds a private driver method `_remove_unwanted_characters()`, which refactors how the above mentioned echo was previously being removed from a uart response. The refactor adds some logging messages to help debug, it searches for each gcode-command individually, and it removes newline and return characters, which have been found to appear within …
> Api disconnect before connect

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette_unittest.py
Quick PR to remove some functions that are no longer relevant to our code-base.
- Removes the 'calibrate' function as that is no longer how we handle calibrating containers
- Removes 'set_max_volume' function as that will be calculated using the pre-set ul-per-mm value
> Removes functions that are no longer used in OT 2

- protocol-designer/src/step-generation/aspirateUpdateLiquidState.js
- protocol-designer/src/step-generation/test-with-flow/aspirateUpdateLiquidState.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/well-contents/index.js
Closes #1479 
Turns out I'd written the test for "aspirate from trough with 8-channel pipette" with the wrong logic - the specified aspirate `volume` should be per tip, not "total volume aspirated from source". So before, when aspirating 10uL from a trough with a multi-channel, liquid tracking would move 10/8 uL (instead of 10 uL) from the trough to each pipette tip, then on dispensing 10 it would dispense `__air__`, thus making the destination wells gray.
- update aspirateUpdateLiquidState test for common well (trough) with multichannel pipette
- fix aspirateUpdateLiquidState for common wells with multichannel pipette
- type cleanup with the repeated `SingleLabwareLiquidState` type
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_fix-aspirate-from-trough-liq-tracking-bug/ …
> PD: fix liquid tracking bug on aspirating from trough

- api/opentrons/api/session.py
- app/src/components/ConnectPanel/connect-panel.css
- app/src/components/RunLog/CommandList.js
- app/src/components/RunLog/SessionAlert.js
- app/src/components/RunLog/index.js
- app/src/components/RunLog/styles.css
- app/src/components/SetupPanel/styles.css
- app/src/robot/reducer/session.js
- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/alerts/AlertItem.js
- components/src/alerts/alerts.css
- components/src/icons/icon-data.js
- components/src/lists/lists.css
- components/src/styles/colors.css
This PR closes #1269 addresses #855 by conditionally displaying 'RunComplete' 'Run Paused' and 'Run Canceled' `AlertItem` banners to the run screen. 
*Note:* the designs show links to run again after run complete or run canceled. This is hidden since this is not functional yet and thats a rather large ticket.
While I was in there I refactored some of the comp_lib colors to standardize highlighted/active/info states of `AlertItem` in comp_lib and active calibration steps in the app. We started having 3+ versions of the selected blue colors. @IanLondon and I sat down and standardized a few things to avoid this moving forward. There is a little bit of styling in RunLog CSS to allow for proper positioning of the AlertItems without screwing up the scrollable run log styles.
This PR also …
> feat(app, comp): Add run complete, paused, and canceled AlertItems

- api/opentrons/tools/write_pipette_memory.py
Small PR, to help the SZ team avoid sending unneeded characters when scanning barcodes (like the ASCII select character in XTerm `"\x1b(B"` they are seeing over there)
> API: removes characters before the P in the pipette barcode

- components/src/styles/typography.css
- protocol-designer/src/components/IngredientSelectionModal.js
- protocol-designer/src/components/WellSelectionInstructions.css
- protocol-designer/src/components/WellSelectionInstructions.js
- protocol-designer/src/components/WellSelectionModal.js
Closes #1324 
> Add the text "De-select: Shift + Click" as in this illustration:
* complib: 'unselectable' custom prop set in typography.css
* pd: WellSelectionInstructions component
- quick UI review: this text should show up as in the image for ingred selection modal & for well selection modal
- CSS review: `--unselectable` in `typography.css`
> add well selection instructional text

- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/dispense.js
- protocol-designer/src/step-generation/errorCreators.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/dispense.test.js
Closes #1406
- Aspirate & dispense command creators return "labware does not exist" error object instead of raising an exception, when labware id does not exist in RobotState
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_delete-labware-gracefully/index.html
- Create labware X
- Set up steps
- Go back to Deck Setup, delete labware X, you should see an error banner 'This step involves labware that has been deleted'
- Fix the step by selecting another labware Y, the error will go away
And for multiple steps all using the same labware, same thing should happen.
> PD: delete labware gracefully

- protocol-designer/src/components/FileSidebar.css
- protocol-designer/src/components/FileSidebar.js
- protocol-designer/src/containers/ConnectedFileSidebar.js
Closes #1500
This is just minimal setup for the Upload button in PD. It doesn't do anything with the protocol when you upload it (just logs parsed JSON to console). Doing the Redux hookup in a separate PR.
I tried adapting the `UploadInput` from Run App to re-use it, but the buttons are styled differently enough, and the presentational side is simple enough, that it seemed easier to just make a separate component. UploadInput is already kinda multiplexed to be a button or a file-drop-area, so making it an OutlineButton with a different label text and no icon seemed to be cramming too much into it.
* parses JSON (and just logs to console for now)
* gives error when `*.py` file is uploaded
* gives error if file cannot be parsed as JSON
* added top/bottom margin to DOWNLOAD button to match …
> PD file upload button initial steps

- app/src/components/RunLog/CommandList.js
- app/src/components/RunLog/index.js
- app/src/components/RunLog/styles.css
- app/src/robot/selectors.js
- components/src/__tests__/__snapshots__/modals.test.js.snap
- components/src/modals/SpinnerModal.js
- components/src/modals/SpinnerModal.md
- components/src/modals/SpinnerModalPage.js
- components/src/modals/index.js
- components/src/modals/modals.css
This PR closes #855 by displaying a spinner modal while a cancel request is in progress. *Note i updated to thicket to not include the reset run link as it is not implemented, is quite large, and is covered in several other tickets*
This ticket also breaks out `SpinnerModal` and implements it as a child of `SpinnerModalPage` in comp_lib to allow for spinner modals with optional message and no title bar.
- Add `SpinnerModal` to comp_lib
- Update `SpinnerModalPage` to use SpinnerModal
- getCancelInProgress selector for conditional rendering of `SpinnerModal` while robot homes and resets
Standard code review.
https://s3-us-west-2.amazonaws.com/opentrons-components/app_cancel-confirmation/index.html
Run a protocol (if you're not on moon moon you may have to make push onto the testing robot). …
> feat(app, comp): Display `SpinnerModal` while robot homes and reboots

- api/opentrons/deck_calibration/__init__.py
- api/opentrons/deck_calibration/endpoints.py
- api/opentrons/deck_calibration/linal.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot_configs.py
- api/opentrons/server/endpoints/control.py
- api/tests/opentrons/server/calibration_integration_test.py
- api/tests/opentrons/server/test_calibration_endpoints.py
- api/tests/opentrons/server/test_control_endpoints.py
- app/src/components/CalibrateDeck/ClearDeckAlert.js
- app/src/components/CalibrateDeck/InstructionsModal.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/robot.js
Accounts for multi-channel y offset and left mount x offset. Fixes #1400 and fixes #1450 
- (fix) Deck calibration endpoints work correctly with single and multi-channel pipettes and both mounts
Tested on 🌔 🌔 , creates functionally idential transform files with multi on left and single on right, and same as CLI
> Add deck calibration move endpoint with offset logic for multi-channel

- app-shell/lib/config.js
- app-shell/lib/log.js
- app-shell/lib/main.js
- app-shell/lib/ui.js
- app-shell/package.json
- app/__mocks__/electron.js
- app/package.json
- app/src/__mocks__/logger.js
- app/src/config/__tests__/config.test.js
- app/src/config/index.js
- app/src/index.js
- app/src/logger.js
- app/src/reducer.js
- app/src/shell/__tests__/shell.test.js
- app/src/shell/index.js
- yarn.lock
Larger PR than I intended; I ended up implementing just a little more functionality than we strictly needed for config (but that we do need for future work). My apologies.
Closes #1329
- feat(app): Add app-shell config to app state
- Added config remote to `app/src/shell` module to grab initial state
- Added an async IPC channel so the main and renderer threads can dispatch actions to each other
- Handled in `app-shell/lib/main` and `app/src/shell` (middleware)
- Added config actions:
- `config:UPDATE` gets sent from renderer to main to trigger the file write
- `config:SET` gets sent from main to renderer on write success to be reduced into state
- Cleaned up some mocking related to config and logging so every test run doesn't need to create temp files
Test procedure:
1. Launch app and …
> feat(app): Add app-shell config to app state

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/types.js
Closes #969 
- refactor `robotStateTimeline` selector to be able to compose command creators
- drop tips from all pipettes at end of protocol
All cases should drop tips only if there are tips on pipette: 2 pipettes with tips, 1 with 1 without, and no tips on either pipette. Test on robot please if you can.
The multi-channel has been doing something weird with the position of the trash when it goes to drop tips. It does this even when I ssh in and `from opentrons import protocols; import json; protocols.execute_protocol(json.loads("""{ protocol JSON here }"""))` so it's a backend problem out of scope of this PR.
> refactor robotTimeline selector to support drop tips at end

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/drivers/smoothie_drivers/serial_communication.py
This small PR toggle the UART port close/open if there is no response from the port.
In addition, the logging messages for gcodes sent and received were moved to show the exact contents of the response, to help debuggin.
> API: toggle uart port closed/open if no response

- CONTRIBUTING.md
- package.json
- yarn.lock
As discussed in various meetings, we need a way to keep track of the various changes that we make to this codebase. One way to do this is to add this information into our commit messages and format them in such a way that we could generate a changelog from them...
...and that's what we're going to do with [commitizen](https://commitizen.github.io/cz-cli/) and [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog)!
Ensuring your commit messages are properly formatted is a pain, so this PR adds commitizen to format our messages for us. Commitizen is a little CLI wizard that will ask a few questions and then commit your changes with the proper message:
```
<type>[optional scope]: <description>
[optional body]
[optional footer]
```
Closes #1523
- …
> chore(repo): Add commitizen to repo and docs

- app/src/components/RunLog/ConfirmCancelModal.js
- app/src/components/RunLog/index.js
- app/src/components/RunPanel/RunControls.js
- app/src/components/RunPanel/index.js
- app/src/pages/Run.js
This PR closes #1271. Clicking cancel now pauses run and links to `/run/cancel`. Modal provides option to go back (resume) or cancel run. Both actions redirect to `/run`
- change cancel button to `Link` component, trigger onPauseClick
- `/run/cancel` renders new component `ConfirmCancelModal`
- go back action resumes protocol and returns to RunLog
- cancel action cancels protocol and returns to RunLog
Please test on a robot.
> feat(app): Initiate and confirm run cancel

- api/Makefile
Thanks to @heyoni for reporting this!
`cp -R docs/public/*` will not copy dotfiles because globs do not include dotfiles with `*`
`cp -R docs/public/.` [will include dotfiles](https://superuser.com/a/367303)
- docs(api): Fix docs copy task to include dotfiles (like .nojekyll)
Run `make -C api docs` on your machine, ensure all necessary dotfiles are copied
> docs(api): Fix docs copy task to include dotfiles (like .nojekyll)

- README.md
- api/docs/source/static/nav.css
- api/docs/source/templates/layout.html
This PR ensures online documentation navigation header and footer match opentrons.com
- remove dead links from resources tab in nav
- update layout template css, js, and navigation
1- Checkout this branch
2- `cd api/docs`
3- `make clean html`
4- go to build folder and open any html file 
go to blog.opentrons.com
> docs(docs): Update header and footer navigation

- app/src/components/ChangePipette/ConfirmPipette.js
This PR closes #1453
Modal popup after user clicks the exit button within confirm pipette attached screen,
particularly in a detach pipette use case was redundant. Exit button in title bar still displays the confirm cancel modal.
- remove conditional exitButtonProps. Exit button in confirm pipette screen never hits exit confirmation url.
Please test on actual robot if possible! Virtual smoothie is fine as well.
Go through change pipette in RobotSettings. Click [exit pipette setup] and confirm no confirm cancel modal renders.
> feat(app): Remove confirm exit modal from change pipette screens

- api/opentrons/robot/robot.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/calibration_integration_test.py
- api/tests/opentrons/server/test_calibration_endpoints.py
Cache pipette models on robot reset and connect, for better consistency
- refactor(api): Cache pipette models on reset and connect
Tested on 🌔 🌔 , resulted in slightly better consistency in detecting installed pipette models in corner cases, such as after cancelling a protocol.
> refactor(api): Cache pipette models on reset and connect

- api/opentrons/instruments/pipette.py
- api/opentrons/server/main.py
- api/tests/opentrons/labware/test_pipette_unittest.py
fix(api): Modify touch tip defaults to reduce speed and touch 1mm below edge of well, and add parameters to allow users to modify these values.
Closes #1448
- fix(api): Modify touch tip defaults to 60mm/s and 1mm below edge of well
Tested on 🌔 🌔 and demo'ed to Kristin and Kinnari
> fix(api): Modify touch tip defaults

- components/src/__tests__/__snapshots__/lists.test.js.snap
- components/src/lists/TitledList.js
- components/src/lists/lists.css
- components/src/styles/colors.css
- protocol-designer/src/components/StepCreationButton.css
- protocol-designer/src/components/steplist/MultiChannelSubstep.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/steplist/actions/actions.js
- protocol-designer/src/steplist/reducers.js
Closes #1171 
- complib: `TitledList` takes `hoverable` prop that toggles `:hover` style to show border
- complib: `TitledList` style updated to match design (see #1171)
- complib: `TitledList` uses `outline` not `border`
- pd: user cannot collapse selected step; steps *temporarily* expand when selected and return to their previous collapse state when de-selected
- pd: hovered steps are not "selected"; hovered steps show border
- pd: StepCreationButton gets z-height so it is above TitledList header
-complib: remove carat hover state for selected step
Run App should look the same as before, and interaction with TitledList items in Run App should be unchanged.
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_update-styles-for-step-items-2018-05-22/index.html
PD should …
> PD & Complib: Update styles for TitledList & behavior for StepItems

- app/src/components/SetupPanel/DeckCalibrationGroup.js
- app/src/components/TipProbe/UnprobedPanel.js
- app/src/components/nav-bar/NavButton.js
- app/src/pages/SetupDeck.js
- app/src/robot/reducer/calibration.js
- app/src/robot/test/calibration-reducer.test.js
This PR makes tip probe completely optional for both protocol run and labware calibration
Closes #1496
- feat(app): Make tip probe completely optional
Virtual smoothie is fine. Making tip probe optional messes a little with the existing logic for when to display the various clear / populate deck modals, so should test that still works:
- Ensure "clear deck" alert modal still pops up before tip probe on:
- Ensure populate deck alert modal pops up before labware calibration on:
> feat(app): Make tip probe completely optional

- protocol-designer/src/labware-ingred/reducers/index.js
Previous behavior used 'trash-box' which causes misalignment with actual trash on deck! D'oh
* Fixed trash in slot 12 was `trash-box`, now is `fixed-trash` labware type
Test on a robot, if you'd like
> feat(protocol-designer): make default trash labware 'fixed-trash' not 'trash-box'

- app/src/components/AppSettings/AppUpdateModal.js
- app/src/components/AppSettings/index.js
- app/src/pages/AppSettings.js
- app/src/shell/__tests__/shell.test.js
- app/src/shell/index.js
This PR closes #1154 by rendering the app update modal on app page load if 
- an update is available
- the update alert has not been marked seen
- add `SET_UPDATE_SEEN` reducer to shell
- set `update: {... seen: true}` on `START_DOWNLOAD`
- redirect `/menu/app` to `menu/app/update` on app page view if update is available and seen=false
- update `START_DOWNLOAD` test and write `SET_UPDATE_SEEN` in shell
- add alertOverlay prop `AppUpdateModal`
Please let me know if tests are missing.
To test UI (no robot neccessary):
1. Change `app-shell/package.json` version (line 4) from `"version": "3.0.1-beta.1"` to "version": "3.0.0"
2. Click 'more' nav button in main nav
3.  Click [Not now] button in Alert
> feat(app): Render update app modal if update available

- api/opentrons/api/session.py
This is a little PR to address the API portion of #1270
- fix(api): Reset startTime when session.refresh is called
Changes are self-explanatory. Please let me know if you feel like the assignment should live in a different method (e.g. `self._reset`)
> fix(api): Reset startTime when session.refresh is called

- app/src/components/RunLog/CommandList.js
- app/src/components/RunLog/index.js
- app/src/components/RunPanel/RunControls.js
- app/src/components/RunPanel/RunTimer.js
- app/src/components/RunPanel/index.js
- app/src/containers/UploadStatus.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/__mocks__/session.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
Addresses app requirements of #1270. This PR adds a reset run button that calls `session.refresh` to reset the run log. It also adds a spinner because `session.refresh` takes about the same amount of time as a session upload.
- feat(app): Add ability to reset a run after it ends
Please try this out with both a real robot as well as with Virtual Smoothie. If possible, run the API with #1576 or else "Start Time" will do weird stuff (i.e. it will clear out and then go back to the start time of the previous run when `session.refresh` completes. This is an API bug addressed in 1576).
> feat(app): Add ability to reset a run after it ends

- app/src/components/JogControls/styles.css
This PR closes #1567. Jog increment selection is now to the left of the jog buttons. Since jog hot keys are not implemented yet, that text is not included in this ticket.
- Update css grid placement of jog buttons, increments, and labels
Quick CSS only fix. Please check the layout in deck calibration and/or labware calibration jog controls implementation
> fix(app): Render jog increments to left of jog buttons

- components/src/instrument-diagram/InstrumentGroup.js
- components/src/instrument-diagram/InstrumentInfo.js
- components/src/instrument-diagram/instrument.css
- protocol-designer/src/components/FilePage.js
Closes #1535
* `showMountLabel` prop on `InstrumentGroup` + `InstrumentLabel` shows "Left Pipette" | "Right
Pipette" when true
* Remove `min-width` from `InstrumentGroup` b/c it makes PD file page too wide on small screens
* Should not affect run app - double check!
* PD matches image in #1535
> feat(protocol-designer): specify left|right pipette label

- protocol-designer/src/components/FileSidebar.css
- protocol-designer/src/components/FileSidebar.js
Closes #1534
Rename upload to "Import JSON" and download to "Export"
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_rename-buttons-1534/index.html
:bread:
> feat(protocol-designer): rename upload & download buttons

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/server/calibration_integration_test.py
- api/tests/opentrons/server/test_calibration_endpoints.py
- api/tests/opentrons/server/test_control_endpoints.py
Driver simulation will no longer falsely report 'p10_single_v1', and pipette model cache will not be overwritten when driver is in simulation.
- fix(api): Improve pipette model caching
> fix(api): Improve pipette model caching

- protocol-designer/src/components/Form.css
- protocol-designer/src/components/IngredientSelectionModal.js
- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/labware/NameThisLabwareOverlay.js
- protocol-designer/src/components/labware/labware.css
- protocol-designer/src/containers/ConnectedDeckSetup.js
- protocol-designer/src/containers/IngredientPropertiesForm.js
- protocol-designer/src/containers/IngredientsList.js
- protocol-designer/src/containers/LabwareNameEditForm.js
- protocol-designer/src/labware-ingred/actions.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/well-selection/reducers.js
Closes #1281
* show "Labware Name" TitledList "button" in IngredientsList
* LabwareNameEditForm connected component - labware edit form appears when the button is clicked and closes when the form is saved or canceled
* Make sure you can't get into funky state by flipping around btw diff labware, diff modals, clicking the labware, etc - but keep in mind standing bug #1561
* This is the oldest part of PD and the code needs a broader cleanup, I tried to balance not having a huge diff vs not making the mess worse
> feat(protocol-designer): allow user to rename labware in ingred edit mode

- app/src/components/RunLog/SessionAlert.js
- app/src/components/RunLog/index.js
- app/src/components/RunLog/styles.css
- components/src/alerts/AlertItem.js
This is the new PR to replace the once previously dirtied by a rebase and a merge. 
This PR doesn't have an issue attached but [reset run] link was not present in the Run Complete and Run Canceled banners but was shown in design. This adds the reset functionality and text to those banners.
- fix(app): Add reset run link to run canceled/complete banners
Testing on Virtual Smoothie is fine. 
Upload and run a protocol to completion
Run protocol again and cancel
> fix(app): Add reset run link to run canceled/complete banners

- components/src/interaction-enhancers/index.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/components/labware/NameThisLabwareOverlay.js
Closes #1282
- During deck setup, new labware "saves" when you click outside the "name this labware" overlay
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_deck-setup-name-labware-on-click-away-1282/index.html
> feat(protocol-designer): make new labware dismiss nickname overlay when user clicks away

- api/opentrons/protocols/__init__.py
When uploading a protocol with a long delay (or a lot of short delays) the protocol takes a long time to upload because it's calling `time.sleep` as it simulates the protocol upon upload.
Also I realized that I had the implementation of "delay until user input" wrong - `wait: True` not `wait: String` should call `robot.pause()`
- Don't `time.sleep` when uploading a JSON protocol
- Fix delay until user input `wait: True` implementation
I tested on Sunset (upload a protocol that has long delays, see it doesn't take too long) - virtual smoothie is probably OK.
Are there any cases where this would cause a problem? `robot.is_simulating` is safe to use here, right?
---
```json
{
"protocol-schema": "1.0.0",
"metadata": {
"protocol-name": "DNA-test",
"author": "Kinnari",
"description": "test with …
```
> fix(api): json protocol upload does not time.sleep when simulating

- protocol-designer/src/step-generation/robotStateSelectors.js
- protocol-designer/src/top-selectors/substep-highlight.js
Before this, if the user created a protocol, added steps that use a pipette, and then click "New
File" and make a new pipette, PD would whitescreen if that new pipette was different than the old
one
- safe to change pipettes in "New File" modal (no white screen, but bad UX right now)
- also fixed partially implemented distribute well highlighting - before it was highlighting just single wells, it didn't highlight all wells when mousing over a distribute step
- Changing pipette types in "New File" modal after making steps that use that pipette no longer whitescreens (but PD does show a bunch of error banners)
- Mouseover distribute step highlights all wells
> fix(protocol-designer): fix whitescreen upon creating new file

- components/src/nav/NavButton.js
- components/src/nav/NavButton.md
- protocol-designer/src/containers/ConnectedNav.js
Closes #1505
- Add `selected` prop to NavButton, update complib NavButton.md
There used to be `isCurrent` but it got removed?
Run App should be unaffected, PD should have selected styles on current page
Does not fix bug #1561 - I wanna map out all the page-like things, forms, modals, and modes before figuring out a cleaner way to handle out navigation. This is just a style PR
> feat(protocol-designer): pd & components: selected prop on NavButton

- app/src/components/ChangePipette/ConfirmPipette.js
- app/src/components/ChangePipette/Instructions.js
- app/src/components/ChangePipette/PipetteSelection.js
- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/types.js
- shared-data/js/pipettes.js
This PR is also serving as the bug ticket for this regression.
#1474 introduced changes to `shared-data` that were incompatible with the app's change pipette wizard. This PR updates the app's usage of pipettes from `shared-data` to fix change pipette.
- fix(app): Fix change pipette with v1.3 pipette models
Please test change pipette with a real robot. If at all possible (I'm not sure if there are any in the office) please try with a `v1.3` pipette (@andySigler has informed me that P50's should be `1.3`)
Previously, the change pipette route for a given pipette would be:
```
.../:mount/:model
```
But because more than one model may match a given selection (e.g. "P300 Single-channel"), we've switched it to:
```
.../:mount/:name
```
And the app now checks the attached pipette against …
> fix(app): Fix change pipette with v1.3 pipette models

- app/src/components/RobotSettings/InformationCard.js
This PR adds an entry for firmware version to the Information card on the Robot Settings page.
Checks off a checkbox in #1118 
- feat(app): Add firmware version to robot settings page
1. Open app
2. Click on a robot
3. Look at the firmware version
> feat(app): Add firmware version to robot settings page

- app/src/analytics/__tests__/make-event.test.js
- app/src/analytics/make-event.js
This PR closes #1553 by adding level 2 priority tracking events and tests to the app.
- add protocolUpload, runPause, runError, runCancel events and tests
- Get Mixpanel user ID from debug logs or config file, or Alfie. replace `correct_mixpanel_id` in following command to run the app.
- `make dev OT_APP_MIXPANEL_ID=correct_mixpanel_id OT_APP_ANALYTICS__OPTED_IN=1`
- watch console for logged events!
**Upload Event:**
Upload a protocol without errors (upload successful)
Upload a protocol errors (upload errors)
**Run Events:**
> feat(app): Add priority 2 analytics events

- app/src/robot/reducer/calibration.js
- app/src/robot/test/calibration-reducer.test.js
This PR closes #1620. Now, if a user calibrates any labware and then runs a tip probe, labware calibration progress will be reset. Why? So we always have a tip on the pipette when we calibrate labware.
-fix(app): Tip probe response clears out `confirmedBySlot`
- Load a protocol
- Calibrate all tipracks (disabled in side panel)
- Run a tip probe
> fix(app): Tip probe clears labware calibration progress

- protocol-designer/src/containers/ConnectedTitleBar.js
This adds some explanatory text to the page title that shows when the desk setup step is selected. 
It also consolidates the logic in the `ConnectedTitleBar`'s complex mapping of state to props.
Closes #1339
> feat(protocol-designer): elaborate on deck setup in title bar

- CONTRIBUTING.md
- Makefile
- api-server-lib/MANIFEST.in
- api-server-lib/Makefile
- api-server-lib/Pipfile
- api-server-lib/Pipfile.lock
- api-server-lib/README.md
- api-server-lib/ot2serverlib/__init__.py
- api-server-lib/ot2serverlib/endpoints.py
- api-server-lib/ot2serverlib/package.json
- api-server-lib/setup.cfg
- api-server-lib/setup.py
- api/Pipfile
- api/opentrons/broker/broker.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/drivers/temp_deck/driver.py
- api/opentrons/instruments/pipette.py
- api/opentrons/server/endpoints/control.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_update_endpoints.py
- architecture-and-planning/backend-architecture.md
- package.json
Separate update endpoints into a library that can be imported by both the Update Server and the API Server, to ensure they stay the same. Fixes #1642 
- refactor(api): Separate endpoints into a library to be shared with update server
Tested on 🌔 🌔 , update to this version works and runs protocols as normal, and API accepts successive updates. This PR is a little long, but there are actually *no* changes in functionality. Code moves to new files, unused variables are removed to fix lint errors [that I'm not sure why they passed before], and added a bunch of documentation and install boilerplate. The only new thing that is really of note is the `push-api` task in the repo-level Makefile.
> refactor(api): Separate endpoints into a library to be shared with update server

- protocol-designer/src/components/LabwareDropdown.css
Make font color, in the labware selection modal, standard font-dark.
Closes #1341
> feat(protocol-designer): Darken font in labware selection modal

- app/src/components/CalibrateDeck/ErrorModal.js
- app/src/components/CalibrateDeck/styles.css
This PR addresses #1641 and updates the text and styling of the error modal in deck calibration. Currently, the error modal is just a fallback error modal during startRequest. The error modal close button directs users back to robot settings page.  Error modal is an alertOverlay to ensure it renders over calibrate deck modals. Implementation in deck calibration steps to come in follow up PR.
- refactor ErrorAlertModal 
This is just a text and style update. 
To view error modal in deck calibration comment out lines 
57- 64 in `app/src/components/CalibrateDeck/index.js` and begin deck calibration from robot settings page.
> refactor(app): Update deck calibration error modal

- api-server-lib/Makefile
- api-server-lib/ot2serverlib/__init__.py
- api-server-lib/ot2serverlib/endpoints.py
- api/opentrons/server/endpoints/serverlib_fallback.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_update_endpoints.py
Add fallback code for update endpoints, in case `ot2serverlib` is not installed. Make endpoints able to install "whl", "serverlib", and "fw" (see updated endpoint documentation).
- fix(api): Add fallback code for update endpoints, in case `ot2serverlib` is not installed
Tested on 🌔 🌔 for backward compatibility (multiple updates without `ot2serverlib` installed)
> fix(api): Fallback for update endpoints

- app-shell/lib/menu.js
This PR removes the Reload option from the View menu if devtools are not active. Given that we still have improper `throw`s in render paths that will break reloads, this is a more appropriate solution than #1640.
Fixes #1618
- fix(app-shell): Remove Reload from View menu unless devtools are active
> fix(app-shell): Remove Reload from View menu unless devtools are active

- .github/ISSUE_TEMPLATE.md
The "behavior" header in our issues template trips me up every time.
- Update GH issue template: current behavor / expected behavior instead of 'behavior'
- Also update link to CONTRIBUTING.md (`edge` not `v3a`)
Clearer?
> chore(github): update github issue template headers

- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/top-selectors/well-contents/index.js
Fix a bug where **multi-channel** transfer/distribute/consolidate substeps were always showing only the ingredients in the "first" tip of the multichannel (eg A-row in 96 plate).
Now each tip should show the correct ingredients for the well that tip accesses.
- fix bug with multi-channel substep ingredients only showing ingredients for first tip
- All variants of 8-channel access should render substeps correctly for 8-channel pipette transfer-like steps: 96 flat, 384 plate, trough
> Fix bug with multichannel substep display

- app-shell/lib/main.js
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/AppSettings/index.js
- app/src/config/index.js
This PR addresses #1632 (last checkbox) User can toggle app-level feature flags in the App 'Advanced Settings' section.
- Add advanced settings to app settings page
- Enable toggling devtools in app
- Run `make -C app-shell` in root
- Open app build from `./app-shell/dist/YOUR_OS/Opentrons`
> feat(app): Toggle devtools feature flag in app settings

- app/src/__tests__/util.test.js
- app/src/components/CalibrateDeck/ErrorModal.js
- app/src/components/CalibrateDeck/InstructionsModal.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/styles.css
- app/src/robot/actions.js
- app/src/util.js
This PR adds some chaining logic to the API calls in deck calibration to ensure that if a given API call errors, deck calibration is stopped.
Closes #1641
- feat(app): Capture and display errors during deck calibration 
First off, don't be scared by the diff count. It's mostly a unit test file. Second off:
1. Start deck calibration with a robot
- This doesn't work well with Virtual Smoothie without `driver_3_0.py` modifications
2. Induce some sort of failure (e.g. turn the robot off)
I've written a fairly straightforward chainer (implemented as a thunk action) for the types of actions we use in the app:
1. Plain actions
2. Thunk actions (that return a maybe action)
- e.g. a thunk that needs to put something from state into a payload
3. Thunk actions that return a Promise (that resolves to …
> feat(app): Capture and display errors during deck calibration

- app-shell/Makefile
- app-shell/electron-builder.json
- app-shell/lib/api-update.js
- app-shell/lib/main.js
- app/src/http-api-client/server.js
This PR adds additional files to the payload of the `POST /server/update` call:
- API server lib wheel (to update the server lib)
- Smoothie firmware hex (to update smoothie)
After merging, clicking "Update" in the app for a robot will update the API, the API support library, and Smoothie, so this PR closes #1115
- feat(app): Pass server-lib and firmware to /server/update 
Tested on Sunset. Does not work with Virtual Smoothie (endpoint `500`s on Smoothie firmware update, which makes sense).
1. Check out an older: `git checkout v3.1.1`
2. Downgrade a robot: `make -C api push flash restart`
3. `git checkout app-shell_bundle-updates `
4. `make -C app-shell` (Ensure all wheels are built)
3. Open app, go to robot settings page, click Update
- After restart (and possibly an info card refresh) …
> feat(app): Pass server-lib and firmware to /server/update

- app/src/robot/reducer/calibration.js
- app/src/robot/test/session-reducer.test.js
This PR fixes #1597 by resetting labware calibration on session refresh. Tipracks are re-enabled and other labware is disabled until tipracks are calibrated again.
-fix(app): Reset calibration state on reset run
- calibrate labware (tipracks in particular)
- run a protocol to completion or cancel
- click reset run
- navigate back to calibrate screen
> fix(app): Reset calibration state on reset run

- api/opentrons/__init__.py
- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
This PR also serving as the bug ticket.
As reported by @HenryOpentrons, the app was reporting that an incorrect pipette was attached in the Tip Probe screen even if the correct pipette was attached. Upon further investigation, this was only happening with `v1.3` pipettes, and was due to the fact that the RPC API was _always_ reporting pipettes used in the protocol as `v1` pipettes, regardless of what was attached to the robot.
- fix(api): Fix RPC reporting wrong models for v1.3 pipettes
- Removed redundant `is_simulating` check for retrieving correct model string of pipettes created from config
- Added attached pipette caching call prior to RPC protocol simulation to ensure proper pipette models were picked up
I've tested this on Sunset with a `v1.3` P50. We need to ensure:
> fix(api): Fix RPC reporting wrong models for v1.3 pipettes

- api-server-lib/ot2serverlib/endpoints.py
- api-server-lib/ot2serverlib/ignore_update.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_update_endpoints.py
Closes #1624. Provides two endpoints, a getter and setter, to handle returning the currently ignored update. Tested on young- 🌔 
- Adds GET request under /server/update/ignore
- Adds POST request under /server/update/ignore which is formatted as:
{'IgnoreStatus': 'True or False', 'IgnoredVersion': 'Version String'}
@Kadee80 does this implementation make sense? Any other use cases to return something other than status 200?
> feat(api): Add endpoints to handle API update ignores

- protocol-designer/README.md
- protocol-designer/webpack.config.js
This is a super basic fast path to hiding the warnings we're going to make from showing production until they're ready. Copied small part of the pattern from app's config.
- basic env var plugging in
- Clean out old README and add section for keeping track of env vars
If you go to something like `protocol-designer/src/components/App.js` and do `console.log('env var test', process.env.OT_PD_SOMETHING)` then do ` OT_PD_SOMETHING=spam make dev`, you should see `'env var test', 'spam'` in the console
> chore(protocol-designer): support ultra-minimal feature flags

- app/src/components/RobotSettings/ConnectBanner.js
- app/src/pages/Robots.js
This PR closes #1314. Will open a separate issue for connectRequest error banner.
- feat(app): Show connect alert banner on successful connection
> feat(app): Show connect alert banner on successful connection

- .github/PULL_REQUEST_TEMPLATE.md
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
#1701 reminded me that some `OpenTrons` not `Opentrons` lines still exist -- they're mostly in the outdated API docs, but I fixed the ones in PD.
Also tossed in changing the last remaining `v3a` to `edge` in PULL_REQUEST_TEMPLATE.
@mcous is it OK to edit PD's CHANGELOG like this? Or should I leave CHANGELOG and just change package.json, and it will correct it when it builds the next CHANGELOG?
> chore(*): OpenTrons -> Opentrons; v3a -> edge

- api/opentrons/drivers/rpi_drivers/gpio.py
- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/opentrons/robot/robot.py
- api/opentrons/server/endpoints/control.py
- api/opentrons/server/main.py
This PR reworks the rail lights endpoints so we'll be able to satisfy #1684. It's also serving as the ticket because additional API work for #1684 was not anticipated.
- refactor(api): Move lights endpoints to /robot/lights and provide getter 
This branch is currently pushed to Sunset
> refactor(api): Move lights endpoints to /robot/lights and provide getter

- app/src/components/RobotSettings/ControlsCard.js
- app/src/http-api-client/__tests__/robot.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/robot.js
- components/src/structure/RefreshCard.js
This PR wires the lights toggle UI from #1708 to the `/robot/lights` endpoint from #1709 so that the user can turn their robot's lights on and off.
Closes #1684
- feat(app): Add toggle to turn on/off robot rail light
Try it out with a robot! Does not work with Virtual Smoothie. Sunset is up to date with the necessary endpoints
> feat(app): Add toggle to turn on/off robot rail lights

- components/src/styles/colors.css
- protocol-designer/src/components/SelectionRect.css
SelectionRect fill color broke in an earlier CSS refactor, this PR fixes it & update colors to match the design (before it broke, it was slightly different eg had dashed stroke instead of solid stroke)
- update styles for SelectionRect
should match picture
> fix(protocol-designer): fix styles for SelectionRect

- api/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
This PR fixes a bug with older p50 pipettes not being recognized by the robot.
A small subset of p50 pipettes were written with model strings ending with `"v13"` instead of the currently used format `"v1.3"`. The driver's `read_pipette_model()` method was intending to replace those old substrings with the new one, but was replacing with an invalid string (missing the underscore)
> fix(api): Fixes bug in replacing substring of old p50 pipettes

- protocol-designer/src/containers/Alerts.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-generation/aspirate.js
- protocol-designer/src/step-generation/aspirateUpdateLiquidState.js
- protocol-designer/src/step-generation/dispenseUpdateLiquidState.js
- protocol-designer/src/step-generation/test-with-flow/aspirate.test.js
- protocol-designer/src/step-generation/test-with-flow/aspirateUpdateLiquidState.test.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
- protocol-designer/src/step-generation/warningCreators.js
- protocol-designer/src/steplist/formProcessing.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/reducers.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/well-contents/index.js
Closes #1089 and closes #1697
1. This PR separates concerns of validating step forms vs creating a "timeline" data object from an array of CommandCreators. Instead of the timeline being created inside the `robotStateTimeline` selector in `file-data`, that logic is moved to `commandCreatorsTimeline`, simplifying the `robotStateTimeline` selector
2. This PR creates a new `warnings` pipeline for *timeline-level warnings*.
3. To show that the warning pipeline works, this PR also includes the first warning in PD: "Not enough liquid in well(s)" when the user aspirates more liquid from a well than the well contains.
Unlike timeline-level errors, warnings do not stop timeline creation pipeline. They indicate to the user that something may or may not have gone wrong, and the protocol may still be …
> PD timeline warnings: not enough liquid in well

- protocol-designer/src/components/StepEditForm/FormSection.js
- protocol-designer/src/components/StepEditForm/MixForm.js
- protocol-designer/src/components/StepEditForm/PauseForm.js
- protocol-designer/src/components/StepEditForm/TransferLikeForm.js
- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/components/StepEditForm/index.js
The step edit form contained a lot of type-specific form logic that could be abstracted away. In
order to accomplish an ideal generalized solution for step form validation, the component needed to
be reorganized. Furthermore, instead of acting as a single connected parent to far downstream
components that might want data from redux. This adds connected leaf components that partition those
props to the field that needs them, and away from the general clutter in the Step Edit Form.
-Try creating a step of each type and switching all the editable fields.
- make sure that the values persist when you navigate to a different step and back
> refactor(protocol-designer): Split up step edit form logic into types

- app/src/components/LabwareCalibration/styles.css
- app/src/components/Page/index.js
- app/src/components/Page/styles.css
- components/src/modals/modals.css
- components/src/styles/positioning.css
This PR fixes the alignment issues introduced by #1705. Some modal page titlebars had been cropped. This should standardize behavior once and for all. Worth noting labware calibration uses a spinner modal as modal page content, not the SpinnerModalPage component from comp_lib so a little css override in `LabwareCalibration` was necessary.  While I was in there, I made the TitleBar position fixed.
- comp_lib update ModalPage styles
- app fixed titlebar when in page
- center spinner modal positioning in `LabwareCalibration`
Please click though any and all modals in the app, some are not accessible in VS so a Robot is preferred.
> fix(app): Fix alignment issues in modals, fix titlebar on page

- app/src/components/RobotSettings/InformationCard.js
- app/src/components/RobotSettings/UpdateModal.js
This PR is also serving as the ticket. With the addition of firmware updates in the robot update flow, we ran into an issue where sometimes, the firmware would not update (for various valid / invalid reasons). However, because the API update usually succeeds, `/health` would report that the robot was up to date, and the update button would become disabled. This would then remove any firmware upgrade path from the user until the next API update.
Until we figure out a more refined approach to separating and communicating smoothie firmware, this PR removes the button disable logic and allows the user to send the update request even if the robot appears up to date.
- fix(app): Enable robot update even if API reports up-to-date 
Tested on Sunset. Robot update should work even if robot is …
> fix(app): Enable robot update even if API reports up-to-date

- app/src/index.js
During `3.2.0-beta.1` testing on Windows 7, we discovered that `react-router-redux`'s `goBack` action breaks in prod on Windows 7 by trying to goBack to a `file:` URL. This PR switches to hash routes to avoid this issue.
This PR serving as the bug report and the fix.
- fix(app): Switch to hash routes to enable reload in prod 
I'll be testing this with our Win 7 machine on Sunset.
> fix(app): Switch to hash routes to fix back in prod on Win 7

- CHANGELOG.md
- api-server-lib/ot2serverlib/CHANGELOG.md
- api-server-lib/ot2serverlib/package.json
- api/opentrons/CHANGELOG.md
- api/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
This PR bumps to `3.2.0-beta.1`
* **api:** Add ignore update endpoint implementation to fallback file ([#1720](https://github.com/Opentrons/opentrons/issues/1720)) ([2a68dc5](https://github.com/Opentrons/opentrons/commit/2a68dc5))
* **api:** Fix RPC reporting wrong models for v1.3 pipettes ([#1691](https://github.com/Opentrons/opentrons/issues/1691)) ([e302382](https://github.com/Opentrons/opentrons/commit/e302382))
* **api:** Fixes bug in replacing substring of old p50 pipettes written with v13 instead of v1.3 ([#1717](https://github.com/Opentrons/opentrons/issues/1717)) ([1322055](https://github.com/Opentrons/opentrons/commit/1322055))
* **app:** Enable robot update even if API reports up-to-date ([#1721](https://github.com/Opentrons/opentrons/issues/1721)) …
> chore(release): 3.2.0-beta.1

- components/src/forms/forms.css
- protocol-designer/src/components/IngredientPropertiesForm.js
Disallow saving Ingredient Properties Form w/o name & valid volume. Also show field-level errors
Closes #1609
Also closes #1671 
- disable saving ingred props form w/o name & volume > 0
- show field-level errors
- COMPONENT LIBRARY: add some padding-top to the `InputField` captions, the new drop shadow overlaps them without it
`IngredientPropertiesForm` overall needs a big refactor, but hopefully the new structures in `StepEditForm` can be applied here & we can trash all the `this.Field` junk down the road!
So this is a somewhat ugly, non-scalable fix to make UX for ingred properties form work as desired, for now.
@mcous @Kadee80 do you use the `caption` of `InputField`? Is this padding-top addition OK?
> feat(protocol-designer): disallow saving ingred form w/o name & volume

- api/opentrons/server/main.py
Log API server and Smoothie FW versions on API server boot. Fixes #1120
- Add log of API server and Smoothie FW versions to API server boot
`make -C api dev` and see that the versions are logged
> feat(api): Log API server and Smoothie FW versions on API server boot

- api/opentrons/server/endpoints/wifi.py
This PR is a bug report and a fix.
We received a report of a user being unable to connect to WiFi even with correct credentials. We were unable to get the actual error message the app was receiving, but we know the PSK had a `$` in it. Our inputs to `nmcli` are completely unsanitized aside from being wrapped in double-quotes, which (in addition to being a security hole) means they won't handle SSIDs or PSKs with various "special" characters.
This PR uses the [`shlex.quote`](https://docs.python.org/dev/library/shlex.html#shlex.quote) builtin to properly sanitize the ssid and psk inputs before passing them to `nmcli`
- fix(api): Sanitize wifi inputs to handle special characters
Please ensure the WiFi configure endpoint is still functional on real robots!
> fix(api): Sanitize wifi inputs to handle special characters

- components/src/buttons/Button.js
- components/src/buttons/buttons.css
- protocol-designer/src/components/StepEditForm/FormSection.css
- protocol-designer/src/components/StepEditForm/FormSection.js
- protocol-designer/src/css/reset.css
Closes #1690
- components: buttons can take `hover` prop to appear hovered
- protocol-designer: update design of FormSection's toggle-collapse button
- protocol-designer: global reset of browser default blue button outline
:monkey:
> feat(protocol-designer): allow button to look hovered via .hover class

- api/opentrons/containers/__init__.py
- api/tests/opentrons/containers/test_labware_fns.py
- api/tests/opentrons/database/test_labware_definitions.py
Fix row order in `labware.create`. Fixes #1748
- Reverse row order in `labware.create` so that the top row is A
See steps to reproduce in attached bug ticket
> fix(api): Fix row order in labware.create

- app/src/components/RobotSettings/UpdateModal.js
- app/src/pages/Robots.js
- components/src/modals/Overlay.js
#1726 and #1745 introduced some bugs in how modals are(n't) displayed on the robot settings page. This PR / bug ticket fixes those bugs up.
- fix(app): Fix overlay and redirect duplication in robot settings page
> fix(app): Fix overlay and redirect duplication in robot settings page

- protocol-designer/src/components/StepEditForm/formFields.js
- protocol-designer/src/components/modals/NewFileModal.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/containers/ConnectedStepEditForm.js
- protocol-designer/src/containers/ConnectedWellSelectionModal.js
- protocol-designer/src/file-data/actions.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/index.js
- protocol-designer/src/pipettes/actions.js
- protocol-designer/src/pipettes/index.js
- protocol-designer/src/pipettes/pipetteData.js
- protocol-designer/src/pipettes/reducers.js
- protocol-designer/src/pipettes/selectors.js
- protocol-designer/src/pipettes/types.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/types.js
- protocol-designer/src/well-selection/actions.js
This is a big ol' diff but it's just taking pipette-related concerns out of `file-data/` and into a new atom `pipettes/`. Nothing should be changed for now except `fileData.pipettes` state is now in `pipettes.pipettes`
- factor out `pipettes/` from `file-data/`
- alphabetize some imports
On UI side, nothing should look/act different.
> refactor(protocol-designer): move pipettes into own dir (Tiprack assignment part 1!)

- app/src/__tests__/util.test.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/RobotSettings/InformationCard.js
- app/src/util.js
This PR reorganizes the action chain on "Exit" click during deck calibration so that the homing spinner from #1726 gets shows during DC exit.
Closes #1613
- fix(app): Show spinner during home on deck calibration exit 
Required some tweaks in the bespoke action chaining util to handle the fact that the (now deprecated) react-router-redux middleware swallows route change actions rather than returning them, which goes against redux conventions and results in `dispatch(push(path))` returning `undefined` rather that the `push` object. Hurray.
Tested on Sunset and looks good to me
> fix(app): Show spinner during home on deck calibration exit

- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/steplist/actions/actions.js
Closes #1681
- StepItems can be toggled collapsed/expanded, even when selected
- Basic review :baby:
> feat(protocol-designer): user can collapse selected StepItem

- protocol-designer/src/components/LabwareDropdown.js
- protocol-designer/src/components/modals/NewFileModal.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/containers/LabwareDropdown.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/pipettes/actions.js
- protocol-designer/src/pipettes/index.js
- protocol-designer/src/pipettes/reducers.js
- protocol-designer/src/pipettes/selectors.js
- protocol-designer/src/pipettes/types.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/types.js
Addresses UI parts of #1573 ("get next tip" selector is blocked by labware definitions lacking tip volume, so PD continues to use existing "get next tip" behavior -- which doesn't work right with 2 pipettes)
- User can select tiprack model for pipette in New File modal
- User can only add tipracks that have been selected there to the deck, other tip rack options are not shown in the Add Labware modal/list
- In New File modal, tiprack model dropdown clears if you set corresponding Pipette dropdown to None
- When adding labware, you should only be able to select the 1 or 2 tiprack types that have been assigned to pipettes (but since we don't have GEB 300 tips in the dropdown yet, those don't show up as an option to add. ~That will be in the next PR.~ GEB tips aren't actually supported in …
> Pd pipette tip assignment: Part 2

- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/index.js
This PR addresses #1632 and #1727 by adding an advanced settings card to Robot page with a disabled download logs section.
- feat(app): Add advanced settings card to robot settings page
Standard review. This ones super small and UI only.
> feat(app): Add advanced settings card to robot settings page

- protocol-designer/src/components/modals/NewFileModal.css
- protocol-designer/src/components/modals/NewFileModal/NewFileModal.css
- protocol-designer/src/components/modals/NewFileModal/PipetteDiagram.js
- protocol-designer/src/components/modals/NewFileModal/TiprackDiagram.js
- protocol-designer/src/components/modals/NewFileModal/index.js
Closes #1695
- add new tiprack + pipette diagrams & copy to New File modal
- Tipracks are not styled correctly, look very similar to plates. I'm going to fix that in my next PR
> feat(protocol-designer): add diagrams & copy to new file modal

- app/src/components/JogControls/index.js
- components/src/interaction-enhancers/HandleKeypress.js
Previously, `<HandleKeypress>` would call `event.preventDefault` if the keypress event matched one of its handlers. This is necessary functionality for its current use in the app (to prevent jog step size radio button shenanigans on arrow key presses), but should've been configurable. This PR makes the prevent default functionality opt-in.
Closes #1764
- fix(components): Make preventDefault call in HandleKeypress opt-in
> fix(components): Make preventDefault call in HandleKeypress opt-in

- .dockerignore
- .travis.yml
- CONTRIBUTING.md
- Dockerfile
- Makefile
- compute/conf/nginx.conf
- compute/scripts/setup.sh
- compute/scripts/start.sh
- package.json
- update-server/MANIFEST.in
- update-server/Makefile
- update-server/Pipfile
- update-server/Pipfile.lock
- update-server/README.md
- update-server/otupdate/__init__.py
- update-server/otupdate/__main__.py
- update-server/otupdate/bootstrap.py
- update-server/otupdate/endpoints.py
- update-server/otupdate/package.json
- update-server/otupdate/selftest.py
- update-server/setup.cfg
- update-server/setup.py
- update-server/tests/conftest.py
- update-server/tests/test_bootstrap_fns.py
- update-server/tests/test_server_boot.py
- update-server/updateServerDesignNotes.md
Core update server, currently able to update itself safely. Notably missing: restart endpoint, and api and fw update endpoints. Those are out of scope for this PR. Fixes #1208 
- Added update server sub-project to repo
- Added self-update endpoint in update server, with safety check in sandboxed environment
- Added health endpoint to provide versions of all robot software
Has been tested on 🌔 🌔 and is able to boostrap itself (installing successive updates over itself properly, and rejecting ones that fail to boot or accept subsequent updates).
Note that this will have no effect on running robots until the Dockerfile is updated, and that follow-up PRs need to be completed to add API and FW update and restart endpoints before this application will be ready to ship.
> feat(update-server): Add basic update server

- app/src/components/RobotSettings/ConnectivityCard.js
- app/src/components/RobotSettings/WifiConnectForm.js
- app/src/components/RobotSettings/WifiConnectModal.js
- app/src/components/RobotSettings/styles.css
- app/src/http-api-client/__tests__/wifi.test.js
- app/src/http-api-client/index.js
- app/src/http-api-client/wifi.js
This PR serving as both a ticket and a fix.
WiFi card no longer disables the submit button arbitrarily and more obviously communicates which WiFi network is currently connected. We also now display the `nmcli` error message (if we get an error) to help out the support team.
* Connected to WiFi
* Note that "Connected" button still allows the user to re-submit a password just in case
* Trying to join a new network while connected over WiFi
* Note button is no longer disabled even though we're not on USB
* Failed connect
* Note the `nmcli` error message and generic `<ErrorModal>`
- fix(app): Make WiFi card more lenient and understandable
> fix(app): Make WiFi card more lenient and understandable

- app/src/components/TipProbe/ContinuePanel.js
- app/src/components/calibrate-pipettes/PipetteTabs.js
- app/src/pages/Calibrate/Pipettes.js
This PR is a continuation of #1765. We missed a couple links that were still pointing to `/calibrate/instruments` instead of the newer `/calibrate/pipettes`
- fix(app): Remove holdover /calibrate/instruments missed by #1765 
Try to break tip probe and labware calibration! Virtual smoothie is fine
> fix(app): Remove holdover /calibrate/instruments missed by #1765

- protocol-designer/src/components/FilePage.js
Before, clicking "Update" button on FilePage's form (not the New File modal, but the "Information" name/author/desc form) would navigate away to `http://localhost:8080/?#/` and refresh the page!
- fix: do not navigate on FilePage form submit
No more navigation/refresh on clicking "Update"
:palm_tree:
> fix(protocol-designer): do not navigate on FilePage form submit

- api-server-lib/ot2serverlib/endpoints.py
- api/opentrons/server/endpoints/serverlib_fallback.py
- update-server/Makefile
- update-server/otupdate/__init__.py
- update-server/otupdate/control.py
- update-server/tests/test_server_boot.py
Add restart endpoint to Update Server and shorten restart sleep to 1s
Fixes #1792
- Add `POST /server/update/restart` to Update Server
- Shorten restart sleep to 1s
Tested on 🌔 🌔 and unit tests passing locally
> feat(update-server): Add restart endpoint to Update Server and shorten sleep

- api/opentrons/config/advanced_settings.py
- api/opentrons/config/feature_flags.py
- api/opentrons/server/endpoints/__init__.py
- api/opentrons/server/endpoints/serverlib_fallback.py
- api/opentrons/server/endpoints/update.py
- api/opentrons/server/main.py
- api/tests/opentrons/cli/test_cli.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_settings_endpoints.py
- api/tests/opentrons/server/test_update_endpoints.py
Add advanced settings endpoints to api server. Also added an lru_cache decorator to the "splitLabwareDefinitions" feature flag to reduce unnecessary disk IO (this is preferred anyway, as changing from old to new labware definitions without a reboot causes exceptions). 
Fixes #1656
Test on robot that previously had a feature flag set to True, ensure that it remains True in new endpoint
> feat(api): Add advanced settings endpoints to api server

- api/opentrons/drivers/temp_deck/driver.py
- api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py
This PR enables Temp-Deck's API driver to set/get temperatures as floating point.
The temp-deck driver was previously casting all temperatures to integers (both read-from and sent-to), however the temp-deck accepts floating point temperatures, as well as reports it's own temperature as a floating-point value with 3 decimal places.
[Documentation of Temp-Deck gcodes and argument scan be found in it's readme](https://github.com/Opentrons/opentrons-modules/tree/edge/modules/temp-deck#set-temperature)
> fix(api): Allows floating-point temperatures

- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/http-api-client/__tests__/settings.test.js
- app/src/http-api-client/actions.js
- app/src/http-api-client/index.js
- app/src/http-api-client/settings.js
- app/src/http-api-client/types.js
This PR is the front-end companion to #1786. It wires up `/settings` to the app.
Closes #1632
- feat(app): Add robot settings toggles to Advanced Settings card 
Sorry this PR is so large; it's mostly API client boilerplate and tests. I started work on a boilerplate reduction in this PR by creating generic API action creators (see `http-api-client/actions.js`). There's a path forward where all the reducers in each client module (e.g. `calibration`) are removed in favor of a monolithic one. Talk to me in real life if you're interested.
Otherwise, give this a shot on any robot that's update to date with `edge` from today (e.g. Sunset)
> feat(app): Add robot settings toggles to Advanced Settings card

- protocol-designer/src/dismiss/selectors.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
Closes #1789 
- save additional PD metadata fields: dismissedWarnings, ingredients, ingredLocations, savedStepForms, and orderedSteps to JSON Protocol File
Are we still Missing any data? Well, we'll see in the next PR where these saved fields are actually used :)
> PD: download file with all metadata PD will need to load

- protocol-designer/src/components/modals/NewFileModal/NewFileModal.css
Closes #1776
- fix NewProtocolModal height
Should modals do this by default?
> fix(protocol-designer): allow scroll when NewFileModal too tall

- Makefile
Remove lerna from test commands for Python sub-projects. This was meant to not run python tests on branches that do not have changes in those projects. This both fails to work on CI (though it does work on developers computers), and risks not running tests at all on `edge` builds.
- Remove lerna from test commands for Python sub-projects
Make sure all CI task that should execute do so
> build(repo): Remove lerna from test commands for Python sub-projects

- app/src/components/DeckMap/styles.css
- components/src/deck/Deck.js
- components/src/deck/constants.js
- protocol-designer/src/constants.js
- protocol-designer/src/containers/ConnectedDeckSetup.js
- protocol-designer/src/containers/Deck.css
Deck component SVG had a viewBox calculated from slot width, height, and spacing. Since the deck is actually bigger than that, this PR just uses hard-coded height and width to set the viewBox to the actual bounds of the Deck SVG.
- fix Deck SVG viewBox
- update Deck styles in PD
- update DeckMap styles in Run App
> fix(components): fix Deck component viewBox

- api/opentrons/robot/robot.py
Remove an extraneous call to `cache_instrument_models` that caused pipette model cache to be invalidated and fall back to default. Fixes #1805 
Remove call to `cache_instrument_models` in pipette
Tested on Sunset
> fix(api): Remove incorrect call to `cache_instrument_models`

- app/src/components/InstrumentSettings/AttachedPipettesCard.js
- app/src/http-api-client/__tests__/robot.test.js
- app/src/http-api-client/actions.js
- app/src/http-api-client/index.js
- app/src/http-api-client/robot.js
- app/src/http-api-client/settings.js
Following up on work started in #1795, this PR converts the `/robots` HTTP API client module to use the new generic API actions in preparation for a single API client reducer.
Three of the existing modules have code that doesn't fit cleanly into a generic reducer, and `robot.js` is one of them. I'm going to follow up with two more refactor PRs (one for `calibration.js` and one for `health-check.js`) before doing the reducer refactor to keep things sane.
- refactor(app): Convert robot HTTP API client module to generic API actions
The `/robot` enpoints are used for
- Lights toggle
- Home button
- Pipette swap
Please make sure all of them still work properly. Tested on Sunset and it looked good. VS should work, too (although VS does funky stuff with `/robot/lights`, which is out of scope)
> refactor(app): Convert /robot HTTP API module to generic API actions

- app/src/components/CalibrateDeck/ConfirmPosition.js
- app/src/components/CalibrateDeck/index.js
- app/src/components/CalibrateDeck/types.js
- app/src/components/CalibrateLabware/ConfirmPositionContents.js
- app/src/components/JogControls/index.js
- app/src/http-api-client/__tests__/calibration.test.js
- app/src/http-api-client/calibration.js
- app/src/http-api-client/index.js
- app/src/http-api-client/robot.js
- app/src/http-api-client/settings.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/calibration.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
This PR removes the `calibration.js` module specific `api:CAL_REQUEST`, etc actions in favor of
the new, generic `api:REQUEST`, etc actions. Making the calibration module more generic also meant moving the jog step size out of redux and into the state of the `JogControls` component, as had been discussed with @b-cooper.
This PR is prep work for a `modules.js` API client module for #1735 and continues work started in #1813.
- refactor(app): Use generic actions in /calibration API module 
The following peices of logic have been touched, and we should verify all is still well:
- Happens whenever you click "Exit" in Deck Calibration
> refactor(app): Use generic actions in /calibration API module

- app/src/components/LostConnectionAlert/index.js
- app/src/config/index.js
- app/src/health-check/__tests__/health-check.test.js
- app/src/health-check/index.js
- app/src/http-api-client/__tests__/health.test.js
- app/src/http-api-client/__tests__/server.test.js
- app/src/http-api-client/client.js
- app/src/http-api-client/health.js
- app/src/http-api-client/index.js
- app/src/http-api-client/server.js
- app/src/index.js
- app/src/reducer.js
- app/src/robot/reducer/connection.js
- app/src/robot/test/connection-reducer.test.js
- app/src/types.js
This PR continues the work of #1813 and #1819 by switching the `/health` API client module over to generic API actions. As part of this effort, the `health-check` module was moved to be a sibling rather than child of the API reducer to separate the states in preparation for a simplified API reducer.
- refactor(app): Refactor /health modules to use generic API actions 
Stuff that was touched:
- I like to test this by connecting to a robot and then turning off wifi or killing the VS process
- I test this by bumping the version in `app-shell/package.json` before launching `make -C app dev`
I tested on Sunset and it looked good to me
This all l
> refactor(app): Refactor /health modules to use generic API actions

- .flowconfig
- app/src/components/nav-bar/NavButton.js
This PR is serving as the bug report and fix.
By moving the pipettes card to a different page in #1785, we lost a little side-effect we were relying on whereby clicking "Connect" would always open the "Pipettes" card, thereby ensuring that a `GET /pipettes` call had been made before the user eventually got to the "Calibrate" page. With pipettes on a separate page from the "Connect" button, the user can make it to "Calibrate" without `GET /pipettes` ever being called, resulting in an erroneous "Incorrect Pipettes Attached" warning message.
This PR adds a `GET /pipettes` call to the onClick handler of the "Calibrate" nav button to ensure we always have the pipette state we need before starting calibration.
- fix(app): Call GET /pipettes before starting calibration 
1. Connect to robot
2. …
> fix(app): Call GET /pipettes before starting calibration

- api-server-lib/ot2serverlib/endpoints.py
- api/opentrons/server/endpoints/serverlib_fallback.py
- update-server/Makefile
- update-server/otupdate/__init__.py
- update-server/otupdate/bootstrap.py
- update-server/otupdate/endpoints.py
- update-server/otupdate/install.py
- update-server/otupdate/selftest.py
- update-server/tests/test_bootstrap_fns.py
- update-server/tests/test_server_boot.py
Add endpoint for updating API server, ot2serverlib, and Smoothie FW, and make revisions for backward-compatibility with app/`make` software update commands. Fixes #1549 
Note about change in behavior: the update endpoint now checks the return code of install processes, and will return 400 if any wheel/hex files submitted fail to install
- Add endpoint for updating API server, ot2serverlib, and Smoothie FW
- Modify update-related routes for backward-compatibility with app/`make` software update commands
- Update endpoints check returncode of install processes
Tested on 🌔 🌔 and unit tests run locally
> feat(update-server): Add update endpoint 

- app/src/components/CalibrateLabware/ConfirmModalContents.js
- app/src/components/CalibrateLabware/ConfirmPickupContents.js
- app/src/components/CalibrateLabware/ConfirmPickupPrompt.js
- app/src/components/CalibrateLabware/ConfirmPositionContents.js
- app/src/components/CalibrateLabware/ConfirmPositionDiagram.js
- app/src/components/CalibratePanel/PipetteList.js
- app/src/components/CalibratePanel/PipetteListItem.js
- app/src/components/TipProbe/ContinuePanel.js
- app/src/components/TipProbe/index.js
- app/src/components/calibrate-pipettes/PipetteTabs.js
- app/src/components/calibrate-pipettes/Pipettes.js
- app/src/pages/Calibrate/Pipettes.js
- app/src/pages/Calibrate/index.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/constants.js
- app/src/robot/reducer/calibration.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/calibration-reducer.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
- app/src/robot/types.js
This PR is the follow up for #1765. Refactors the app selectors, actions, and types to refer to Pipettes and Pipettes rather than instruments to avoid future confusion once modules are in place.
- refactor(app): Refactor pipette selectors and types no longer use the term instrument
This one touched a lot of files, but its mainly types and selectors. Tested on Sunset. Please make sure everything still works on robot/VS.
> refactor(app): Refactor pipette selectors and types

- CHANGELOG.md
- api-server-lib/ot2serverlib/CHANGELOG.md
- api-server-lib/ot2serverlib/package.json
- api/opentrons/CHANGELOG.md
- api/opentrons/package.json
- app-shell/CHANGELOG.md
- app-shell/package.json
- app/CHANGELOG.md
- app/package.json
- components/CHANGELOG.md
- components/package.json
- lerna.json
- protocol-designer/CHANGELOG.md
- protocol-designer/package.json
- shared-data/CHANGELOG.md
- shared-data/package.json
- webpack-config/CHANGELOG.md
- webpack-config/package.json
This commit to be tagged as `v3.2.0` for release **prior to merge**. It re-releases the `v3.2.0-beta.3` as `v3.2.0` 
- Version bump only
This one is pretty well tested by our beta folks. Sanity checks are always good, though
> chore(release): 3.2.0

- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
This PR serving as a bug report and a fix.
The `getCalibrator` selector was incorrectly checking tip-probe status to decide if a pipette could be used for labware calibration. Since tip-probe is optional, this PR removes that check to make sure the correct pipette is used.
- fix(app): Remove tip-probed check in calibrator selector 
1. Load a protocol / robot with multi on left and single on right
2. Do not tip probe
3. Go through tiprack calibration so you end up with a tip on the right single channel pipette
4. Proceed to labware calibration
(Tested on Sunset)
> fix(app): Remove tip-probed check in calibrator selector

- api/opentrons/server/rpc.py
- api/tests/opentrons/server/test_server.py
- app/src/robot/api-client/index.js
- app/src/rpc/client.js
- app/src/rpc/remote-error.js
- app/src/rpc/test/client.test.js
This PR adds traceback reporting to the RPC server for failed remote calls and logs them in the app when they are passed over from the worker.
Closes #1841
- feat(app): Log tracebacks from failed RPC calls 
1. Launch app with devtools enabled
2. Load bad protocol onto virtual smoothie (or a robot with this branch pushed)
3. Load bad protocol onto robot that is on an earlier branch
>  feat(app): Log tracebacks from failed RPC calls 

- protocol-designer/src/step-generation/distribute.js
- protocol-designer/src/step-generation/test-with-flow/distribute.test.js
Closes #1763
- support distribute step when volume exceeds pipette max
Create a distribute step with a volume greater than the pipette max (eg P10 distributing 11uL). Instead of generating an empty step, it should act as expected.
> feat(protocol-designer): support distribute with volume over pipette max

- protocol-designer/src/dismiss/reducers.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/steplist/reducers.js
Closes #1604
Fully-functional file loading in PD!
- Enable populating steplist / step forms, ingredients and ingredient locations, labware, and dismissed warnings from a saved JSON Protocol file.
Does anything not load in a saved file that should be persisted?
Can you break it? Especially mess with selection states, adding and editing ingreds/labware/steps, deleting things.
NOTE: saved files from before didn't have all the fields and will not work. Make sure any saved files you test were saved from PD using this branch!
> PD: load file all metadata

- api/opentrons/server/endpoints/control.py
- api/opentrons/server/main.py
- api/tests/opentrons/server/test_control_endpoints.py
Add GET /modules endpoint with stub for module discovery (awaiting underlying implementation)
Related to #1831
- Add GET /modules endpoint with stub for module discovery
@Kadee80 does this unblock #1739 ? (and/or other modules FE work?)
> feat(api): Add GET /modules endpoint with stub for module discovery

- api/opentrons/drivers/mag_deck/__init__.py
- api/opentrons/drivers/mag_deck/driver.py
Add driver for for MagDeck. Closes #1809 
Adds the following driver methods:
```
connect(port)
disconnect()
is_connected()
home()
probe_plate()
move(distance_mm)
get_device_info()
enter_programming_mode()
```
And properties:
```
plate_height
mag_position
```
Please review if the functionality of the driver is as expected.
The hardware's current response for GET_CURRENT_POSITION is ``` Z<distance> ``` but this driver assumes ``` Z:<distance> ``` (note the colon). Requested a change of device response on opentrons-modules PR#15
> feat(api): Add Magdeck driver

- protocol-designer/src/components/FileSidebar/ConnectedFileSidebar.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/containers/ConnectedNewFileModal.js
- protocol-designer/src/dismiss/reducers.js
- protocol-designer/src/file-data/reducers/index.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/load-file/index.js
- protocol-designer/src/load-file/types.js
- protocol-designer/src/navigation/reducers/index.js
- protocol-designer/src/pipettes/actions.js
- protocol-designer/src/pipettes/reducers.js
- protocol-designer/src/steplist/reducers.js
Closes #970
- refactor load-file/ atom to be more standard
- remove UPDATE_PIPETTE action
- new CREATE_NEW_PROTOCOL action (replaces heavy mapDispatchToProps on
NewFileModal)
> feat(protocol-designer): clear everything when new protocol is created

- protocol-designer/src/labware-ingred/__tests__/containers.test.js
- protocol-designer/src/labware-ingred/__tests__/ingredients.test.js
- protocol-designer/src/labware-ingred/reducers/index.js
Closes #1616
- fix labware copying - no mirroring of name or ingredients
- update old COPY_LABWARE-related tests (had entirely wrong state shape -- good case for keeping Flow in tests!)
> fix(protocol-designer): fix labware copy mirroring

- protocol-designer/src/components/FileSidebar/ConnectedFileSidebar.js
- protocol-designer/src/components/FileSidebar/FileSidebar.js
Closes #967
- disable Download Protocol button (aka Export) when on the splash page
:radio:
> feat(protocol-designer): disable export button with no protocol

- protocol-designer/src/containers/LabwareContainer.js
Closes #1779
- remove "name labware" prompt for tipracks
> feat(protocol-designer): remove name labware prompt for tipracks

- protocol-designer/src/components/FileSidebar/ConnectedFileSidebar.js
- protocol-designer/src/components/FileSidebar/FileSidebar.js
- protocol-designer/src/index.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/load-file/reducers.js
- protocol-designer/src/load-file/selectors.js
Closes #1602
- uses unsavedChanges reducer to keep track of any actions that might clean or dirty the "saved" state of the protocol
:warning: **MUST HAVE `NODE_ENV === 'production'` for this to show up!** :warning: 
(In dev it's really annoying, because the onbeforeunload modal messes up hot reloading)
You could use the prod build here (after CI completes): https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_alert-unsaved-changes-1602/index.html
**Redux DevTools check:**
> feat(protocol-designer): alert user of unsaved changes to protocol

- protocol-designer/src/step-generation/replaceTip.js
- protocol-designer/src/step-generation/robotStateSelectors.js
- protocol-designer/src/step-generation/test-with-flow/replaceTip.test.js
- protocol-designer/src/step-generation/test-with-flow/robotStateSelectors.test.js
- protocol-designer/src/step-generation/types.js
Closes #1573
- `tiprackAssignment` key in RobotState
- `getNextTiprack` fn uses new `tiprackIsAvailableToPipette` so that `replaceTip` will not get tips from tipracks assigned to other pipettes
- add tiprack assignment cases to `replaceTip` tests
> feat(protocol-designer): support tiprack-to-pipette assignment

- components/src/constants.js
Closes #1862
- Well color order (when adding new ingredients) was blue, pink, green. now green, pink, blue.
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_swap-well-color-order-1862/index.html
> feat(protocol-designer): switch well order colors

- api/opentrons/instruments/pipette.py
Add `Pipette._shake_off_tips()` back to the end of a `drop_tip()` sequence, to help tips fully fall off.
This shaking is helpful for when tips are touching something while being dropped. Like for example, when touching the tip-rack when being returned, or when touching previously trashed tips in the trash box. This movement was inadvertently removed a couple of months ago, and is needed now for p1000 lifetime testing (because the tips/nozzles are bigger and therefore get stuck for more easily).
> feat(api): Brings back the shake after drop-tip

- protocol-designer/src/components/StepEditForm/FormAlerts.js
- protocol-designer/src/components/StepEditForm/helpers.js
- protocol-designer/src/components/steplist/TimelineAlerts.js
- protocol-designer/src/containers/Alerts.js
- protocol-designer/src/containers/ConnectedStepItem.js
- protocol-designer/src/dismiss/actions.js
- protocol-designer/src/dismiss/reducers.js
- protocol-designer/src/dismiss/selectors.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/load-file/reducers.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
- protocol-designer/src/steplist/index.js
Closes #1843 
- make form-level warnings dismissable
- disambiguate dismissWarning action: now dismissTimelineWarning vs dismissFormWarning
- Form level warnings should show up (eg, set a low disposal volume on a Distribute)
- Form level warnings should be dismissable (each warning type is dismissable per-step)
- Timeline warnings (eg not enough liquid in well) still work, and are dismissable per-step as before
- Loading a file (saved via this branch's version of PD! not earlier files) will restore all dismiss state (both form-level and timeline-level)
> PD: make form warnings dismissable 1843

- api/opentrons/api/models.py
- api/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
Add "modules" field to RPC. Closes #1733 
- Add "modules" field to RPC
Note: will always return an empty array until API object is in place
> feat(api): Add "modules" field to RPC

- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/icons/icon-data.js
- components/src/structure/Card.js
- protocol-designer/package.json
- protocol-designer/src/components/FilePage.css
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/pipettes/actions.js
- protocol-designer/src/pipettes/reducers.js
- protocol-designer/src/pipettes/selectors.js
- protocol-designer/src/utils.js
- yarn.lock
Closes #1536
Allows user to swap pipette mounts. If you set up a protocol with one or two pipettes, then swap the mounts, the protocol should function the same with no other changes required. Ie, you can just click "SWAP", and swapping shouldn't ever require the user to make any other changes to the steps etc.
- Add `swap-horizontal` icon
- Add `contentClassNameOverride` prop to `Card` component (this is so I can opt out of `display: flex`)
- Use `Card`s to organize FilePage contents to match design
- Add swap button to FilePage
- Clean up pipette ID creation (was ID'd by mount and model, not a unique id)
- Use `uuid` library for uuids instead of custom implementation (and start using uuid for pipettes instead of ID derived from pipette data)
- Clean up `ConnectedFilePage` types …
> feat(protocol-designer): enable user to swap pipette mounts

- app/src/components/Page/RefreshWrapper.js
- app/src/components/Page/index.js
- app/src/components/UploadStatus/Status.js
- app/src/components/nav-bar/NavButton.js
- app/src/pages/Calibrate/Labware.js
- app/src/pages/Calibrate/Pipettes.js
- app/src/robot/api-client/client.js
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
This PR addresses #1737 by adding and implementing module selectors and actions in `Calibrate/Labware`.  It also introduces a RefreshWrapper for pages which is implemented on page mount in order to `fetchPipettes` and `fetchModules` from the api.
- feat(app): Add and implement module selectors in calibration
- add `RefreshWrapper` component and implement on calibration pages
If you'd like to see a populated `modulesBySlot` comment out line `343` and uncomment lines` 345-351` in `app/src/robot/api-client/client.js`.  *Please note tests wont pass with this uncommented.
> feat(app): Add and implement module selectors in calibration

- api/opentrons/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette.py
Fix `pipette.delay()` so it does not perform a blocking sleep while the protocol is simulating
> fix(api): pipette.delay() does not block during simulation

- components/src/constants.js
- protocol-designer/src/components/IngredPill.js
- protocol-designer/src/components/IngredientsList.js
- protocol-designer/src/components/SelectablePlate.js
- protocol-designer/src/components/steplist/SourceDestSubstep.js
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/labware-ingred/reducers/index.js
- protocol-designer/src/labware-ingred/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/index.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/top-selectors/well-contents/index.js
- protocol-designer/src/top-selectors/well-contents/wellContentsAllLabware.js
Closes #1812 and refactors `generateSubsteps` fn to lessen that fn's responsibilities. This bug was harder to see b/c `generateSubsteps` was managing timeline indicies, whereas now it's just fed the relevant timeline frames.
-calls to swatchColors use `Number` not `parseInt`, warns on non-integer input (NaNs)
-clean up swatchColors import (no re-routing)
-clarify names of labware/ingred types
-rename 'substepId' to 'substepIndex' in PD substeps
-less argument boilerplate in allSubsteps selector
-remove namedIngredsByLabware selector, convert WellContents to NamedIngreds in getIngredsFactory fn instead
-make generateSubsteps fn work on a single step, no longer is responsible
for mapping across step list itself
- See #1812 -- in substep Pills, do ingredients show up in the state of the …
> PD: fix destination well pills in substeps

- app/src/components/RobotSettings/inputs.js
- components/src/__tests__/__snapshots__/forms.test.js.snap
- components/src/forms/DropdownField.js
- components/src/forms/forms.css
- protocol-designer/src/components/modals/NewFileModal/NewFileModal.css
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/load-file/types.js
- protocol-designer/src/pipettes/reducers.js
Upon creating a new protocol, if the user has not selected a pipette model for a given mount, that
mount's tiprack select should be disabled.
Closes #1780
- changed the structure of the `NewFileModal` to accommodate coupling `pipetteModels` to their corresponding `tiprackModels` and abstracting out duplicate logic that is shared between both mounts.
- Added a `disabled` prop to the `DropdownField` component in the component library.  There was already a sneaky unused component in `RobotSettings/inputs` that was trying to use the `disabled` prop on the `DropdownField` in order to keep flow happy I had to update the type of that unused component so that disabled is `boolean` and not `?boolean`. 
Switch around pipette and tiprack selection in the initial `NewFileModal`. You should not be …
>  fix(protocol-designer): disable tiprack select if no pipette selected

- app/src/components/ConnectModulesModal/Prompt.js
- app/src/components/ConnectModulesModal/ReviewModuleItem.js
- app/src/components/ConnectModulesModal/index.js
- app/src/components/ConnectModulesModal/styles.css
- app/src/components/DeckMap/ConnectedSlotItem.js
- app/src/components/DeckMap/ModuleItem.js
- app/src/components/DeckMap/index.js
- app/src/components/DeckMap/styles.css
- app/src/components/InstrumentSettings/AttachedModulesCard.js
- app/src/components/ModuleItem/ModuleImage.js
- app/src/components/ReviewDeckModal/LabwareComponent.js
- app/src/http-api-client/modules.js
- app/src/pages/Calibrate/Labware.js
- app/src/robot/types.js
- components/src/CenteredTextSvg.js
This PR adds a deck map to the module review modal, showing which modules are connected and which are missing.
Closes #1737
- feat(app): Add deck map to module review modal
- To stub session modules, uncomment lines 345 to 351 in `app/src/robot/api-client/client.js`
- To stub connected modules, edit comments in `app/src/http-api-client/modules.js`
- Comment line 54
- Uncomment lines 56 to 80
0. Launch app with `OT_APP_MODULES=1`
1. Connect to robot (VS is fine)
2. Go to labware calibration
> feat(app): Add deck map to module review modal

- app/src/components/DeckMap/ConnectedSlotItem.js
- app/src/components/DeckMap/LabwareItem.js
- app/src/components/DeckMap/ModuleNameOverlay.js
- app/src/components/DeckMap/index.js
- app/src/components/DeckMap/styles.css
- app/src/components/ReviewDeckModal/LabwareComponent.js
This is the last remaining PR to close out the current sprint's modules tickets. It adds a module name overlay to any labware that are sitting on modules on the deck.
Closes #1739
- feat(app): Show module name over labware on deckmaps
Follow instructions in #1910 to stub out protocol (session) and actual modules and enable module with `OT_APP_MODULES=1`. Then:
Per discussion with @pantslakz over Slack, these do not line up with screens because:
1. Modifying existing `ContainerNameOverlay` to support module name would've been frustrating
2. `ContainerNameOverlay` is likely going to be refactored with the rest of the Deck components
3. Screens are still subject to change once we can start UX testing in the wild
> feat(app): Show module name over labware on deckmaps

- protocol-designer/src/components/steplist/TimelineAlerts.js
- protocol-designer/src/steplist/formProcessing.js
Closes #1880, Closes #1815
-allow more control in overriding step-generations warnings/errors w/in PD context
-fix bug with "Change tip" being blank (#1815)
- Change tip to "Never" in a step that is the first for that pipette - error copy should match #1880 
- In new steps, "Change Tip" should be set to "Always" (not blank)
> feat(protocol-designer): change copy for pipette missing tip error

- api/opentrons/api/session.py
This PR is pulling double-duty as a ticket. Now that all steps of labware calibration are optional and some are order-independent, there are corner cases in which a pipette will not be retracted. The simplest way to guarantee that a pipette will not remain in the down position during run is to home both Z axes prior to beginning a run.
- Home Z axes before run to guarantee that pipettes will be retracted
> fix(api): Home Z axes before run to guarantee that pipettes will be retracted

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/dropAllTips.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/test-with-flow/dropAllTips.test.js
Tips should now always be dropped at end of protocol.
Closes #969
- add `dropAllTips` CommandCreator and use it in PD at end of timeline
- drops all tips at end of protocol (you can look at the saved JSON commands to check)
- doesn't break anything timeline-related, ie PD still works normally
> fix(protocol-designer): fix bug where tips not dropped at end of protocol

- protocol-designer/src/components/labware/ClickableText.js
- protocol-designer/src/components/labware/LabwareOnDeck.js
- protocol-designer/src/components/labware/labware.css
Closes #1519 (makes icon+text brighter, was mid-gray before. See picture in issue)
I tried to clean the SVG styles up a tiny bit:
- removed a magic transforms (instead aligned with `dominant-baseline: text-before-edge;`, thanks @mcous for showing me that rule)
- gave a `height` prop to the `ClickableText` component with a default value instead of having hard-coded height
- added a `rect` w/ `.clickable_area` that fills the whole area of icon+text because on `edge` right now, it's hard to hover/click thin line-drawing icons - you gotta click a pixel of the icon that has fill, instead of the general area.
-update hover button styles to be bright white
-fix hover cursor finicky-ness
-style cleanup
> feat(protocol-designer): restyle labware hover buttons

- protocol-designer/src/pipettes/reducers.js
This is the issue and fix for a bug in PD.
Commit: cd8b9202e0cd954b8f9ecf7bba96f61641a00445
When loading a json file into PD, substeps don't appear for any steps (except Pause), and deleting all tipracks doesn't cause "not enough tips" error. New steps you create after loading a file also have this problem, even if you delete all the protocol's steps. This doesn't happen when you create a protocol from scratch (ie when you do not upload a file)
Pipette were being given new unique IDs upon load, instead of using the IDs referenced in the uploaded file.
- fix file load bug w mismatched pipette ids
- Make sure bug is fixed: saving, refreshing, then loading a file shouldn't cause strange behavior around pipettes & tips. There have been a few breaking changes to file loading in the past weeks, …
> fix(protocol-designer): fix file load bug w mismatched pipette ids

- protocol-designer/src/containers/SelectablePlate.js
- protocol-designer/src/steplist/selectors.js
- protocol-designer/src/steplist/utils.js
Previously the explanatory copy above the deck setup step was shown if deck setup was selected or
hovered. This led some jarring hover behavior, where the text (which acts as a title or subheader) would flicker in and out while the mouse hovered other steps in the step list. Now it is only shown when the deck setup step selected (`deckSetupMode` === when you are actively setting up the deck).
~BREAKING CHANGE: When deck setup step is selected, hovering over other steps will not change the appearance of the liquid state on the deck map, you will only see the initial liquid state while deck setup is in progress. You will still see the changing liquid state on hover if other "standard" steps are selected or no steps are selected.~
> fix(protocol-designer): Only show deck setup prompt text when selected

- protocol-designer/src/steplist/generateSubsteps.js
Closes #1919
- fix consolidate substeps when using mix in advanced settings
- Creating a Consolidate step with Mix (under Aspirate section, and/or under Dispense section) should not add the aspirate/dispense rows to the substeps of that Consolidate in the step list. In other words, toggling mix on and off inside a Consolidate and saving the form should no longer affect the substeps.
(Also I double-checked that Distribute and Transfer are not including the mix stuff in their substeps, you can check that too if you want)
> fix(protocol-designer): fix substeps for consolidate using inner mix

- api/opentrons/config/containers/default-containers.json
- api/opentrons/containers/placeable.py
- api/opentrons/data_storage/database.py
- api/opentrons/drivers/mag_deck/driver.py
- api/opentrons/modules/__init__.py
- api/opentrons/robot/robot.py
- api/tests/opentrons/labware/test_modules.py
Closes #1889, Closes #1887, Closes #1886, Closes #1645
This PR adds Magdeck API object that enables us to add a magdeck and control it. To properly use the API methods, changes to Docker Container setup are required [init system, udev rules]. Magdeck's functionality is fully implemented (sans update firmware):
- Load a Magdeck module (Discover and connect to it)
- Control: calibrate/engage/ disengage, connect/disconnect
- Get device info (Serial no., Model no, firmware version)
**Modules geometry tracking is in progress**
1. `opentrons/modules`: Magdeck API object & load modules
2. `default-containers.json` now includes a magdeck definition
3. `Module` added to `placeables`
4. `opentrons/data_storage/database.py` now loads a `Module` object on `module.load()`
5. `robot.py` now checks for …
> feat(api): add magdeck api object

- app/src/components/InstrumentSettings/ModulesCardContents.js
- app/src/components/ModuleItem/ModuleInfo.js
- app/src/components/ModuleItem/index.js
- app/src/components/ModuleItem/styles.css
- app/src/components/RunPanel/index.js
- app/src/components/TempDeckStatusCard/CardContentRow.js
- app/src/components/TempDeckStatusCard/StatusCard.js
- app/src/components/TempDeckStatusCard/StatusItem.js
- app/src/components/TempDeckStatusCard/index.js
- app/src/components/TempDeckStatusCard/styles.css
- app/src/http-api-client/modules.js
- app/src/robot/api-client/client.js
- components/src/lists/lists.css
This PR closes #1740 - Adds the realtime status card to the run panel (UI only, endpoint still pending). It also adds some mock module data fields for TempDeck and MagDeck see `app/src/http-api-client/modules.js`.
- feat(app): Add realtime status TempDeck card to run panel
*For the full module experience:*
comment out line 77, uncomment lines 79-110 in `app/src/http-api-client/modules.js`
uncomment lines 345-351 in `app/src/robot/api-client/client.js`
run `OT_APP_MODULES=1 make dev` in app (this card is hidden behind the modules flag)
*Notes:*
It is worth nothing that we will only be supporting one TempDeck at a time for launch. See comments in #1740. TempDeck prop is a single TempDeckModule object, not an array.
The TempDeck status card's visibility is based what is returned by the API …
> feat(app): Add realtime status TempDeck card to run panel

- .eslintrc.js
- app/src/components/ConfirmTipProbeModal/Contents.js
- app/src/components/RunLog/CommandList.js
- app/src/components/RunPanel/RunControls.js
- app/src/pages/Robots/index.js
- package.json
- protocol-designer/src/components/IngredientPropertiesForm.js
- protocol-designer/src/components/labware/ClickableText.js
- protocol-designer/src/components/modals/MoreOptionsModal.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/containers/LabwareNameEditForm.js
- yarn.lock
As discussed in #1788, this PR enables the `plugin:react/recommended` rule and resolves (or, in the case of one error, ignores) existing lint errors.
- style(js): Enable `plugin:react/recommended` eslint rules 
This change should **have no affect** on app, component library, and protocol designer. Please check the touched files to make sure nothing broke.
I will annotate each change with the rule for clarity
> style(js): Enable `plugin:react/recommended` eslint rules
