- api/src/opentrons/tools/factory_test.py
The method it currently uses is tough to maintain and we have a utility function
in nmcli that does exactly what we need so just use that.
Run the factory test and make sure it gets the ip address appropriately
> chore(api): factory tools should use nmcli for ip address check

- app/src/shell/index.js
- app/src/shell/remote.js
- app/src/shell/types.js
In investigating @IanLondon's reports of a circular-dependency based assertion, I found that the root of the problem was an assertion firing for a missing remote during import (i.e. before the code was actually running).
I'm not 100% sure of the Electron and/or webpack mechanics that are allowing that assertion to be hit, but moving the assertion to property access time fixes the issue.
@IanLondon: `app/src/protocol/selectors.js` creates a logger (via `app/src/protocol/protocol-data.js`), which relies on the `remote` module to send logs over to the desktop shell to save to a file. Rebasing #3891 over this branch fixed the issues for me.
- fix(app): make shell remote check lazier to avoid spurious assertions
> fix(app): make shell remote check lazier to avoid spurious assertions

- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/config/index.js
- app/src/config/selectors.js
Versions of the app ending in `-alpha.N` get published to the "alpha" update channel. While the update channel is configurable for a given app installation, setting the channel to "alpha" has not been available in the UI.
Following up on #3848, this PR enables "alpha" as an update channel setting in the app's "Advanced Settings" page if the devtools are enabled.
- refactor(app): Allow "alpha" update channel with devtools enabled
> refactor(app): Allow "alpha" update channel with devtools enabled

- CONTRIBUTING.md
These were only occasionally followed before; with buildroot in the mix, it's
more important to get them exactly right so as not to block others, and make
updates available to testers.
This is based on the process we've been following for 3.11.0, so let's not merge it until we've followed that process all the way through to make sure there's no gotchas we didn't think about. However, it's ready for reviews with that caveat in mid.
> chore(docs): fix robot software stack release instructions

- labware-library/src/components/App/index.js
- labware-library/src/filters.js
When query parameters are present in the labware library URL, React hydrates the tree incorrectly because the prerendered tree includes definitions that the React rendered tree (with the query param filters included) does not.
This PR fixes this problem by mirroring the query params into component state, thereby ensuring the first React render includes all definitions and therefor matches the pre-rendered tree. There is a split second between HTML rendered on the screen and React taking over and applying the filters, but that is existing behavior in the 1.0.0 release.
This branch is branched off of the tag `labware-library@1.1.0`. Once this PR is approved, this commit should be tagged `1.1.1` and _then_ merged into `edge`.
- fix(labware-library): Fix incorrect tree hydration with query …
> fix(labware-library): Fix incorrect tree hydration with query params

- labware-library/src/components/App/__tests__/__snapshots__/App.test.js.snap
- labware-library/src/components/App/index.js
- labware-library/src/components/Nav/Breadcrumbs.js
- labware-library/src/labware-creator/components/IntroCopy.js
- labware-library/src/labware-creator/components/LabwareCreator.css
- labware-library/src/labware-creator/components/LabwareCreator.js
- labware-library/src/labware-creator/components/Section.js
- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
- labware-library/src/styles/spacing.css
addresses #3910
This PR 
- Adds the website main nav from LL to LC page
- Adds breadcrumb nav to LC page
- Adds some initial responsive styling to the 'landing page' content with a placeholder for upload section 
- feat: Add main navigation to labware creator page
- refactor: Update breadcrumbs to accept a creator boolean (to render on LC page)
- refactor: Initial responsive styling for LC landing content
- refactor: Placeholder div for upload
Happy to have a convo now before we get to far about what styles live where!
> feat(labware-creator): Add main navigation to labware creator page

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/LabwareSelectionModal/index.js
- protocol-designer/src/components/SettingsPage/FeatureFlagCard/FeatureFlagCard.js
- protocol-designer/src/components/SettingsPage/FeatureFlagCard/index.js
- protocol-designer/src/components/SettingsPage/SettingsApp.js
- protocol-designer/src/components/SettingsPage/SettingsPage.css
- protocol-designer/src/components/SettingsPage/index.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/feature-flags/actions.js
- protocol-designer/src/feature-flags/index.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/card.json
- protocol-designer/src/localization/en/feature_flags.json
- protocol-designer/src/localization/en/index.js
- protocol-designer/src/persist.js
- protocol-designer/src/types.js
This PR serves as its own ticket.
It came up in the PD release planning meeting today that we want to be able to test the full custom labware flow (LC + PD + RA), so we want to make "upload custom labware" available to internal users and for user testing.
However, custom labware upload to PD is a highly desired feature and until it's fully supported (LC release), we don't want to mislead users by showing the button in PD.
This PR hides the "upload custom labware" button unless a user goes to Settings > Feature Flags > Upload custom labware and enabled that feature. It also establishes feature flags in PD (analytics opt-in/out is related, but not exactly the same domain). We plan to use more feature flags in the future with upcoming features in PD.
- add feature flag "atom" to PD
- add …
> feat(protocol-designer): put custom labware upload under feature flag

- labware-library/src/labware-creator/index.js
- shared-data/js/labwareTools/__tests__/createDefaultDisplayName.test.js
- shared-data/js/labwareTools/index.js
- name the Python file saved in the zip test_{displayName}.py instead of calibrate_{displayName}.py
- fix displayName generation and add tests
- python file starts with test_ instead of calibrate_?
- auto-generated display name correctly matches our conventions (fill in fields to see the value) 
Our display name convention is: `[brand]_[num_wells]_[format]_[total_volume]_[volume_units]_[optional modifiers]`
NOTE: we have a variant for tube rack / aluminum block, but since we don't have a place in LC to enter 2 different brands, I'm ignoring it for now. OK with you all? The variant would be `[brand]_[num_wells]_[format]_[tube_brand]_[total_volume]_[volume_units]_[optional modifiers]`
> fix(shared-data): fix labware display name; change python file

- labware-library/src/labware-creator/index.js
- shared-data/js/labwareTools/__tests__/createDefaultDisplayName.test.js
- shared-data/js/labwareTools/index.js
keep the purgatory-edge branch in sync with hotfix to UX testing branch
* name py file test_{displayName} not calibrate_{...}
* fix labware display name fn
- diff should look the same with no weird extra stuff that might have come in from `lc_setup-labware-creator`
> fix(labware-library): fix labware display name; change python file

- api/src/opentrons/protocol_api/contexts.py
We need to update docstrings for apiv2 atomic functions to make it clear that we won't attempt to guess positional args anymore.
> chore(docs): apiv2: update docs for optional args

- labware-library/src/labware-creator/index.js
Closes #3970
- show diameter field when well shape's radio group is unselected
- nothing weird?
> feat(labware-creator): show diameter field by default

- app/src/protocol/__mocks__/selectors.js
- app/src/protocol/selectors.js
- app/src/robot/selectors.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/selectors.test.js
- app/src/shell/index.js
- app/src/shell/remote.js
- app/src/shell/types.js
Closes #3826 
- display labware on deckmap for JSON v3 protocols
- factor out protocol selectors into a selectors.js file
This only works with JSON v3 protocols, not Python. Earlier JSON versions didn't have embedded labware, so there's no way to have it work with them.
For JSON v3 protocols, Run App should display labware on the Deck Map from the JSON protocol's embedded labware definitions. (Not only custom labware, but all labware in the protocol is read from the protocol, including standard labware.)
It will show all labware that is in a slot on the deck in that JSON protocol. BUT- the existing behavior where labware are not shown unless "interacted" with is preserved.
~I factored out `protocol/index.js` into its own `protocol/selectors.js` file to try and fix a circular …
> feat(app): display custom labware on deckmap

- labware-library/package.json
- labware-library/src/__mocks__/definitions.js
- labware-library/src/__tests__/__snapshots__/labwareInference.test.js.snap
- labware-library/src/__tests__/labwareInference.test.js
- labware-library/src/components/LabwareDetails/InsertDetails.js
- labware-library/src/components/LabwareDetails/LabwareDetailsBox.js
- labware-library/src/components/LabwareList/__tests__/__snapshots__/LabwareList.test.js.snap
- labware-library/src/components/labware-ui/WellProperties.js
- labware-library/src/definitions.js
- labware-library/src/labware-creator/__tests__/__snapshots__/labwareDefToFields.test.js.snap
- labware-library/src/labware-creator/__tests__/labwareDefToFields.test.js
- labware-library/src/labware-creator/__tests__/loadAndSaveIntegration.test.js
- labware-library/src/labware-creator/components/ImportErrorModal.js
- labware-library/src/labware-creator/components/ImportLabware.js
- labware-library/src/labware-creator/fields.js
- labware-library/src/labware-creator/fieldsToLabware.js
- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/labwareDefToFields.js
- labware-library/src/labware-creator/styles.css
- labware-library/src/labwareInference.js
- protocol-designer/src/step-generation/test-with-flow/__snapshots__/fixtureGeneration.test.js.snap
- shared-data/js/labwareTools/index.js
- shared-data/labware/fixtures/2/fixture_12_trough.json
- shared-data/labware/fixtures/2/fixture_96_plate.json
Closes #3842 
- make `ImportLabware` trigger an upload attempt, on either click or drag-and-drop-file
- save `groups` metadata into saved defs
- use `groups` metadata to populate the form fields from an uploaded def
ERROR MESSAGE MODAL
- (See "EXCEPTION" in section above for the 4th possible error message case)
LABWARE LIBRARY
NOTE: I imagine we'll have **copy changes** around the file import errors. I'd like to not evaluate them in this PR, unless I'm going totally in the wrong direction with the 4 error cases of have. I'm down to modify the copy and the details of the import error message modal in a follow-up.
> feat(labware-creator): upload labware definitions to LC

- labware-library/src/labware-creator/components/ImportLabware.js
- labware-library/src/labware-creator/components/IntroCopy.js
- labware-library/src/labware-creator/components/importLabware.css
- labware-library/src/labware-creator/fields.js
- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
closes #3977
- refactor(labware-library): Update landing content and instructions copy
http://sandbox.labware.opentrons.com/lc_copy-edits/create/
**Note:** Punted on the subscript for XY offset and spacing since this text is driven by data strings and there is no subscript S unicode character.
> refactor(labware-library): Update landing content and instructions copy

- api/docs/source/v1/atomic_commands.rst
This PR fixes small typos on the APIv1 docs.
> chore(docs): apiv1: fix typos

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
This commit fixes incorrect indentation during a previous refactor that caused smoothie errors to be silently swallowed if they occured at any time but during home. Unlike the last fix, it doesn't make the system home after such an error unless the error occurred during move or probe, since homing after other errors would be pointless at best and actively harmful at worst (for instance, smoothie "returns an error" if it tries to read an instrument eeprom on a mount with no instrument attached).
This is a change to a pretty fundamental part of the API, since this codepath is taken on every smoothie communication path. We should look at
- Tip probes without failures
- Tip probes with induced failures (aka probes with no tip attached)
- Attach pipette, especially removing pipette
- Induced …
> fix(api): fix ignoring smoothie errors during non-home

- protocol-designer/src/components/KnowledgeBaseLink/index.js
- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/LabwareSelectionModal/styles.css
- protocol-designer/src/localization/en/modal.json
closes #3924
Enable the custom labware feature flag (in Settings page) to see the custom labware button and new copy in the Add Labware Modal.
- Link should work
- If you disable the custom labware feature flag, both the button and the copy should disappear from the Add Labware Modal.
> feat(protocol-designer): add copy with custom labware button

- shared-data/labware/definitions/2/opentrons_96_tiprack_20ul/1.json
This PR updates the `tipOverlap` value for the Opentrons 20 uL tip rack. The original value is copied from the 10 uL tip rack definition. Since the P20 GEN2 pipette has a longer nozzle than the P10, this number should be larger. 
After robot factory reset and CLI deck calibration, do not tip probe and run this protocol. You should see that the pipette would not touch the deck because the tip length was supposed to be longer.
```
def run(ctx):
from opentrons.types import Location, Point
tiprack = ctx.load_labware('opentrons_96_tiprack_20uL', '6')
pip = ctx.load_instrument('p20_single_v2.0',
mount='right', tip_racks=[tiprack])
location = Location(Point(380.87, 9.0, 0.0), ctx.deck)
pip.move_to(location)
pip.return_tip()
```
After updating the 20 uL tip rack definition, you …
> fix(shared-data): fix tipOverlap value for P20 tiprack

- Makefile
We've been getting flaky CI failures all the time where `make lint-css` fails with an [obscure make error about stdout already being closed](https://lists.gnu.org/archive/html/bug-make/2014-07/msg00035.html)
In a blind attempt to fix these issues (and without any obvious errors in the [stylelint CLI](https://github.com/stylelint/stylelint/blob/master/lib/cli.js)) this PR pipes the stylelint into `tee` to paper over whatever is causing this
🤷‍♂ 
- ci(travis): Pipe stylelint to tee in CI to paper over stdout problems
Thanks to @sfoster1 for this idea. Open to others if anyone has them
> ci(travis): Pipe stylelint to tee in CI to paper over stdout problems

- labware-library/src/images/circularWell.svg
- labware-library/src/images/rectangularWell.svg
- labware-library/src/images/wellShapeFlat.svg
- labware-library/src/images/wellShapeU.svg
- labware-library/src/images/wellShapeV.svg
- labware-library/src/labware-creator/components/HeightGuidingText.js
- labware-library/src/labware-creator/components/RadioField.js
- labware-library/src/labware-creator/components/optionsWithImages/index.js
- labware-library/src/labware-creator/components/optionsWithImages/optionsWithImages.css
- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
Closes #3957 -- see ticket for illustration and details
- also factored out `HeightGuidingText` to its own file
- LC should still work, especially the well shape / well bottom shape fields
> feat(labware-creator): add images to well shape fields

- api/Makefile
- api/docs/source/conf.py
- api/docs/source/templates/toc-with-nav-force-no-hidden.html
- api/docs/source/templates/toc-with-nav-force-show-hidden.html
The new tree structure broke links for both the OT 1 API and the generated PDF of our documentation. Closes #3987.
- Change link reference for OT 1 api and PDF to always point to parent link
- Modify location that PDF is placed
- Ensure that the PDF is copied to the correct place for local and CI builds
Check links work when you're in API v1 docs, API v2 docs and the main page.
> fix(docs): Fix OT 1 API link and PDF link

- api/Makefile
Many of the Makefile targets have corresponding .PHONY declarations.  A few of these were slightly out of sync, either using old names, or leaving targets out.
Please make sure:
- I didn't miss anything. i.e., all targets that should be `.PHONY` actually are, now.
- I didn't mistakenly make something `.PHONY` that shouldn't have been.
> chore(api): fix outdated .PHONY targets in API Makefile

- api/src/opentrons/util/calibration_functions.py
Fix #3983. The bug was simply reading from a similarly named (but wrong) variable.
During CLI tip probe calibration, assuming the tip correctly hits the west and east switches, it should also correctly hit the south and north switches.
CLI tip probe calibration should also be immediately responsive to hitting the east or west switches unexpectedly early or late. Use your finger to tap the east or west switch well before the pipette tip hits it. Then, when the pipette moves to touch the south and north switches, its x-position should be off-center in that direction.
> fix(api): fix tip probing not fully self-centering

- api/src/opentrons/server/rpc.py
- api/tests/opentrons/server/test_server.py
- app/src/robot/api-client/index.js
- app/src/rpc/client.js
Fixes #3998
An arbitrary (default) file size limit in the API made it impossible to upload protocol files larger than 4Mb. After removing that limit, we discovered that:
1. The API simulates the protocol before sending an 'ack' back to the client, causing the client request to time out
2. The API had log statments that would crash the API server when receiving large files
This PR removes the log statements from the API (and a log statement from the App with the same problem), and removes the file size limit. It also moves the 'ack' response to before simulation, as expected by the App.
> fix(api): remove protocol file size limit and ack immediately

- labware-library/src/labware-creator/components/optionsWithImages/optionsWithImages.css
- labware-library/src/labware-creator/styles.css
This PR hides the default options label for radio fields that have options with images. Nothing crazy here, the work was done, just the class was never added to CSS. Closes #3957
Before:
Now:
- refactor(labware-creator): Add missing hidden class
> refactor(labware-creator): Add missing hidden class

- .travis.yml
- Makefile
In `edge`, the `lint-css` failing in Travis is fixed but `lc_purgatory-edge` doesn't have the change, so it keeps failing 😞 
- CI passes
> chore(repo): pull in updates from edge that fix intermittent CI css-lint failure

- app/src/components/ModuleLiveStatusCards/TempDeckCard.js
- app/src/components/ModuleLiveStatusCards/ThermocyclerCard.js
- app/src/components/ModuleLiveStatusCards/index.js
- app/src/config/index.js
- app/src/config/types.js
- app/src/robot-api/resources/modules.js
- app/src/robot/selectors.js
- app/src/robot/test/selectors.test.js
Remove flag that hides thermocycler cards and controls.
> refactor(app): remove thermocycler feature flag

- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
> feat(labware-creator): separate create vs upload fields; scroll upon upload

- labware-library/src/labware-creator/fields.js
- labware-library/src/labware-creator/index.js
Serves as its own ticket!
Default the well shape to "circular" and default the well bottom shape to "flat".
Get rid of the image fallback stuff now that neither of those fields should ever become `null`.
👁‍🗨
> feat(labware-creator): default well shape & bottom field values

- labware-library/src/labware-creator/index.js
This PR serves as its own ticket. Since we renamed the test guide filename to `labwareDefinition_testGuide.pdf` in AWS, we needed to update the link URL in LC.
- refactor(labware-creator): Update labware test guide link
> refactor(labware-creator): Update labware test guide link

- api/src/opentrons/protocol_api/geometry.py
Module slot assertion error improperly included the string literal "{location}" instead of the template string representing the invalid slot.
> fix(api): fix format string in module slot assertion

- shared-data/module/definitions/1.json
The display name of the Thermocycler Module should be 'Thermocycler Module' and not carry an old
reference to 'full plate'
> refactor(shared-data): remove ref to full plate in tc name

- api/src/opentrons/server/endpoints/logs.py
Make logs readable again! For buildroot, default was set to machine readable logs which is great for computers but not for humans.
- Change default for logs to be text instead of JSON.
Check that when you download logs, you can now read the files instead of having JSON blobs.
> refactor(api): Change log readout default to text for reability

- api/docs/public/ot1/_sources/index.txt
The comment states "Transfer 100uL from the plate's 'A1' well to it's 'A2' well" but the code had B1 instead of A2.
> docs(ot1): Fix small typo in OT1 documentation

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/containers/placeable.py
- api/src/opentrons/legacy_api/modules/magdeck.py
- api/tests/opentrons/labware/test_modules.py
APIv1 magdeck does not check the labware definition for the engage height. This means that any custom labware that is not in the `LABWARE_ENGAGE_HEIGHT` list would not work with the magdeck even if they are compatible.
https://github.com/Opentrons/opentrons/blob/7fe710955745f7fd76f1ebfc4c0534ab949dbd92/api/src/opentrons/legacy_api/modules/magdeck.py#L4-L6
closes #3832
- add `magdeck_engage_height` as one of the properties of `Placeable`
- which would return `magneticModuleEngageHeight` from the definition if it is magdeck compatible and return `None` if not
Test on robot
> feat(api): apiv1: load magdeck engage height from labware definitions

- api/src/opentrons/server/endpoints/logs.py
Because otherwise this just isn't that useful
> refactor(api): increase default log record count to 500k

- api/src/opentrons/legacy_api/api.py
Return tip height config value was never being passed into the pipette constructor in api v1, and so the p1000 gen2 was never actually going to the correct height.
- Pass in return tip height to `Pipette` constructor
- See that the return tip value is actually 0.83 for a gen2 pipette instead of 0.5
> fix(api): Fix usage of return tip height v1

- app/src/components/CalibratePanel/LabwareListItem.js
- app/src/components/ConnectModules/index.js
- app/src/components/DeckMap/index.js
- app/src/components/FileInfo/ProtocolModulesCard.js
- app/src/components/InstrumentSettings/AttachedModulesCard.js
- app/src/components/InstrumentSettings/index.js
- app/src/components/ModuleLiveStatusCards/index.js
- app/src/components/PrepareModules/index.js
- app/src/components/RunPanel/RunControls.js
- app/src/components/RunPanel/index.js
- app/src/components/calibrate-pipettes/styles.css
- app/src/robot-api/resources/modules.js
- components/src/hooks/useInterval.js
- components/src/nav/SidePanel.css
This PR closes #2676 by disabling the "Start Run" button in the run page the robot is missing any required modules
- fix(app): Disable run start button if missing modules
- Due to the need to be polling modules on almost every page, I reconfigured the modules API client epic to simply poll GET /modules while connected to a robot
- I think this should replace all most of out reactive module state needs until the notifications WS can be put in place
- The only exception to this is the Modules card in Instrument Settings, which still needs to poll regardless of connection status (because user can view this card without clicking "Connect")
I refactored some common code to a `getMissingModules` selector. This touched the following flows:
> fix(app): Disable run start button if missing modules

- update-server/Makefile
- update-server/buildroot_upload.py
- update-server/otupdate/buildroot/file_actions.py
- update-server/otupdate/buildroot/update.py
- update-server/tests/buildroot/test_file_actions.py
linux has a concept of machine id
(http://man7.org/linux/man-pages/man5/machine-id.5.html), which is a uuidlike
that identifies a machine - e.g., every computer, kvm, docker container, etc
should have a unique one. systemd will generate one if it sees that
/etc/machine-id is empty, but if /etc/machine-id is not writable (or really /etc
in general), it will bind-mount a tmpfs on /etc/machine-id, which will be lost
when the machine reboots. Given the things we do to the robot, this is usually
ok, but journald scopes journal files by machine-id to allow unified log
locations for things like multiple docker containers or kvms running on the same
host without stomping each other. That means that even if we change journald to
force fs backing for journals, the journals will be in a new place …
> refactor(update-server): preserve machine ID

- protocol-designer/src/components/StepEditForm/fields/TipPosition/TipPositionModal.js
Closes #4057
- Set tip position to `0`. Save the modal. Open the modal again. Modal field should be `0`. The bug was that when you open the modal again, the modal field would "default" to `1`.
> fix(protocol-designer): fix tip position bug with zero

- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/hardware_control/simulator.py
- api/tests/opentrons/hardware_control/test_instruments.py
Previously, the hardware controller would accept only the name, model, or
appropriate back compat patches for the attached pipettes while the simulator
would accept anything that was a valid prefix of a pipette. Well, it turns out
'p' is a valid prefix for just about anything that the hardware controller will
choke on. Stop just allowing prefixes and make the user put in something that's
a valid pipette identifier.
Closes #4062
> fix(api): apiv2: allow pipette name or model in cache_instruments

- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/protocol_api/test_context.py
We didn't have a loaded_modules prop; loaded_labwares and loaded_instruments
returned Nones for empty deck slots. Fix all this up to make these more useful.
These are changes to make @IanLondon 's life a bit easier inspecting apiv2 protocols in the protocol library. They shouldn't affect protocol execution since they're just about accessors that aren't really used.
> feat(api): apiv2: improve accessors for loaded lw/mods/instrs

- protocol-designer/src/components/modals/LabwareUploadMessageModal/LabwareUploadMessageModal.js
- protocol-designer/src/labware-defs/actions.js
- protocol-designer/src/labware-defs/types.js
- protocol-designer/src/localization/en/modal.json
Closes #4009
- Uploading custom labware (non-Opentrons) should still work
- If you upload a labware with `"namespace": "opentrons"`, PD will now give you an error modal and block the upload
> feat(protocol-designer): disallow standard labware def upload

- protocol-designer/src/containers/ConnectedStepItem.js
Closes #3678 and more generally, fixes bug where form errors didn't make StepItem show an error icon.
- Deleting labware (the problem specified in #3678) will now make all StepItems for steps using that labware show the red error icon
- Play around with other ways to make form errors (mess with pipettes?? You can't save erroring forms, so I can only think of labware & pipettes being ways to make forms error out. Running out of tips is a timeline error, not a form error.) Behavior should be as expected - StepItem in sidebar shows red error icon, only by selecting the step and opening the form do you see error banners
> fix(protocol-designer): show form error state in StepItems

- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
`TransferPlan` uses cached location to determine locations for `mix_before` and `mix_after`. Instead, the mix locations should be determined by the source and destination of the transfer.  
closes #3197
- add `location` as one of the kwargs for mix options, which will then be passed to `InstrumentContext.mix` when it is called during a transfer
- for `mix_before`, mix location is set to the transfer source
- for `mix_after`, mix location is set to the transfer destination
Not sure if using `replace()` is the best way to modify the mix options.
Feel free to modify and simulate the following protocol:
```
def run(ctx):
tiprack = ctx.load_labware('opentrons_96_tiprack_10uL', 1)
pip = ctx.load_instrument('p20_single_gen2',
mount='right', tip_racks=[tiprack])
plate = …
```
> fix(api): apiv2: pass correct locations for mix in TransferPlan

- api/src/opentrons/protocols/parse.py
- api/tests/opentrons/protocols/test_parse.py
- By iterating through the full list of subassignments in ast.Import and
ast.ImportFrom statements, we can catch cases where someone imports a
blacklisted module other than first (e.g. from opentrons import labware, robot)
- Add opentrons.containers to the list
Closes #3949
> fix(api): Expand infer_version_from_metadata to catch more

- package.json
- yarn.lock
#4088's lockfile wasn't quite right and turns out `make -C app dev` would crap out as soon as any source change was made. This PR removes the necessary `resolutions` object in package.json in favor of getting the various transitive dependencies correct in the lockfile.
- build(webpack): Fix webpack lockfile dependencies breaking app dev
> build(webpack): Fix webpack lockfile dependencies breaking app dev

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
This parsing is unreliable because we have the smoothie's echo mode on and our
multiple new lines sometimes stomp the actual response from the smoothie. This
raises an IndexError and breaks pipette config updating and makes the system
unreliable.
This should remove cases where sometimes you'd get mysterious homes during other actions and then errors during homing.
> fix(api): dont parse the smoothie response to update_pipette_config

- api/docs/source/v1/api.rst
- api/docs/source/v1/examples.rst
- api/src/opentrons/legacy_api/containers/placeable.py
Closes #4025
Unzip this and navigate in your browser to the apiv1 docs to see the changes
[dist.zip](https://github.com/Opentrons/opentrons/files/3648824/dist.zip)
> docs(api): Document placeable positioning methods

- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
Transfers with uneven lists of sources and targets were previously cut short, with the number of transfers determined by the length of the shorter list. For example, a one-to-many transfer would turn into a one-to-one.
This PR primes the source and target lists to make their lengths match before generating aspirate and dispense actions, mimicking the behavior of apiv1. This allows apiv2 to handle one-to-many, few-to-many transfers as described in the documentation.
closes #4081 
- add `extend_source_target_lists()` to update the source or target list if they are of uneven lengths
Simulate the following protocol:
```
def run(ctx):
from opentrons.protocol_api import transfers as tx
tiprack = ctx.load_labware('opentrons_96_tiprack_10uL', 1)
pip = ctx.load_instrument('p20_single_gen2', …
```
> fix(api): apiv2: allow transfer with uneven sources and targets 

- api/src/opentrons/system/nmcli.py
This should prevent the macs from changing when the robot restarts, which plays
havoc with people using mac whitelisting in their wireless networks.
Testing:
- push this to your robot
- reconnect to wifi
- dump the mac addr
- restart the robot
- dump the mac addr
- they should be the same
> fix(api): Force the permanent mac address for wifi connections

- api/src/opentrons/deck_calibration/dc_main.py
We were getting a little complex with motion commands in _helper_pickup. Relying
on the smoothie driver to move only in z is ugly, but in line with how we do it
elsewhere in the module, and doesn't have this issue.
Closes #3980
This is luckily a limited change so we can just test picking up tips with left and right mounts in apiv1.
> fix(api): apiv1: cli-dc: fix tip pickup with left mount

- app/src/components/RobotSettings/ControlsCard.js
This issue serves as its own ticket -- closes @btmorr's Post-It on the NIGHTMARE WALL.
* add a "Restart Robot" button to Run App (next to "Home" button)
> feat(app): add restart robot button

- api/src/opentrons/execute.py
- api/src/opentrons/simulate.py
Functionality for bundled protocols wasn't added to opentrons_simulate and
opentrons_execute entrypoints.
On Windows and either OSX or Linux:
- simulate a bundle in apiv2 and make sure it works
- simulate a non-bundle in apiv2 and apiv1 and make sure they still work
- simulate json protocols in apiv2 and apiv1 and make sure they still work
On a robot (for opentrons_execute):
Note: since the behavior we're testing happens at parse and labware creation time, you don't have to wait for the protocol to finish
- use opentrons_execute in apiv2 on a bundle
- use opentrons_execute in apiv2 and apiv1 on a non-bundle
- use opentrons_execute in apiv1 and apiv2 on a json protocol
> fix(api): Fix sim and exec entrypoints for bundled protocols

- .eslintignore
- Makefile
[New changes](https://github.com/Opentrons/opentrons/pull/4059) to the `format` command in the Makefile for CI caused a release branch to fail. Sometimes lerna will randomly change some file formats that might fail this check on `make format`, so ignore `prettier` check on the `lerna.json` file.
> ci(travis): Ignore lerna file for linter

- api/src/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
The session needs a protocol text member exposed via rpc to let apps that aren't
the one that uploaded the protocol see what the protocol was. The app also
relies on it (perhaps incorrectly) in a couple ways, for instance the creation
method, and without this exposed it can't decide what it is.
In addition, add a test to catch the regression in the future.
This issue was introduced in 1c503ed37cc1bbba0f4cf5b09c93811e08abc704
- Push this to a robot
- Upload a python protocol and note that Creation Method says "Protocol API"
- Upload a json protocol and note that Creation Method says the PD version used to create it
- Connect to the robot from a different runapp and note that it has the protocol details as well
> fix(api): reflect protocol text over rpc

- app/src/protocol/__tests__/actions.test.js
- app/src/protocol/__tests__/reducer.test.js
- app/src/protocol/__tests__/selectors.test.js
- app/src/protocol/index.js
- app/src/protocol/protocol-data.js
- app/src/protocol/selectors.js
- app/src/protocol/types.js
On Windows, Run App was sending bytes instead of base64-encoded bytes when uploading a zip, because Windows Electron does different mime types for zips?
This drops the mime typing and just uses file suffixes, which are more straightforward.
- .json & .py uploads still work as before
- .zip upload works (esp on Windows)
NOTE: there's a bug with "Creation Method" that will be fixed in a separate ticket
> fix(app): fix zip mimetype bug

- labware-library/src/components/Sidebar/LabwareGuide.js
- labware-library/src/components/Sidebar/__tests__/__snapshots__/LabwareGuide.test.js.snap
- labware-library/src/localization/en.js
This PR closes #4147 by adding `Custom Labware Creator` link to Labware Library sidebar
- feat(labware-library): Add link for LC to LL sidebar
http://sandbox.labware.opentrons.com/ll_add-lc-link/
Question: Is this a DO NOT MERGE kind of thing? I doubt we are cutting a LL release before LC
> feat(labware-library): Add link for LC to LL sidebar

- api/src/opentrons/server/endpoints/logs.py
- api/src/opentrons/system/log_control.py
Previously we coalesced logs twice: once as a list of journald reports, and then
again in the destination format. This was really slow and let us run out of
memory. We also use the python-journald reader, which is _unbelievably slow_ and unsuited to the task of streaming out logs. It took ~2ms per log record.
Instead, just call `journalctl --no-pager` and dump them to a pipe. It's so much faster.
- Get logs. Nothing should crash and it shouldn't take literally 5 minutes on some robots.
> fix(api): Do not run out of memory when dumping large logs

- api/src/opentrons/server/__init__.py
- api/src/opentrons/server/endpoints/control.py
And not in the cwd of the server.
Closes #4122
Testing: Put this on a robot and get a picture with `curl -X POST $(robot ip):31950/camera/picture > image.jpg; open image.jpg`
> fix(api): Put camera images in tempdirs

- api/src/opentrons/protocol_api/geometry.py
- api/tests/opentrons/protocol_api/test_geometry.py
During simulation, prevent deck items from being loaded into slots obscured by other deck items,
including the thermocycler, which spans multiple slots.
Closes #3107
> feat(api): implement deck item spanning first pass

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocols/parse.py
- api/tests/opentrons/protocols/test_parse.py
If we have a bundle, we need to only consider labware from that bundle when
labware is loaded into modules.
Also fix an issue that would lead to very ugly exceptions when simulating a
bundled protocol.
- Upload a non-bundled protocol that loads labware in a module and check that it works
- Upload a non-bundled protocol that loads nonexistent labware in a module and check that the error is acceptable
- Upload a bundled protocol that loads labware in a module and check that it works
- Uploads a bundled protocol that loads a labware not in the bundle into a module and check that the error occurs and is acceptable
> fix(api): Only load labware for modules from bundles

- Makefile
- jest.config.js
I think I figure out the `make: write error` bug that we're seeing in CI:
- Our `make test-js` task prints coverage
- Our coverage reporter was set to `text`, which prints out the coverage of **every single JS file in the repo**
- This log takes a long time on Travis, which can lead to a race condition where Jest doesn't exit cleanly because jest is waiting for the log to finish logging
- build(jest): print coverage summary rather than every single file
- Re-run the CI task if you feel like it
- Make sure test-js still behaves on your machine
> build(jest): print coverage summary rather than every single file

- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
This PR separates the File and Labware Test Protocol sections and adds a callout to the bottom that guides the user to the labware test guide PDF.
While I was in there, I refactored the CSS a little so that when we have a LinkOut that we want to look like a button (occurs 2x now) we can `@apply --link-btn-blue` (note: the blue button style uses akko pro as per website style-guide)
closes #4118 
- feat(labware-creator): Guide user to labware test
http://sandbox.labware.opentrons.com/lc_labware-test-callout/create/
Since this splits up an existing section please double check validation/generation is unaffected.
> feat(labware-creator): Guide user to labware test

- labware-library/src/analytics/index.js
- labware-library/src/labware-creator/analyticsUtils/index.js
- labware-library/src/labware-creator/components/Dropdown.js
- labware-library/src/labware-creator/components/LinkOut.js
- labware-library/src/labware-creator/components/RadioField.js
- labware-library/src/labware-creator/components/Section.js
- labware-library/src/labware-creator/components/TextField.js
- labware-library/src/labware-creator/index.js
This doesn't hook up the events, the stub function `reportEvent` will only `console.log` them. When we add the opt-in flow and connect MixPanel in upcoming PR(s), `reportEvent` would call `mixpanel.track`.
Part of #4115 
- Make sure all the events outlined in the spreadsheet linked in #4115 are logged. Make sure events always log when they should (no misses), and make sure there's no spamming of events that aren't really new (eg from re-rendering). See the sheet for full details (esp properties) but in summary:
> feat(labware-creator): add analytics events skeleton

- .travis.yml
Given that our release process now includes tagging each RC build as an `alpha`, this PR removes the legacy signing of builds on `edge` and `release_*` branches, as that behavior was from earlier times where we attempted to use builds from those branches as release candidates.
- ci(travis): only sign the mac app on v* tagged builds
I checked `appveyor.yml` and `app-shell/Makefile` for additional changes, but it looks like the travis config is the only thing that needs updating
> ci(travis): only sign the mac app on v* tagged builds

- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/labware/test_pipette.py
- shared-data/pipette/definitions/pipetteModelSpecs.json
Gen2 models no longer need the `DropTipShake`.
- remove quirks from pipetteModelSepcs.json
- update appropriate tests
Test on robot
> refactor(shared-data): remove DropTipShake from all Gen2 models

- shared-data/pipette/definitions/pipetteNameSpecs.json
This PR updates all flow rates for Gen2 pipettes to `5 mm/s`.
Flow rates are determined using this equation:
> X uL/s = Y uL/mm x 5 mm/s
Where Y is the ul/mm calculated based on the max volume of a given pipette and its associated piecewise function in the aspirate/dispense functions (found in pipetteModelSpecs).
> refactor(shared-data): update Gen2 aspirate/dispense/blowout speeds

- .travis.yml
- In July 2019, Travis [enabled the npm cache setting by default](https://docs.travis-ci.com/user/caching/#npm-cache)
- The npm cache setting will either:
- Cache the npm system package cache if your `install` script is `npm ci`
- Cache the repository's `node_modules` folder otherwise
- We have the yarn cache setting enabled, which caches yarn's system package cache
Since our `install` script is not `npm ci`, the end result for us is that we cache both the system level yarn package cache **and** the repository's node_modules folder. This is bad for us, because we want a fresh `node_modules` folder on every build to ensure any native dependencies are properly built.
We have been seeing intermittent build failures do to improperly built native depedencies that can only be cleared by …
> ci(travis): Do not cache the node_modules folder

- api/Pipfile.lock
- api/docs/source/v2/new_advanced_running.rst
- api/src/opentrons/api/session.py
- api/src/opentrons/commands/commands.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocols/bundle.py
- api/src/opentrons/protocols/parse.py
- api/src/opentrons/protocols/types.py
- api/src/opentrons/simulate.py
- api/src/opentrons/util/entrypoint_util.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_labware.py
- api/tests/opentrons/protocols/fixtures/bundled_protocols/simple_bundle/protocol.py
- api/tests/opentrons/protocols/test_bundle.py
- api/tests/opentrons/protocols/test_parse.py
- api/tests/opentrons/test_simulate.py
- api/tests/opentrons/util/test_entrypoint_utils.py
Adds bundle handling and bundle creation to the simulate script.
You can now
- Specify directories to gather data files and labware defs from (python files are not yet supported)
- Specify a place to emit the bundle
- In addition to adding these features to simulate, centralized bundle parsing further
Look over the python code
Simulate some bundles
Create some bundles and simulate and/or run them
> feat(api): Add bundle creation to opentrons_simulate

- api/src/opentrons/config/advanced_settings.py
For the "use older pipette calibrations" feature flag, emphasize that this doesn't impact GEN2
pipettes
Closes #3596
> refactor(app): update older pipette calibrations ff text

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/types.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/cli/test_cli.py
We set the plunger currents to the values in the pipette config for most
actions, but do not do it when homing those axes. As a consequence, they home at
the robot config current values, which are 0.05A regardless of the kind of
pipettes. We've been mostly getting away with this, but there are positive
reports of skipping axes on gen2 pipettes.
Closes #3572
Home pipette plungers. Look at the smoothie logs and make sure that it's setting the current specified in the smoothie configs. Do this in both apiv1 and apiv2. You're looking for a line like this:
`Oct 02 20:54:01 OT2BK111111111 opentrons-api-serial[6395]: smoothie: Write -> b'M907 A0.1 B1.0 C0.05 X0.3 Y0.3 Z0.1 G4P0.005 G28.2B\r\n\r\n'`
This is the line that commands a B-axis home (note the `G28.2B`) and the current (`M907... B1.0`). …
> fix(api): Use proper currents for plunger home

- api/src/opentrons/legacy_api/containers/__init__.py
- api/tests/opentrons/containers/test_containers.py
- shared-data/labware/definitions/2/opentrons_1_trash_1100ml_fixed/1.json
- shared-data/labware/definitions/2/opentrons_1_trash_850ml_fixed/1.json
In 42deac230ce334e0a6ace69b756a1df5d8dd63e0 we changed the behavior of container
load to load v2 trash containers and dynamically modify the geometry to move the
"center" point +y by half the size of a multichannel pipette. This let our
multichannel pipettes dispense in the middle of the trash without having to
special case behavior at runtime. It also let us use the v2 trash definitions in
apiv1, which are more correct.
Unfortunately, one of the ways in which the old trash definitions were incorrect
was to put the "center" of the trash well at a very specific location for both
multi and single pipettes - y+80mm. With the correct geometry and special casing
based on the size of a multi, we were using y+85mm or so. This interacts badly
with a sheet metal change on the gantry, and robots …
> fix(api): change trash definitions to avoid y head crash

- .travis.yml
Travis cache upload is taking a very (very) long time at least on osx release builds; disable it, at least for now
> ci(travis): disable travis caching

- labware-library/src/components/website-navigation/styles.css
This PR serves as it own ticket. Some of the LC link styles were updated last week, to allow for easier overwriting links styles (links as buttons). Unfortunately, this applied the blue text color to all subdomain nav links. This PR sneaks in a little specificity to override that and once again, match the main website navigation.
Before:
Now:
- refactor(labware-library): Update subdomain navlink styles
> refactor(labware-library): Update subdomain navlink styles

- app/src/robot/api-client/client.js
Closes #4202 
In #4099, I added a new argument to `Session.create` to support bundle execution, but missed the case where the App version was ahead of the robot server. This makes App backwards-compatible when calling `Session.create` via RPC.
Push v3.12.0 on to a robot and check:
> fix(app): fix broken back-compat for pre-3.13.x robots

- labware-library/src/labware-creator/components/RadioField.js
> fix(labware-creator): fix radio group touched on change in Mac FF

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/util.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_util.py
Adds an equivalent to `head_speed` (and will be used to implement backcompat head_speed) to v2.
Set the head speed in protocols and make sure that the robot moves slower. Also check the smoothie logs and note that it's only set for each specific motion, and reset after, including if there's errors.
> feat(api): apiv2: add max speed control

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/LabwareSelectionModal/index.js
- protocol-designer/src/components/SettingsPage/FeatureFlagCard/FeatureFlagCard.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
With LC release, custom labware in PD can be a full-on feature! This PR promotes custom labware from an experimental feature to a normal one.
Since this PR removes the only feature flag that PD has, I made some placeholder comment junk so that we have a template for where in the code to add feature flags again.
~Soon after or maybe before this is merged, @mcous will have a PR to add a "Gen 2 Pipettes" feature flag to PD, so we can get rid of the placeholder stuff.~
*UPDATE:* Mike & I just talked -- in order not to rush, we'll merge this then do the Gen 2 pipette PR after the PD release
- see note above about the cruft & timing vs Mike's PR
> feat(protocol-designer): promote custom labware upload to full feature

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/localization/en/modal.json
- protocol-designer/webpack.config.js
Oops I missed this copy + link change. Now it should be "Access Labware Creator here" and the "here" should link to https://labware.opentrons.com/create
- bump version for next RC
- Copy OK
- Link goes directly to LC
> fix(protocol-designer): fix copy & link for custom labware

- .travis.yml
Since we now merge to master before tagging, we can change the docs deploy to
trigger on master builds.
When we switch to a separate build/deploy model, we can upload docs during the deploy. For now, deploying on master means we only deploy on actual customer-facing builds.
> chore(deploy): only deploy api docs on master

- .flowconfig
- app/src/components/ChangePipette/InstructionStep.js
- app/src/components/ChangePipette/index.js
- components/src/__tests__/instrument-diagram.test.js
- components/src/instrument/InstrumentDiagram.js
- components/src/instrument/InstrumentDiagram.md
- components/src/instrument/InstrumentGroup.md
- components/src/instrument/PipetteSelect.css
- components/src/instrument/PipetteSelect.js
- components/src/instrument/PipetteSelect.md
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/js/helpers/wellSets.js
- shared-data/js/pipettes.js
- shared-data/js/types.js
- shared-data/pipette/definitions/pipetteNameSpecs.json
- shared-data/pipette/schemas/pipetteNameSpecsSchema.json
This PR adds the new pipette select component from #3996 and adds it to PD behind a feature flag.
- refactor(app,pd): add GEN1 category to OG pipettes, FF'd GEN2 select to PD
Due to lack specs/screens, I had to make the following judgement calls:
- A `displayCategory` for original pipettes of `GEN1` was added to the pipette config and UI as per various ad-hoc Slack conversations and #4138 
- No design assets existed for this, but since they followed the GEN2 designs I don't think this is a problem
- There were no specs nor screens for the selected state of the pipette dropdown, so I chose to use the given pipette's `displayName`
- At the moment, the original pipette's `displayName` properties **do not include "GEN1"**
- Do they need to be updated?
App:
1. Enable dev tools
2. Go to the …
> refactor(app,pd): add GEN1 category to OG pipettes, FF'd GEN2 select to PD

- api/src/opentrons/config/advanced_settings.py
- api/tests/opentrons/server/test_settings_endpoints.py
GET /settings now has an additional "restart_required" key in the individual
settings objects, which should be true or false. If true, the robot should be
restarted after changing the flag.
Also changes the wording of the api2 feature flag now that it is entering beta.
@Opentrons/js This should allow the runapp to automatically pop a modal to restart the robot after changing these flags.
`restart_required` should be `True` for the api v2 flag, and `False` for everything else.
> feat(api): Specify if a restart is required after changing some ffs

- api/src/opentrons/api/session.py
- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/execute.py
- api/src/opentrons/server/endpoints/settings.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
- api/tests/opentrons/server/test_settings_endpoints.py
Adds a new feature flag to enable apiv1 backcompat when apiv2 is enabled.
This feature flag should only show up in GET /settings when apiv2 is enabled.
If this new feature flag is enabled, pass apiv1 protocols uploaded when apiv2 is
selected to the backcompat executors.
Gate this functionality in opentrons_simulate and opentrons_execute behind the
new flag.
- The feature flag should only appear if apiv2 is set
- If the feature flag is not set, using an apiv1 protocol with runapp upload, `opentrons_simulate`, or `opentrons_execute` should give you an error
- If the feature flag is set, using an apiv1 protocol with runapp upload, `opentrons_simulate` or `opentrons_execute` should "work" (it will try to execute it using the backcompat executor, which does not currently work)
> feat(api): apiv2: conditionally enable backcompat

- api/src/opentrons/hardware_control/adapters.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/legacy_wrapper/__init__.py
- api/src/opentrons/protocol_api/legacy_wrapper/api.py
- api/src/opentrons/protocol_api/legacy_wrapper/instrument_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/robot_wrapper.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/protocol_api/test_back_compat.py
- api/tests/opentrons/tools/test_qc_scripts.py
Implements the most common publically accessible robot methods on top of the protocol contexts. Using this, you should be able to connect and disconnect, pause and resume, reset, set comments, and the like. Most of the work here is in the structure, and the individual calls are very simple as a result. 
Run some back compat protocols, using only these robot methods. Also make sure it works in jupyter and from a python interactive shell if you build the globals manually.
> feat(api): apiv2: implement robot methods backcompat

- api/docs/source/v1/labware.rst
- api/docs/source/v2/new_labware.rst
- api/src/opentrons/legacy_api/api.py
- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/containers/test_containers.py
- labware-library/src/components/LabwareList/__tests__/__snapshots__/LabwareList.test.js.snap
- shared-data/js/__tests__/labwareDefSchemaV2.test.js
- shared-data/labware/fixtures/2/fixture_12_trough_v2.json
V2 labware definitions have versions, which are bumped whenever the geometry
definitions change. It's important to be able to specify the version to load.
APIv2 allows this; the patch to add labware v2 loads from apiv1 does not. This
closes that gap.
Closes #4216
The code here is ready to review, but this PR shouldn't be merged until docs are in.
> feat(api): v1: Add version specification to labware.load

- api/src/opentrons/legacy_api/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette_unittest.py
A bug was introduced in `mix` in APIv1 by #3692. In APIv1, mix arguments - repetitions, volume, and location, are all optional. Currently, if a mix location is not present, the mix volume would always get updated to the working volume of the pipette. The pipette is therefore mixing at an incorrect volume.
Additionally, `mix` does not validate the type of the volume argument. This means that if a location is passed rather than a volume, it is mistakenly considered as the mix volume. The location would then be interpreted as absent and hence, both the mix volume and location will be updated based on the logic mentioned above.
- check volume type, if it's a placeable and a mix location is missing, set it as the location and update the volume to be the pipette's available volume (working …
> fix(api): correctly handle mix optional arguments

- protocol-designer/src/analytics/actions.js
- protocol-designer/src/analytics/fullstory.js
- protocol-designer/src/initialize.js
Make similar changes to PD's Fullstory stuff so it mirrors LL/LC's FS setup in #4177
- Update Fullstory snippet, they've added additional arguments
- Enable linting and flow checking this file
- Rename generic things to Fullstory where relevant (I imagine if we have multiple integrations, they'll use their own files instead of 1 big file)
- Add `ot_application_name_str: 'protocol-designer'` analytics tag b/c we're re-using the same FS org across apps and it might be helpful to filter on this?
- Should work the same as before, please test in sandbox and check FS
> refactor(pd): update FS snippet; enable linting/flow

- protocol-designer/src/components/PrereleaseModeIndicator.js
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/SettingsPage/FeatureFlagCard/FeatureFlagCard.js
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/configureStore.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/card.json
- protocol-designer/src/localization/en/feature_flags.json
Closes #4143. The goals of this "prerelease mode" are:
- allow us to release PD with latent features that don't get exposed to users
- allow internal stakeholders to try out these latent features in builds
- avoid blocking PD releases due to long-running projects being in a WIP state
- implement prerelease mode flag and separate user-facing flags ("Experimental Settings") vs prerelease-mode-only flags
- add placeholder TODO for modules in the New File Modal (hidden under a flag)
- To enter prerelease mode, open the JS console and type `enablePrereleaseMode()` and hit Enter. (To open the JS console in Chrome, press Command+Option+J for Mac or Control+Shift+J 
for Windows/ Linux)
- When in prerelease mode, you should see a red and black ⚠️ icon in the top right
- When in prerelease mode, …
> feat(protocol-designer): Implement prerelease mode + settings

- labware-library/src/labware-creator/components/IntroCopy.js
- labware-library/src/labware-creator/components/LabwareCreator.css
- labware-library/src/labware-creator/styles.css
#4031 inadvertently introduced global CSS into the Labware Library stylesheet, breaking the filter link highlighting in labware library
- Removed global styles from labware creator CSS
Please remember that CSS modules **only works with class names** and things nested under classNames. If you use element tags or put element tags nested without an `&` first, the style becomes global
- Please check the sandbox as well as local dev
> fix(labware-library): fix leaky creator CSS from creator breaking filter link styling

- app/src/components/AddLabwareCard/__tests__/AddLabwareCard.test.js
- app/src/components/AddLabwareCard/__tests__/__snapshots__/AddLabwareCard.test.js.snap
- app/src/components/AddLabwareCard/index.js
- app/src/components/AppSettings/AdvancedSettingsCard.js
- app/src/components/InstrumentSettings/AttachedModulesCard.js
- app/src/components/ListLabwareCard/__tests__/ListLabwareCard.test.js
- app/src/components/ListLabwareCard/__tests__/__snapshots__/ListLabwareCard.test.js.snap
- app/src/components/ListLabwareCard/index.js
- app/src/components/MenuPanel/index.js
- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/ControlsCard.js
- app/src/components/analytics-settings/AnalyticsSettingsCard.js
- app/src/config/index.js
- app/src/config/selectors.js
- app/src/config/types.js
- app/src/pages/More/CustomLabware.js
- app/src/pages/More/index.js
- components/src/structure/Card.js
- components/src/structure/RefreshCard.js
Closes #4243. See ticket for more details and acceptance criteria.
This PR:
- Adds a feature flag to the app for custom labware: `customLabware`
- Adds a More > Custom Labware page with empty cards to the app behind that feature flag
- refactor(app): add empty More > Custom Labware page behind feature flag
1. Navigate to More > App Settings
2. Toggle `__DEV__ Custom Labware` to enabled
Card titles are still a design WIP. Please ignore them for the purposes of this review.
> refactor(app): add empty More > Custom Labware page behind feature flag

- .travis.yml
- RELEASING.md
Deploy docs builds to an s3 bucket with a branch-named prefix.
This is prep for using our website deploy scripts to make the docs site live
instead of using github pages.
Note that as currently implemented, a minority of the links in the sidebar (among others) aren't relative and will direct you to docs.opentrons.com; that's going to be fixed in #4248
> ci(travis): deploy API docs to s3

- api/src/opentrons/deck_calibration/dc_main.py
The _helper_tip_pickup function in cli deck cal operates on a position that was
calculated in deck coordinates taking model offset into account, but sends it
directly back into the driver. Positions are therefore off by the model offset,
meaning p1000s move up 20mm before picking up a tip and p10s move down 17mm
before picking up a tip.
This removes the model offset before picking up a tip.
Closes #4250
- Pick up a tip during CLI deck calibration on APIv1 using a p10, a p1000, and a p50 (or p300)
> fix(api): api1: consider model offset in cli deck cal tip pickup

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
ed483822a014061f031c64aaff717a32e9f606aa was actually broken in its
implementation, because if update=false the old saved speed would be set instead
of the new value. This fixes the issue.
Testing: set a non-default flow rate and notice that it actually has an effect now.
> fix(api): apiv2: correctly set smoothie speed

- app-shell/Makefile
- app-shell/src/exports.js
- app-shell/src/preload.js
- app-shell/webpack.config.js
- app/Makefile
- babel.config.js
- discovery-client/Makefile
- discovery-client/package.json
- discovery-client/webpack.config.js
- package.json
- webpack-config/index.js
- webpack-config/lib/node-base-config.js
- yarn.lock
This PR switches the build process of app-shell and discovery-client from `babel-cli` to `webpack`. This enables:
1. app-shell to pull in pre-compiled opentrons dependencies (like shared-data)
2. a consistent, compile-free experience for discovery-client consumers
(1) makes implementing #4244 a lot easier, because we'll be able to pull shared-data's labware validation functions into app-shell. (2) is just a nice to have that we get for free with this switch.
This PR adds a new base config to @opentrons/webpack-config: `nodeBaseConfig`. It has the following differences from `baseConfig`:
- The compile target is `node` rather than `web`
- The export is `commonjs` instead of the default `var`
- `BundleAnalyzerPlugin` is the only included plugin
- `node_modules` dependencies (other than …
> build(app-shell,discovery-client): switch from babel-cli to webpack

- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
In transfer and distribute commands in APIv2, touch tip is set to happen after any blow out commands. This means that if there is a disposal volume, or the user-specified blow-out location is at the trash, the pipette would blow out and then touch tip at the trash!
_Note_ this behavior has already been fixed in APIv1 by #4231
- make touch tip always happen before blow out
- add test to check desired behaviors
Run this protocol and make sure the pipette touches tip before blowing out at the trash or at the specified location.
```
def run(protocol):
tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', '1')
res12 = protocol.load_labware('usascientific_12_reservoir_22ml', '4')
m300 = protocol.load_instrument(
'p300_multi', 'left', tip_racks=[tiprack])
m300.distribute(30, …
```
> fix(api): apiv2: always touch tip before blow out

- app/package.json
- components/package.json
- discovery-client/package.json
- labware-designer/package.json
- package.json
- protocol-designer/package.json
- protocol-library-kludge/package.json
- shared-data/package.json
- yarn.lock
Just a PR to upgrade flow to latest. For once, the upgrade doesn't require any code changes. Please 👍 if your local workflow doesn't break.
- chore(flow): upgrade flow to 0.110.0
```shell
yarn
yarn flow stop
yarn flow check
```
- Note: you probably want to make sure your editor is configured to use flow from node_modules if available
> chore(flow): upgrade flow to 0.110.0

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
API v2 did not accept Location types as valid places to perform transfers. As that behavior does not align with API v1, this PR fixes that and serves as a ticket for documenting the issue.
- Also check whether an argument for source/dest is a location
- Add test that uses Location types as inputs for source and destination
You can mess around with different combinations using this protocol and see that the location inside the well changes as expected:
```
from opentrons import types
def run(ctx):
tiprack1 = ctx.load_labware('opentrons_96_tiprack_300ul', 2)
pip = ctx.load_instrument('p300_single_gen2', mount='right', tip_racks=[tiprack1])
plate = ctx.load_labware('corning_96_wellplate_360ul_flat', 3)
plate_to_move = types.Location(types.Point(0.5, 0.5, 1.0) + …
```
> fix(api): Allow Location types in advanced liquid handling functions

- api/src/opentrons/protocol_api/contexts.py
This serves as a ticket and code change. In API v1, users were able to turn off the default homing position for `drop_tip` by specifying `drop_tip(home_after=False)`. This behavior is in hardware controller, but not in the user facing `drop_tip` method.
- Edit signature of drop_tip in `contexts.py` to allow for homing
Test that drop tip doesn't home after when you specify home_after=False
> refactor(api): Allow disable home for drop tip in api v2

- labware-library/src/components/labware-ui/labware-images.js
We want to make sure the P20 tip rack definition (created in #3929) is added to the Labware Library so that users can use it with the P20 Gen2 pipettes. 
closes #3964
> feat(labware-library): add P20 tip rack image to library

- protocol-designer/src/labware-ingred/actions/actions.js
- protocol-designer/src/step-forms/actions/modules.js
- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/test/reducers.test.js
- protocol-designer/src/step-forms/types.js
- protocol-designer/src/step-forms/utils.js
Addresses #4132 - for module creation/deletion/placement on the deck. All that should be left is selectors which will come next!
This should set us up to have meaningful data representation of modules on the deck which responds correctly to all the module/labware actions
This PR adds a bunch of tests to existing labware placement behavior in the reducers, and a bunch more for modules on the deck and labware-module swap interactions as we've diagrammed on paper.
* add module invariant properties reducer
* expand the savedStepForms reducer's initial deck setup step to respond to module placement
* add tests for existing labware stuff (added passing tests before making changes to the reducers) and add tests for new module state stuff
- This was TDD'd and has good coverage so reviewing tests …
> feat(protocol-designer): add reducers for module placement

- api/src/opentrons/server/__init__.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/server/test_settings_endpoints.py
A few devs were seeing the `Too many files open` OS error on their local computer. This modifies a few things about how we handle websockets in `conftest` and when we copy files over using `shutil` which reduced the errors on my local computer. I was unable to fully prevent the too many files open error from occurring at all, but I decided it was time to move on to other things.
- Manually close the client test fixture after yield statement
- Deleted unnecessary calls to `async_server` in `test_settings_endpoints`
- Reduced amount of times the template db was copied over for the config directory
Um..not really sure how to test? I guess set the limit of your open files back down to default which is 256.
> refactor(api): Modify test socket handling to reduce too many files open error

- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/server/test_settings_endpoints.py
POST /settings now has a "links" field in its response. If the "links" field
contains a "restart" element, that element is a URI pointing to /server/restart,
and its presence indicates that the client should restart the robot using that
API.
The restart link is present if a setting that has the "restart_required" field
is changed.
- The response body should be the same as previously but with a (usually) empty "links" subobject
- There should only be an entry in "links" if you change the useProtocolApi2 flag
This should unblock #4285
> refactor(api): add restart links to settings

- app/src/analytics/selectors.js
- app/src/components/RobotSettings/AdvancedSettingsCard.js
- app/src/components/RobotSettings/RestartRequiredBanner.js
- app/src/components/RobotSettings/styles.css
- app/src/epic.js
- app/src/pages/Calibrate/Labware.js
- app/src/pages/Robots/RobotSettings.js
- app/src/reducer.js
- app/src/robot-admin/__tests__/epic.test.js
- app/src/robot-admin/actions.js
- app/src/robot-admin/epic.js
- app/src/robot-api/resources/settings.js
- app/src/robot-api/resources/types.js
- app/src/robot-api/types.js
- app/src/robot-settings/__tests__/actions.test.js
- app/src/robot-settings/__tests__/epics.test.js
- app/src/robot-settings/__tests__/reducer.test.js
- app/src/robot-settings/__tests__/selectors.test.js
- app/src/robot-settings/actions.js
- app/src/robot-settings/constants.js
- app/src/robot-settings/epic.js
- app/src/robot-settings/index.js
- app/src/robot-settings/reducer.js
- app/src/robot-settings/selectors.js
- app/src/robot-settings/types.js
- app/src/types.js
~Blocked by #4283, PR will be rebased when 4283 is merged~ Rebased and ready
This PR closes #4267 by wiring the new restart action+state from #4283 to the AdvancedSettingsCard.
Following up on what we established with buildroot, this PR also refactors robot settings into its own state subtree (`robotSettings`) to finally bail out of the organizational problems that have plagued the app's HTTP-fed state
- feat(app): add robot restart alert for FF changes that require restart
**Requires a robot or virtual smoothie running #4290 or later**
If you want to test with virtual smoothie *before* 4290 is merged:
1. Checkout 4290 branch
2. Start API dev server
3. Checkout **this branch** to run your dev app
3. To simulate a "restart", kill your server and restart it
4. After you kill your server, …
> feat(app): add robot restart alert for FF changes that require restart

- shared-data/protocol/schemas/3.json
This allows applications to specify new generations of pipette without having to
modify the schema every time.
Closes #4235
> refactor(shared-data): remove enum from protocol schema pipette type

- api/src/opentrons/execute.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/test_simulate.py
With API v2 beta imminently approaching we want to encourage users to convert and/or write new protocols in API v2. Instead of forcing them to specify a feature flag every time they want to locally simulate their protocols, we should assume the version. Also, for jupyter notebook, people should be able to easily simulate their commands in API v2. This PR adds in a method which allows you to access a simulating context.
- Remove the feature flag check for server versions and only check based on protocol type + version
- Add method to access a simulating protocol context
1. Simulate API v2 protocol and make sure no errors occur
2. Simulate API v1 protocol and make sure no errors occur
3. Simulate JSON protocol
4. Import `opentrons.simulate.get_protocol_api` and see that you can simulate …
> refactor(api): Remove FF in simulation and add simulating context

- api/docs/source/v2/new_modules.rst
- api/src/opentrons/drivers/temp_deck/driver.py
- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/legacy_api/modules/tempdeck.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py
- api/tests/opentrons/hardware_control/modules/test_hc_tempdeck.py
- api/tests/opentrons/protocol_api/test_module_context.py
In the interest of consistency, this makes the tempdeck's set_temp call hold until the temperature
is reached by default. This is the same behavior as the thermocycler api. The ability to continue
work while an on going set temperature command is occuring will be covered by an upcoming addition
that handles that concern at the top protocol scope.
APIv2's tempdeck context's `set_temperature` function should not proceed with the execution of the protocol until the temperature is reached. In addition, the `wait_for_temp` function is no longer present on the tempdeck's context. Its behavior will be recaptured by a generalized "wait for condition" solution that is forthcoming.
> refactor(api): make apiv2 tempdeck set_temp behave like TC

- api/src/opentrons/hardware_control/simulator.py
@ahiuchingau found a bug in simulation where the ~run flag is set during resume instead of pause.~ simulator throws an error when the run flag is set. This should be the opposite because the run flag symbolizes that move actions are valid.
> fix(api): Set run flag for pause instead of resume

- app/src/components/ChangePipette/Instructions.js
- app/src/components/ChangePipette/PipetteSelection.js
- app/src/components/ChangePipette/index.js
- app/src/components/ChangePipette/types.js
- app/src/config/index.js
- app/src/config/types.js
This PR closes #3601 by removing the GEN2 pipettes FF + enabling them by default in the add/change pipettes wizard.
- feat(app): Enable GEN2 pipettes
> feat(app): Enable GEN2 pipettes

- api/src/opentrons/drivers/thermocycler/driver.py
- api/src/opentrons/hardware_control/modules/__init__.py
- api/src/opentrons/hardware_control/modules/magdeck.py
- api/src/opentrons/hardware_control/modules/mod_abc.py
- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/hardware_control/modules/update.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/legacy_api/modules/__init__.py
- api/src/opentrons/server/endpoints/update.py
- api/src/opentrons/server/http.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/hardware_control/modules/test_hc_magdeck.py
- api/tests/opentrons/hardware_control/modules/test_hc_tempdeck.py
- api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
- api/tests/opentrons/hardware_control/test_modules.py
- api/tests/opentrons/labware/test_modules.py
- api/tests/opentrons/server/test_control_endpoints.py
- api/tests/opentrons/server/test_update_endpoints.py
Use bossac to upload firmware binaries to a connected thermocycler. Add logic to differentiate
module bootloader types and update accordingly.
Closes #3973
- fix up apiv2 firmware update endpoint to function proper
- use `bossac` subprocess to upload received firmware to connected TC
- bootloader_type class property
- remove unused apiv1 module firmware update code
- return prompt to update api server if attempting to update module via apiv1
> feat(api): add ability to update TC firmware from robot

- api/src/opentrons/api/models.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/data/testosaur-gen2-v2.py
- api/tests/opentrons/data/testosaur-gen2.py
When the user specifies an instrument as the name ("p300_single", "p10_single")
but a compatible GEN2 pipette is connected, the instrument name in rpc shows up
as the pipette connected to the robot.
Add an RPC-visible element called "requested_as" to the instrument model that is
the string the user used to request the instrument.
> feat(api): reflect original instrument name via rpc

- shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
- shared-data/pipette/definitions/pipetteNameSpecs.json
Per discussion in Slack, this PR adds "GEN1" to the end of gen1 pipettes display names
- feat(shared-data): add "GEN1" to gen 1 pipette display names
- Pipette select
- Protocol info page in app
- Calibration page in app
- Pipette select in PD
> feat(shared-data): add "GEN1" to gen 1 pipette display names

- app-shell/src/buildroot/index.js
- app-shell/src/buildroot/release-files.js
- app-shell/src/buildroot/update.js
- app-shell/src/config.js
- app-shell/src/discovery.js
- app-shell/src/http.js
- app-shell/src/log.js
- app-shell/src/main.js
- app-shell/src/robot-logs.js
- app-shell/src/ui.js
- app-shell/src/update.js
- app-shell/webpack.config.js
- babel.config.js
#4260 switched the build process of app-shell from babel to webpack. Because the source files are now bundled, `__filename` and `__dirname` refer to **the bundle** rather than the source files. This threw off the path resolution to the BR pre-migration wheels.
This PR fixes usage of `__dirname` and `__filename` in app-shell to resolve premigration issues, and adds a guard to the `http::postFile` utility function to properly throw errors if the function is called with a file that can't be found
- refactor(app-shell): fix BR premigration paths with webpackification
> refactor(app-shell): fix BR premigration paths with webpackification

- app/src/pages/Robots/RobotSettings.js
- app/src/robot-admin/__tests__/reducer.test.js
- app/src/robot-admin/__tests__/selectors.test.js
- app/src/robot-admin/reducer.js
- app/src/robot-admin/selectors.js
- app/src/robot-settings/__tests__/actions.test.js
- app/src/robot-settings/__tests__/epics.test.js
- app/src/robot-settings/__tests__/reducer.test.js
- app/src/robot-settings/__tests__/selectors.test.js
- app/src/robot-settings/actions.js
- app/src/robot-settings/constants.js
- app/src/robot-settings/epic.js
- app/src/robot-settings/reducer.js
- app/src/robot-settings/selectors.js
- app/src/robot-settings/types.js
This PR fixes some state mistakes in #4285 that resulted in:
- The restart spinner going away prematurely
- The restart required banner persisting even after the robot was restarted
- refactor(app): cleanup restart required state during restart
Where "behaves normally" means:
> refactor(app): cleanup restart required state during restart

- api/src/opentrons/commands/commands.py
In V2, transfer run logs usually looked something like this image
whereas the run logs in api v1 looked like this image 
- Make recursive func return once a list is not nested
Check that transfer logs don't look ugly now
> fix(api): Modify list check to return first item of source and dest

- api/src/opentrons/hardware_control/simulator.py
In
150c7847994962733cbcc786b50b315d78562d59 (https://github.com/Opentrons/opentrons/pull/4294)
we changed the sense of the run flag in the apiv2 simulator to be clear = pause,
set = run. However, we didn't initialize it to set, so we always get the error
message.
It's also unclear if this error message is useful. A pause without a
corresponding resume most likely means the user wants to pause and not resume
until they click resume in the run app, which is a normal case.
This initializes the flag but also removes the warnings.
> fix(api): apiv2: initialize simulator runflag

- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/legacy_api/robot/robot.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/robot/test_robot.py
During labware calibration, the pose tree was being updated only for the single instance that was being calibrated, but the calibration delta was being added to the calibration file on disk, so if you calibrated more than one labware of the same load name (or, more specifically, with the same labware hash) in a single session, you would get the sum of all of the deltas for that session as the new offset. This PR updates all the matching items in the pose tree to avoid this behavior.
Still needs to be tested on robots
Fixes #4288
> fix(api): update all pose tree state when calibrating labware

- protocol-designer/src/components/FilePage.css
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/ProtocolEditor.css
- protocol-designer/src/components/ProtocolEditor.js
- protocol-designer/src/components/modals/EditModulesModal/EditModules.css
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/components/modules/EditModulesCard.js
- protocol-designer/src/components/modules/ModuleRow.js
- protocol-designer/src/localization/en/tooltip.json
This PR addresses #4133 by adding the Add/Edit modules modal with disabled slot dropdown.
Follow up PR will enable slot dropdown upon presence of unrestricted modules FF.
- feat(protocol-designer): Add edit modules modal
Standard code and UI review
> feat(protocol-designer): Add edit modules modal

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/components/modules/EditModulesCard.js
- protocol-designer/src/components/modules/ModuleRow.js
- protocol-designer/src/modules/index.js
- protocol-designer/src/modules/moduleData.js
closes #4133 by adding the ability to select unsupported slots in EditModulesModal when unrestricted modules FF is enabled
- feat(protocol-designer): Enable slot selection for modules when FF enabled
- refactor(protocol-designer): Move module data and functions to `modules/`
Standard code review - See notes but I added a hook that defaults slot selection to the supported slot. This is either a workaround or throw away work until module data comes from state. I'm also open to suggestions on a different way to do this before implementing redux stuff and formik.
FF disabled:
FF enabled:
> feat(protocol-designer): Enable slot selection for modules when FF enabled

- app/src/components/ListLabwareCard/styles.css
- components/src/index.css
- components/src/styles/spacing.css
I added some CSS spacing variables to the components library in #4268. The variables names were attached to :root and conflicted with the spacing variable names already in Labware Library, severely breaking the labware library styling
- refactor(components): remove spacing variables from components library
> refactor(components): remove spacing variables from components library

- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
closes #4334 - bug causing drag-and-drop of labware to fail when you loaded a file
Note: this bug was never released to production
Make sure it fixes the bug:
> fix(protocol-designer): fix bug in manualIntervention step

- api/src/opentrons/config/robot_configs.py
- api/src/opentrons/server/endpoints/settings.py
- api/src/opentrons/server/http.py
- api/tests/opentrons/server/test_settings_endpoints.py
Quality of life endpoint to aid in debugging.
A GET request to /settings/robot now returns a json blob that contains all raw robot settings and deck/gantry calibration values.
> feat(api): add http endpoint for robot settings dump

- app/src/components/DeckMap/index.js
- components/src/deck/RobotWorkSpace.js
- components/src/deck/RobotWorkSpace.md
- components/src/deck/types.js
- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/DeckSetup/SlotWarning.css
- protocol-designer/src/components/DeckSetup/SlotWarning.js
- protocol-designer/src/localization/en/deck.json
closes #4332
- refactor `DeckSetup`
- show "No 8-Channel GEN1 access" warning where appropriate
- rename `RobotWorkSpace`'s `slot` arg to `deckSlotsById`
Start with "disable module restriction" setting OFF.
> feat(protocol-designer): show special-case warning for north/south

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/modules/EditModulesCard.js
- protocol-designer/src/components/modules/ModuleRow.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-forms/types.js
Addresses #4317 by adding `getModulesForEditModulesCard` selector for populating the Modules card with module on deck data from state.
- Add selector `getModulesForEditModulesCard`
- Wire up ModulesCard with `ModulesForEditModulesCard`
- Wire up Remove button with `deleteModule`
> feat(protocol-designer): Wire up modules card with actual data

- protocol-designer/webpack.config.js
Bump to 3.0.7 to kick off QA.
Major changes to NEST labware that was formerly unusably broken and so the defs have been mutated without version bump.
Also new quirk `touchTipDisabled` in the defs. PD doesn't look at that, API will ignore touch tips on trough-likes. That's existing behavior.
Also many latent changes for modules on deck work in progress; we'll have to check these are truly latent.
- expose GEN2 pipettes in pipette select (#4351)
- updates to LabwareSelectionModal (#4325) -- only color change should be user-facing
- do not touch tip on troughs (#4271) -- added `touchTipDisabled` quirk to multiple labware
- swap X/Y spacing for 24-well nest tuberacks (#4240)
- show special-case warning for north/south (#4361)
- add module slot visualization (#4355)
- fix never-released bug in …
> chore(protocol-designer): bump to 3.0.7

- api/src/opentrons/__init__.py
- api/src/opentrons/execute.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/legacy_wrapper/api.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/server/__init__.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/protocol_api/test_back_compat.py
- api/tests/opentrons/protocol_api/test_legacy_migration.py
Closes #3542. Any custom labware from the API V1 database should now be migrated into API V2 format under the custom labware location with the `legacy_api` as the namespace.
- add a migration function which filters out labwares and only creates unfound labwares in v2 with a new namespace called `legacy_api`
- Migration function can get called either on api server start or the simulate/execute entrypoints
@IanLondon if you have time, sanity checking these definitions would be helpful. For others testing, please set `MIGRATE_V1_LABWARE` on the robot's OS environment variable (etc/profile.d/ot-environ.sh) and then load the labware using the `namespace` key in api v2. Once the labware load backcompat function is fully implemented we can retest loading the labware.
> feat(api): Migrate DB Labware into V2 Format

- api/src/opentrons/api/session.py
- api/src/opentrons/execute.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocols/parse.py
- api/src/opentrons/protocols/types.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/data/testosaur-gen2-v2.py
- api/tests/opentrons/data/testosaur_v2.py
- api/tests/opentrons/protocol_api/test_execute.py
- api/tests/opentrons/protocols/fixtures/bundled_protocols/simple_bundle/protocol.py
- api/tests/opentrons/protocols/test_parse.py
- app/src/components/CalibrateLabware/ConfirmModalContents.js
- app/src/robot/actions.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/session.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/session-reducer.test.js
This allows and requires apiv2 users to have
'apiLevel': '2.0'
in their metadata dict.
This is parsed and stored along with the protocol and passed along with RPC.
This allows specification of API minor versions.
Closes #4338
> feat(app,api): allow rich version specification for python protocols

- app/package.json
- app/src/components/RobotSettings/connection.js
- app/src/http-api-client/__tests__/networking.test.js
- app/src/http-api-client/networking.js
- yarn.lock
This PR adds CIDR-notation string parsing to the IP address display of the robots page. Closes #4075
- feat(app): parse subnet out of CIDR-notation IP address
A couple things to note:
- The `networking` subtree needs a lot of work. This API-client-state refactor work is ongoing anyway, so this PR makes the smallest change possible to enable this functionality
- I pulled in one dependency for CIDR-notation parsing
- I didn't want to write my own
- I used the smallest one most widely used one I could find, and it's dependency-free
- https://github.com/rs/node-netmask/
Anyway, open up the app and click on a robot. It should:
> feat(app): parse subnet out of CIDR-notation IP address

- api/docs/v2/index.rst
- api/docs/v2/versioning.rst
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/server/endpoints/__init__.py
- api/tests/opentrons/server/test_health_endpoints.py
As well as adding more docs about protocol API versioning.
The max supported version is exposed in the /health endpoint as
'protocol_api_version': [major, minor].
Closes #4341
> feat(api): add the maximum supported protocol api version

- app/src/components/FileInfo/InstrumentItem.js
- app/src/components/FileInfo/ProtocolPipettesCard.js
- app/src/components/FileInfo/index.js
- app/src/components/FileInfo/useInstrumentMountInfo.js
- app/src/components/nav-bar/NavButton.js
- app/src/pages/Upload/FileInfo.js
- app/src/pages/Upload/index.js
If a protocol has no errors, the app will now display an error message in the FileInfo page and disable the calibration and run pages
Closes #3121
- fix(app): prevent user from proceeding if uploaded protocol has no steps
1. Upload a protocol with no aspirates and dispenses
> fix(app): prevent user from proceeding if uploaded protocol has no steps

- api/src/opentrons/api/session.py
- app/src/components/RunLog/SessionAlert.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
This PR:
- Adds `session_manager.session.errors` to the redux state
- Uses the errors in redux state or from the protocol run request to populate the message of the `SessionAlert` banner in the run page
Closes #4367
- fix(app): display session error messages in SessionAlert
1. Load a protocol that will result in a runtime error
- For example: a protocol that loads a module but does not use it (see #4368)
2. Run the protocol
3. When the protocol errors:
4. Disconnect from the robot and reconnect
5. Go to "Run" page
**Note**: Due to RPC weirdness, the error message that displays if you remain connected vs the error message if you reconnect will be slightly different. This is because the RPC API is awful, and fixing it is not worth the effort.
Also, if you...
1. Start a run
2. Disconnect
3. …
> fix(app,api): display session error messages in SessionAlert

- components/src/modals/ContinueModal.js
- protocol-designer/src/components/Hints/index.js
- protocol-designer/src/components/Hints/useBlockingHint.js
- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/containers/ConnectedMainPanel.js
- protocol-designer/src/localization/en/alert.json
- protocol-designer/src/tutorial/index.js
- protocol-designer/src/tutorial/selectors.js
Closes #4329 
Add new "blocking hint" functionality, previously PD's Hints did not have any effects except on their own dismissed state
> feat(protocol-designer): blocking hint on adding custom labware to modal

- api/docs/v2/new_advanced_running.rst
- api/src/opentrons/api/session.py
- api/src/opentrons/execute.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocols/parse.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_execute.py
- api/tests/opentrons/protocol_api/test_execute_v3.py
When we create a protocol context, give it the requested protocol API version.
Do not allow the simulation or execution of protocols that request a version
above the highest version this release of the software supports.
This behavior should be consistent across all entry points: rpc protocol
session, opentrons_execute/get_protocol_api,
opentrons_simulate/get_protocol_api. The get_protocol_api functions now take an
optional argument to limit the protocol api version to user specifications (with
a default of the max supported version)
Closes #4342
> feat(api): apiv2: Limit protocols to max supported version

- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/hardware_control/modules/update.py
- api/src/opentrons/legacy_api/modules/tempdeck.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/util.py
- api/src/opentrons/server/endpoints/update.py
This adds a do-nothing decorator that lets you specify the version of an API
call.
It also changes the module firmware uploaders in apiv2 to use a different method to get the config
file for avrdude to resolve a circular import issue.
Unfortunately module updates fail because our avrdude.conf has bad syntax but I'll fix that in a separate PR.
Closes #4339
> refactor(api): apiv2: tag all methods and attrs with version added

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/tests/opentrons/drivers/test_driver.py
This log statement was confusing to users, as it seemed to report an error (which are assumed to be a failure or otherwise fatal action that needs to be corrected) when it was in fact not a problem.  The message might still be relevant to a developer working on this module, so suppressing it specifically when checking if a pipette is present or not.
Closes #4096 
Here's the new behavior (prior behavior was an error message after `robot.connect()`--see ticket)
> fix(api): Suppress error log during check for pipettes

- api/docs/v1/conf.py
- api/docs/v2/conf.py
- api/docs/v2/new_atomic_commands.rst
- api/docs/v2/new_complex_commands.rst
- api/docs/v2/new_labware.rst
- api/docs/v2/new_modules.rst
- api/docs/v2/new_pipette.rst
- api/docs/v2/new_protocol_api.rst
- api/docs/v2/versioning.rst
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/legacy_wrapper/robot_wrapper.py
- api/src/opentrons/protocol_api/util.py
The requires_version decorator now adds a sphinx version-added role to the
docstring of whatever it decorates (with some odd spacing to make it parse
correctly). This causes a nice little "New in version x.y" line to show up in
the autogenerated docs.
In addition, manually add versionadded stanzas to all the docs that mention
specific methods or attributes.
Closes #4340
> chore(docs): apiv2: Document the version all ifaces were added

- api/tests/opentrons/data/testosaur.py
- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/constants.js
- protocol-designer/src/step-forms/utils.js
This PR closes #4317 and addresses #4137 by adding Add/Edit capabilities to the `EditModulesModal`. 
It also does a first pass at validation (slot occupied) which requires some UX input. That will be handled in a follow up PR.
- feat(protocol-designer): Enable adding and editing modules in file page
- refactor: Move `getSlotIsEmpty` to utils
> feat(protocol-designer): Enable adding and editing modules in file page

- protocol-designer/src/components/LabwareSelectionModal/LabwarePreview.js
- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/LabwareSelectionModal/styles.css
- protocol-designer/src/localization/en/modal.json
Closes #4135
Also fixes issue where LabwareSelectionModal did not close when you click outside
This adds some text to LabwarePreview (the component you see when you mouse over a labware item in the LabwareSelectionModal -- see issue for design
Make sure rogue mode is OFF
When you're adding labware to a module...
When you're adding labware to the deck...
> feat(protocol-designer): add compatibility info to LabwarePreview

- api/src/opentrons/config/pipette_config.py
The logging around the feature flag to use the old bad aspiration functions for
p10 singles was getting extremely chatty in the expected case of using the new
functions. Remove the expected case logs and bump the unexpected case logs down
to debug.
> refactor(api): remove some very chatty logs in pipette config

- api/docs/v2/new_protocol_api.rst
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/geometry.py
If a given protocol would target the labware loaded into a thermocycler module, while that module is known to be closed, simulation will fail with a helpful message.
Closes #4044
Attempt to upload a protocol in which you:
> feat(api): warn tc-lid/gantry collision in simulation

- protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
Add feature flag that enables the selection of GEN2 multi pipettes in the File tab.
Closes #4396
> chore(protocol-designer): expose gen2 multi pipettes behind ff

- app/src/http-api-client/networking.js
pr #4372 (ac74c122e) added the netmask
package (https://www.npmjs.com/package/netmask) to parse the robot's networking
response of CIDR-format ip/subnetbits into a separate ip and subnet mask.
Unfortunately, that PR was building a Netmask object and then using its base
member to represent the IP address. However, a Netmask object only represents
information _about the subnet_, not about a specific ip; the base attribute is
the base address of the subnet, e.g. `ip & subnetmask`.
Instead, split off the CIDR suffix and use the result as the IP address.
Before: 
Note the IP is displayed as 10.10.0.0, the subnet base
After:
Correct IP shown
> fix(app): display robot ip not robot ip subnet base

- api/src/opentrons/deck_calibration/endpoints.py
- shared-data/pipette/definitions/pipetteModelSpecs.json
- shared-data/pipette/definitions/pipetteNameSpecs.json
Our references for the height (and therefore homing position) of the gen2 multi
was not taking into account that gen1 pipettes home to a bearing, not to the top
of their housing; we have to modify the positions a little bit.
Also, the gen2 multis are tall enough that we need to bump the attach-tip
position for deck calibration down a bit to avoid triggering the z endstop.
- deck calibrate in UI and make sure you don't get a hard stop error
- also make sure the positioning is right
- subsequently tip probe and make sure you don't miss by a lot
> fix(api,shared-data): fix gen2 multi positioning

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
All(?) standard OT2 robots set an environmental variable `OT_SMOOTHIE_ID` to "AMA". This is used to match the comports and identify /dev/ttyAMA0. However if this environmental variable is unset (e.g. on a custom install) the assumed value is `FT232R`. I do not see what purpose this serves, and it requires an extra step of setting this environmental variable.
This PR changes that default which should allow graceful handling where OT_SMOOTHIE_ID is unset. I'm not clear of any situation where the current default (FT232R) would be useful and I presume it is vestigial but I may be unaware of a situation in for example old robots.
An alternative would be to raise an exception if this variable is unset but the current behaviour seems to be suboptimal as you get the obscure error:
```
File …
```
> feat(api): Assume OT_SMOOTHIE_ID is AMA if environmental variable is unset.

- app/src/components/FileInfo/index.js
#4381 inadvertently introduced a bug that allowed the legitimate upload error (i.e. error during simulation) warning to never show
This PR fixes that bug so that we can successfully show errors for both simulation errors and empty protocols (which do not fail simulation, but come back from simulation with an empty commands list)
- refactor(app): fix no-steps-in-protocol warning clobbering upload errors
- Labelled as a refactor for changelog purposes because the bug never hit users
> refactor(app): fix no-steps-in-protocol warning clobbering upload errors

- protocol-designer/src/components/StepEditForm/FormAlerts.js
- protocol-designer/src/components/alerts/Alerts.js
- protocol-designer/src/components/alerts/PDAlert.js
- protocol-designer/src/components/alerts/TimelineAlerts.js
- protocol-designer/src/components/alerts/types.js
PD doesn't use the component library Alert component, which is really only for Run App. This PR makes the existing PD-specific alert presentational component more reusable as `PDAlert` instead of being nested inside a fn inside of PD's `Alerts` connected component.
All existing behavior around alerts in PD should be unaffected
- Code review sanity check -- existing behavior should not be changed
> refactor(protocol-designer): factor out PDAlert

- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/components/modules/styles.css
- protocol-designer/src/localization/en/alert.json
This PR closes #4137 by adding updated module placement warning alert banner + dropdown validation error when unrestricted module placement FF is enabled.
- feat(protocol-designer): Add module placement warning and validation
With unrestricted module placement FF OFF:
With unrestricted module placement FF ON:
Misc
> feat(protocol-designer): Add module placement warning and validation

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/file-types.js
- protocol-designer/src/load-file/actions.js
- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-generation/test-with-flow/__snapshots__/fixtureGeneration.test.js.snap
- protocol-designer/src/step-generation/test-with-flow/__snapshots__/utils.test.js.snap
- protocol-designer/src/step-generation/test-with-flow/fixtures/robotStateFixtures.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils.js
- shared-data/protocol/flowTypes/schemaV4.js
- shared-data/protocol/schemas/4.json
Closes #4404 
Sets up placeholder for v4 JSON protocol schema, but doesn't do a PD migration b/c there is no real v4 yet
* adds guard to production PD to not import protocols with modules
* add early draft/placeholder schema for v4 JSON protocols
The most important thing to test is that PD without any preproduction settings enabled still works as-is with no changes
> feat(protocol-designer): save/load protocols with modules in prepro PD

- protocol-designer/src/labware-ingred/utils.js
- protocol-designer/src/step-forms/utils.js
> feat(protocol-designer): fix labware duplication bug

- api/docs/v2/writing.rst
Since p300 is IMO a more intuitive name to use in a protocol.
> docs: fix 'left' = 'right' and change to pipette name instead

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
- protocol-designer/src/components/LabwareSelectionModal/index.js
- protocol-designer/src/localization/en/feature_flags.json
Result of the recent Slack convo -- the "Disable module restrictions" experimental setting is now confined to disabling module placement. Labware<>module compat is enforced no matter what this setting is toggled to.
Closes #4136 (kinda indirectly)
- Update copy for "disable module restrictions" setting
- Shouldn't affect other uses of the setting (slot placement stuff)
> feat(protocol-designer): enforce labware<>module compat

- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/SlotControls.js
Serves as its own ticket. Fixes small UI bug in PD where the "swapping labware not possible" orange warning on top of a labware didn't go away when you dragged over to an empty slot. To reproduce on edge:
1. Add a temperature module in slot 3
2. Put a labware immediately adjacent to that module (eg move the tiprack to slot 2)
3. Click the module and add a compatible labware - let's say a well plate
4. Drag the well plate off the module and over slot 2, the "swapping labware not possible" warning is correctly shown.
5. Without letting go, continue dragging the well plate to an empty slot. The "swapping labware not possible" warning doesn't go away! (You can still drop it into an empty slot though)
- Reproduce the thing above on `edge` sandbox so you know what it looks like
- This bug …
> fix(protocol-designer): fix labware incompat drag warning

- api/src/opentrons/tools/__init__.py
- api/src/opentrons/tools/write_pipette_memory.py
The Shenzhen and hardware teams usually run the utils in api/src/opentrons/tools
from a laptop connected to a smoothie with a serial cable, and the changes to
have the tools.driver object work were gated behind config.IS_ROBOT. Now they
are not.
> fix(api): tools: fix `write_pipette_memory` on host

- api/docs/v2/new_atomic_commands.rst
Note that we no longer try and guess your meaning when calling the functions and
you have to follow normal python argument rules.
Closes #3972
> docs(api): clarify aspirate and dispense optional args

- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/step-generation/utils.js
Closes #4130
Morgan thought it would give users a false sense of security if we show collision errors for slot 1<>4 and 3<>6 situations but not everything. This PR hides the new error if you have module restrictions disabled.
This implementation is hacky but by definition it's only for experimental settings.
> feat(protocol-designer): ignore labware<>module collision error in rogue mode

- api/docs/static/pygments.css
- api/src/opentrons/commands/commands.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/__init__.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/definitions.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/protocol_api/util.py
- api/tests/opentrons/protocol_api/test_context.py
- api/tests/opentrons/protocol_api/test_labware.py
Use the API version specified by the protocol at init to check access to all API functions and methods and make sure the version is appropriate.
- Pass the requested version through to dependent instances of ModuleContext, InstrumentContext, Labware, etc
- Rework the `requires_version` decorator to inject a version check
- See if the code makes sense at all
- Poke holes
- is the error well worded?
- make sure we don't break v1 protocols or v2 protocols
- make a local mod or something and check that it actually works (although the tests should catch it)
> feat(api): check papi version on method call

- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/legacy_wrapper/api.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/modules_wrapper.py
- api/tests/opentrons/protocol_api/test_legacy_labware.py
- api/tests/opentrons/protocol_api/test_legacy_modules.py
Implement backcompat shims for modules. This includes the special case of
loading labware with share=true for loading labware onto modules. Most
functionality is a straight passthrough to the underlying module context, but
some things have special implementations (mostly due to the previous change of
having tempdeck.set_temp also wait until the temperature is reached in v2).
Closes #3655
> feat(api): apiv2: v1-backcompat: implement modules

- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/types.py
- api/tests/opentrons/protocol_api/test_legacy_labware.py
The old Placeable wells had different arguments in  their positioning methods
than the new Wells, and also returned a different thing - a named tuple with
arguments reversed compared to Location, and also with the point encoding an
_offset_ relative to the well origin in the bottom left rather than an absolute
point in deck coordinates.
The new LegacyLocation is meant to encode such an offset pairing (and has the
same ordering as the tuples customarily used in the Pipette and Robot classes),
and the accessors now have the right arguments and return the correct
LegacyLocations, as verified through comparison to v1 outputs.
> feat(api): apiv2: backcompat: implement LegacyWell position methods

- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/tests/opentrons/protocol_api/test_accessor_fn.py
- api/tests/opentrons/protocol_api/test_legacy_labware.py
- api/tests/opentrons/protocol_api/test_offsets.py
The keyword for `sharing` in API v1 could either be used for stacking or sharing scenarios. This PR attempts to cover both use-cases when loading api v1 definitions for 
- Add DeckItem abstract base class
- Add LegacyDeckItem which adds some functionality around determining slot height based off of whether a labware is stacking, sharing or other
- Use LegacyDeckItem whenever you aren't adding a module to the deck
~- Determine whether stacking or sharing based off of the size of the initially added labware.~
Logic seem OK? More tests to add? Anything else?
> refactor(api): Add sharing and stacking for backcompat

- api/src/opentrons/api/calibration.py
"Calibrate to bottom" when enabled prevents tiprack calibration working as described in #4417. This should fix that.
Fixes  #4417.
Prevents calibration to bottom having any effect for tipracks.
Haven't tested this as I don't have a dev environment setup yet, but can confirm things are broken at present and logically this should work.
> fix(APIV2): Make tipracks always calibrate from top

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/SettingsPage/FeatureFlagCard/FeatureFlagCard.js
- protocol-designer/src/localization/en/modal.json
Closes #4129
Credit to @shlokamin for being a code pairing partner! 💻 
- add experimental settings warning modal
For both user-exposed Experimental Settings and for preproduction settings...
- You should be blocked by this modal both when you're toggling ON and when you're toggling OFF a setting (ie, on/off direction doesn't matter).
- Displaying the modal should scroll to the top of the window and lock the scrollbar. This is existing PD funky modal behavior, newly ticketed as #4446
> feat(protocol-designer): add warning when using expt features

- api/src/opentrons/protocol_api/contexts.py
The calibration session currently picks up the simulated context from the beginning of the session.
This means that the simulated modules are also usedduring labware calibration. This temporarily
connect the thermocycler during calibration so the session is aware of the lid's open/close state.
This is a short term patch that will be removed in place of better session management to replace the
current RPC over HTTP session communication.
Please ensure that you are able to proceed to calibrating the labware loaded onto the Thermocycler in these 2 cases (via the run app):
- Your last protocol step is a call to  `thermocycler.open_lid()`
- Your last protocol step is a call to  `thermocycler.close_lid()`
stub protocol:
```
metadata = {"apiLevel": "2.0"}
def run(protocol):
reagents = …
```
> fix(api): connect context to real thermocycler during calibration

- components/src/__tests__/__snapshots__/icons.test.js.snap
- components/src/icons/icon-data.js
- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/forms/MagnetForm.js
- protocol-designer/src/components/StepEditForm/forms/index.js
- protocol-designer/src/components/StepEditForm/index.js
- protocol-designer/src/form-types.js
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/localization/en/tooltip.json
I'm saying addresses #4303 since the issue has WIP and Design tags. (This could potentially close it if design stays as is)
This PR:
- Adds module icons to components library
- Updates StepCreationButton to contain module steps (Only magnet is wired)
- Adds MagnetForm
This PR does NOT:
- Generate the step data on save
- Disable the module steps based on InitialDeckSetup
> feat(protocol-designer): Add magnet step UI

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
@TaylorGoodman was able to reproduce a bug in which cancelling a protocol run during a thermocycler hold led to the api server hanging. This manifested itself as an unresettable protoco, which needed to be power cycled.  
This adds cancel support for the ongoing long running tasks created by the Temperature Module and the Thermocycler Module. 
- Cancelling a run while a Temperature Module is heating to temp should be recoverable 
- Cancelling a run while a Thermocycler Module is heating to temp should be recoverable
- Cancelling a run while a Thermocycler Module is holding at temp should be recoverable
> fix(api): clear running module tasks on cancel

- api/src/opentrons/api/session.py
- api/src/opentrons/commands/commands.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/legacy_wrapper/__init__.py
- api/src/opentrons/protocol_api/legacy_wrapper/api.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/instrument_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/modules_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/robot_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/types.py
- api/src/opentrons/util/entrypoint_util.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/data/multi-single.py
- api/tests/opentrons/data/testosaur.py
- api/tests/opentrons/integration/test_api.py
- api/tests/opentrons/protocol_api/test_back_compat.py
- api/tests/opentrons/protocol_api/test_instrument_wrapper.py
This is the PR for adding full backwards compatibility for instrument methods (aka just about everything) to APIv2. it is still under development but there is enough basic functionality read to begin testing.
- aspirate (all argument forms)
- dispense (all argument forms)
- pick up tip (all argument forms including tipracks specified in instrument constructor)
- drop tip (all argument forms)
- tempdeck and magdeck arguments and labware loading
> feat(api): apiv2: implement instruments backcompat

- __mocks__/electron.js
- app-shell/src/labware/__tests__/dispatch.test.js
- app-shell/src/labware/index.js
- app-shell/src/main.js
- app/src/components/AddLabwareCard/ChangePathButton.js
- app/src/components/AddLabwareCard/PathDetail.js
- app/src/components/AddLabwareCard/__tests__/AddLabwareCard.test.js
- app/src/components/AddLabwareCard/__tests__/ChangePathButton.test.js
- app/src/components/AddLabwareCard/__tests__/PathDetail.test.js
- app/src/components/AddLabwareCard/__tests__/__snapshots__/AddLabwareCard.test.js.snap
- app/src/components/AddLabwareCard/__tests__/__snapshots__/ChangePathButton.test.js.snap
- app/src/components/AddLabwareCard/__tests__/__snapshots__/PathDetail.test.js.snap
- app/src/components/AddLabwareCard/index.js
- app/src/components/AddLabwareCard/styles.css
- app/src/components/ListLabwareCard/__tests__/ListLabwareCard.test.js
- app/src/components/ListLabwareCard/index.js
- app/src/custom-labware/__tests__/actions.test.js
- app/src/custom-labware/actions.js
- app/src/custom-labware/index.js
- app/src/custom-labware/types.js
- app/src/pages/More/CustomLabware.js
This PR adds UI and a selection dialog to set the user's custom labware directory. Closes #4246.
- refactor(app): add dialog to change custom labware directory
The location of the custom labware directory was already stored in config as of #4268. Now:
- Clicking "Change Source" dispatches a `labware:CHANGE_CUSTOM_LABWARE_DIRECTORY` action that gets sent to the main process via `meta.shell: true`
- Main process catches that action and opens a directory selection dialog via `electron::dialog.showOpenDialog`
- Once the user selects a directory, a `config:UPDATE` action is dispatched to update the labware directory entry
- Changes to the labware directory entry in config trigger a refresh of the labware list
Reference screen: https://zpl.io/bo6RmzW (option 3)
Note: The ticket mentions that …
> refactor(app): add dialog to change custom labware directory

- components/src/modals/AlertModal.js
- protocol-designer/src/components/DeckSetup/DeckSetup.css
- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/Hints/hints.css
- protocol-designer/src/components/Hints/index.js
- protocol-designer/src/components/modals/EditPipettesModal/StepChangesConfirmModal.js
- protocol-designer/src/localization/en/alert.json
- protocol-designer/src/localization/en/deck.json
- protocol-designer/src/navigation/actions.js
- protocol-designer/src/tutorial/index.js
- protocol-designer/src/tutorial/reducers.js
closes #4328
* make AlertModal props exact
* allow Hints to be alert or plain
* remove "Tell the robot where labware and liquids start on the deck" text
> feat(protocol-designer): move deck setup guidance to hint modal

- api/src/opentrons/__init__.py
This is necessary for jupyter compatibility
> refactor(api): add robot globals in backcompat mode

- api/src/opentrons/api/session.py
- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/execute.py
- api/src/opentrons/legacy_api/protocols/execute_v3.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/integration/test_api.py
- api/tests/opentrons/server/test_settings_endpoints.py
- api/tests/opentrons/test_simulate.py
This removes the back compat feature flag and makes v1 backcompat available by
default in the v2 internals. You can also now select an internals version in the
opentrons_simulate and opentrons_execute scripts.
> feat(api): surface protocol apiv1 backcompat in apiv2

- app/src/components/RunLog/ConfirmCancelModal.js
Following @sfoster1 's comments on #4464. This adds clarifying copy to the cancel modal that better forecasts how your modules will behave.
> refactor(app): clarify module behavior in cancel modal

- api/Makefile
- api/docs/v2/new_advanced_running.rst
- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/tools/__init__.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_settings_endpoints.py
- api/tests/opentrons/tools/test_qc_scripts.py
This removes the apiv2 feature flag in favor of a new flag, useLegacyInternals,
with the opposite sense: enable to use the v1 internals (default off).
Closes #2187
> feat(api): enable v2 internals by default

- api/src/opentrons/protocol_api/legacy_wrapper/api.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/tests/opentrons/protocol_api/test_legacy_migration.py
Since we're going to spend a while with the ability to switch back and forth
between v1 and v2, we should make the v1->v2 labware migration not delete the
labware database when it's done. Instead, we just skip any labware we've already
migrated.
This also means we don't have to gate this functionality behind an environment
variable anymore and we can just do it all the time (even if we're on v1
internals).
> refactor(api): make labware migration non-destructive

- api/src/opentrons/protocol_api/contexts.py
Previously we only raised an  exception if the lid was 'closed', now we'll catch the edge case where the lid is partially open, but still unsafe to pipette to or from.
Behavior identified by @ChrisYarka 
- manually close a TC lid part way before a run, and then attempt to pipette from it, an exception should be raised
> fix(api): flag move to tc with in-between lid as unsafe

- api/src/opentrons/api/calibration.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/labware.py
- api/src/opentrons/protocol_api/legacy_wrapper/containers_wrapper.py
- api/src/opentrons/protocol_api/legacy_wrapper/instrument_wrapper.py
- api/tests/opentrons/protocol_api/test_instrument_wrapper.py
- api/tests/opentrons/protocol_api/test_legacy_labware.py
There were a couple different issues with pre-protocol labware calibration for the backcompat shim (even on top of getting locations correctly):
- We need to use the underlying context's hardware _manager_ rather than its hardware instance so we can take advantage of the calibration manager connecting to actual hardware (otherwise we won't move anywhere)
- We need to patch the underlying labware object's well builder to build legacy wells or a lot of the advanced constructors will return labware.Well, which doesn't work with the back compat wrapper motion control
- We need to home plungers at some point before calibration. This may actually be a v2 bug in general, it was causing hard stop errors the first time you go to pick up a tip after boot in calibration
- For some reason we were …
> fix(api): fix calibration issues in backcompat

- app-shell/src/labware/__tests__/definitions.test.js
- app-shell/src/labware/__tests__/dispatch.test.js
- app-shell/src/labware/__tests__/validation.test.js
- app-shell/src/labware/definitions.js
- app-shell/src/labware/index.js
- app-shell/src/labware/validation.js
- app/src/custom-labware/__tests__/actions.test.js
- app/src/custom-labware/__tests__/reducer.test.js
- app/src/custom-labware/__tests__/selectors.test.js
- app/src/custom-labware/actions.js
- app/src/custom-labware/reducer.js
- app/src/custom-labware/types.js
Continuing work on #4247. This PR follows up on #4475 by wiring the "Add Labware" button to a file picker and a copy action.
- Valid files will be copied into the labware directory and shown in the list
- Invalid / duplicate files reported into state, but no error UI is wired to that state yet
- Unexpected filesystem errors are not yet caught
- refactor(app): wire up Add Labware button without error handling
With the "Custom Labware" feature flag enabled in the app, navigate to "More" > "Custom Labware"
- Dialog is a single-file picker
- Dialog is limited to JSON files
If you are in need of valid custom labware files, either create one with labware creator, or:
- Grab any labware file from `shared-data/labware/definitions/2/`
- Open it up and change its `namespace` field to something …
> refactor(app): wire up Add Labware button without error handling

- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/components/listButtons.css
- protocol-designer/src/localization/en/application.json
- protocol-designer/src/localization/en/tooltip.json
- protocol-designer/src/step-forms/utils.js
This PR closes #4456 by disabling step creation button when modules required for step are not present on the deck. It also updates ALL step creation button tooltip text.
- chore: Add `isModuleOnDeck` util
- feat(protocol-designer): Disable module step creation when module missing
http://sandbox.designer.opentrons.com/pd_disable-module-steps/ (currently building... not up to date yet)
- Transfer:  Move liquid to and from wells/tubes.
- Mix: Mix contents of wells/tubes.
- Pause: Enable pause within protocol.
- Temperature: Set temperature command for Temperature and Thermocycler modules.
- Magnet: Engage or disengage the Magnetic module.
- Thermocycler Profile: Program a profile for the Thermocycler module.
> feat(protocol-designer): Disable module step creation when module missing

- api/src/opentrons/config/advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
Keep around the useProtocolApi2 and enableApi1BackCompat feature flags if they are present so downgrades don't end with the server crashing afterwards. 
You should also now be able to delete things from the feature flags file and the server will be able to start up (it will crash when you edit it at the same time that it's running, though).
> fix(api): fix bad adv settings crash

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/forms/MagnetForm.js
- protocol-designer/src/constants.js
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/steplist/fieldLevel/errors.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/fieldLevel/processing.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/getDisabledFields/index.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMagnet.js
- protocol-designer/src/steplist/formLevel/handleFormChange/index.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
This PR closes #4300 by adding form and field level validation. Addresses #4303 by changing the magnetAction field from a dropdown to a radio group.
- feat(protocol-designer): Add magnet step form field validation. It also updates magnet action field to be a radio group instead of a dropdown. Punting on labware selection until ticket is finalized. 
http://sandbox.designer.opentrons.com/pd_magnet-form-field-validation/ (currently building... not up to date yet)
> feat(protocol-designer): Add magnet step form field validation

- __mocks__/electron.js
- app-shell/src/dialogs/__tests__/dialogs.test.js
- app-shell/src/dialogs/index.js
- app-shell/src/labware/__tests__/definitions.test.js
- app-shell/src/labware/__tests__/dispatch.test.js
- app-shell/src/labware/__tests__/validation.test.js
- app-shell/src/labware/compare.js
- app-shell/src/labware/definitions.js
- app-shell/src/labware/index.js
- app-shell/src/labware/validation.js
- app/src/components/AddLabwareCard/AddLabwareFailureModal.js
- app/src/components/AddLabwareCard/__tests__/AddLabwareCard.test.js
- app/src/components/AddLabwareCard/__tests__/AddLabwareFailureModal.test.js
- app/src/components/AddLabwareCard/__tests__/__snapshots__/AddLabwareFailureModal.test.js.snap
- app/src/components/AddLabwareCard/index.js
- app/src/components/AddLabwareCard/styles.css
- app/src/custom-labware/__fixtures__/index.js
- app/src/custom-labware/__tests__/actions.test.js
- app/src/custom-labware/__tests__/reducer.test.js
- app/src/custom-labware/__tests__/selectors.test.js
- app/src/custom-labware/actions.js
- app/src/custom-labware/reducer.js
- app/src/custom-labware/selectors.js
- app/src/custom-labware/types.js
- components/src/styles/typography.css
Closes #4247 
This PR follows up on #4475 and #4487 by adding "Add Labware" error handling to the UI, including allowing the user to overwrite existing labware with a newer duplicate.
- refactor(app): handle "Add Labware" errors and allow overwrites
With the "Custom Labware" feature flag enabled in the app, navigate to "More" > "Custom Labware"
In lieu of a test plan in this PR, please follow the acceptance criteria in #4247
If you are in need of valid custom labware files, either create one with labware creator, or:
- Grab any labware file from `shared-data/labware/definitions/2/`
- Open it up and change its `namespace` field to something other than `opentrons`
If you need an invalid custom labware file, use:
- Any standard Opentrons labware
- Any JSON file that isn't labware
- Any JSON …
> refactor(app): handle "Add Labware" errors and allow overwrites

- app-shell/README.md
- app-shell/package.json
- app-shell/src/config.js
- app-shell/src/log.js
- app-shell/src/main.js
- app-shell/src/menu.js
- app-shell/src/robot-logs.js
- app/src/config/types.js
- yarn.lock
- Separated context menu setup from devtools extensions install
- Previously, the "Inspect Element" right click could be broken if devtools failed to install
- Added `--reinstallDevtools` option to force a devtools reinstall if they're not loading for some reason
- Side-effect: standard context menu options like "Copy" and "Paste" are now available
- Added Help menu entry for opening app's log folder
- Previously, app's logs were hard to get to
- Restored "Save As..." functionality for robot logs
- Transparent log saving was inconvenient and confusing for users
- Fixes #4293
- fix(app-shell): improve context menu and log handling
Caution: robot logs take a _long_ time to download. This is an API side thing
- This is easiest to see if you haven't got the new React Profiler extension …
> fix(app-shell): improve context menu and log handling

- api/src/opentrons/api/session.py
- api/src/opentrons/server/serialize.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/server/test_server.py
This lets the run app provide all the custom labware it knows about to an
unbundled protocol execution without having to also provide all the standard
labware it knows about.
There are new session.create methods for bundles and custom labware,
specifically create_from_bundle and create_with_extra_labware:
create_from_bundle(name, contents)
create_with_extra_labware(name, contents, extra_labware)
These operate the same way as session.create. In the bundle case, it is the same
as calling create with binary=True. In the create_with_extra_labware case,
extra_labware should be a list of labware definitions as dicts (aka serialized
directly as json). You can probably call create_with_extra_labware with a json
protocol but it won't do anything different than create.
These new functions are …
> feat(api): add extra labware in session

- app-shell/src/labware/__tests__/dispatch.test.js
- app-shell/src/labware/index.js
- app-shell/src/main.js
- app/src/protocol/protocol-data.js
- app/src/robot/actions.js
- app/src/robot/api-client/__tests__/create-sessions.test.js
- app/src/robot/api-client/client.js
- app/src/robot/reducer/session.js
- app/src/robot/selectors.js
- app/src/robot/test/actions.test.js
- app/src/robot/test/api-client.test.js
- app/src/robot/test/selectors.test.js
- app/src/robot/test/session-reducer.test.js
- app/src/rpc/remote-error.js
- app/src/shell/update.js
This PR refactors how the RPC API client calls `session_manager.create` in order to:
- Support using custom labware in Python protocols (see #4490)
- Fix #4202 for real this time
- Call the correct `session_manager.create...` method depending on the protocol and what methods the remote `session_manager` has available
- If ZIP, call `session_manager.create_from_bundle` if available, else `create(..., true)`
- If Python, call `create_with_extra_labware` or `create` depending on if the user has custom labware or not
- Else, call `create`
With the app's "Custom Labware" feature flag enabled:
1. Add a custom labware to the app
2. Upload a Python protocol using that labware to a robot with #4490 installed
> fix(app): Call correct create method depending on protocol

- app/src/components/UploadPanel/UploadMenu.js
- app/src/pages/Upload/FileInfo.js
- app/src/pages/Upload/index.js
- app/src/robot/reducer/session.js
- app/src/robot/test/session-reducer.test.js
If the user has custom labware present in the app, and they navigate to the protocol upload page, a warning will display if the robot hasn't yet been updated to the version needed to support custom labware in Python protocols
- refactor(app): add warning if robot doesn't support custom labware
Ensure your app's "Custom Labware" feature flag is enabled
**Empty folder**
**Folder has labware, robot has support**
**Folder has labware, robot does not have support**
> refactor(app): add warning if robot doesn't support custom labware

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/util/vector.py
@rgatkinson reported in #4482 that per their investigations, APIv1 protocol
simulation (and thus execution) spends an inordinate amount of time in
numpy.isclose - around 13%. They noted that numpy.isclose is intended to be
dynamic across many sizes of array, and the main place that we use it (in the
smoothie driver to elide motion axes that haven't changed their coordinates)
compares scalars.
This fix uses math.isclose, which compares only scalars, in place of
numpy.isclose. It uses math.isclose instead of @rgatkinson's handwritten version
for maintainability and just in case of any odd bugs around floating point
handling. Also, math.isclose is not that much slower than the handrolled:
```
>>> timeit.timeit(lambda: valid_movement(10, 'X'), number=10000)
0.22610970796085894
>>> …
```
> perf(api): use math.isclose in hotpaths

- api/src/opentrons/hardware_control/__init__.py
Expands docstring to explain how tip pick-up works in hardware terms.
Resolves #4433 (for now).
> docs: Document pick_up_tip hardware procedure

- api/src/opentrons/commands/commands.py
- api/tests/opentrons/labware/test_pipette_unittest.py
- api/tests/opentrons/test_simulate.py
This PR fixes some inconsistency in the command publisher.
For a quick example:
```
Picking up tip A1 of Opentrons 96 Tip Rack 10 µL on 1
Aspirating 1 uL from A2 of Opentrons 24 Tube Rack with NEST 1.5 mL Snapcap on 6 at 1.0 speed
Dispensing 1.0 uL into A1 of NEST 96 Well Plate 100 µL PCR Full Skirt on Thermocycler Module on 7
Blowing out at A1 of NEST 96 Well Plate 100 µL PCR Full Skirt on Thermocycler Module on 7
Dropping tip A1 of Opentrons Fixed Trash on 12
```
- volume can be both an `int` and a `float`
- the aspirate speed is stated but not the dispense speed
- update the volume type for all liquid handling commands
- publish dispense speed
- rename `magnetic deck module` to `Magnetic Module`
- rename `temperature deck module` to `Temperature Module`
- round all Thermocycler …
> refactor(api): clean up command publisher

- api/src/opentrons/drivers/mag_deck/driver.py
- api/src/opentrons/drivers/temp_deck/driver.py
- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/hardware_control/modules/magdeck.py
- api/src/opentrons/hardware_control/modules/tempdeck.py
- api/src/opentrons/legacy_api/modules/magdeck.py
- api/src/opentrons/legacy_api/modules/tempdeck.py
- api/tests/opentrons/config/test_pipette_config.py
- api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py
- api/tests/opentrons/labware/test_modules.py
Add locks on both the temperature and magnetic modules to prevent multi-access to data from the hardware.
**Test Plan**
1. Ensure you can still set/deactivate temperature in the app
2. Run an API v1 protocol with a tempdeck and set temp low (maybe 5C) so that you can cancel before the temperature reaches the target. You should still be able to deactivate the temperature module after in the app, and then set temp again in the app.
3. Repeat #2 with an API v2 protocol.
4. With a magnetic module, ensure that you can plug/unplug and have the robot continue to be able to recognize it.
5. Use a magnetic module in a v1 and v2 protocol
> feat(api): Add locks on direct data access for mag and temp module

- shared-data/pipette/definitions/pipetteModelSpecs.json
Previously, the defaults of the plunger current and drop tip current of the following pipettes exceed their maxes. 
- `p300_single_v2.0`
- `p300_single_v2.1`
- `p1000_single_v2.0`
- `p1000_sinlge_v2.1`
This PR fixes them by setting the maxes to be the same as the defaults.
> fix(shared-data): increase GEN2 pipette plunger & drop tip current

- api/src/opentrons/deck_calibration/endpoints.py
- api/tests/opentrons/labware/test_pipette.py
- api/tests/opentrons/robot/test_robot.py
- api/tests/opentrons/server/test_calibration_endpoints.py
The http deck calibration would back up the most recent gantry calibration, rather than the one it had started with. While I was trying to figure this out, I also noticed that critical points were not being handled correctly for API v2 which resulted in a z difference for gen2 pipettes.
- Backup the config at the beginning of a session
- Modify how we handle critical points for positioning.
1. Run a deck calibration with a gen2 pipette, see that the Z value is reasonable
2. Run a deck calibration with a gen1 multi pipette and see that the config values are reasonable
3. Check the most recently backed up file to ensure that it is different from the current `deck_calibration.json`
> fix(api): Fix critical points and gantry config backup in http deck cal

- api/src/opentrons/hardware_control/__init__.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/tests/opentrons/hardware_control/test_instruments.py
- api/tests/opentrons/protocol_api/test_context.py
Prevent liquid handling actions (aspirate/dispense) if the pipette does not have a tip. Fixes #4219 
Example protocol (the basic protocol from the v2 docs) with the pick_up_tip call commented out:
```
from opentrons import protocol_api
metadata = {
'protocolName': 'My Protocol',
'author': 'Name <email@address.com>',
'description': 'Simple protocol to get started using OT2',
'apiLevel': '2.0'
}
def run(protocol: protocol_api.ProtocolContext):
plate = protocol.load_labware('corning_96_wellplate_360ul_flat', '2')
tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', '1')
left_pipette = protocol.load_instrument(
'p300_single', 'left', tip_racks=[tiprack])
left_pipette.aspirate(100, plate['A1'])
left_pipette.dispense(100, plate['B2'])
left_pipette.drop_tip()
```
> fix(api): prevent liquid handling without a tip

- app-shell/src/main.js
- app/src/components/MenuPanel/index.js
- app/src/config/index.js
- app/src/config/types.js
- app/src/pages/More/Resources.js
- app/src/pages/More/index.js
This PR removes the `customLabware` feature flag to enable the custom labware management feature by default
- feat(app): enable custom labware management in the app
0. Open your app's config file and remove the `devInternal.customLabware` setting if it exists
1. Open the app
2. Navigate to "More"
> feat(app): enable custom labware management in the app

- api/src/opentrons/api/models.py
- api/src/opentrons/protocol_api/labware.py
- app/src/robot/api-client/client.js
Prior to this PR,
- The app determined that a given RPC labware is a tiprack by running a regex for `/tiprack/i` against the `type` field of the RPC `Container`
- `Container.type` was set to the `name` of the v2 `Labware` class
- `Labware.name` was always set to the load name of the labware
#4452 introduced a change that set `Labware.name` to the passed-in `label` parameter of the labware if it was used. This broke tiprack detection in the client anytime label was set to a string that didn't contain the exact case-insensitive string "tiprack".
The Protocol Designer always passes in the display name of the labware as label by default, which means tiprack detection was automatically broken for all PD protocols.
This PR adds a new getter method to `Labware` for `load_name`, which is now used …
> fix(rpc): ensure load name is attached to RPC "containers"

- api/src/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
- shared-data/protocol/fixtures/3/unusedPipette.json
We've had a consistent issue in the session management around protocols that the
required instruments, modules, and labware are all pulled from scraping the
commands emitted by the protocol. That means if you load a pipette, instrument,
or module (which does not emit a command notification) but never use it (which
does), it never gets added to the requisite rpc-exposed property and thus
the app doesn't let you calibrate or indicate that you should attach the
pipette.
In V1, this was acceptable because as a byproduct of the way v1 worked, when you
ran the protocol it would create a handler for that pipette or module with no
issue.
In V2 (and also now when interpreting JSON protocols, since that uses V2) this
isn't true - we're much more strict about only allowing Contexts for the
hardware …
> fix(api): present loaded but unused pipettes and modules to rpc

- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
This PR categorized as a refactor because it finishes something that was missed in #4477 but not yet released.
In the context of the `edge` branch, it fixes a regression where purposeful user-initiated restarts of the robot cause spurious "robot has unexpectedly disconnected" warnings due to the RPC client not properly catching restart trigger actions
- refactor(app): ensure RPC API client uses correct restart action shape
1. Connect to a robot via the "Connect" button or connect toggle
2. Click "Restart" or trigger a factory reset
> refactor(app): ensure RPC API client uses correct restart action shape

- api/src/opentrons/protocol_api/labware.py
Okaayyy, let's try it again. Somehow deleted my change with the onto target rebase and thus closed my other PR...
Fixing up the labware load error message to be more descriptive for new 'custom labware upload' users. As per this message from design:
```
FileNotFoundError [Line 16]: Unable to find a labware definition for "custom_12_wellplate_6900ul", version 1, in the Opentrons namespace. Please confirm your protocol includes the correct labware spelling and (optionally) the correct version number and namespace.
If you are referencing a custom labware in your protocol, you must add it to your Custom Labware Definitions Folder from the Opentrons App before uploading your protocol.
```
> refactor(api): Modify the labware load error message

- app-shell/src/labware/__tests__/dispatch.test.js
- app-shell/src/labware/index.js
- app/src/analytics/__tests__/custom-labware-events.test.js
- app/src/analytics/__tests__/epics.test.js
- app/src/analytics/__tests__/make-event.test.js
- app/src/analytics/epics.js
- app/src/analytics/make-event.js
- app/src/analytics/mixpanel.js
- app/src/analytics/types.js
- app/src/components/AddLabwareCard/index.js
- app/src/components/layout/CardCopy.js
- app/src/components/layout/index.js
- app/src/components/layout/styles.css
- app/src/custom-labware/__tests__/actions.test.js
- app/src/custom-labware/__tests__/reducer.test.js
- app/src/custom-labware/actions.js
- app/src/custom-labware/types.js
This PR adds analytics events for various custom labware actions. Closes #4537 
- feat(app): add simple agregate event tracking for custom labware
Pretty well covered by unit tests, but if you feel so inclined:
1. Set `MIXPANEL_ID` to our test application ID
2. Do various custom labware stuff
3. Observe actions
See original ticket for link to events specs
> feat(app): add simple aggregate event tracking for custom labware

- shared-data/js/getLabware.js
- shared-data/js/helpers/index.js
This PR marks the Eppendorf EPTips definitions as "Retired" in PD and removes them from the Labware Library. Closes #4518, see ticket for additional details and removal reasoning
- fix(labware): "retire" eppendorf tiprack definitions
- <http://sandbox.labware.opentrons.com/labware_remove-eppendorf-tipracks>
- <http://sandbox.designer.opentrons.com/labware_remove-eppendorf-tipracks>
> fix(labware): "retire" eppendorf tiprack definitions

- api/src/opentrons/server/endpoints/settings.py
When we made the v2 feature flag "always on", we stopped resetting key v1 values
in factory reset. Reenable them.
- Reset labware calibration and make sure the database is removed and rebuilt
- Reset tip probe and make sure both the tip length dicts and instrument offset dicts are removed
> fix(api): always do equivalent v1 factory resets

- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
I fixed the ability for _single channel_ pipettes to transfer using location types in #4276 but never actually checked multi-channels for this behavior. While @ncdiehl11 was trying to simulate a protocol, we discovered that this behavior was not fixed for multi-channels.
- Add multichannel transfer test (should have done that before..)
- Fix assertion for multichannel transfers so it won't fail on Locations
Test on a robot with this protocol:
```
import math
metadata = {
'protocolName': 'Custom Chip PCR Preparation',
'author': 'Nick <protocols@opentrons.com>',
'source': 'Custom Protocol Request',
'apiLevel': '2.0'
}
def run(ctx):
num_samples, p10_mount, p50_mount = [24, 'right', 'left']
if num_samples > 24:
raise Exception("24 sample membranes maximum on chip.")
if p10_mount == p50_mount: …
```
> fix(api): Allow Location types for multichannels in transfer

- api/src/opentrons/legacy_api/modules/magdeck.py
This lets you query the magdeck status when simulating.
Write a v1 protocol that querys `magdeck.status`. It will crash without this pr.
> fix(api): shadow the magdeck height in v1

- api/src/opentrons/protocol_api/contexts.py
This PR is pulling double duty as a bug report
In return tip, labware return tip was being called explicitly even though it was called implicitly
under drop_tip
This shouldn't change anything behaviorally but removes unnecessary error message
> fix(api): remove unnecessary tip return

- api/src/opentrons/drivers/serial_communication.py
- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
- api/src/opentrons/server/endpoints/control.py
- api/tests/opentrons/drivers/test_driver.py
After a recent refactor the smoothie driver has a short timeout for sending
commands to be acked and a longer timeout after sending an M400 to wait for the
command to execute. This works for most long-running commands like move, but
some commands - specifically G28.2, home - are executed before they ack rather
than being queued, and can take a long time. That means that if the gantry is in
the front left of the robot, as far as it can be from home, the x home will
frequently hit its short ack timeout and retry, which leads to two successive x
homes. This can also happen with plunger homes, especially on gen2 pipettes,
when the plunger is at the bottom.
Testing:
- Run a long protocol with a lot of motion and make sure there aren't any smoothie errors.
> fix(api): fix homing timeouts

- api/docs/v1/api.rst
Remove `get_protocol_api` and `bundle_from_sim` from API Reference section in APIv1 docs.
Make sure they do not show up here:
http://sandbox.docs.opentrons.com/docs_remove-v2-in-v1-docs/v1/api.html
> docs(api): remove protocolContext references from PAPIv1 docs

- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/server/test_settings_endpoints.py
When fusing v1 and v2, we accidentally stopped exposing v1 settings resets. When exposing them again, we bundled them with the v2 options. Those options now need to have their copy updated to indicate the changes.
Closes #4568
> fix(api): update settings reset copy to avoid confusion

- api/Makefile
When I tried to test #4574, I experienced some weird issues that came about from jupyter not being restarted on an API update.
This is a small feature to add that ability when someone calls `make push-api`.
> feat(api): Restart jupyter with an api push

- api/docs/v2/new_advanced_running.rst
- api/src/opentrons/config/__init__.py
- api/src/opentrons/execute.py
- api/src/opentrons/protocols/parse.py
- api/src/opentrons/simulate.py
- api/src/opentrons/util/entrypoint_util.py
- api/tests/opentrons/data/python_v2_custom_lw.py
- api/tests/opentrons/protocols/test_parse.py
- api/tests/opentrons/test_execute.py
- api/tests/opentrons/test_simulate.py
Previously, extra_labware (the mechanism for v2 custom labware) wasn't really
handled in the script entrypoints opentrons_execute and opentrons_simulate. This
adds that handling. Specifically,
- opentrons_execute learned -L, which lets you specify paths to search for
labware definitions (previously only known by opentrons_simulate for building
bundles). This defaults to '.', as in opentrons_simulate
- opentrons.{simulate,execute}.get_protocol_api learned the extra_labware
argument, which should be a dict mapping labware names to labware definitions.
If this is not specified (as in, not as an empty dict), if this is a robot the
software will look in /var/lib/jupyter/notebooks/labware for custom labware.
- Add the jupyter lookup thing to docs. This is the canonical "right place" to
put …
> feat(api): Handle extra labware in script entrypoints

- api/docs/ot1/_static/banners.css
- api/docs/ot1/api.html
- api/docs/ot1/calibration.html
- api/docs/ot1/containers.html
- api/docs/ot1/examples.html
- api/docs/ot1/firmware.html
- api/docs/ot1/genindex.html
- api/docs/ot1/index.html
- api/docs/ot1/modules.html
- api/docs/ot1/pipettes.html
- api/docs/ot1/py-modindex.html
- api/docs/ot1/robot.html
- api/docs/ot1/search.html
- api/docs/ot1/transfer.html
- api/docs/ot1/writing.html
This lets you know that you're in the ot1 docs. Great!
It's the same style as the v1/v2 redirect banners.
Closes #4403
> chore(docs): put a banner in ot1 docs

- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/labware/test_pipette_unittest.py
- api/tests/opentrons/protocol_api/test_context.py
If you pass an air_gap larger than the pipette's working volume to any complex
command, in either v1 or v2, you get an infinite loop because it's subtracted
from the pipette's max volume to figure out how much can be aspirated in any
given transfer step.
Limit air_gap to between 0 and the pipette's expected working volume in transfer
and friends.
Closes #364
> fix(api): limit air_gap in transfer to <max volume

- api/src/opentrons/main.py
- api/tests/opentrons/test_main.py
That is the standard path for runtime-loaded firmware for attached hardware in
linux. It's a better way to update the smoothie than packing it in the api
wheel. In the future, we may even want to use a separate systemd task to update
the smoothie. Requires https://github.com/Opentrons/buildroot/pull/57
- Make sure that if you change the name of the file in `/usr/lib/firmware` on the robot, the api server detects it as the right smoothie firmware to use and does an update on boot.
> refactor(api): look for smoothie firmware in /usr/lib/firmware

- api/docs/v1/complex_commands.rst
- api/docs/v2/new_complex_commands.rst
We had a errant `new_tip='single'` in the API example docs. This PR fixes that line to use the correct `new_tip='once'`.
This PR also adds a `new_tip='once'` section to the PAPIv1 docs to close #357
- docs(api): fix transfer example to use new_tip='once'
- Did I miss any other places where this sort of typo slipped in?
> docs(api): fix transfer example to use new_tip='once'

- api/src/opentrons/api/session.py
- api/tests/opentrons/api/test_session.py
If you have a robot.connect() in your protocol, and upload it through the
opentrons app, then the robot will move and execute the commands in the protocol
during simulation. It will also behave badly when run. Make the protocol raise
an error if it calls robot.connect when run through the rpc session.
Closes #4252
This pokes around at global state in the session and thus makes me a little nervous. We should make sure that
1. If you upload a protocol that calls robot.connect(), you get the new error
2. If you then upload another v1 protocol, that actually executes
3. If you upload a protocol that does _not_ call robot.connect(), everything works as normal.
> fix(api): do not allow robot.connect() in rpc protocols

- api/src/opentrons/legacy_api/instruments/pipette.py
- api/tests/opentrons/labware/test_pipette_unittest.py
Touch tip in APIv1 moves to the +X direction to touch the first side of the well before moving up to the desired height. This causes collisions with any labware with v-shaped wells, and can potentially dislocate tube racks by dragging the upwards (see behavior [here](https://drive.google.com/file/d/1hSRdIlICRC9edA2o0Bwjdsvk37xzf33v/view?usp=sharing))
This PR fixes this issue by moving the pipette to the correct Z height for touch tip before moving in the XY directions, mimicking the touch tip behavior in APIv2. 
Closes #2712 & closes #3599
Already tested on 🍀 but feel free to verify the behavior.
Can this fix possibly break anything?
> fix(api): apiv1: move instrument in Z-axis prior to touch tip in XY

- api/src/opentrons/drivers/rpi_drivers/gpio.py
A number of pins need to be set at power-on before the robot can work correctly. Previously some of these were defined only in the [ot-blinkenlights](https://github.com/Opentrons/buildroot/blob/opentrons-develop/board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights) script in the buildroot repo. This was confusing to newcomers: in some sense it was the only logic needed for the robot to pipette not to be found in the opentrons repo. This PR places that logic in a new function, `robot_startup_sequence` in `gpio` which can then be invoked from `ot-blinkenlights`. 
In #4397, @sfoster1 said there might be issues about ensuring this is only run once. I can't think of a nice way to achieve this that would work even if the modules were re-imported in a new Python process. But I think that …
> chore: refactor startup sequence logic from blinkenlights to API

- app/src/components/CalibratePanel/PipetteList.js
- app/src/components/CalibratePanel/PipetteListItem.js
- app/src/components/calibrate-pipettes/PipetteTabs.js
- app/src/components/calibrate-pipettes/Pipettes.js
- app/src/nav/__tests__/calibrate-selectors.test.js
- app/src/nav/calibrate-selectors.js
- app/src/nav/index.js
- app/src/nav/types.js
- app/src/pages/Calibrate/Pipettes.js
- app/src/pages/Calibrate/index.js
- app/src/pipettes/constants.js
- app/src/pipettes/selectors.js
- app/src/robot/api-client/client.js
- app/src/robot/selectors.js
- app/src/robot/test/api-client.test.js
- app/src/robot/types.js
- components/src/lists/ListItem.js
This PR disables tip-probe calibration for pipettes that are "unused" in a given protocol. "unused" is taken to mean "RPC reports this pipette interacts with 0 tip racks"
Closes #4570
- fix(app): disable tip probe for unused pipettes
- Also removed the no-longer-used alert banner on the /calibrate/pipettes page that now never shows up because you're not allowed to proceed to calibration if your pipettes don't match
> fix(app): disable tip probe for unused pipettes

- api/src/opentrons/legacy_api/instruments/pipette.py
When transfers emit a touch_tip in v1, they just pass the keyword arg value as
the first positional parameter. It is, however, a number, and interpreted as a
voffset by touch_tip; but it also emits a warning, which you can see if you're
simulating. Just pass it as the v_offset keyword arg.
No behavior change other than the warning going away is expected here.
Closes #3703
> fix(api): specify v_offset in transfer touch_tip

- app/src/epic.js
- app/src/modules/__fixtures__/index.js
- app/src/modules/__tests__/actions.test.js
- app/src/modules/__tests__/reducer.test.js
- app/src/modules/__tests__/selectors.test.js
- app/src/modules/actions.js
- app/src/modules/constants.js
- app/src/modules/epic/__tests__/fetchModulesEpic.test.js
- app/src/modules/epic/__tests__/pollModulesWhileConnectedEpic.test.js
- app/src/modules/epic/__tests__/sendModuleCommandEpic.test.js
- app/src/modules/epic/fetchModulesEpic.js
- app/src/modules/epic/index.js
- app/src/modules/epic/pollModulesWhileConnectedEpic.js
- app/src/modules/epic/sendModuleCommandEpic.js
- app/src/modules/index.js
- app/src/modules/reducer.js
- app/src/modules/selectors.js
- app/src/modules/types.js
- app/src/pipettes/__tests__/actions.test.js
- app/src/reducer.js
- app/src/robot/actions.js
- app/src/robot/selectors.js
- app/src/types.js
This PR refactors the code that was in `app/src/robot-api/resources/modules` (and a few other places) into a new, top-level state subtree at `app/src/modules` and `state.modules`.
- Six actions
- Fetch modules + success + failure
- Send module command + success + failure
- Three epics
- Fetch modules epic (makes HTTP call on fetch modules action)
- Send module command epic (makes HTTP call on send module command action)
- Poll modules while connected epic (triggers fetch modules actions on an interval while robot is connected)
- Three selectors
- Get attached modules
- Get unprepared modules (checks that attached thermocycler lid is open)
- Get missing modules (compares attached modules to protocol modules)
- One reducer
- Puts attached modules in state on FETCH_MODULES_SUCCESS
**This PR …
> refactor(app): refactor /modules state into first-class state subtree

- api/docs/v1/complex_commands.rst
- api/docs/v2/new_modules.rst
closes #4254. In lieu of actually fixing the issue (to avoid making wellseries logic more gross), we are instead documenting best practices for using a multi-channel with advanced functions in API v1. 
I wanted to avoid mentioning the bug in our docs, but I'm open to suggestions on how we can best make sure people only use `columns` or a list of the first row's wells to accomplish a transfer.
> docs(api): Add more info about transferring with multi-channels

- api/src/opentrons/legacy_api/containers/placeable.py
- api/src/opentrons/legacy_api/modules/magdeck.py
- api/src/opentrons/legacy_api/robot/robot.py
If you used a label to customize the name of the labware on your magdeck in v1,
and you were using the original v1 labware name to load on to the magdeck, you
would have to specify the engage height because the label would be used to look
up the magdeck height.
Closes #2310
Nobody may care about this! But technically it was still a bug.
You can test it with this protocol:
```python
from opentrons import modules, labware
mag_module = modules.load('magdeck', '1')
mag_plate = labware.load('biorad-hardshell-96-PCR', '1', 'mag_plate_custom_name',
share=True)
mag_module.engage()
```
Note that it won't happen if you use a v2 labware because it'll get it from the definition.
> fix(api): allow labels on old magdeck containers in v1

- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/definitions.py
- api/tests/opentrons/protocol_api/test_module_context.py
Currently, `ModuleContext.load_labware` is missing a few important parameters, such as `label`, `namespace`, and `version`. Also, `_extra_labware` should also be passed into the `load` function in `ModuleContext.load_labware`, as pointed out in #4612.
This PR adds:
- `label`, `namespace`, and `version` to `ModuleContext.load_labware`
- `_extra_labware`to be passed to the load function in `ModuleContext.load_labware`
- `label` to `ModuleContext.load_labware_from_definition`
- bump the max supported API version!
- docstring fixup for `ProtocolContext.load_labware_from_definition`
- more tests!
closes #4595, closes #4612
> fix(api): allow labeling and versioning for module labware

- api/src/opentrons/api/session.py
Since the robot singleton is now not the thing the rest of the api runs on, it
may not be connected the first time the system tries to detect attached pipettes
before a run. This means that requested pipettes get built as v1, which means
that their settings stand a good chance of being wrong - and that can lead to
failed drop tips.
Closes #4590
Upload v1 protocols under the following circumstances and check the app redux state path /robot/session/pipettesByMount/{mount}/name. The name should usually (with some noted exceptions be the actual full model number of the pipette:
- With the correct pipette already attached, the name should be the full model number (e.g. v1.5)
- With an incorrect pipette, it should be v1 of the pipette specified in the protocol.
> fix(api): make sure the robot is connected before querying instrs

- api/src/opentrons/protocol_api/util.py
You love to see it
Makes the autodoc'd apiv2 stuff that has the `requires_version` decorator go from this:
to this (which is what we want):
> docs(api): Fix autodoc formatting to fix rendering

- api/docs/v2/new_modules.rst
- Thermocycler app usage instructions have been moved into the Help Center, so they can be removed from the API docs.
- For brevity and readability, most instances of *Thermocycler Module* have been changed to *Thermocycler.* This contradicts what I used to think the guidance was, but the content/marketing people clarified it for me earlier today.
> docs(api): Update Thermocycler docs

- shared-data/labware/schemas/2.json
Currently, the JSON schema for labware considers definitions with `wells: {}` valid.
This PR adds having at least one well as a requirement for the top-level `wells`, `groups.wells`, and `ordering`.
closes #4506
> fix(shared-data): require well(s) in labware schema

- protocol-designer/src/constants.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateTemperature.js
- protocol-designer/src/steplist/formLevel/handleFormChange/index.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
closes #4578 
This PR adds both form and field validation for temperature step for the temperature module only.
- feat(protocol-designer): add temperature step form validation
- Create protocol with temp module
- Add temperature step
- Select change temperature
- Create protocol with temp module
- Add temperature step
- Select change temperature
- Create protocol with temp module
- Add temperature step
- Select change temperature
> feat(protocol-designer): add temperature step form validation

- api/src/opentrons/api/session.py
If you cancelled when the robot was homing before the protocol, it wouldn't
actually cancel the protocol itself because it wasn't using the right hardware
backend sometimes.
This makes it correctly cancel the protocol.
- Run a v1 protocol and cancel while the robot is homing before the protocol begins; the robot should home and then stop moving
- Run a v2 protocol and cancel while the robot is homing before the protocol begins; the robot should home and then stop moving.
> fix(api): fix cancelling during the pre-protocol home

- api/docs/v1/atomic_commands.rst
- api/docs/v1/complex_commands.rst
- api/docs/v1/examples.rst
- api/docs/v1/hardware_control.rst
- api/docs/v1/index.rst
- api/src/opentrons/legacy_api/instruments/pipette.py
This PR replaces all very ancient `tiprack-200ul` definitions and the not-as-ancient-but-still-out-of-date `opentrons-tiprack-300ul` to `opentrons_96_tiprack_300ul`.
closes #4587
make sure the old definitions are no longer being used in:
http://sandbox.docs.opentrons.com/docs_remove-old-tiprack-defs/v1/
> docs(api): remove tiprack-200ul from v1 docs

- .travis.yml
- Makefile
- package.json
- protocol-designer/src/analytics/reducers.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/persist.js
- protocol-designer/src/tutorial/reducers.js
- webpack-config/lib/base-config.js
- yarn.lock
This PR removes the last remaining circular import in PD, and enforces our new experimental "no circular imports" rule in CI for both `protocol-designer` and `labware-library` (LL already is circle-free!)
It reimplements PD's `persist.js` by putting "rehydrated" data originating from localStorage into the `REHYDRATE_PERSISTED` action payload, instead of bad practice before where the reducers read from localStorage upon receiving a (previously no-payload) `REHYDRATE_PERSISTED` action. 
- Make a protocol with no steps to get the hint, check the "remember this" and close the hint. PD should remember and not show you this hint when you reload
- Toggle experimental settings (aka feature flags) on/off, refresh PD, and make sure they persist
- Toggle the opt-in toggle (right above the …
> refactor(protocol-designer): reimplement Redux persistence; enforce no circular imports

- Makefile
- app/src/components/CalibrateLabware/ConfirmPositionContents.js
- app/src/components/CalibrateLabware/ConfirmPositionDiagram.js
- app/src/components/CalibrateLabware/instructions-data.js
- app/src/components/modals/BottomButtonBar.js
- app/src/components/modals/ErrorModal.js
- app/src/components/modals/Modal.js
- app/src/components/modals/ScrollableAlertModal.js
- app/src/components/modals/index.js
This PR follows up on #4630 and removes the run app's two circular dependency warnings and enables madge checking for `app/src`
- refactor(app): remove remaining circular dependencies from the app
The files touched were part of the labware calibration wizard, so smoke testing labware calibration couldn't hurt
> refactor(app): remove remaining circular dependencies from the app

- labware-library/src/components/labware-ui/labware-images.js
- shared-data/labware/definitions/2/opentrons_96_filtertiprack_20ul/1.json
- shared-data/pipette/definitions/pipetteModelSpecs.json
Closes #4524. This PR adds the Opentrons 20 µL filter tip rack definition to Labware Library. It has the same dimensions as the Opentrons 10 µL tip rack. 
- add new definition in shared-data
- add image of the 10 uL tip rack to labware library
- update tip overlap values for P20 GEN2 in pipetteModelSpecs
> feat(shared-data): add 20uL filter tiprack

- app/src/robot-controls/__fixtures__/home.js
- app/src/robot-controls/__fixtures__/index.js
- app/src/robot-controls/__tests__/actions.test.js
- app/src/robot-controls/__tests__/reducer.test.js
- app/src/robot-controls/__tests__/selectors.test.js
- app/src/robot-controls/actions.js
- app/src/robot-controls/constants.js
- app/src/robot-controls/epic/__tests__/homeEpic.test.js
- app/src/robot-controls/epic/homeEpic.js
- app/src/robot-controls/epic/index.js
- app/src/robot-controls/reducer.js
- app/src/robot-controls/selectors.js
- app/src/robot-controls/types.js
This PR follows up on the refactor work completed in #4440, #4477, #4544, #4599, #4615, and #4631. The endpoints being recreated today are:
- `POST /robot/home`
This PR does not wire up these actions because it will involve a fairly heavy rewrite of Change Pipette. That will be its own PR.
- Added homing controls to `app/src/robot-controls`
- Added 4 actions (`home` + success / failure, clear homing status/error)
- Added homing and homing error state to `state.robotControls` reducer
- Added 2 selector (`getMovementStatus` and `getMovementError`)
- Added 1 epic (`homeEpic`)
- Added tests for all of the above
Since this PR doesn't wire anything up to the UI, we can save functional testing for that upcoming PR. For this one, please make sure the code and added unit tests look reasonable!
> refactor(app): add home actions and calls to robot-controls module

- protocol-designer/src/ui/modules/selectors.js
- protocol-designer/src/ui/steps/actions/thunks.js
This PR closes #4643 by adding the existing `module_without_labware` hint to the temperature step.
- feat(protocol-designer): Add missing labware hint to temperature step
This is a tiny one for once!
- Make a protocol with a temperature module
- Add a temperature step
_Note_: This is a hint so if you've previously dismissed it for a magnet step or previous temperature step you will not see it again that session. If you've previously checked [ ] don't show this again when testing the magnet step hint - you will not see this hint so please clear out dismissed hints in settings before testing!
> feat(protocol-designer): Add missing labware hint to temperature step

- api/docs/v2/writing.rst
- api/src/opentrons/simulate.py
Closes #4649. 
- Make `file_name` default to None in `simulate`
- Fixup the code in the docs and hopefully make it a little more clear to users which method they should use. (Open to suggestions here)
Please review the documentation and see if it makes sense.
> fix(api): Fix simulate file from python shell

- app/src/robot-controls/__fixtures__/index.js
- app/src/robot-controls/__fixtures__/move.js
- app/src/robot-controls/__tests__/actions.test.js
- app/src/robot-controls/__tests__/reducer.test.js
- app/src/robot-controls/actions.js
- app/src/robot-controls/constants.js
- app/src/robot-controls/epic/__tests__/moveEpic.test.js
- app/src/robot-controls/epic/index.js
- app/src/robot-controls/epic/moveEpic.js
- app/src/robot-controls/reducer.js
- app/src/robot-controls/types.js
This PR follows up on the refactor work completed in #4440, #4477, #4544, #4599, #4615, #4631, #4646. The endpoints being recreated today are:
- `GET /robot/positions`
- `POST /robot/move`
- `POST /motors/disengage`
This PR does not wire up these actions because it will involve a fairly heavy rewrite of Change Pipette. That will be its own PR. As of this PR, all necessary endpoints for the wizard are in the new epic-based `robot-controls` module!
- Added movement controls to `app/src/robot-controls`
- Added 3 actions (`move` + success / failure)
- Added move and move error state to `state.robotControls` reducer
- Added 1 epic (`moveEpic`) that:
1. Calls GET /robot/positions
2. Then calls POST /robot/move with result of GET /robot/positions
3. Then calls POST /motors/disengage depending on …
> refactor(app): add move, positions, and disengage calls to robot-controls

- protocol-designer/src/components/StepEditForm/fields/Volume.js
- protocol-designer/src/components/StepEditForm/forms/Mix.js
- protocol-designer/src/components/StepEditForm/forms/MoveLiquid/index.js
- protocol-designer/src/localization/en/form.json
- change volume label to volume per well
> feat(protocol-designer): change volume label to volume per well

- update-server/otupdate/balena/install.py
This fixes one of the warnings caught by the test suite.  A regex string relied on the deprecated behavior of unrecognized backslash escape sequences expanding to the literal backslash plus the literal character.  It's said that these will be syntax errors in the future.
Fix it by making the string raw.
> refactor(update-server): Make regex string raw.

- api/src/opentrons/config/advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
No migration protection was added for the `useProtocolApi2` feature flag. If the flag does not exist and you try to downgrade to a version which requires this feature flag then an error occurs.
- Add back in the feature flag
Everything look ok?
> fix(api): Add back in useProtocolApi2 feature flag

- api/src/opentrons/config/advanced_settings.py
This renames and reworks the copy of the "Use older pipette calibrations" advanced setting to clarify that it only affects *volumetric* calibration, and to give a hint about its intended usage.  This should help avoid confused users mistakenly trying it when they run into positional calibration problems.
> fix(api): Clarify intended use of "Use older pipette calibrations" flag

- api/src/opentrons/drivers/thermocycler/driver.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/drivers/module_drivers/test_thermocycler_driver.py
- api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
Previously the tc firmware didn't support a deactivate block only gcode command, so the deactivate block hardware control function would actually deactivate the lid too. This fixes that inconsistency and wires it up to the new gcode for deactivate block
> fix(api): split out tc deactivation at driver level

- api/docs/root/index.html
Closes #4672 
Per @b-cooper suggestion, use a relative url to the v2/ path instead of the full index.html to both avoid the redirect loop and still not have to specify the hostname
> docs(api): fix redirect loop

- app/src/components/CalibrateLabware/ProceedToRun.js
- app/src/components/CalibratePanel/LabwareListItem.js
- app/src/components/ModuleControls/TemperatureControl.js
- app/src/components/ModuleControls/index.js
- app/src/components/ModuleItem/index.js
- app/src/components/ModuleLiveStatusCards/index.js
- app/src/components/PrepareModules/index.js
- app/src/components/ReviewDeck/index.js
- app/src/modules/constants.js
- app/src/modules/selectors.js
- app/src/modules/types.js
- shared-data/js/constants.js
- shared-data/js/types.js
Uses defined constants for tempdeck, magdeck, and thermocycler strings. 
It looks like test coverage should catch anything that would affect the selector (getUnpreparedModules), and the rest affects the components. 
However, to properly validate that this doesn't break anything, we should probably run protocols that use each of the modules (temp + mag + thermocycler). 
Other parts of the monorepo should also use these same constants, but I'm breaking up the refactor by each of the subrepos.
> refactor(app): use defined constants for tempdeck, magdeck, thermocycler

- protocol-designer/src/steplist/formLevel/getNextDefaultMagnetAction/__tests__/getNextDefaultModuleAction.test.js
- protocol-designer/src/steplist/formLevel/getNextDefaultMagnetAction/index.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/ui/steps/actions/actions.js
closes #4449 by auto-selecting the opposite of the previous magnet step magnetAction value when a previous magnet step is present.
- feat(protocol-designer): Auto-select !previous magnet action
http://sandbox.designer.opentrons.com/pd_default-magnet-action/
- Create a protocol with a magnetic module
- create a magnet step with magnetAction = 'engage' + save
- create a second magnet step
- save with disengage selected
- create a third magnet step
> feat(protocol-designer): Auto-select !previous magnet action

- protocol-designer/src/components/StepEditForm/forms/TemperatureForm.js
- protocol-designer/src/constants.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/getNextDefaultModuleId/__tests__/getNextDefaultModuleId.test.js
- protocol-designer/src/steplist/formLevel/getNextDefaultModuleId/__tests__/index.js
- protocol-designer/src/steplist/formLevel/getNextDefaultModuleId/index.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/ui/modules/selectors.js
- protocol-designer/src/ui/steps/actions/actions.js
- protocol-designer/src/ui/steps/actions/thunks.js
This PR closes #4642 by adding the logic to auto-select modules in the set temperature form. 
The work grew a bit due to the fact that the TC set temperature form is not yet implemented. See changelog
- feat(protocol-designer): Auto-select module in set temperature form
- Add thermocycler module option to set temp dropdown options
- Auto-select temperature module by default, if only TC present, autoselect TC
- Update missing labware hint to check for module present and missing labware for temperature step
- conditionally render set temperature form for temperature module, render TODO for TC form
This one's a bit of a pain to test...
http://sandbox.designer.opentrons.com/pd_autoselect-module-id/
**Temp module without labware**
- Create a protocol with a temperature module + no labware
- …
> feat(protocol-designer): Auto-select module in set temperature form

- app/src/components/ConfigurePipette/ConfigErrorBanner.js
- app/src/components/ConfigurePipette/ConfigForm.js
- app/src/components/ConfigurePipette/ConfigMessage.js
- app/src/components/ConfigurePipette/index.js
This PR adds a spinner to the "Save" button in Pipette Settings. Closes #4583
> fix(app): add spinner to "Save" button in Pipette Settings

- protocol-designer/src/localization/en/alert.json
This is a quick one - didn't want this is slip through the cracks. Closes #4607 by finalizing module missing labware hint copy
- refactor(protocol-designer): Finalize module missing labware hint copy
http://sandbox.designer.opentrons.com/pd_missing-module-hint-copy/
In settings, restore all hints
Make a protocol with a module but no labware on it
Create a module step
> refactor(protocol-designer): Finalize module missing labware hint copy

- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forPickUpTip.js
- protocol-designer/src/step-generation/utils/reduceCommandCreators.js
- protocol-designer/src/steplist/generateSubsteps.js
Addresses #4697 but still slower than before the step-generation refactor
To compare performance, save a protocol that uses a bunch of tips and does a bunch of transfers. Open it in `edge` and time it, then open it in this branch and time it. Should be noticably faster, but still slow.
Also:
- tip pickup behavior should not change
- substep generation should not change
> perf(protocol-designer): improve timeline generation performance

- api/src/opentrons/execute.py
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/util.py
- api/src/opentrons/simulate.py
- api/tests/opentrons/protocol_api/test_util.py
When these created synchronous adapter threads for hardware controllers, they
would never clean them up. This was fine on python 3.6 and 3.7 but not on
subsequent versions. We now clean them up properly.
Closes #4666 
- simulate and (much less importantly since it always runs in a controlled environment) execute and make sure the program actually exits cleanly
> fix(api): properly clean up threads in opentrons_simulate, _execute

- api/docs/v2/new_atomic_commands.rst
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/definitions.py
- api/tests/opentrons/protocol_api/test_context.py
Currently in APIv2, after a tip is returned, the tip is added back to the tip tracker and will again be picked up by the subsequent `pick_up_tip` call. The documentations however states that the next unused tip will be picked up instead.
This PR closes #4668 by not adding the tip back to the tracker for API version 2.2 and above. A note has been added to the documentations to notify users of the changes made. 
- confirm that the next unused tip is being picked up in version 2.2 rather than the returned tip
> fix(api): do not pick up returned tips

- app/src/robot/reducer/calibration.js
- app/src/robot/test/calibration-reducer.test.js
This should fix a behavior where a user starts labware calibration and exits the flow to home the robot from the robots tab, which breaks their calibration experience when they return.
> fix(app): clear lw calibration state if top level home is called

- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/fieldLevel/processing.js
This PR should finally close out the set temp ticket by updating mask to number to allow for negative numbers and 0.
closes #4305
- fix(protocol-designer): Update maskToNumber to allow for negatives and 0
Make a protocol with a temperature module
Make a temperature step
Select Set Temperature option
Note - I'm not sure if negative integers are an option anywhere but you can test the maskToNumber by removing the `onlyPositiveNumbers` from line 161 `protocol-designer/src/steplist/fieldLevel/index.js`
> fix(protocol-designer): Update maskToNumber to allow for negatives and 0

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/FilePipettesModal.css
- protocol-designer/src/components/modals/FilePipettesModal/ModuleFields.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/components/modules/EditModulesCard.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
This PR closes #4695 by hiding the thermocycler module options for create/edit protocol behind a dev internal feature flag.
- feat(protocol-designer): Hide thermocycler functionality behind flag
Check settings. Ensure `Enable Thermocycler` feature flag is toggled OFF
Toggle `Enable Thermocycler` feature flag ON
Obviously, if you imported a file you created with the FF on, you will still see the TC on the deck and step generation regardless of the FF setting. That aside, please confirm this PR does not miss some weird edge case where TC stuff is visible with the flag off.
> feat(protocol-designer): Hide thermocycler functionality behind flag

- api/docs/v2/new_examples.rst
Easy fixes for Multiple Air Gaps and Dilution example protocols in docs.
closes #4688
> docs(api): apiv2: fix example protocols

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/forms/TemperatureForm.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/index.js
This PR addresses #4286 by making moduleId field required for temperature step. This will only show when a module is deleted that is used saved temperature step. Since set temp step is not fully wired up, this is code only for now.
- feat(protocol-designer): Make moduleId field required for temperature step
As mentioned above, there's still some work to be done wiring up set temp step, so we can't test this in the UI just yet.
> feat(protocol-designer): Make moduleId field required for temperature step

- api/docs/v2/new_modules.rst
- api/docs/v2/versioning.rst
- api/src/opentrons/hardware_control/modules/magdeck.py
- api/src/opentrons/protocol_api/contexts.py
- api/tests/opentrons/data/mad_mag_v2.py
- api/tests/opentrons/protocol_api/test_module_context.py
Similar to #4705, this PR adds a keyword argument to `MagneticModuleContext.engage()` to allow users to move the magnets on the module relative to the base of the labware. 
closes #4213
- add kwarg to `engage()`
- update test
- add some note to docs
- add API version 2.2. to `versioning.html`
- fix `new_modules.html` formatting so the titles are rendered properly
- `MagneticModuleContext.engage(height_from_base=0)` should move the magnets so that the tops of the magnets are level with the ledge that the labware sits on in the module
> feat(api): apiv2: add height_from_base arg to MagneticModuleContext.engage()

- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/DeckSetup/ModuleTag.css
- protocol-designer/src/components/DeckSetup/ModuleTag.js
- protocol-designer/src/components/steplist/AspirateDispenseHeader.js
- protocol-designer/src/components/steplist/MagnetStepItems.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/localization/en/modules.json
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
- protocol-designer/src/top-selectors/substep-highlight.js
- protocol-designer/src/top-selectors/substeps.js
- protocol-designer/src/top-selectors/timelineFrames.js
- protocol-designer/src/top-selectors/tip-contents/index.js
- protocol-designer/src/top-selectors/well-contents/index.js
- protocol-designer/src/ui/modules/selectors.js
- protocol-designer/src/ui/modules/utils.js
> feat(protocol-designer): show magnetic module status in substeps and on deck

- api/docs/v2/new_complex_commands.rst
- api/src/opentrons/protocol_api/contexts.py
- api/src/opentrons/protocol_api/definitions.py
- api/src/opentrons/protocol_api/transfers.py
- api/tests/opentrons/protocol_api/test_transfers.py
The current TransferPlan limits the multi-channel pipettes to have access only to the first row of any labware. This limitation works fine for plates that are in the standard 96-well format. However, in order to fill all wells of a 384-well plate, a multi-channel pipette would need to access the second row of the plate as well. 
This PR closes #4669 and closes #4664 by allowing both row 1 and 2 to be accessible by multi-channel pipettes when the target plate is in the `384Standard` format.
Note: This PR requires a API version bump to 2.2!!
```python
metadata = {'apiLevel': '2.2'}
def run(protocol):
tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 1)
p50 = protocol.load_instrument('p50_multi', 'left', tip_racks=[tiprack])
plate384 = …
```
> fix(api): apiv2: allow multi to access all 384 wells in transfer

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
This PR closes #4728 by hiding previously disabled categories/labware options what are incompatible or unavailable for modules.
- feat(protocol-designer): Hide incompatible labware
http://sandbox.designer.opentrons.com/pd_hide-incompat-labware/
Standard review. 
Note: I conditionally rendered the lists/items rather than touching `TitledList` or `ListItem` or `PDTitledList` to avoid breaking something unintentionally.
> feat(protocol-designer): Hide incompatible labware

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/forms/PauseForm.js
- protocol-designer/src/constants.js
- protocol-designer/src/form-types.js
- protocol-designer/src/localization/en/form.json
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.js
- protocol-designer/src/ui/steps/actions/actions.js
This PR closes #4306 by adding the UI side of pause until temp to the pause form behind the modules feature flag.
- feat(protocol-designer): Pause until temperature reached
- refactor: Update `getDefaultModuleId` to apply to any moduleId field
- refactor: Update `pauseForAmountOfTime` to accept `'untilTime' | 'untilTemperature' | 'untilResume'
- refactor: Remove moduleIdRequired field level validation (was disabling pause for amount of time when module FF was off)
http://sandbox.designer.opentrons.com/pd_wait-until-temp/
Turn Modules in PD FF off
Turn Modules in PD FF on
**Known weirdness not covered by this PR:**
- I had to update the pauseFormToArgs wait field. Right now, saving a Pause until temperature reached saves as a pause for amount of time with 0h 0m 0s. This needs to be handled …
> feat(protocol-designer): Pause until temperature reached

- .eslintrc.js
Add no-default-export rule to linter file warning
Added `no-default-export` as a linter warning since this change affects the codebase broadly. To make this an error and the necessary updates seemed noisy/untenable. We can also scrap if we think the warnings are also too noisy and find a better path forward.
> build(opentrons): add no-default-export rule to linter file

- Makefile
- package.json
- yarn.lock
Add onchange lib to conditionally watch files using make format watch=true command and invoke
prettier on changed file
Added `onchange` library recommended by prettier https://github.com/prettier/prettier/blob/master/docs/watching-files.md.
Initially tried to implement using `watchman` but proved to be quite difficult / could potentially require additional implied dependencies. Onchange is nice because now it requires no additional setups for engineers to begin watching for changes and running prettier.
Curious about watchman issues / have other ideas? These were my findings:
- Attempted to run the task `watchman-wait . -p '**/*.js' -m 0 | xargs prettier --write`. `-m 0` disables the `max-limit`, so the task can continue to run but unfortunately did not allow me to pipe the stdout into …
> build(opentrons): add onchange watch to make format command

- update-server/otupdate/buildroot/name_management.py
- update-server/tests/buildroot/test_name_management.py
Every time an OT-2 has its robot software updated, an extra blank line is inserted in the middle of `/etc/machine-info`, causing the file to grow slowly over time. By a quick calculation, this will cause us to run out of space on the SD card somewhere around release v3.15000000000.0.
* Fixed the issue described above.
* Added some unit tests. It doesn't look like this code was previously covered.
* Figure out what to do about the linter, which complains about long lines, but also doesn't let me break them up into multiple lines with subsequent lines indented.
1. Update your OT-2 with this build.
2. Check the contents of `/etc/machine-info`, paying special attention to blank lines.  I think the OT-2s have `md5sum` pre-installed, to help.
3. Update your OT-2 again.
4. Check …
> refactor(update-server): Don't add extra newlines to /etc/machine-info on update

- protocol-designer/src/localization/en/deck.json
Fix #4725
Switches warning text to match the text in #4725
Create a protocol in PD with a gen1 8-Channel pipette, as well as a module
Validate that the correct deck warning text renders on the deckmap
> refactor(protocol-designer): Revise deckmap crash warning

- app/src/components/App.js
- app/src/components/Resources/ResourceCard.js
- app/src/components/Resources/index.js
- app/src/components/Resources/styles.css
- app/src/index.js
- app/src/pages/More/Resources.js
- app/src/pages/More/index.js
This PR closes #4813 by wrapping text in the resources card on smaller screens. See ticket for prev /buggy behavior. While I was in there, I hit a few export default warnings, and cleared them up. hence the 7 affected files instead of 1 CSS file.
- Open app
- Navigate to More > Resources
- Resize app screen (smaller)
> refactor(app): Make resource card responsive

- protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
This PR closes #4825 by changing the recommended labware for the magnetic module form biorad to nest.
- fix(protocol-designer): Update magnetic module recommended labware
Make a protocol with a magnetic module and add a labware to it
> fix(protocol-designer): Update magnetic module recommended labware

- protocol-designer/src/constants.js
- protocol-designer/src/file-data/selectors/commands.js
- protocol-designer/src/form-types.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-forms/types.js
- protocol-designer/src/step-generation/commandCreators/atomic/deactivateTemperature.js
- protocol-designer/src/step-generation/commandCreators/atomic/disengageMagnet.js
- protocol-designer/src/step-generation/commandCreators/atomic/index.js
- protocol-designer/src/step-generation/commandCreators/atomic/setTemperature.js
- protocol-designer/src/step-generation/commandCreators/index.js
- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/index.js
- protocol-designer/src/step-generation/index.js
- protocol-designer/src/step-generation/test-with-flow/__snapshots__/utils.test.js.snap
- protocol-designer/src/step-generation/test-with-flow/deactivateTemperature.test.js
- protocol-designer/src/step-generation/test-with-flow/fixtures/robotStateFixtures.js
- protocol-designer/src/step-generation/test-with-flow/setTemperature.test.js
- protocol-designer/src/step-generation/test-with-flow/utils.test.js
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/step-generation/utils/commandCreatorArgsGetters.js
- protocol-designer/src/step-generation/utils/index.js
- protocol-designer/src/steplist/formLevel/getNextDefaultModuleId/__tests__/getNextDefaultModuleId.test.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/index.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/magnetFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/temperatureFormToArgs.js
- protocol-designer/src/top-selectors/substep-highlight.js
- shared-data/protocol/flowTypes/schemaV4.js
First part of hooking up Temperature step (addresses #4693) - this should make all possible sorts of valid inputs into the Temperature step get translated into atomic commands (with limited, speculative support for thermocycler).
This does not update the robot state in response to the commands - that will be the next PR.
- define & create setTargetTemperature vs deactivateTemperature commands for temperature module and for thermocycler
- hook up Temperature step to mapFormToArgs
- define temperature deck 3-case state (module state in robotState.modules)
This isn't a very visual one, you need to inspect the JSON to test it (besides code review of the new tests)
Use Temperature step with temperature module and/or thermocycler. Try set temperature, and deactivate. Save the protocol and …
> feat(protocol-designer): add commands for temperature step

- Makefile
- By default, `madge` prints a nice little terminal spinner as it runs through its files
- In CI, because it's not a real terminal, this just prints a new line for every single file checked
- We've currently got a lot of eslint warnings printed (see #4830)
Unfortunately, in CI tasks with lots of logs tend to lead to spurious `make: write error` failures (similar to the ones that were fixed by #4159).
- build(madge,eslint): disable madge spinner and eslint warnings on CI
- Test by messing up a circular dependency and/or JS file and run `make` with `CI=true`
> build(madge,eslint): disable madge spinner and eslint warnings on CI

- protocol-designer/src/components/StepEditForm/forms/MagnetForm.js
- protocol-designer/src/steplist/formLevel/getNextDefaultEngageHeight/__tests__/getNextDefautEngageHeight.test.js
- protocol-designer/src/steplist/formLevel/getNextDefaultEngageHeight/index.js
- protocol-designer/src/steplist/formLevel/getNextDefaultMagnetAction/__tests__/getNextDefaultModuleAction.test.js
- protocol-designer/src/steplist/formLevel/getNextDefaultMagnetAction/index.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/ui/modules/selectors.js
- protocol-designer/src/ui/steps/actions/actions.js
- shared-data/js/constants.js
- shared-data/js/getLabware.js
This PR closes #4764 by adding a function to shared data to calculate recommended engage height for supported labware and rendering recommended value message as engageHeight caption.
- add `getLabwareDefaultEngageHeight` to shared-data
- feat(protocol-designer): Populate engageHeight field with prev values || recommended
- default first `magnetAction` to 'engage'
Make a protocol with a magnetic module
Do not add labware
Make a magnet engage step
Make a protocol with a magnetic module
Add supported labware
Make first magnetic step
Add disengage step
Add another engage step
Make a protocol with a magnetic module
Upload custom labware 
Make a magnet engage step
Add disengage step
Add another engage step
This PR also defaults the first `magnetAction` to `'engage'` to avoid nulling out …
> feat(protocol-designer): Populate engageHeight field with previous values

- app-shell/src/__mocks__/log.js
- app-shell/src/buildroot/index.js
- app-shell/src/buildroot/release-files.js
- app-shell/src/config.js
- app-shell/src/discovery.js
- app-shell/src/log.js
- app-shell/src/main.js
- app-shell/src/menu.js
- app-shell/src/robot-logs.js
- app-shell/src/ui.js
- app-shell/src/update.js
- app/src/__mocks__/logger.js
- app/src/analytics/hash.js
- app/src/analytics/index.js
- app/src/analytics/make-event.js
- app/src/analytics/mixpanel.js
- app/src/analytics/selectors.js
- app/src/components/CalibrateDeck/index.js
- app/src/index.js
- app/src/logger.js
- app/src/pages/Robots/index.js
- app/src/protocol/protocol-data.js
- app/src/protocol/selectors.js
- app/src/robot/api-client/index.js
- app/src/shell/epic.js
- app/src/support.js
- app/src/util.js
Change default exports to named exports in app and app-shell
I'm trying to fix these linter warning in chunks to make merging and reviewing easier. This is the first bit, more to come. 😅 
I will use this as the base branch and merge all the corresponding PRs into this branch
> style(app): change default exports to named exports

- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/index.js
- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/magnetUpdates.js
- protocol-designer/src/step-generation/getNextRobotStateAndWarnings/temperatureUpdates.js
- protocol-designer/src/step-generation/test-with-flow/temperatureUpdates.test.js
- protocol-designer/src/step-generation/utils/misc.js
This will close out the remainder of 4693 by allowing the temp deck to be updated.
closes #4693
- Create forSetTemperature and forDeactivateTemperature for use in robot state and warnings
Nothing on the ui side, just verify that the tests and the data the functions returns is sufficient.
> feat(protocol-designer): allow temperature deck to be updated

- labware-library/src/labware-creator/index.js
- labware-library/src/labware-creator/styles.css
This PR closes #4875 by moving the Labware Creator test guidance callout + PDF download button before the export button.
- refactor(labware-creator): Swap PDF and export button order
http://sandbox.labware.opentrons.com/lc_pdf-export-btn-swap/create/
> refactor(labware-creator): Swap PDF and export button order

- protocol-designer/src/components/DeckSetup/LabwareOverlays/LabwareControls.js
- protocol-designer/src/ui/steps/selectors.js
- protocol-designer/src/ui/steps/test/selectors.test.js
Allow highlighting of labware when hovering over module steps in the timeline. closes #4696
- return module id in getHoveredStepLabware if stepArgs is a module
- Update highlighted flag in LabwareControls to allow labware on these modules to be highlighted
[http://sandbox.designer.opentrons.com/pd_highlight-modules/](http://sandbox.designer.opentrons.com/pd_highlight-modules/)
> feat(protocol-designer): add labware hover highlighting to modules

- .gitignore
- CONTRIBUTING.md
- Makefile
- labware-library/Makefile
- labware-library/cypress/integration/labware-creator/fileImport.spec.js
- protocol-designer/Makefile
- protocol-designer/cypress.json
- protocol-designer/cypress/integration/home.spec.js
- protocol-designer/cypress/integration/newProtocol.spec.js
- protocol-designer/cypress/integration/settings.spec.js
- protocol-designer/cypress/integration/sidebar.spec.js
- protocol-designer/cypress/plugins/index.js
- protocol-designer/cypress/support/commands.js
- protocol-designer/cypress/support/index.js
Building on my cypress.io tests for the labware-library, this PR adds testing to the protocol-designer. here is a lot to test with this complex app, and I wanted to get what I have done now merged while I work on the rest. These tests include page navigation, the settings page, and protocol definitions up through liquids.
I also added a global `make test-e2e` command that runs all existing cypress tests for all the apps. I had to tweak the existing labware-library tests slightly to make this work.
- Added the required file layout for cypress.io in the protocol-designer app. 
- Created e2e tests that go up through adding liquids.
- Added a global 'make test-e2e' command that runs all existing cypress tests for all apps.
There are no breaking changes. This PR takes what I made for the …
> test(protocol-designer): add cypress.io infrastructure and initial tests

- api/docs/v2/writing.rst
- api/src/opentrons/execute.py
- api/src/opentrons/simulate.py
A required parameter was added to the `get_protocol_api` method of `opentrons.simulate` and `opentrons.execute`, but the corresponding documentation was not all updated.
> docs(api): add version parameter in jupyter instructions

- components/src/__tests__/__snapshots__/slotmap.test.js.snap
- components/src/__tests__/slotmap.test.js
- components/src/index.js
- components/src/slotmap/SlotMap.js
- components/src/slotmap/SlotMap.md
- components/src/slotmap/index.js
- components/src/slotmap/styles.css
- components/styleguide.config.js
This PR addresses #4815 by adding the SVG mini slot map to the component library. 
Splitting up the component library and PD implementation into 2 separate PRs  for sanity sake. Thanks @IanLondon for the SVG pairing!
- feat(components): Add mini slot map to shared components
> feat(components): Add mini slot map to shared components

- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/RadioGroupField.js
- protocol-designer/src/components/StepEditForm/forms/PauseForm.js
- protocol-designer/src/localization/en/tooltip.json
- protocol-designer/src/ui/modules/selectors.js
This PR closes #4867 by disabling the `Pause until temperature reached` radio field when there is no Thermocycler or Temperature Module present on the deck.
- feat(protocol-designer): Conditionally disabled pause until temp
- refactor(protocol-designer): Add optional className to RadioGroupField to enable disabled styles
Make a protocol without a temperature or thermocycler module
add a pause step
add a temperature or thermocycler module to the deck
> feat(protocol-designer): Conditionally disabled pause until temp

- api/tests/opentrons/cli/test_cli.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_settings_endpoints.py
test_settings_endpoints fails when running independently. specifically, it passes the first time, but fails the second time. the root cause is that a robot settings file is created on the first run and breaks the second run.
fixes #4894 
Add config setup/teardown to test_settings_endpoints.
> fix(api): test_settings_endpoints fails when running independently. 

- Makefile
- api/Makefile
- app-shell/Makefile
- app/Makefile
- components/Makefile
- discovery-client/Makefile
- labware-designer/Makefile
- labware-library/Makefile
- protocol-designer/Makefile
- protocol-library-kludge/Makefile
- shared-data/Makefile
- update-server/Makefile
make on macOS does not seem to honor updates to PATH within the Makefile for shell invocation. This can be resolved be setting the PATH env variable as part of the SHELL command. This change is benign for GNU make.
fix #4808
All Makefiles have been updated to modify the existing line that set the SHELL env variable to include the PATH.
I have tested this using standard make on macOS (10.15) and GNU make on Ubuntu linux. Some tests on other configurations would provide confidence that this works across the supported environments.
> build(make): ensure SHELL includes PATH in its environment

- protocol-designer/src/steplist/fieldLevel/errors.js
This very tiny PR closes #4913 by updating the min/max range error copy.
- refactor(protocol-designer): Update range caption copy
Make an engage magnet step
Enter a number above max range for engage height
Enter a number below min range for engage height
Make a set temperature step
Enter a number above max range for target temp
_Note: Min is 0, and negative numbers are not allowed via maskers so you cant get the Min range exceeded error here!_
> refactor(protocol-designer): Update range caption copy

- api/src/opentrons/protocol_api/execute.py
Happened to see this while browsing code. `self._msg` doesn't exist. Use `self.message` for concatenation.
> fix(api): bug in MalformedProtocolError.__str__

- .github/CODEOWNERS
Adds configuration for github code owners
(https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
to the repo
> chore(*): add CODEOWNERS to repo

- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/components/steplist/__tests__/StepItem.test.js
- protocol-designer/src/localization/en/modules.json
- protocol-designer/src/step-generation/types.js
- protocol-designer/src/steplist/generateSubsteps.js
- protocol-designer/src/steplist/types.js
This PR closes #4863 by adding `awaitTemperature` substeps. Shout out to Jenny for the reusable `ModuleSubstepItem`!
- feat(protocol-designer): Add awaitTemperature substep items
code review: I added 1 test, since there is only 1 possible way for this substep to render. Am I missing any cases?
create a set temperature step
create a pause until temp step (await temp)
> feat(protocol-designer): Add awaitTemperature substep items

- protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdatePause.js
This PR closes #4949 by clearing the three time fields in the pause step form when the radio button selection changes.
This is a follow up PR to https://github.com/Opentrons/opentrons/pull/4944#discussion_r376620836
Create a protocol with a temp deck
Make a temp step (can be empty)
Make a pause step 
Select `Delay for an amount of time` 
FIll in time seconds, minutes, hours fields
Change the radio button
> feat(protocol-designer): reset time fields in pause step

- app/src/components/IconCta/styles.css
Closes #4974
- refactor(app): Fix custom labware directory button backgrounds
> refactor(app): Fix custom labware directory button backgrounds

- protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/step-forms/utils.js
closes #4726 
This feature allows users to add modules to slots where compatible labware is already set up. The second part of the ticket was already done in another PR.
- Add check for compatible labware in edit module modal
- Add tests for existing edit module modal (at least the parts that I worked on in this feature) 
http://sandbox.designer.opentrons.com/pd_compatible-labware/
Make sure to disable module placement restrictions
**With compatible labware**
1. Create a protocol without any modules
2. Add a magnet or temperature **compatible** module to any deck slot
3. Add steps if you like
4. Go back to the file page and click on add next to the module that you added compatible labware for
5. Under positions, select the slot that you added the labware to
6. Click save and go back to …
> feat(protocol-designer): allow modules to be placed on compatble labware

- protocol-designer/src/components/SettingsPage/FeatureFlagCard/FeatureFlagCard.js
- protocol-designer/src/components/modals/modal.css
- protocol-designer/src/localization/en/modal.json
This PR closes #4911 by changing the title and content of the experimental settings warning modals. 
- fix(protocol-designer): Update experimental settings warning text
Go to settings in PD
Toggle an experimental setting ON
Toggle an experimental setting OFF
> fix(protocol-designer): Update experimental settings warning text

- api/src/opentrons/server/endpoints/networking.py
- api/src/opentrons/server/http.py
- api/src/opentrons/server/openapi.json
- api/src/opentrons/system/nmcli.py
- api/tests/opentrons/server/test_networking_endpoints.py
Closes #4847 
This PR allows us to disconnect the robot wifi by using `/wifi/disconnect` endpoint. The endpoint needs the wifi ssid specified in the body of the `POST` request as a string in JSON format: `{'ssid': 'your_wifi_ssid'}`
Upon disconnecting from wifi, the robot should not auto-connect to the ssid unless it is re-booted.
Uses nmcli.
- added disconnect endpoint & networking request handler
- added disconnect method to `nmcli`
- added a networking endpoints test
- plz make sure the code looks good
- test by sending a POST request with the ssid to a robot connected over wifi. Best to send the request over a wired connection so you can receive the response back. Also try to disconnect over the wifi connection; the robot should disconnect but you wouldn't get any response to the http …
> feat(api): add wifi disconnect capability

- app/src/modules/epic/fetchModulesEpic.js
- app/src/modules/epic/pollModulesWhileConnectedEpic.js
- app/src/modules/epic/sendModuleCommandEpic.js
- app/src/modules/epic/updateModuleEpic.js
- app/src/modules/types.js
- app/src/networking/epic/index.js
- app/src/networking/epic/statusEpic.js
- app/src/pipettes/epic/fetchPipetteSettingsEpic.js
- app/src/pipettes/epic/fetchPipettesEpic.js
- app/src/pipettes/epic/fetchPipettesOnConnectEpic.js
- app/src/pipettes/epic/updatePipetteSettingsEpic.js
- app/src/pipettes/types.js
- app/src/robot-admin/epic/fetchResetOptionsEpic.js
- app/src/robot-admin/epic/resetConfigEpic.js
- app/src/robot-admin/epic/restartEpic.js
- app/src/robot-admin/types.js
- app/src/robot-api/operators.js
- app/src/robot-controls/epic/fetchLightsEpic.js
- app/src/robot-controls/epic/homeEpic.js
- app/src/robot-controls/epic/moveEpic.js
- app/src/robot-controls/epic/updateLightsEpic.js
- app/src/robot-controls/types.js
- app/src/robot-settings/epic/clearRestartPathEpic.js
- app/src/robot-settings/epic/fetchSettingsEpic.js
- app/src/robot-settings/epic/updateSettingEpic.js
- app/src/robot-settings/types.js
- app/src/robot/test/api-client.test.js
- app/src/shell/epic.js
- app/src/types.js
- app/src/util.js
This PR is a followup to the recent app-side API client changes. In the interest of stronger type-checking and fewer things to type, this PR simplifies the app's typing of epic to a single `Epic` type of the definition:
```js
export type Epic = (
action$: Observable<Action>,
state$: Observable<State>
) => Observable<Action>
```
I've had this sitting on a local branch for a while, so now that module firmware updates and get /networking/status are in, now would be a good time to get this change made
- Updated the type annotations of the app's epics to use more simple `Epic` definition
Did not touch actual source, just type definitions, so please smoke test and make sure the code looks reasonable
> refactor(app): simplify top-level Epic type

- components/src/__tests__/__snapshots__/slotmap.test.js.snap
- components/src/slotmap/SlotMap.js
- components/src/slotmap/__tests__/SlotMap.test.js
- components/src/slotmap/styles.css
- protocol-designer/src/components/modules/CrashInfoBox.js
- protocol-designer/src/components/modules/styles.css
This PR closes #4989 by updating the viewbox for the slotmap to not crop the edge slot borders and matching crash warning icons on slotmap and crash info box in File Settings Page.
- fix(protocol-designer): Update SlotMap and CrashInfoBox styles
- refactor(components): Add enzyme tests to SlotMap
http://sandbox.designer.opentrons.com/pd_slot-map-edits/
> fix(protocol-designer): Update SlotMap and CrashInfoBox styles

- protocol-designer/src/components/StepEditForm/forms/MagnetForm.js
- protocol-designer/src/components/StepEditForm/forms/__tests__/MagnetForm.test.js
- protocol-designer/src/ui/steps/actions/__tests__/actions.test.js
- protocol-designer/src/ui/steps/actions/actions.js
This PR closes #4912 by rounding the caption underneath the engage height input and the default height in the input to match the same rules as when typing in a height. In this case, it will round decimals to the tenth place.
- Use same masking logic for the caption in MagnetForm and the default engage height in actions
- Added tests for this part of functionality as agreed on from yesterday's testing meeting
Enzyme has a known issue with shallow rendering + diving connected components and hooks. Any ideas on testing the MagnetForm is welcome! I had to mount and manually mock the field components.
**Engage height with more than 1 decimal place**
Create a new protocol with a magnet module
Add the USA Scientific 96 Deep Well Plate 2.4 mL on top of the magnet module
Add a magnet step
The …
> fix(protocol-designer): round caption under engage height to match input box

- api/setup.py
This matches the version on the robot, and can actually parse labware requirements.
Closes #5004
> chore(api): bump required jsonschema in pypi config

- api/setup.py
This PR tweaks #5005.
jsonschema [uses semantic versioning](https://python-jsonschema.readthedocs.io/en/stable/faq/#how-do-jsonschema-version-numbers-work). So, we can specify that we don't want their next breaking change.
jsonschema has already had one major version bump since we've started using it, apparently. That could have included breaking changes that affect us; we're lucky it didn't.
Should we also change this in the Pipfile?
https://github.com/Opentrons/opentrons/blob/01fccdfc3c6159dc2cd45a59e2ee07cea21031d2/api/Pipfile#L32
* [jsonschema changelog](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst).
* It would be nice if we could also do this for NumPy, the only other dependency not to have a pinned version. But we can't, because [they don't use semantic …
> chore(api): Constrain jsonschema dependency to current major version

- shared-data/protocol/schemas/4.json
I missed this in the original JSON v4 schema PR! `closeLid` -> `runProfile`. Should match the type in `shared-data/protocol/flowTypes/schemaV4.js`
- Typo fixed
- No more obvious typos?
> fix(shared-data): fix typo in v4 protocol schema

- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/test/reducers.test.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/index.js
Closes #4883
This is mostly a data-sanity cleanup, ensuring `moduleId` doesn't retain deleted modules' IDs. The UX should be unchanged, b/c it already gives you the same "missing module" timeline error whether the ID is `null` or invalid.
UPDATE: we were missing form-level errors for these forms. This PR adds/fixes them.
- null out moduleId when corresponding module is deleted
- fix/create form-level errors for module forms
* Creating any step that refers to a module (magnet, temperature, pause until temp) and deleting that module should set that step's `moduleId` to `null` instead of retaining the old ID
> fix(protocol-designer): null out deleted module IDs from step forms

- app/src/networking/__fixtures__/index.js
- app/src/networking/__fixtures__/list.js
- app/src/networking/__tests__/actions.test.js
- app/src/networking/__tests__/reducer.test.js
- app/src/networking/__tests__/selectors.test.js
- app/src/networking/actions.js
- app/src/networking/constants.js
- app/src/networking/epic/__tests__/wifiListEpic.test.js
- app/src/networking/epic/index.js
- app/src/networking/epic/wifiListEpic.js
- app/src/networking/reducer.js
- app/src/networking/selectors.js
- app/src/networking/types.js
This PR closes adds actions, reducer, epic, and selector logic to the app's top level `networking` state module to support `GET /wifi/list`. Closes #5021.
This PR does not remove the corresponding logic in `http-api-client/networking.js` nor does it touch component wirings in favor of doing that work in other PRs.
- refactor(app): add state for GET /wifi/list to networking module
1. Open up Redux devtools
2. Dispatch `networking:FETCH_WIFI_LIST` action
```
{
type: 'networking:FETCH_WIFI_LIST',
payload: { robotName: 'sanni-t Bot' },
meta: {}
}
```
> refactor(app): add state for GET /wifi/list to networking module

- app-shell/src/__tests__/discovery.test.js
- app-shell/src/discovery.js
- discovery-client/README.md
- discovery-client/src/__fixtures__/mdns-browser-service.js
- discovery-client/src/__fixtures__/service.js
- discovery-client/src/__tests__/client.test.js
- discovery-client/src/__tests__/service-list.test.js
- discovery-client/src/__tests__/service.test.js
- discovery-client/src/cli.js
- discovery-client/src/index.js
- discovery-client/src/mdns-browser.js
This PR continues #4830 by switching the discovery client over to named exports
- refactor(discovery-client): switch default exports to named exports
Smoke test app discovery:
1. Delete `~/Library/Application\ Support/Opentrons/discovery.json` (or the `discovery.json` file in whatever path your OS's config directory is)
2. Open the app
Smoke test standalone discovery client:
1. `make -C discovery-client`
2. `yarn discovery browse`
> refactor(discovery-client): switch default exports to named exports

- app/src/components/CalibrateDeck/AttachTip.js
During deck calibration, the app tells users to "Place *a GEB tip* on the...pipette before continuing."
This PR is a proposal to say "an *Opentrons tip*" instead.
Our tip situation is a confusing mess. I won't attempt to tell the full history, but, currently:
* The [Labware Library](https://labware.opentrons.com/?category=tipRack) has GEB tip racks, which are colorful and don't fit on the deck without an adapter, as well as Opentrons tip racks, which are black.
* We only sell, support, and test with [Opentrons tips](https://shop.opentrons.com/collections/opentrons-tips).
* Opentrons tips are manufactured by GEB, and they unfortunately bear a GEB sticker, but Hardware is working on getting an Opentrons sticker added.
* The Hardware team keeps talking about getting better tips from GEB. …
> fix(app): Deck cal: Tell users to attach an Opentrons tip, not a GEB tip.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR servers as its own ticket. This splits our issue templates between bug reports and feature requests for our own sanity as well as external contributors'
- chore(*): Separate feature request and bug report issue templates
I left the copy pretty generic. Please include any copy edits you'd like to see.
> chore(*): Separate feature request and bug report issue templates

- api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
If the plunger of a pipette that requires move splitting is at the top
of its range when a home() occurs, the hard limit error that happens
during the move will cause the api server to spin forever.
Closes #5071
> fix(api): fix a spinlock in pre-home plunger unsticking

- protocol-designer/src/components/FilePage.css
- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/StepEditForm/ButtonRow/index.js
- protocol-designer/src/components/StepEditForm/ButtonRow/styles.css
- protocol-designer/src/components/StepEditForm/StepEditForm.css
- protocol-designer/src/components/StepEditForm/fields/TipPositionField/TipPositionInput.css
- protocol-designer/src/components/StepEditForm/fields/TipPositionField/TipPositionModal.js
- protocol-designer/src/components/StepEditForm/fields/WellOrderField/WellOrderInput.css
- protocol-designer/src/components/StepEditForm/fields/WellOrderField/WellOrderModal.js
- protocol-designer/src/components/modals/EditModulesModal/EditModules.css
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/components/modals/EditPipettesModal/StepChangesConfirmModal.css
- protocol-designer/src/components/modals/EditPipettesModal/StepChangesConfirmModal.js
- protocol-designer/src/components/modals/FilePipettesModal/FilePipettesModal.css
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/modal.css
Too many styles for buttons!
Addresses #1670. Doesn't close it b/c I didn't want to mess with the lost-grid button rows now.
This does slightly change styles (margin above buttons), but hopefully the margin changes are good and make less subtle variations in the styles. Detailed below
- remove multiple `button_row` classes
- new `button_row_divided` class for the common case where there is a button on the left and the rest on the right
The easiest way I've found to look for style changes is to open `edge` sandbox in one tab, and open this branch in another tab.
> feat(protocol-designer): unify "button row" styles

- protocol-designer/src/components/FileSidebar/__tests__/FileSidebar.test.js
- protocol-designer/src/components/FileSidebar/utils/__tests__/getUnusedEntities.test.js
My #5029 broke CI for `edge`, this PR updates these tests.
Also add some Flow coverage to the enzyme test, which pointed out the fixture was slightly wrong (FileData keys on the wrong level)
> fix(protocol-designer): fix tests for FileSidebar after merging #5029

- app/src/networking/__fixtures__/configure.js
- app/src/networking/__fixtures__/index.js
- app/src/networking/__tests__/actions.test.js
- app/src/networking/actions.js
- app/src/networking/api-types.js
- app/src/networking/constants.js
- app/src/networking/epic/__tests__/wifiConfigureEpic.test.js
- app/src/networking/epic/index.js
- app/src/networking/epic/wifiConfigureEpic.js
- app/src/networking/types.js
Part of #4842 
This PR adds actions, epics, etc. to `app/src/networking` for `POST /wifi/configure`. It does not wire any of these up to the UI because the configuration UI is currently being refactored in #5028; the wireup will happen there
To test, use the Redux devtools to dispatch a configure action:
```js
{
type: 'networking:POST_WIFI_CONFIGURE',
payload: {
robotName: 'some-robot-name',
options: { ssid: 'network-name', psk: 'network-password' },
},
meta: {}
}
```
- Note: this replaces existing logic in `mapDispatchToProps` of `app/src/components/RobotSettings/SelectNetwork/index.js`
> refactor(app): add wifi configure actions and epics to networking module

- scripts/python_build_utils.py
api will be split into api-server and opentrons packages. Adding support in python_build_utils.py. Made a slight refactor to make it easier to add new packages.
Also, enabled running from the scripts directory.
Notice that it's to be merged into api_splitup_feature_branch, a feature branch for the split up.
Sorry about the PR noise. This replaces #5051 which was for a bumbbranch.
> feat(scripts): python_build_utils supports upcoming api spli

- api/src/opentrons/protocol_api/util.py
* Python 3.6 allows the expression `some_string in SomeEnum` in addition to `some_enum_value in SomeEnum`.
* In April 2018, Python 3.7 [deprecated](https://github.com/python/cpython/pull/6392) `some_string in SomeEnum`.
* In Python 3.8, it raises a `TypeError`.
Because of this, user protocols that adjust `protocol.max_speeds` throw an exception when simulated on Python 3.8. Our own custom labware test protocol does this.
* Replaced ad-hoc key normalization logic in `AxisMaxSpeed.__getitem__` with the same code used elsewhere in the class, which just so happens to avoid the problematic expression.
Please double-check that this doesn't accidentally introduce any behavioral changes that the unit tests don't cover. (I don't think it does.)
This had been raising `DeprecationWarning`s, but we …
> fix(api): Avoid Python 3.8 unsupported `str in Enum` expression

- scripts/python_build_utils.py
api will be split into api-server and opentrons packages. Adding support in python_build_utils.py. Made a slight refactor to make it easier to add new packages.
Also, enabled running from the scripts directory.
> feat(scripts): python_build_utils supports upcoming api split 

- api/docs/v2/index.rst
- api/docs/v2/new_atomic_commands.rst
- api/docs/v2/new_complex_commands.rst
- api/docs/v2/new_examples.rst
- api/docs/v2/new_labware.rst
- api/docs/v2/new_modules.rst
- api/docs/v2/new_pipette.rst
- api/docs/v2/versioning.rst
Some bugs have been fixed since the release of PAPI version 2.0 that are still switched behind the apiLevel metadata. As a result, users should be encouraged to use the more recent version of the API as a default. Users who copy-paste example code from the docs have been getting a metadata object with apiLevel set to 2.0 and thus have encountered problems such as inability to access the 2nd half of 384-well plates.
- updated API docs example code metadata to apiLevel 2.2
Take a look at the docs and make sure I didn't change something I shouldn't have.
> docs(api): update example apiLevel to 2.2

- api/src/opentrons/main.py
- api/src/opentrons/server/__init__.py
This is a mild refactor to support migration to robot_server. .
The robot_server will serve as the entrypoint to the http server. It will use the opentrons.api package to interact with the robot. Robot server needs to initialize the api, not unlike what we do in `opentrons.main`. This defines that initialize method that will be used by api and robot_server. Eventually main and server.main will be removed from the api sub project.
> refactor(api): create a method that will initialize api.

- app-shell/src/labware/__tests__/definitions.test.js
- app-shell/src/labware/definitions.js
- app/src/protocol/__tests__/reducer.test.js
- app/src/protocol/constants.js
- app/src/protocol/index.js
- app/src/protocol/protocol-data.js
- app/src/protocol/types.js
This PR fixes an embarrassing mistake in the app's filename handling for custom labware and protocols: it expects all file extensions to be lowercase
Fixes #5151
- fix(app): accept mixed-case extensions for protocols and custom labware
> fix(app): accept mixed-case extensions for protocols and custom labware

- protocol-designer/src/components/steplist/ModuleStepItems.js
- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/components/steplist/StepItem.js
- protocol-designer/src/components/steplist/__tests__/StepItem.test.js
- protocol-designer/src/localization/en/modules.json
- protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.js
- protocol-designer/src/steplist/formLevel/stepFormToArgs/test/pauseFormToArgs.test.js
closes #5116. See ticket for text/style updates.
- refactor(protocol-designer): Update pause item substep messaging and styles
Make a protocol with a temperature module
Add a set temp step
Add a pause until temperature step
Add a pause until told to resume step with a message
Add a pause for an amount of time step and a message
> refactor(protocol-designer): Update pause item substep messaging

- app/src/robot/api-client/client.js
- app/src/robot/test/api-client.test.js
This works PR works around a "bug" from the RPC API in PAPIv1 (Existing expected bahavior? Who really knows?) that was discovered by an internal user.
A pipette may be reported to the app to use no tip racks even if a tip rack object used in the protocol reports usage by that same pipette. E.g. the session can come back with:
- RPC Session
- "Instruments" list
- Some pipette
- Tip racks list: []
- "Containers" list
- Some tip rack
- Pipettes list: [ "Some pipette" ]
This appears to happen if one constructs the pipettes without using the `tip_racks` argument of the constructor in PAPIv1. To work around this issue, the app will now build the tip rack usage list from both the RPC instruments _and_ the RPC containers, instead of just the instruments.
- fix(app): use containers and instruments …
> fix(app): use containers and instruments to set RPC pipette tip rack list

- protocol-designer/src/components/DeckSetup/ModuleTag.css
- protocol-designer/src/components/DeckSetup/ModuleTag.js
- protocol-designer/src/components/DeckSetup/__tests__/ModuleTag.test.js
Closes #5110 by adding the highlighted border around the module label when hovering over module steps in the timeline.
- Update styling for tag - border adds a bit more space to the tag
- Tag is also now highlighted along with the labware
- Updated test file - added extra describe block to separate out two components in the file
1. Hovering over module step with labware
2. Create a new protocol with a module
3. The tag on the deck should not be highlighted
4. Add labware to the module on the deck
5. Add the same labware to another slot
6. Add some steps (transfers, mixes) to the labware not on the module
7. Add a module step
8. Hover over the transfer/mix steps
9. Hover over the module step
10. Try removing the labware on the deck
> feat(protocol-designer): add border to module tag when hovering over step

- robot-server/robot_server/service/models/control.py
The fastapi application now resides in robot-server.
Move recent changes to the control model from `api` to `robot-server`.
> refactor(robot-server): udpate control model

- robot-server/Pipfile
- robot-server/Pipfile.lock
- robot-server/tests/conftest.py
- robot-server/tests/service/routers/test_health.py
This sets up basic robot_server http client for unittesting using a hardware simulator.
The `/health` endpoint unit test from `api` is ported to run against the fastapi service implementation.
This is meant to support further deprecation of use of aiohttp in favor of fastapi in #4963
> refactor(api): port aiohttp health unit test to fastapi

- robot-server/robot_server/service/routers/health.py
Fix bug that only revealed itself when `fw_version` stopped being an awaitable.
> fix(robot-server): fix failure in fw_version reading in health endpoint.

- protocol-designer/cypress/integration/newProtocol.spec.js
- protocol-designer/cypress/integration/settings.spec.js
The cypress end to end tests were failing since we added the modal and the cypress couldn't access some of the buttons covered by the announcement modal.
- Added relevant tests to close announcement modal so tests can continue
- Run the e2e tests for protocol designer. They should no longer be failing. There should be no more errors saying element was covered by modal overlay.
> test(protocol-designer): fix failing cypress tests following addition of announcement modal

- robot-server/robot_server/service/routers/settings.py
Cannot import log control on non-linux machines. I was importing it to get the max number of log records to return in the get_log API.
> fix(robot-server): cannot import log control

- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/SlotControls.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/__tests__/SlotControls.test.js
- protocol-designer/src/components/DeckSetup/__tests__/DeckSetup.test.js
- protocol-designer/src/utils/__tests__/labwareModuleCompatibility.test.js
- protocol-designer/src/utils/labwareModuleCompatibility.js
Closes #4910 by removing restrictions when placing custom labware on modules
- Add checks for custom labware in relevant functions
- Add tests
https://github.com/Opentrons/opentrons/issues/4910 - acceptance criteria here
This was tested with the python api but feel free to test it yourself.
**Swapping labware**
1. Create a custom labware using labware creator
2. Create a new protocol with a magnet and temperature module
3. On the deck view, click on the modules to add a new labware
4. Select upload custom labware and upload your labware
5. Select the custom labware as the labware to place on the magnet and temperature module
6. Add magnet and temperature compatible labwares to the deck in empty slots
7. Swap the custom labware on the magnet module with the magnet compatible labware
8. …
> feat(protocol-designer): allow custom labware on modules

- .gitignore
Vscode configs were getting tracked by git depending in where they live. I assume we don't want that, so voila.
> chore(*): include all vscode configs in gitignore

- protocol-designer/src/ui/labware/__tests__/selectors.test.js
- protocol-designer/src/ui/labware/selectors.js
- protocol-designer/src/ui/modules/utils.js
closes #5119. Adds module prefix to labware on top of modules for transfer and mix form labware dropdowns.
- feat(protocol-designer): Add module prefix to labware
make a protocol with both modules
add labware on top of those modules
add some other labware
create a transfer step
create a mix step
> feat(protocol-designer): Add module prefix to labware

- robot-server/robot_server/service/main.py
- robot-server/robot_server/service/models/control.py
- robot-server/robot_server/service/models/pipettes.py
- robot-server/robot_server/service/routers/control.py
- robot-server/robot_server/service/routers/pipettes.py
- robot-server/tests/service/routers/test_pipettes.py
Implements the `GET  /pipettes` endpoint in robot-server's fastapi.
port tests from api
implement endpoint business logic
Very low risk. This only impacts code that is not executed on the robot at the moment.
closes #5145
> refactor(robot-server, api): add /pipettes endpoint and tests

- protocol-designer/package.json
- protocol-designer/src/components/modals/GateModal/index.js
- protocol-designer/src/networking/opentronsWebApi.js
- protocol-designer/webpack.config.js
- yarn.lock
Closes #5126 
This merges in the changes from the PD hotfix release 3.0.8! (tag `protocol-designer@3.0.8`)
- Allow user to bypass Typeform modal
- Bump PD version to 3.0.8 (we'll bump it to 4 soon so this doesn't really matter)
Check the sandbox build or run dev with this flag: `make -C protocol-designer/ dev OT_PD_SHOW_GATE=1` so that the Typeform blocking modal appears
Try this in an incognito tab so localStorage / cookies don't remember that you dismissed any of the modals.
> feat(protocol-designer): allow user to bypass typeform modal

- app/package.json
- components/src/__tests__/__snapshots__/structure.test.js.snap
- components/src/buttons/Button.js
- components/src/forms/InputField.js
- components/src/forms/SelectField.js
- components/src/index.js
- components/src/structure/Card.js
- components/src/styles/font-size.js
- components/src/styles/typography.js
- flow-typed/npm/styled-components_v5.x.x.js
- jest.config.js
- scripts/setup-enzyme.js
Rather than jamming these changes into a different feature PR, this PR adds some stuff needed to get styled-components playing nicely in the app
- Add styled-components flow type definition
- Integrate styled-components into jest snapshots (even though we'll be removing most, if not all, snapshot tests)
- Add some more JS styles to components library
Covered by review requests
> build(styled-components): add styled-components to app deps

- api/src/opentrons/system/nmcli.py
- api/tests/opentrons/system/test_nmcli.py
nmcli uses ':' as a field separator. If it encounters a : in a field
value, it escapes it with a backslash. We weren't parsing this
correctly (or indeed at all) and therefore couldn't connect to wifi
networks whose names include a colon. Parsing escaped strings is hard,
so this change uses the csv module to parse them properly
- Connect to a wifi network. I did this at home (my network has a colon in it, hence the issue) and it works now
- Really only new wifi connections, and since it's only response values even just listing wifi networks checks if the problem is solved
> fix(api): properly parse escaped nmcli responses

- robot-server/robot_server/service/main.py
- robot-server/robot_server/service/models/item.py
- robot-server/robot_server/service/models/json_api/errors.py
- robot-server/robot_server/service/models/json_api/factory.py
- robot-server/robot_server/service/models/json_api/request.py
- robot-server/robot_server/service/models/json_api/resource_links.py
- robot-server/robot_server/service/models/json_api/response.py
- robot-server/robot_server/service/routers/item.py
- robot-server/tests/service/helpers.py
- robot-server/tests/service/models/json_api/test_errors.py
- robot-server/tests/service/models/json_api/test_factory.py
- robot-server/tests/service/models/json_api/test_request.py
- robot-server/tests/service/models/json_api/test_resource_links.py
- robot-server/tests/service/models/json_api/test_response.py
- robot-server/tests/service/routers/test_item.py
Adds formatted json responses and error handling in FastAPI framework
closes #4636 
In the `robot-server` project:
- run `OT_API_FF_useFastApi=TRUE make dev`
You should be able to visit `/docs` route on localhost.  This will allow you to review the swagger interactive docs. The two endpoints these changes affect are the placeholder endpoints `/items` and `/items/{item_id}`
Please add comments around any additions you would like to see, this is a first pass at solidifying some structure based on the JSON:API spec but we can change and add as we see fit.
Still todo:
> feat(robot-server): add formatted json responses and error handling

- labware-library/src/labware-creator/__tests__/loadAndSaveIntegration.test.js
- labware-library/src/labware-creator/labwareTestProtocol.js
The Custom Labware Creator generates a Python protocol to test the exported labware, but it only provides a few pipettes to pick from. 
This PR adds the rest of the single-channels. As far as I know, there's no reason for the test protocol *not* to support these pipettes. It was just never prioritized.
(People occasionally reach out to Support about this. We just edit the generated protocol and send them the modified file. So, if the rest of the pipettes *were* deliberately excluded, uh...)
Closes #4789.
* Added dropdown entries for GEN2 single-channels and the P50S GEN1.
* Replaced some code that dynamically generated human-readable pipette names from their API load names, and vice-versa, with a big dumb table. Generalizing the code to support the GEN2s would have made it unnecessarily …
> feat(labware-library): Support more pipettes in custom labware test protocol

- robot-server/robot_server/service/main.py
- robot-server/robot_server/service/models/control.py
- robot-server/robot_server/service/models/json_api/errors.py
- robot-server/robot_server/service/models/motors.py
- robot-server/robot_server/service/routers/control.py
- robot-server/robot_server/service/routers/motors.py
- robot-server/tests/service/routers/test_motors.py
Implement the `/motors` endpoints in robot-server's fastapi app
- separate the the motor models and routes from control into their own module
- port tests from aiohttp into fastapi. 
- separate the tests into smaller tests.
- implement the endpoints
The ticket is to port the endpoint and unit tests.
I do not have a robot to test this on, so not 100% it will work on a robot.
Very low. These changes all live behind a feature flag which is not enabled.
closes #5192
> refactor(robot-server): add /motors endpoints and tests

- protocol-designer/src/ui/steps/actions/actions.js
Closes #5247
The problem was that existing magnet steps were being treated the same as just-newly-created magnet steps. The desired behavior for just-newly-created steps 
- Ideas for tests? I thought about refactoring the `if (newStepType === 'magnet') {...} else if (formData?.stepType === 'magnet') {...}` into a function that could be tested on its own, but I'm not very motivated to put work into the pristine-never-saved form stuff since we're going to strip it out :/
PD only, shouldn't affect PRs in flight
> fix(protocol-designer): fix bug with selecting magnet > disengage step

- protocol-designer/src/step-forms/reducers/index.js
- protocol-designer/src/step-forms/test/reducers.test.js
Clear out `engageHeight` from MAGNET steps when magnetic module model is
edited.
Closes #5225
I also cover an unspecified case where if you have a form open (thus in `unsavedForm` reducer state) and edit a module, that open form will just close without changes instead of doing something smarter
Also, I figured EDIT_MODULES shouldn't affect magnet steps that somehow aren't using the same `moduleId` as the edited module.
* add tests for uncovered unsavedForm reducer
```js
{
type: 'EDIT_MODULE',
payload: {
id: "magnetic module ID here", 
model: "magneticModuleV2"
}
}
```
NOTE: you might notice that opening a Magnet > Disengage step shows "engage" being selected. That's not new in this PR, it's #5247 
Definitely PD-only, shouldn't interfere with other PD work unless it's specifically …
> feat(protocol-designer): clear out engageHeight

- protocol-designer/src/ui/modules/selectors.js
- shared-data/js/constants.js
- shared-data/js/getLabware.js
Closes #5226
* existing 3 labware defs should be output in real mm from labware bottom
- The 3 labware that use engageHeight should have their PD suggested defaults equal to `((original_number_in_def * 2) - 4) / 2`. For GEN2 magnetic module, the final `/ 2` shouldn't happen, for GEN1, it should.
For the 1 recommended magnetic module labware, `for nest_96_wellplate_100ul_pcr_full_skirt`, both default value and "Recommended: __" caption should be:
FYI, the math is:
```
20 short mm from def for nest_96_wellplate_100ul_pcr_full_skirt
= 10 real mm from switch
Do -4 real mm to translate "from switch" to "from labware bottom"
= 6 real mm
GEN2: 6 real mm
GEN1: 12 short mm (6*2)
```
Shouldn't interfere with anything outside on engageHeight use in PD. But it WILL mess up creating engage magnet …
> feat(shared-data): correct existing labware defs engageHeight

- protocol-designer/src/constants.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/steplist/formLevel/index.js
- protocol-designer/src/steplist/formLevel/warnings.js
Closes #5230
- Introduces `meta` field to HydratedFormData
Note: the existing "form hydration" stuff works on the fields `pipette` and `labware`. A raw/non-hydrated FormData will have `pipette: string` b/c it's the ID, then after being "hydrated" it will be HydratedFormData with `pipette: PipetteEntity`.
For 2 reasons, I want to start nesting the results of hydration in some field, I'm calling it `meta` but I'm open to other suggestions eg `context` or `hydrated` or whatever. This would be instead of the existing "form hydration" mechanism of converting the types of some certain fields
1. Much easier to type well once we finally get to typing FormData / HydratedFormData in #3161 (right now FormData is mostly any-typed and HydratedFormData is entirely any-typed, which has been causing …
> feat(protocol-designer): use different ranges for gen1 vs gen2 engageHeight

- protocol-designer/src/feature-flags/reducers.js
Serves as its own ticket. Allow E2E tests etc to set initial values of feature flags aka (experimental settings) via env vars.
- Note that if you've used PD before, this will only have an effect in an incognito tab (unless you clear out your localStorage) because only the INITIAL values are populated and persisted ones have precedence
- This is one approach to make E2E testing easier. Alternatively, we could set the localStorage state in Cypress directly, instead of setting up env vars to populate it
none?
> feat(protocol-designer): allow setting initial settings w env vars

- robot-server/robot_server/service/models/json_api/__init__.py
- robot-server/robot_server/service/models/json_api/factory.py
- robot-server/robot_server/service/models/json_api/request.py
- robot-server/robot_server/service/models/json_api/response.py
- robot-server/robot_server/service/routers/item.py
- robot-server/tests/service/helpers.py
- robot-server/tests/service/models/json_api/test_errors.py
- robot-server/tests/service/models/json_api/test_factory.py
- robot-server/tests/service/models/json_api/test_request.py
- robot-server/tests/service/models/json_api/test_response.py
fix `typing_extensions` bug by removing Literal type and subsequently the library
closes #5275
See here: https://github.com/Opentrons/opentrons/issues/5275
Introduced a bug when importing `Literal` type from `typing_extensions` which is only used in development. Python 3.8 supports `Literal` types, so we can revert changes at a later date.
> fix(robot-server): fix typing_extensions bug

- flow-typed/npm/formik_v2.x.x.js
- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/modals/FilePipettesModal/FilePipettesModal.css
- protocol-designer/src/components/modals/FilePipettesModal/ModuleFields.js
- protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/ModuleFields.test.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/PipetteFields.test.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/index.test.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/constants.js
- protocol-designer/src/step-forms/types.js
This PR closes #5150 and part of #5189 by enabling the model dropdown when creating a new protocol so users can select their model for their module.
- Use formik to handle the FilePipettesModal state and errors
- crash warnings only show up for gen 1 modules
- Added unit tests (was annoying to test the modal with formik, might be a good idea to refactor out the form so its easier to unit test)
The errors for the dropdowns are currently very ugly. After talking with Ian, we thought it would be a good idea to allow Dropdown components to accept a react node for error props instead of just a string since we use formik in multiple places and we could use the form error components to our advantage so we don't have to manage the errors ourselves - #5283 
Same goes for the flow typing for …
> feat(protocol-designer): allow selection of gen 2 modules and use formik

- api/src/opentrons/server/endpoints/control.py
- api/src/opentrons/system/camera.py
- robot-server/robot_server/service/routers/camera.py
- robot-server/tests/service/routers/test_camera.py
Implement camera endpoint in fastapi
- move ffmpeg call out of `server/endpoints/control.py` to `/system/camera.py`
- add ffmpeg command line for development on mac.
- use stderr to get results from ffmpeg. they ain't in stdout.
- use return code to determine failure/success of call to ffmpeg.
- implement post_take_picture in robot_server.
- add tests.
I tested this on my mac. I don't have a robot. Both the fastapi and aiohttp versions work.  Returning an image from my mac's camera. The fastapi UI renders the image.
Moderate. There's a change to the aiohttp handler.
closes #5223
> refactor(api,robot-server): Robot server port camera fast api

- api/src/opentrons/protocol_api/execute.py
- api/src/opentrons/protocol_api/protocol_context.py
if you give exec() separate locals and globals, it executes the provided
data as if embedded in a class definition which we very much do not want
- we want it to be executed as if in just a file, which of course it is.
This makes scoping work the same as it does when people write their
protocols and expect them to work.
While we're at it, call the argument we feed to the protocol's run
method something a little less likely to collide.
Closes #4982
Closes #4981
Should be minor - narrowly scoped change and easy to check since it happens in `opentrons_simulate`. 
This protocol:
```python
metadata = {"apiLevel": "2.1"}
deck_clearance = 0.5
calibration_cross_coordinates = [(x, y, deck_clearance) for x, y in [
(12.13, 9.0),
(380.87, 9.0),
(12.13, 348.5)
]]
def run(protocol): …
```
> fix(api): exec protocol contents in module mode

- api/src/opentrons/server/endpoints/calibration/check.py
- api/src/opentrons/server/endpoints/calibration/models.py
- api/src/opentrons/server/endpoints/calibration/session.py
- api/src/opentrons/server/http.py
- api/tests/opentrons/server/test_calibration_session.py
This PR refactors the POST request in the calibration check session flow. Previously, the POST request would return a status if a session had already been created. Now there is a GET request which returns that information.
- If a session already exists, the POST request will return a 409
- A GET request was added back in. If no session exists it will return a 404, otherwise it will return a 200 + the status.
HTTP structure look OK? Anything missing and/or should be removed?
- Ensure the behavior/status response structure still remains the same.
> refactor(api): Add in a GET request for calibration check session

- api/src/opentrons/system/log_control.py
- robot-server/robot_server/service/main.py
- robot-server/robot_server/service/models/logs.py
- robot-server/robot_server/service/models/settings.py
- robot-server/robot_server/service/routers/logs.py
- robot-server/robot_server/service/routers/settings.py
- robot-server/tests/service/routers/test_logs.py
- robot-server/tests/service/routers/test_settings.py
Implement the endpoints in `/endpoints/logs.py` in robot-server's fastapi app
closes #5142
- port endpoints/logs.py routes. logs model and routes file
- refactor route routes/settings
- port/added tests from aiohttp into fastapi
Very low. These changes all live behind a feature flag which is not enabled.
> refactor(robot-server): port log endpoints and add tests

- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/index.test.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
closes #5276 by fixing a bug where crash info box was rendering when module restrictions were disabled.
- fix(protocol-designer): Hide CrashInfoBox when module restrictions disabled
- refactor: Add test for hidden crash info box
Make sure module restrictions FF is OFF
Make a protocol with a Gen1 Multi and a magnetic module
Make sure module restrictions FF is ON
Make a protocol with a Gen1 Multi and a magnetic module
Low, should only affect PD new file modal, but please double check all crash info warnings render when they should in new file modal and file settings page.
> fix(protocol-designer): Hide CrashInfoBox when module restrictions disabled

- protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
closes #5188 by enabling the dropdown for model selection
- Migrate form to formik to handle errors and validation
- enable dropdown for model selection and handle slot select disabled depending on what model and flag is selected
- fix previous tests and added additional tests to cover new feature
Regression testing mostly to make sure nothing broke when moving to formik.
Make sure the disable module warnings flag is off.
**Editing/Adding module**
**Compatible labware**
Low - should only affect pd but the correct model for the modules should be in the json file when exported
> feat(protocol-designer): allow user to select module model when adding or editing modules

- protocol-designer/src/components/DeckSetup/DeckSetup.js
- protocol-designer/src/components/FileSidebar/FileSidebar.js
- protocol-designer/src/components/LabwareSelectionModal/index.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/components/modules/EditModulesCard.js
- protocol-designer/src/components/modules/ModuleRow.js
- protocol-designer/src/components/modules/__tests__/EditModulesCard.test.js
- protocol-designer/src/components/modules/__tests__/ModuleRow.test.js
- protocol-designer/src/file-data/selectors/fileCreator.js
- protocol-designer/src/step-forms/selectors/index.js
- protocol-designer/src/step-forms/utils.js
- protocol-designer/src/steplist/formLevel/errors.js
- protocol-designer/src/ui/labware/selectors.js
- protocol-designer/src/ui/modules/selectors.js
- protocol-designer/src/ui/modules/utils.js
We had a lot of `const module = ...` or `mapValues(modules, module => ...` etc, which is usually fine. But since `module` is a reserved word with a global Flow type, you can do things like `if (module)` or `return module.id` even if there is no `const module = ...` around. So if you're declaring a variable called `module` at the top of a fn and using it at the bottom, and then delete or change `module` at the top, you might not get linting errors about your missing variable.
This silly problem led me to get really confused for 15 mins working on a PR with `module`
This PR should be purely a refactor, changing uses of local `module` variables to something else like `moduleOnDeck` or `moduleEntity` etc.
I wish there was a linting rule where you can't assign `module` (or use it as an arg …
> fix(protocol-designer): rename 'module' variables to something else

- protocol-designer/src/components/DeckSetup/__tests__/ModuleTag.test.js
- protocol-designer/src/components/steplist/StepItem.css
- protocol-designer/src/localization/en/modules.json
Closes #5305 
See linked issue for screenshots + Zeplin link
just PD copy styling
> fix(protocol-designer): fix module substep text styling

- app/src/components/ModuleLiveStatusCards/ThermocyclerCard.js
- app/src/components/ModuleLiveStatusCards/styles.css
- app/src/robot/selectors.js
This PR fixes an alignment issue within the Thermocycler's run card cycle info.
The Time remaining should be on a new row beneath the cycle and step counts, but they were all scrunching together.
This also repairs a regression in formatting the time remaining, that was introduced in the shift away from moment in #5127 .  For instance, ten seconds remaining was displaying as 19:00:10 and it should correctly display as 00:00:10.
> fix(app): alignment in thermocycler card cycle info

- robot-server/robot_server/service/models/networking.py
- robot-server/robot_server/service/routers/networking.py
Bug fix in fastapi handling of `/network/status`
Added `unavailable` to `ConnectionState` enum. It is a valid state returned by nmcli.
None. Behind a feature flag
> fix(robot-server): unavailable is a valid network connection state

- protocol-designer/src/components/DeckSetup/DeckSetup.js
This PR closes #5309 by disabling deckmap slot warnings for GEN2 Modules only
- fix(protocol-designer): Only show slot access warnings for Gen1 modules
Make sure disable module restrictions FF is OFF
Make a protocol with GEN1 modules and a GEN1 8-Channel Pipette
Change the magnetic module to GEN2
Change the temperature module to GEN2
Slow. PD deckmap only
> fix(protocol-designer): Only show slot access warnings for Gen1 modules

- protocol-designer/src/components/FilePage.js
- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/components/StepEditForm/forms/PauseForm.js
- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/index.test.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/containers/ConnectedFilePage.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/load-file/actions.js
🥁 This closes #4968 by removing the enable modules in PD FF, and promoting disable module restrictions to a user facing experimental setting.
- feat(protocol-designer): Enable magnetic and temperature module support
Please really run this one to ground. 
Quadruple check:
Modules in PD only
> feat(protocol-designer): Enable magnetic and temperature module support

- protocol-designer/src/components/modals/EditModulesModal/MagneticModuleWarningModalContent.css
- protocol-designer/src/components/modals/EditModulesModal/MagneticModuleWarningModalContent.js
- protocol-designer/src/components/modals/EditModulesModal/__tests__/EditModulesModal.test.js
- protocol-designer/src/components/modals/EditModulesModal/index.js
- protocol-designer/src/localization/en/alert.json
- protocol-designer/src/tutorial/index.js
Closes #5251
Note that it's not specified in the ticket that the warning modal is a Blocking Hint. Confirmed w Morgan that it is.
- add blocking hint to edit modules modal, in the case that you're changing the model of an existing magnetic module
Be careful because even when you leave "Don't show me again" unchecked, PD won't show you the same blocking hint twice in the same session. By design, you have to refresh PD to see the hint a second time. (And if you do check "Don't show me again", you have to reset hints on the Settings page and also restart PD!)
just PD
> feat(protocol-designer): add warning modal switching mag model

- protocol-designer/src/components/DeckSetup/ModuleTag.js
- protocol-designer/src/components/DeckSetup/ModuleViz.js
Part of @dozercodes's work on E2E tests in PD, this makes 2 new data-attr selectors
- add `data-test` attrs w/ values `ModuleViz_{moduleType}` and `ModuleTag_{moduleType}` to ModuleViz & ModuleTag components respectively
- Flow type cleanup
just PD
> test(protocol-designer): add data-test attrs to ModuleTag and ModuleViz

- protocol-designer/cypress/integration/home.spec.js
- protocol-designer/cypress/integration/newProtocol.spec.js
- protocol-designer/cypress/integration/settings.spec.js
- protocol-designer/cypress/integration/sidebar.spec.js
- protocol-designer/cypress/support/commands.js
Adds a custom cypress command that can be used throughout all the PD cypress tests to close the announcement modal. This was already being done on some tests but needed to be done for all the tests. 
This is the first custom command, so any thoughts you have using this feature would be greatly appreciated. 
None, this only affects the E2E tests.
> fix(protocol-designer e2e): Add custom command to close the 3.17 announcement modal in E2E tests

- protocol-designer/src/components/FileSidebar/FileSidebar.js
- protocol-designer/src/components/KnowledgeBaseLink/index.js
- protocol-designer/src/localization/en/alert.json
This PR closes #5335 by updating the copy for the export v4 json protocol announcement modal. Note, the support link doesn't work yet.
Make sure the modal matches what's on the ticket
Low- just updating modal text
> feat(protocol-designer): update export v4 protocol modal copy

- protocol-designer/src/components/modals/FilePipettesModal/__tests__/PipetteFields.test.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
This PR closes #5336  by removing the visible FF toggle from experimental settings for GEN2 multi channel pipette usage. (The work to enable gen2 by default was already in place)
- feat(protocol-designer): Remove multi gen2 feature flag
Low PD multi GEN2 only
> feat(protocol-designer): Remove multi gen2 feature flag

- components/package.json
- components/src/instrument/InstrumentDiagram.md
- components/src/styles/colors.js
- components/src/styles/typography.js
- components/src/tooltips/DeprecatedTooltip.js
- components/src/tooltips/DeprecatedTooltip.md
- components/src/tooltips/HoverTooltip.js
- components/src/tooltips/Tooltip.js
- components/src/tooltips/Tooltip.md
- components/src/tooltips/__tests__/Tooltip.test.js
- components/src/tooltips/__tests__/usePopper.test.js
- components/src/tooltips/__tests__/useTooltip.test.js
- components/src/tooltips/constants.js
- components/src/tooltips/index.js
- components/src/tooltips/styles.js
- components/src/tooltips/types.js
- components/src/tooltips/usePopper.js
- components/src/tooltips/useTooltip.js
- labware-library/src/components/labware-ui/LoadName.js
- yarn.lock
This PR closes #5120 by adding a `useTooltip` hook + `<Tooltip>` component pair to the component library. At the moment, this component is standalone and not used anywhere except the styleguide examples.
Future PRs will be needed to:
- Add hover functionality via a `useHover` and `useHoverTooltip` hook (#5364)
- Rewrite the internals of `HoverTooltip` to use the hooks
- Gradually replace usage of `HoverTooltip` with either:
- Direct hook usage
- More considered CL components that can take a disabled reason for a tooltip rather than simply disabling themselves 
- feat(components): add hooks-based tooltip component to library
- Note: renamed existing `Tooltip` component to `DeprecatedTooltip`
- It still uses the old `react-popper` tooltip but that component was renamed
Very low. New tooltip …
> feat(components): add hooks-based tooltip component to library

- protocol-designer/src/step-generation/__tests__/modulePipetteCollision.test.js
- protocol-designer/src/step-generation/utils/_getFeatureFlag.js
- protocol-designer/src/step-generation/utils/modulePipetteCollision.js
> feat(protocol-designer): allow GEN1 multi pipette access N/S of GEN2 modules

- protocol-designer/src/components/alerts/TimelineAlerts.js
Serves as its own ticket. @Kadee80 noticed that the PIPETTE_VOLUME_EXCEEDED error (which has no i18n entry, intended to default to the `step-generation` error copy) doesn't display the copy correctly:
- use step-generation timeline error copy if no i18n entry exists
- `Attempted to ${actionName} volume greater than pipette max volume (${volume} > ${maxVolume})`
- Or, if using disposal volume: `Attemped to ${actionName} volume + disposal volume greater than pipette max volume (${volume} + ${disposalVolume} > ${maxVolume})`
low
just PD
> fix(protocol-designer): default to non-i18n step-gen errors if no i18n copy

- protocol-designer/webpack.config.js
Closes #5148
Just bumps the version
- Tests pass
- I can't think of anything that could be bad about this now :p Both #5371 and #5123 are dependent on this
none, just PD
> chore(protocol-designer): update PD version constant to 4.0.0

- protocol-designer/src/components/DeckSetup/LabwareOverlays/DragPreview.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/EditLabware.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/SlotControls.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/__tests__/SlotControls.test.js
- protocol-designer/src/components/DeckSetup/LabwareOverlays/constants.js
- protocol-designer/src/components/steplist/DraggableStepItems.js
- protocol-designer/src/constants.js
Closes #5367 
I think this bug is: in any loaded protocol, reordering the steps caused a whitescreen because SlotControlsComponent receives the STEP_ITEM itemType and attempted to access a key that isn't there, because it's expecting a LABWARE itemType that has different keys. (For some reason a newly-created protocol works fine -- race condition?)
- consolidate DND_TYPES as in old TODOs
- make slot overlay check if indeed there's a labware being dragged, (and not a STEP_ITEM or something else)
I think 5367 was a latent bug that until recently wasn't able to surface due to some kind of race condition?? Not sure what could have made it surface.
- New protocol, reorder steps: should work as expected
- Loaded protocol, reorder steps: should work as expected
- Dragging labware: should work as …
> fix(protocol-designer): fix dnd bug

- protocol-designer/src/components/modals/AnnouncementModal/announcements.js
This PR closes #5334 by updating the copy for the intro announcement modal. Note, the support link doesn't work yet.
Make sure the modal matches what's on the ticket
Low- just updating modal text
> feat(protocol-designer): update intro announcement modal copy

- app/src/robot/selectors.js
Both #5322 and #5319 touched `app/src/robot/selectors.js` and merging both created a bug due to one of those PRs changing `import { ... PIPETTE_MOUNTS ... } from './constants'` to `import * as Constants from './constants'`
This PR corrects that merge bug to get tests passing and builds working
- refactor(app): fix error caused by two refactors touching robot selectors
Nothing specific since it's a one line fix. Make sure tests pass on your machine if you're feeling thorough
Very low. Bug was caused by merge and caught by tests.
> refactor(app): fix error caused by two refactors touching robot selectors

- protocol-designer/src/components/DeckSetup/LabwareOverlays/SlotControls.js
That was dumb. Introduced bug in #5370 where you couldn't add labware to slots. This is b/c `itemType` is `null` when nothing is actively being dragged. Instead of rendering the slot controls, SlotControlsComponent returned null when nothing was being dragged
:upside_down_face: 
low, PD only
> fix(protocol-designer): allow adding labware

- protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.js
- protocol-designer/src/steplist/fieldLevel/errors.js
- protocol-designer/src/steplist/fieldLevel/index.js
- protocol-designer/src/steplist/fieldLevel/processing.js
- protocol-designer/src/steplist/fieldLevel/test/processing.test.js
This PR closes #5274 by adding field level validation for magnetic module engage height text input. 
Along the way, I also refactored the `maskToFloat` input masker to just mask to float, and added an additional masker to trim decimals (previously `maskToFloat` was doing both) 
refactor `maskToFloat` to just mask to float
change signature for `maskToInt`
add 'trimDecimals' masker
add field level validation for magnetic module engage height
- code review 
- make sure you **CANNOT** submit non-numbered values into the `engage height` field
Because of the refactor I did, the following fields were affected, but shouldn't have changed. The expected behavior is that they should mask floats, and only allow one decimal place:
1. liquid placement form volume (when adding liquids to protocol)
2. …
> fix(protocol-designer): add field level validation for magnetic module engage height

- robot-server/robot_server/service/main.py
- robot-server/tests/service/routers/test_item.py
- robot-server/tests/service/test_main.py
Closes #5285
To keep compatibility with APIv1, this PR makes fastAPI exception handlers return errors in API v1 style (i.e. in {'message': 'error_string' } format)
Helper functions for API v2 error formatting are left untouched for future use.
- Added reformatting of errors to `/service/main.py`
- Added new tests: `/tests/service/test-main.py`
- Updated test in `/service/routers/test_item.py`
- Does the code look good?
- Check if you get expected responses to requests
- Does this need more tests? 
Low- Impacts only error responses
> feat(robot-server): make fastapi return v1 style errors

- components/src/buttons/Button.js
- components/src/tooltips/types.js
- protocol-designer/src/components/StepCreationButton.js
- protocol-designer/src/components/listButtons.css
closes #5386 by refactoring the tooltips from the older deprecated tooltip with Mikes shiny new one! By doing so we fixed a lot of styling issued that arose.
- refactor(protocol-designer): Use new complib tooltip component
- refactor(components): Update types in Buttons.js so that it works with refs/new tooltips properly
Low? This is implementing the new tooltip in one spot in PD and should NOT affect older instances anywhere.
> refactor(protocol-designer): Use new complib tooltip component

- protocol-designer/src/components/steplist/PauseStepItems.js
- protocol-designer/src/components/steplist/StepItem.css
This PR closes #5387 by unifying the pause step item content spacing.
- fix(protocol-designer): Unify pause step item spacing
Make all 3 variations of pause steps with and without messages to display
Low, CSS in PD only
> fix(protocol-designer): Unify pause step item spacing

- protocol-designer/src/components/modals/EditModulesModal/index.js
Closes #5385
- Disabling the "Slot" dropdown in EditModuleModal should show the tooltip
- Enabling it (either by selecting GEN2 or by turning on Disable Module Restrictions setting) should hide the tooltip
- Modal form still works the same
low, only PD
> feat(protocol-designer): hide tooltip when slot dropdown enabled

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/pipette_config.py
- api/src/opentrons/config/reset.py
- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/cli/test_cli.py
- api/tests/opentrons/config/test_advanced_settings.py
- api/tests/opentrons/config/test_pipette_config.py
- api/tests/opentrons/config/test_reset.py
- api/tests/opentrons/conftest.py
- api/tests/opentrons/server/test_settings_endpoints.py
- robot-server/robot_server/service/models/settings.py
- robot-server/robot_server/service/routers/settings.py
- robot-server/tests/service/routers/test_settings.py
These endpoints are implemented in fastapi:
`GET /settings/robot`
`GET /settings/pipettes`
`GET /settings/pipettes/{pipette_id}`
`PATCH /settings/pipettes/{pipette_id}`
`POST /settings/reset`
`GET /settings/reset/options`
`POST /settings/log_level/local`
`GET /settings`
`POST /settings`
To do this I moved a lot of logic from `opentrons.server.endpoints.settings` into other modules.
- The model of pipette config spells out exact field names.
- Refactor `opentrons.server.endpoints.settings`: 
- Move reset logic to it's own module in `opentrons.config`
- Move pipette config override logic out of handler and into `opentrons.config.pipette_config`
- Refactor `opentrons.config.advanced_settings`:
- Make Setting object a namedtuple of SettingDefinition (what used to be Setting) and the value. A …
> refactor(robot-server): robot server port settings to fastapi

- api/src/opentrons/hardware_control/modules/magdeck.py
In
https://github.com/Opentrons/opentrons/pull/5330/ (f1cfb967c18fd2f43ea962cddc86e10e95e1d9f3)
we added per-model offsets for the height from base command for
magdecks. Previously, this value had been set to 5. The PR incorrectly
uses 5mm true for gen2s, and doubles it for the incorrect units for
gen1. Instead, what we need to do is use 5 (bad) mm for gen1, and 2.5 mm
true for gen2.
This one is a bit tough to test. The easiest way is to connect the magnetic module to your computer, command the offsets (`G0Z5` on a gen1, `G0Z2.5` on a gen2 with proper firmware) and use a straightedge of some kind to check that the magnets are _roughly_ level with the labware engage plane. Keep in mind that it may not (will not) be exact because of piece-to-piece variance.
It's less important to test this …
> fix(api): correctly set magdeck offsets

- api/src/opentrons/__init__.py
- api/src/opentrons/legacy_api/__init__.py
One of the most important parts of supporting APIv1 is continuing to
support direct execution of protocols as scripts, protocols that look
like this:
from opentrons import robot
robot.connect()
That means that the robot singleton has to be either created in the
package init, or has to be available by normal import means through
opentrons.robot. We don't want the second because we want to sequester
apiv1 in its own little subdirectory, so we went with the first. The
problem with the first, though, is that you have to build the singleton
on any import of anything inside the opentrons package, and that's
really slow especially on a raspberry pi.
However, python 3.7 includes
[pep-562](https://www.python.org/dev/peps/pep-0562/), which allows for a
__getattr__ at module scope that behaves like …
> refactor(api): load v1 singletons lazily

- robot-server/robot_server/service/main.py
- robot-server/robot_server/service/routers/__init__.py
- robot-server/tests/service/routers/test_item.py
Fastapi exception handling middleware is applied to the entire application. We want legacy v1 endpoints to return errors with the format `{"message": "error string"}` while future v2 endpoints return a more complete JSON API inspired schema.
This means the middleware handling http and validation errors needs to know how to format the response.
The approach is to use an Openapi tag (`v1`) for legacy API. This has the benefit of labeling these endpoints as legacy in docs. 
- Put all v1 routers into a single router.
- Add those routes with a `v1` tag.
- Add function to find whether tag exists on request endpoint. 
Is this a reasonable approach to distinguishing v1 endpoints?  Is it too hacky?
Alternatives could be:
- a custom router that attaches a field to the `state` variable of a request. …
> feat(robot-server): return correct error format based on endpoint

- labware-library/cypress/fixtures/TestLabwareProtocol.py
- labware-library/cypress/integration/labware-creator/fileImport.spec.js
- labware-library/cypress/plugins/index.js
- labware-library/src/labware-creator/index.js
- package.json
- protocol-designer/cypress/integration/migrations.spec.js
- protocol-designer/cypress/plugins/index.js
- shared-data/js/cypressUtils.js
- yarn.lock
Closes #5103 and adds e2e load-save testing to Labware Creator, ensuring that LC transforms a labware definition into fields and then into a zip in exactly the same way
- add e2e test for labware creator - confirm loading a labware definition fixture, selecting a pipette, and saving the zip gives you a zip with a matching labware definition and a python test protocol that matches a fixture
low, just LL. Again like for the PD E2E file load-save tests, the riskiest thing is that if somehow `window.Cypress` exists in production, downloaded files would be disabled. When we make E2E tests run in CI and edit the Makefiles, we can replace this with an env var.
> test(labware-library): add load-save e2e test for labware creator

- protocol-designer/cypress/integration/newProtocol.spec.js
- protocol-designer/cypress/integration/newProtocolWithModules.spec.js
- protocol-designer/cypress/integration/settings.spec.js
- protocol-designer/cypress/support/commands.js
This PR closes #5321 by adding E2E tests for Modules in PD. This PR leans heavily on @Kadee80's Modules in PD [testing script](https://coda.io/d/PD-Testing-Script-Happy-Path_dCWXIDxlcsE/PD-Modules-Testing-Script_suaLi?loginToken=eyJjc3JmVG9rZW4iOiJLSmNYUjlCMWs4RFZDNkRDIiwiZXhwaXJ5TXNlYyI6MTU4NTg2NTMxMzc4M30#_luQlu) for direction. The bulk of this PR is a long protocol test that creates a new protocol test with pipettes, modules, liquids, and various steps. Note, there are quite a few unsavory selector in these tests, and I will be a compiling a list of elements which will need better selectors that we can add over time. 
Added tests:
- Toggle on/off "Disable module placement restriction" experimental setting
- Create a protocol file with modules
- Add liquids
- Add labware to deck and …
> test(protocol-designer): Add modules in PD E2E tests 

- protocol-designer/src/components/modals/EditPipettesModal/index.js
- protocol-designer/src/components/modals/FilePipettesModal/FilePipettesModal.css
- protocol-designer/src/components/modals/FilePipettesModal/PipetteDiagram.js
- protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/PipetteFields.test.js
- protocol-designer/src/components/modals/FilePipettesModal/__tests__/index.test.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
- protocol-designer/src/components/modals/NewFileModal/index.js
- protocol-designer/src/feature-flags/reducers.js
- protocol-designer/src/feature-flags/selectors.js
- protocol-designer/src/feature-flags/types.js
- protocol-designer/src/localization/en/feature_flags.json
This PR closes #5332 by adding a custom tiprack FF and conditionally rendering the new UI when the FF is turned on.
- feat(protocol-designer): Implement custom tiprack UI behind flag
This was a little whacky cause the layouts were very conditional, there is a little bit of component work that will be torn down once the Flag is removed and this is a full feature, but it was necessary to conditionally render both old and new layouts properly.
Low. PD only behind a FF.
> feat(protocol-designer): Implement custom tiprack UI behind flag

- robot-server/robot_server/__init__.py
- robot-server/robot_server/constants.py
- robot-server/robot_server/service/app.py
- robot-server/robot_server/service/errors.py
- robot-server/robot_server/service/exceptions.py
- robot-server/robot_server/service/models/json_api/errors.py
- robot-server/robot_server/service/routers/control.py
- robot-server/robot_server/service/routers/deck_calibration.py
- robot-server/robot_server/service/routers/modules.py
- robot-server/robot_server/service/routers/motors.py
- robot-server/robot_server/service/routers/networking.py
- robot-server/robot_server/service/routers/settings.py
- robot-server/tests/service/models/json_api/test_errors.py
- robot-server/tests/service/test_app.py
- robot-server/tests/service/test_errors.py
Add API version header to responses.
Define an api version. This is an integer starting at 1.
Middleware that examines the `opentrons-version` header in request.  The api version used to respond to the request is chosen in this manner: 
- if the request version is an integer and <= server api version, we use that version
- otherwise we use the server version.
The chosen version is attached to the request.state object for consumption by handlers.
Finally, the response will contain `opentrons-version` that holds the version used to handle the request.
Rename `exceptions.py` to `errors.py` and put error related helpers in there.
None
closes #4633
> feat(robot-server): create middleware to support api versioning

- protocol-designer/src/components/modals/FilePipettesModal/ModuleFields.js
- protocol-designer/src/components/modals/FilePipettesModal/index.js
This PR closes #5389 by defaulting the model dropdown for TC only to GEN1.
- fix(protocol-designer): Default to GEN1 model for TC
http://sandbox.designer.opentrons.com/pd_autoselect-tc-gen1/
Make a protocol with all 3 modules. 
Check and uncheck each module (add remove then re-add to deck)
Export a protocol with a TC
Export a protocol without a TC
Low, PD single form field.
> fix(protocol-designer): Default to GEN1 model for TC

- robot-server/Config.in
- robot-server/Pipfile
- robot-server/Pipfile.lock
- robot-server/robot_server/service/routers/settings.py
- robot-server/tests/service/rpc/test_server.py
- Upgrade package version
- Identify dependencies accurately in `Config.in`
Remove workarounds related to old bugs in fastapi.
I've tested on my rPI
None
> chore(robot-server): upgrade fastapi to 0.54.1

- robot-server/Makefile
- update-server/Makefile
Change the makefiles to also copy over systemd unitfiles for our
monorepo-based units, which prevents having to install new buildroot
builds when we change the unitfiles
Do a `make push` on this branch and it should work.
> chore(robot-server,update-server): push systemd units

- .travis.yml
- labware-library/Makefile
- labware-library/cypress.json
- labware-library/src/index.hbs
- labware-library/webpack.config.js
- package.json
- protocol-designer/Makefile
- protocol-designer/cypress.json
- protocol-designer/src/components/FileSidebar/FileSidebar.js
- protocol-designer/webpack.config.js
- yarn.lock
Run cypress tests in Travis! Build will fail if any e2e tests fail. Closes #5318 
This is dependent on #5424 - after it is merged, I'll rebase this PR and change `if (global.Cypress)` in that PR to `if (process.env.CYPRESS === '1')`.
Sanity check!
- One weird thing I encountered was that labware library tests failed in Travis because GTM_ID env var was set, which somehow caused an error to be thrown about Intercom being undefined. So I set `GTM_ID=''` and also just to be safe I cut out the GTM tag from the Handlebars HTML template if GTM_ID is falsey.
- I'm using `wait-until` to make sure that the dev server is running before trying to start Cypress
- Cypress by default saves videos. I don't think they're useful to us, so I turned them off. We can always enable them and upload them to S3 …
> ci(travis): run cypress e2e tests on build

- protocol-designer/src/components/StepEditForm/fields/TipPositionField/index.js
- protocol-designer/src/components/StepEditForm/fields/WellOrderField/index.js
This PR is the first of many that addresses #5411. This PR refactors `WellOrderField` and `TipPositionField`
- refactor(protocol-designer): Convert class based components to functional ones with hooks
- refactor(protocol-designer): Use new tooltip component in WellOrder and TipPosition 
- Double check the WellOrder, TipPosition, and TipPosition (after you check off touch tip) fields in TRANSFER step advanced settings for both aspirate and dispense.
- Double check the WellOrder, TipPosition, and TipPosition (after you check off touch tip) fields in MIX step advanced settings for both aspirate and dispense.
Low, just a couple tooltip refactors. Just make sure they all work!
> refactor(protocol-designer): Use new tooltip component in WellOrder and TipPosition 

- protocol-designer/src/components/steplist/AspirateDispenseHeader.js
- protocol-designer/src/components/steplist/MixHeader.js
- protocol-designer/src/components/steplist/ModuleStepItems.js
This PR addresses #5411 by replacing the old HoverTooltips with the shine new tooltip for labware names in the `AspirateDispenseHeader` `MixHeader` and `ModuleStepItems`. The next PR will handle the `IngredPill` and `SubstepRow` refactor. 
- refactor(protocol-designer): Update tooltip component in substep headers
Make a protocol with a Transfer, Mix, and  MagnetStep (make sure there's a labware on the magnetic module)
PS - this rips out the Portal part of the old tooltip, placement is _slightly_ different than on edge for the destination labware tooltips, but this is because we are using popper.js built in placement arguments instead of getting crazy with custom styles and a Portal.
Low, just PD tooltips.
> refactor(protocol-designer): Update tooltip component in substep headers

- protocol-designer/src/components/FileSidebar/FileSidebar.js
- protocol-designer/src/components/modals/AnnouncementModal/announcements.js
- protocol-designer/src/localization/en/alert.json
This PR serves as its own ticket, it removes references to beta in the announcement and V4 export text.
- refactor(protocol-designer): Update announcement and export modal text
http://sandbox.designer.opentrons.com/pd_update-announements-remove-beta-wording/
- Open up this branch in an incognito window so you can see the modules announcement modal
- Make a protocol with a module and export it to view V4 export modal
Low just text in PD
> refactor(protocol-designer): Update announcement and export modal text

- protocol-designer/src/components/StepEditForm/fields/ChangeTipField/ChangeTip.js
This PR also addresses #5411 by updating the tooltip logic for the dropdown options in the change tip field. 
This PR however does NOT touch the parent component which is the `ChangeTip` field itself. This is due to the fact that it uses `FieldConnector` and that refactor will require simultaneously updating 10 components to ensure nothing breaks. Saving that fun for last.
- refactor(protocol-designer): Update tooltip for ChangeTipOptionLabel
- Make a protocol with a transfer
- Hover over change tip label
- Click the dropdown and hover over each option
Low. PD single tooltip instance.
> refactor(protocol-designer): Update tooltip for ChangeTipOptionLabel

- api/src/opentrons/hardware_control/api.py
If a delay appears after a pause in a protocol and there is no actual robot or module command to await the execution manager between them, the delay will capture the current pause and resume automatically when its timer has elapsed. This change makes the delay function await the execution manager to keep this edge case from occurring.
Closes #4801
> fix(api): make delay wait for existing pause before pausing itself

- app-shell/Makefile
- app-shell/__mocks__/usb-detection.js
- app-shell/electron-builder.config.js
- app-shell/package.json
- app-shell/src/main.js
- app-shell/src/system-info/__tests__/usb-devices.test.js
- app-shell/src/system-info/index.js
- app-shell/src/system-info/usb-devices.js
- appveyor.yml
- package.json
- scripts/setup-global-mocks.js
- shared-data/package.json
- webpack-config/lib/node-base-config.js
- yarn.lock
The library that we use to build our production Electron app (`electron-builder`) has had a history of selecting incorrect dependencies from the `yarn` workspace for inclusion in the production bundle. This has caused issues in the past (see #3920) and will continue to cause issues if not fixed (see #5537).
A quick audit of the app-shell's spec'd dependencies vs what's actually in the bundle was [fairly alarming](https://github.com/Opentrons/opentrons/issues/5537#issuecomment-622464608).
This PR disables hoisting for `app-shell` dependencies, so that all app-shell production dependencies end up installed in `app-shell/node_modules`. This appears to be enough to get `electron-builder` selecting the correct dependencies.
On top of the hoisting issue, the app's devtools were running into + …
> fix(app-shell): upgrade Electron, avoid hoisting dependencies, and fix devtools

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/server/endpoints/settings.py
- api/tests/opentrons/config/test_advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
- robot-server/robot_server/service/routers/settings.py
- robot-server/tests/service/routers/test_settings.py
Changes the default http handling from the aiohttp app in opentrons to the fastapi one in robot-server.
- remove `useFastApi` in favor of `useV1HttpApi`
- Is it right to just remove `useFastApi` feature flag? 
Super duper high! This is a total re-implementation of the http api processing.
closes #5510
> feat(robot-server,api): change useFastApi to useV1HttpApi

- .travis.yml
#5482 added `libudev` to the TravisCI build dependencies for JS projects. Turns out the reason we need this dependency to get CI to pass was because the prebuilt binary download step (where  binaries for `usb-detection` on the given OS were downloaded) wasn't set up correctly.
#5545 fixed the broken prebuild step, so the `libudev` dependency is no longer needed. This PR removes it from the Travis config.
- ci(travis): remove unnecessary libudev build dependency
Low if CI is green. `libudev` is not used by the Travis config because prebuilt binaries for `usb-detection` are downloaded. If the dependency was needed to build usb-detection, this PR would fail CI
> ci(travis): remove unnecessary libudev build dependency

- app/src/components/Alerts/U2EDriverOutdatedAlert.js
- app/src/components/Alerts/__tests__/U2EDriverOutdatedAlert.test.js
- app/src/config/constants.js
- app/src/config/types.js
- app/src/nav/__tests__/selectors.test.js
- app/src/nav/selectors.js
- app/src/pages/More/NetworkAndSystem.js
- app/src/pages/More/__tests__/NetworkAndSystem.test.js
- app/src/system-info/constants.js
This PR removes the `enableSystemInfo` feature flag to release the guarded U2E driver update notification functionality to users.
Closes #5493. See ticket for screenshots and GIF recordings made prior to the tweaks listed below:
Besides removing the feature flag, this PR makes requested UX and product tweaks:
- Clicking "Get Update" in the warning modal will **not** redirect the user to the System Info car
- Modal and card warning CTA made slightly more forceful:
> Please update your computer’s driver to ensure a reliable connection to your OT-2.
There are various flows and facets in this user experience related to dismissing the alert vs. dismissing the alert permanently, the range of driver versions that can trigger this alert, and analytics collected. Care was taken to make sure those …
> feat(app): alert user if Windows U2E driver is out of date

- app/src/components/SystemInfoCard/U2EAdapterInfo.js
- app/src/components/SystemInfoCard/U2EDeviceDetails.js
- components/src/primitives/Box.js
- components/src/primitives/Box.md
- components/src/primitives/Flex.js
- components/src/primitives/Link.js
- components/src/primitives/Text.js
- components/src/primitives/__tests__/Box.test.js
- components/src/primitives/__tests__/Flex.test.js
- components/src/primitives/__tests__/Link.test.js
- components/src/primitives/__tests__/Text.test.js
- components/src/primitives/__tests__/style-props.test.js
- components/src/primitives/index.js
- components/src/primitives/style-props.js
- components/src/structure/Card.js
- components/src/styles/spacing.js
- components/src/styles/typography.js
Palate cleanser PR for myself after the U2E project is officially dev complete. This PR follows up on #5637 by:
- Adding a `<Box>` primitive to the library
- Just a `<div>` with styling props to reduce CSS repetition
- Adding spacing props to the primitive components
- They allow you to set `margin` and `padding`
- They inlcude very handy `marginX`, `marginY`, `paddingX`, and `paddingY` props to set left/right or top/bottom simultaneously
- Also added a simple set of [power-of-two space scale](https://styled-system.com/guides/why-powers-of-two/) constants - the props don't require using the constants, though; they'll take whatever string or number you give them
- They also make it very easy to ensure that only parent components deal with margins, which makes child components easier to …
> feat(components): add Box primitive to components library

- robot-server/robot_server/service/models/modules.py
- robot-server/tests/service/routers/test_modules.py
The live_data was not being returned properly. The unit tests were woefully incomplete. 
The root cause is that the live data is modeled as a Union of the three module live_data types. It is crucial that unions be sorted in order of specific-ness.  
Changed union order and filled out the unit tests
Low. It's a bug fix.
> fix(robot-server): /modules was not returning the right module specific data

- app/src/analytics/__tests__/selectors.test.js
- app/src/analytics/selectors.js
- app/src/analytics/types.js
This PR attaches pipette and module names to the existing protocol analytics event data
Closes #5540
- feat(app): collect pipette and module load analytics from protocol runs
Low. Small, unit-tested addition to existing data collection selector
> feat(app): collect pipette and module load analytics from protocol runs

- .travis.yml
- appveyor.yml
Our CI configs weren't updated with our dev/prod environment upgrade to Python 3.7. This PR updates the Travis and AppVeyor configs to use Python 3.7 instead of 3.6
- ci: use Python 3.7 in CI
Low if CI is green. Even with Python 3.6 in the CI configs, pipenv was still grabbing Python 3.7 to create its vitrual environments, so this change doesn't really do much except communicate developer intent a little more clearly
> ci: use Python 3.7 in CI

- app/src/analytics/make-event.js
- app/src/support/profile.js
- app/src/system-info/__fixtures__/index.js
- app/src/system-info/__tests__/utils.test.js
- app/src/system-info/selectors.js
- app/src/system-info/utils.js
As [was pointed out](https://github.com/Opentrons/opentrons/pull/5482#discussion_r414586903) in the PR that added USB device collection to the app, our filter for determining if a given device was a Realtek U2E adapter consisted of asking "Does this device report that its manufacturer is the string 'Realtek'?" This proved to be insufficient pretty quickly, because Realtek makes devices that are not U2E adapters.
This PR tightens the filter to check:
- Does the Vendor ID of the USB device match Realteks's registered VID?
- Is the Product ID close to the registered PID of an `RTL8150`
- Note: in real world testing + collected analytics, our devices report a PID that is _slightly off_ from what is expected (expected: `0x8150`, actual: `0x8050`)
- Hence, "close to" rather than exact match
- …
> fix(app): tighten filter logic that identifies Realtek U2E adapters

- api/src/opentrons/config/advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings.py
Advanced settings are read way more often than written. Each call to get_adv_setting loads the json file to extract the setting. 
- Wrapped `get_all_adv_settings` with `lru_cache` decorator. The cache is invalidated when `set_adv_setting` succeedes.
- Tests to prove it works.
High risk. Advanced settings are important.
> feat(api): use lru_cache on get_all_adv_settings

- api/src/opentrons/types.py
- api/tests/opentrons/test_types.py
Adds multiplication operator(s) to types.Point wrt to floats or ints.
This allows scaling an offset by a fixed amount, making it easy to combine e.g. a direction vector and a distance.
Previously:
```types.Point(1,2,3) * 2 => (1, 2, 3, 1, 2, 3)```
Feel totally free to reject this e.g. if Points are not meant to be used for offset vectors. I couldn't find tests for this but feel free to point me (NPI) to them and I can add one.
Added mul and rmul operators.
Changes a fundamental type, but seems very unlikely this operator is invoked anywhere at present except accidentally?
> feat(api): add multiplication operator(s) to types.Point

- robot-server/robot_server/service/app.py
We're not using the default pydantic/fastapi validation error responses. We have our own error format.
Add directive to openapi spec generator about the type of the pydantic/fastapi validation errors. 
None. Only impacts openapi spec and docs.
> fix(robot-server): make sure fastapi validation errors are properly documented

- scripts/push.mk
- update-server/Makefile
This didn't quite work for a couple reasons:
- needed to fix some things specifically in the update-server package
- push-systemd-unit needs to remount the filesystem
Testing:
- `make push` from top level
- `make push` in each of `api`, `robot-server`, `update-server`
All should complete with no failures
> fix: fix makefile refactor for push tasks

- Config.in
- Makefile
- api/Makefile
- api/Pipfile
- api/Pipfile.lock
- api/setup.py
- external.mk
- robot-server/Pipfile
- robot-server/Pipfile.lock
- robot-server/robot_server/service/rpc/rpc.py
- scripts/python_build_utils.py
- shared-data/Makefile
- shared-data/python/Config.in
- shared-data/python/Pipfile
- shared-data/python/Pipfile.lock
- shared-data/python/buildroot.mk
- shared-data/python/opentrons_shared_data/__init__.py
- shared-data/python/setup.cfg
- shared-data/python/setup.py
This adds the skeleton of python bindings for shared-data actually
resident in shared-data, like the js bindings. This is the prequel to
moving direct shared data handling to these bindings and adding a lot of
type definitions.
This package will be eventually published to pypi and installed as a dependency when users install the wheel.
You'll have to re-run make install-py.
https://github.com/Opentrons/buildroot/pull/88 will put this in buildroot builds
Does this uh seem like a good idea? Does it seem like the right structure? Does the dev workflow work?
None, no changes to actual code
> refactor(shared-data): add python bindings skeleton

- app-shell/src/system-info/__tests__/dispatch.test.js
- app-shell/src/system-info/__tests__/network-interfaces.test.js
- app-shell/src/system-info/index.js
- app-shell/src/system-info/network-interfaces.js
- app/src/analytics/__tests__/system-info-events.test.js
- app/src/analytics/make-event.js
- app/src/components/SystemInfoCard/U2EAdapterInfo.js
- app/src/components/SystemInfoCard/U2EDeviceDetails.js
- app/src/components/SystemInfoCard/__tests__/U2EAdapterInfo.test.js
- app/src/support/__tests__/system-info-profile.test.js
- app/src/support/profile.js
- app/src/system-info/__fixtures__/index.js
- app/src/system-info/__tests__/actions.test.js
- app/src/system-info/__tests__/reducer.test.js
- app/src/system-info/__tests__/selectors.test.js
- app/src/system-info/actions.js
- app/src/system-info/constants.js
- app/src/system-info/reducer.js
- app/src/system-info/selectors.js
- app/src/system-info/types.js
- app/src/system-info/utils.js
This PR adds simple network interface information collection to the app. The app-shell polls the OS for its active network interfaces (default 30 second poll) and places the list of active interfaces in state. If it recognizes that the MAC address of any of those active interfaces match the serial number of any U2E devices also in state, it will add the IP address to the UI, as well as the support profile and the analytics profile (for analytics, it will be anonymized to a boolean for "is there an IPv4 assigned?")
Closes #5397. See ticket for acceptance criteria.
- feat(app): add network interface collection to system-info
1. Open your app
2. Connect a robot with the robot turned off
3. You should see the device show up **without** a "Network Interface" in the "Networking & System" page …
> feat(app): add network interface collection to system-info

- api/src/opentrons/commands/commands.py
- api/tests/opentrons/commands/test_commands.py
[too_many_seconds.json.zip](https://github.com/Opentrons/opentrons/files/4704262/too_many_seconds.json.zip)
This PR closes #5414. JSON protocols export delay duration in seconds (even with large durations), so when the commands get published to the run log, the formatting is funny. 
This PR normalizes delay duration to the format we'd expect (seconds > 60 carry over to minutes)
- Add unit test coverage for delay command
- Normalize delay duration
Make sure the tests look okay
Run a JSON protocol with seconds > 60 and make sure the run log converts the time correctly. For example, a delay duration of 0 minutes and 100 seconds should be converted to 1 minute and 40 seconds.
I attached a sample protocol to use to this PR
Low, just normalizing time units
> fix(api): convert extra seconds to minutes in delay command

- api/src/opentrons/drivers/rpi_drivers/__init__.py
This raises the level of the warning about the failure to initialise a GPIO device from `info` to `warning`, making it more likely that it will be displayed (e.g. in Jupyter). Without this change, there is no indication given to the user of e.g. a Jupyter notebook of why their commands to control lights are doing nothing. It also adds some detail about what functionality is likely to be affected.
Ideally each function that requires GPIO would raise a warning (or even exception?) if the GPIO device is not available and this is not a simulation.
> refactor(api): raise GPIO warning, and add detail

- api/src/opentrons/hardware_control/controller.py
If you run a robot without RUNNING_ON_PI in the environment you get this warning message (and substantially reduced functionality), but it is not clear how to resolve it. This provides that information. In my case it was because I was invoking one Python script from another with subprocess.
> refactor(api): add info to debug warning on how IS_ROBOT is determined

- api/src/opentrons/drivers/rpi_drivers/gpio.py
The GPIO pin that allows the Pi to output audio was automatically enabled prior to the upgrade to libgpiod https://github.com/Opentrons/opentrons/pull/5381 . This is relied upon by e.g. this test https://github.com/Opentrons/opentrons/blob/751d9a402fa5d1f936df43ed12fd7387be23237f/api/src/opentrons/tools/factory_test.py#L217, and allows users to make their robots make sounds.
This should restore that functionality by enabling this pin during GPIO setup.
Do close this if it was an active decision to deprecate audio (but that seems a shame given it is the only way the OT2 has to communicate autonomously)
- adds function to control audio_enable_pin and calls out to it during setup
@ahiuchingau seems to be the expert on this
- setup function should already be covered by tests?
- this will …
> fix(api): Enable audio on GPIO startup

- api/docs/v2/new_modules.rst
The examples forgot to put quotation marks around the dict keys.
Low.
> docs(api): Fix syntax errors in Thermocycler profile examples

- app/src/components/RobotSettings/UploadRobotUpdate.js
In a small (code-wise) oversight, we forgot to clear the value of the `<input type="file">` that drives the "robot update from file" flow. Without that value reset (as is present on the protocol upload input), the upload button can become "stuck" if you attempt to select the same file
Fixes #5781 
- fix(app): clear <input> value after robot update file select
1. Try to upload an "update" file that you know will cause an error (e.g. a random, non-update zip file)
2. After the update fails, try to upload a new, working file
- Bonus points: have the second file have the exact same absolute path as the first file
Low; fixing a bug by mirroring implementation of the protocol file upload button which, once upon a time, had this exact same problem.
The component isn't covered by unit tests, …
> fix(app): clear <input> value after robot update file select

- robot-server/robot_server/service/access/models.py
- robot-server/robot_server/service/access/router.py
- robot-server/robot_server/service/app.py
- robot-server/robot_server/service/json_api/__init__.py
- robot-server/robot_server/service/legacy/models/__init__.py
- robot-server/robot_server/service/legacy/routers/__init__.py
- robot-server/robot_server/service/session/models.py
- robot-server/robot_server/service/session/router.py
Mock up of API to interact with access tokens and take control of a robot.
See : https://coda.io/d/Session-State-Management_dZ8yJSRoO6_/Access-Control_suRGF#_lu_TE for more details
These are the new API
```
GET /access/tokens
POST /access/tokens
DELETE /access/tokens/{token}
GET /access/controls/{scope}
POST /access/controls/{scope}
PUT /access/controls/{scope}/{token}
DELETE /access/controls/{scope}/{token}
```
Example of usage for taking control of robot:
```
request:
POST /access/tokens
response:
{
'data': {
'attributes': {
'token': 'abc_123'
}
}
}
request
POST /access/controls/robot
{
'data': {
'attributes': {
'token': 'abc_123'
}
}
}
```
Zero. 
closes #5746
> feat(robot-server): Mock up of access control models and router.

- app/src/components/NetworkSettingsCard/DisableDiscoveryCache.js
We had some bad merge timing with #5759 and #5800 that broke the JS typecheck job in `edge`. Sorry everyone!
- refactor(app): add type annotation missing due to merge timing
A quick 👍 I guess?
Nonexistent
> refactor(app): add type annotation missing due to merge timing

- shared-data/python/setup.py
When you pass packages to setup.py you need to pass all the subpackages!
There's even a special helper just for that! I didn't use it! We didn't
get any subpackages and you can't tell from the tests because they use
editable installs! Oops!
> fix(shared-data): recursively specify subpackages

- api/src/opentrons/data_storage/database_migration.py
This removes the labware database migration statements that are `print`ed every time the robot module is imported, which are confusing for end users, in favour of `log.info` messages. It leaves two print statements intact that are called when migration actually happens so that if the interface does not lock up without any information on progress. Changes welcome.
Largely fixes #5406.
Low - no functional changes. These messages seem to date from balena.
> refactor(api): remove labware migration prints

- robot-server/robot_server/service/legacy/routers/logs.py
- robot-server/tests/service/legacy/routers/test_logs.py
The fastapi automatic encoder for responses was doing a bit too much
when we returned a raw string in the logs response. By using the
Response class directly, we can specify the encoding as text/plain if
we're returning text logs instead of letting fastapi infer it.
Closes #5846
Install it and get logs - there should be newlines
> fix(robot-server): preserve newlines in text logs

- scripts/python.mk
- shared-data/Makefile
The shared-data pr had a small makefile refactor to coalesce the deploy
and deploy-staging python makefile tasks, but what that forgot is that
uploads to test pypi must be allowed to fail, since every edge build
in the same version will upload a wheel with the same name, which pypi
doesn't allow.
This adds that functionality back to the python_upload_package makefile
function
It also adds a bit of complexity to allow callers to specify a prefix
command since the shared-data task needs to execute in a subdirectory.
> build(scripts): allow test pypi uploads to fail again

- .travis.yml
- Makefile
- api/Makefile
- api/setup.py
- robot-server/Makefile
- robot-server/setup.py
- scripts/python.mk
- scripts/python_build_utils.py
- shared-data/Makefile
- shared-data/python/setup.py
These get uploaded to test pypi (where they are by and large never
downloaded, but it allows us to dry-run uploads to production pypi).
Test pypi doesn't allow you to reuse filenames, just like real pypi, and
each edge build in the same version will have the same wheel filename.
In the past, we overcame this by allowing the test pypi upload to fail,
but then... that doesn't really test anything.
Luckily, PEP440[1] which defines python versioning conventions, allows a
.devN tag to be at the end of versions, with the intent being that the N
is a build number. So this pr adds the capability to specify a
BUILD_NUMBER= environment variable - which travis edge builds now do -
which will get added to
- the wheel filenames
- the actual versions encoded in the wheel metadata
- the required version …
> chore(build): dev wheel versions on edge builds

- scripts/python.mk
- shared-data/Makefile
- shared-data/python/Makefile
and put python stuff in there. that prevents an issue where the
wheelname variable would run at makefile rule build time and create
spurious venvs and pipenv files in shared-data/
can you run setup-py, dist-py, test-py, lint-py in shared-data? how about setup-py, test-py, and lint-py from the top level?
if you run setup-js, make sure you no longer get a special opentrons-(hash) venv in ~/.local/share/virtualenvs and spurious Pipfiles in shared-data
> chore(shared-data): add python/ makefile

- api/src/opentrons/drivers/smoothie_drivers/__init__.py
This adds the `set_acceleration` command to `SimulatingDriver` meaning that this command can be used in simulated protocols.
Hit this while developing something - does it seem reasonable to add?
Adds `set_acceleration` that is simply `pass`, in line with other functions in this class.
Very low
> refactor(api): add set_acceleration to SimulatingDriver

- scripts/python_build_utils.py
there's even a big warning at the top! That I just missed. This needs to
be able to run under python 2.7 for annoying buildroot reasons.
> fix(scripts): make python_build_utils 2.7 compatible again

- api/src/opentrons/protocol_api/protocol_context.py
Clarify that `protocol.comment` does not allow real time communication which one might otherwise guess it did. (I realise use cases where simulation might be different from reality are rare).
> docs(api): Clarify that protocol.comment's message is computed in simulation

- shared-data/python/Makefile
There was a missing `)` in the makefile.
> fix(build): missing semicolon in shared-data/python/Makefile

- robot-server/robot_server/service/legacy/models/modules.py
- robot-server/robot_server/service/legacy/routers/modules.py
- robot-server/tests/service/legacy/models/test_modules.py
- robot-server/tests/service/legacy/routers/test_modules.py
Closes #5882 
Updates modules' SerialCommand model (`/robot-server/service/legacy/models`) to accept any type of args. Previously the args were strictly str type which caused type errors while executing module commands since these commands have various arg types.
- Changed the modules model to accept `typing.Any` args
- Updated `post_serial_command` (routers/modules) to catch any TypeErrors because of bad args and respond with a helpful message.
- Added tests for modules SerialCommand model
- Added tests for modules routers
- Code & tests make sense
- If you have a module, send it a POST request and verify that the command is executed with good args while a helpful response is provided for bad args. (If you have a tempdeck or thermocycler, the pre temp card in the app should now work …
> fix(robot-server): type mismatch in SerialCommand args

- .eslintignore
This means we won't be trying to format internal caching stuff from
mypy, among other things
> chore: add mypy stuff to eslintignore

- .travis.yml
- shared-data/python/Makefile
Deploys were breaking after I moved the python makefile tasks in shared-data to a subdirectory
- When the build passes and the deploy goes ok and i revert the change that deploys on all branches
> chore(build): fix pypi test deploy again

- app-shell/src/buildroot/__tests__/release-files.test.js
- app-shell/src/buildroot/index.js
- app-shell/src/buildroot/release-files.js
This PR adds old robot update file cleanup to the app-shell's buildroot module. The cleanup is run after the current release is successfully download, and is allowed to fail (with a log message).
Closes #4667
- fix(app-shell): clean up old robot update files
Note: due to the build bug fixed by #5886, this test plan won't currently work on `edge` because there's no release available for `3.19.0-alpha.1`. To test, **manually set your `app-shell/package.json` version to 3.19.0-alpha.0** before running `make -C app dev`
1. Check the contents of your Robot OS downloads folder
- On macOS: `ls ~/Library/Application\ Support/Opentrons/__ot_buildroot__`
2. Notice that there are probably a bunch of folders in there
3. Open the app and wait a few seconds
4. Check your Robot OS downloads folder again …
> fix(app-shell): clean up old robot update files

- app-shell/src/__tests__/discovery.test.js
- app-shell/src/discovery.js
- app-shell/src/system-info/index.js
- app/src/discovery/__tests__/epic.test.js
- app/src/discovery/epic.js
PR from pairing with @sanni-t. Fixes #5343; see ticket for details and acceptance criteria.
Also fixes an unreleased regression with the discovery spinner never stopping introduced by #5874 
- fix(app): restart MDNS browser when network interfaces change
Test plan:
1. Start the app with your USB-to-Ethernet robot **unplugged**
2. While the discovery spinner is going, plug the robot in
3. The robot should show up without you needing to click "try again"
- Depending on how long your computer takes to get the network interface activated with a self-assigned IP address, the spinner may time out before the robot shows up
- This is ok as long as the robot still (eventually) shows up
For the spinner regression:
Low. This PR repurposes the (already tested) network interface monitoring logic from …
> fix(app): restart MDNS browser when network interfaces change

- app/src/components/CheckCalibration/BadCalibration.js
In calibration check, if the tip pickup location seems very wrong, the user gets an "unable to check robot calibration" screen. This screen says to redo deck calibration.
This matches the *design,* but I think this it's technically wrong? The problem could also be with pipette calibration. Therefore, the app should link to broader troubleshooting steps.
* Changed that link from [Get started: Calibrate the deck](https://support.opentrons.com/en/articles/2687620-get-started-calibrate-the-deck) to [Checking your OT-2's calibration](https://support.opentrons.com/en/articles/4028788-checking-your-ot-2-s-calibration), which should be where the other pages link when they detect an ambiguous calibration error.
* Changed copy to match ("troubleshoot" instead of "learn more").
* Avoided renaming …
> fix(app): use troubleshooting link when calcheck fails at tip pickup

- api/tests/opentrons/protocol_api/test_context.py
- robot-server/tests/integration/test_deck_calibration.tavern.yaml
Test was failing in edge due to kwargs if statement being unable to compare a numpy array.
> fix(api): Fix failing test from edge due to kwarg check

- app-shell/electron-builder.config.js
- app-shell/src/discovery.js
- app-shell/src/exports.js
- app-shell/src/preload.js
- app-shell/src/update.js
- app-shell/webpack.config.js
- app/src/discovery/__tests__/reducer.test.js
- app/src/discovery/reducer.js
- app/src/shell/__mocks__/remote.js
- app/src/shell/index.js
- app/src/shell/types.js
This PR removes everything from the app's preloaded remote module except for the IPC channel. Closes #5900 
- refactor(app): limit preloaded shell remote to ipcRenderer
- Robot discovery list
- App version info card on "More" page
Low, mostly removals
> refactor(app): limit preloaded shell remote to ipcRenderer

- app/src/analytics/__tests__/epic.test.js
- app/src/analytics/epic.js
#5874 switched the app's MixPanel module from sync loading at launch to async loading when the app-shell sent over the config. This introduced a race condition where the app's previously existing logic to change the user's opt-in status in response to user initiated events would erroneously fire at config init, because it saw a change from `null` to "opted in or out".
This PR ensures the runtime opt-in change only fires after the config is fully loaded to avoid opt-in changes conflicting with (or rather, happening before) mixpanel is initialized.
Closes #5970
- refactor(app): fix race condition introduced by async anayltics init
- *Refactor* rather than "fix" because bug was never released
- You can test this with the branch build or with the dev task with `OT_APP_MIXPANEL_ID` set
- Hit …
> refactor(app): fix race condition introduced by async anayltics init

- app/src/components/CheckCalibration/styles.css
- app/src/components/RobotSettings/CheckCalibrationControl.js
- app/src/components/RobotSettings/ControlsCard.js
- app/src/components/RobotSettings/__tests__/CheckCalibrationControl.test.js
- app/src/components/RobotSettings/__tests__/ControlsCard.test.js
- app/src/components/TitledControl/__tests__/TitledControl.test.js
- app/src/components/TitledControl/index.js
- components/src/buttons/Button.js
- components/src/interaction-enhancers/__tests__/useHover.test.js
- components/src/interaction-enhancers/useHover.js
- components/src/primitives/Btn.js
- components/src/primitives/Btn.md
- components/src/primitives/README.md
- components/src/primitives/__tests__/Btn.test.js
- components/src/primitives/index.js
- components/src/primitives/style-props.js
- components/src/primitives/types.js
- components/src/styles/borders.js
- components/src/styles/colors.js
- components/src/tooltips/__tests__/useHoverTooltip.test.js
A _very_ common pattern that comes up when using our buttons is: "display a tooltip when this button is disabled". There are two problems that prevent us from doing this easily with out current button components:
- When disabled, our existing button CSS adds `pointer-events: none` to the button node, preventing enter and leave events
- When a `<button>` is disabled, React will not trigger `mouseleave` events (nor `mouseenter` events, starting at [React v16.13](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-1)), even if `pointer-events` aren't touched and **sometimes even if the handlers are attached to the button's parent**
This PR tackles both of these issues so that we can easily display tooltips on disabled buttons:
- Added new buttons in `primitives` that don't …
> feat(components): add primitive btns and fix useHover on disabled buttons

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Nitpicky formatting tweaks to our bug report, feature request, and pull request templates.
1. **Soft-wrap lines.** The templates use `` in each section to explain what to fill in. Formerly, lines in these comments were hard-wrapped. Because the GitHub editor uses a variable-width font, and because the browser window can be resized, this looked weird.
1. **Remove indentation,** for the same reasons as above. The former indentation was inconsistent, anyway.
1. **Rearrange bug report sections.** Now, it follows the logical order: "summarize the problem; show me what you did; show me what happened when you did that; tell me what you expected to happen instead." Formerly, the steps to reproduce were between the current behavior and the expected behavior, which felt a little weird.
1. **Use …
> chore(*): Tweak issue and PR template formatting

- app-shell/src/config/migrate.js
When we added config migration to the app, we added an assert to make sure that the config migrates properly. Unfortunately, this assert doesn't handle the migrated config being at a _higher_ level than the "latest", which can happen in the case of regular development or in the case of user downgrades.
- fix(app): loosen config version assert after migration
1. Update your app's config file to have a higher version than is latest (e.g. `2`)
- This might have already happened to your config file if you were testing #5976 
2. Try to open the app
Low
> fix(app): loosen config version assert after migration

- api/src/opentrons/protocol_api/geometry.py
- api/src/opentrons/protocol_api/instrument_context.py
This PR does the following:
1. adding a new warning when the wrong **Opentrons** tipracks are using for a pipette (this warning does not work for custom tipracks)
2. updating the LabwareHeightError message to alert user that the mismatched pipette/tiprack combo could be the cause of the error
> feat(api): add warning when a wrong tiprack is used for the pipette in the protocol

- api/docs/v2/new_labware.rst
Fixes #5806.
* In a code sample, use the result of .move() as an adjusted location to which the pipette can be moved, instead of implying .move() does the actual moving.
None in particular.
Low.
> docs(api): correct .move() example

- robot-server/tests/conftest.py
When setting up the background robot-server we need to wait for it to be ready before running through the integration tests.  We use a `time.sleep` of 15 seconds. We had to raise it from 2 seconds recently. 
This PR removes the `time.sleep` and polls `/health` every 500ms waiting for server to be ready.
None. Tests only
> fix(robot-server): tavern test setup fix

- robot-server/robot_server/service/session/models.py
- robot-server/robot_server/service/session/router.py
- robot-server/robot_server/service/session/session_types/base_session.py
- robot-server/tests/integration/sessions/test_calibration_check.tavern.yaml
- robot-server/tests/integration/sessions/test_default.tavern.yaml
- robot-server/tests/integration/sessions/test_tip_length_calibration.tavern.yaml
- robot-server/tests/integration/test_session.tavern.yaml
- robot-server/tests/service/session/test_router.py
Add `created_at` timestamp to Session response.
We always had this as part of the internal mode, but didn't include it in the body of the HTTP response.
- Add `created_at` timestamp to Session response.
- tests
None
> feat(robot-server): return created_at in session response

- robot-server/robot_server/service/session/models.py
- robot-server/tests/integration/sessions/test_default.tavern.yaml
We should use camel instead of snake case for command names. 
None
> refactor(robot-server): default session commands to camel case

- api/docs/v2/new_atomic_commands.rst
We changed `mix()` to not move between actions in apiLevel 2.3 (#5128). This fixes the description in the docs to reflect actual behavior
Make sure it uses the correct idiom "API Version"?? rather than `apiLevel` ??
> docs(api): update mix description behavior

- robot-server/robot_server/service/legacy/routers/control.py
The right-pipette change position was offset 10mm in y, I think because
of a typo when porting it. This commit changes the value to match the
old HTTP API implementation.
> fix(robot-server): fix typo in change pipette position

- jest.config.js
Jest in watch mode consumes a lot of file watcher resources. It's watching many `node_modules` files it doesn't need to watch. On Linux, even after adding inotify resources, `yarn jest --watch` (or even `yarn jest --watch protocol-designer/src`) takes a few minutes to start and sometimes times out a few times unless I kill flow or something and try again.
Related issue: https://github.com/facebook/jest/issues/3254
Update Jest config to exclude any `/node_modules/` paths from the file watch
- Jest tests still pass, same number of tests run (config not excluding any tests)
- Jest watch startup time might be significantly faster (at least on Linux it is!)
low to medium, messing with jest config
> chore(js): improve jest watch performance by excluding node_modules

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/tests/opentrons/config/test_advanced_settings.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
- robot-server/tests/integration/test_settings.tavern.yaml
Remove the deprecated `useV1HttpApi` config setting and `use_fast_api` feature flag.  This is a setting that is irrelevant at this point.
The use deprecated v1 http api switch should no longer appear in the run app
Low. This is a removal of unused code.
closes #6079
> fix(api, robot-server): remove the deprecated useV1HttpApi config setting 

- app/src/sessions/__fixtures__/index.js
- app/src/sessions/calibration-check/constants.js
- app/src/sessions/epic/__tests__/createSessionCommandEpic.test.js
- robot-server/robot_server/robot/calibration/check/session.py
- robot-server/robot_server/robot/calibration/tip_length/state_machine.py
- robot-server/robot_server/robot/calibration/tip_length/user_flow.py
- robot-server/robot_server/service/session/command_execution/__init__.py
- robot-server/robot_server/service/session/command_execution/command.py
- robot-server/robot_server/service/session/command_execution/hardware_executor.py
- robot-server/robot_server/service/session/models.py
- robot-server/tests/integration/sessions/test_default.tavern.yaml
- robot-server/tests/integration/sessions/test_tip_length_calibration.tavern.yaml
- robot-server/tests/robot/calibration/tip_length/test_state_machine.py
- robot-server/tests/robot/calibration/tip_length/test_tip_length_calibration.py
- robot-server/tests/service/session/session_types/test_check_session.py
- robot-server/tests/service/session/test_models.py
- robot-server/tests/service/session/test_router.py
The first release of sessions defined a set of commands for calibration check sessions. A command is defined as a name and a data payload schema. The command names are: 
```
"loadLabware"
"preparePipette"
"jog"
"pickUpTip"
"confirmTip"
"invalidateTip"
"saveOffset"
"exit"
```
As we begin work on tip length calibration, default, and protocol sessions we see that this naming was short sighted. 
This PR adds two features:
- namespaces command names.
- command defintions can be created in more than one enumeration. This eliminates the need for one monster CommandName enumeration.
After this PR. Command names will look like this:
```
"robot.homeAllMotors"
"robot.homePipette"
"robot.toggleLights"
"calibration.loadLabware"
"calibration.preparePipette"
"calibration.jog"
"calibration.pickUpTip" …
```
> feat(robot-server): Robot server command namespaces

- api/src/opentrons/protocol_api/execute_v3.py
- api/src/opentrons/protocol_api/json_dispatchers.py
- api/tests/opentrons/protocol_api/test_execute_v3.py
We finally will implement air gap! This PR should make the executors for both V3 and V4 protocols support the `"airGap"` command in the schema (command is the same in both schemas)
- Support `airGap` JSON command
This is tricky to test correctly, because the API's `InstrumentContext.air_gap` fn is stateful. However, the JSON command should be stateless.
Like asp/disp/etc, API `air_gap` uses a remembered flow rate that must be reset (but this we already solved for asp/disp/etc). New problem for air gap is that `air_gap` uses the previous location and does not have an argument that allows specifying a well/location. However, the JSON command has a `well` parameter. Additional surface for error is that `air_gap` takes a height from top, while the JSON command specifies an …
> feat(api): support air gap command in V3+V4 executors

- components/src/__tests__/__snapshots__/slotmap.test.js.snap
- components/src/slotmap/SlotMap.js
This PR serves as its own ticket, found a styling bug during QA. When we switched our Icon component to use the Svg primitive, the collision warning icon got left behind.
width => svgWidth
height => svgHeight
- fix(comp-lib): Update SlotMap prop names
Take a look in both complib and PD and make sure the slotmap collision icon isnt goofy.
low, single component in PD/complib
> fix(components): Update SlotMap prop names

- app/src/sessions/__fixtures__/index.js
- app/src/sessions/calibration-check/constants.js
Fix unreleased command change of 'calibration.preparePipette' ->
'calibration.check.preparePipette' on client side.
In https://github.com/Opentrons/opentrons/pull/6105, I refactored the location of a specific check calibration command on the robot-server side, but forgot to reflect the change in the client. This repairs calibration check, which was broken by the error. 
Confirm Calibration Check works as expected
Fixing bug to unreleased code, should be minimal risk
> fix(app): correctly namespace calibration check command

- api/docs/v1/complex_commands.rst
- api/docs/v1/hardware_control.rst
- api/docs/v1/modules.rst
- api/docs/v1/pipettes.rst
- api/docs/v1/writing.rst
- api/docs/v2/new_complex_commands.rst
- api/docs/v2/new_labware.rst
- api/docs/v2/new_pipette.rst
- api/src/opentrons/execute.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/instrument_context.py
- api/src/opentrons/protocol_api/module_contexts.py
- api/src/opentrons/simulate.py
`make docs` barfs hundreds of Sphinx warnings to the console, making the API docs difficult to work on. They're mostly silly syntax problems. This PR fixes many of them.
Fixed lots of silly syntax problems. See the commit messages; edits are grouped into commits based on which warning they resolve. (GitHub unfortunately lists the commits [in the wrong order](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-in-the-wrong-order) on this page, but they're independent, so it shouldn't matter.)
[Here is a diff of the `make docs` stderr](https://gist.github.com/SyntaxColoring/7a0c8b338516b245647b0c45dfe0ad44). I think I accidentally introduced a few new warnings, which I'll address in a follow-up PR.
This does result in some changes to the generated HTML. …
> chore(api): fix lots of Sphinx warnings

- .eslintignore
- discovery-client/src/__tests__/health-poller.test.js
- discovery-client/src/constants.js
- discovery-client/src/health-poller.js
- discovery-client/src/service.js
- discovery-client/src/store/__tests__/hostsByIpReducer.test.js
- discovery-client/src/store/index.js
- discovery-client/src/store/reducer.js
- discovery-client/src/store/types.js
- discovery-client/src/types.js
- flow-typed/global.js
- flow-typed/npm/lodash_v4.x.x.js
This PR is part of #5981 and continues the work of #6106 by rewriting the existing health poller with two main goals:
- Hook in nicely with the new Redux state + actions
- Avoid surfacing polls that have become stale due to later polls returning
- This is to avoid race conditions that cause robots to appear to flip back and forth between healthy and unhealthy
**This new health poller is not hooked up to anything.** You can compare it to the old health poller to get a sense of the logic that has changed (and also what has not changed).
- New poller (not hooked up): `discovery-client/src/health-poller.js`
- Old poller (still hooked up): `discovery-client/src/poller.js`
~Currently blocked by #6106 and will require rebase~
- refactor(discovery-client): refactor poller to enable wire-up to …
> refactor(discovery-client): refactor poller to enable wire-up to Redux

- .gitignore
- api/Makefile
- robot-server/Makefile
- scripts/python.mk
- shared-data/python/Makefile
There’s this nice pyenv-win package that is a fork of pyenv that works on
windows, but it doesn’t set up shims for everything installed to your python
scripts so things like pipenv don’t work - they look at the wrong place for the
python binary.
Invoking scripts like pipenv via python -m pipenv works fine, though. So this PR
does that. Shouldn’t affect other platforms.
`make setup-py`
> chore(api,robot-server,shared-data,scripts): better win pyenv support

- api/docs/v2/new_labware.rst
The labware example used "slot" for loading a well plate, which returns an error because it should be "location"
List out the changes to the code in this PR. Please try your best to categorize your changes and describe what has changed and why.
- fixed syntax error ExceptionInProtocolError: TypeError...  unexpected keyword argument 'slot' 
Describe any requests for your reviewers here.
This is my first pull request, so please let me know if I can make things better in future requests!
This does not effect other parts of the system. It is an isolated piece of labware example users can copy and paste. The well plate is not referenced otherwise.
> docs(api): corrects labware definition example's syntax to "location" 

- discovery-client/src/store/__tests__/actions.test.js
- discovery-client/src/store/__tests__/hostsByIpReducer.test.js
- discovery-client/src/store/__tests__/manualAddressesReducer.test.js
- discovery-client/src/store/__tests__/robotsByNameReducer.test.js
- discovery-client/src/store/__tests__/selectors.test.js
- discovery-client/src/store/actions.js
- discovery-client/src/store/index.js
- discovery-client/src/store/reducer.js
- discovery-client/src/store/selectors.js
- discovery-client/src/store/types.js
- discovery-client/src/types.js
This PR adds an action, a reducer, and some selectors to the Discovery Client Redux state to enable:
- (Re)initializing the state with a list of robots
- Used by the app's initialization of the Discovery Client with robots from its discovery cache
- Also used by the app on discovery cache clear / disable
- (Re)initializing a list of IP addresses to manually track
- Used by the app's "Manually Add / Remove IP Address" flow
- Replaces the `ADD_IP_ADDRESS` and `REMOVE_IP_ADDRESS` actions from #6106 because they didn't work out well in practice given how the Discovery Client is actually hooked up to the app
- Getting the full list of robots from the Discovery Client
- Getting the full list of IP addresses to hand to the Health Poller
~Blocked by #6121, will require rebase~
- **Reducers + …
> refactor(discovery-client): add robot and address initialization to state

- discovery-client/src/__tests__/mdns-browser.test.js
- discovery-client/src/index.js
- discovery-client/src/mdns-browser.js
- discovery-client/src/types.js
- flow-typed/npm/mdns-js_v1.0.x.js
This PR adds a new mDNS browser wrapper to the Discovery Client to create a unified facade around the mDNS browser provided by [mdns-js](https://github.com/mdns-js/node-mdns-js). Mostly, this PR serves to move setup and teardown logic that currently exists in the `DiscoveryClient` class and put it into a testable module that can be `start`ed and `stop`ped like the `HealthPoller`
**Blocked by #6153 and will require rebase**
- refactor(discovery-client): add new mDNS browser wrapper
This is the last PR before the PR that actually wires things up and can be tested on actual robots. For now, without the wireup:
N/A
> refactor(discovery-client): add new mDNS browser wrapper

- api/src/opentrons/calibration_storage/dev_types.py
- api/src/opentrons/calibration_storage/get.py
- api/src/opentrons/calibration_storage/modify.py
- api/src/opentrons/calibration_storage/types.py
- api/src/opentrons/legacy_api/containers/__init__.py
Robot server fails to start on robot because `typing_extensions` (not present on the robot) was imported at runtime. 
This PR moves `type_extensions` dependent types to `dev_types.py` and make sure they are only used during type checking.
Low
> fix(api): moves type_extension in calibration storage to dev_types for type checking only

- api/src/opentrons/commands/commands.py
- api/tests/opentrons/labware/test_pipette_unittest.py
- api/tests/opentrons/test_execute.py
- api/tests/opentrons/test_simulate.py
Hello 👋
This pull request addresses the open issue #2772 
to display the flow rate in uL/sec instead of the rate multiplier e.g. "1.0"
With the aim to display the output as suggested in the expected behaviour of the issue
> 'Aspirating {volume} uL from {location} at {flow_rate} uL/sec'
an example output from the python protocol
[my_protocol.py.zip](https://github.com/Opentrons/opentrons/files/4960766/my_protocol.py.zip)
> Picking up tip from A1 of Opentrons 96 Tip Rack 300 µL on 1
Aspirating 100.0 uL from A1 of Corning 96 Well Plate 360 µL Flat on 2 at 300 uL/sec
Dispensing 100.0 uL into B2 of Corning 96 Well Plate 360 µL Flat on 2 at 375.0 uL/sec
Dropping tip into A1 of Opentrons Fixed Trash on 12
- Imported FlowRates to commands.py to act as a getter for objects dispense and aspirate …
> fix: Commands log: misleading "rate" for aspirate/dispense

- README.md
- fixed the spelling of `grapical` in the main readme
> docs(readme): tiny typo

- robot-server/robot_server/service/session/models.py
Pydantic and Union types are a bit tricky. This PR just adds comments to hopefully help people out.
Also commenting the validation pattern used in SessionType and CreateParam. 
None. Just comments
> chore(robot-server): add comments about using Union of Pydantic models.

- api/src/opentrons/drivers/rpi_drivers/__init__.py
The message displayed when we fail to connect to GPIOs in Jupyter/Python script because another process is already using them doesn't explain that the reason stopping the server works is that it frees up the GPIOs for connecting. This may (or may not) be behind for example #6164.
This adds that to the message.
> refactor(api): clarify warning on GPIO connection problem

- api/docs/v2/new_examples.rst
Fixes up some typos in the the Examples sections of the docs.
Make sure the text accurately describes the code and vice-versa.
> docs(api): fix typos in examples

- api/src/opentrons/protocol_api/protocol_context.py
Closes #5467 
Explains `fixed_trash` has a well and you should specify it to use as a pipetting destination
Does it make sense?
Low/none, it's a docstring
> docs(api): explain trash has a well

- api/src/opentrons/calibration_storage/get.py
- api/src/opentrons/calibration_storage/types.py
- robot-server/robot_server/service/labware/models.py
- robot-server/robot_server/service/labware/router.py
- robot-server/tests/service/labware/test_labware_calibration_access.py
We store calibration offsets by parent - including by slot. When an
offset is stored for a slot, the parent key (which is used to determine
the location of the calibration file) is saved as the labware hash.
However, this is not how it should be expressed when loaded - the parent
of a slot-relative offset is empty until and unless we start saving
different calibration offsets for the same labware in different slots.
Also, fill out the example fields for the labware calibration model in
the robot server and restore an early return in get labware calibrations
if there are no calibrations to return.
\
This also is required to support #6100
> fix(api): set parent for in-slot offsets to empty

- app/src/components/LostConnectionAlert/index.js
#5626 introduced a bug caused by switching the logic for showing the LostConnectionAlert
- Before (good): Show alert if RPC WS goes down unexpectedly **or** robot stops responding on /health
- After (bad): Show alert if RPC WS goes down **and** robot stops responding on /health
This PR switches that **and** back to the proper **or**. Yay software. Bug noted in this thread: https://github.com/Opentrons/opentrons/issues/6159#issuecomment-665197896
- fix(app): show conn. alert if WS closes **or** robot becomes unhealthy
You can test this by creating a condition for the WS to go down but the robot to remain healthy
1. Connect a robot to both Wi-Fi and U2E
2. Click "connect" once the app shows the robot as wired
3. Pull the USB cable to sever the WebSocket connection
Bug on `edge`:
- WS will …
> fix(app): show conn. alert if WS closes **or** robot becomes unhealthy

- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/src/opentrons/config/reset.py
- api/src/opentrons/hardware_control/pipette.py
- api/src/opentrons/legacy_api/instruments/pipette.py
- api/src/opentrons/protocol_api/instrument_context.py
- robot-server/tests/integration/test_settings.tavern.yaml
Makes the robot-side feature flag text a) talk about the cal overhaul as a whole
rather than just tip length (should make it a lot easier to handle going
forward) and b) be even more forward about how you shouldn't enable it.
Keeps the advanced settings option the same because I really hate
changing the advanced settings options names.
> refactor(api): rename calibration overhaul feature flag

- robot-server/robot_server/service/dependencies.py
- robot-server/robot_server/service/protocol/protocol.py
- robot-server/robot_server/service/session/command_execution/command.py
- robot-server/robot_server/service/session/configuration.py
- robot-server/robot_server/service/session/errors.py
- robot-server/robot_server/service/session/manager.py
- robot-server/robot_server/service/session/models.py
- robot-server/robot_server/service/session/router.py
- robot-server/robot_server/service/session/session_types/protocol_session.py
- robot-server/tests/conftest.py
- robot-server/tests/integration/sessions/test_protocol.tavern.yaml
- robot-server/tests/service/session/session_types/test_check_session.py
- robot-server/tests/service/session/test_manager.py
Create the core of a protocol session.
- Created ProtocolSession derived from BaseSession
- Added CreateParams for ProtocolSession type
- SessionManager can create and delete protocol session
- Defined enum of protocol command definitions.
**This PR needs to be rebased once the protocol api PR is merged #6182**
Review naming of commands.
Zero. These endpoints don't do anything yet.
closes #6072
> feat(robot-server): Robot server protocol session mockup

- app/src/components/CalibrateTipLength/MeasureNozzle.js
- app/src/components/CalibrateTipLength/MeasureTip.js
- app/src/components/CalibrateTipLength/__tests__/MeasureNozzle.test.js
- app/src/components/CalibrateTipLength/__tests__/MeasureTip.test.js
- app/src/components/CalibrateTipLength/index.js
- app/src/components/CalibrateTipLength/types.js
Pop a spinner modal while API requests are in flight for tip length calibration
> refactor(app): show spinners during tlc requests

- api/src/opentrons/commands/commands.py
Hello 👋
To Address issue #6258
Setting Block temperature of Thermocycler module currently outputs
>`Setting Thermocycler well block temperature to 60.0 °Cwith a hold time of 5.0 minutes and 0 seconds`
with the change adds a space before "with" changes output to
>`Setting Thermocycler well block temperature to 60.0 °C with a hold time of 5.0 minutes and 0 seconds`
Let me know if i have missed or overlooked something i can change it
The error is reproducable with the following protocol
> [my_protocol.zip](https://github.com/Opentrons/opentrons/files/5015194/my_protocol.zip)
Low Risk
Thanks Benedict! 🚀
> fix: adds missing space to Thermocycler command

- app/src/calibration/labware/__tests__/selectors.test.js
- app/src/calibration/labware/selectors.js
If you have a labware on a module, and another of that labware on the
deck, the app will display (x2) next to the entry for the labware on the
deck in the file info panel. This is becaues of too-loose matching on
parent in a new selector. Tighten up that matching so labware on modules
doesn't get doublecounted.
- Load a protocol that has the same labware on the module and the deck
- Make sure the quantities in the file info page are correct
> fix(app): don't doublecount labware on modules

- app/src/components/ModuleItem/__tests__/ModuleUpdate.test.js
Deleting these commented out tests to remove the linter warning. I didn't actually write new tests to cover what these commented snapshots were supposed to be covering, but maybe we can create a ticket or something to do so. 
NA
Low
> test(app): remove commented out tests

- app/src/calibration/labware/__tests__/selectors.test.js
- app/src/calibration/labware/selectors.js
This PR follows up on an #6100 and #6246. A given labware used in a protocol should be associated to a given entry in the labware calibrations results if the labware's:
1. loadName matches the calibration data entry, and
2. namespace matches the calibration data entry, and
3. version matches the calibration data entry, and
4. parent module (or lack of parent) matches the data entry
The implementation I wrote in #6100 was buggy, and #6246 noted that it resulted in incorrect quantities being displayed in the table. However, it it turns out 6100 was buggy for both quantity linking _and_ calibration data linking. If a labware does not have a module parent, it could get linked (in UI) to module-based calibration data **if the module-based calibration entry was earlier in the response array**. …
> refactor(app): ensure proper API cal data is associated to protocol labware

- api/docs/templates/v1/layout.html
- api/docs/templates/v2/layout.html
This PR removes legacy intercom code in favor of GTM. This was conflicting with the new script and causing issues for support and sales.
fix(docs): Remove legacy intercom script
Low. docs invisible script only
> fix(docs): Remove legacy intercom script

- robot-server/robot_server/robot/calibration/deck/models.py
- robot-server/robot_server/robot/calibration/deck/user_flow.py
- robot-server/robot_server/robot/calibration/deck/util.py
- robot-server/robot_server/robot/calibration/helper_classes.py
- robot-server/robot_server/robot/calibration/tip_length/models.py
- robot-server/robot_server/robot/calibration/tip_length/user_flow.py
- robot-server/robot_server/service/session/manager.py
- robot-server/robot_server/service/session/models.py
- robot-server/robot_server/service/session/session_types/__init__.py
- robot-server/robot_server/service/session/session_types/deck_calibration_session.py
- robot-server/scripts/plot_session.py
- robot-server/tests/integration/sessions/test_deck_calibration.tavern.yaml
This hooks up the deck calibration user flow to the HTTP server.
closes #6251
- add `DeckCalibrationSession` and new SessionType
- move `AttachedPipette` and `RequiredLabware` from `/robot-server/robot/calibration/tip_length/models.py` to top level `helper_classes.py` 
- add integration tests
Low
> refactor(robot-server): add deck cal user flow to http server + integration tests

- robot-server/robot_server/service/session/models.py
- robot-server/tests/service/session/test_models.py
If createParams isn't used we should be able to accept either a null or empty object or no createParams key at all.
> fix(robot-server): Robot server createParams bug

- robot-server/robot_server/robot/calibration/tip_length/user_flow.py
- robot-server/tests/robot/calibration/tip_length/test_user_flow.py
Fix bug identified by @Laura-Danielle while reviewing #6316. Multichannel pipettes were improperly factoring in the front nozzle critical point in some move to commands which led to separate and extraneous motion.
- no longer specifying critical point when getting `gantry_position` or when calling `move_to` for return tip.
Low, This code is still behind a ff
> fix(robot-server): fix multi channel move in tip length cal

- api/src/opentrons/api/session.py
- api/src/opentrons/config/advanced_settings.py
- api/src/opentrons/config/feature_flags.py
- api/tests/opentrons/api/test_session.py
- api/tests/opentrons/config/test_advanced_settings_migration.py
- robot-server/robot_server/service/session/session_types/protocol_session.py
- robot-server/tests/conftest.py
- robot-server/tests/integration/sessions/test_protocol.tavern.yaml
- robot-server/tests/integration/test_settings.tavern.yaml
Adds a feature flag (`enableHttpProtocolSessions`) that enables the creation of new HTTP protocol sessions, but disables creating RPC protocol sessions via SessionManager.
This is for a future beta release of experimental HTTP protocol sessions. 
Please review the naming and the wording of the feature flag description. 
Tested with local robot-server and run-app
- connect to robot
- load a protocol
- return to main page and enable `enableHttpProtocolSessions`
- load a protocol and see this error:
low. 
closes #6305
> feat(api,robot-server): Robot server rpc http ff

- api/src/opentrons/api/session.py
- api/src/opentrons/api/util.py
- api/tests/opentrons/api/test_session.py
You can't inhibit creating Session in build_and_prep if http protocol sessions are enabled because.... THATS HOW PROTOCOL SESSIONS RUN PROTOCOLS!!
> fix(api): Fix protocol sessions not being able to run protocols even if feature flag is enabled

- api/src/opentrons/calibration_storage/modify.py
- api/src/opentrons/util/helpers.py
- api/tests/opentrons/containers/test_containers.py
- api/tests/opentrons/hardware_control/test_calibration_functions.py
- api/tests/opentrons/protocol_api/test_offsets.py
- robot-server/robot_server/service/access/router.py
- robot-server/robot_server/service/protocol/protocol.py
- robot-server/robot_server/service/session/command_execution/command.py
- robot-server/robot_server/service/session/models.py
- robot-server/robot_server/service/session/session_types/base_session.py
- robot-server/robot_server/util.py
- robot-server/tests/integration/protocols/test_protocol_upload.tavern.yaml
- robot-server/tests/integration/sessions/test_calibration_check.tavern.yaml
- robot-server/tests/integration/sessions/test_deck_calibration.tavern.yaml
- robot-server/tests/integration/sessions/test_default.tavern.yaml
- robot-server/tests/integration/sessions/test_tip_length_calibration.tavern.yaml
- robot-server/tests/integration/test_session.tavern.yaml
- robot-server/tests/test_util.py
`datetime.utcnow()` does not set the time zone to utc. The JSON serialized datetime strings were missing the `+00:00` indicator of UTC time zone. Using `datetime.now(tz=timezone.utc)` remedies this.
None
closes #6374
> fix(robot-server): datetime responses are missing timezone.

- robot-server/robot_server/service/session/session_types/protocol/execution/command_executor.py
- robot-server/robot_server/service/session/session_types/protocol/models.py
- robot-server/robot_server/service/session/session_types/protocol/session.py
- robot-server/tests/integration/sessions/test_protocol.tavern.yaml
- robot-server/tests/service/session/session_types/protocol/execution/test_command_executor.py
Fleshes out the model for the protocol session response. 
This is a schema and implementation that will certainly change once we dig into protocol context work. The goal is to provide a model for the beta release.
- Add `ProtocolSessionEvent` model. It describes an event that happened during a protocol session. This is either a protocol session command (via http) or a command executed by the protocol (via broker).  The difference is described by `source` attribute.
- Use `events` instead of `commands`.
- Unit tests
Questions:
- Do we want the events to be flat or do we we want an event to have a list of sub-events? 
**Answer from review discussion was yes**
- Related: this PR doesn't assign `commandId` to `protocol` sourced events. Every `protocol` event is a pair (`$: before` and `$: …
> feat(robot-server): Robot server protocol session model

- api/src/opentrons/calibration_storage/get.py
- api/src/opentrons/calibration_storage/migration.py
- api/src/opentrons/calibration_storage/modify.py
- api/src/opentrons/legacy_api/containers/__init__.py
- api/src/opentrons/protocol_api/labware.py
- api/tests/opentrons/protocol_api/test_offsets.py
- api/tests/opentrons/robot/test_robot.py
- app/src/components/FileInfo/index.js
Closes #6394. A bug has been popping up for users upgrading from a server version other than 3.19.0. Previously, when the index file does not exist, but a labware calibration file does, the migration check for the index file would fail because there are no protections to ensure that we are reading from a file that exists.
- Check that the file passed into the migration function exists before reading from it
- Only update the index file if that particular entry does not exist yet
- Update some tests to reflect the changes
I wasn't sure if I should just get rid of all the file exists checks at the call sites of `read_cal_file` and just put the check in here, or rely on the `FileNotFoundError`.  Also any other refactors we want to do while we're here?
Please test on a robot by:
1. deleting …
> fix(api, app): Ensure index file exists before reading from it

- api/src/opentrons/protocol_api/protocol_context.py
Document how to delete labware from a slot to load new labware mid-protocol. A somewhat popular request: #6214.
No functional change to code base but this is advanced usage which may not play hugely well with calibration flows, etc. Still think that documenting it in the API section, which only advanced users likely get to anyway, is useful.
> fix(api): Document deck slot deletion

- CONTRIBUTING.md
I think that `systemd-dev` doesn't exist and  `libsystemd-dev` does (looking at Raspbian but attempted to confirm on Ubuntu with similar results).
> docs(CONTRIBUTING): fix package name for systemd-dev

- app-shell/src/config/__fixtures__/index.js
- app-shell/src/config/__tests__/migrate.test.js
- app-shell/src/config/migrate.js
- app/src/config/schema-types.js
- app/src/support/__tests__/profile.test.js
- app/src/support/profile.js
This PR fixes #6461. See ticket for rationale and acceptance criteria 
- fix(app): do not set the user's Intercom name to "Unknown User"
- The app has never had logic to set `config.support.name` nor `config.support.email`, which is why I think its ok that we brute-force `null` them out rather than checking if the value matches the default before nulling it out
- **For support team members**: This will cause new users to show up in Intercom with their display name (not their actual name) defaulting to the user ID. See https://github.com/Opentrons/opentrons/issues/6461#issuecomment-685019078 for a screenshot of what this looks like
- **For QA team**: This might require a change to existing manual test procedure depending on what the existing test for the Intercom integration looks like
- …
> fix(app): do not set the user's Intercom name to "Unknown User"

- api/src/opentrons/drivers/thermocycler/driver.py
- api/src/opentrons/hardware_control/modules/thermocycler.py
- api/tests/opentrons/drivers/module_drivers/test_thermocycler_driver.py
- api/tests/opentrons/hardware_control/modules/test_hc_thermocycler.py
Closes #6392 
- Thermocycler driver: modified the rule that checks if `hold_time` has been updated. It now checks if `hold_time` was *probably* updated, based on the closeness of `hold_time` value read to `hold_time` value set.
- Thermocycler HW control: updated `wait_for_hold` to account for the uncertainty introduced by above logic.
- Are there any edge cases you can think of that could break this logic?
- Is there a better way to make this fix? (without changing the firmware preferably)
- The driver tests that raise error are time-consuming since the error is raised after waiting for 5 seconds. Is there a way to minimize this delay? Or is it okay to let it take all that time?
Since a set_temperature function exits only when hold_time has turned 0, we can count on that behavior and only …
> fix(api): thermocycler hold_time bug

- Makefile
- jest.config.js
It would be really nice to have a modern pipenv, so let's see if it works.
- See if you can still `make setup-py` with this version of pipenv
- See if you can change something in a `Pipfile` and then `pipenv update`
> chore(build): bump required pipenv

- robot-server/robot_server/service/protocol/router.py
- robot-server/robot_server/service/session/router.py
- robot-server/tests/integration/protocols/test_protocol_upload.tavern.yaml
- robot-server/tests/integration/sessions/test_protocol.tavern.yaml
There are instances where we are still using snake case in HTTP parameters when we should be using camel case.
None
> refactor(robot-server): use camel case for http params

- api/src/opentrons/protocol_api/instrument_context.py
fixes a reST typo in the `aspirate()` and `dispense()` docstrings
Closes #6491
> docs: fix aspirate and dispense typo

- api/docs/v2/new_labware.rst
- api/docs/v2/writing.rst
reST syntax for `.. code-block` directives requires the code to be at the same indent as the options. When code block substitutions were introduced per #6292, the convention used a 4 space indent for the `:substitutions:` option. These two code blocks did not get the proper indentation.
Since the example code had a 3 space indent and the option had a 4 space indent, the mismatch caused Sphinx to see the `.. code-block` in the `move_to()` example as empty.
Closes #6506 
none, docs only
> docs: fix indent in code-block directives

- app/src/robot-admin/__fixtures__/index.js
- app/src/robot-admin/__fixtures__/system-time.js
- app/src/robot-admin/api-types.js
- app/src/robot-admin/constants.js
- app/src/robot-admin/epic/__tests__/syncTimeOnConnectEpic.test.js
- app/src/robot-admin/epic/index.js
- app/src/robot-admin/epic/syncTimeOnConnectEpic.js
- app/src/robot-api/__utils__/epic-test-mocks.js
- app/src/robot-api/constants.js
- app/src/robot-api/types.js
- robot-server/robot_server/service/legacy/models/health.py
This PR wires the app up to the time endpoints added in #6403. When the app requests to connect over RPC, it will also hit `GET /system/time` and, if the time is mismatched by more than 60 seconds, the app will send a `PUT /system/time` request to get things sync'd.
Closes #3872
- feat(app): sync robot time with app time on connect
Smoke test:
0. Ensure your robot is running software that includes the time endpoints added in #6403
1. SSH into your robot and mess up the time
1. `systemctl disable systemd-timesyncd`
2. `date -s 10:10`
2. Open the Opentrons App
3. Click the connect toggle or button
4. Disconnect and connect again
Medium low. Thoughts + notes:
- Time is a funny thing to mess with
- If `timesyncd` is running and the robot has NTP access, the NTP time will be reasserted quite …
> fix(app): sync robot time with app time on connect

- app/src/components/CalibrateDeck/CompleteConfirmation.js
- app/src/components/CalibrateDeck/SaveXYPoint.js
- app/src/components/CalibrateDeck/SaveZPoint.js
- app/src/components/CalibrateDeck/__tests__/SaveXYPoint.test.js
- app/src/components/CalibrateDeck/__tests__/SaveZPoint.test.js
- app/src/components/CalibrationPanels/CompleteConfirmation.js
- app/src/components/CalibrationPanels/SaveXYPoint.js
- app/src/components/CalibrationPanels/SaveZPoint.js
- app/src/components/CalibrationPanels/__tests__/CompleteConfirmation.test.js
- app/src/components/CalibrationPanels/__tests__/SaveXYPoint.test.js
- app/src/components/CalibrationPanels/__tests__/SaveZPoint.test.js
Temporary patch to unblock user testing calibration flows. Introduces a third of a second delay between the first and second of two chained commands through out calibration flows on the run app.  This should immediately be addressed by a more robust epic-based solution.
> fix(app): temporary fix for chained command race conditions in cal flows to unblock user testing

- robot-server/robot_server/service/errors.py
- robot-server/robot_server/service/legacy/models/health.py
- robot-server/robot_server/service/legacy/routers/health.py
- robot-server/robot_server/service/system/models.py
- robot-server/robot_server/service/system/router.py
- robot-server/robot_server/system/errors.py
- robot-server/robot_server/system/time.py
- robot-server/tests/integration/system/test_system_time.tavern.yaml
- robot-server/tests/integration/test_health_check.tavern.yaml
- robot-server/tests/service/legacy/routers/test_health.py
- robot-server/tests/service/system/test_router.py
- robot-server/tests/system/test_time.py
PR #6501 uses the time endpoints to check & update robot's system time. In the absence of a time endpoint, which is true for all versions < 3.21, the app would get a 404 for this endpoint. This PR adds a time link to the health endpoint so that the app can check for the presence of time endpoints and only then attempt to use them.
- added time link to /health
- updated link for /system/time to be more accurate with the expected format
- raise error to prohibit setting time on dev server
- updated tests
Low. Doesn't touch any critical components
> refactor(robot-server): add time link to /health, refactor system/time links

- robot-server/robot_server/service/json_api/resource_links.py
- robot-server/robot_server/service/protocol/router.py
- robot-server/robot_server/service/session/router.py
- robot-server/robot_server/service/system/router.py
- robot-server/tests/integration/protocols/test_protocol_upload.tavern.yaml
- robot-server/tests/integration/system/test_system_time.tavern.yaml
- robot-server/tests/service/json_api/test_errors.py
- robot-server/tests/service/json_api/test_resource_links.py
- robot-server/tests/service/session/test_router.py
- robot-server/tests/service/system/test_router.py
Standardize the `links` returned in v2 responses according to changes in `/system/time` endpoint.
- `ResourceLinks` is a dict of string to `ResourceLink` object rather than a union of `str` and `ResourceLink`. 
- The keys used in `/sessions` router are not the HTTP verb but the resources.
- `self` is reserved as the key indicating the link to the requested or created link
- Added link attribute to `/protocols` responses
How does the naming look?
Very low. These are not used yet.
closes #6518
> refactor(robot-server): robot server resource links

- app-shell/src/buildroot/__tests__/release-files.test.js
- app-shell/src/buildroot/__tests__/release-manifest.test.js
- app-shell/src/buildroot/index.js
- app-shell/src/buildroot/release-files.js
- app-shell/src/buildroot/release-manifest.js
Companion PR to #6483. This PR adds functionality to the app to cache the Robot OS releases manifest (`releases.json`) to the filesystem so that the app can know about robot updates (most importantly, robot updates it has already downloaded to disk) even if the app is not instantaneously online.
Fixes #5992
- fix(app): cache robot releases manifest for offline usage
Smoke test:
1. Get a robot (or dev server) to report that it is out of date
- With the dev server, manually mess with `api/src/opentrons/package.json::version`
2. Open the Opentrons App with your computer connected to internet
- The app should report that the robot needs to be updated
3. Close the app and disable your computer's internet
4. Re-open the app
- The app should still report that the robot needs to be updated
Please …
> fix(app): cache robot releases manifest for offline usage

- .github/actions/webstack/deploy-to-sandbox/action.yaml
- .github/workflows/docs-build.yaml
Adds a github action and workflow to deploy the docs to the appropriate sandbox link when they are built.
Check it out: http://sandbox.docs.opentrons.com/actions_docs-deploy-v2/
> chore(build): Deploy docs to sandbox on push

- .gitignore
- api/mypy.ini
- robot-server/mypy.ini
- robot-server/robot_server/robot/calibration/deck/user_flow.py
- robot-server/robot_server/robot/calibration/helper_classes.py
- robot-server/robot_server/robot/calibration/pipette_offset/user_flow.py
- robot-server/robot_server/robot/calibration/tip_length/user_flow.py
- robot-server/robot_server/service/labware/router.py
- robot-server/robot_server/service/legacy/routers/modules.py
- robot-server/robot_server/service/legacy/routers/networking.py
- robot-server/robot_server/service/legacy/routers/settings.py
- robot-server/robot_server/service/session/session_types/check_session.py
- robot-server/robot_server/service/session/session_types/deck_calibration_session.py
- update-server/mypy.ini
Hey look, I'm figuring out how to set up my editor for Python dev! Turns out that there is a [pydantic plugin for mypy](https://pydantic-docs.helpmanual.io/mypy_plugin/) that we're not using. When I enabled it, 20 new type errors showed up in `robot-server`.
Most are pretty minor, but there are a couple bad looking ones that I've commented on in a PR review below. I resisted the urge to fix any of them and instead added `# type: ignore[...]` suppression comments along with `TODO`s with a little more detail about how to fix them.
I also took this opportunity to:
- Make our `mypy.ini` files use a consistent style that matches the examples in the mypy documentation
- Enable error code output from mypy so we can write more specific type error suppression comments
- chore(robot-server): enable …
> chore(robot-server): enable pydantic mypy plugin and suppress new errors

- .github/workflows/js-check.yaml
This is lint, check, and format. These can't really be split up
per-project (especially check) so it triggers on changes to anything.
> chore(build): add gh workflow for js checks

- api/src/opentrons/api/calibration.py
- api/src/opentrons/hardware_control/api.py
- api/src/opentrons/hardware_control/controller.py
- api/src/opentrons/hardware_control/simulator.py
- api/src/opentrons/hardware_control/types.py
- api/src/opentrons/hardware_control/util.py
- api/tests/opentrons/api/test_calibration.py
- api/tests/opentrons/hardware_control/test_moves.py
- api/tests/opentrons/hardware_control/test_util.py
Certain calibration workflows involve jogging pipettes up pretty high. Especially with GEN2 pipettes, the upwards range of motion can be pretty limited, and jogging up like that can cause hard limit errors which poison the system.
Use the motion checking system we already have (after a bit of a light refactor) to actually raise errors during jog, albeit swallowing them before returning them to the app, to implement a system where the robot just won't move if you jog it too high specifically during labware calibraiton (in V2 protocols, anyway).
Medium - this affects a pretty core part of the system in labware calibration, but in a very limited way. The checks can only raise exceptions specifically when jogging in labware calibration, not in any of the new flows.
- Make sure you can still …
> fix(api): limit calibration jogs when going upward

- shared-data/python/Makefile
This PR fixes the two following issues with `make push` in shared-data:
1. old wheel files are not being cleared and accumulate in `python/dist`
2. a new wheel file is only generated when changes to python files are detected but not json files
- add `clean_cmd` that is found in both api and robot-server Makefiles to clear the shared-data build directory
- use the `json_sources` filter to look for changes
Am I understanding and fixing this correctly?
> chore(shared-data): clean build directory and check json changes during make wheel

- robot-server/robot_server/service/session/models/command.py
Create models for commands used in basic pipetting protocol: load instrument, load labware, aspirate, dispense, pick up tip, and drop tip.
Just adding new models.
None
closes #6556
> feat(robot-server): create models for basic pipetting session commands

- app-shell/package.json
- yarn.lock
e-d-i 3.1.1 includes
https://github.com/MarshallOfSound/electron-devtools-installer/pull/140,
a fix for an issue where google bumped the version of their chrome
extension format and the unpacker that r-d-i used therefore stopped
working. The PR uses a new version of that unzipper library that
functions.
Fixes an issue where addon devtools would never be installed.
> chore(app-shell): bump electron-devtools-installer to 3.1.1

- api/src/opentrons/protocol_api/implementation/interfaces/instrument_context.py
- api/src/opentrons/protocol_api/implementation/interfaces/labware.py
- api/src/opentrons/protocol_api/implementation/interfaces/modules/magnetic_module_context.py
- api/src/opentrons/protocol_api/implementation/interfaces/modules/module_context.py
- api/src/opentrons/protocol_api/implementation/interfaces/modules/temperature_module_context.py
- api/src/opentrons/protocol_api/implementation/interfaces/modules/thermocycler_module_context.py
- api/src/opentrons/protocol_api/implementation/interfaces/protocol_context.py
Adding abstract interfaces for implementation of `ModuleContext` and it's derived classes. 
Even though we've put this epic aside for now, I still think it's worth doing. So going to chip away at it.
closes #6330
Feedback I am looking for:
- are inputs and outputs of functions okay. Some of them should be more specifically typed (`ThermocyclerStep` for example).
- are there methods that don't belong.
Note that the target branch is a feature branch.
The purpose of this PR is to get these interfaces written. There could (will) end up being quite a bit of shuffling once I try to continue to the next step which is to have the Context classes delegate their work to implementations of these interfaces. 
None
> refactor(api): abstract baseclasses for module contexts

- robot-server/robot_server/service/session/models/command.py
- robot-server/robot_server/service/session/router.py
- robot-server/robot_server/service/session/session_types/live_protocol/command_interface.py
- robot-server/robot_server/service/session/session_types/live_protocol/state_store.py
- robot-server/tests/conftest.py
- robot-server/tests/integration/sessions/test_live_protocol.tavern.yaml
- robot-server/tests/service/session/session_types/live_protocol/test_command_executor.py
- robot-server/tests/service/session/session_types/live_protocol/test_load_labware.py
- robot-server/tests/service/session/session_types/live_protocol/test_state_store.py
Live protocol session continued! This PR adds the ability to load labware.
Closes #6591 
- added load_labware handler
- added LoadLabwareResponse model
- added labware state handler to store
- added unit tests & tavern integration tests
Low. Adds a 'result' router field to sessions command executor. Everything else is still isolated.
> feat(robot-server): http basic pipetting- load labware

- api/src/opentrons/types.py
This changes the labware used to define an arbitrary point-based location from 'Hi' to None. `None` is the better format to use to ensure retraction (thanks @sfoster1 ). Since this is the only place in the documentation that an example of point labware is given, users are likely to develop the bad habit of using random strings (as I did in #6655).
Very low: just docs
> docs(api): change labware in Location.move example from 'Hi' to None

- .github/actions/python/pypi-deploy/action.yaml
Per
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
to account for CVE-2020-15228
> chore(actions): switch to new environment setting

- .github/workflows/app-test-build-deploy.yaml
- .github/workflows/js-check.yaml
- Makefile
We somehow stored some invalid cache data for our js workflows, I think
because I was changing what was cached without changing the cache keys.
This PR changes the cache keys to
a) actually reflect what they're caching, which would be important if we
start caching python stuff for instance
b) rebuild the cache with the current config
Ugh.
> chore(build): rebuild js gh caches

- api/src/opentrons/protocols/parse.py
- api/src/opentrons/protocols/types.py
- api/tests/opentrons/protocols/test_parse.py
Closes #6681
- pin existing JSON protocols to API version 2.8
- Code review, including automated test
Medium. Should not affect current behavior, bc JSON protocols will already be using the latest API version. This just prevents them from using 2.9 etc when those come out.
> feat(api): pin JSON protocols to APIVersion 2.8

- .flowconfig
Flow would pick up on the json files interned in the shared-data python
bindings at least on my system. Get them outta here
> chore: ignore shared-data python in flow

- app/src/alerts/__tests__/actions.test.js
- app/src/alerts/__tests__/selectors.test.js
- app/src/alerts/actions.js
- app/src/alerts/constants.js
- app/src/alerts/epic.js
- app/src/alerts/selectors.js
- app/src/components/Alerts/__tests__/Alerts.test.js
- app/src/components/RobotSettings/SelectNetwork/ConnectModal/__tests__/form-state.test.js
- app/src/components/RobotSettings/UpdateBuildroot/SkipAppUpdateMessage.js
- app/src/components/RobotSettings/__tests__/ControlsCard.test.js
- app/src/components/ToggleBtn/__tests__/ToggleBtn.test.js
- app/src/components/ToggleBtn/index.js
- app/src/components/app-settings/AppAdvancedSettingsCard.js
- app/src/components/app-settings/AppSoftwareSettingsCard.js
- app/src/components/app-settings/DowngradeAppControl.js
- app/src/components/app-settings/UpdateAppModal.js
- app/src/components/app-settings/UpdateNotificationsControl.js
- app/src/components/app-settings/__tests__/AppAdvancedSettingsCard.test.js
- app/src/components/app-settings/__tests__/AppSoftwareSettingsCard.test.js
- app/src/components/app-settings/__tests__/UpdateAppModal.test.js
- app/src/components/app-settings/__tests__/UpdateNotificationsControl.test.js
- components/__utils__/mountWithStore.js
- components/src/modals/BaseModal.js
- components/src/modals/__tests__/BaseModal.test.js
- components/src/styles/colors.js
- components/src/styles/typography.js
This PR adds the ability for a user to disable app update pop-up notifications either via the pop-up or via a toggle in More > App > App Software Settings.
Closes #6684
~This is a draft PR blocked by #6708. Will require rebase.~
- feat(app): allow app update pop-up notifications to be disabled
The acceptance criteria are in #6684, so take a look at that. As usual, manually editing `version` in `app-shell/package.json` to a previous version is the best way to test this with `make -C app-shell dev`
- **Note:** The notification will also pop up as soon as you toggle it back on the first time you make the switch
- Click "View Available Update" in More > App
- Click "Downgrade" (or whatever it says based on your fake dev version) on a Robot settings page and click "View App Update" on the …
> feat(app): allow app update pop-up notifications to be disabled

- .gitignore
Prevent `*.sublime-project` and `*.sublime-workspace` files from being added to Git, in the same way we prevent `.vscode`
and `*.code-workspace` files from being added.
-----
If we wanted, we *could* check in the `.sublime-project` file, to share tedious settings like which directories to keep out of the index and how to normalize whitespace on file save. I'm assuming we don't, though, since I haven't seen anyone else use Sublime Text.
> chore: Exclude Sublime Text project files from Git

- api/src/opentrons/drivers/thermocycler/driver.py
- api/tests/opentrons/drivers/module_drivers/test_thermocycler_driver.py
The thermocycler driver unit tests were taking an eternity due to the retry logic and sleeps. 
Created a constant for `DEFAULT_POLLER_WAIT_SECONDS` and patched it to be 0.0 seconds. 
Zero. Just test change.
> chore(api): speed up thermocycler test.

- api/tests/opentrons/protocol_api/test_instrument.py
As per [this awesome suggestion](https://github.com/Opentrons/opentrons/pull/6670#discussion_r502649429) by @amitlissack, I've refactored the instrument context test to to use `pytest.mark.parametrize` to cut down on redundant code.
- Use pytest mark parametrize in instrument context test
Code review on test, make sure I didn't lose any coverage
Low, just refactoring a test
> refactor(api): use pytest mark parametrize in instrument context test

- app/src/analytics/__tests__/alerts-events.test.js
- app/src/analytics/__tests__/system-info-events.test.js
- app/src/analytics/epic.js
- app/src/analytics/make-event.js
- app/src/components/app-settings/UpdateNotificationsControl.js
- app/src/components/app-settings/__tests__/UpdateNotificationsControl.test.js
- app/src/support/__tests__/config-profile.test.js
- app/src/support/__tests__/system-info-profile.test.js
- app/src/support/profile.js
This PR fixes an oversight in the "Ignore App Updates" buildout. Setting the app to silence the update pop-ups should:
- Send an anonymous analytics tracking event (if the user has opted in to anonymous usage tracking)
- Set a flag on the user's support profile to note that they've disabled app updates 
- fix(app): add analytics and support tracking to ignore app update
- Also fixed a race condition in the analytics event epic that I found during smoke testing of this PR
Smoke testing this is annoying, but here is the plan I followed:
- Click "Ignore app updates" in the modal and close the warning modal
- Event: `appUpdateDismissed`, property `updatesIgnored: true`
- Click "Not now" in the app update modal
- Event: `appUpdateDismissed`, property `updatesIgnored: false`
- Event: …
> fix(app): add analytics and support tracking to ignore app update

- api/Makefile
- notify-server/Makefile
- robot-server/Makefile
- shared-data/python/Makefile
Some editor support systems have a bad habit of invoking mypy and adding
mypy caches in the directory of whatever file you happen to be visiting,
and then those caches stick around and go into the wheels, and then
they're really big and hard to install. Add mypy_caches in locations
where they should not be (anywhere except subproject roots, basically)
to the clean_cmds for each python project.
Try invoking mypy in some random subdir of a python project then do a `make wheel` and make sure the `.mypy_cache` folder that results doesn't make it in.
> chore(build): Remove stray mypy caches

- notify-server/Makefile
- notify-server/notify_server/logging.py
- notify-server/notify_server/main.py
- notify-server/notify_server/settings.py
- notify-server/poetry.lock
- notify-server/pyproject.toml
- notify-server/tests/test_logging.py
- notify-server/tests/test_settings.py
Adding configuration for the two server addresses and dev vs prod flag.
closes #6704 
Using pydantic's `BaseSettings` since it manages the whole environment variable override nicely.
None
> feat: add basic application configuration using pydantic BaseSettings.
