Opentrons/opentrons

opentrons_sdk/labware/containers.py
opentrons_sdk/labware/deck.py
opentrons_sdk/protocol/handlers/context.py
opentrons_sdk/protocol/protocol.py
tests/opentrons_sdk/integration/test_protocol.py
tests/opentrons_sdk/labware/test_containers.py
tests/opentrons_sdk/labware/test_deck.py

In this PR @astaff and I paired to make the following changes,
* Added ability to load containers and inject into Protocol singleton
* Changed Protocol to be singleton object / add light support for testing
* Added integration test for protocol
* Added support for querying protocol containers

Deck setup

---

opentrons_sdk/protocol/handlers/motor_control.py
tests/opentrons_sdk/protocol/test_motor_handler.py

This PR tests the motor handler's `move_to_well` and `move_into_well` methods.

20160922 030400 move to well test

---

opentrons_sdk/containers/calibrator.py
opentrons_sdk/containers/placeable.py
tests/opentrons_sdk/containers/test_calibrator.py
tests/opentrons_sdk/containers/test_containers.py

adding calibration:
1) Calibrator.calibrate takes calibration_data dictionary with current values, container (or any placeable), expected and actual coordinates and returns updated calibration data
2) Calibrator.apply_calibration apply calibration_data to a deck returning a new deck
changed Placeable to use name as a key to access it's children

63 calibration

---

opentrons_sdk/labware/instruments.py
opentrons_sdk/robot/robot.py
opentrons_sdk/util/geometry.py
tests/opentrons_sdk/labware/test_instruments.py

This PR adds command to pick up a tip. Does not use calibrated locations.

51 tip manipulation

---

opentrons_sdk/drivers/motor.py
tests/opentrons_sdk/drivers/motor_test.py

This PR:
1. inverts the Z axis in the motor driver

20160930 092200 invert z axis

---

opentrons_sdk/containers/placeable.py
opentrons_sdk/drivers/motor.py
opentrons_sdk/labware/instruments.py
opentrons_sdk/robot/robot.py
tests/opentrons_sdk/containers/test_placeable.py
tests/opentrons_sdk/protocol/test_robot.py

This PR address some bugs found while testing:
1. Pipette has a `go_to` method now
2. Placeable `from_polar` calculation fixed
3. Removed unnecessary delays in motor driver
4. Properly flipping Z axis in the motor driver

20160930 122400 post test fixes

---

opentrons_sdk/containers/placeable.py
opentrons_sdk/drivers/motor.py
opentrons_sdk/labware/instruments.py
tests/opentrons_sdk/drivers/motor_test.py
tests/opentrons_sdk/integration/move_robot.py
tests/opentrons_sdk/labware/test_instruments.py

This PR:
1. Flips the X and Y axis in the motor driver, so the user-facing origin is the lower left corner
2. Adds driver methods for setting/getting the motor controller's `steps_to_mm` value

75 flip y coordinates

---

opentrons_sdk/containers/calibrator.py
opentrons_sdk/containers/placeable.py
opentrons_sdk/labware/instruments.py
opentrons_sdk/robot/robot.py
opentrons_sdk/util/vector.py
tests/opentrons_sdk/containers/test_calibrator.py
tests/opentrons_sdk/helpers/test_calibration.py
tests/opentrons_sdk/labware/test_instruments.py
tests/opentrons_sdk/performance/test_performance.py

In this PR:
- performance tuning
- refactored calibration, vector and placeable for performance
- updated Calibrator to be more usable by client code
- added performance test

20161010 102700 placeable calibrator speed

---

.coveragerc
.travis.yml
README.md

This PR:
- Adds test coverage
- Adds integration with https://coveralls.io
- Adds coverage badge to README.md

20161011 add coverage

---

foo.py
opentrons_sdk/containers/placeable.py
opentrons_sdk/drivers/motor.py
opentrons_sdk/drivers/virtual_smoothie.py
opentrons_sdk/instruments/magbead.py
opentrons_sdk/instruments/pipette.py
opentrons_sdk/json_importer/json_importer.py
opentrons_sdk/robot/robot.py
opentrons_sdk/util/log.py
tests/opentrons_sdk/containers/test_grid.py
tests/opentrons_sdk/labware/test_pipette.py
tests/opentrons_sdk/protocol/test_robot.py

This PR:
1. makes fixes to Pipette, Robot, and JSON_Importer for running off a JSON protocol
2. uses `pipette.move_to(strategy='arc')` (default) and `pipette.move_to(strategy='direct')`, instead of the ambiguous `go_to()`
3. refactors Pipette to use `Placeable.bottom()` and `Placeable.top()`
4. adds a `Robot.simulate()` method
5. fixes the slot location coordinates assigned in Robot

Actual protocol fixes

---

opentrons_sdk/containers/placeable.py
opentrons_sdk/robot/robot.py
tests/opentrons_sdk/containers/test_placeable.py

In this PR:
* Cleaning up code, making it easier to read
* Adding docstrings

Refactorings; documentation

---

opentrons_sdk/drivers/motor.py
opentrons_sdk/json_importer/json_importer.py

* Updates error reporting for bad container/well location data

20161024 153000 use json importer

---

opentrons_sdk/drivers/motor.py
opentrons_sdk/util/vector.py

adds a tracer for homing and updates the vector encoder

add better homing tracing and update vector encoder

---

opentrons/instruments/pipette.py
tests/opentrons/labware/test_pipette.py

Small PR, fixing a bug in Pipette and writing a test for it

fixed bug in Pipette.calibrate(); added test

---

.travis.yml

This PR reenables doc tests - they were broken but a previous commit of mine fixed them. I didn't have time to check if they were fixed until today; thus, the delayed PR.

Reenable doc tests

---

.travis.yml
appveyor.yml
appveyor/run_with_env.cmd
requirements.txt

Sets up the API to run on windows

54 m setup windows build for opentrons api repo

---

opentrons/drivers/motor.py
tests/opentrons/drivers/test_motor.py
tests/opentrons/protocol/test_robot.py

Small PR, where the driver raises `RuntimeError` if there is no connection when attempting to write to serial port

221-s-home-should-return-an-error-if-the-user-is-not-connected

---

docs/api_tips_and_tricks.md
docs/source/tips_and_tricks.rst
opentrons/instruments/pipette.py
opentrons/json_importer/json_importer.py
tests/opentrons/containers/test_grid.py
tests/opentrons/labware/test_pipette.py

Small PR, making `Pipette.mix(repetitions, volume, location)`

pipette.mix(repetitions, volume, location)

---

opentrons/robot/robot.py

Small PR including `'commands_total': len(robot._commands)` within the `robot.run` 'command-run' notification

including total commands count within robot run emit

---

docs/source/index.rst

Reverts OpenTrons/opentrons-api#113

Revert "Fix doc example and imports"

---

opentrons/config/containers/default-containers.json
tests/opentrons/containers/test_grid.py
tests/opentrons/containers/test_persisted_containers.py

This PR fixes the container files, and removes unused custom containers

Clean up container files

---

docs/source/getting_started.rst
docs/source/module.rst
docs/source/tips_and_tricks.rst
docs/source/updating_firmware.rst
docs/source/well_access.rst

Docs edits

---

docs/source/api.rst
docs/source/getting_started.rst
docs/source/tips_and_tricks.rst
docs/source/well_access.rst
opentrons/instruments/pipette.py
opentrons/robot/robot.py

This PR updates docs, mostly the getting started page's explanation of API principles.

Update docs getting started page

---

docs/source/custom_containers.rst
docs/source/index.rst
docs/source/setup.rst

this PR adds a page to the docs about custom containers

add custom containers

---

docs/source/conf.py
docs/source/templates/layout.html

This tiny PR:
Fixes broken footer contact form. 
Disables sphinx google analytics code generation. 
Manually injects GA code.
*note* A combo of  attempting to track contact form submissions with google analytics and sphinxes defaul GA code injection was what broke the form.

Footer contact form

---

opentrons/instruments/pipette.py

This PR address:
https://github.com/OpenTrons/opentrons-api/issues/144

do not modify dispensing volume if it is 0

---

.gitignore
docs/source/getting_started.rst
docs/source/labware_library.rst
tests/opentrons/protocol/test_robot.py

- added air_gap() to getting started
- added touch_tip(height) to getting started
- added start_at_tip() to getting started
- added containers.list() to labware library

Jan 30 app updates

---

opentrons/containers/placeable.py
tests/opentrons/containers/test_placeable.py

Small PR, adding a `__add__` method to placeable, which takes this placeables list of children and appends the other's list of children

allows Placeables to be added together like lists

---

api/opentrons/server/main.py

Uses `Placeable.get_type()` method in Flask server, to be able to handle `WellSeries`

Transfer live testing

---

.travis.yml
Makefile
app-shell/app/main/main.js
appveyor.yml

Clean up PR. Removes commented code, removes shutting down the backend server via a web request.

20170316 132700 revert server child process killing

---

api/docs/source/static/override_master.css
api/docs/source/templates/layout.html

This small PR:
- Adds new support links and we're hiring to docs template

updated nav and footer links

---

api/docs/source/static/override_master.css
api/docs/source/templates/layout.html

This PR:
Adds modules link to header and footer in docs

Add modules link docs navigation

---

api/opentrons/util/environment.py

This PR,
* Makes the API when running in environment like Jupyter to use the app's data dir for reading calibrations.
TODO: test

20170505 150000 sync api to app calibrations dir

---

api/opentrons/drivers/smoothie_drivers/v1_2_0/driver.py
api/opentrons/server/log.py
api/opentrons/server/main.py

Always use opentrons.util.environment.get_path('APP_DATA_DIR')

always use opentrons.util.environment.get_path('APP_DATA_DIR')

---

app/ui/components/Brand.css
app/ui/components/Brand.js
app/ui/components/Button.js
app/ui/components/Calibrate.js
app/ui/components/Connect.css
app/ui/components/Connect.js
app/ui/components/Connection.js
app/ui/components/Home.css
app/ui/components/Home.js
app/ui/components/Jog.css
app/ui/components/JogPipette.js
app/ui/components/JogPlunger.js
app/ui/components/Load.js
app/ui/components/Main.css
app/ui/components/RunControl.css
app/ui/components/RunControl.js
app/ui/components/RunNotifications.css
app/ui/components/RunNotifications.js
app/ui/components/RunProgress.css
app/ui/components/RunProgress.js
app/ui/components/Upload.js
app/ui/components/Util.css
app/ui/components/Welcome.js
app/ui/components/app.css
app/ui/components/app.js

This PR is purely UI component based, does not touch redux state or API. @IanLondon @mcous any code review welcome before finishing out this section of the run screen.
- Uses app.js rather than  Main.js as root component
- Introduces mock state in app.js
- Applies initial styles and conditional component rendering to run button, and run controls components.
- Shrinks side panel to mimic closed side panel before tackling that section of the app (WIP)
- Run Progress bar based on progress prop (1/3)*100 to mock command 1 of run_log.length being current command
- Conditionally renders 3 run notification types: Tip, Paused, Error:
```
isRunning: false
```
```
isRunning: true,
isPaused: false,
errors: []
```
```
isRunning: true,
isPaused: true,
errors: []
```
```
isRunning: true,
isPaused: …
```

App 3 0 run screen

---

.travis.yml
app/Makefile
app/internals/mocks/fileMock.js
app/internals/scripts/CheckBuiltsExist.js
app/internals/scripts/CheckNodeEnv.js
app/shell/logging.js
app/shell/main.js
app/shell/menu.js
app/shell/preferences.js
app/shell/servermanager.js
app/ui/components/App.js
app/ui/routes.js
app/webpack.config.main.prod.js
app/webpack.config.renderer.dev.dll.js
app/webpack.config.renderer.dev.js
app/webpack.config.renderer.prod.js
scripts/install-linux

This PR gets Travis to green! It does this by disabling OSX in Travis for now, fixing all front end lint errors, and using make -C instead of cd. Please give it a once over for sanity!

(Chore) App 3.0 - Get Travis to green

---

app/ui/robot/api-client/client.js

#336 changed the notification object shape. This tiny PR updates the API client to handle that shape change.
- (Fix) Update robot API notification handler for #336
@OpenTrons/js you know what to do

(v3, fix) Update session client

---

.travis.yml

Trying to fix: "No such file or directory @ dir_chdir - /home/travis/build/Opentrons/opentrons/api/app/dist"

less directory changing w cd in travis

---

api/opentrons/drivers/smoothie_drivers/v3_0_0/driver_3_0.py
api/opentrons/robot/base.py
api/opentrons/robot/robot.py
api/opentrons/robot/robot_configs.py

This PR builds a very simple configuration dict for robot configurations. This functionality will be replaced by work for ticket #80 (`[L] Migrate hardcoded values to config or database`), but should make our lives easier until then.
Don't think this requires tests due to the planned short-term use but let me know if you'd like some added. 
- (Chore) Change description
- (Fix) Change description
- (Feature) Change description
- (Refactor) Change description
- (Docs) Change description
- (Tests) Change description
**Note**: If your PR incorporates …

Config_dict for machine configurations

---

app/ui/components/App.js
app/ui/components/NavPanel.js
app/ui/containers/Nav.js

We added the file dropzone without hooking up the upload. This PR fixes that.
- (Fix) Hook file upload to dropzone (#398)
- (Fix) Prevent file drops outside of the dropzone from taking over the screen (#398)
Normal review!

(v3, bugfix) Actually hook up file upload drop

---

api/setup.py
app/electron-builder.json
app/package.json
appveyor.yml

- Changed package name in `package.json` to contain valid characters only.
- Calling the right make dist target
Results are here: https://ci.appveyor.com/project/Opentrons/opentrons

(chore) Fixing Windows Build

---

api/docs/source/cookbook.rst
api/docs/source/index.rst

Write a high level description of the pull request.
New page for "cookbook" recipes, starting out with 384 plate filling

start cookbook page w 384 plate filling

---

README.md
api/opentrons/robot/robot_configs.py

Robot config with envvars

---

api/opentrons/instruments/pipette.py
api/tests/opentrons/containers/test_default_containers.py
api/tests/opentrons/containers/test_old_container_loading.py
api/tests/opentrons/labware/test_pipette.py

Add assertions to Pipette methods to ensure that tip is present or not present as required for correct behavior. Addeded/fixed minor inline documentation.
No behavioral changes, so no important changes to docs or tests

Add tip assertions

---

app/ui/components/App.css
app/ui/components/ConnectPanel.css

This small PR implements a few css for scrolling divs:
- swap fixed pixel height for app wrapper with 100vh (helps on resize and smaller screens)
- enable scrolling on discovered robots list (when 7+ robots discovered on 1 network)
Check List:
@mcous can you confirm it scrolls with all office robots discovered?

V3a scrollable discovered robots list

---

compute/scripts/start.sh

Modify start script command arguments to aiohttp requirments

---

compute/scripts/start.sh

During boot, before advertising server, home the robot

Home robot on start of Docker container

---

api/opentrons/config/containers/default-containers.json

#457 
Saw this API config typo reported while looking through open issues. Very simple fix. Will be looking to contribute more in the future.
Check List:
- [no ] Are there breaking changes in the API and how are they being communicated?

Correct the total-liquid-volume in first well of e-gel container

---

app/ui/components/deck/LabwareItem.js
components/src/icons/icons.css

@mcous I just copy-pasted your suggestions
@Kadee80 will this work for your fancy new spinner?

(pd, app) Icon "spin" prop works in nested SVG

---

api/docs/source/templates/layout.html

This PR is super tiny, and is related #648. Our public facing docs are still generated from master so please note this PR both branches from and merges into master.
see #670, addresses first checklist item
- update `docs/source/templates/layout.html` jobs links to point to `http://opentrons.com/jobs`

Update jobs link in sphinx template

---

api/opentrons/cli/main.py

Changes deck points to the calibration points etched on the deck, to allow calibration comparisons to accumulate less error.
NOTE: This will not work on beta machines, only pp1 machines with the moved deck points

changes points to etched points on deck

---

Dockerfile
api/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/tests/opentrons/drivers/test_driver.py

Adds a method for parsing smoothieware's switch values, which includes endstop states and probe switch state.

Parse switch state

---

components/src/__tests__/__snapshots__/forms.test.js.snap
components/src/__tests__/forms.test.js
components/src/forms/DropdownField.js
components/src/forms/DropdownField.md

closes #714 
See component library for how DropdownField has changed (https://s3-us-west-2.amazonaws.com/opentrons-components/complib_dropdown-field-can-be-empty/index.html once build has finished)

(complib) DropdownField is empty with falsey "value"

---

components/src/__tests__/__snapshots__/structure.test.js.snap
components/src/__tests__/structure.test.js
components/src/structure/TitleBar.js
components/src/structure/TitleBar.md
components/src/structure/structure.css
components/styleguide.config.js

This PR adds a necessary component to the component library for #677
Review link: https://s3-us-west-2.amazonaws.com/opentrons-components/complib_top-bar-with-back/index.html#titlebar
- Added optional `onBackClick` prop to `TitleBar`
Nothing special

feat(complib): Add optional back button to TitleBar

---

api/opentrons/__init__.py
api/opentrons/data_storage/labware_definitions.py
api/opentrons/data_storage/serializers.py
api/tests/opentrons/database/test_database.py
api/tests/opentrons/database/test_labware_definitions.py
api/tests/opentrons/database/test_serializers.py

Update definition docs, add "labware" alias for "containers" at user-facing level, and add serializers/deserializers
Fixes #763 and fixes #765 
- (docs) Update labware definition docs
- (feature) Add serializers and deserializers for new data format
- (feature) Add "labware" alias for "containers" at user-facing level

Add serializers

---

Dockerfile
compute/conf/nginx.conf
compute/scripts/start.sh

Reverts Opentrons/opentrons#798
A transitive dependency of jupyter broke our build, so this will need to be re-added with some infrastructural modifications

Revert "Add jupyter server to robot"

---

api/tests/opentrons/database/test_labware_definitions.py
api/tests/opentrons/database/test_serializers.py
labware-definitions/definitions/GEB-tiprack-300ul.json
labware-definitions/definitions/tube-rack-5ml-96.json

Add the "tube-rack-5ml-96-beta-update" and "GEB-tiprack-300ul" labware definitions

Add labware definitions

---

api/opentrons/__init__.py
api/opentrons/api/calibration.py
api/opentrons/api/models.py
api/opentrons/api/session.py
api/opentrons/robot/robot_configs.py
api/opentrons/server/endpoints.py
api/opentrons/server/main.py
api/opentrons/server/rpc.py

I'm drowning in unreadable logs!
- api(chore): Set default log level to INFO and modify the levels of many log messages

Change default log level to info and adjust level of log statements

---

api/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/tests/opentrons/drivers/test_driver.py

This PR engages a plunger motor only if it is being moved. Previously, both plunger motors were being engaged if either one was moving, creating heat.

only engages the plunger that is being moved

---

Dockerfile
compute/conf/jupyter_notebook_config.py
compute/scripts/start.sh

Reverts Opentrons/opentrons#822
Serves jupyter notebook on all interfaces, port 48888. Data is stored under `/data/user_storage/opentrons_data/jupyter`

Revert "Revert "Add jupyter server to robot""

---

api/opentrons/config/feature_flags.py
api/opentrons/robot/robot.py
api/opentrons/robot/robot_configs.py

A small refactor of feature flag style, in preparation for future functional changes (immediately #764 )
- (feature) Modify style of feature flags for cleaner use (no functional changes)
- (chore) Remove broken/unsupported functions from `robot` or make minor fixes
- (docs) Remove out of date todo items

Revise format of feature flags and remove dead code and comments

---

api/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/opentrons/drivers/smoothie_drivers/serial_communication.py

Add debug logs to driver, to make serial communication bugs easier to debug (unticketed chore). No behavioral changes.
- (chore) Add debug log statements to driver

Add debug logs to driver

---

api/opentrons/deck_calibration/endpoints.py
api/opentrons/server/main.py
api/opentrons/util/calibration_functions.py
api/tests/opentrons/api/test_calibration.py

Multichannel models were colliding with the taller model of fixed trash. This PR fixes #1040.
- Refactor of 'probe_instrument' within calibration_functions
- Adds tests for functionality of creating hotspots
- Adds debug log statements for easier diagnosis of tip probe and/or offset bugs.

Api bug tall trash

---

api/Makefile

Add change pipette commands to api makefile
- (chore) Add change pipette commands to api makefile
Review this request by never having to pull the mounts down manually again

Add change pipette commands to api makefile

---

api/opentrons/server/endpoints/wifi.py
api/tests/opentrons/server/test_wifi_endpoints.py

Enable ssids with spaces, make psks optional, and refactor wifi endpoint testing. Fixes #1107 
- (feature) Support ssids with spaces and networks without passwords
- (refactor) Remove test code from production paths and use proper mocks
Independent verification on robots

SSIDs with spaces, networks without passwords, and better testing

---

api/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/tests/opentrons/drivers/test_driver.py
api/tests/opentrons/server/test_control_endpoints.py

Make pipette read methods in driver honor simulating mode
- (refactor) Make pipette read methods in driver return simulating responses

Make pipette read methods in driver honor simulating mode

---

api/opentrons/server/main.py

Home on server start
- (fix) Home on server start as a temporary solution until smart homing is done
Checked on 🌔 🌔

Home on server start as temporary fix

---

protocol-designer/src/components/SelectablePlate.js
protocol-designer/src/components/WellSelectionModal.js
protocol-designer/src/containers/ConnectedWellSelectionModal.js
protocol-designer/src/containers/SelectablePlate.js
protocol-designer/src/containers/WellSelectionInput.js
protocol-designer/src/labware-ingred/actions.js
protocol-designer/src/well-selection/actions.js
protocol-designer/src/well-selection/reducers.js
protocol-designer/src/well-selection/selectors.js
protocol-designer/src/well-selection/test/utils.test.js
protocol-designer/src/well-selection/utils.js

Closes #1229
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_well-selection-multichannel/index.html
Hopefully, no matter what well selection you make in any container, PD should now not crash or do anything absurd. If you try to use a multichannel with an incompatible labware like a tube rack, it will simply quietly not allow you to select any wells. The well selection is done geometrically from the labware definitions. Try a variety of containers and see if there are any conditions that it breaks in.
Exceptions are below.
And remember to include enough tip racks (running out of tips still whitescreens PD), and use transfer + consolidate steps only, others not supported.
* The input `WellSelectionInput` that you click on to open the modal doesn't show accurate number of …

Pd well selection multichannel

---

api/opentrons/tools/factory_test.py

Adds the newly required 3rd arg to `serial_communication.write_and_return`, the expected acknowledgement from Smoothieware (`b'ok\r\nok\r\n'`)

Fix: factory-test bug coming from refactor of write_and_return

---

api/opentrons/deck_calibration/endpoints.py
api/tests/opentrons/server/test_calibration_endpoints.py

This PR fixes a little typo in the DC endpoints
- fix(api): Add missing async to save_transform handler in DC
Standard review. Currently testing on Sunset

fix(api): Add missing async to save_transform handler in DC

---

api/opentrons/instruments/pipette_config.py

Removes accidental print statements left in when merging PR #1441

API: removes accidental print statements from PR 1441

---

api/docs/source/labware.rst
api/docs/source/pipettes.rst
api/docs/source/robot.rst
api/docs/source/writing.rst

This is part 2 in docs cleanup. First pass of fixing tests in pipettes.rst and documentation in writing.rst. Kinda getting the hang of sphinx now.
- Updated pipettes.rst to be in-line with updated API changes
- Changed writing.rst to reflect current standards using jupyter notebook
- Renamed containers.rst -> labware.rst
If you see any grammar mistakes or other things that should be included let me know!

Fixes docs in pipettes.rst, writing.rst

---

api/opentrons/api/session.py
api/opentrons/robot/robot_configs.py
api/opentrons/server/main.py
api/opentrons/server/rpc.py

Use config file setting instead of environment variables to set debug log level
- (refactor) Use config file value instead of environment variable to set server log level

refactor(api): Move log level configuration to json config file

---

api/docs/source/atomic commands.rst
api/docs/source/complex commands.rst
api/docs/source/examples.rst
api/docs/source/index.rst
api/docs/source/pipettes.rst
api/opentrons/robot/robot.py

Looks bigger than it is.
- Split out the pipettes.rst file into three components:
1. Pipette setup
2. Atomic functions (aspirate/dispense, mix etc)
3. Complex functions (transfer, distribute etc)
- Made a few text changes

Rename files and edit examples

---

api/opentrons/tools/write_pipette_memory.py

This PR updates the pipette eeprom-writing script to handle new v13 barcodes. This has been separated into a separate PR to expedite it's merging and getting it in the hands of production team.

API: pipette eeprom writing script to accept v13 versions

---

api/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/tests/opentrons/tools/test_qc_scripts.py

Adds a test for the pipette eeprom-writing script

Api: adds test pipette eeprom-writing tool

---

protocol-designer/src/steplist/reducers.js

Closes #964 
- actually remove deleted steps from `orderedSteps` reducer
- better handle undefined steps to avoid TypeError trying to access undefined (though undefined steps shouldn't be allowed to happen)
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_fix-delete-step-bug/index.html
- Deleting steps should no longer cause white screen, but instead just delete the step and its effects on the visual liquid tracking deck.
No "are you sure" modal, and no warning about effects of step deletion on later steps in this bug fix PR.

PD: fix Delete Step bug

---

protocol-designer/src/containers/Alerts.js
protocol-designer/src/containers/ConnectedStepItem.js
protocol-designer/src/file-data/selectors/commands.js
protocol-designer/src/file-data/selectors/fileCreator.js
protocol-designer/src/steplist/generateSubsteps.js
protocol-designer/src/top-selectors/substep-highlight.js
protocol-designer/src/top-selectors/substeps.js
protocol-designer/src/top-selectors/well-contents/index.js

Just cleanup to avoid having 2 very similar selectors
- Remove robotStateTimeline selector, use robotStateTimelineFull instead
- PD should work the same

remove robotStateTimeline selector, use robotStateTimelineFull

---

api/opentrons/config/__init__.py

If a USB drive ends up being mounted in read-only mode (cause still unknown), it currently causes the server to fail entirely. This puts protections around attempted writes in config management to allow the server to start in this scenario.
- fix(api): Handle OSErrors when a USB drive is mounted read-only

fix(api): Handle OSErrors when a USB drive is mounted read-only

---

api/docs/source/robot.rst
api/opentrons/instruments/pipette.py
api/opentrons/robot/robot.py

Update documentation for `robot.head_speed` and fix other typos, in response to user request (no issue filed).
- docs(api): Update documentation for `robot.head_speed` and fix other typos
Docs only changes, tested locally, should only need code review

docs(api): Update documentation for `robot.head_speed`

---

api/opentrons/server/main.py

feat(api): lock resin update on server start and unlock on exit
Fixes #1551
1. Create an application in resin on edge and move a robot into it
2. Start a long protocol on that robot
3. While that protocol is running, push an update into resin, it will interrupt the protocol
4. With this branch on the robot repeat 2 and 3 and it will not interrupt the protocol

feat(api): lock resin update on server start and unlock on exit

---

protocol-designer/src/components/labware/NameThisLabwareOverlay.js
protocol-designer/src/components/labware/labware.css

Closes #1531
- update style of name new labware overlay
Mostly a style review
https://s3-us-west-2.amazonaws.com/opentrons-protocol-designer/pd_restyle-name-labware-field-1531/index.html

feat(protocol-designer): update name new labware overlay style

---

api/opentrons/package.json
app-shell/package.json
app/package.json
components/package.json
package.json
protocol-designer/package.json
shared-data/package.json
webpack-config/package.json

chore(release): 3.1.0

---

api/opentrons/deck_calibration/dc_main.py

Deck calibration CLI tool now homes on start (required for accurate movement, shouldn't be up to user), has more debug logging, and makes a backup after completion (to match behavior of the UI tool). Closes #1556 which could not be reproduced.
- refactor(api): Improve logging and backup in deck calibration cli tool and add home
Reviewed on 🌔 🌔 with @sanni-t . Otherwise just needs general code review

refactor(api): Improve logging and backup in deck calibration cli tool and add home

---

api/opentrons/package.json
app-shell/package.json
app/package.json
components/package.json
package.json
protocol-designer/package.json
shared-data/package.json
webpack-config/package.json

Release Candidate for version `3.1.1`
https://github.com/Opentrons/opentrons/compare/v3.0.0...chore_release-3.1.1
RC review

chore(release): 3.1.1

---

components/src/alerts/alerts.css
components/src/styles/colors.css

Made warning ribbon title darker
Made all titles semibold
This should effect protocol designer and run app

components: made title bold and darker

---

api/opentrons/package.json
app-shell/package.json
app/package.json
components/package.json
package.json
protocol-designer/package.json
shared-data/package.json
webpack-config/package.json

Release Candidate for version `3.1.2`
https://github.com/Opentrons/opentrons/compare/v3.1.1...edge
RC review

chore(release): 3.1.2

---

components/src/alerts/alerts.css

Darkens the title text for info alerts
Title text is now selected-dark
Hope I did it right!

info title text is now selected-dark

---

protocol-designer/src/components/WellSelectionModal.css

Closes #1325
Increase the font size of the selected pipette in the well selection modal.
🐎

feat(protocol-designer): increase selected pipette font-size

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Version bump PR for `3.2.0-beta.0`
See [`CHANGELOG.md`](https://github.com/Opentrons/opentrons/blob/release_3.2.0-beta.0/CHANGELOG.md) (first new changelog generated by Lerna 🎉 )
Test as you would any other release

chore(release): 3.2.0-beta.0

---

api/opentrons/server/endpoints/serverlib_fallback.py

Add ignore update endpoint implementation to fallback file
- Add ignore update endpoint implementation to fallback file
Push this API update to a robot that does not have ot2serverlib installed

fix(api): Add ignore update endpoint implementation to fallback file

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

This PR creates version `3.2.0-beta.2`
* **api:** Sanitize wifi inputs to handle special characters ([#1743](https://github.com/Opentrons/opentrons/issues/1743)) ([18f8d0f](https://github.com/Opentrons/opentrons/commit/18f8d0f))
* **protocol-designer:** set max width of form field rows ([#1723](https://github.com/Opentrons/opentrons/issues/1723)) ([c3a0dc6](https://github.com/Opentrons/opentrons/commit/c3a0dc6)), closes [#1488](https://github.com/Opentrons/opentrons/issues/1488)
* **api:** Log API server and Smoothie FW versions on API server boot ([#1728](https://github.com/Opentrons/opentrons/issues/1728)) ([6c3c3c4](https://github.com/Opentrons/opentrons/commit/6c3c3c4)), closes [#1120](https://github.com/Opentrons/opentrons/issues/1120)
* **app:** Connect home button to API on robot …

chore(release): 3.2.0-beta.2

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

PR to bump to `3.2.0-beta.3`
https://github.com/Opentrons/opentrons/compare/v3.2.0-beta.2...126d57e1234e1a7667eb5a2416ed192a2b3c0a5a
* **api:** Fix row order in labware.create ([#1749](https://github.com/Opentrons/opentrons/issues/1749)) ([40ac527](https://github.com/Opentrons/opentrons/commit/40ac527)), closes [#1748](https://github.com/Opentrons/opentrons/issues/1748)
* **app:** Fix overlay and redirect duplication in robot settings page ([#1759](https://github.com/Opentrons/opentrons/issues/1759)) ([ce94b22](https://github.com/Opentrons/opentrons/commit/ce94b22))
* **components:** Resize main navbar and title bar to match designs ([#1757](https://github.com/Opentrons/opentrons/issues/1757)) ([4d46011](https://github.com/Opentrons/opentrons/commit/4d46011)), closes …

chore(release): 3.2.0-beta.3

---

CLA.txt
CONTRIBUTING.md
api-server-lib/README.md
api-server-lib/setup.py
api/Makefile
api/README.rst

Minor typo fixes found during update server work and add notes to developer instructions in readme and contributing docs
- docs(*): Minor typo fixes and add notes to developer instructions
No behavioral changes, please just look at the edits.

docs(*): Minor typo fixes and add notes to developer instructions

---

app/src/http-api-client/__tests__/modules.test.js
app/src/http-api-client/__tests__/reducer.test.js
app/src/http-api-client/actions.js
app/src/http-api-client/index.js
app/src/http-api-client/modules.js
app/src/http-api-client/reducer.js

This PR puts plumbing in place for #1735 to hit the endpoint described in #1831 
- feat(app): Add GET /modules to API client 
We've got pretty much nothing to test against with this PR, so please give the code a review and hopefully we won't have to fix too much up once we have API and UI in place

feat(app): Add GET /modules to API client

---

protocol-designer/src/components/IngredientsList.js

feat(protocol-designer): change edit labware nickname icon to pen

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

This PR bumps the version to `3.3.0-beta.0` for our next beta release.
https://github.com/Opentrons/opentrons/compare/v3.2.0-beta.3...d2195247d389fe2be64bc296d271038db9649d0b
* **api:** Allows floating-point temperatures to be set/read to/from temp-deck ([#1798](https://github.com/Opentrons/opentrons/issues/1798)) ([856134a](https://github.com/Opentrons/opentrons/commit/856134a))
* **api:** Fix QC script which uses 85% current to use default speeds for Y axis ([#1802](https://github.com/Opentrons/opentrons/issues/1802)) ([aa8a319](https://github.com/Opentrons/opentrons/commit/aa8a319))
* **api:** Remove incorrect call to `cache_instrument_models` ([#1810](https://github.com/Opentrons/opentrons/issues/1810)) ([2f80ece](https://github.com/Opentrons/opentrons/commit/2f80ece))
* **app:** Call …

chore(release): 3.3.0-beta.0

---

protocol-designer/src/containers/ConnectedSidebar.js
protocol-designer/src/containers/ConnectedTitleBar.js
protocol-designer/src/containers/TitleBar.css
protocol-designer/src/navigation/selectors.js

Closes #1502
- change text of well selection modal TitleBar and add back button
:school_satchel:

feat(protocol-designer): update well selection modal's TitleBar

---

protocol-designer/src/components/IngredientPropertiesForm.js
protocol-designer/src/components/IngredientsList.js

Closes #1864
Lil' copy change
:angel:

feat(protocol-designer): change copy ingredients -> liquid

---

protocol-designer/src/components/FileSidebar/FileSidebar.css
protocol-designer/src/components/FileSidebar/FileSidebar.js

Closes #1784
Just some text change and button re-ordering. Also cleaned up old css
-restyle file sidebar buttons
- buttons look like #1784

feat(protocol-designer): re-order and restyle file sidebar buttons

---

protocol-designer/src/file-data/selectors/commands.js

Closes #1706
To make StepCreators composable, and because they individually can't be aware of future steps, they always hang on to their tip at the end. However, this can cause liquids to drip while tips are needlessly carried over. Plus it looks really freaking weird. In practice, the only time tips shouldn't be dropped at the end of a step is if the next step for that pipette has "change tip: never" set -- this means "reuse tips from previous step with this pipette".
So this PR makes the `robotStateTimeline` selector look into the future, and drop tips at the end of each step unless they'll need to be carried over.
- drop tips eagerly at the end of each step unless the next step for a pipette uses change tip: "never"
Do you see any edge cases where this won't work right?
To see exactly …

feat(protocol-designer): make pipettes eagerly drop tips

---

api/opentrons/server/main.py

Adds a check for virtual smoothie before copying udev files to user_storage on server start
```server/main.py```

fix(api): check virtual smoothie before copying udev file to robot 

---

app/src/components/TempDeckStatusCard/index.js

This PR is a follow up to #1740. The TempDeckStatusCard now checks connected modules status at a 1 second interval.
feat(app): Add continuous polling to modules during run
Run app with modules enabled `OT_APP_MODULES=1 make dev`
uncomment lines 345-351 in `app/src/robot/api-client/client.js` 
comment out line 77 and uncomment lines 79-110 in `app/src/http-api-client/modules.js`

feat(app): Add continuous polling to modules during run

---

api/opentrons/api/session.py

Add clear method to RPC SessionManager for upload confirm modal in Run App

feat(api): Add clear method to RPC SessionManager

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

This PR bumps the version to `3.3.0-beta-1` for our next beta release.
https://github.com/Opentrons/opentrons/compare/v3.3.0-beta.0...a284e20
* **api:** check virtual smoothie before copying udev file on server start ([#1960](https://github.com/OpenTrons/opentrons/issues/1960)) ([9a31f3d](https://github.com/OpenTrons/opentrons/commit/9a31f3d))
* **api:** Fix pipette.delay() so it does not sleep during protocol simulation ([#1902](https://github.com/OpenTrons/opentrons/issues/1902)) ([f63bdba](https://github.com/OpenTrons/opentrons/commit/f63bdba))
* **api:** Fix the database migration script geometry logic ([#1959](https://github.com/OpenTrons/opentrons/issues/1959)) ([7ae9756](https://github.com/OpenTrons/opentrons/commit/7ae9756))
* **api:** Home Z axes before run to guarantee that …

chore(release): 3.3.0-beta.1

---

app/src/components/AppSettings/AppUpdateModal.js

Bug report and fix (typo noticed by @b-cooper)
- fix(app): Fix copy typos in update error modal 
Check for typos

fix(app): Fix copy typos in update error modal

---

protocol-designer/src/localization/en/alert.json

Does the new copy make sense?
Closes #2085

fix(protocol-designer): tweak timeline alert copy

---

CHANGELOG.md
api-server-lib/ot2serverlib/CHANGELOG.md
api-server-lib/ot2serverlib/package.json
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

[Changelog](https://github.com/Opentrons/opentrons/compare/v3.3.0-beta.1...0fb5b2d)

chore(release): 3.3.0

---

protocol-designer/src/tutorial/hintManifest.js

Reference the Starting Deck State in the add liquids to deck hint copy

fix(protocol-designer): Clarify the copy in the add liquids to deck hint

---

api/opentrons/api/session.py

The RPC session API has no protections against creating a new session while a session creation request is already in progress. Due to the robot singleton, this can result in two sessions simultaneously simulating and messing with the robot. This results in errors to the user at best, and at worst makes the robot start moving.
This PR adds a simple lock flag to only allow one session creation request at a time.
- fix(api): Prevent session creation while session creation already in progress

fix(api): Prevent session creation while creation already in progress

---

api/opentrons/server/endpoints/control.py
api/tests/opentrons/server/test_control_endpoints.py

The /home endpoint was correctly checking to see if an instrument was already loaded onto the
machine but was incorrectly just deleting whatever it had afterwards. Now it only deletes the
instrument if it actually created it.
This would then cause ugly tracebacks whenever the robot tried to move subsequently, since the instrument was no longer in the pose tree.
Previously, if you were in a calibration context and tried to change a pipette, after the pipette was changed (or not changed, or really just homed) further attempts to move the robot would get the following error in the resin console:
```
2018-08-22 19:38:42,669 opentrons.server.rpc ERROR [Line 282] Exception while getting line number:
Traceback (most recent call last):
File …
```

fix(api): Preserve preexisting instruments when homing

---

api/opentrons/instruments/pipette.py

Closes #2011 and #1951.
Problem: Multichannels moving to a trough did not handle edge case WellSeries. This caused misbehavior when transferring or distributing to more than one column. 
- Add logic in transfer plan to handle WellSeries edge cases for multichannel
Please test this code on your respective robots with at least one trough:
```
plate = labware.load('trough-12row', '5')
plate_in = labware.load('trough-12row', '2')
tiprack = labware.load('tiprack-200ul', '1')
p50 = instruments.P50_Multi(mount='right', tip_racks=[tiprack])
p50.pick_up_tip()
p50.distribute(5, plate_in.wells('A1'), plate.wells(), blow_out = True, new_tip='never')
p50.distribute(5, plate_in.wells('A2'), plate.cols('1', to='12'), blow_out = True, new_tip='never')
p50.return_tip()
```

fix(api): Fix WellSeries parsing for trough containers

---

components/src/buttons/Button.js
components/src/forms/CheckboxField.js
components/src/forms/FormGroup.js
components/src/tooltips/HoverTooltip.js
protocol-designer/src/components/StepEditForm/MixForm.js
protocol-designer/src/components/StepEditForm/StepFormField.js
protocol-designer/src/components/StepEditForm/TipPositionInput/index.js
protocol-designer/src/components/StepEditForm/TransferLikeForm.js
protocol-designer/src/components/StepEditForm/formFields.js
protocol-designer/src/components/StepEditForm/getTooltipForField.js
protocol-designer/src/localization/en/tooltip.json

Closes #1981 - impements tooltips for advanced settings (and Volume cuz why not)
- add tooltips for advanced settings
- :mount_fuji: :mouse2:

feat(protocol-designer): add tooltips for advanced settings

---

api/opentrons/config/containers/default-containers.json

Container offsets for biorad PCR plate + 10ul tiprack were slightly off pre-calibration.
- Change depth on 10ul rack + slight XY changes
- Change biorad PCR plate XY
Test on your own robot please!

fix(api): Fix container definitions of biorad PCR and 10ul tiprack

---

CHANGELOG.md
api/opentrons/CHANGELOG.md
api/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Beta Release to 3.3.1-beta.0
- Will need to fix my commit message when I squash merge

chore(release): 3.3.1-beta.0

---

api/docs/source/modules.rst

Updated the docs to reflect changes implemented in PR #2171 (add custom engage height and offset parameters)

docs(api): update magdeck engage() doc

---

CONTRIBUTING.md

Fixed typo in contributing document

docs(repo): correct typo in contributing guide

---

components/src/tooltips/HoverTooltip.js
components/src/tooltips/tooltips.css
protocol-designer/src/components/StepCreationButton.js

Clarify the target of hovered tooltips by adding an arrow.
Closes #2026
- all `HoverTooltip` instances have an arrow now

feat(protocol-designer): add dynamic tooltip arrow

---

protocol-designer/src/components/SettingsPage/Privacy.js
protocol-designer/src/components/modals/AnalyticsModal.js

Update the copy in the analytics disclaimer to accurately portray our data collection in beta.

fix(protocol-designer): tweak analytics copy for accuracy

---

api/opentrons/broker/broker.py
api/opentrons/config/__init__.py
api/opentrons/containers/placeable.py
api/opentrons/data_storage/labware_definitions.py
api/opentrons/data_storage/serializers.py
api/opentrons/deck_calibration/dc_main.py
api/opentrons/deck_calibration/endpoints.py
api/opentrons/deck_calibration/linal.py
api/opentrons/drivers/mag_deck/driver.py
api/opentrons/drivers/temp_deck/driver.py
api/opentrons/instruments/instrument.py
api/opentrons/robot/robot_configs.py
api/opentrons/util/calibration_functions.py
api/opentrons/util/environment.py

Fix as many mypy typing errors as possible without changing any behavior

chore(api): Fix some mypy typing errors

---

api/opentrons/hardware_control/__init__.py
api/opentrons/hardware_control/controller.py
api/opentrons/hardware_control/simulator.py
api/opentrons/types.py
api/tests/opentrons/hardware_control/test_moves.py

Adds the absolute movement and relative movement methods ( #2234)
* Added Point tuple and Axis enums
* Added smoothie driver to the controller
* Added move_to(), move_rel() and home() to controller & simulator
* Added tests

feat(api): add hardware control move_to(), move_rel()

---

api/Makefile
api/opentrons/broker/__init__.py
api/opentrons/commands/commands.py
api/opentrons/config/advanced_settings.py
api/opentrons/data_storage/database.py
api/opentrons/data_storage/old_container_loading.py
api/opentrons/data_storage/serializers.py
api/opentrons/drivers/__init__.py
api/opentrons/drivers/mag_deck/__init__.py
api/opentrons/drivers/mag_deck/driver.py
api/opentrons/drivers/temp_deck/__init__.py
api/opentrons/hardware_control/__init__.py
api/opentrons/helpers/__init__.py
api/opentrons/legacy_api/api.py
api/opentrons/protocol_api/__init__.py
api/opentrons/server/endpoints/serverlib_fallback.py
api/tests/opentrons/hardware_control/test_instantiation.py
api/tests/opentrons/hardware_control/test_instruments.py

This fixes all mypy diagnostic messages except those known to be addressed in an
upcoming PR.

chore(api): Fix more mypy type errors

---

api/opentrons/hardware_control/controller.py
api/tests/opentrons/drivers/module_drivers/test_temp_deck_driver.py

This PR
..updates imports to fix test errors in `hardware_control`
..makes changes to temp deck driver test to remove possibility of test failure due to scope and same name functions

test(api): fix test errors

---

api/src/opentrons/protocol_api/labware.py
api/src/opentrons/server/endpoints/settings.py
api/tests/opentrons/protocol_api/test_offsets.py

Add calibration clear for new labware calibration files to factory reset. Closes #2276
- feat(api): Factory reset clears new labware calibration files
The tests should cover this feature well. Please look over code and tests.

feat(api): Factory reset clears new labware calibration files

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
lerna.json
package.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

This release fixes a bug where the API server was not properly released because the path to its `package.json` changed.

Release 3.5.1

---

protocol-designer/src/steplist/reducers.js

feat(protocol-designer): collapse all step items on newly loaded file

---

protocol-designer/src/containers/ConnectedSidebar.js

Show Ingredients List while liquid placement modal is open.

fix(protocol-designer): fix sidebar for liquid placement modal

---

protocol-designer/src/constants.js
protocol-designer/src/localization/en/tooltip.json
protocol-designer/src/steplist/actions/handleFormChange.js
protocol-designer/src/steplist/formLevel/warnings.js

Closes #2749 - no more 20%!!
- Default and recommended disposal volume should default to the pipette minimum volume

feat(protocol-designer): use pipette min vol as default/recommended disposal volume

---

protocol-designer/src/steplist/formLevel/warnings.js

This PR serves as its own ticket. Creating a Distribute, cancelling it, and opening it again caused a whitescreen bug!
- try to break PD with adding steps, canceling them before they're saved, and opening again.

fix(protocol-designer): fix bug with null distribute step

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Update version numbers and changelogs for 3.6.4 rc, mostly due to updated p1000 aspirate function from @Carlos-fernandez .
https://github.com/Opentrons/opentrons/compare/v3.6.3...edge
changelog + release notes review

chore(release): v3.6.4

---

protocol-designer/src/components/LiquidPlacementModal.css
protocol-designer/src/components/LiquidPlacementModal.js

fix(protocol-designer): fix liquid placement modal overlay height

---

protocol-designer/src/labware-ingred/reducers/index.js

fix(protocol-designer): make rename labware set correct key

---

protocol-designer/src/step-generation/utils.js

this created an unintended breaking change for PD files in application-data, for no good reason! revert before doing a release (the change reverted in this PR has not been released yet)

fix(protocol-designer): revert changes to source_well / dest_well constants

---

api/src/opentrons/hardware_control/__init__.py

The plunger home does not need a move beforehand, that was based on an incorrect understanding of the system and leads to spurious hard limit errors.

fix(api): api2 should not move before homing plunger

---

protocol-designer/src/steplist/formLevel/errors.js

Quick copy change -- closes #2674

feat(protocol-designer): change pipette<>labware incompatible copy

---

protocol-designer/src/components/modals/FilePipettesModal/FilePipettesModal.css

fix for style regression in dropdown after step form updates

fix(protocol-designer): fix dropdown font-size for pipettes and tips

---

.travis.yml
api/Makefile

This should fix the travis deploy issues from being in the wrong directory.

fix(api): go to the right path for pypi deploy

---

.travis.yml
CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/build/release-notes.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Version bump PR for 3.7.0 release
See `CHANGELOG.md` and `app-shell/build/release-notes.md`
Please review release-notes!

chore(release): 3.7.0

---

app-shell/build/release-notes.md

PR updates release notes (again) for 3.7.0 for work completed this week.

docs(app-shell): Update release notes for latest 3.7.0 RC

---

protocol-designer/package.json
protocol-designer/src/file-data/selectors/fileCreator.js
protocol-designer/webpack.config.js
yarn.lock

Just cleanup: removes now-unused `git-describe` module

refactor(protocol-designer): remove now-unused git-describe dependency

---

protocol-designer/src/components/KnowledgeBaseLink/index.js
protocol-designer/src/steplist/formLevel/warnings.js

Closes #3130
The knowledge base link has changed, this updates the usage of it in PD

fix(protocol-designer): update disposal volume knowledge base link

---

protocol-designer/src/localization/en/tooltip.json

Fixes this ugliness which @howisthisnamenottakenyet pointed out: 
- :man_shrugging:

fix(protocol-designer): fix move liquid tooltip; remove old unused tooltips

---

protocol-designer/README.md

* add overview section
* update env vars
* add some more info for contributors
Anything important missing?

docs(protocol-designer): update README

---

app/src/components/ConfigurePipette/ConfigForm.js
app/src/components/ConfigurePipette/ConfigFormGroup.js
app/src/components/ConfigurePipette/FormButtonBar.js
app/src/components/ConfigurePipette/styles.css
app/src/components/modals/BottomButtonBar.js

This PR implements min/max field validations as well as plunger group validation.
closes #2942
- refactor(app): Add pipette config form validation

refactor(app): Add pipette config form validation

---

protocol-designer/src/load-file/migration/1_1_0.js

@b-cooper realized this was left in, but doesn't do anything :man_shrugging: 
- Nothing broke

refactor(protocol-designer): remove no-op 'changeVersion' fn

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/build/release-notes.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
labware-library/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Going to try the release process a bit differently this time, by doing our QA checks on (possibly increasing) alpha releases and doing a final patch release at the end (no tags until the end, though).
Please review changelogs for your components.

chore(release): 3.8.0-alpha.0

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/build/release-notes.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
labware-library/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

This is RC2 for 3.8.0. Please check changelogs, but the only change is the addition of two bugfix commits.

chore(release): 3.8.0-alpha.1

---

protocol-designer/src/labware-ingred/actions/actions.js
protocol-designer/src/labware-ingred/actions/thunks.js
protocol-designer/src/labware-ingred/utils.js
protocol-designer/src/step-forms/reducers/index.js

Prevent crashing associated with duplicating labware on an already full deck.
Closes #3254

fix(protocol-designer): don't create labware ids if can't create labware

---

api/src/opentrons/tools/write_pipette_memory.py
api/tests/opentrons/config/test_pipette_config.py
shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
shared-data/js/__tests__/pipettes.test.js
shared-data/robot-data/pipetteModelSpecs.json

This adds new pipette models both in pipetteModelSpecs and write_pipette_memory
for upcoming v1.5 model releases.

feat(api): Add support for (p300m,p50m,p10s,p1000s)v1.5

---

shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
shared-data/js/__tests__/pipettes.test.js
shared-data/robot-data/pipetteModelSpecs.json

Adds support for the p300s v1.5, with a different aspiration function.

feat(api): Add support for p300s v1.5

---

app/src/components/FileInfo/ProtocolModulesCard.js
app/src/components/InstrumentSettings/AttachedModulesCard.js
app/src/components/InstrumentSettings/ModulesCardContents.js
app/src/http-api-client/__tests__/modules.test.js
app/src/http-api-client/modules.js
app/src/robot/api-client/worker.js
app/src/robot/selectors.js
app/src/robot/test/selectors.test.js

This PR closes #3063 and enables TC modules in the File Info page when the feature flag is set. If not uploading a TC protocol file info page will not display required TC modules.
- refactor(app): Enable TC in file info page behind feature flag
- refactor(app): Move TC feature flag logic to `robot` and `http` module selectors
**IMPORTANT**
After testing the TC logic, please test attached modules card and file info with another module type attached / protocol uploaded.
- Turn API V2 feat flag on
`make -C app dev` with TC attached 
Upload working TC protocol:
```
def run(ctx):
plate = ctx.load_labware_by_name('generic_96_wellplate_380_ul', 2)
tiprack = ctx.load_labware_by_name('opentrons_96_tiprack_300_ul', 1)
thermocycler = ctx.load_module('thermocycler', 10)
tc_plate = …
```

refactor(app): Enable TC in file info page behind feature flag

---

labware-library/src/__mocks__/definitions.js
labware-library/src/components/LabwareList/NoResults.js
labware-library/src/components/LabwareList/__tests__/LabwareList.test.js
labware-library/src/components/LabwareList/__tests__/NoResults.test.js
labware-library/src/components/LabwareList/__tests__/__snapshots__/NoResults.test.js.snap
labware-library/src/components/LabwareList/index.js
labware-library/src/components/LabwareList/styles.css
labware-library/src/components/Sidebar/FilterCategory.js
labware-library/src/components/Sidebar/__tests__/__snapshots__/FilterCategory.test.js.snap
labware-library/src/components/Sidebar/styles.css

Closes #3080
- Add "No Results" message all labware hidden
<http://sandbox.labware.opentrons.com/lablib-no-results>

refactor(labware-library): Add "No Results" message if all labware hidden

---

shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
shared-data/robot-data/pipetteModelSpecs.json

Update P300M 1.5 pick up current to 0.9 A
closes #3343 
change requested by hardware team

feat(shared-data): update P300M 1.5 pick up current to 0.9 A

---

labware-library/src/definitions.js

Fixes JS typecheck failures in edge. Failure caused by merging #3354, which was not rebased over #3350, which had merged earlier and had made the definition of `Well` more strict

refactor(labware-library): Fix typecheck failures from stricter Well def

---

shared-data/js/__tests__/__snapshots__/pipettes.test.js.snap
shared-data/robot-data/pipetteModelSpecs.json

feat(api): Set P10M1.5 pick up increment to 3mm

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
labware-library/CHANGELOG.md
labware-library/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

New release to support opentrons tiprack 10ul that has been shipped out to customers.

chore(release): 3.8.3-alpha.0

---

api/src/opentrons/legacy_api/api.py
api/tests/opentrons/config/test_pipette_config.py
api/tests/opentrons/labware/test_pipette_constructors.py
shared-data/robot-data/pipetteModelSpecs.json

Add Pipette+ constructors 
closes #3406
Check constructor names

feat(api): add pipette plus constructors

---

protocol-designer/package.json

PD document title should be "Opentrons Protocol Designer BETA" not "Opentrons Protocol Designer Prototype"
This PR serves as it's own ticket

fix(protocol-designer): update document title to reflect project status

---

api/src/opentrons/legacy_api/robot/mover.py

This was actually just unacceptable

fix(api): Remove really slow logging

---

api/src/opentrons/legacy_api/api.py

Since we added an adapter to load apiv2 labware into apiv1, apiv1 falls back to
checking apiv2 if it can't find a labware name. If that labware still isn't
found (for instance, it's just mispelled) then the error message sent by the api
to the runapp is a FileNotFoundError involving the definitions2/ directory. This
leads the user (and support agents, and devs) to think the robot is on apiv2.
Instead, just catch FileNotFound at the top level of apiv1 and provide an
actually useful error message.
- Upload a protocol with a bad labware name and check that you get a nice error message
- Make sure we didn't break loading labware

fix(api): Don't talk about apiv2 if you can't find a labware

---

labware-library/src/components/App/styles.css
labware-library/src/components/LabwareDetails/Stats.js
labware-library/src/components/LabwareList/LabwareCard.js
labware-library/src/components/LabwareList/LoadName.js
labware-library/src/components/LabwareList/styles.css
labware-library/src/components/Nav/styles.css
labware-library/src/components/website-navigation/styles.css
labware-library/src/localization/en.js
labware-library/src/styles/breakpoints.css
labware-library/webpack.config.js
webpack-config/lib/base-config.js

Closes #3075. See ticket for acceptance criteria as well as **which items are not in scope for this ticket**.
- refactor(labware): Remove unnecessary information from labware cards
~**Question for UX**: The cards look really awkward in the 450 - 767 range. Should we add another breakpoint at 480?~ 480 BP added, takes card multi-column

refactor(labware): Remove unnecessary information from labware cards

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/build/release-notes.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
labware-library/CHANGELOG.md
labware-library/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Release to support new opentrons 1000ul and make certain pipette behaviors configurable.

chore(release): 3.9.0-alpha.0

---

CHANGELOG.md
api/src/opentrons/CHANGELOG.md
api/src/opentrons/package.json
app-shell/CHANGELOG.md
app-shell/build/release-notes.md
app-shell/package.json
app/CHANGELOG.md
app/package.json
components/CHANGELOG.md
components/package.json
discovery-client/CHANGELOG.md
discovery-client/package.json
labware-designer/CHANGELOG.md
labware-designer/package.json
labware-library/CHANGELOG.md
labware-library/package.json
lerna.json
protocol-designer/CHANGELOG.md
protocol-designer/package.json
protocol-library-kludge/CHANGELOG.md
protocol-library-kludge/package.json
shared-data/CHANGELOG.md
shared-data/package.json
update-server/otupdate/CHANGELOG.md
update-server/otupdate/package.json
webpack-config/CHANGELOG.md
webpack-config/package.json

Please review the release notes.

chore(release): 3.9.0

---

update-server/Makefile

Like https://github.com/Opentrons/opentrons/pull/3524 but for the update server

chore(update-server): Use npx shx not just shx in update server

---

shared-data/protocol/flowTypes/schemaV3.js
shared-data/protocol/schemas/3.json

add a type def!
* make flow def for json protocol v3
* remove unused definition in the v3 json protocol json schema
Matches JSON schema for v3 protocols?

feat(shared-data): make flow def for json protocol v3

---

protocol-designer/src/components/labware/SelectableLabware.js
protocol-designer/src/top-selectors/well-contents/index.js

Closes #3603
Check that bug reported in #3603 is fixed

fix(protocol-designer): fix bug with timeline idx out of range

---

protocol-designer/src/components/LabwareSelectionModal/styles.css

fix(protocol-designer): left-align labware text in labware selection modal

---

protocol-designer/src/components/EditableTextField.js
protocol-designer/src/components/editableTextField.css

fix(protocol-designer): keep edit nickname to one line

---

protocol-designer/src/components/LabwareSelectionModal/LabwareItem.js
protocol-designer/src/components/LabwareSelectionModal/LabwarePreview.js
protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.js
protocol-designer/src/components/LabwareSelectionModal/styles.css
protocol-designer/src/localization/en/modal.json

Closes #3657
See ticket for criteria & illustration.
NOTE: links will not work because labware library is not live yet!

feat(protocol-designer): add 'view measurements' link

---

api/src/opentrons/protocol_api/contexts.py
api/src/opentrons/protocol_api/geometry.py
api/tests/opentrons/protocol_api/test_context.py

Add ways to set the head speed of the robot from the protocol API.

feat(api): Add speed settings to apiv2

---

protocol-designer/src/components/modals/FileUploadMessageModal/FileUploadMessageModal.js
protocol-designer/src/components/modals/FileUploadMessageModal/modalContents.css
protocol-designer/src/components/modals/FileUploadMessageModal/modalContents.js
protocol-designer/src/components/modals/modal.css

Closes #3696
Open a v1 protocol, see modal. Modal looks OK and copy correct?

feat(protocol-designer): update migration modal copy

---

scripts/python_build_utils.py

Codebuild checks us out in detached HEAD which leads to versions in the
VERSIONS.json in buildroot builds having the opentrons api branch HEAD. This commit modifies the logic to get the branch to better handle the situation by asking git for all the named refs in the repo and finding any that point to the current detached HEAD, with a system of priority preferring tags, then edge, then non-edge branches.
You can see that this works by looking at https://opentrons-buildroot-ci.s3.amazonaws.com/306b4ed3-8407-4b74-aa71-69ca7767aa6c/opentrons-buildroot/VERSION.json which is the version file from a manually-started build with this branch.

chore(api): build: better logic to get git branch from detached HEAD

---

app/src/robot-api/resources/modules.js
app/src/robot-api/resources/pipettes.js

In order to prevent empty states upon arriving at module or instrument UIs, eagerly load them at the start of a session.
Closes #3844

fix(app): eagerly fetch modules and instruments on robot connect

---

app/src/components/nav-bar/NavButton.js

"PROTOCOL" nav button was disabled when connected to a robot
- "PROTOCOL" nav button correctly enabled/disabled
- ❗️

fix(app): fix protocol button

---

app/src/components/RobotSettings/AdvancedSettingsCard.js

This PR is the front-end counterpart to #3868. It adds an alert modal on a visit to the robot settings page of a robot that:
- Has a setting with the id `disableLogAggregation`
- That setting has a value of `null` (`None` in Python-land)
Closes #3867
- feat(app): Add robot logging opt-out alert

feat(app): Add robot logging opt-out alert

---

README.md

chore(test): dummy commit

---

protocol-designer/src/components/FileSidebar/FileSidebar.js

helps ameliorate #3998 by making JSON protocol files smaller
- PD saves protocol files as minified JSON

feat(protocol-designer): output minified json

---

labware-library/src/labware-creator/components/importLabware.css
labware-library/src/labware-creator/styles.css

This PR serves as its own ticket as well. Based on some in person/doc design feedback - this PR updates some styling for the landing content.
- refactor(labware-creator): Implement UX feedback
http://sandbox.labware.opentrons.com/lc_design-tweaks/create/ (not built yet)
- Decrease space between title button and first paragraph text
- Add numbers to ordered list
- Increase indent for `ol`
- decrease spacing between `li`
- I also noticed that the upload button and dropzone did not align vertically on the right side, fixed that

refactor(labware-creator): Implement UX feedback

---

protocol-designer/webpack.config.js

bump to 3.0.4 before tagging & QA

chore(protocol-designer): bump to 3.0.4

---

protocol-designer/webpack.config.js

Bump PD internal version in prep for release

chore(protocol-designer): bump to 3.0.5

---

api/Pipfile
api/Pipfile.lock
api/src/opentrons/commands/commands.py
api/src/opentrons/drivers/smoothie_drivers/driver_3_0.py
api/src/opentrons/hardware_control/socket_server.py
api/src/opentrons/legacy_api/protocols/execute_v3.py
update-server/Pipfile
update-server/Pipfile.lock
update-server/otupdate/buildroot/file_actions.py
update-server/otupdate/buildroot/name_management.py
update-server/otupdate/migration/file_actions.py

This release adds support for checking string formatting!
Also fixes up some of the newly-caught errors!

chore(api, update-server): bumpy mypy to 0.740

---

app-shell/build/release-notes.md

It was in there twice in the release notes

chore(app-shell): we only need to mention 10.9 incompatibility once

---

components/src/instrument/PipetteSelect.css
components/src/instrument/PipetteSelect.js
protocol-designer/src/components/modals/FilePipettesModal/PipetteFields.js
protocol-designer/src/feature-flags/reducers.js
protocol-designer/src/feature-flags/selectors.js
protocol-designer/src/feature-flags/types.js
protocol-designer/src/localization/en/feature_flags.json

Remove feature flag blocking GEN2 pipettes in select and blacklist multis.
Closes #4295
Make a protocol with GEN2 singles.

feat(protocol-designer): expose GEN2 pipettes in pipette select

---

protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.js

refactor(protocol-designer): remove old stray log

---

shared-data/pipette/definitions/pipetteModelSpecs.json
shared-data/pipette/definitions/pipetteNameSpecs.json

refactor(shared-data): gen2 multi dvt config changes

---

.eslintrc.js
app/src/components/ChangePipette/PipetteSelection.js
app/src/config/index.js
app/src/config/types.js

Add feature flag to allow usage of Multi GEN2 pipettes in the app.
turn feature flag on, and attempt to attach a multi from the drop down.

chore(app): create ff for exposing multi GEN2 pipettes

---

api/src/opentrons/api/session.py

The RPC scrapes labware from commands and has special handling for getting a
labware object to later reflect so the app knows what to calibrate. We needed
handling for the legacy labware types.
Upload a protocol like this under v1 backcompat:
```python
from opentrons import labware, instruments, robot
tiprack = labware.load('opentrons-tiprack-300ul', '1')
#tiprack2 = labware.load('opentrons-tiprack-300ul', '4')
trough = labware.load('usascientific_12_reservoir_22ml','2')
plate = labware.load('corning_96_wellplate_360ul_flat', '3')
pip = instruments.P300_Single(mount='right', tip_racks=[tiprack])
#pip_multi = instruments.P300_Multi('left',tip_racks=[tiprack2])
pip.pick_up_tip(tiprack[0])
pip.aspirate(50, trough.wells('A1'))
pip.dispense(50, plate.wells('A1'))
pip.drop_tip()
```
The …

fix(api): add handling for legacy(location,well,labware) in rpc

---

api/src/opentrons/protocol_api/contexts.py

fix(api): wrap modules hc instance in sync adapter on load

---

api/docs/v2/new_modules.rst

Clarify block max volume for temperature commands and polish tc language.

docs(api): clean up tc language

---

api/release-notes.md
app-shell/build/release-notes.md

Modify release notes based on feedback from @umbhau.

chore(release-notes): Elaborate on new features in release notes

---

protocol-designer/src/components/KnowledgeBaseLink/index.js

closes #4324
- code review, double check link in PD

feat(protocol-designer): update recommended labware article link

---

api/src/opentrons/deck_calibration/__init__.py
api/src/opentrons/deck_calibration/dc_main.py

Closes #4519. 
- remove all instances of v2 feature flag check in deck cal CLI
- get rid of unused functions that were required for v1 api server.
Sanity check on a robot

refactor(api): Remove instances of apiv2 feature flag for deck cal CLI

---

.gitignore
labware-library/src/labware-creator/labwareTestProtocol.js

change test labware test protocol to use api v2
closes #4539

feat(labware-library): change test protocol to api v2

---

app/src/components/Resources/index.js

Make sure it renders and the link clicks

feat(app): add link to docs in resources card

---

api/src/opentrons/api/session.py

If the last command in a protocol is a pause (or not necessarily the last
command, but with nothing that will actually pause in between it and the end of
the protocol) then the protocol will finish and the session will broadcast a
"finished" state, but will issue a home at the end of the protocol which will...
be paused. The app doesn't know because the session says it's finished, so the
app will never either automatically resume or present the option to resume, and
the only way out is to restart your robot.
Instead, at the end of a `run`, if the protocol is in a paused state, just wait.
This lets the app see the state and present the appropriate action to the user.
If the user resumes, the wait ends and we go on to end of protocol behavior. If
the user cancels, the smoothie is hard reset …

fix(api): special case pause at end of protocol

---

api/src/opentrons/protocol_api/contexts.py

Closes #4613 
*Review Requests*

fix(api): fix temp connect to attached modules during lw calibration

---

labware-library/src/labware-creator/labwareTestProtocol.js

add decks 1 and 7 to labwareTestProtocol before labware test
closes #4451 
-->

feat(labware-library): add decks 1 and 7 to labwareTestProtocol before labware test

---

.flowconfig
protocol-designer/package.json
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/dispenseUpdateLiquidState.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forAspirate.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forBlowout.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forDispense.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forDropTip.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/forPickUpTip.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/index.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/magnetUpdates.js
protocol-designer/src/step-generation/test-with-flow/dispenseUpdateLiquidState.test.js
protocol-designer/src/step-generation/test-with-flow/fixtures/robotStateFixtures.js
protocol-designer/src/step-generation/test-with-flow/forAspirate.test.js
protocol-designer/src/step-generation/test-with-flow/forBlowout.test.js
protocol-designer/src/step-generation/test-with-flow/forDropTip.test.js
protocol-designer/src/step-generation/test-with-flow/forPickUpTip.test.js
protocol-designer/src/step-generation/test-with-flow/updateMagneticModule.test.js
protocol-designer/src/step-generation/test-with-flow/utils/index.js
protocol-designer/src/step-generation/test-with-flow/utils/makeImmutableStateUpdater.js
protocol-designer/src/ui/steps/reducers.js
shared-data/protocol/flowTypes/schemaV4.js
yarn.lock

related to issue #4697
- Added immer package
- Switched step generation to use immer
Please generate a few protocols and make sure the step generation looks correct.

feat(protocol-designer): use immer in step generation

---

NOTICE

This PR makes the copyright status of this repository slightly more explicit. 
Closes #4807. See issue for details and discussion
- docs(repo): add NOTICE file with copyright and warranty statements

docs(repo): add NOTICE file with copyright and warranty statements

---

protocol-designer/src/components/DeckSetup/getModuleVizDims.js
protocol-designer/src/components/modals/EditModulesModal/index.js
protocol-designer/src/constants.js
protocol-designer/src/file-data/selectors/fileCreator.js
protocol-designer/src/step-forms/reducers/index.js
protocol-designer/src/step-generation/commandCreators/atomic/deactivateTemperature.js
protocol-designer/src/step-generation/commandCreators/atomic/setTemperature.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/index.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/magnetUpdates.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/temperatureUpdates.js
protocol-designer/src/step-generation/test-with-flow/deactivateTemperature.test.js
protocol-designer/src/step-generation/test-with-flow/setTemperature.test.js
protocol-designer/src/step-generation/types.js
shared-data/js/__tests__/protocolSchemaV4.test.js
shared-data/js/constants.js
shared-data/js/modules.js
shared-data/js/types.js
shared-data/module/definitions/2.json
shared-data/module/schemas/2.json
shared-data/protocol/fixtures/4/simpleV4.json
shared-data/protocol/fixtures/4/testMagneticModuleV4.json
shared-data/protocol/fixtures/4/testTemperatureModuleV4.json
shared-data/protocol/fixtures/futureproofV4.json
shared-data/protocol/flowTypes/schemaV4.js
shared-data/protocol/schemas/4.json

See the RFC #4836 for all the context - this PR is the code attached to that RFC. (Closes #4836)
PS you can definitely ignore the PD-specific changes if you're not 🕷 - the Flow type def and matching JSON schema def is the important stuff.
- Please review the RFC and make sure that this JSON schema defines everything we need to adequately support modules (mag, temp and TC!) in JSON protocols
- Check out the new v4 protocol fixtures (they're big but if you ignore the `labwareDefinitions` key, they should be very manageable)
- Check out the v4 tests
- PD people: please code review PD changes. Should just be a refactor and some renaming to match the schema

feat(shared-data): new v4 JSON protocol schema

---

protocol-designer/src/components/DeckSetup/ModuleTag.js
protocol-designer/src/components/DeckSetup/__tests__/ModuleTag.test.js
protocol-designer/src/localization/en/modules.json
protocol-designer/src/step-generation/commandCreators/atomic/awaitTemperature.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/magnetUpdates.js
protocol-designer/src/step-generation/getNextRobotStateAndWarnings/temperatureUpdates.js
protocol-designer/src/step-generation/robotStateSelectors.js
protocol-designer/src/step-generation/test-with-flow/awaitTemperature.test.js
protocol-designer/src/step-generation/test-with-flow/robotStateSelectors.test.js
protocol-designer/src/step-generation/utils/misc.js

Show temperature module status on the deck
closes #4308 
- Add tempdeck to ModuleStatus
- Changed tag width based on meeting with Morgan
- @IanLondon - As requested, I added changes from a [previous](https://github.com/Opentrons/opentrons/pull/4865) PR here
http://sandbox.designer.opentrons.com/pd_temp-status/
**Module at the start of a protocol**
1. Create a new protocol with a temperature module.
2. Add any step
3. Hovering over the step should show "Deactivated" on the tag
4. Add a temperature step and set a target
3. Hovering over the temperature step should still show "Deactivated" on the deck
**Module is going from a disabled temp to a set temp**
1. Create a new protocol with a temperature module.
2. Add a temperature step and set a target
3. Hovering over the temperature step …

 feat(protocol-designer): display temperature status on deck

---

protocol-designer/src/ui/steps/actions/__tests__/actions.test.js

Fixes failing action test `protocol-designer/src/ui/steps/actions/__tests__/actions.test.js`

fix(protocol-designer): fix failing action test

---

.eslintrc.js
Makefile
protocol-library-kludge/src/App.js
protocol-library-kludge/src/URLDeck.js
shared-data/js/__tests__/labwareDefSchemaV1.test.js
shared-data/js/helpers/getWellTotalVolume.js
shared-data/js/helpers/index.js
shared-data/js/helpers/wellIsRect.js
shared-data/js/schema.js

Closes #4830!
- refactor(js): remove remaining default exports and adjust lint config
Smoke tests but sanity checks of the code

refactor(js): remove remaining default exports and adjust lint config

---

protocol-designer/src/localization/en/form.json

closes #5111 - shortens deactivate temperature module text 
- fix(protocol-designer): Update temperature modules disengage text

fix(protocol-designer): Update temperature modules disengage text

---

robot-server/robot_server/service/models/networking.py
robot-server/robot_server/service/models/settings.py
robot-server/robot_server/service/routers/control.py
robot-server/robot_server/service/routers/networking.py
robot-server/robot_server/service/routers/settings.py

More prep for porting api from aiohttp to fastapi

feat(robot_server): add missing endpoints to robot_server from api

---

.github/PULL_REQUEST_TEMPLATE.md

In a risk assessment, you go over your change set and identify other
areas of the system it might touch. Particularly important in a broad
and connected system, this process both gets the person submitting the
PR to consider the impact of their changes and points testers and
reviewers in the right direction.

chore: add risk assessment field to pr template

---

shared-data/protocol/schemas/4.json

Closes #5227
Just JSON schema documentation update
Description is clear enough?
no risks

docs(shared-data): update v4 protocol schema - engageHeight description

---

api/src/opentrons/protocol_api/module_contexts.py

closes #5214, closes #5215 
Since the Gen1 and Gen2 magnetic modules are using different steps/mm values, the engage heights baked in labware definitions would need to be handled differently:
Case 1: Gen1 Magnetic Module + non-standard labware**: double the engage height
Case 2: Gen2 Magnetic Module + standard labware**: halve the engage height
If neither of these cases are true, the engage height will remain unchanged.
** Standard labware: 
- Biorad 96 well 200 uL PCR plate
- NEST 96 well 100 uL PCR plate
- USA Scientific 96 well 2.4 mL plate
Requires changes in #5244 + Opentrons/opentrons-modules/pull/114 to test
- make sure engage heights are correct during protocol run and simulation
Low risk since it's only affecting the magdeck engage height for APIVersion 2.3 or above

refactor(api): use different engage heights for GEN1 and GEN2 modules

---

protocol-designer/src/step-forms/reducers/index.js
protocol-designer/src/step-forms/selectors/index.js
protocol-designer/src/step-forms/test/reducers.test.js

Closes #5232
Note that when the module is GEN1, engageHeight units are in "short mm" = 0.5mm. The 96 NEST skirted plate has a default of 12 GEN1 units = 6 GEN2 units.
Create some steps, including Magnet > Engage steps.
just PD engageHeight

feat(protocol-designer): preserve engage heights if already default

---

protocol-designer/src/__tests__/persist.test.js

`protocol-designer/src/__tests__/persist.test.js` added mock implementations to `Storage.prototype.getItem` and `setItem`. These mock implementations were not cleaned up, which would cause other tests to fail if the Jest environment / worker happened to be re-used for another test that interacted with localStorage
**Note**: There are places in PD were localStorage is accessed directly instead of going through the tested wrapper. This is dangerous and should be fixed.
- Ensured mocks were actually cleaned up
- Removed reliance on mocks for greenfield tests in favor of checking localStorage directly
- JSDOM has a localStorage implementation, so there was no need to mock in these tests except to simulate errors
- Test changes look good and you don't get flaky failures in tests unrelated to …

test(protocol-designer): fix leaky localStorage mocks

---

protocol-designer/src/components/KnowledgeBaseLink/index.js
protocol-designer/src/components/modals/EditModulesModal/MagneticModuleWarningModalContent.js

This PR closes #4952
- chore(protocol-designer): Update knowledgebase links
Please double check all 3 links listed in the ticket.
Low PD only link changes.

chore(protocol-designer): Update knowledgebase links

---

protocol-designer/src/components/modals/AnnouncementModal/announcements.js

Forgot to remove my comment to add a support link on PR #5345 🤦🏽‍♂️ 
None, just removing a comment

feat(protocol-designer): remove add support link comment

---

protocol-designer/src/step-forms/reducers/index.js
protocol-designer/src/step-forms/test/reducers.test.js

closes #5384
1. Moving an empty module to a compatible labware: place module under labware
2. Moving an empty module to an incompatible labware: swap module and labware
3. Moving an occupied module to any labware (Module in slot 1 has labware A. User moves modules to slot 3 with labware B): module holds on to its labware A and both go to slot 3, and labware B moves to slot 1
4-6: toggling "Disable module restrictions" feature should not affect this
PD only

feat(protocol-designer): allow moving empty module under compat labware

---

package.json

Add robot-server to package.json so lerna updates version and change log.
Tested locally.

fix(robot-server): add robot-server to monorepo's package.json

---

protocol-designer/src/components/modals/AutoAddPauseUntilTempStepModal.js
protocol-designer/src/localization/en/modal.json

Copy change to pause unti temp modal
Closes #5432
Low, just copy change in PD

feat(protocol-designer): update pause until temp modal copy

---

api/src/opentrons/protocol_api/geometry.py

Reverts Opentrons/opentrons#5532

refactor(api): Remove touch tip fix from edge

---

robot-server/tests/integration/test_identify.tavern.yaml
robot-server/tests/integration/test_robot.tavern.yaml

A quick one for your afternoon. This PR adds tests for the following endpoints:
- `/identify`
- `/robot/positions`
- `/robot/move`
- `/robot/home`
- `/robot/lights` (GET and POST)
Test coverage and structure
Nada

test(robot-server): Add integration tests for robot endpoints

---

robot-server/tests/integration/test_motors.tavern.yaml
robot-server/tests/integration/test_pipettes.tavern.yaml

Another quick one, adds simple tests for `/pipettes` and the two `/motors` endpoints.
- Adds integrations tests for pipettes and motors
Test coverage
None

test(robot-server): Add tests for pipettes and motors endpoints

---

api/docs/v2/index.rst

Per conversation we had in slack, the way we previously ordered the sidebar was not reflective of how we suggest to organize a protocol. Reordered it to match the `How it's Organized` section
Moved the labware and modules section about the pipette section

docs(api): Reordered navigation sidebar

---

robot-server/robot_server/service/session/command_execution/hardware_executor.py

Feature added in a recent PR was not a conflict with edge but broke a feature in edge. 
Specifically, I removed `complete_command` which was used by hardware executor in edge. 
Update hardware executor to use `duration` and not use the removed `complete_command`
None

fix(robot-server): fix a merge race condition.

---

app/src/components/Resources/index.js

The support center has been re-organized. This PR addresses that by linking to the root page.
Make sure this links to the main page of the support center
Low risk!

fix(app): update link to support center

---

components/README.md

This PR fixes a broken link in the readme
Example changelog:
- Fixed broken link

docs: fix broken link

---

api/README.rst

This PR is used to fix inline text highlighting

chore(api): fix inline text highlighting in api/readme.rst

---

api/src/opentrons/protocol_api/protocol_context.py

Hello 👋  just fixes a quick typo

fix: typo "protoocl"

---

app/src/components/ModuleControls/TemperatureControl.js
app/src/components/ModuleControls/index.js
app/src/components/ModuleLiveStatusCards/ThermocyclerCard.js

Closes #6086
- Rename "base" to "block" re TC
Update "base" -> "block" in the run app
Locations:
Low, just a copy change

feat(app): rename base -> block for TC copy

---

robot-server/robot_server/service/session/command_execution/command.py
robot-server/robot_server/service/session/manager.py
robot-server/robot_server/service/session/models/command.py
robot-server/robot_server/service/session/models/session.py
robot-server/robot_server/service/session/session_types/live_protocol/command_executor.py
robot-server/robot_server/service/session/session_types/live_protocol/command_interface.py
robot-server/robot_server/service/session/session_types/live_protocol/session.py
robot-server/robot_server/service/session/session_types/live_protocol/state_store.py
robot-server/tests/integration/sessions/test_live_protocol.tavern.yaml
robot-server/tests/service/session/session_types/live_protocol/test_command_executor.py
robot-server/tests/service/session/session_types/live_protocol/test_state_store.py

Next steps in epic for a live protocol session. Goal is to implement commands in HTTP for completing the basic pipetting protocol. 
- A `StateStore`. Currently just for the live protocol commands.
- A `CommandInterface` for implementing the commands. 
- Create a command executor for live protocol sessions. 
- It routes commands to the correct handler in `CommandInterface`.
- It calls `StateStore` to save command and result.
Nothing specific. This is still a work progress feature.
None. This doesn't do anything yet. 
closes #6559

feat(robot-server): http basic pipetting session - command routing and state store

---

.github/actions/python/setup/action.yaml
.github/workflows/notify-server-lint-test.yaml
notify-server/Makefile
notify-server/mypy.ini
notify-server/notify_server/__init__.py
notify-server/notify_server/main.py
notify-server/notify_server/package.json
notify-server/poetry.lock
notify-server/pyproject.toml
notify-server/tests/__init__.py
notify-server/tests/test_notify_server.py
package.json
scripts/python.mk
scripts/python_build_utils.py

Adding requirements for running CI
closes #6752 
See inline questions.
None

chore: notify server ci

---

app-shell/src/buildroot/index.js

There was a very simple bug causing problems with the update manifest caching introduced in #6494 for fresh installations of the app, because the call to ensure the directory existed was happening _after_ the manifest was downloaded.
Fixes #6786
- fix(app-shell): ensure robot updates folder exists before caching manifest
Smoke test:
Medium, for the same reason this is a high severity bug

fix(app-shell): ensure robot updates folder exists before caching manifest
